### ISSUE TITLE
Newer, better "deploy" CLI implementation

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1]
Requirements:

- deprecate the existing `deploy` CLI verb
  - we retain the verb indefinitely, but we mark it as deprecated
- add a new CLI verb handler to implement cluster creation

**Comment by posix4e** [comment]
Can we close this?

**Comment by jackfrancis** [comment]
@posix4e I think enough time has expired that suggests `deploy` is in fact the preferred verb, so I'll close it.
