### ISSUE TITLE
CIS 4.1.2 Ensure auditd service is enabled

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#1008]
# 4.1.1.1 Ensure audit log storage size is configured (Not Scored)
# 4.1.2 Ensure auditd service is enabled (Scored)

apt_package 'auditd' do
  action :install
end

cookbook_file 'Set /etc/audit/auditd.conf' do
  path '/etc/audit/auditd.conf'
  source 'etc/audit/auditd.conf'
  mode '0640'
end

**Comment by jackfrancis** [comment]
We will enable this via an api model option `auditDEnabled` in both the `masterProfile` and items in the `agentPoolProfiles` configuration array.
