### ISSUE TITLE
Switch default Linux distro to Ubuntu 18.04-LTS

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#1025]
Currently blocked on two separate issues: https://github.com/Azure/aks-engine/issues/761 for non-VHD (`ubuntu-18.04` distro) scenarios and https://github.com/Azure/aks-engine/issues/875 for Azure CNI scenario (which is the default networkPlugin).

**Comment by Guilhermeslucas** [comment]
This looks like a nice issue! I want to give it a try during next week :)

**Comment by CecileRobertMichon** [comment]
@Guilhermeslucas this is already in progress but we're waiting on the Azure CNI team for a new release to unblock us. I recommend you look at issues with the `good first issue` label if you're looking for good issues to tackle.

**Comment by Guilhermeslucas** [comment]
Thanks for answering, Cecile :)

**Comment by CecileRobertMichon** [comment]
new blocker: https://github.com/Azure/aks-engine/issues/1306

**Comment by CecileRobertMichon** [comment]
keep open

**Comment by msaurabhee** [comment]
Shall we move to 20.04 directly now. No point in being 2 years behind.

**Comment by alexeldeib** [comment]
doesn't seem like azure has 20.04 available yet? I did an `az vm image list --all --publisher Canonical` and found 12.04 up to 19.10.

**Comment by matthiaswenz** [comment]
@alexeldeib  I suspect switching to 20.04 would be looking forward unless we're considering pre-release software. Ubuntu 20.04 LTS is currently planned to be released 04/23/2020.

**Comment by alexeldeib** [comment]
Not by default, of course :) azure publishes lots of different builds, I was curious if maybe there was a nightly build of 20.04 (the official docker releases already have focal for example).

**Comment by iharrington** [comment]
Any Update on this? It seems both issues noted by @CecileRobertMichon as blockers have been resolved > https://github.com/Azure/aks-engine/pull/1192 & https://github.com/Azure/aks-engine/pull/884 I tried to review roadmap and can't seem to locate any additional info or a date when this will be available, thanks in advance!

**Comment by CecileRobertMichon** [comment]
@iharrington the current blocker is https://github.com/Azure/aks-engine/issues/1306 (see my comment above)

**Comment by DanRigby** [comment]
With #1306 being fixed by @jackfrancis, are there any remaining blockers for switching to Ubuntu 18.04-LTS?

**Comment by jackfrancis** [comment]
Hi @DanRigby That was the only blocker. Now to just get some mileage on it. Practically speaking setting it to default only means we'll test it more broadly, more common, but it doesn't prevent someone like yourself from building clusters with it right now. :) All our data suggest a running 18.04-LTS-backed cluster is production ready.

**Comment by iharrington** [comment]
Is there a roadmap or somewhere we can check the status of this becoming available for aks?

**Comment by CecileRobertMichon** [comment]
@iharrington you can check the AKS equivalent issue [here](https://github.com/Azure/AKS/issues/1487)

**Comment by mjsabby** [comment]
Does it make sense to move to Ubuntu 20.04 now?

**Comment by jackfrancis** [comment]
#3070 changed the default Linux distro to 18.04-LTS

@mjsabby we wouldn't consider changing the default Ubuntu distro for quite a while. If you'd like to track the introduction of that as a configurable option, please file an issue. Thanks!
