### ISSUE TITLE
Aks-engine 1.13 with hyper-v isolation container os does not match

### ISSUE THREAD

**Issue by digeler** [Azure/aks-engine#1029]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):No

---

**What version of aks-engine?**:latest

---

**Kubernetes version**: 1.13

**What happened**: we used this template : https://github.com/Azure/aks-engine/blob/master/examples/windows/kubernetes-hyperv.json
and we get the following error : 

Error: failed to start container "alerting-eventhub": Error response from daemon: CreateComputeSystem alerting-eventhub: The container operating system does not match the host operating system.
(extra info: {"SystemType":"Container","Name":"alerting-eventhub","Owner":"docker","VolumePath":"\\\\?\\Volume{09eeb0a6-5c58-11e9-b122-a1294e7ad2c8}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\alerting-eventhub","Layers":[{"ID":"2829226a-ab84-514a-97b8-4be31a7ab1a1","Path":"C:\\ProgramData\\docker\\windowsfilter\\78fb9ce6ce02c193b23d3c10a8aeb89a77c4223a04589e6b1dd3a44cb0261ccf"},{"ID":"5026f2bf-5cf7-5a5d-bc10-74a2ab70d929","Path":"C:\\ProgramData\\docker\\windowsfilter\\1f9fba9dc031fee34c1b89de631f8c81d548f16704721910911a9b320ee89afa"},{"ID":"bdd23e03-0313-5857-afc3-66f364b4e89e","Path":"C:\\ProgramData\\docker\\windowsfilter\\d5c1158dff925a869856e38ba41fa27d60bb7c9933bd2ecdb6349391c3cf6ff6"},{"ID":"e67806ed-4465-52df-8e1a-27ab95ddb61a","Path":"C:\\ProgramData\\docker\\windowsfilter\\0237266e311aa11ccfde19cbec01841080468e26f19bfbf6f944f6fb31655940"},{"ID":"708ec319-7618-55db-935d-7ff7b4f5c328","Path":"C:\\ProgramData\\docker\\windowsfilter\\d875eadff908030cd04a42c55ea3ff67dc4fbfd01d66a44fffb04c451fc3f515"},{"ID":"60d0f1d0-9cc7-5b04-9553-893023ff4d28","Path":"C:\\ProgramData\\docker\\windowsfilter\\2891e836ce40fe37a6b7ff7d23170de19744b167cdcbe54414c3b23b25c2c03a"},{"ID":"d5613eea-f023-5f4c-b003-6ce240092f06","Path":"C:\\ProgramData\\docker\\windowsfilter\\176b76068da154387f72029e5f1bb68dae0c6b2775277ca3538dcf84ce6458e4"},{"ID":"e2f2cda9-aa6f-517e-bf2e-45c5b5627b4c","Path":"C:\\ProgramData\\docker\\windowsfilter\\6d5531d41be675673cb387d23d3a3a84802143b4e0e29426e404ca36b19b0b01"},{"ID":"94cedc5e-e1d3-5e5d-876a-5821bdcf5475","Path":"C:\\ProgramData\\docker\\windowsfilter\\0199ae9ac6708cd7cc0875a322de22a72f8a524f7935bfc3368945113cdd410b"},{"ID":"592ad116-76d6-59dd-8a25-ad4e67dfbc42","Path":"C:\\ProgramData\\docker\\windowsfilter\\662e9cfd0d49029a1663d3f3bf94a4df1862fb0d46e41e7377f5f9d60a4fdf29"}],"ProcessorWeight":5000,"HostName":"alerting-eventhub-5f75947577-vntrf","MappedDirectories":[{"HostPath":"c:\\var\\lib\\kubelet\\pods\\46faa051-5c5a-11e9-9954-000d3a2bb437\\volumes\\kubernetes.io~secret\\secret-volume","ContainerPath":"c:\\inetpub\\wwwroot\\secret-volume","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\var\\lib\\kubelet\\pods\\46faa051-5c5a-11e9-9954-000d3a2bb437\\volumes\\kubernetes.io~secret\\default-token-zx5k8","ContainerPath":"c:\\var\\run\\secrets\\kubernetes.io\\serviceaccount","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"NetworkSharedContainerName":"062c3e88cda3f1bc6827ae9576ec6c4721e4096a75a242feb7e226460b777957"})

isolation is enabled  

according to this article :

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
and the model creates this: 
 
},
    "agentWindowsOffer": {
      "defaultValue": "WindowsServerSemiAnnual",
      "metadata": {
        "description": "The offer of windows image for the agent virtual machines."
      },
      "type": "string"
    },
    "agentWindowsPublisher": {
      "defaultValue": "MicrosoftWindowsServer",
      "metadata": {
        "description": "The publisher of windows image for the agent virtual machines."
      },
      "type": "string"
    },
    "agentWindowsSku": {
      "defaultValue": "Datacenter-Core-1809-with-Containers-smalldisk",
      "metadata": {
        "description": "The SKU of windows image for the agent virtual machines."
      },
      "type": "string"

the container was belt using : 

Windows Server, version   1709 | 64-bit | .NET Framework 4.7.1

this should be supported  : 
Supports
Only `hyperv` isolation
if not what kind of host needed to support this container ?
here is one of the nodes : 
ddresses:
  Hostname:    2251k8s000
  InternalIP:  10.240.0.4
  ExternalIP:  52.166.51.154
Capacity:
 attachable-volumes-azure-disk:  4
 cpu:                            2
 ephemeral-storage:              133703676Ki
 memory:                         8388148Ki
 pods:                           110
Allocatable:
 attachable-volumes-azure-disk:  4
 cpu:                            2
 ephemeral-storage:              133703676Ki
 memory:                         6290996Ki
 pods:                           110
System Info:
 Machine ID:      2251k8s000
 System UUID:
 Boot ID:
 Kernel Version:  10.0.17763.379

**What you expected to happen**:
windows pods to be scheduled 

**How to reproduce it** (as minimally and precisely as possible):
deploy the template and try to deploy dotnet-framework:4.7.1 you will get the error above

**Anything else we need to know**:
is there any setting needs to be done on the nodes ?

**Comment by CecileRobertMichon** [comment]
From @craiglpeters's email response:

There are two factors:
Windows process isolated containers require the Docker image Windows version to match the Windows host. Looks like once that issue was faced the user tried to use Hyper-V isolation to work around this.
Windows Hyper-V isolation isn't currently supported in Kubernetes
These points are documented here: https://kubernetes.io/docs/setup/windows/intro-windows-in-kubernetes/#windows-containers-in-kubernetes

You'll need to align the Windows container base image with the Windows host version on 2019 since we don't test older versions of Windows Server in Kubernetes.

The Kubernetes community is working towards enabling Hyper-V, and thus allowing some version skew between Windows container base images and host.

**Comment by duggaraju** [comment]
To add to this.. you need to add annotations to the POD spec to be able to run with hyper-v isolation.  
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hyperv
  annotations:
    **"experimental.windows.kubernetes.io/isolation-type": hyperv**
spec:
  containers:
   - name: hyperv
     image: mcr.microsoft.com/windows/servercore:ltsc2019
  restartPolicy: Never
```
But even after adding that running hyper-v containers fails: 
```
λ kubectl describe pods/hyperv
Name:               hyperv
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               4076k8s00000000/10.248.0.4
Start Time:         Mon, 03 Jun 2019 13:28:26 -0700
Labels:             <none>
Annotations:        experimental.windows.kubernetes.io/isolation-type: hyperv
                    kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"experimental.windows.kubernetes.io/isolation-type":"hyperv"},"name":"hyperv","...
Status:             Pending
IP:
Containers:
  hyperv:
    Container ID:
    Image:          mcr.microsoft.com/windows/servercore:ltsc2019
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xgqcq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-xgqcq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xgqcq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age   From                      Message
  ----     ------                  ----  ----                      -------
  Normal   Scheduled               13s   default-scheduler         Successfully assigned default/hyperv to 4076k8s00000000
  Warning  FailedCreatePodSandBox  2s    kubelet, 4076k8s00000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "hyperv": Error response from daemon: CreateComputeSystem 3b8c785dc7001e0655df0c8d2a6837d958fe78e0431984fc77d2960d805c82a2: winapi error #2151088414
(extra info: {"SystemType":"Container","Name":"3b8c785dc7001e0655df0c8d2a6837d958fe78e0431984fc77d2960d805c82a2","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\3b8c785dc7001e0655df0c8d2a6837d958fe78e0431984fc77d2960d805c82a2","Layers":[{"ID":"83cde023-8ecb-5f26-9303-eace05c698d1","Path":"C:\\ProgramData\\docker\\windowsfilter\\12bce7e06003d3cc27eaaf7779e6334d9e385a7e10d0da47029129f882b71735"},{"ID":"7ea8a073-7456-5de3-a626-973ed1532d2d","Path":"C:\\ProgramData\\docker\\windowsfilter\\2970723ae51bb1144a58886fea980f4d10735cc38eac0d074f05e80b5c4b2a74"}],"ProcessorWeight":2,"HostName":"hyperv","HvPartition":true,"HvRuntime":{"ImagePath":"C:\\ProgramData\\docker\\windowsfilter\\2970723ae51bb1144a58886fea980f4d10735cc38eac0d074f05e80b5c4b2a74\\UtilityVM"}})
```

Does the underlying OS has Hyper-V feature enabled by default? Or is that something we need to manually enable?

**Comment by PatrickLang** [comment]
@duggaraju - what VM size were you using? Some don't support Hyper-V.

@digeler 's scenario won't work as we can't run Windows Server 2016 or 1709 containers with Hyper-V isolation and Kubernetes.

**Comment by duggaraju** [comment]
I was using DS4-v3 as recommended byhttps://azure.microsoft.com/en-us/blog/nested-virtualization-in-azure/.  The weird thing I discovered is that Host Compute service (vmcompute.exe) on the node is crashing when trying to start a hyper-v container.  However if I create a standalone Azure VM and run there hyper-v containers succeeds. For some reason the VMs with k8s bits installed can't run hyper-v containers.
