### ISSUE TITLE
Scale command throws error with --api-model=kubernetes.json

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#1048]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE 
---

**What version of aks-engine?**:
0.34.0
---

**What happened**:
aks-engine scale --api-model=kubernetes.json throws error
`Error: error creating directory '': mkdir : The system cannot find the path specified.`

aks-engine scale --api-model=D:\aks\kubernetes.json works.

**What you expected to happen**:
aks-engine scale works well

**How to reproduce it** (as minimally and precisely as possible):
aks-engine scale --api-model=kubernetes.json

**Anything else we need to know**:
I think it is caused by below code in scale.go: 
```
dir, file := filepath.Split(sc.apiModelPath)
return f.SaveFile(dir, file, b)
```

**Comment by zhiweiv** [comment]
It worked before, looks like logic changed via #890 
@alexeldeib

**Comment by mboersma** [comment]
I was able to reproduce this with current master:
```
$ ./bin/aks-engine scale -m kubernetes.json --auth-method device -l eastus --master-FQDN example.eastus.cloudapp.azure.com -g maboersm-vmas -c 3
INFO[0000] validating...                                
INFO[0000] No subscription provided, using selected subscription from azure CLI: 12341234-1234-1234-1234-1234123412 
INFO[0005] Name suffix: 12341234                        
INFO[0009] Found no resources with type Microsoft.Network/routeTables in the template.  source="scaling command line"
INFO[0009] Starting ARM Deployment (example-1088741070). This will take some time... 
INFO[0166] Finished ARM Deployment (example-1088741070). Succeeded 
Error: error creating directory '': mkdir : no such file or directory
Usage:
  aks-engine scale [flags]
```

I'll try to fix it.

**Comment by alexeldeib** [comment]
@mboersma Sorry about that 🙁 I goofed and depended on deployment directory when my PR was to remove it. Looks like @zhiweiv made an apt point about this code:
```
dir, file := filepath.Split(sc.apiModelPath)
return f.SaveFile(dir, file, b)
```
Which I think means we aren't saving to the correct output directory (and would overwrite the user model?). I see you're already on your way to a fix so i'm a bit late here -- appreciate it 😊 If you prefer I can also pick this up and clean up after myself, just let me know.

**Comment by CecileRobertMichon** [comment]
@alexeldeib another potential bug that this revealed is that users can now pass in an "input" apimodel (the same apimodel they passed in to the deploy command to create the cluster) when we expected them to pass in the _output/apimodel.json file before. I don't know if that's something we want/a desired use case but it's causing things like #1051. I also think re-generating the certificate profile for an upgrade or a scale would be breaking. We should enforce validation + add documentation to make sure that only the output, fully expanded, apimodel can be used as input for upgrade/scale until we validate that using an apimodel that doesn't have all defaults set is a valid use case.

**Comment by alexeldeib** [comment]
@CecileRobertMichon So on scale/upgrade we should validate that the model has pre-provided certificates basically? We probably should not overwrite the user-provided file, should that write to a temp file maybe? WDYT?

Might make sense to revert that PR in the meantime? The cert issue could hose a cluster (if I understand correctly), and it's a minor QoL improvement.

**Comment by CecileRobertMichon** [comment]
I think we _should_ overwrite the apimodel file granted that *only* the node count (or k8s version for upgrade) changes (not the certificates or anything like that). The idea is that you can re-use the same file over and over again to scale/upgrade since that file we reflect the state of the cluster after the latest operation.

**Comment by dpetillo** [comment]
I can reproduce this in the latest version 38.4

**Comment by ocdi** [comment]
I had this error on the release-v0.40.0 branch when trying an upgrade on a test cluster. I was running in the directory and specified `apimodel.json` directly. It worked successfully if I changed the path to `./apimodel.json`

I opened a PR #1889 that works for me, however I'm not a go developer so I've done this in a naive manner.
