### ISSUE TITLE
Windows kubelet prints error "Unable to read config path" every 20s

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#1049]
**Is this an ISSUE or FEATURE REQUEST?**
ISSUE
---

**What version of aks-engine?**:
0.34.0
---

**Kubernetes version**:
1.14.1

**What happened**:
Windows kubelet prints error "Unable to read config path" every 20s

```
E0413 10:54:41.722276    3544 file.go:104] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
E0413 10:55:01.728055    3544 file.go:104] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
E0413 10:55:21.729621    3544 file.go:104] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
E0413 10:55:41.723525    3544 file.go:104] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
E0413 10:56:01.732765    3544 file.go:104] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
```

**What you expected to happen**:
Kubelet does not output this error

**How to reproduce it** (as minimally and precisely as possible):
Build a cluster with Windows nodes, check  C:\k\kubelet.err.log in Windows nodes.

**Anything else we need to know**:
I can find `--pod-manifest-path=/etc/kubernetes/manifests` was passed to kubelet in C:\k\kubeletstart.ps1.

Also in defaults-kubelet.go, it indicates pod-manifest-path shoud not be passed to Windows kubelet, not sure why it is not working.

```go
staticWindowsKubeletConfig := make(map[string]string)
for key, val := range staticLinuxKubeletConfig {
	switch key {
	case "--pod-manifest-path": // Don't add Linux-specific config
		break
	default:
		staticWindowsKubeletConfig[key] = val
	}
}
```

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/acs-engine/pull/3744 fixed this on Linux nodes, we need to apply a parallel change on the Windows provisioning script.

**Comment by zhiweiv** [comment]
These were really annoying while checking kubelet logs 😟.
