### ISSUE TITLE
Scale does not work, new Windows nodes don't appear

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#1050]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.34.0
---

**Kubernetes version**:
1.14.1

**What happened**:
Scale does not work, new Windows nodes don't appear in kubectl get nodes

**What you expected to happen**:
Scale works for Windows pool

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster with 1 Windows node, scale to 2 nodes, check output of kubectl get nodes.

**Anything else we need to know**:
Error in kubelet log
E0414 03:06:20.738164    3488 kubelet_node_status.go:94] Unable to register node "1478k8s001" with API server: Post https://10.255.255.5:443/api/v1/nodes: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")

Here are template and log
[kubernetes.json.txt](https://github.com/Azure/aks-engine/files/3076978/kubernetes.json.txt)
[kubelet.err.log](https://github.com/Azure/aks-engine/files/3076979/kubelet.err.log)

**Comment by CecileRobertMichon** [comment]
This is most likely related to #1051. You need to use the apimodel in the output directory so that the same certificates are used for the new node(s).

**Comment by zhiweiv** [comment]
Thanks for clarify, I got confused by the aks-engine help output, it works now with apimodel in the output directory.
```
Usage:
  aks-engine scale [flags]

Flags:
  -m, --api-model string            path to the apimodel file
---------------------------------------------------------------
Usage:
  aks-engine deploy [flags]

Flags:
  -m, --api-model string            path to the apimodel file
```
