### ISSUE TITLE
Scale command added a lot of default value to api model file

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#1051]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.34.0
---

**What happened**:
Scale command added a lot of default value to api model
For example, 
the original content
```json
"masterProfile": {
  "count": 1,
  "dnsPrefix": "test",
  "vmSize": "Standard_B2s",
  "osDiskSizeGB": 60
}
```
After scale command it was changed to below
```json
"masterProfile": {
  "count": 1,
  "dnsPrefix": "test",
  "subjectAltNames": null,
  "vmSize": "Standard_B2s",
  "osDiskSizeGB": 60,
  "storageProfile": "ManagedDisks",
  "oauthEnabled": false,
  "preProvisionExtension": null,
  "extensions": [],
  "availabilityProfile": ""
}
```

**What you expected to happen**:
Scale command only update the value of node count in api model.

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster, scale nodes, check api model file.

**Comment by CecileRobertMichon** [comment]
@zhiweiv you should use the apimodel file generated by aks-engine as part of the output directory which already contains all the defaults that were used to deploy your cluster, not an input apimodel with incomplete fields. The description of the flag was already updated in master and that should hopefully help clarify that confusion. Let me know if you think of anything to make this more clear.

**Comment by zhiweiv** [comment]
Thanks for clarify, I got confused by the aks-engine help output.
```
Usage:
  aks-engine scale [flags]

Flags:
  -m, --api-model string            path to the apimodel file
---------------------------------------------------------------
Usage:
  aks-engine deploy [flags]

Flags:
  -m, --api-model string            path to the apimodel file
```

**Comment by zhiweiv** [comment]
Btw, could we make the help text more clear, since deploy and scale use different api model.
@CecileRobertMichon

**Comment by mboersma** [comment]
I'll take a look at clarifying this further in the help text and docs.
