### ISSUE TITLE
SupportPodPidsLimit becoming a beta feature breaks some 1.14 deployments

### ISSUE THREAD

**Issue by skinny** [Azure/aks-engine#1055]
**Is this a request for help?**:
no
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
master
---

When deploying a new 1.14 cluster but especially when upgrading to 1.14 or higher from an earlier version the combination of `aks-engine` and the `SupportPodPidsLimit` feature breaks some deployments (rabbitmq for example).

PID hungry applications are running fine on 1.13 due to the fact that the `SupportPodPidsLimit` feature gate is still alpha and therefore disabled by default. In 1.14 the feature is enabled by default which would not be a real issue by itself. However `aks-engine` deploys with a `pids-per-pod` limit of 100 which is not used until the feature flag is turned on.

I don't know if we need to have a higher default value or none at all, but as-is this is not a sane default setup

**Kubernetes version**:
1.14

**Comment by PatrickLang** [comment]
How are you seeing this in the logs?

if a pod is being PID limited, would you see something like this in dmesg? `[ 1764.354453] cgroup: fork rejected by pids controller in /kubepods/pod4b2e9900-656c-11e9-b3cb-000d3a6d7f20/36804292fff8d2b18d7c83d453ae58da0092bdfff2c89a0f540628bec1f532aa`

**Comment by PatrickLang** [comment]
@jackfrancis this was killing one of my 1.14 demos. Just deploy this chart and watch SQL go into CrashBackOff

https://github.com/PatrickLang/fabrikamfiber/tree/helm-2019-mssql-linux/charts/fabrikamfiber

**Comment by PatrickLang** [comment]
Here's the missing docs https://github.com/kubernetes/website/pull/13806

**Comment by skinny** [comment]
@PatrickLang I have not noticed anything in `dmesg`  but experienced this issue the same way you mention ed : just deploy the `rabbitmq-ha` chart and it will fail with all kind of `fork` errors. Setting the pid-limit back to -1 resolves the issue.

**Comment by PatrickLang** [comment]
@skinny thanks, that makes sense. I am trying 1000 and so far mssql seems happy.

One thing that's not intuitive here is if you do `docker inspect` on the running containers, you won't see a pid limit set there. It's set by the kubelet on the cgroup, which is why I found the errors in `dmesg` on the node rather than in the pod.

**Comment by skinny** [comment]
Thanks for reminding me of that, yes I also had to dig deep to find out that the limit is set on cgroup level instead of container level. Even more reason to document this behavior clearly imo
