### ISSUE TITLE
Moby version should be configurable

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#107]
See #106

**Comment by vpatelsj** [comment]
We would love to have a version flag exposed in API model to stay pinned to a specific moby version while deploying clusters via AKS Engine!

**Comment by dtzar** [comment]
How does the 3.x version number map to the upstream moby-engine?  What I see in [their releases ](https://github.com/moby/moby/releases) and changelog is old yet new commits are there.

**Comment by CecileRobertMichon** [comment]
@dtzar sorry no one answered your question! In case you still haven't figured out an answer, the Moby build version in an internal Azure build because the upstream Moby project does not currently publish versioned releases.

I've started work on this, follow #407 for progress.
