### ISSUE TITLE
Unable to deploy to az, "Changing property 'imageReference' is not allowed.

### ISSUE THREAD

**Issue by jjeyaraj** [Azure/aks-engine#1072]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**What version of aks-engine?**:
 .\aks-engine.exe version
Version: v0.34.1
GitCommit: e68d84850
GitTreeState: clean
---

**Kubernetes version**:
1.14.1

**What happened**:
Trying to deploy the generated config, i'm running into the issue it indicates:
**"code": "PropertyChangeNotAllowed",
    "message": "Changing property 'imageReference' is not allowed.",**

**What you expected to happen**:
Expect the deployment to go through

**How to reproduce it** (as minimally and precisely as possible):
Use the following engine to generate via aks-engine:
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorVersion": "1.14.1"
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "mrprpsapi16",
            "vmSize": "Standard_D2_v3"
        },
        "agentPoolProfiles": [
            {
                "name": "linuxpool3",
                "count": 2,
                "vmSize": "Standard_D2_v2",
                "availabilityProfile": "AvailabilitySet"
            },
            {
                "name": "windowspool4",
                "count": 10,
                "vmSize": "Standard_D2s_v3",
                "availabilityProfile": "AvailabilitySet",
                "osType": "Windows",
                "extensions": [
                    {
                        "name": "winrm"
                    }
                ]
            }
        ],
        "extensionProfiles": [
            {
                "name": "winrm",
                "version": "v1"
            }
        ],
        "windowsProfile": {
            "adminUsername": "xxxxxxxxxxxxxxxxxxxxxx",
            "adminPassword": "xxxxxxxxxxxxxxxxxxxxxxxxx"
        },
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "xxxxxxxxxxxxxxxxx",
            "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        }
    }
}

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Hello 👋Are you deploying in a new resource group with a unique DNS prefix? This error indicates you are trying to modify an existing deployment rather than creating a new one.

**Comment by jjeyaraj** [comment]
Hey,

Based on the conversation we had it looks like this is due to an earlier bad deployment.
 so when I redeployed it again, it was trying to modify an existing osprofile.

Closing this out. Thanks for the help.
