### ISSUE TITLE
CIS: nessus gaps

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1074]
```
1.3.2  Ensure filesystem integrity is regularly checked
Requirement is to put this into root’s crontab.
0 5 * * * /usr/bin/aide --check

1.4.1 Ensure permissions on bootloader config are configured
This should already be set, but is getting reverted to 444. Will have to determine if something is changing this during deprovision or provisioning.
chown root:root /boot/grub/grub.cfg
chmod og-rwx /boot/grub/grub.cfg

1.5.1 Ensure core dumps are restricted
This audit has 2 parts…
"* hard core 0" is already set in /etc/security/limits.d/CIS.conf. This part of the Nessus scan seems broken – it does not expect the '*' at the beginning of the line.
"fs.suid_dumpable = 0" needs to be present in /etc/sysctl.conf or /etc/sysctl.d/*; Could add to /etc/sysctl.d/60-CIS.conf to keep all changes in one place.

2.3.4 Ensure telnet client is not installed
This is installed as a 'recommends' of ubuntu-standard. Easy to remove.
apt remove -y telnet

5.1.8 Ensure at/cron is restricted to authorized users - '/etc/at.deny'
Need to delete /etc/at.deny. 

6.2.8  Ensure users' home directories permissions are 0750 or more restrictive
Must chmod the following folders to 0750.
/var/lib/chrony
/var/lib/misc
/home/jpeacock
/var/lib/lxd/
/home/mbearup
/var/run/dbus
/var/cache/pollinate
/var/spool/postfix
/var/run/sshd
/run/systemd
/run/systemd/netif
/run/systemd
/run/uuidd
```

**Comment by hieumoscow** [comment]
Hi @jackfrancis, 
I ran a test within AKS nodes and saw that most files in your 6.2.8 section now has 0755/drwxr-xr-x access.
Is there a reason for the Other Read and Other Execute permissions? 

root@aks-agentpool-19894834-vmss000000:~# cat 626.sh
#!/bin/bash
for dir in `cat /etc/passwd | egrep -v '(root|halt|sync|shutdown)' | awk -F: '($7 != "/usr/sbin/nologin") { print $6 }'`; do
  dirperm=`ls -ld $dir | cut -f1 -d" "`
  if [ `echo $dirperm | cut -c6 ` != "-" ]; then
    echo "Group Write permission set on directory $dir"
  fi
  if [ `echo $dirperm | cut -c8 ` != "-" ]; then
    echo "Other Read permission set on directory $dir"
  fi
  if [ `echo $dirperm | cut -c9 ` != "-" ]; then
    echo "Other Write permission set on directory $dir"
  fi
  if [ `echo $dirperm | cut -c10 ` != "-" ]; then
    echo "Other Execute permission set on directory $dir"
  fi
done
root@aks-agentpool-19894834-vmss000000:~# ./626.sh
Other Read permission set on directory /var/lib/lxd/
Other Execute permission set on directory /var/lib/lxd/
Access: (0755/drwxr-xr-x)

**Comment by hieumoscow** [comment]
For 5.1.8 Ensure at/cron is restricted to authorized users - '/etc/at.deny'
I still see /etc/at.deny in AKS. Is this planned to be removed?

```bash
root@aks-agentpool-19894834-vmss000000:/etc# stat /etc/at.deny
  File: /etc/at.deny
  Size: 144       	Blocks: 8          IO Block: 4096   regular file
Device: 811h/2065d	Inode: 879         Links: 1
Access: (0640/-rw-r-----)
```
