### ISSUE TITLE
Extensions are ignored for both master and agent nodes

### ISSUE THREAD

**Issue by adelina-t** [Azure/aks-engine#1079]
**ISSUE**

---

**What version of aks-engine?**:

v0.33.0 onwards 

---

Consider this template:

```
{
    "location": "westeurope",
    "name": "prow-e05f8716-60f1-11e9-95d1-0e02a3139140",
    "APIVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.14"
        },
        "masterProfile": {
            "count": 1,
            "distro": "ubuntu",
            "dnsPrefix": "prow-custom-test3",
            "vmSize": "Standard_D2_v3"
        },
        "agentPoolProfiles": [
            {
                "name": "windowspool1",
                "count": 2,
                "distro": "ubuntu",
                "vmSize": "Standard_D2s_v3",
                "osType": "Windows",
                "availabilityProfile": "AvailabilitySet",
                "osDiskSizeGB": 128,
		"extensions": [
		     {
			"name": "winrm"
		     }
		]
            }
        ],
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": ""
                    }
                ]
            }
        },
        "windowsProfile": {
            "adminUsername": "azureuser",
            "adminPassword": "Passw0rd1234",
            "WindowsImageSourceUrl": "",
            "WindowsPublisher": "",
            "WindowsOffer": "",
            "WindowsSku": "",
            "windowsDockerVersion": "18.09.5",
        },
        "extensionProfiles": [
            {
                "name": "winrm",
                "version": "v1"
            }
        ]
    }
}
```

The resulting ARM templates will not contain any Custom Script resources for the indicated extensions ( The template only includes a Windows agent extension, but it applies to master and Linux agents as well )

As far as I can tell, this happens after the introduction of this templating refactor: https://github.com/Azure/aks-engine/pull/324

Previously, the templates for the extension were generated by calling [1][2]. Post refactor, [2] is of course dead code and not being used in the new templating model, however I find no call to [1] or anything similar in the new model.

[1] https://github.com/Azure/aks-engine/blob/206328a0270c91b8b3dfa6d859eeff56b2f9c51c/pkg/engine/engine.go#L956
[2] https://github.com/Azure/aks-engine/blob/master/pkg/engine/template_generator.go#L625

Something similar to: https://github.com/adelina-t/aks-engine/commit/0b9bb97bb218d80d7e0d37d26b43df3eabd81de5 can be a quick fix for the issue, however not necessarily suited for permanence.

**Comment by adelina-t** [comment]
cc: @PatrickLang

**Comment by PatrickLang** [comment]
Thanks! I actually ran into this today trying to test some new Windows KBs.

Can you add a note on which extensions (master or agent pool) you're using? I think it might make more sense to put some of those straight into AKS-Engine for reliability. WinRM and Windows KBs make sense. OpenSSH for Windows nodes is already merged and enabled by default too for example

**Comment by adelina-t** [comment]
I observed it in testing. Basically our custom master extension ( which makes the master node not schedulable )
