### ISSUE TITLE
Deterministic Windows VHD

### ISSUE THREAD

**Issue by craiglpeters** [Azure/aks-engine#1084]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature Request

---

**What version of aks-engine?**: Going forward

---

**Kubernetes version**: 1.14 and later

**What happened**:
Build Windows VHDs with

- [x] Windows Server 2019 and latest cumulative update
- [x] (optional) Additional KBs installed
- [ ] container runtime(s)
- [ ] Kubernetes
- [ ] CNI 
- [ ] Log collection scripts

preinstalled for faster deployments. Need to create a process for managing the creation of VHD for supported Windows Server releases, and curating the configuration and patches that corresponds to the way AKS-Engine does this for Linux.

If log paths change, update https://github.com/Azure/azure-diskinspect-service/pull/95/files

**How to reproduce it** (as minimally and precisely as possible):
Pulling the latest Windows version isn't deterministic

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
I think we can close this. @marosset kindly re-open if I'm wrong.

**Comment by marosset** [comment]
> I think we can close this. @marosset kindly re-open if I'm wrong.

You are not wrong. Thanks for doing some house-cleaning here.
