### ISSUE TITLE
No outbound UDP possible when using standard load balancer

### ISSUE THREAD

**Issue by sylr** [Azure/aks-engine#1099]
When using Azure Zones you need to use load balancers of the Standard SKU.

The Standard SKU does not work the same as the Basic SKU when it comes to SNAT'ing outbound connections.

In case of UDP connections the load balancer SNAT mechanism will only be fired up if there is at least one UDP load balancing rule. If not your requests will go out but you'll never get a response.

Source: https://stackoverflow.com/questions/50168334/public-lb-configuration-for-ntp-service-in-azure

**Comment by jackfrancis** [comment]
@sylr is it acceptable to deliver a "dummy" UDP load balancing rule w/ the ARM template spec so that a user doesn't have to do so manually?

**Comment by sylr** [comment]
That's what I did.
