### ISSUE TITLE
Azure CNI ip-masq-agent nonMasqueradeCIDRs is missing agent subnet

### ISSUE THREAD

**Issue by sylr** [Azure/aks-engine#1100]
Currently the ip-masq-agent configuration only reference the master subnet and is missing the agent subnet.

This leads to not having real clients IP (public IPs) shown to pods. Instead you'll only see agents IP.

https://github.com/Azure/aks-engine/blob/aa434b2e88de408dc1bbeb1fbc5f7a46277c687e/pkg/api/types.go#L1069-L1075

**Comment by shaikatz** [comment]
If you use CustomVNET you should specify VnetCidr that includes both your master and agent subnets (written in the documentation).
If you don't use CustomVNET it'll use the DefaultVNETCIDR which is `10.0.0.0/8` and it covers both agent and master subnets.

I don't think there is a bug here.

**Comment by sylr** [comment]
That might not be possible to make a CIDR that stricly defines Master + Agent subnets. I, for example have different netmasks for these subnets and they also might not be contiguous.

**Comment by shaikatz** [comment]
Yea that makes it a bit harder, you have 2 options:
1. Set broader netmask that includes both of them.
   It won't make any harm if the super subnet is a bit too big, as long as it doesn't include only internal addresses.
2. Change their subnets.

**Comment by sylr** [comment]
Yeah so you were right, it was a configuration mistake on my part, this value should really be the VNET cidr.
