### ISSUE TITLE
error when using enableVMSSNodePublicIP

### ISSUE THREAD

**Issue by superyyrrzz** [Azure/aks-engine#1108]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of aks-engine?**: 0.34.0

---

**Kubernetes version**:

**What happened**:

I am trying #130. Following quickstart, I added `enableVMSSNodePublicIP` and `availabilityProfile` to the example, like:
```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "enableVMSSNodePublicIP1": true
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

**What you expected to happen**: Succeed

**How to reproduce it** (as minimally and precisely as possible): Meet error:
```
INFO[0000] new api model file has been generated during merge: C:\Users\xxx\AppData\Local\Temp\mergedApiModel186671755
Error: loading API model: error parsing the api model: Unknown JSON tag enableVMSSNodePublicIP
```

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
`enableVMSSNodePublicIP` is available in the master branch but not part of an aks-engine release yet. It will be available with the next minor release (`v0.35.0`). In the meantime, you can [build from source](https://github.com/Azure/aks-engine/blob/master/docs/community/developer-guide.md#build-aks-engine-from-source) if you'd like to try it out.

**Comment by superyyrrzz** [comment]
@CecileRobertMichon Thank you for the information. I can build and run it in docker on Windows. No error on config `enableVMSSNodePublicIP`, but I meet another error:
```
INFO[0000] new api model file has been generated during merge: /tmp/mergedApiModel199102542
Error: loading API model: failed to get client: Invoking Azure CLI failed with the following error:
Usage:
  aks-engine deploy [flags]
```

No detailed error shows from Azure CLI. I find it is from this piece of code:https://github.com/Azure/aks-engine/blob/8caef60e0892d02d674ca71e92ee05c4c7498978/vendor/github.com/Azure/go-autorest/autorest/azure/cli/token.go#L153-L161

Then I tried run this directly in shell. It works well to return a JSON:
```
az account get-access-token -o json --resource https://management.azure.com/
{
  "accessToken": "...",
   ...
}
```

Not sure whether I missed something to run it from source code. Similar to #773 but not with the same error message.

**Comment by munishm** [comment]
@superyyrrzz - the solution is to use the authentication method to client secret. 

Please refer:  **https://github.com/Azure/aks-engine/issues/773**
