### ISSUE TITLE
Azure Kubernetes with Cosmos DB Deployment error when using AKS version v0.33.6 (latest)

### ISSUE THREAD

**Issue by SnehaGunda** [Azure/aks-engine#1119]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

**What version of aks-engine?**:
v0.33.6: https://github.com/Azure/aks-engine/releases/tag/v0.33.6
---

**Kubernetes version**:

**What happened**:
Azure Kubernetes with Cosmos DB as backend using ARM template. Template deployment results in the following error when using AKS version v0.33.6 (latest):

![image](https://user-images.githubusercontent.com/14284405/56531838-8ad77d80-6509-11e9-878a-8f55eba5d73f.png)

**How to reproduce it** (as minimally and precisely as possible):
Install AKS latest version https://github.com/Azure/aks-engine/releases/tag/v0.33.6
Install latest version of Azure CLI. run the following commands:

az group create --name <RG name> --location centralus

az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/<sub_Id>/resourceGroups/<RG name>"

aks-engine deploy --subscription-id <sub_Id> --client-id <app_id> --client-secret <password>  --dns-prefix <RG name> --location centralus --api-model apiModel.json  --force-overwrite

**Anything else we need to know**:
ApiModel.json file contents:

{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "kubernetesConfig": {
                "useManagedIdentity": false
            }
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "",
            "vmSize": "Standard_D2_v3",
            "cosmosEtcd": true
        },
        "agentPoolProfiles": [
            {
                "name": "agent",
                "count": 1,
                "vmSize": "Standard_D2_v3",
                "availabilityProfile": "AvailabilitySet"
            }
        ],
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": ""
                    }
                ]
            }
        }
    }
}

**Comment by jackfrancis** [comment]
Resources spec, before:

```
{
      "apiVersion": "[variables('apiVersionCosmos')]",
      "kind": "GlobalDocumentDB",
      "location": "[resourceGroup().location]",
      "name": "[variables('cosmosAccountName')]",
      "properties": {
        "capabilities": [
          {
            "name": "EnableEtcd"
          }
        ],
        "consistencyPolicy": {
          "defaultConsistencyLevel": "BoundedStaleness",
          "maxIntervalInSeconds": 5,
          "maxStalenessPrefix": 100
        },
        "databaseAccountOfferType": "Standard",
        "locations": [
          {
            "failoverPriority": 0,
            "locationName": "[resourceGroup().location]"
          },
          {
            "failoverPriority": 1,
            "locationName": "[resourceGroup().location]"
          }
        ],
        "name": "[variables('cosmosAccountName')]",
        "primaryClientCertificatePemBytes": "[variables('cosmosDBCertb64')]"
      },
      "tags": {
        "defaultExperience": "Etcd"
      },
      "type": "Microsoft.DocumentDB/databaseAccounts"
    }
```

After:

```
{
      "apiVersion": "[variables('apiVersionCosmos')]",
      "consistencyPolicy": {
        "defaultConsistencyLevel": "BoundedStaleness",
        "maxIntervalInSeconds": 5,
        "maxStalenessPrefix": 100
      },
      "kind": "GlobalDocumentDB",
      "location": "[resourceGroup().location]",
      "name": "Microsoft.DocumentDB/databaseAccounts",
      "primaryClientCertificatePemBytes": "[variables('cosmosDBCertb64')]",
      "properties": {
        "capabilities": [
          {
            "name": "EnableEtcd"
          }
        ],
        "consistencyPolicy": {
          "defaultConsistencyLevel": "BoundedStaleness",
          "maxIntervalInSeconds": 5,
          "maxStalenessPrefix": 100
        },
        "databaseAccountOfferType": "Standard",
        "locations": [
          {
            "failoverPriority": 0,
            "locationName": "[resourceGroup().location]"
          },
          {
            "failoverPriority": 1,
            "locationName": "[resourceGroup().location]"
          }
        ]
      },
```
