### ISSUE TITLE
Getting "Could not find member 'Sensitivity' on object of type 'TemplateResource' " Error message with all aks binary v0.32.0 to v0.34.3

### ISSUE THREAD

**Issue by satishsudhini** [Azure/aks-engine#1168]
New aks engine version after v0.32.0 cluster installation failing with the below error message

Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'Sensitivity' on object of type 'TemplateResource'. Path 'properties.template.resources[12].Sensitivity', line 1, position 11293

**Comment by mboersma** [comment]
@satishsudhini could you attach the apimodel.json (removing your subscription ID and other sensitive info) and the commands you used to deploy?

**Comment by satishsudhini** [comment]
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.11",
      "orchestratorVersion": "1.11.8",
      "kubernetesConfig": {
        "enableRbac": true,
        "enableSecureKubelet": true,
        "enableAggregatedAPIs": true,
        "networkPolicy": "calico",
        "networkPlugin": "kubenet",
        "clusterSubnet": " * ",
        "serviceCidr": " * ",
        "dnsServiceIP": " * ",
        "dockerBridgeSubnet": "* ",
        "etcdDiskSizeGB": "32",
        "privateCluster": {
          "enabled": true
        },
        "kubeletConfig": { 
          "--non-masquerade-cidr": "*",
          "--cluster-domain": "*",
          "--feature-gates": "PodPriority=true"
        },
        "apiServerConfig": {
          "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
        },
        "useInstanceMetadata": false,
        "enableEncryptionWithExternalKms": true,
        "cloudProviderRateLimit": false,
        "cloudProviderRateLimitBucket": 0,
        "cloudProviderRateLimitQPS": 0,
        "addons": [
          {
            "name": "blobfuse-flexvolume",
            "enabled" : false
          },
          {
            "name": "smb-flexvolume",
            "enabled" : false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled" : false
          },
          {
            "name": "nvidia-device-plugin",
            "enabled" : false
          },
          {
            "name": "azure-cni-networkmonitor",
            "enabled" : false
          },
          {
           "name": "ip-masq-agent",
           "enabled" : false
          }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "CLUSTER_NAME",
      "distro": "ubuntu",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": "SUBNET_ID",
      "availabilityProfile": "AvailabilitySet",
      "firstConsecutiveStaticIP": "MASTER_IP",
      "OSDiskSizeGB": 32,
      "extensions": [
        {
          "name": "bootstrap",
          "singleOrAll": "All"
        }
     ]
    },
    "agentPoolProfiles": [
      {
        "name": "AGENT_NAME",
        "count": 2,
        "distro": "ubuntu",
        "vmSize": "Standard_DS4_v2",
        "vnetSubnetId": "SUBNET_ID",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile" : "ManagedDisks",
        "diskSizesGB": [2],
        "OSDiskSizeGB": 64,
        "acceleratedNetworkingEnabled": true,
        "preProvisionExtension": {
            "name": "prepare_vm_disks",
            "singleOrAll": "All"
        },
        "extensions": [
          { 
            "name": "bootstrap",
            "singleOrAll": "All"
          }
       ]
      }
    ],
    "extensionProfiles": [
      {
          "name": "prepare_vm_disks",
          "version": "v1",
          "rootURL": "*",
          "script": "*",
          "urlQuery": "*"
      }
    ],
    "linuxProfile": {
      "adminUsername": "ADMIN_ACCOUNT",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "PUBLIC_KEY"
          }
        ]
      }
    },
    "aadProfile": {
      "serverAppID": "*",
      "clientAppID": "*",
      "tenantID": "*",
      "adminGroupID": "*"
    },    
    "servicePrincipalProfile": {
      "clientId": "*",
      "secret": "*",
      "objectId": "*"
    }
  }
}

**Comment by CecileRobertMichon** [comment]
@satishsudhini where is the `prepare_vm_disks` extension template coming from?

**Comment by satishsudini** [comment]
We are using this extension for prepare vm . This is taken from below https://raw.githubusercontent.com/Azure-Samples/compute-automation-configurations/master/prepare_vm_disks.sh .

This same script we are using with v31.3 which is working fine
