### ISSUE TITLE
Add CONFIG_NF_CONNTRACK_PROCFS in kernel config

### ISSUE THREAD

**Issue by carlpett** [Azure/aks-engine#117]
**Is this a request for help?**: Yes?

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature request

**What version of acs-engine?**: any

---

Could the kernel flag `CONFIG_NF_CONNTRACK_PROCFS` be enabled on the kernels we get with acs-engine clusters? This would allow reading conntrack statistics to metrics systems from /proc/net/stat/nf_conntrack, which is useful to alert on for example [https://github.com/kubernetes/kubernetes/issues/56903](kubernetes#56903).

**Comment by CecileRobertMichon** [comment]
@carlpett we build an OS image using Packer based on Ubuntu 1604. We don't build the kernel ourselves but get it from Canonical in the UbuntuServer image. Is there any way to add what you're looking for on an existing image? Or do you know of a Canonical distribution of this kernel that has the option you're looking for?

**Comment by carlpett** [comment]
Aha, I assumed you were building the kernels somewhere in the Azure team. I found the kernel config files as they are built by Canonical: http://kernel.ubuntu.com/~kernel-ppa/configs/. For example, xenial/linux-azure, would be the ones we use, I assume.
Looking around, most kernels are not enabling this flag, with the notable exception of the GCP and GKE builds, which seems like a relevant comparison :) 
It is also enabled by default in Fedora, Centos and RHEL cloud images.

As for adding it to an existing image, not really, since it requires recompiling the kernel and installing it on all the machines.
