### ISSUE TITLE
Enable k8s deployments with no outbound internet

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#118]
This issue is to track the progress of deployments with no outbound (except allowing outbound to cluster vnet). 

Sub items:

- [x] Pre-download all dependencies in the OS image to avoid downloads during deployment

- [x] Pre-pull all container addon images and do not attempt to pull when pods start if already present 

- [ ] Use internal load balancer so nodes can talk to the apiserver (right now all `kubectl` commands running on nodes timeout because they try to reach a public IP) - ~also the reason CSE fails with exit code 30~ now skipping CSE check when no outbound

- [x] Make sure all addons start and go to running state, each with an assigned IP in the vnet

- [x] Make outbound connection check optional

**Comment by fawohlsc** [comment]
+1 

Having this feature would be amazing, since a lot of folks especially in FSI require that.

**Comment by CecileRobertMichon** [comment]
If anyone is interested in beta testing this, we already have a feature flag `BlockOutboundInternet` that you can specify in your apimodel to deploy with an NSG rule that blocks outbound internet (except for outbound to VNET): 
```
"apiVersion": "vlabs",
  "properties": {
        "featureFlags": {
              "blockOutboundInternet": true
        }
...
```

**Comment by fawohlsc** [comment]
Pretty cool - thanks @CecileRobertMichon. Which outbound to VNET connectivity is required by aks-engine? Do customers have to open anything in their VNET?

**Comment by fawohlsc** [comment]
Pretty cool, thank you @CecileRobertMichon

**Comment by dzemp** [comment]
Just wanted to test the new feature by using the precompiled aks-engine for Windows, but get the following error:

FATA[0002] error loading API model in generateCmd: error parsing the api model: Unknown JSON tag featureFlags

@CecileRobertMichon, is this a known issue? Do I need to compile the aks-engine on my own?

**Comment by dzemp** [comment]
When I want to deploy a generated azuredeploy.json with the new featureFlag enabled using Azure CLI, I get the following error:

Message: The template deployment 'ClusterDeployment' is not valid according to the validation procedure. The tracking id is '809ed5cf-590b-4abc-9ea1-89c187a7fdad'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
Exception Details:
        Error Code: SecurityRuleParametersMissing
        Message: Required security rule parameters are missing for security rule with Id: /subscriptions/<id>/resourceGroups/<rg>/providers/Microsoft.Network/networkSecurityGroups/k8s-master-97729440-nsg/securityRules/allow_vnet. Security rule must specify DestinationAddressPrefixes, DestinationAddressPrefix, or DestinationApplicationSecurityGroups.

@CecileRobertMichon, is this a known issue? It works without the featuresFlag.

**Comment by CecileRobertMichon** [comment]
@dzemp I have only tested this with limited cluster configurations so far so it's possible that your specification apimodel configuration is was not one of these. Can you please share the apimodel cluster configuration that you were using? I think this is because you are using an existing vnet most likely.

**Comment by CecileRobertMichon** [comment]
GPU not currently compatible with no outbound #940

**Comment by rbitia** [comment]
Currently supported "no outbound" configurations are documented here: test/e2e/test_cluster_configs/no_outbound.json

Therefore closing this issue in favor of #940 staying open.
