### ISSUE TITLE
Proposal: support service principal secret rolling

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#1189]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature Request 
---

**What version of aks-engine?**:
all
---

Creating and updating an Azure service principal or the service principal secret used by a cluster is a difficult task today. In fact, it's not even fully documented (see: docs: how to change Service Principal credentials? #724). Can this be automated as a new feature for `aks-engine` ?

**Comment by CecileRobertMichon** [comment]
related to https://github.com/Azure/aks-engine/issues/724 and #1229
