### ISSUE TITLE
Add custom tags to the cluster vm's

### ISSUE THREAD

**Issue by mo-saeed** [Azure/aks-engine#1204]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of aks-engine?**:
aks-engine 0.35.0
---

**Kubernetes version**:
1.13.5

**What happened**:
No option to add custom tags to azure VM's while creating the cluster

**What you expected to happen**:
Add custom VM tags during the cluster installation, in the cluster definition file
 
customTags:
  project: ops
  team:    devops

**Comment by Guilhermeslucas** [comment]
anyone working with this? I can try! :)

**Comment by Guilhermeslucas** [comment]
I am investigating this issue! I'm just wondering which is the desired behavior in this issue. 
It would be adding just like this [link](https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-tags/azuredeploy.json#L174-L178)? Besides, it would be just one tag for every resource that is created for the cluster? Thanks a lot!

**Comment by Guilhermeslucas** [comment]
Just a quick question, isn't [this](https://github.com/Azure/aks-engine/tree/master/examples/kubernetes-labels) the behavior we want to get?

**Comment by mo-saeed** [comment]
@Guilhermeslucas No this is kubernetes node labels https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#add-a-label-to-a-nodeels

**Comment by mo-saeed** [comment]
> Just a quick question, isn't [this](https://github.com/Azure/aks-engine/tree/master/examples/kubernetes-labels) the behavior we want to get?

**Comment by mo-saeed** [comment]
Sorry closed by mistake !

**Comment by Guilhermeslucas** [comment]
No problem! @mo-saeed Since you are here, let me ask you something. The intention here is to make a only one tag that will be added to all of the machines (master and agents) or be able to add a separated tag for both master and agent? Thanks!

**Comment by mo-saeed** [comment]
@Guilhermeslucas no need for separated tags, same tags for all cloud resources, VM's (master and agents) and not sure also if possible to all other resources like vnet and etcd disks, nw security groups, etc.... 
but ofc for now the most important is to have custom tags for master and agent **VM's**.
