### ISSUE TITLE
Windows Nodes not properly provisioned (VMSS)

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/aks-engine#1210]
**Is this a request for help?**: Confirming and Raising an issue

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of aks-engine?**: v.0.35.1

---

**Kubernetes version**:

1.14.1

**What happened**:

When creating an AKS-E cluster with Windows Nodes in VMSS, the Windows Agent nodes are not properly provisioned:

- no displayed when running `kubectl get nodes`. But I see my Linux Master node.
- can't deploy any Windows containers on my Windows Agent nodes.

**What you expected to happen**:

`kubectl get nodes` should list my Windows Agent nodes too and should be able to deploy my Windows containers on my Windows Agent Nodes.

**How to reproduce it** (as minimally and precisely as possible):

Here is the command line I run:
```
aks-engine deploy -s $subscriptionId --client-id '$clientId' --client-secret '$clientSecret' --dns-prefix $dnsPrefix -l $location --api-model https://raw.githubusercontent.com/mathieu-benoit/aksengine-agent/master/example/kubernetes-win-vmss.json
```

**Anything else we need to know**:

- My `kubectl` version in my current Azure Cloud Shell is 1.13
- I tried 3 times, with other AKS-E clusters creation, same issue, just in case.
- My Azure deployment successfully completed and I see my VMSS in Azure.
- I tried with AvailabilitySet instead and I don't have this issue.
- Those tests were before and after the outage on 2019-05-02

**Comment by CecileRobertMichon** [comment]
@craiglpeters

**Comment by mathieu-benoit** [comment]
FYI, just re-tested with the new AKS-Engine version v0.36.0, and I don't have anymore that issue. Closing it.
I now see the Windows agent nodes.
