### ISSUE TITLE
VMExtensionProvisioningError error cse-master exit code 15 - ERR_ETCD_CONFIG_FAIL

### ISSUE THREAD

**Issue by andremakram** [Azure/aks-engine#1212]
**Is this a request for help?**:

YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE
---

**What version of aks-engine?**:
Version: v0.34.3
GitCommit: 3fbbf8225
GitTreeState: clean

---
**Kubernetes version**:
1.14.1

**What happened**:
Deployment on the master linux boxes fails with cse-master-0 error status 15.

> ERR_ETCD_CONFIG_FAIL=15 # Unable to configure etcd cluster

Error: https://github.com/Azure/aks-engine/blob/fa9c6607811b7393dc6d9bdb5fe9f0cc27d5bf0f/parts/k8s/cloud-init/artifacts/cse_helpers.sh#L15

```
Deployment failed. Correlation ID: 57c24174-1b7c-4e11-a5dd-6541ce922ec2. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=15\n[stdout]\n\n[stderr]\nConnection to k8s.gcr.io 443 port [tcp/https] succeeded!\nConnection to gcr.io 443 port [tcp/https] succeeded!\nConnection to docker.io 443 port [tcp/https] succeeded!\n\"."
      }
```

**What you expected to happen**:
I expected the etcd to be configured correctly.

**How to reproduce it** (as minimally and precisely as possible):
I followed: https://github.com/Azure/aks-engine/blob/1b082728b0a68c695dc10af17a191ef371919756/docs/kubernetes/windows.md

When I deploy the kubernetes.config file like this:
`az group deployment create --name plangk8swin1-deploy --resource-group k8s-win1 --template-file "./_output/plangk8swin1/azuredeploy.json" --parameters "./_output/plangk8swin1/azuredeploy.parameters.json"`

After a few minutes I get the error message.

**Anything else we need to know**:
the config file is below:(note that we have our private VNet but this also failed without privateCluster being enabled and without the custom VNet.

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.14",
      "kubernetesConfig": {
          "privateCluster": {
            "enabled": true
        },
        "addons": [
          {
            "name": "kubernetes-dashboard",
            "enabled": true
          }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "k8stest3",
      "vmSize": "Standard_D2_v3",
      "vnetSubnetId":"<REDACTED_PRIVATE>t",
      "FirstConsecutiveStaticIP" : "<REDACTED_PRIVATE>",
      "agentVnetSubnetId": "<REDACTED_PRIVATE>",
      "vnetCidr": "<REDACTED_PRIVATE>"
    },
    "agentPoolProfiles": [
      {
        "name": "windowspool2",
        "count": 2,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows",
        "osDiskSizeGB": 128,
        "extensions": [
            {
                "name": "winrm"
            }
        ],
        "vnetSubnetId": "<REDACTED_PRIVATE>"
      }
    ],
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": "<REDACTED_PRIVATE>",
      "sshEnabled": true
    },
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<REDACTED_PRIVATE>"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "<REDACTED_PRIVATE>",
      "secret": "<REDACTED_PRIVATE>"
    },
    "extensionProfiles": [
      {
        "name": "winrm",
        "version": "v1"
      }
    ]
  }
}
```

**Comment by CecileRobertMichon** [comment]
@andremakram when was this approximately? There's an ongoing outage (see https://azure.microsoft.com/en-us/status/).

**Comment by andremakram** [comment]
@CecileRobertMichon, it's been 2-3 days. So this happened yesterday as well.

**Comment by CecileRobertMichon** [comment]
@andremakram I will try to repro this with your apimodel. We haven't seen this error in any of our CI recently so it might be due to a specific cluster configuration. In the meantime, could you please fetch logs from your master-0 VM: `sudo journalctl -u etcd`, `systemctl status etcd`. Also, try to `systemctl start etcd` and see if that succeeds.

**Comment by CecileRobertMichon** [comment]
I couldn't repro this with the apimodel you provided with aks-engine version 0.34.3. Did you retry multiple times? It's possible that this was a flake if it only happened once. If not, it might be an issue with your vnet since that's the only only thing that differs between my deployment and yours.

**Comment by andremakram** [comment]
@CecileRobertMichon, thanks for looking. The output of the commands is below. 

It seems that etcd is actually installed properly but something else is wrong. Do you have any suggestion what I might try to figure out what could be going wrong with the VNet? The Vnet was setup a while back and we've been using it successfully for other Azure services.

I tried this multiple times and it still failed. I tried without a VNet before and I got the same error. I will try again without the VNet. I wonder if there is something wrong with our subscription or my user access that might have caused this.

**sudo journalctl -u etcd**

sudo: unable to resolve host k8s-master-32040618-0: Connection timed out
-- Logs begin at Thu 2019-05-02 22:16:41 UTC, end at Fri 2019-05-03 20:27:16 UTC. --
May 02 22:22:12 k8s-master-32040618-0 systemd[1]: Stopped etcd - highly-available key value store.
May 02 22:22:12 k8s-master-32040618-0 systemd[1]: Starting etcd - highly-available key value store...
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresponding flag
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: etcd Version: 3.2.25
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: Git SHA: 182de1a9e
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: Go Version: go1.8.7
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: Go OS/Arch: linux/amd64
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: setting maximum number of CPUs to 2, total number of available CPUs is 2
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: found invalid file/dir lost+found under data dir /var/lib/etcddisk (Ignore this if you are upgrading etcd)
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: peerTLS: cert = /etc/kubernetes/certs/etcdpeer0.crt, key = /etc/kubernetes/certs/etcdpeer0.key, ca = , trusted-ca = /etc/kubernetes/certs/ca.crt, client-cert-auth = true
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: listening for peers on https://10.151.23.122:2380
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: listening for client requests on 10.151.23.122:2379
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: listening for client requests on 127.0.0.1:2379
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: name = k8s-master-32040618-0
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: data dir = /var/lib/etcddisk
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: member dir = /var/lib/etcddisk/member
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: heartbeat = 100ms
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: election = 1000ms
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: snapshot count = 100000
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: advertise client URLs = https://10.151.23.122:2379
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: initial advertise peer URLs = https://10.151.23.122:2380
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: initial cluster = k8s-master-32040618-0=https://10.151.23.122:2380
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: starting member d96b0e72c7a83586 in cluster 6b1f2318dbdea0ae
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: d96b0e72c7a83586 became follower at term 0
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: newRaft d96b0e72c7a83586 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: d96b0e72c7a83586 became follower at term 1
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: simple token is not cryptographically signed
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: starting server... [version: 3.2.25, cluster version: to_be_decided]
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: d96b0e72c7a83586 as single-node; fast-forwarding 9 ticks (election ticks 10)
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: ClientTLS: cert = /etc/kubernetes/certs/etcdserver.crt, key = /etc/kubernetes/certs/etcdserver.key, ca = , trusted-ca = /etc/kubernetes/certs/ca.crt, client-cert-auth = true
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: d96b0e72c7a83586 cannot campaign at term 1 since there are still 1 pending configuration changes to apply
May 02 22:22:12 k8s-master-32040618-0 etcd[15838]: added member d96b0e72c7a83586 [https://10.151.23.122:2380] to cluster 6b1f2318dbdea0ae
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: d96b0e72c7a83586 is starting a new election at term 1
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: d96b0e72c7a83586 became candidate at term 2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: d96b0e72c7a83586 received MsgVoteResp from d96b0e72c7a83586 at term 2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: d96b0e72c7a83586 became leader at term 2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: raft.node: d96b0e72c7a83586 elected leader d96b0e72c7a83586 at term 2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: setting up the initial cluster version to 3.2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: set the initial cluster version to 3.2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: published {Name:k8s-master-32040618-0 ClientURLs:[https://10.151.23.122:2379]} to cluster 6b1f2318dbdea0ae
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: ready to serve client requests
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: serving client requests on 10.151.23.122:2379
May 02 22:22:13 k8s-master-32040618-0 systemd[1]: Started etcd - highly-available key value store.
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: enabled capabilities for version 3.2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: ready to serve client requests
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: serving client requests on 127.0.0.1:2379
----
**systemctl status etcd**

● etcd.service - etcd - highly-available key value store
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-02 22:22:13 UTC; 22h ago
     Docs: https://github.com/coreos/etcd
           man:etcd
 Main PID: 15838 (etcd)
    Tasks: 10
   Memory: 8.4M
      CPU: 4min 56.365s
   CGroup: /system.slice/etcd.service
           └─15838 /usr/bin/etcd --name k8s-master-32040618-0 --peer-client-cert-auth --peer-trusted-ca-file=/etc/kubernetes/certs/ca.crt --peer-cert-file=/etc/kubernetes/certs/etcdpeer0.crt --peer-key-file=/etc/kubernetes/certs/etcdpeer0.key --initial-advert

May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: raft.node: d96b0e72c7a83586 elected leader d96b0e72c7a83586 at term 2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: setting up the initial cluster version to 3.2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: set the initial cluster version to 3.2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: published {Name:k8s-master-32040618-0 ClientURLs:[https://10.151.23.122:2379]} to cluster 6b1f2318dbdea0ae
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: ready to serve client requests
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: serving client requests on 10.151.23.122:2379
May 02 22:22:13 k8s-master-32040618-0 systemd[1]: Started etcd - highly-available key value store.
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: enabled capabilities for version 3.2
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: ready to serve client requests
May 02 22:22:13 k8s-master-32040618-0 etcd[15838]: serving client requests on 127.0.0.1:2379

----
**systemctl start etcd**

Asked me for a password but I don't have a password for the linux box.

**Comment by CecileRobertMichon** [comment]
hmm so it looks like etcd is actually running fine. Can you try `sudo etcdctl cluster-health`?

**Comment by andremakram** [comment]
@CecileRobertMichon

**sudo etcdctl cluster-health**

sudo: unable to resolve host k8s-master-32040618-0: Connection timed out
member d96b0e72c7a83586 is healthy: got healthy result from https://10.151.23.122:2379
cluster is healthy

**Comment by CecileRobertMichon** [comment]
it looks like a DNS issue... Are you doing anything special with your VNET? Any firewall or blocked outbound traffic? Are you using Azure DNS?

**Comment by andremakram** [comment]
So the issue seemed to be that the linux box didn't have the Vm name in the hosts file. But now I'm stuck because if i delete my deployment and re-run it, I see the same problem. If I fix the linux box, I cannot continue the deployment because the error is persisted somewhere.

Any idea how to add code so that I can add the linux box to the hosts file?
