### ISSUE TITLE
Moving images from gcr/dockerhub/quay

### ISSUE THREAD

**Issue by jchauncey** [Azure/aks-engine#1218]
This is the catch all issue for moving the images used in a provisioned kubernetes cluster from depending on outside services like gcr/quay/dockerhub to one owned an maintained by the upstream containers team. 

The following list are images that represent those that will need to be changed:

```
addon-resizer
cluster-autoscaler
coredns
exechealthz-amd64
k8s-dns-dnsmasq-nanny-amd64
k8s-dns-kube-dns-amd64
k8s-dns-sidecar-amd64
kube-addon-manager-amd64
kubernetes-dashboard-amd64
metrics-server-amd64
rescheduler
tiller
k8s-device-plugin
virtual-kubelet
```
There may be others so when this work is done we need to check to make sure we are not missing any.

**Comment by jchauncey** [comment]
Question is whether this is the only place I need to update: 

https://github.com/Azure/aks-engine/blob/master/pkg/api/k8s_versions.go

**Comment by mboersma** [comment]
See also @cpuguy83's work in #797.

**Comment by andyzhangx** [comment]
be careful about this bug: [image pull error from ACR anonymous repository](https://github.com/andyzhangx/demo/blob/master/issues/acr-issues.md#2-image-pull-error-from-acr-anonymous-repository), it's only fixed in some higher k8s versions

**Comment by jchauncey** [comment]
sounds good
