### ISSUE TITLE
Disable addons not supported on Azure Stack

### ISSUE THREAD

**Issue by jadarsie** [Azure/aks-engine#1224]
**Is this a request for help?**:
No

**Is this an ISSUE or FEATURE REQUEST?**:
Feature

**What version of aks-engine?**:
Latest

**What happened**:
Azure Stack does not support all the addons that AKSe deploys by default.
Some of the optional addons are not supported either or were not yet validated.

**What you expected to happen**:
AKSe to ignore the input json and not deploy those addons

List of addons to block:
- AAD Pod Identity
- ACI Connector
- Cluster Autoscaler
- Blobfuse Flex Volume
- SMB Flex Volume
- KeyVault Flex Volume
- Rescheduler
- NVIDIA Device Plugin
- Container Monitoring

**Comment by jadarsie** [comment]
> **Anything else we need to know:**
> How to document this difference in behavior between Azure / Azure Stack?

@mboersma I am considering creating a new page to explain what addons people should expect to work on Azure Stack. Would you rather add that info to an existing page? which one?

**Comment by CecileRobertMichon** [comment]
@jadarsie I'll let you close this if it's fixed.
