### ISSUE TITLE
Document how to configure gMSA with windows containers

### ISSUE THREAD

**Issue by jsturtevant** [Azure/aks-engine#1225]
**Is this a request for help?**: no

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): feature request (documentation)

---

**What version of aks-engine?**: all

---

**Kubernetes version**:
all

**What happened**:
There is no documentation on how to set up gmsa.  

**What you expected to happen**:
Sample and documentation for this common use case.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/

**Comment by techbunny** [comment]
Are you looking for end-to-end documentation for this or just the AKS-Engine specifics?  Creating GMSAs in AD is documented here (https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts) and the kubernetes specific details are in the link you provided.  So the AKS-Engine specific part would be how to domain-join the nodes to access the AD for the GMSA.

**Comment by jsturtevant** [comment]
I was thinking a [tutorial](https://github.com/Azure/aks-engine/tree/master/docs/tutorials) or [how-to](https://github.com/Azure/aks-engine/tree/master/docs/howto) that would show how to deploy into custom vnet, set the appropriate flags in aks-engine via model and setting up the domain-join.  Since this is a popular ask wanted to make sure it was easy to figure out instead of in several different places.

**Comment by georgewen** [comment]
has anyone figured out how to domain join a windows node within aks? I am trying to do the same but can't find any documenatation on it.

**Comment by rexhinvorpsi** [comment]
Yeah same here
