### ISSUE TITLE
Pull request template has broken link

### ISSUE THREAD

**Issue by ryanhartje** [Azure/aks-engine#124]
**Is this a request for help?**:
Nope
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
master branch at least
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
n/a

**What happened**:
The PR template has a broken link to the pull request best practices. I don't see the template checked in, so I imagine an admin of this project needs to update this. It currently says:
```
<!--
Thanks for sending a pull request!  Here are some tips for you:
1. If you want *faster* PR reviews, read how: https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#best-practices-for-faster-reviews
-->
```

**What you expected to happen**:
That link should point to:
https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#best-practices-for-faster-reviews

**How to reproduce it** (as minimally and precisely as possible):
Make a PR

**Anything else we need to know**:
Nope, simply one line fix.

**Comment by CecileRobertMichon** [comment]
Fixed (in aks-engine)! Thanks @ryanhartje
