### ISSUE TITLE
Cannot deploy Kubernetes cluster (Custom data in OSProfile exceeds 87380 characters)

### ISSUE THREAD

**Issue by bclau** [Azure/aks-engine#1260]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of aks-engine?**:v0.35.1, v0.35.0

---

**Kubernetes version**: v1.14.1

**What happened**:

Tried to deploy a Kubernetes cluster using the following ``kubernetes.json`` file: [1] (some fields have been redacted: keys, passwords, etc.)

[1] https://paste.ubuntu.com/p/8c9dFbnKk9/

After the files have been generated, the deployment failed:

    Deployment failed. Correlation ID: 2c152cc5-6d99-4ede-b1bd-312dedc1cb87. {
      "error": {
        "code": "InvalidParameter",
        "message": "Custom data in OSProfile must be in Base64 encoding and with a maximum length of 87380 characters.",
        "target": "customData"
      }
    }

This issue no longer appears when the ``kubernetesConfig`` field is reduced to only contain ``azureCNIURLLinux`` and ``azureCNIURLWindows``.

**What you expected to happen**:

The deployment should have been successful.

**How to reproduce it** (as minimally and precisely as possible):

    ./aks-engine generate kubernetes.json # [1]
    cd _output/dns-name
    az group create -l eastus -n dns-name
    az group deployment create -g dns-name -n k8s-deployment -template-file azuredeploy.json --parameters azuredeploy.parameters.json

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Hi @bclau, you are running into custom data limits. #1251 should help free up some space. In the meantime, is there any reason you are using the `ubuntu` distro or are you able to deploy with `aks` which is a custom AKS image based on ubuntu-16.04 (same image as `ubuntu`) with some pre-installed components.

**Comment by bclau** [comment]
Hello. I haven't tried the ``aks`` engine. But it's good to know that this issue is getting fixed.

**Comment by CecileRobertMichon** [comment]
I highly recommend that you give `"distro": "aks"` a try... It's the default value for aks-engine deployments. It allows faster and more reliable deployments.

**Comment by adelina-t** [comment]
@CecileRobertMichon  We are using distro: ubuntu because in e2e testing we need to use a custom hyperkube. See https://github.com/Azure/aks-engine/issues/342 for reference.

**Comment by bclau** [comment]
@CecileRobertMichon It seems that there is an error when trying to deploy a cluster with the ``aks`` distro: [1]

    Deployment failed. Correlation ID: b2ad14d7-741d-4fe3-a422-040a6a57bb9c. {
      "error": {
        "code": "PropertyChangeNotAllowed",
        "message": "Changing property 'customData' is not allowed.",
        "target": "customData"
      }
    }


[1] https://paste.ubuntu.com/p/fyrhKYjH9y/

**Comment by CecileRobertMichon** [comment]
@bclau that error indicates that ARM is trying to modify an existing VM. You might have been reusing the same dnsPrefix or redeployed before the resource group had finished deleting. Can you try again with a different dnsPrefix/resource group?

**Comment by Kuzbekov** [comment]
Hi @CecileRobertMichon 
I faced the same problem with almost default config https://pastebin.com/MeHzTdSx
Looks like it does not reproduce with "OrchestratorVersion": "1.14.1"
