### ISSUE TITLE
Kubernetes LB doesn't respect externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by sylus** [Azure/aks-engine#1269]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of aks-engine?**: v0.31.1

---

**Kubernetes version**: v1.12.5

**What happened**:

Kubernetes LB doesn't respect externalTrafficPolicy: Local

```
Type Reason Age From Message
---- ------ ---- ---- -------
Normal EnsuringLoadBalancer 21m service-controller Ensuring load balancer
Normal EnsuredLoadBalancer 19m service-controller Ensured load balancer
```

We did notice that the node gets the right IP but the pod itself gets the IP of the node.

We also tried using Traefik and Istio Gateway Ingress and neither worked.

**What you expected to happen**:

Kubernetes LB respects externalTrafficPolicy: Local

**How to reproduce it** (as minimally and precisely as possible):

Try on any deployed AKS-Engine cluster.

**Anything else we need to know**: N/A

**Comment by jackfrancis** [comment]
@slack does this ring a bell?
