### ISSUE TITLE
[docs] roadmap.md is referenced but not in this repo

### ISSUE THREAD

**Issue by nschonni** [Azure/aks-engine#127]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
N/A
---

**Kubernetes version**:
N/A

**What happened**:
N/A

**What you expected to happen**:
The referenced roadmap.md exists in docs/roadmap folder

**How to reproduce it** (as minimally and precisely as possible):
Go to https://github.com/Azure/aks-engine/blob/f4f9637a6a0fec75295201dc02236d8227f6d103/docs/roadmap/releases.md and click on the "aks-engine Roadmap" link.

**Anything else we need to know**:
Not sure if the file ever existed or is still pending a push

**Comment by mboersma** [comment]
The docs have been refactored significantly, and this broken link no longer exists.
