### ISSUE TITLE
AKS-Engine upgrade failed ARM template

### ISSUE THREAD

**Issue by mzack18081985** [Azure/aks-engine#1278]
**Is this a request for help?**:

yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue

**What version of aks-engine?**:

v0.35.1

If this is a ISSUE, please:
Upgrade from 1.11.5 to 1.12.8 failed with ARM Template error.

**Kubernetes version**:
1.11.5

**What happened**:
Error: upgrading cluster: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplate" Message="Deployment template validation failed: 'The resource 'Microsoft.Network/networkSecurityGroups/k8s-master-37191916-nsg' at line '1' and column '26450' is defined multiple times in a template. Please see https://aka.ms/arm-template/#resources for usage details.'."

**Comment by CecileRobertMichon** [comment]
@mzack18081985 what aks-engine version and apimodel (cluster config) was the cluster originally created with?

**Comment by mzack18081985** [comment]
Hi, i think i found the problem. We had in the cluster config a jumpstation and it looks like that the generated arm template with jumpstation are not working anymore. After i deleted the jumpstation from the template the deployment worked.

**Comment by jackfrancis** [comment]
Please re-open if there's anything in AKS Engine's template generation implementation could be improved to remove this edge case, thanks!
