### ISSUE TITLE
Refactor: unify generate and deploy commands

### ISSUE THREAD

**Issue by ohthehugemanatee** [Azure/aks-engine#1281]
**Is this a request for help?**:
---
No.

**Proposal**
---
Deploy and Generate commands do a lot of the same things, and end up duplicating a lot of each others code. It's more reliable and maintainable to unify these code paths. 

Ideally `deploy` should be `generate` plus one or two extra functions.

Proposed flow:

* FilterInput: Runs any changes to the user input. eg normalizing location names.
* MergeAPIModel: merges CLI arguments with the API model defaults, produces a combined .json 
* LoadAPIModel: loads the combined json
* AutofillAPIModel: creates any generated default values
* ValidateAPIModel: validates the final containerService against a fixed set of rules
* GenerateTemplate: saves to files
* (deploy only) deployTemplate

With this flow we can properly unit test each requirement, with one test instead of two. And we get a concrete set of validation criteria for *outputs*, effectively defining the interface with the ARM template generator and Azure underlay. If it's helpful for documentation, we can also validate inputs as a way of defining the interface with AKS.

**Comment by ohthehugemanatee** [comment]
@craiglpeters  @CecileRobertMichon @jackfrancis  request for comment before I start hacking on this. :)

**Comment by jackfrancis** [comment]
Thanks for scaffolding this out! Usually we do data model validation after what you've called the `LoadAPIModel` step, and before default property assignment/expansion. Basically, by the time we send an opinionated, but incomplete, input data representation through the defaults flow, we want to ensure that the configuration combinatorics are sane and mutually functional.

**Comment by CecileRobertMichon** [comment]
Sounds great. Thanks for taking the initiative here.

+1 on what Jack said above, I think we want to 1) auto-generate missing values that are unique per cluster (like SSH keys and DNS prefix) 2) Validate 3) Fill out default properties (ie. Network plugin, enabled addons, etc.).

**Comment by ohthehugemanatee** [comment]
that makes sense, and it's probably more readable. BUT you do miss out on the completeness of your validation...

Anyway I won't argue about the precise steps - you know this tool far better than me! The important part (to me) is unifying the code path. :)

One other question: are there any differences in how `deploy` generates its ARMs, compared to `generate`? Or is the deploy command really as simple as generate + deploy? I want to make sure I'm not missing something huge here.
