### ISSUE TITLE
Support using existing user assigned identity to create a cluster

### ISSUE THREAD

**Issue by norshtein** [Azure/aks-engine#1284]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): feature request

Can we support using existing user assigned identity to create a cluster? I'm glad to implement this if you agree to support this feature 😄 .

**Comment by andyzhangx** [comment]
I think it already supports user assigned identity, I have tried below config before:
```
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.14.1",
      "kubernetesConfig": {
        "useManagedIdentity": true,
        "userAssignedID": "USER-ASSIGNED-ID"
      }
    },
```

**Comment by norshtein** [comment]
Hi @andyzhangx The example you mentioned is used for creating a new user assigned identity with name `USER-ASSIGNED-ID`, it does not support using existing user assigned identity.

**Comment by andyzhangx** [comment]
@norshtein if using existing user assigned identity, aks-engine will report error while it still work. I think you could fix the error report msg at least.

**Comment by norshtein** [comment]
What's the error message and how to reproduce the error? As far as I know, creating two user assigned identities having the same name in different resource group is allowed. And AKS-Engine creates resources in a new resource group, so set `userAssignedID` to existing identity's name is valid.

**Comment by andyzhangx** [comment]
the error message is like `RoleAssignment` failed since I already assigned current resource group as `Contributor` role. Here are my steps:
 - create a new resource group and a new managed identity in that resource group
 - assign the new managed identity current resource group as `Contributor` role
 - create k8s cluster by assign by specifying the existing managed identity

**Comment by norshtein** [comment]
@andyzhangx Got your point. This should be expected behavior. In my opinion, to support using existing user assigned identity, instead of reusing `orchestratorProfile.kubernetesConfig.userAssignedID`, we may want to introduce a new property. This saves us from ambiguousness and complex logic.

**Comment by norshtein** [comment]
Hi @CecileRobertMichon  @jackfrancis @mboersma , any thought on this topic?

**Comment by jackfrancis** [comment]
Hmm, there is no "create if not exist"-equivalent declarative spec we can specify in ARM template?

**Comment by norshtein** [comment]
For some resources, ARM does an incremental deployment. So for @andyzhangx 's example, the error message is not `IdentityAlreadyExist` but is `RoleAssignmentAlreadyAssigned`, which indicates the ARM does an incremental deployment for the user assigned identity, otherwise it will report an error complaining the identity already exists.

But incremental deployment is not the key problem. To use existing user assigned identity, the identity may in other resource groups, so it should take a unique identifier such as the resource id. That's why I think we should introduce a new property. When AKS-engine founds the cluster is using an existing user assigned identity, it does not generate its definition in ARM template, but directly use the resource id in VM(or VMSS)'s `identity` definition.

**Comment by norshtein** [comment]
Friendly ping @jackfrancis

**Comment by jackfrancis** [comment]
We would definitely accept this feature :)

**Comment by norshtein** [comment]
Cool. I have drafted a PR to implement this feature:https://github.com/norshtein/aks-engine/pull/1
 I added a struct `ExistingUserAssignedIdentityProfile` in `orchrstratorProfile.KubernetesConfig` to accept existing user assigned identity information. We may want to discuss the struct name and where should we add it.

**Comment by elutsky** [comment]
Any updates on this? 
This hurting us each time we are creating a new cluster :(

**Comment by devigned** [comment]
Related: https://github.com/Azure/aks-engine/pull/2238
