### ISSUE TITLE
Question: AKS Windows supports custom vnet, AKS-E doesn't

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#1289]
I joined the AKS Windows private preview today, I found it supports custom vnet for hybrid Linux and Windows cluster. As far as I know AKS-E deploy and scale doesn't work with custom vnet  yet, see #210 #431.

From my understanding AKS is based on AKS-E, one of tags in my created AKS Windows pool is `aksEngineVersion : v0.33.4-aks`. I am wondering how this happend, does the AKS team fixed this issue on their branch, if it is yes, can you merge that back to AKS-E?

**Comment by jackfrancis** [comment]
Confirmed. (root cause unknown)

**Comment by zhiweiv** [comment]
So will we make some changes to align AKS-E with AKS for custom vnet support?

**Comment by jackfrancis** [comment]
Yes, I've labeled this as a bug.
