### ISSUE TITLE
Include k8s 1.13.6 version as it includes important fixes

### ISSUE THREAD

**Issue by mo-saeed** [Azure/aks-engine#1301]
**Is this a request for help?**: YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):FEATURE REQUEST

---

**What version of aks-engine?**: latest

---

Please include latest versions of k8s (1.13.6) as it has important fixes for azure LB API and new Azure SDK 
https://github.com/kubernetes/kubernetes/pull/76993

---
**Kubernetes version**:
1.13.6

**Comment by mboersma** [comment]
#1262 merged a week ago and it will appear in the next AKS Engine release (minor or patch). For now, you can build `aks-engine` from source to get Kubernetes v1.13.6 support.

**Comment by mo-saeed** [comment]
@mboersma Thank you, any estimation when will be the next release of aks-engine ?

**Comment by mboersma** [comment]
We want to include 1.14.2 support as well, so that requires a new VHD build which is already in progress. Then we'll do a release, so probably tomorrow (Friday).

**Comment by mboersma** [comment]
@mo-saeed [AKS Engine v0.36.0](https://github.com/Azure/aks-engine/releases/tag/v0.36.0) is out, with support for Kubernetes v1.13.6 and v1.14.2.
