### ISSUE TITLE
unit tests should be quieter

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#1302]
**Is this a request for help?**:

No.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

FEATURE REQUEST.

---

**What version of aks-engine?**:

master

---

**How to reproduce it** (as minimally and precisely as possible):

Run `make test` and then wade through the command output, desperately trying to locate the test case that made the suite FAIL.

Ideally the tests should only print `stdout` / `stderr` when one fails. If tests are green I would like to see only the test case names printed in `-v`erbose mode.

**Anything else we need to know**:

**Comment by rudolphjacksonm** [comment]
I could maybe take a look at this if I have free time in the next few weeks
