### ISSUE TITLE
Coredns restarts a lot in k8s because of OOM kill

### ISSUE THREAD

**Issue by gowthamboddapati** [Azure/aks-engine#1303]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
aks-engine v0.34.3

---

**Kubernetes version**:
K8s version: 1.14.1 

**What happened**:
coredns on master node restarts a lot. The exit reason is OOM killed. I have increased the k8s coredns resource limit from 170mi to 512Mi still I see coredns restarts because of OOM killed but little less frequent. 
I have tried going down a version from 1.3.1 to 1.2.6 by modifying the: /etc/kubernetes/addons/coredns.yaml but still the same issue.  But if we deploy aks-engine v0.31.2 (but this release has some other issues) which has coredns 1.2.6 version as default we don't see the memory consumption pattern.

azureuser@k8s-master-17103577-0:/etc/kubernetes/addons$ kubectl top pods -n kube-system |grep -i core
NAME                                            CPU(cores)   MEMORY(bytes)
coredns-8484bf8d55-fx5m9                        230m         363Mi
 

Describe pod:

     Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Running
      Started:      Wed, 15 May 2019 07:20:28 +0000
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 15 May 2019 01:43:18 +0000
      Finished:     Wed, 15 May 2019 07:20:17 +0000
    Ready:          True
    Restart Count:  1
    Limits:

**What you expected to happen**:
CoreDNS is stable and doesn't restart. 

**How to reproduce it** (as minimally and precisely as possible):
I am not sure how to reproduce it. But it happens every single time with the workloads we deploy to k8s cluster. The cluster deployed is a single master and 5 windows worker nodes. Windows nodes are running "2019-Datacenter-Core-with-Containers-smalldisk". Windows nodes generate large number of DNS request to widely varying domain names. 

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
Hi @gowthamboddapati, is this a hybrid cluster, i.e., is there a linux node pool to schedule additional coredns replicas onto? Is it possible the single master is the only schedulable node for coredns and it's being overloaded?

**Comment by gowthamboddapati** [comment]
@Jack Francis<mailto:Jack.Francis@microsoft.com> The cluster has single linux master node. I am not sure about master node not having resources. Since when I modify the coredns.yaml file to set replicas to 3 it does bring up 3 replicas.

I see that coredns is being overloaded. But I don’t see coredns is scaling. I see that coredns autoscaler is not on by default.  Is there a way during installation I say enable coredns auto scaler?

**Comment by jackfrancis** [comment]
dns-horizontal-autoscaler is not currently deployed automatically with clusters, so you'd have to add that functionality yourself

However, I think the operational scenario you require isn't going to work with a single master vm. I'd recommend at least 3 masters (AKS Engine allows clusters with 1, 3, or 5 master vms at present).

**Comment by slayercao** [comment]
hello, i got the same issue.
by default, my k8s cluster has 2 coredns pods, and these 2 pods keeps restarting for "OOM killed". the version is k8s.gcr.io/coredns:1.2.6. i tried reboot my VM and kubelet/docker service, but it doesn't work.
