### ISSUE TITLE
Unable to create multiple master nodes with custom VNet installed

### ISSUE THREAD

**Issue by yarinm** [Azure/aks-engine#1313]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
 v0.35.1
also happened with
v0.32.3
---

**Kubernetes version**:

1.12.7
**What happened**:
I've created the following custom vnet:
`{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {  },
    "variables": {  },
    "resources": [
      {
        "apiVersion": "2018-06-01",
        "location": "[resourceGroup().location]",
        "name": "AKSCustomVNet",
        "properties": {
          "addressSpace": {
            "addressPrefixes": [
              "10.77.60.0/22"
            ]
          },
          "subnets": [
            {
              "name": "AKSMasterSubnet",
              "properties": {
                "addressPrefix": "10.77.60.0/26"
              }
            },
            {
              "name": "AKSAgentSubnet",
              "properties": {
                "addressPrefix": "10.77.62.0/23"
              }
            }
          ]
        },
        "type": "Microsoft.Network/virtualNetworks"
      }
    ]
  }`

And I've tried to create a cluster with several master nodes using this template:
`{
  "apiVersion": "vlabs",
  "properties": {        
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.12.7",
      "kubernetesConfig": {
        "enableEncryptionWithExternalKms": true
      }
    },    
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "rs2aks",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/XXXX/resourceGroups/YYYY/providers/Microsoft.Network/virtualNetworks/AKSCustomVNet/subnets/AKSMasterSubnet",
      "firstConsecutiveStaticIP": "10.77.60.20"
    },
    "agentPoolProfiles": [
      {
        "name": "rs2aksagent",
        "count": 5,
        "vmSize": "Standard_D8s_v3",
        "vnetSubnetId": "/subscriptions/XXXX/resourceGroups/YYYY/providers/Microsoft.Network/virtualNetworks/AKSCustomVNet/subnets/AKSAgentSubnet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "..."
          }
        ]
      }
    },
    "servicePrincipalProfile": {
     ...
    }
  }
}
`
When I try to deploy the generate templates to azure two out of three of the k8s-master NICs fail to deploy with this error:
{
  "error": {
    "code": "PrivateIPAddressIsAllocated",
    "message": "IP configuration /subscriptions/XXXX/resourceGroups/YYYY/providers/Microsoft.Network/networkInterfaces/k8s-master-79482307-nic-2/ipConfigurations/ipconfig1 is using the private IP address 10.77.60.22 which is already allocated to resource /subscriptions/915a0b56-b689-45ac-877c-44041b3e4b68/resourceGroups/aks-engine-test/providers/Microsoft.Network/networkInterfaces/k8s-master-79482307-nic-0.",
    "details": []
  }
}

it seems that all of them are deployed using the same address.
**What you expected to happen**:
Master NICs to deploy successfully

**How to reproduce it** (as minimally and precisely as possible):
Probably using the provided JSONs

**Anything else we need to know**:
I tried to change firstConsecutiveStaticIP field to start / end / middle of subnet range and I still got the same problem.

**Comment by yarinm** [comment]
Note: I've tried to add the "vnetCidr" field but I kept getting the same error during deployment.

**Comment by CecileRobertMichon** [comment]
@yarinm see https://github.com/Azure/aks-engine/blob/master/examples/e2e-tests/kubernetes/release/default/definition.json for a working example of using custom vnet with multiple masters. I think you're missing the clusterSubnet field.

**Comment by yarinm** [comment]
@CecileRobertMichon Even when using clusterSubnet field I get the same problem. Clearly there's some sort of bug in the ARM template that is generating.

**Comment by yarinm** [comment]
Okay so the bug here is that the first NIC that is setup defines one "static" IP and 31 dynamic ones. since my subnet has only 64 addresses it causes the conflict. Why do we need 31 dynamic addresses?

**Comment by CecileRobertMichon** [comment]
Ah yes, you're subnet needs to be big enough. See https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#custom-vnet for recommendations and explanation of the 31 addresses.
