### ISSUE TITLE
Skipping minor version upgrade in AKS will fail on orchestrator tag check

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#132]
When AKS deprecates 1.8, upgrades from 1.7 to 1.9 will need to be allowed. Right now, this will fail because 1.8 is not deprecated in aks-engine and the check on the node version will only allow upgrade to the next minor version: https://github.com/Azure/aks-engine/blob/master/pkg/operations/kubernetesupgrade/upgradecluster.go#L283

aks-engine also performs an overall upgrade validation based on the cluster state at: https://github.com/Azure/aks-engine/blob/azure-cni/cmd/upgrade.go#L180

Skipping minor version when the next minor is deprecated is supported in both aks-engine and AKS at the moment. However, aks-engine validates upgrade during the node upgrade using its own supported versions.

The options to fix this are:

 a) deprecate 1.7 and 1.8 in aks-engine too, 
b) remove the second upgrade validation check per node in acs-engine,
c) change the upgrade check policy so it's more permissive of skipping minor versions (dangerous)

**Comment by tariq1890** [comment]
Our supportVersion matrix should be a super-set of the AKS matrix (or at the very least, directly mappable)

**Comment by CecileRobertMichon** [comment]
@tariq1890 it is a super-set, the issue here is that aks-engine upgrade does validation of node version that is based on supported versions and only allows to skip a minor version if the next minor is deprecated, which won't be the case.

I think the easiest way out of this is to deprecate 1.7/1.8 in aks-engine as well but it doesn't fix the underlying design issue of "AKS upgrades do validation in aks-engine using aks-engine supported versions."
