### ISSUE TITLE
Pod networking issues

### ISSUE THREAD

**Issue by fsigalov** [Azure/aks-engine#1320]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
I'm not sure. I don't see a tag on the vm.
---

**Kubernetes version**:
1.8.7

**What happened**:
Most pods are failing to start. We suspect connectivity issues. The cluster was healthy and happy, and all the pods broke around the same time. kube-dns can't start, azsecpack can't start.
Host network has no issues.
CNI team says pod-to-pod networking is working, only pod-to-internet is broken

**What you expected to happen**:
Cluster continues to be healthy

**How to reproduce it** (as minimally and precisely as possible):
I don't know because I don't know what broke the cluster

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Hi @fsigalov, what aks-engine (or acs-engine) version was used to deploy the cluster? https://github.com/Azure/aks-engine/blob/master/docs/tutorials/deploy.md#L147

Also, could you please share the kube-dns logs with us? Any chance your Service Principal expired?

Also, any reason the cluster is on 1.8.7? 1.8 is deprecated in aks-engine so I would recommend upgrading to a newer k8s version so we can better provide help.

**Comment by fsigalov** [comment]
We had a pipeline create the cluster, and I don't see a reference to what version was used. Any way to find out from inside the cluster?
kube-dns is failing to start and so I can't see any logs. But I can ssh to the node, if you want any log from there?
We've verified from a node that the SP stored on the cluster is correct. ssh from master to node uses the same SP to talk to Azure. But from inside the pod, it's failing to log in to azure.
We are working on migrating to a 1.12 cluster.

**Comment by CecileRobertMichon** [comment]
You should still be able to see an error message about why the pod is failing to start. For example:
```
kubectl logs kube-dns-123                    
Error from server (BadRequest): container "kube-dns" in pod "kube-dns-123" is waiting to start: trying and failing to pull image
```

You can use VM tags to determine the aks-engine version. See the [link](https://github.com/Azure/aks-engine/blob/master/docs/tutorials/deploy.md#L147) I sent above on checking those.

**Comment by fsigalov** [comment]
> kubectl logs kube-dns-v20-5d9fdc7448-6x7ml -n kube-system -c kubedns
Error from server (BadRequest): container "kubedns" in pod "kube-dns-v20-5d9fdc7448-6x7ml" is waiting to start: ContainerCreating

  Type     Reason      Age                   From                                Message
  ----     ------      ----                  ----                                -------
  Warning  FailedSync  26s (x51042 over 8d)  kubelet, k8s-agentpool1-26329242-8  Error syncing pod

I checked for vm tags. It doesn’t have one for acs-engine.

**Comment by CecileRobertMichon** [comment]
If you don't have an acs-engine tags it means the cluster is on a version older than [0.17.0](https://github.com/Azure/acs-engine/releases/tag/v0.17.0) since that's when the version tag was added (or that you or someone from your team deleted those tags explicitly, which is less likely). I highly recommend upgrading to get a fresher version of aks-engine (or creating a new cluster and migrating workloads) to get the latest improvements and bug fixes... latest release is [v0.35.1](https://github.com/Azure/aks-engine/releases/tag/v0.35.1).

**Comment by CecileRobertMichon** [comment]
Could you SSH on k8s-agentpool1-26329242-8 and get the kubelet logs? `sudo journalctl -u kubelet`

**Comment by fsigalov** [comment]
I’ve shared the file at \\fsigalov3\public2\kubelet<file://fsigalov3/public2/kubelet> on corpnet

**Comment by CecileRobertMichon** [comment]
have you tried restarting kubelet? `sudo systemctl restart kubelet`

Earlier you said "But from inside the pod, it's failing to log in to azure." what makes you say that?

**Comment by fsigalov** [comment]
I've made a new cluster using k8s 1.12, so I'm going to stop debugging this old cluster and delete it. Thanks for your help!
