### ISSUE TITLE
Coredns deployment tolerates all NoSchedule taints.

### ISSUE THREAD

**Issue by fampton** [Azure/aks-engine#1325]
https://github.com/Azure/aks-engine/blob/279a235d211a671facfa6f24218f7e848a5d939a/parts/k8s/addons/coredns.yaml#L134

For unique hardware we will typically apply a noschedule taint to avoid unnecessary pods getting scheduled onto them. The coredns pod seems to have tolerations for any noschedule taint, which prevents the node from being scaled down by the cluster autoscaler if coredns is scheduled onto it.

**Comment by mboersma** [comment]
This was added in #555. The idea was to ensure core system components could always be scheduled.

@jackfrancis could we revisit the `NoSchedule` taint toleration?

**Comment by jackfrancis** [comment]
I think we want to enable this as an option. @palma21 drove this effort in response to user feedback that folks wanted this prioritized scheduling toleration for coredns and other system components,

**Comment by palma21** [comment]
That sounds like incorrect behavior from the scaling side. Do you have some kind of pod disruption budget? The node should be able to scale down if k8s sees that it can schedule it somewhere else and resources are underutilized.

That said, if you don't want the coredns pods on your specific hardware machines, do remove the toleration on your deployment. We have a number of use cases that will break if we remove it for everyone, but we can certainly revisit.

**Comment by fampton** [comment]
Thanks for confirming this is expected. Modifying the CoreDNS deployment will work.
