### ISSUE TITLE
Add metrics supported by kube-state-metrics to AKS

### ISSUE THREAD

**Issue by victornoel** [Azure/aks-engine#1328]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of aks-engine?**: 0.33.4

---

AKS supports metrics from metrics-server (or is it heapster, it's not clear) to be collected via log analytics.
It would be relevant to also have kube-state-metrics (see [this](https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-vs-metrics-server) for the difference) on the nodes and its metrics collected.

One feature it provides not available on AKS is for example gathering data about killing event and their reason. It is currently not possible to know if a pod has been killed because of OOM.
kube-state-metrics brings this kind of features (see [this](https://stackoverflow.com/a/50563113/9046139) for example).

**Comment by CecileRobertMichon** [comment]
Hello, this looks like an issue for AKS (not the open source project AKS Engine). It should be filed at https://github.com/Azure/AKS/issues. Thanks!

**Comment by victornoel** [comment]
@CecileRobertMichon sure, here it is: Azure/AKS#990, sorry for the confusion :)
