### ISSUE TITLE
Scaling operation should replace nodes that aren't talking to k8s

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#134]
**Is this a request for help?**: 

No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature request

---

**What version of aks-engine?**:

Any;

---

Working on a customer-reported incident, we managed to have some agent node VMs that appeared to be part of the cluster but were not reporting in and could not be seen in `kubectl get nodes`. Since the customer was already on 1.11.5 there was no upgrade path currently. Scaling up and down would not replace these low-numbered nodes, but if we added a k8s connectivity check in the scale code, it would have replaced them and healed the cluster.

**Comment by rocketraman** [comment]
See also issue https://github.com/Azure/acs-engine/issues/2148 which I think is a bit more general than this, and should cover this use case.
