### ISSUE TITLE
Add note in documentation for aks-engine version update

### ISSUE THREAD

**Issue by mo-saeed** [Azure/aks-engine#1365]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of aks-engine?**: All

---

**Kubernetes version**:
All

**What happened**:
No documentation for aks-engine upgrade

**What you expected to happen**:
Just adding this note in the documentation (not sure where exactly) 
```
To upgrade aks-engine version the upgrade command should be run at least one time to upgrade all kubernetes components associated with the new aks-engine version (e.g. moby version, etcd version, addons like azure-cni)
if same kubernetes version is needed then run the upgrade command with  `--force` command.
```

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/aks-engine/blob/master/docs/topics/upgrade.md

**Comment by jackfrancis** [comment]
Hi @mo-saeed, what exactly is missing from the documentation? I assume this is not what you're looking for? https://github.com/Azure/aks-engine/blob/master/docs/topics/upgrade.md

**Comment by mo-saeed** [comment]
Hi @jackfrancis, For me it's just need to be very clear that running `aks-engine upgrade` is necessary for aks-engine version upgrade.
I had a cluster with old aks-engine version and when i tried to scale one node with newer aks-engine then the new node had different moby versions than other nodes. 
It's just for people who are new to the tool to be aware of this fact, for example i assumed scale command with the newer aks-engine version would update kubernetes components (e.g. moby) on all nodes including master which is not the case and it's totally fine but needs to be clarified somewhere in the documentation.
Also would it make sense when running `aks-engine scale` command with newer aks-engine version to update all k8s components associated with the newer version ?

**Comment by jackfrancis** [comment]
That's all fair, let's leave this ticket open as a forcing function for us to produce improved documentation around scale and upgrade.

Speaking to your last point, I believe we have recently improved our enforcement of automatically moving component versions forward with scale and upgrade. @CecileRobertMichon to confirm?

**Comment by CecileRobertMichon** [comment]
Yes that's correct. Those PRs and this issue were a result of a conversation @mo-saeed and I had on the sig-azure slack.

**Comment by jackfrancis** [comment]
I think you bring up an interesting feature idea @mo-saeed:

- when scaling up, always ensure that all nodes in a node pool have the same implementation (k8s component versions, moby version, etc)

The above is not currently supported, but we could add it as an option

- `aks-engine scale --all-nodes`

Or something like that. Basically:

- add _n_ new nodes
- go back 1 at time through the existing nodes and replace them with nodes that look like the new ones
