### ISSUE TITLE
Document moby container runtime versions

### ISSUE THREAD

**Issue by itaysk** [Azure/aks-engine#1392]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): issue - documentation request

---

**What version of aks-engine?**: not applicable

---

Since Microsoft stopped shipping Docker and now builds their own moby, it's hard to understand which version is being used in my clusters. 3.0.4 does mean much to me other than it's after 3.0.3. 
We'd like more visibility into the build/release process, and the relation to the moby release: If there's a correlation between the versions of MS moby and moby's moby, a simple table would be nice. If not, maybe a commit sha or any other indication so we know what we are actually using.

**Comment by cpuguy83** [comment]
There is not currently a strong correlation.
MS Moby 3.0.5 is pretty close to Docker 19.03.

We actually wanted to include the sha in the version but kubelet does not like this at all.

You can get the commit from the engine itself, however in some cases the commit may not line up with an upstream (moby) commit (due to CVE patches).

I am working upstream to have a more formal release process of the engine that is not tied to Docker CE versions.

In the meantime we'll discuss what we can do to communicate what's in a release.
Do you specific concerns?

**Comment by itaysk** [comment]
My specific concern was to identify 3.0.4, but that trigger another question in our org about how do we even know what's our production is running. For now we're fine with the info we gathered so I don't have further questions, but IMO it's better to keep this issue opened until this is properly documented.

**Comment by LaurentLesle** [comment]
I guess if moby is the upstream of the moby-engine used by AKS and also docker-engine that would help our customers understanding which version of Moby is used in docker-engine and also AKS through moby-engine. At the moment it is a little bit confusing when customers needs a minimum version of Docker-engine 17.03 and says AKS runs 3.0.5. The perception is AKS running a very old version of docker-engine, which is not that case as you says moby-engine 3.0.5 is close from docker-engine

**Comment by cpuguy83** [comment]
I understand the versioning is confusing... heck even within just the Docker CE product itself versioning is confusing to a lot of people (...1.11->1.12->1.13->17.03->17.09->18.03...).

As with most things only checking a version is not all that useful and it's best to test for functionality. Depending on what feature you need this information could be available in response headers or it could be in the output from `docker info` (or `GET /info`).
Probably the easiest thing to do is to check the API version that the engine supports.
The API version is the same between all the things.

I am looking into what we can do to help reduce confusion.
