### ISSUE TITLE
Cilium BPFFS mount unit file is incorrectly gzipped

### ISSUE THREAD

**Issue by UnwashedMeme** [Azure/aks-engine#1393]
https://github.com/Azure/aks-engine/pull/508 introduced, via node custom data, the systemd unit `/etc/systemd/system/sys-fs-bpf.mount`. This works on the master nodes but on a agent/worker node:

(the following on a cluster built with v0.35.1)
```
azureuser@k8s-main-40037667-vmss000008:~$ cat /etc/systemd/system/sys-fs-bpf.mount
41j0E9/VPRR$0.W,GB3"a=Q!Ƣ1})7V1՝|S-/ƬKOZ}X4

## It's gzippped still!
azureuser@k8s-main-40037667-vmss000008:~$ cat /etc/systemd/system/sys-fs-bpf.mount | gunzip 
[Unit]
Description=Cilium BPF mounts
Documentation=http://docs.cilium.io/
DefaultDependencies=no
Before=local-fs.target umount.target
After=swap.target

[Mount]
What=bpffs
Where=/sys/fs/bpf
Type=bpf

[Install]
WantedBy=multi-user.target
```

It looks like when some refactoring/reorganizing got done in https://github.com/Azure/aks-engine/commit/206328a0270c91b8b3dfa6d859eeff56b2f9c51c a small mistake was introduced.
* The unit file itself is a `getBase64EncodedGzippedCustomScript`  [original-patch](https://github.com/Azure/aks-engine/commit/206328a0270c91b8b3dfa6d859eeff56b2f9c51c#diff-af8d8862e75162bcadadbb574ada9e8bR86); it has now moved [on master to here](https://github.com/Azure/aks-engine/blob/master/pkg/engine/armvariables.go#L167)
* In the `masternodecustomdata.yml` it is marked as being `encoding: gzip` [in 206328a](https://github.com/Azure/aks-engine/commit/206328a0270c91b8b3dfa6d859eeff56b2f9c51c#diff-607db9f9c89e7874bd0ef216c92f7e02R163), still present [on master](https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/masternodecustomdata.yml#L144)
* In the `nodecustomdata.yml` the `encoding: gzip` is missing even though it is the same variable reference. [in 206328a](https://github.com/Azure/aks-engine/commit/206328a0270c91b8b3dfa6d859eeff56b2f9c51c#diff-db62d66d8529cd5128f96f21dae13279R158); still missing [on master](https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/nodecustomdata.yml#L145)

**Comment by UnwashedMeme** [comment]
@jackfrancis  any chance you can add the missing `encoding: gzip` line?

**Comment by CecileRobertMichon** [comment]
@UnwashedMeme it looks like you have a good understanding of the issue, would you like to open a PR to fix it? AKS Engine is open source and we welcome contributions.

**Comment by UnwashedMeme** [comment]
I would love to, but CLA issues + my poor build environment means I probably won't get there for a day or two and was just hoping this could get done quickly. :-)

**Comment by UnwashedMeme** [comment]
The CLA has been submitted to legal, so maybe one day I'll be allowed to copy those 14 characters from one place in the file to another.

**Comment by UnwashedMeme** [comment]
Would you like a PR targetting any of the bugfix branches? This patch can be cherry-picked across branches pretty easily.
