### ISSUE TITLE
[Feature Request] new aks-engine update and apply commands

### ISSUE THREAD

**Issue by mo-saeed** [Azure/aks-engine#1404]
**Is this a request for help?**: YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of aks-engine?**: ALL

---

**Kubernetes version**: ALL

**What happened**:
new aks-engine commands `aks-engine update`:
- Open apimodel.json in edit mode (would be nice if apimodel.json can be saved as cluster state file in azure storage bucket/account)
- Change the needed config (e.g. apiserver config, controller-manger config, addons config) 

THEN `aks-engine apply`:
- Apply the changes, either by modifying the manifest and addon files in the master nodes or by calling `aks-engine upgrade (same k8s version) --force`

**What you expected to happen**: 
configuration changes management after cluster creation using aks-engine commands.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by akshaysngupta** [comment]
+1 would be nice to have.

**Comment by mo-saeed** [comment]
https://github.com/Azure/aks-engine/issues/542
