### ISSUE TITLE
ephemeral hostmounts

### ISSUE THREAD

**Issue by posix4e** [Azure/aks-engine#1422]
**Describe the request**
Often times with daemonsets, local replication is a great fast low cost model. Especially with machine learning datasets!
**Explain why AKS Engine needs it**
We uses aks for machine learning and we wanna be able to pre locate the dataset on each local drive before beginning training. Our nodes already have plenty of instance storage
**Describe the solution you'd like**
I'd like to be able to tie back to an ephemeral drive without doing any special configuration on a per  node basis.
**Describe alternatives you've considered**
Writing a container to mount the host to a /data
**Additional context**

**Comment by PatrickLang** [comment]
How would you want to manage it? Do you need to keep it past the pod lifetime? 

It seems like this could work https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/  using the temp disk if you want to persist data past pod lifetime, but are ok losing it if you deprovision the node.

**Comment by posix4e** [comment]
That's exactly what i want

**Comment by posix4e** [comment]
This looks great I'll give it a try

**Comment by andyzhangx** [comment]
Here is the solution to use LSv2 NVME disk as a local persistent volume:
https://github.com/Azure/kubernetes-volume-drivers/tree/master/local
