### ISSUE TITLE
Unable to use Windows Server 2019 release for Windows 

### ISSUE THREAD

**Issue by duggaraju** [Azure/aks-engine#1423]
Using 

      "windowsProfile": {
        "adminUsername": "azureuser",
        "adminPassword": "replacepassword1234$",
        "sshEnabled": true,
        "windowsOffer": "WindowsServer",
        "windowsSku": "2019-Datacenter-Core-with-Containers",
      },

The deployment fails with

Deployment failed. Correlation ID: 71273473-be0e-438b-96e7-555f72489284. {
  "error": {
    "code": "PlatformImageNotFound",
    "message": "The platform image 'MicrosoftWindowsServer:WindowsServer:2019-Datacenter-Core-with-Containers:1809.0.20190314' is not available. Verify that all fields in the storage profile are correct.",
    "target": "imageReference"
  }
}

Looks like OS image version is either hard coded or the default value picked is incorrect.  If I explicitly set the image version

      "windowsProfile": {
        "adminUsername": "azureuser",
        "adminPassword": "replacepassword1234$",
        "sshEnabled": true,
        "windowsOffer": "WindowsServer",
        "windowsSku": "2019-Datacenter-Core-with-Containers",
        "imageVersion": "2019.0.20190521"        
      },
then it works fine.

**Comment by PatrickLang** [comment]
/kind feature

Windows Server 1903 will need a number of updates including the pause image and test images. Marking this as a feature.

**Comment by PatrickLang** [comment]
Actually, the title is a bit wrong. Both releases you referenced are for 1809/2019 which use the same versioning scheme. I'm updating the title and opening a separate issue to track 1903

**Comment by PatrickLang** [comment]
Can you try one of these sets of parameters? I don't think that's a valid SKU. Here's some recent ones:

```
$ az vm image list --publisher MicrosoftWindowsServer --all -o table

Offer                    Publisher                      Sku                                             Urn                                                                                                            Version
-----------------------  -----------------------------  ----------------------------------------------  -------------------------------------------------------------------------------------------------------------  -----------------
...
WindowsServer              MicrosoftWindowsServer         2019-Datacenter-with-Containers                 MicrosoftWindowsServer:WindowsServer:2019-Datacenter-with-Containers:2019.0.20190603                           2019.0.20190603
WindowsServer              MicrosoftWindowsServer         2019-Datacenter-with-Containers-smalldisk       MicrosoftWindowsServer:WindowsServer:2019-Datacenter-with-Containers-smalldisk:2019.0.20190603                 2019.0.20190603
```

**Comment by duggaraju** [comment]
Weird that 2019.0.20190521 image which existed before is removed now.  Like i mentioned above, if  the "imageVersion" is explicitly set then I can create the cluster.  If it is not set then the hard coded default image version only works with 1809 (Not 1903).  Would be nice if the default was something like "latest" similar to what azure supports and picks the latest images for the given SKU

**Comment by PatrickLang** [comment]
Yeah, I agree that we should default to latest, as long as we can guarantee it isn't broken. Right now there isn't enough testing on those images before they're published so we want to pre-test them in the aks-engine repo before accepting them. #1489 is an example where I'm making sure the June patches are ok to roll out. Getting images tested through aks-engine before they're publicly available is one of my team's near-term goals.
