### ISSUE TITLE
RHEL support

### ISSUE THREAD

**Issue by LiquoriChris** [Azure/aks-engine#1425]
Hello, 

Is RHEL a supported OS for aks-engine? I have tried creating a custom image in Azure and using the custom-image.json file in the example, but the ARM deployment failed. 

Is aks-engine only supported on Windows, Ubuntu, and Core OS?

Thank you for your help. 

Chris

**Comment by CecileRobertMichon** [comment]
@pwshliquori there is an existing RHEL implementation in aks-engine but it was only implemented for legacy Swarm clusters. 

We would welcome a PR to add RHEL support for Kubernetes if someone wants to pick this up.

**Comment by pwshliquori** [comment]
Thank you. Appreciate the feedback.
