### ISSUE TITLE
Error: validating API model after populating values: OrchestratorProfile.KubernetesConfig.ClusterSubnet '***/24' must reserve at least 9 bits for nodes

### ISSUE THREAD

**Issue by johneng89** [Azure/aks-engine#1431]
**Describe the bug**
While trying to deploy a k8's cluster in /24 subnet of Azure, I got the following error:
Error: validating API model after populating values: OrchestratorProfile.KubernetesConfig.ClusterSubnet '****/24' must reserve at least 9 bits for nodes
**Steps To Reproduce**
Deploy a K8's cluster into /24 subnet
**Expected behavior**
Its supposed to get deployed
**AKS Engine version**
v0.34.1
**Kubernetes version**
kubectl version v1.14.1
**Additional context**
Please, a work around will be appreciated.

**Comment by CecileRobertMichon** [comment]
Hi @johneng89, are you deploying with a pre-existing vnet? See https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#L231 about IP collision.
