### ISSUE TITLE
Max Pods Documentation

### ISSUE THREAD

**Issue by posix4e** [Azure/aks-engine#1432]
**Describe the request**
Where do we tell people how many pods to run per node. Also why is the default 30?
**Explain why AKS Engine needs it**
kubeflow and aks-engine alone are more than 30

**Comment by CecileRobertMichon** [comment]
30 is the default with Azure CNI (default `--network-plugin`) but there is work in progress to make that 110: https://github.com/Azure/aks-engine/pull/861. With `--network-plugin` kubenet, the default is already 110. This value is configurable via the `kubeletConfig` property. See https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#L259 and https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#L229
