### ISSUE TITLE
Disable ip-masq-agent addon with Azure CNI

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#1440]
Proposal: azure-ip-masq-agent is currently installed if k.NetworkPlugin != NetworkPluginCilium. It should only be necessary with any plugin using basic networking (e.g. kubenet) as NAT is needed. Can we disable it for Azure CNI by default?

cc: @khenidak @mo-saeed

**Comment by CecileRobertMichon** [comment]
@sharmasushant thoughts?

**Comment by mo-saeed** [comment]
@CecileRobertMichon I think it's necessary, I tried to deploy cluster with ip-masq-agent disabled and it failed with this error ```VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=34\n[stdout]\n\n[stderr]\nConnection to k8s.gcr.io 443 port [tcp/https] succeeded!\nConnection to gcr.io 443 port [tcp/https] succeeded!\nConnection to docker.io 443 port [tcp/https] succeeded!\n\"."``` 
the logs showing that the kubelet failed to start with the following error ```Jun 12 15:04:12 k8s-minion-22546418-vmss000002 bash[27525]: Bad argument `MASQUERADE'
Jun 12 15:04:12 k8s-minion-22546418-vmss000002 bash[27525]: Try `iptables -h' or 'iptables --help' for more
Jun 12 15:04:12 k8s-minion-22546418-vmss000002 systemd[1]: kubelet.service: Control process exited, code=exi
Jun 12 15:04:12 k8s-minion-22546418-vmss000002 systemd[1]: Failed to start Kubelet.```

**Comment by CecileRobertMichon** [comment]
Thanks for the info @mo-saeed, I'll close this issue in that case.
