### ISSUE TITLE
Add option to disable hyperthreading

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#1465]
**Describe the request**
"Customers running untrusted code on a hyper-threaded VM will need to disable hyper-threading or move to a non-hyper-threaded VM size." according to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/mitigate-se#enabling-additional-security

We should add an option to do that in AKS-Engine so that setting can be applied as clusters are scaled up or upgraded.

**Explain why AKS Engine needs it**

Modifying templates directly to make this change can break AKS or AKS-Engine upgrades and scaling.

**Describe the solution you'd like**

Put a property in the agent pool so that you can specify the VM size, and if you want to opt out of hyperthreading.

**Describe alternatives you've considered**

Alternative is to use VM sizes without hyperthreading if it's an impact.

**Additional context**

**Comment by tachyus-ryan** [comment]
Was this option ever added?
