### ISSUE TITLE
All parameters of customSearchDomain has to be provided to be visible in the template

### ISSUE THREAD

**Issue by Morishiri** [Azure/aks-engine#1468]
**Describe the bug**
In the docs: https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#linuxprofile
there is information about `customSearchDomain` inner keys, where each is described as not required. When providing only `customSearchDomain.name` the generated parameters file contains this section, but template file doesn't - deployment fails. When all 3 are provided  -both generated files contain all the fields.
**Steps To Reproduce**
1. (success case) Fill in (ssk key and SP) and deploy https://github.com/Azure/aks-engine/blob/master/examples/vnet/kubernetesvnet-customsearchdomain.json

Used command: `aks-engine generate --output-directory "./test-1" --api-model "./kubernetesvnet-customsearchdomain.json"`

Output:
- azuredeploy.json contains:
```
"searchDomainName": {
      "defaultValue": "",
      "metadata": {
        "description": "Custom Search Domain name."
      },
      "type": "string"
    },
    "searchDomainRealmPassword": {
      "defaultValue": "",
      "metadata": {
        "description": "Windows server AD user password to join the Linux Machines with active directory and be able to change dns registries."
      },
      "type": "securestring"
    },
    "searchDomainRealmUser": {
      "defaultValue": "",
      "metadata": {
        "description": "Windows server AD user name to join the Linux Machines with active directory and be able to change dns registries."
      },
      "type": "string"
    },
```
- azuredeploy.parameters.json contains:
```
    "searchDomainName": {
      "value": "vlabs.local"
    },
    "searchDomainRealmPassword": {
      "value": "foobar"
    },
    "searchDomainRealmUser": {
      "value": "vlabs"
    },
```
if you try to deploy it it will success.

2. (error case) Fill in (ssk key and SP), remove `customSearchDomain.realmUser` and `customSearchDomain.realmPassword` and deploy https://github.com/Azure/aks-engine/blob/master/examples/vnet/kubernetesvnet-customsearchdomain.json

Used command: `aks-engine generate --output-directory "./test-2" --api-model "./kubernetesvnet-customsearchdomain.json"`

Output:
- azuredeploy.json doesn't contain `customSearchDomain` fields at all.
- azuredeploy.parameters.json contains:
```
    "searchDomainName": {
      "value": "vlabs.local"
    },
    "searchDomainRealmPassword": {
      "value": ""
    },
    "searchDomainRealmUser": {
      "value": ""
    },
```

if you try to deploy it it will end up with error saying:
> Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template parameters 'searchDomainRealmUser, searchDomainName, searchDomainRealmPassword' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are...

**Expected behavior**
In second case the required `customSearchDomain` should be visible in `azuredeploy.json` file.
**AKS Engine version**
```
$ aks-engine version
Version: v0.36.4
GitCommit: a030f5df2
GitTreeState: clean
```
**Kubernetes version**
1.14.1
**Additional context**
None

**Comment by UnwashedMeme** [comment]
@Morishiri the name on this parameter is a bit misleading, while it does set the custom search domain it is really about trying to join active directory.

As a heads up setting just the domain is unlikely to yield a working cluster.  There are several points where the master tries to look up the address of agent nodes in DNS-- unless your VM hostname exist in DNS this will lead to errors. The two solutions I know of right now are:
* Use azure DNS+DHCP, this relies on the magic vnet `internalDomainNameSuffix`
  * Theoretically aks-engine could add your search path in addition to azure's, but the code isn't at all setup right now to do that.
* Use AD DNS and have all the VMs join the domain-- that's what these parameters trigger right now
  * This doesn't work reliably, see #1577

**Comment by Morishiri** [comment]
ok thanks for explaining that!
