### ISSUE TITLE
ACR Hyperkube image transition

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1472]
**Describe the request**

@jchauncey will provide details on available hyperkube images hosted by ACR

**Explain why AKS Engine needs it**

Produce clusters backed by Azure-stamped k8s

**Comment by jchauncey** [comment]
Image Path: `upstream.azurecr.io/k8s/core/hyperkube-amd64`

Published Tags:
```
v1.12.6
v1.12.7
v1.13.5
v1.14.1
v1.14.2
v1.15.0-beta.0
v1.16.0-alpha.0
```

**Comment by CecileRobertMichon** [comment]
related to https://github.com/Azure/aks-engine/issues/1123

**Comment by jackfrancis** [comment]
@jchauncey Why isn't 1.14.3 published in the ACR repo above?

**Comment by jchauncey** [comment]
building it now
