### ISSUE TITLE
Windows container networking/dns fails on pod redeploy/upgrade

### ISSUE THREAD

**Issue by harshaperera532** [Azure/aks-engine#1475]
**Describe the bug**
I've deployed a hybrid cluster. I am deploying nano server and server core pods (ASP.Net Core) on the Windows nodes. These connect to Azure Key Vault at startup. On fresh Windows nodes this works ok and the software starts up. However, on redeploying/upgrading some or all of the pods on the Windows nodes fail to start as they are not able to connect to Vault (Host is unknown error). Kubernetes restarts the pods but they never startup. If the pod is manually deleted, the new pod that is brought up by k8s also fails. If the node is drained and restarted the pod may successfully start, however another pod on that node may now fail to start. I've tried pausing the thread for 60s at application start and then attempting to connect to Vault and also pausing for 30s after a failure to connect to Vault and retrying (3 attempts).

I built one of the containers using the ASP.Net Core Linux (Alpine) image and deployed into the Linux node. So far this has successfully started every time. The other images cannot currently be based on Linux.

I have created multiple clusters and always get this issue. If a new windows node is added to the cluster this works initially and then pods fail on it once they are redeployed/upgraded.

**Steps To Reproduce**
Believe the following should reproduce.
- Create a Linux and Windows hybrid cluster
- Deploy multiple Windows pods that connect to an external service at startup
- Redeploy a different version of the windows pod - some or all will probably no longer connect to the external service.

**Expected behavior**
The DNS lookup to work and for the pod to be able to establish a connection to Vault

**AKS Engine version**
0.36.4

**Kubernetes version**
1.14.1

**Additional context**
The clusters are deployed in West Europe.
The Windows nodes are running kernel version 10.0.17763.379
The docker images are based on mcr.microsoft.com/windows/servercore:ltsc2019 and mcr.microsoft.com/dotnet/core/aspnet:2.2.5-nanoserver-1809

**Comment by CecileRobertMichon** [comment]
@harshaperera532 could you please share the exact apimodel (minus secrets) that you used to deploy the cluster?

**Comment by zhiweiv** [comment]
You can see if these 2 issues help,
https://github.com/Azure/AKS/issues/1029
https://github.com/Azure/azure-container-networking/issues/341

**Comment by harshaperera532** [comment]
@CecileRobertMichon I've attached the apimodel used to create the cluster
[sanitised_apimodel.json.txt](https://github.com/Azure/aks-engine/files/3290929/sanitised_apimodel.json.txt)

**Comment by harshaperera532** [comment]
@zhiweiv [https://github.com/Azure/AKS/issues/1029](url) does seem to be very similar to what I am seeing. I have previously used the workaround of setting the Google DNS as kube-dns didn't work in Windows containers till recently. However, I need resolution to internal services now.

**Comment by PatrickLang** [comment]
Can you try this on a new cluster? This was a known problem in Windows 10.0.17763.379 that's resolved now.
