### ISSUE TITLE
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get services http:heapster

### ISSUE THREAD

**Issue by narayana98765** [Azure/aks-engine#1490]
hi Team,

These machines are ACS Kubernetes master servers deployed using ACS-Engine.

Kubernetes Version: 1.10.2
Setup: 1 Master 3 Nodes
Docker Version: 1.13.1

Right now the machines are up and running however kubernetes api server is not responding which resulted in cluster level issues. All pods in the kube-system are up and running, however we are not getting response from backend.

Kube-Dns Logs:
E0618 06:36:47.278570       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E0618 06:36:50.350587       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E0618 06:36:50.350587       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host

Heapster Logs: 

E0618 06:38:03.535148       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: Failed to list *v1.Namespace: Get https://10.0.0.1:443/api/v1/namespaces?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E0618 06:38:03.535639       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E0618 06:38:03.535743       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E0618 06:38:03.626483       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E0618 06:38:03.626580       1 reflector.go:190] k8s.io/heapster/metrics/heapster.go:328: Failed to list *v1.Pod: Get https://10.0.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host

scelocaladmin@k8s-master-26759809-0:~$ kubectl top nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get services http:heapster:)

**Comment by CecileRobertMichon** [comment]
Is this a new cluster or a pre-existing cluster that suddenly stopped working? If it was working before, did you change anything or run any operations (upgrade, scale) before it stopped working?

Are kubelet logs showing anything interesting? `journalctl -u kubelet`

Also please verify that your Service Principal secret is not expired.

what configuration is the cluster using? please share your apimodel.

**Comment by narayana98765** [comment]
Hi Cecile Robert,

Thanks for the update , we have resolved the issue , its ACS cluster , and its resolved by rebooting the nodes and master as kube-system api-server and heapster not able to commutate with nodes , thanks for your support , if we have any issues further update you the same.

Regards,
Narayana

**Comment by mboersma** [comment]
I'm glad you found a workaround. If you run into this again and can reproduce it with `aks-engine`, please reopen this issue or create a new one.
