### ISSUE TITLE
Kubernetes upgrade from pre-0.37.0 cluster fails when calico is used

### ISSUE THREAD

**Issue by skinny** [Azure/aks-engine#1492]
When a cluster created with an earlier version of aks-engine and using the `networkPolicy: calico` is upgraded using the latest (v0.37.0 and later) version of aks-engine the newly provisioned masters (with new version) won't come up because `kubelet` fails to start because of a missing `calico-daemonset.yaml` 

Due to this change : https://github.com/Azure/aks-engine/commit/2318d1a55730f5a9adfb7e54014373e9ff8d9721#diff-ae5521caff62cc4fe47f430c7263a49bL137

the definition of `isEnabled` changed. The earlier version of aks-engine deployed the DS because the networkPolicy was set to `calico` and generated an apimodel.json file with the addon  `calico` set to disabled. The upgrade command using the latest version now incorrectly uses this disabled addon in the apimodel.json to stop deploying the daemonset yaml file to the new masters.

**Steps To Reproduce**
Upgrade a cluster with `networkPolicy: calico` created aks-engine < v0.37.0 to a newer version of kubernetes (1.13 to 1.14 for example)

**Expected behavior**
The cluster

**AKS Engine version**
`v.0.37.0 and master`

**Comment by CecileRobertMichon** [comment]
@skinny thanks for reporting, we will investigate. As a workaround in the meantime, could try changing the `isEnabled` value of calico in your apimodel to `true` before running the upgrade?

**Comment by skinny** [comment]
Yes I forgot to mention that. Changing the enabled flag in the apimodel before running the upgrade works fine

**Comment by CecileRobertMichon** [comment]
Thanks for confirming. That PR actually fixed a bug because we were previously ignoring the value of "isEnabled" for Calico.

**Comment by jackfrancis** [comment]
@skinny what did the calico-daemonset addons item look like in the apimodel before the change?

**Comment by skinny** [comment]
Unfortunately I don't have the "old" apimodel.json anymore. They only thing I changed in there was `enabled:false` to `enabled:true` before running the upgrade. 

The earlier version of aks-engine actually deployed the deamonset based on the `networkPolicy` settings but didnt save it as  'enabled' in the apimodel.json file

**Comment by jackfrancis** [comment]
Yes, the interesting thing is that prior to the change described in this issue the "calico-daemonset" addon didn't actually exist. The k8s addons interface was used under the hood to deliver the calico yaml spec. As such the current implementation should be backwards-compatible with older clusters:

https://github.com/Azure/aks-engine/blob/master/pkg/api/addons.go#L280

**Comment by skinny** [comment]
@jackfrancis please see my revised comment

**Comment by skinny** [comment]
Ok, I retraced my steps and came up with this this : 


@deploy time :

```networkPolicy: calico
addon: n/a```

Result: DS gets deployed, but no addon present in apimodel.json

@upgrade time (with newer aks-engine):

Present in apimodel.json : 

```networkPolicy: calico
addon: n/a```

Result: 
This version checks the addon instead of the networkPolicy and decides to not deploy the DS yaml on the new masters.
Kubelet fails to start due to the contents of /opt/azure/containers/kubelet.sh, which is execute before starting the kubelet.
See https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/masternodecustomdata.yml#L358 
Due to the networkPolicy still being `calico` the `sed` command is deployed but fails because the actual DS file is not there anymore

**Comment by jackfrancis** [comment]
I think I've got root cause:

This PR introduced w/ v0.36.0 added the calico api model addon w/ enabled set to default:

https://github.com/Azure/aks-engine/pull/1089

I'll add a back-compat fix to statically change that to true in upgrade scenarios if networkPolicy == calico

Thanks again for reporting @skinny! (and for your endurance here :|)

**Comment by skinny** [comment]
Happy to help!
