### ISSUE TITLE
Linux directory permissions can not be changed on azurefile mount

### ISSUE THREAD

**Issue by gazataeon** [Azure/aks-engine#1494]
Unable to `chmod` or `chown` any directory/file on an azurefiles persistent volume from within a container.

**Steps To Reproduce**
`kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
parameters:
  skuName: Standard_LRS
allowVolumeExpansion: true`

Using the above everything is forced to use `root:root:` with permissions of `777` no matter what I try and do after the pod is provisioned.

This however is not the case when using Managed Disk volume mounts

**Expected behavior**
Functions as Managed disk mounts do, permission changes from the container.

**AKS Engine version**
1.14

**Kubernetes version**
1.14.0

**Comment by jackfrancis** [comment]
@lachie83 @ritazh @khenidak is the above the expected behavior of the `kind: StorageClass` Azure cloudprovider implementation? If so, would that implementation ever change to match the managed disk mount implementation?

**Comment by andyzhangx** [comment]
@jackfrancis SMB mount options(including dir permission) could not be changed, it's by SMB proto design, while for disk(ext4, xfs) dir permission could be changed after mount
close this issue, let me know if you have any question.
