### ISSUE TITLE
Print hostname in VMSS CSE command

### ISSUE THREAD

**Issue by Banani-Rath** [Azure/aks-engine#1496]
We are using vmss extension for provisioning vm with aks-engine!

At present we come across a scenario where provisioning failed with following error:

 

We have created a log analytics work space to track all logs but when I queried with following I couldn’t found more information.

 
I just see one output couldn’t get more information.

 

My question is :

Is there  a way to get more information or logs to investigate?

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/aks-engine/blob/master/docs/howto/troubleshooting.md#vmextensionprovisioningerror-or-vmextensionprovisioningtimeout should help

**Comment by fenxu** [comment]
Is there a way that we could find more information about which instance is failed?
Now the information shows on portal is failed but without any specific instance number. That makes the trouble shooting hard.
It means once some instances failed, we even don't know which one that is and even can't manually fix/kill that.

**Comment by CecileRobertMichon** [comment]
For scale sets, the extension is associated to the scale set itself and not to each individual instance which makes it tricky to know which instance failed unfortunately. For availability sets, one extension is deployed per VM and we name them accordingly so it's easier to know which extension failed. 

I think one thing we could do is print a log line as part of the error message with the hostname. Would that help?
