### ISSUE TITLE
Walkthrough - Incorrect kubernetes link

### ISSUE THREAD

**Issue by phatcher** [Azure/aks-engine#150]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
NA
---

Walkthrough has incorrect link to kubernetes release should be [this](https://kubernetes.io/docs/setup/release/notes/)

**Comment by CecileRobertMichon** [comment]
thanks for reporting @phatcher! I moved this issue to the aks-engine repo since all further development will happen here. Would you like to open a PR to fix it? We welcome contributions :)

**Comment by jreypo** [comment]
@phatcher which walkthrough doc are you referencing to?

Neither [this](https://github.com/Azure/aks-engine/blob/master/docs/kubernetes/walkthrough.md) nor [this](url) doc contain a link referencing the current or another Kubernetes release.

**Comment by jreypo** [comment]
@CecileRobertMichon I can fix this if you point me to the right doc, honestly I cannot find whcih doc is @phatcher referencing to

**Comment by CecileRobertMichon** [comment]
@jreypo thanks for helping! I looked for a broken link in the walkthrough doc but couldn't find one, I think the link @phatcher was referring to might be `Kubernetes release page` in https://github.com/Azure/aks-engine/blob/master/docs/kubernetes/windows.md because that one is broken.

**Comment by jreypo** [comment]
Thanks @CecileRobertMichon just created PR #260 to fix this
