### ISSUE TITLE
Cluster Deployment failing with Error Could not find member 'Sensitivity' on object of type 'TemplateResource'. Path 'properties.template.resources[12].Sensitivity

### ISSUE THREAD

**Issue by satishsudini** [Azure/aks-engine#1517]
**Describe the bug**

**Steps To Reproduce**
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.15",
      "orchestratorVersion": "1.15.0",
      "kubernetesConfig": {
        "enableRbac": true,
        "enableSecureKubelet": true,
        "enableAggregatedAPIs": true,
        "networkPolicy": "calico",
        "networkPlugin": "kubenet",
        "clusterSubnet": "*",
        "serviceCidr": "*",
        "dnsServiceIP": "*",
        "dockerBridgeSubnet": "*",
        "etcdDiskSizeGB": "32",
        "privateCluster": {
          "enabled": true
        },
        "kubeletConfig": { 
          "--non-masquerade-cidr": "*",
          "--cluster-domain": "*",
          "--feature-gates": "PodPriority=true"
        },
        "apiServerConfig": {
          "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
        },
        "useInstanceMetadata": false,
        "enableEncryptionWithExternalKms": true,
        "cloudProviderRateLimit": false,
        "cloudProviderRateLimitBucket": 0,
        "cloudProviderRateLimitQPS": 0,
        "addons": [
          {
            "name": "blobfuse-flexvolume",
            "enabled" : false
          },
          {
            "name": "smb-flexvolume",
            "enabled" : false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled" : false
          },
          {
            "name": "nvidia-device-plugin",
            "enabled" : false
          },
          {
            "name": "azure-cni-networkmonitor",
            "enabled" : false
          },
          {
           "name": "ip-masq-agent",
           "enabled" : false
          }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "CLUSTER_NAME",
      "distro": "ubuntu",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": "SUBNET_ID",
      "availabilityProfile": "AvailabilitySet",
      "firstConsecutiveStaticIP": "MASTER_IP",
      "OSDiskSizeGB": 32,
      "extensions": [
        {
          "name": "bootstrap",
          "singleOrAll": "All"
        }
     ]
    },
    "agentPoolProfiles": [
      {
        "name": "AGENT_NAME",
        "count": 2,
        "distro": "ubuntu",
        "vmSize": "Standard_DS4_v2",
        "vnetSubnetId": "SUBNET_ID",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile" : "ManagedDisks",
        "diskSizesGB": [2],
        "OSDiskSizeGB": 64,
        "acceleratedNetworkingEnabled": true,
        "preProvisionExtension": {
            "name": "prepare_vm_disks",
            "singleOrAll": "All"
        },
        "extensions": [
          { 
            "name": "bootstrap",
            "singleOrAll": "All"
          }
       ]
      }
    ],
    "extensionProfiles": [
      {
          "name": "prepare_vm_disks",
          "version": "v1",
          "rootURL": "*",
          "script": "prepare_vm_disks.sh",
          "urlQuery": "*",
      }
    ],
    "linuxProfile": {
      "adminUsername": "ADMIN_ACCOUNT",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "PUBLIC_KEY"
          }
        ]
      }
    },
    "aadProfile": {
      "serverAppID": "AAD_SERVER_APP_ID",
      "clientAppID": "AAD_CLIENT_APP_ID",
      "tenantID": "AZURE_TENANT_ID",
      "adminGroupID": "AAD_ADMIN_GROUP_ID"
    },    
    "servicePrincipalProfile": {
      "clientId": "CLIENT_ID",
      "secret": "CLIENT_SECRET",
      "objectId": "OBJECT_ID"
    }
  }
}

aks-engine generate test.json

**Expected behavior**
Should deploy the cluster 

**AKS Engine version**

v0.37.3

**Kubernetes version**

k8-1.1.5

**Additional context**

Error Message: Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'Sensitivity' on object of type 'TemplateResource'. Path 'properties.template.resources[12].Sensitivity', line 1, position 115589.'.

**Comment by CecileRobertMichon** [comment]
@satishsudini I believe this is a duplicate of https://github.com/Azure/aks-engine/issues/1168.

The word "sensitivity" does not appear anywhere in the repo, as I pointed out in the previous issue I believe it's coming from the "prepare_vm_disks" extension. Where do you get that extension from?

**Comment by satishsudini** [comment]
We are using this extension for prepare vm . This is taken from below https://raw.githubusercontent.com/Azure-Samples/compute-automation-configurations/master/prepare_vm_disks.sh

**Comment by CecileRobertMichon** [comment]
what about the "bootstrap" extension? I don't see an extensionProfile for it in your apimodel, where is the template coming from? 

not seeing `Sensitivity` in any aks-engine template generation paths so trying to understand where it's coming from... Where is the template downloaded from?

**Comment by satishsudini** [comment]
It will be there right below extension . This is bootstrap script which runs 

      {
          "name": "bootstrap",
          "version": "v3",
          "extensionParameters": " * * * * ”,
          "rootURL": " chef url“,
          "script": "bootstrap.sh",
          "urlQuery": " token”
      }

**Comment by CecileRobertMichon** [comment]
what is the resulting ARM template extension resource in azuredeploy.json? Basically, check in your _output/ directory and search the cluster's azuredeploy.json file for `Sensitivity`.  Please send me the entire resource json of the resource that property is in (resource[12] according to the error message). I suspect it is coming from your extension since it's not part of aks engine code.

**Comment by satishsudini** [comment]
Thanks @CecileRobertMichon  . This is caused by the VM tags which we are using i removed that cluster installation went through .
