### ISSUE TITLE
get-akse.sh doesn't work on Azure Cloud Shell without sudo

### ISSUE THREAD

**Issue by craiglpeters** [Azure/aks-engine#1518]
**Describe the bug**
Basic use of aks-engine as documented https://github.com/craiglpeters/aks-engine/blob/master/docs/tutorials/quickstart.md#install-aks-engine doesn't work in Azure Cloud Shell
**Steps To Reproduce**
Follow the shell script instructions in the link above.
Output is 
```craig@Azure:~$ curl -o get-akse.sh https://raw.githubusercontent.com/Azure/aks-engine/master/scripts/get-akse.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5860  100  5860    0     0  16205      0 --:--:-- --:--:-- --:--:-- 16232
craig@Azure:~$ chmod 700 get-akse.sh
craig@Azure:~$ ./get-akse.sh
Downloading https://github.com/Azure/aks-engine/releases/download/v0.37.3/aks-engine-v0.37.3-linux-amd64.tar.gz
Preparing to install aks-engine into /usr/local/bin
./get-akse.sh: line 46: sudo: command not found
Failed to install aks-engine
        For support, go to https://github.com/Azure/aks-engine.```

**Expected behavior**
Script will not fail

**AKS Engine version**
v0.37.3

**Kubernetes version**
N/A

**Additional context**

**Comment by mboersma** [comment]
Cloud Shell is a restricted environment where `sudo` won't be available. Maybe the script can detect that it's running in Cloud Shell and download the binary to `/usr/local/bundle/bin` instead, since that does appear to be a user-writable directory in the $PATH. I'll give that a try.

**Comment by mboersma** [comment]
@craiglpeters [this script](https://raw.githubusercontent.com/Azure/aks-engine/2d638d7e9d1f4551f9ec8b6dcab910f7c721f1cf/scripts/get-akse.sh) seems to work ok on Azure Cloud Shell and locally. Let me know if you get a chance to test it.
