### ISSUE TITLE
Private cluster with Standard LB for both Master and Agents is failed

### ISSUE THREAD

**Issue by rameshthangaraj** [Azure/aks-engine#1519]
I am trying to create a private cluster with Standard LB for both Master and Agents  and the private network is unreachable to fetch the packages to install during the custom script extension and the deployment is getting failed. I am able to create a private cluster using Basic LB for master and agents . But for better scalability and throughput we go for Standard LB but the backend pool machines in Standard LB is internet blocked and hence the issue. What is the solution for resolving this issue.

**Comment by jackfrancis** [comment]
This should be addressed by https://github.com/Azure/aks-engine/pull/2572
