### ISSUE TITLE
Certificate profile does not except certificate private key

### ISSUE THREAD

**Issue by LiquoriChris** [Azure/aks-engine#1521]
**Describe the bug**

caPrivateKey does not accept private key via key vault or string value.

aks-engine generate returns the following error on the caPrivateKey:

```Error: in SetPropertiesDefaults template ./ApiModel.json: The raw pem is not a valid PEM formatted block```

This error does not show up if I remove the caPrivateKey from the certificateProfile block.

**Steps To Reproduce**

1. Add certificateProfile with appropriate settings:
 
```
"certificateProfile": {
            "caCertificate": "/subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.KeyVault/vaults/$KeyVault/secrets/kubernetes-dev-crt",
            "caPrivateKey": "/subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.KeyVault/vaults/$KeyVault/secrets/kubernetes-dev-key"
}
```

Custom multiple master API model is being used. 

**Expected behavior**

aks-engine generate should generate the ARM template with appropriate key vault certificate entries. 

```Receiving the following error: Error: in SetPropertiesDefaults template ./ApiModel.json: The raw pem is not a valid PEM formatted block```

The crt and key do not contain any ```/n``` in the file. 

**AKS Engine version**

0.37.1

**Kubernetes version**

1.13.5

**Comment by CecileRobertMichon** [comment]
@LiquoriChris this is most likely due to the secret `kubernetes-dev-key` or `kubernetes-dev-crt` not being formatted properly. Did you follow https://github.com/Azure/aks-engine/blob/master/examples/keyvault-params/README.md ? Make sure you are base64 encoding the secrets as explained in the doc.

**Comment by LiquoriChris** [comment]
@CecileRobertMichon yes. I have tried setting the secret using the az commands listed in the readme. If I remove the caCertificate and caPrivate key (example below), the ARM template is generated. 

```
"certificateProfile": {
    "apiServerCertificate": "/subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.KeyVault/vaults/$KeyVault/secrets/kubernetes-dev-crt",
    "apiServerPrivateKey": "/subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.KeyVault/vaults/$KeyVault/secrets/kubernetes-dev-key",
    "clientCertificate": "/subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.KeyVault/vaults/$KeyVault/secrets/kubernetes-dev-crt",
    "clientPrivateKey": "/subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.KeyVault/vaults/$KeyVault/secrets/kubernetes-dev-key",
    "kubeConfigCertificate": "/subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.KeyVault/vaults/$KeyVault/secrets/kubernetes-dev-crt",
    "kubeConfigPrivateKey": "/subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.KeyVault/vaults/$KeyVault/secrets/kubernetes-dev-key"
}
```

**Comment by LiquoriChris** [comment]
I've noticed that adding the certificate profile does not modify the certificates in the apimodel.json file after generation. The certificates do not get replaced with the secrets from key vault. I tried entering the cert (in base64) statically and had the same result.

**Comment by CecileRobertMichon** [comment]
See https://github.com/Azure/aks-engine/issues/883#issuecomment-497897229

I can't repro, I believe the error is what it actually says `The raw pem is not a valid PEM formatted block` --> the certificates stored in your keyvault aren't formatted properly.

> I have tried setting the secret using the az commands listed in the readme. If I remove the caCertificate and caPrivate key (example below), the ARM template is generated.
if no CA cert/key pair is passed in, aks-engine ignores the passed in certificate profiles and generates new certs by design. That's why you're not seeing the error (your keyvault certs aren't used).

> I've noticed that adding the certificate profile does not modify the certificates in the apimodel.json file after generation. The certificates do not get replaced with the secrets from key vault. 
This is expected. The certs are fetched from keyvault at cluster deployment time, not as part of the apimodel generation. The apimodel contains a reference to the keyvault, not the cert raw values.

> I tried entering the cert (in base64) statically and had the same result.
This means that one of your certs is not properly formatted.

**Comment by LiquoriChris** [comment]
Thank you for the clarifications. I appreciate your help,
