### ISSUE TITLE
aks-engine deploy error for for service principal with contributor permission 

### ISSUE THREAD

**Issue by gkranga** [Azure/aks-engine#1532]
acs-engine based kubernetes deployment as per the steps in the document ---> https://github.com/Azure/aks-engine/blob/master/docs/tutorials/deploy.md But I get the error as below. 

I can resolve this problem by creating a service principal with Owner level access rather than the contributor but this is not the best security practice. 

aks-engine deploy --subscription-id xxxxxxxxxx     --dns-prefix mycluster     --resource-group psaksengine     --location southindia     --api-model  template.json    --client-id yyyyy     --client-secret zzzzzz     --set servicePrincipalProfile.clientId="yyyy"     --set servicePrincipalProfile.secret="zzzzz" -f

INFO[0000] new api model file has been generated during merge: /var/folders/qv/vbc5nh5n73dd8dvh75hv20y80000gn/T/mergedApiModel577560619 
WARN[0003] apimodel: missing masterProfile.dnsPrefix will use "mycluster" 
INFO[0017] Starting ARM Deployment (psaksengine-353628854). This will take some time... 
Error: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplateDeployment" Message="Deployment failed with multiple errors: 'Authorization failed for template resource 'xxxxxxx' of type 'Microsoft.Authorization/roleAssignments'. The client 'xxxxxxxx' with object id 'xxxxxxx' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/xxxxxxxx/resourceGroups/mycluster/providers/Microsoft.Authorization/roleAssignments/b3fc7a89-1449-5d87-b926-e403ae73da6f'.:Authorization failed for template resource '344822f0-32be-5724-b12d-4220ef74ade3' of type 'Microsoft.Authorization/roleAssignments'. The client 'yyyyyy' with object id 'zzzzzzz' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/xxxxxx/resourceGroups/mycluster/providers/Microsoft.Authorization/roleAssignments/344822f0-32be-5724-b12d-4220ef74ade3'.:Authorization failed for template resource '3f3769c4-d918-5ece-b9ad-cf2b87362b41' of type 'Microsoft.Authorization/roleAssignments'. 

**Steps To Reproduce**

explained above 

**Expected behavior**
deployment to be completed successfully 

**AKS Engine version**

Version: v0.37.2
GitCommit: 0eb170306
GitTreeState: clean

**Kubernetes version**
1.12

**Additional context**

**Comment by sukhong** [comment]
Same issue is happening to me:

Error: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplateDeployment" Message="The template deployment failed with error: 'Authorization failed for template resource 'xxx' of type 'Microsoft.Authorization/roleAssignments'. The client 'xxx' with object id 'xxx' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Authorization/roleAssignments/xxx'.'."

This is occuring after I enabled
