### ISSUE TITLE
Load balancer creation in US DoD 

### ISSUE THREAD

**Issue by oronboni** [Azure/aks-engine#1534]
**Describe the bug**
The loadbalancer in Ingress (Nginx) deployment failed in the creation process.

EnsureHostInPool(ingress/nginx-ingress): backendPoolID(/subscriptions//resourceGroups//providers/Microsoft.Network/
loadBalancers//backendAddressPools/) - failed to ensure host in pool: "azure - cloud provider rate limited(read) for operation:VMSSGetInstanceView"]

**Steps To Reproduce**
Create cluster in US DoD Central with the following configuration:
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.14.3",
      "kubernetesConfig": {
        "apiServerConfig": {
           "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration"
          },
        "useManagedIdentity": true,
        "addons": [
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "config": {
              "max-nodes": "50",
              "min-nodes": "4",
              "scan-interval": "10s"
			  }
          },
		  {
            "name": "tiller",
            "enabled" : false
          },
		  {
            "name": "kubernetes-dashboard",
            "enabled" : false
          } 
        ]
		}
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "@__Master_dnsPrefix__@",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/@__subscriptionID__@/resourceGroups/@__resourceGroupName__@/providers/Microsoft.Network/virtualNetworks/@__clusterVnetName__@/subnets/@__Master_vnetSubnetName__@",
      "firstConsecutiveStaticIP": "10.10.0.230",
      "vnetCidr": "10.10.0.0/16",
      "subjectAltNames": [
        "@__Master_dnsPrefix__@.@__Master_DomainSuffix__@"
      ]
    },
    "agentPoolProfiles": [
      {
        "name": "wdatpagents",
        "count": 4,
        "vmSize": "Standard_D4_v2",
        "vnetSubnetId": "/subscriptions/@__subscriptionID__@/resourceGroups/@__resourceGroupName__@/providers/Microsoft.Network/virtualNetworks/@__clusterVnetName__@/subnets/@__agent_vnetSubnetName__@",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "osDiskSizeGB":  400,
        "acceleratedNetworkingEnabled": true
      }
    ],
    "linuxProfile": {
      "adminUsername": "wdatpuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "@__ClusterSshPublicKey__@"
          }
        ]
      }
    }   
  }
}

Deploy Nginx with service 
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: <Public IP that created before in the same resource group>
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress

**Expected behavior**
Get the Ip in when get the svc info.

**AKS Engine version**
0.37.0

**Kubernetes version**
1.14.3

**Additional context**
There is no onboard group on the cluster.

**Comment by mboersma** [comment]
@oroboni the rate-limiting error doesn't sound likely to be specific to a DoD location—if you try a similar cluster in the production cloud, I wonder if we would see the same problem. I'm trying to reproduce this, but no luck so far.

**Comment by oronboni** [comment]
@mboersma there is no problem in the public cloud. 
before the ticket created cluster created with the same aks-engine version and the same K8S version in the public cloud and there was no issue with the load balancer (therefore I assume its relate to US DoD).

@mboersma can you please try to check it in US DoD (@CecileRobertMichon can you assist ?)

**Comment by CecileRobertMichon** [comment]
Did you try https://github.com/Azure/aks-engine/issues/420#issuecomment-459928040 ?

**Comment by oronboni** [comment]
Are you sure that in this case this solution is the correct ? (The teams not using the cluster yet and the traffic is low)

**Comment by oronboni** [comment]
The cluster is operational. 
The problem is with system identity (cannot allocate public IP from different resource group)

**Comment by CecileRobertMichon** [comment]
Glad to hear that. Let us know if you run into more issues.
