### ISSUE TITLE
Changing to reconcile mode for addons doesn't allow upgrade of tiller or customize coredns

### ISSUE THREAD

**Issue by fazdamoa** [Azure/aks-engine#1541]
**Describe the bug**
Upgrading tiller version now reverts to 2.11.0 after 60 seconds due to reconcile mode
Annoying for us as we have to downgrade helm version on all workstations and jenkins slaves to get helm working again (we use 2.13.0) - or reinstall tiller each upgrade?

Coredns configmap customization also doesn't work due to this. coredns-custom configmap doesn't work for us (does it work at all on non-managed aks...?)
As we rely on internal DNS for some apps we have to rework them to services/endpoints if this is staying.

**Steps To Reproduce**
helm init --upgrade

**Expected behavior**
Version of tiller should be updated to 2.13.0 and stay there
Proxy to custom dns servers should work in coredns

**AKS Engine version**
0.37.3
**Kubernetes version**
1.15

**Comment by mboersma** [comment]
@fazdamoa in AKS Engine v0.37.3, the CoreDNS change was reverted, so you should be able to customize the ConfigMap again. For `helm init --upgrade` to stick, currently you'd have to edit the tiller deployment manifest to replace `Reconcile` with `EnsureExists`.

Without `Reconcile`, addons weren't being upgraded during `aks-engine upgrade`. You can read the discussion about the tradeoffs [here](https://github.com/Azure/aks-engine/pull/1401) and [here](https://github.com/Azure/aks-engine/pull/1493#issuecomment-503303279).

**Comment by fazdamoa** [comment]
The CoreDNS change was reverted (to EnsureExists) in 0.37.2 - but was put back to reconcile in 0.37.3?
See commit
https://github.com/Azure/aks-engine/commit/5d48814d6995e50373c50fed6d4aad07fdef4271

Currently it is being wiped every 60 seconds when customized (on 0.37.3)

I can see the tradeoffs and fully understand :) as long as I can customize CoreDNS somehow...
Apologies for poor formatting/if I got something wrong, I'm pretty new to commenting on github.

**Comment by mo-saeed** [comment]
@fazdamoa You can always change the config in the addons folder on any of the master machines (/etc/kubernetes/addons), from Reconcile to EnsureExists as @mboersma mentioned. then run helm upgrade

**Comment by fazdamoa** [comment]
Thanks, updating the addons files fixed the issues. Although after the upgrade both our production cluster and dev cluster CoreDNS pods were failing the readiness probe.

Adjusting timeoutSeconds to 5 on the CoreDNS deployment has fixed the issue

**Comment by fazdamoa** [comment]
Actually, adjusting timeoutSeconds only has worked on one of our clusters.
Our 'prod' cluster (not actually very prod yet) CoreDNS won't start at all due to readiness probe:

`kubectl logs -n kube-system coredns-5fbbc9f6b4-jrsf7
.:53
2019-07-01T09:00:05.873Z [INFO] plugin/reload: Running configuration MD5 = 9973ba6ef6abfdd262e55113ee44f8bc
2019-07-01T09:00:05.873Z [INFO] CoreDNS-1.5.0
2019-07-01T09:00:05.873Z [INFO] linux/amd64, go1.12.2, e3f9a80
CoreDNS-1.5.0
linux/amd64, go1.12.2, e3f9a80
E0701 09:00:30.884138       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Get https://10.0.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0701 09:00:30.909719       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout`

Timing out on connecting to api server - can see the kubernetes service is in default namespace. I have put back CoreDNS deployment and configmap in /etc/kubernetes/addons to their defaults, upped the timeout to 10s and it still won't start.

In `kubectl describe pod`

`Warning  Unhealthy  4m41s (x151 over 29m)  kubelet, k8s-master-25167954-2  Readiness probe failed: Get http://10.16.144.65:8181/ready: dial tcp 10.16.144.65:8181: connect: connection refused`

No changes have been made to the vnet, this cluster was working in 1.14 and was upgraded in-place. Any ideas?

**Comment by grenzr** [comment]
I am running aks-engine 0.38.5 with k8s 1.15.1 and `kubectl edit deployment tiller-deploy -n kube-system` as @mboersma suggests doesn't seem to make it stick for me when running `helm init --upgrade` afterwards.
60 seconds later the `2.14.2` tiller container gets terminated and replaced with a `2.11.0` again.

Incidentally, tiller 2.11.0 is almost a year old. Can you clarify why this version is installed by default?

**Comment by grenzr** [comment]
update: updating all the `/etc/kubernetes/addons/kube-tiller-deployment.yaml` files on each master node and switching `Reconcile` to `EnsureExists` does make the tiller upgrade stick. It needs to be done on all master nodes.

**Comment by awr** [comment]
@fazdamoa I've run into a similar issue when the coredns pod gets scheduled to one of the master nodes in an HA setup. When it's scheduled to one of the agent nodes, no such issue. 

I believe there's an issue when a master nodes goes through the master lb and connects to the same node it originated from (ie same master) and runs into intermittent connection issues. I can't remember which issue that was from, and I am unsure of what actually causes the behavior. So it seems like it'd make sense to either figure out why the lb to same master is an issue, or remove the toleration from the coredns.yaml to force it onto an agent node.
