### ISSUE TITLE
kubernetes.io labels set via --node-label are unsupported for 1.16

### ISSUE THREAD

**Issue by adelina-t** [Azure/aks-engine#1546]
Kubernetes upstream PR: https://github.com/kubernetes/kubernetes/pull/79305  restricted the  labels that can be applied on the node via the kubelet --node-label flag. 

It basically errors out if the user tries to set labels that contain the "'kubernetes.io" namespace and are not part of the allowed set [1] or contain the allowed prefix [2][3].

In aks-engine, --node-flags set here [4] are not valid for 1.16 anymore.

[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/well_known_labels.go#L45-L58
[2] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/well_known_labels.go#L45-L58
[3] https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/well_known_labels.go#L30-L32
[4] https://github.com/Azure/aks-engine/blob/master/pkg/api/common/helper.go#L242-L243

**Comment by mboersma** [comment]
Thanks for the heads up @adelina-t.

**Comment by mboersma** [comment]
I have an alternative proposal to what's in #1548 

- Stop setting the `kubernetes.io/role` and `node-role.kubernetes.io` labels via `--node-labels` in kubelet startup
- Start setting `kubernetes.azure.com/role` in `--node-labels`
- Add a `node-labeler.sh` systemd unit that restores the (deprecated) master and agent labels, for backward compatibility
- Migrate the systemd unit to a Kubernetes controller or other component

I've prototyped most of this and think it could work. I'll try to put up a PR soon, but I'd love feedback at any time.

**Comment by mboersma** [comment]
Ok, the plan is as described above, with the addition of:

* Handle old and new labels in Azure cloud-provider
