### ISSUE TITLE
tiller container image not updated to version specified in apimodel.json upon cluster upgrade

### ISSUE THREAD

**Issue by mtgerb** [Azure/aks-engine#1583]
**Describe the bug**

The tiller deployment is not updated to the container image specified in the apimodel.json when upgrading the cluster

**Steps To Reproduce**

1. Create a cluster with kubernetes version 1.14.3
2. Change the container image of the tiller addon in the created apimodel.json to gcr.io/kubernetes-helm/tiller:v2.12.3
3. Run a cluster upgrade with -f

**Expected behavior**

The container image of the tiller deployment should be updated to the one specified in the apimodel.json

**AKS Engine version**

v0.37.4

**Kubernetes version**

1.14.3

**Additional context**

Cluster is running in the AzureGermanCloud

**Comment by CecileRobertMichon** [comment]
Hi @mtgerb, this is by design.

Addon images get set to the default for that component during upgrades to ensure that they are known working with that k8s version.

See https://github.com/Azure/aks-engine/blob/aadf3445f73abe2b9b6669da581b140360df03f7/docs/topics/clusterdefinitions.md#addons for more details.

> Additionally above, we specified a custom docker image for tiller, let's say we want to build a cluster and test an alpha version of tiller in it. **Important note!** customizing the image is not sticky across upgrade/scale, to ensure that aks-engine always delivers a version-curated, known-working addon when moving a cluster to a new version. Considering all that, providing a custom image reference for an addon configuration should be considered for testing/development, but not for a production cluster. If you'd like to entirely customize one of the addons available, including across scale/upgrade operations, you may include in an addon's spec a base64-encoded string of a Kubernetes yaml manifest. E.g.,
