### ISSUE TITLE
kube-apiserver missing priorityClass

### ISSUE THREAD

**Issue by fsigalov** [Azure/aks-engine#1602]
**Describe the bug**
kube-apiserver pods do not have a priorityClass or priority set. This means they run at priority 0 instead of system-node-critical

**Steps To Reproduce**
Install a kubernetes cluster using aks-engine

**Expected behavior**
kube-apiserver nodes should have a critical priority instead of 0. I believe because of this issue, the kube-apiserver is being evicted, and I can no longer connect to the cluster using kubectl.

**AKS Engine version**
v0.36.4

**Kubernetes version**
1.14.1

**Additional context**
> kubectl describe pod kube-apiserver-k8s-master-42716724-2 -n kube-system
Name:               kube-apiserver-k8s-master-42716724-2
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>

> kubectl describe pod kube-proxy-67kcf -n kube-system
Name:               kube-proxy-67kcf
Namespace:          kube-system
Priority:           2000001000
PriorityClassName:  system-node-critical

**Comment by sukhong** [comment]
+1.

kube-apiserver, kube-controller-manger, kube-scheduler are missing priorityClass, and being scheduled with priority: 0.

These should be scheduled with priorityClassName: system-node-critical (2000001000) or system-cluster-critical (2000000000).

**Comment by sukhong** [comment]
Created https://github.com/Azure/aks-engine/issues/2150
