### ISSUE TITLE
Application not accessible from outside cluster during aks-engine Upgrade

### ISSUE THREAD

**Issue by Bhuvaneswari-Santharam** [Azure/aks-engine#1624]
Applications are not accessible from outside the cluster during the aks-engine upgrade

**Steps To Reproduce**
1. Deploy application(say nginx) and service of type LoadBalancer to expose the application to be accessed from outside the cluster
2. Upgrade cluster using aks-engine upgrade. During upgrade operation the application will not be accessible from outside the cluster

**Expected behavior**
Should be able to access the application from outside the cluster during upgrade process

**AKS Engine version**
v0.36.2

**Kubernetes version**
1.12.8

**Additional context**

**Comment by marosset** [comment]
Can you comment on how the NSG rules were added?
Where they created as part of the initial AKS Engine template generation/deployment or where they rules added afterwards?

**Comment by Bhuvaneswari-Santharam** [comment]
Repro steps
1.	Used AKS-Engine v0.36.2 – deployed cluster, 3 master and 3 nodes
2.	Deploy the nginx application and create service of type loadbalancer
3.	Get the external-ip and try to access the application from outside the cluster
4.	Check the NSG Rules, the new rule for the app is added
5.	Upgrade the aks-engine, while upgrade process is running try accessing the application, it goes down
6.	Check the nsg rules, the application nsg rule is removed and comes up after sometime.

**Comment by marosset** [comment]
I was able to repro this on my own cluster.
It looks like when the NSG by the initial AKS engine deployment rules for port 80 are not created.
After deploying service type loadbalander the rule gets added which makes sense.
During the AKS engine upgrade the upgrade deployments contain ARM definitions for the NSG without the new rules and during very early during the upgrade process the ARM template gets deployed removing the rule :(

After speaking with @CecileRobertMichon  it sounds like we may be able to omit ARM resource definitions for the NSG in the upgrade templates with the hopes that the upgrade won't change any of the rules.
