### ISSUE TITLE
Cannot get client source IP when using custom vnet

### ISSUE THREAD

**Issue by TonyKingdom** [Azure/aks-engine#1634]
**Describe the request**

According to [Kubernetes official doc](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)，client source ip should be preserved the by setting kubernetes service config ```service.spec.externalTrafficPolicy```  as ```Local```.  I deployed a kubernetes cluster by aks-engine using an existing vnet, and failed to get get client source IP as described above.

However, without custom vnet configuration, the client source ip was preserved.  After digging into the aks-engine generated vnet, I found out that the vnet cidr have the same value as the default value of ```vnetCidr``` defined in ```masterProfile``` section.  I finally worked it out by configuring  the ```vnetCidr``` value as [documented](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md).

The documentation about ```vnetCidr``` should make it clear how it affects client souce IP and default value will break the rule. 

**Explain why AKS Engine needs it**

The documentation about ```vnetCidr``` is confusing and default value is meaningless for existing vnet.

**Describe alternatives you've considered**

Make the documentation more clearer or add each custom subnet cidr into the iptables other then ```vnetCidr``` .

**Additional context**

None

**Comment by salaxander** [comment]
@CecileRobertMichon I should be able to get this taken care of today
