### ISSUE TITLE
Support SSH IP range restriction

### ISSUE THREAD

**Issue by javierprovecho** [Azure/aks-engine#1644]
**Describe the request**

Currently SSH security rule origin of traffic is hardcoded to `*` here:

https://github.com/Azure/aks-engine/blob/da412af14dc37ce3e54f277710550dad11bec41e/pkg/engine/networksecuritygroups.go#L27

Allow to restrict access to Master VMs SSH by IP range.

**Explain why AKS Engine needs it**

Security purposes.

**Describe the solution you'd like**

Adding a property to api model. Ideally an array of ranges, but that would require creating multiple rules. The fastest approach would be to make configurable this property (https://github.com/Azure/aks-engine/blob/master/pkg/engine/networksecuritygroups.go#L27) and export it to the api model.

**Describe alternatives you've considered**

We can close it after cluster creation but a client side patch like this one may break future upgrades.

**Additional context**

We run clusters both in AWS (with kops) and Azure (with aks-engine). Kops has a property to restrict SSH access based on IP range(s).

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/cluster.go#L106-L107

**Comment by CecileRobertMichon** [comment]
related to https://github.com/Azure/aks-engine/issues/720
