### ISSUE TITLE
Enable prometheus scrape on cluster-autoscaler

### ISSUE THREAD

**Issue by shaikatz** [Azure/aks-engine#1654]
**Describe the request**
cluster-autoscaler offers a set of Prometheus metrics to get better visibility on his operations, I would like to be able to get them without patching the deployment.

**Explain why AKS Engine needs it**
AKS Engine should provide production-ready cluster without the need to self modify addons.

**Describe the solution you'd like**
I would like to add `prometheus.io/scrape: "true"` annotation to the cluster auto-scaler deployment and to define containerPort 8085.

This is the current patch that we using after the deployment to enable scraping:
```
kubectl patch -n kube-system deployment cluster-autoscaler -p '{"spec": {"template": {"metadata": {"annotations": {"prometheus.io/scrape": "true"}}, "spec": {"containers": [{"name": "cluster-autoscaler", "ports": [{"containerPort": 8085}]}]}}}}'
```

**Comment by C123R** [comment]
is this already available?

**Comment by NaumGj** [comment]
If you're using a LogAnalytics integration, you can see some of the CA metrics. To enable that, you need to go to your AKS, add a diagnostic setting under "Diagnostic settings" to send logs of the "cluster-autoscaler" category to a Log Analytics workspace. Then, in the "Azure Metrics" table in Log Analytics, one can see at least some of the CA metrics: cluster_autoscaler_scale_down_in_cooldown, cluster_autoscaler_cluster_safe_to_autoscale, cluster_autoscaler_unschedulable_pods_count, cluster_autoscaler_unneeded_nodes_count
