### ISSUE TITLE
Update azure-sdk-for-go w/ exponential backoff enabled

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1664]
Not sure yet which version of azure-sdk-for-go will get this change, but this canonical issue is a good place to start:

https://github.com/Azure/go-autorest/issues/398

**Comment by mboersma** [comment]
It doesn't appear this change is in the current [v31.1.0](https://github.com/Azure/azure-sdk-for-go/releases/tag/v31.1.0) based on the release notes and looking for `DoRetryForAttempts` in the source. So presumably the next release.
