### ISSUE TITLE
When will k8s 1.14.4 be shipped?

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#1674]
k8s 1.14.4 fixed a memory leak https://github.com/kubernetes/kubernetes/pull/78594 in Windows kubelet, I have to restart the Windows nodes every few days due to this bug. #1596 has been merged couple weeks ago, when will this be shipped?

**Comment by CecileRobertMichon** [comment]
available in https://github.com/Azure/aks-engine/releases/tag/v0.38.5
