### ISSUE TITLE
Missing HNS network on Windows Server 2019 Kubernetes nodes

### ISSUE THREAD

**Issue by bclau** [Azure/aks-engine#168]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: master

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes v1.13.0-alpha.2

**What happened**:

When deploying a Kubernetes cluster using Windows Server 2019 nodes, some of the nodes are not able to properly spawn Pods, and the kublet and azure-vnet logs are filled with ``Failed to create endpoint: hnsCall failed in Win32: Element not found. (0x490)`` errors [1]. Looking at the present HNS networks on those nodes [2], it can be seen that they only have 2 HNS networks, instead of the usual 3 HNS networks on healthy nodes [3].

This is not a consistent issue, some nodes can have this issue, while other nodes do not.

[1] https://paste.ubuntu.com/p/q5FDRQqXgb/
[2] https://paste.ubuntu.com/p/2dcXQqknRt/
[3] https://paste.ubuntu.com/p/85pPdZwMdp/

**What you expected to happen**:

Pods should be able to enter a ``Running`` State on all Windows Server 2019 nodes in a Kubernetes deployment.

**How to reproduce it** (as minimally and precisely as possible):

1. Deploy a Kubernetes cluster with Windows Server 2019 nodes.
2. Spawn pods on all Window Server 2019 nodes. ( https://paste.ubuntu.com/p/8DF9pM8F7c/  )
3. Check if all the pods end up in a ``Running`` state. If they do, goto 1.
4. If a pod does not enter the ``Running`` state, check the ``C:\k\kubelet.err.log`` and ``C;\k\azure-vnet.log`` files and check the mentioned errors.
5. Check the HNS networks: ``Get-HNSNetwork``

**Anything else we need to know**:

**Comment by PatrickLang** [comment]
I moved this over to the new repo that we're using for future releases :)

**Comment by zhiweiv** [comment]
I built a cluster a few days ago with aks-engine 0.27/Windows Server 2019/k8s 1.13.1, deployed some pods to Windows node yesterday, today these pods all became Error. The error in logs is "HNS failed with error : The endpoint was not found".

The error began to appear since 1218 17:30:29 in kubelet.err-20181218T174129.272.log.

Here are full logs and config file. 
[k.zip](https://github.com/Azure/aks-engine/files/2693068/k.zip)
[kubernetes.zip](https://github.com/Azure/aks-engine/files/2693070/kubernetes.zip)

**Comment by zhiweiv** [comment]
Some similiar issues in previous version.
https://github.com/Azure/acs-engine/issues/4046
https://github.com/Azure/acs-engine/issues/3920

**Comment by zhiweiv** [comment]
Had a quick test with azure-cni 1.0.16 by instruction from https://github.com/Azure/azure-container-networking/issues/287, looks good so far.
