### ISSUE TITLE
Outbound rule for Standard Load balancer

### ISSUE THREAD

**Issue by sylr** [Azure/aks-engine#1689]
**Describe the request**

In order to be able to fix what would be the outbound public IP of pods it would be nice if we could tell aks-engine to generate a pool of X public IPs which would be used in a load balancer outbound rule.

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ritazh** [comment]
Are you referring to this? https://docs.microsoft.com/en-us/azure/virtual-network/public-ip-address-prefix

**Comment by sylr** [comment]
After giving more thought about this I think it should be directly implemented in the kubernetes azure cloud provider.

See:
- https://github.com/kubernetes/cloud-provider-azure/issues/204
- https://github.com/kubernetes/cloud-provider-azure/issues/203

**Comment by ritazh** [comment]
The default behavior when using SLB is that aks-engine will create the SLB, which includes a fontend PIP and the outbound rule for your agent nodes, unless you provide `agentProfile.LoadBalancerBackendAddressPoolIDs` , then the SLB and the outbound rule will need to be updated by the component that created that SLB outside of aks-engine. See this PR for more info: https://github.com/Azure/aks-engine/pull/1622

Once this SLB is created, then all services of loadbalancer type will be added to this SLB, unless its an ILB, in which case the cloud provider will create a standard ILB. So I think what you are asking for should be added to the SLB creation logic as part of aks-engine, not the cloud provider.

WDYT?
