### ISSUE TITLE
Add feature flag to check ACR connectivity

### ISSUE THREAD

**Issue by thomas1206** [Azure/aks-engine#1696]
Currently, the CSE in AKS engine will check GCR and docker.io connectivity. To enable AKS locking down egress feature, we need check the ACR instead of GCR and docker.io.  Our ACR endpoint:
aksrepos.azurecr.io:443

@jackfrancis

**Comment by jackfrancis** [comment]
@thomas1206 are we able to use the same URI for china cloud as well? Currently we validate `gcr.azk8s.cn:80` in a china cloud context.

**Comment by thomas1206** [comment]
The ACR feature is still not enabled on Mooncake yet. For Mooncake, we need keep the current behavior.
