### ISSUE TITLE
NetworkPlugin cni failed to set up pod - unexpected end of JSON input

### ISSUE THREAD

**Issue by kwaazaar** [Azure/aks-engine#1706]
**Describe the bug**
Pods remain in ContainerCreating status. This happens to several pods that are all scheduled on the same node of the cluster. I fixed it by rebooting the node VM, but AKS or Kubernetes don't fix this for me: the error should be considered fatal and the node should be marked NotReady.

**Steps To Reproduce**
Not sure, just happened on 1 node of our 8 node cluster. This node is actually just a couple of days old.

**Expected behavior**
I think the error comes from communication between cni and kubelet, where kubelet expects the error message to be in json format. When no json is received, it should consider the node to be unhealthy and mark it NotReady, so the pods get rescheduled. Current situation is not really auto-healing :-(

**AKS Engine version**
AKS cluster in West Europe.

**Kubernetes version**
v1.12.7

**Additional context**
On the node, the /var/log/azure-vnet.log contains errors like these:
2019/07/31 10:04:35 Failed to initialize key-value store of network plugin, err:timed out locking store.
2019/07/31 10:04:35 Report plugin error

And the plugin seems to be restarting a lot:
**2019/07/30 11:46:24 [cni-net] Plugin started.**
2019/07/30 11:46:24 [cni-net] Processing DEL command with args {ContainerID:91fb70dbdfad56aaaf0b426c2829a76f1d5310f12dcce147b1ba934dd4c9cccf Netns: IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=;K8S_POD_NAME=;K8S_POD_INFRA_CONTAINER_ID=91fb70dbdfad56aaaf0b426c2829a76f1d5310f12dcce147b1ba934dd4c9cccf Path:/opt/cni/bin}.
2019/07/30 11:46:24 [cni-net] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: InfraVnetAddressSpace: PodNamespaceForDualNetwork:[] MultiTenancy:false EnableSnatOnHost:false EnableExactMatchForPodName:false CNSUrl: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RuntimeConfig:{PortMappings:[] DNS:{Servers:[] Searches:[] Options:[]}} AdditionalArgs:[]}.
2019/07/30 11:46:24 Get number of endpoints for ifname eth0 network azure
2019/07/30 11:46:24 Pod Namespace not specified in CNI Args
2019/07/30 11:46:24 [azure-vnet] Pod Namespace not specified in CNI Args.
2019/07/30 11:46:24 [cni-net] DEL command completed with err:Pod Namespace not specified in CNI Args.
2019/07/30 11:46:24 Failed to execute network plugin, err:Pod Namespace not specified in CNI Args.
**2019/07/30 11:46:24 [cni-net] Plugin stopped.**
2019/07/30 11:48:30 [cni-net] Plugin azure-vnet version v1.0.22.
2019/07/30 11:48:30 [cni-net] Running on Linux version 4.15.0-1051-azure (buildd@lgw01-amd64-016) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #56-Ubuntu SMP Thu Jul 4 23:10:21 UTC 2019

Also note there's a 2 minute gap in the log after the plugin stopped.

**Comment by kwaazaar** [comment]
**Full log from start to stop:**

2019/07/30 11:14:09 [cni-net] Plugin azure-vnet version v1.0.22.
2019/07/30 11:14:09 [cni-net] Running on Linux version 4.15.0-1051-azure (buildd@lgw01-amd64-016) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #56-Ubuntu SMP Thu Jul 4 23:10:21 UTC 2019
2019/07/30 11:14:09 [net] Network interface: {Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback} with IP addresses: [127.0.0.1/8 ::1/128]
2019/07/30 11:14:09 [net] Network interface: {Index:2 MTU:1500 Name:eth0 HardwareAddr:00:0d:3a:38:6f:1f Flags:up|broadcast} with IP addresses: [fe80::20d:3aff:fe38:6f1f/64]
2019/07/30 11:14:09 [net] Network interface: {Index:3 MTU:1500 Name:enP1p0s2 HardwareAddr:00:0d:3a:38:6f:1f Flags:up|broadcast|multicast} with IP addresses: []
2019/07/30 11:14:09 [net] Network interface: {Index:4 MTU:1500 Name:docker0 HardwareAddr:02:42:82:4c:ba:e6 Flags:up|broadcast|multicast} with IP addresses: [172.17.0.1/16]
2019/07/30 11:14:09 [net] Network interface: {Index:5 MTU:1500 Name:azure0 HardwareAddr:00:0d:3a:38:6f:1f Flags:up|broadcast|multicast} with IP addresses: [10.234.20.37/20 fe80::20d:3aff:fe38:6f1f/64]
2019/07/30 11:14:09 [net] Network interface: {Index:7 MTU:1500 Name:azvc4fc8bf8bed HardwareAddr:aa:5d:b2:f5:49:1b Flags:up|broadcast} with IP addresses: [fe80::a85d:b2ff:fef5:491b/64]
2019/07/30 11:14:09 [net] Network interface: {Index:9 MTU:1500 Name:azvb9d065bfbb7 HardwareAddr:26:c2:0d:0f:00:58 Flags:up|broadcast} with IP addresses: [fe80::24c2:dff:fe0f:58/64]
2019/07/30 11:14:09 [net] Network interface: {Index:11 MTU:1500 Name:azvfd4a48dc715 HardwareAddr:be:67:81:eb:52:2a Flags:up|broadcast} with IP addresses: [fe80::bc67:81ff:feeb:522a/64]
2019/07/30 11:14:09 [net] Network interface: {Index:21 MTU:1500 Name:azv18d8ed5ff0e HardwareAddr:0a:d6:f5:1b:72:93 Flags:up|broadcast} with IP addresses: [fe80::8d6:f5ff:fe1b:7293/64]
2019/07/30 11:14:09 [net] Network interface: {Index:283 MTU:1500 Name:azv337bff5ef18 HardwareAddr:d6:55:98:c7:56:b3 Flags:up|broadcast} with IP addresses: [fe80::d455:98ff:fec7:56b3/64]
2019/07/30 11:14:09 [net] Network interface: {Index:73 MTU:1500 Name:azv635dfbc92d7 HardwareAddr:f2:83:96:47:e2:52 Flags:up|broadcast} with IP addresses: [fe80::f083:96ff:fe47:e252/64]
2019/07/30 11:14:09 [net] Network interface: {Index:75 MTU:1500 Name:azv34b692c9418 HardwareAddr:06:af:65:41:02:fc Flags:up|broadcast} with IP addresses: [fe80::4af:65ff:fe41:2fc/64]
2019/07/30 11:14:09 [net] Network interface: {Index:77 MTU:1500 Name:azv7a5e5fa0a2b HardwareAddr:52:d9:87:eb:c6:59 Flags:up|broadcast} with IP addresses: [fe80::50d9:87ff:feeb:c659/64]
2019/07/30 11:14:09 [net] Network interface: {Index:83 MTU:1500 Name:azv976c66c3cc4 HardwareAddr:3a:ee:ea:38:47:f3 Flags:up|broadcast} with IP addresses: [fe80::38ee:eaff:fe38:47f3/64]
2019/07/30 11:14:09 [net] Network interface: {Index:91 MTU:1500 Name:azvdc364dc5aaf HardwareAddr:4a:ce:9e:45:6e:85 Flags:up|broadcast} with IP addresses: [fe80::48ce:9eff:fe45:6e85/64]
2019/07/30 11:14:09 [net] Network interface: {Index:93 MTU:1500 Name:azv072ab1e6dc9 HardwareAddr:de:a4:ed:93:56:f2 Flags:up|broadcast} with IP addresses: [fe80::dca4:edff:fe93:56f2/64]
2019/07/30 11:14:09 [net] Network interface: {Index:97 MTU:1500 Name:azv08a7663ec67 HardwareAddr:ca:47:bc:3c:f7:e5 Flags:up|broadcast} with IP addresses: [fe80::c847:bcff:fe3c:f7e5/64]
2019/07/30 11:14:09 [net] Network interface: {Index:123 MTU:1500 Name:azv5f44a87a7fc HardwareAddr:7e:4c:f3:87:39:4f Flags:up|broadcast} with IP addresses: [fe80::7c4c:f3ff:fe87:394f/64]
2019/07/30 11:14:09 [net] Network interface: {Index:155 MTU:1500 Name:azv3507b6f94d4 HardwareAddr:82:73:75:ad:d9:ac Flags:up|broadcast} with IP addresses: [fe80::8073:75ff:fead:d9ac/64]
2019/07/30 11:14:09 [net] Network interface: {Index:185 MTU:1500 Name:azvf04dc3a183d HardwareAddr:22:c9:8c:f6:4d:6b Flags:up|broadcast} with IP addresses: [fe80::20c9:8cff:fef6:4d6b/64]
2019/07/30 11:14:09 [net] Network interface: {Index:237 MTU:1500 Name:azv91964a4d7a8 HardwareAddr:6e:a2:3f:be:8b:a2 Flags:up|broadcast} with IP addresses: [fe80::6ca2:3fff:febe:8ba2/64]
2019/07/30 11:14:09 [net] Network interface: {Index:239 MTU:1500 Name:azv5e0658bb9f1 HardwareAddr:be:7e:5e:95:d7:fb Flags:up|broadcast} with IP addresses: [fe80::bc7e:5eff:fe95:d7fb/64]
2019/07/30 11:14:09 [net] Network interface: {Index:241 MTU:1500 Name:azv0b8b0b84b92 HardwareAddr:22:8a:ef:c6:92:40 Flags:up|broadcast} with IP addresses: [fe80::208a:efff:fec6:9240/64]
2019/07/30 11:14:09 [net] reboot time 2019-07-24 07:25:22 +0000 UTC store mod time 2019-07-30 10:50:47.691444376 +0000 UTC
2019/07/30 11:14:09 [net] Restored state, &{Version:v1.0.22 TimeStamp:2019-07-30 10:50:47.697996537 +0000 UTC ExternalInterfaces:map[eth0:0xc0001fa000] store:0xc000083470 Mutex:{state:0 sema:0}}
2019/07/30 11:14:09 External Interface &{Name:eth0 Networks:map[azure:0xc00011e090] Subnets:[10.234.16.0/20] BridgeName:azure0 DNSInfo:{Suffix: Servers:[]} MacAddress:00:0d:3a:38:6f:1f IPAddresses:[10.234.20.37/20] Routes:[0xc00011e120] IPv4Gateway:10.234.16.1 IPv6Gateway:::}
2019/07/30 11:14:09 network &{Id:azure HnsId: Mode:bridge VlanId:0 Subnets:[{Family:2 Prefix:{IP:10.234.16.0 Mask:fffff000} Gateway:10.234.16.1}] Endpoints:map[cc84db86-eth0:0xc00020c780 12646c41-eth0:0xc000066f00 2138a713-eth0:0xc000067200 39d0c7e0-eth0:0xc000067500 5d21d600-eth0:0xc000067b00 6b95ccaa-eth0:0xc000067e00 807a9233-eth0:0xc00020c180 a4c47506-eth0:0xc00020c600 e8125ad2-eth0:0xc00020c900 42061857-eth0:0xc000067680 458d61b5-eth0:0xc000067800 692fa10d-eth0:0xc000067c80 16cde1b0-eth0:0xc000067080 85791906-eth0:0xc00020c480 32239016-eth0:0xc000067380 494e13a6-eth0:0xc000067980 7a0f4aa2-eth0:0xc00020c000 84abbef0-eth0:0xc00020c300] extIf:0xc0001fa000 DNS:{Suffix: Servers:[168.63.129.16]} EnableSnatOnHost:false}
2019/07/30 11:14:09 endpoint &{Id:a4c47506-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azvb9d065bfbb7 MacAddress:f2:9a:88:0f:b6:24 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.123 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/5834/ns/net ContainerID:a4c4750696fc5fcabcec50ee8786cf259805a11b96b2ae718935a51bba501962 PODName:restic-4m5hh PODNameSpace:heptio-ark InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:cc84db86-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azvdc364dc5aaf MacAddress:42:1a:fd:01:ba:d5 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.97 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/128260/ns/net ContainerID:cc84db8639d1d53e690100e775e4229b75586040a4b76aba5d3bdb43d33c706b PODName:blueriq-deployment-mutaties-rentewijzigen-beleid-578fcb996jrthq PODNameSpace:test InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:12646c41-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv18d8ed5ff0e MacAddress:be:03:3b:38:76:a9 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.110 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/15698/ns/net ContainerID:12646c41ea3912a0c15e6195af4043d123d308e0b898d6a7b68b46c313027ba5 PODName:kenuwklant-deployment-55c46f64fb-ssq82 PODNameSpace:test InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:2138a713-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv635dfbc92d7 MacAddress:82:6b:e3:22:6d:20 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.160 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/116663/ns/net ContainerID:2138a713f54a70e5e01c4c8a72eaada81632087bd21a0a6442d385361e05ca59 PODName:berichten-deployment-5d88649496-zfd8c PODNameSpace:development InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:39d0c7e0-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv976c66c3cc4 MacAddress:1e:26:db:5a:3e:42 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.38 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/62572/ns/net ContainerID:39d0c7e0f1652eb3f6579117d2abce2ccc243f96861ef6c3f29f1f61d61855cd PODName:mutaties-order-deployment-85c98d5d96-7zpgm PODNameSpace:development InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:5d21d600-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv91964a4d7a8 MacAddress:1a:41:30:e2:74:9d InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.131 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/107754/ns/net ContainerID:5d21d60026c5decbfc7988869f971621c6a57771322739c1519940c4de7d2a97 PODName:kredietgids-frontend-florius-deployment-ddd7f4989-fp652 PODNameSpace:development InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:6b95ccaa-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azvc4fc8bf8bed MacAddress:d6:18:59:a0:ca:aa InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.122 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/5077/ns/net ContainerID:6b95ccaa6ca59a331095526f9a89ee7beedf69fe8966b76401b8d54cefba5cd8 PODName:kured-7fv4p PODNameSpace:kube-system InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:807a9233-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv072ab1e6dc9 MacAddress:f2:5c:84:b9:56:ca InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.103 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/13547/ns/net ContainerID:807a923342413ac19bf8155e46ab2dffe345f83b65d9c02571770f9ca600ad13 PODName:mutaties-order-deployment-5d798b49fd-xs22g PODNameSpace:test InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:e8125ad2-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv337bff5ef18 MacAddress:ae:00:e1:36:d2:19 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.128 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/39072/ns/net ContainerID:e8125ad243f8f7e51d9847597dae6d90f7803cc5f868c145c4feec29c3202f61 PODName:internal-ingresscontroller-nginx-ingress-controller-7f8c672kmj5 PODNameSpace:kube-system InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:42061857-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azvf04dc3a183d MacAddress:82:b6:6f:7d:26:7d InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.115 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/68290/ns/net ContainerID:42061857d621aae0a09198189c5d203e6e91fa63461ccdce12f1334ef94bca2c PODName:zalenium-40000-txkpx PODNameSpace:zaleniumtest InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:458d61b5-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv7a5e5fa0a2b MacAddress:0e:68:11:27:ec:08 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.46 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/120241/ns/net ContainerID:458d61b57ee2161c5d425293792945aeb28a9c1cb7f3dfe266b59b2d9a29ea1b PODName:berichten-deployment-65cf87d9c6-8tgb2 PODNameSpace:test InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:692fa10d-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv0b8b0b84b92 MacAddress:aa:8b:2f:f8:7b:f4 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.119 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/64652/ns/net ContainerID:692fa10d57c2d905e598206eaa711518b100f71cedbd4462e55e7d66fb4f000e PODName:tokenservice-deployment-575565bb4b-9n8tz PODNameSpace:prep InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:16cde1b0-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv08a7663ec67 MacAddress:b6:b9:d9:d1:13:75 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.153 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/35715/ns/net ContainerID:16cde1b01ab4a5c342e09b6b0c23e89d690cc7aed37f472210c28fe805685503 PODName:mutaties-rentewijzigen-deployment-68bbbb6d9c-mx84f PODNameSpace:development InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:85791906-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv3507b6f94d4 MacAddress:ae:88:69:8e:36:f5 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.170 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/58620/ns/net ContainerID:85791906a72d9b1f017aab18f55ff88b9bc3ba3c2e0ca68a230b9c5850926747 PODName:kredietgids-backend-deployment-6ddfb799f9-9vwqp PODNameSpace:test InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:32239016-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv5e0658bb9f1 MacAddress:d2:e8:47:af:34:65 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.121 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/107824/ns/net ContainerID:322390168a67a7e0e7714bb253e7a6733348b49ead707dfbe6b4d4676600a59d PODName:kredietgids-frontend-intern-deployment-b6676b9b5-94wtc PODNameSpace:development InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:494e13a6-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv5f44a87a7fc MacAddress:82:48:6a:14:ee:2e InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.66 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/13835/ns/net ContainerID:494e13a623c91765a1e1673b53dddaf363a20d82b742060f01fa266a1263833a PODName:kredietgids-backend-deployment-7555d4d6b5-kj7gz PODNameSpace:development InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:7a0f4aa2-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azv34b692c9418 MacAddress:1e:75:6f:a4:f2:6d InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.185 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/124286/ns/net ContainerID:7a0f4aa2fb8b2fd2e066c95adb78bd7a873850e6c40651dc4dfdeafd91b1724c PODName:berichten-deployment-5d88649496-m94br PODNameSpace:development InfraVnetAddressSpace:}
2019/07/30 11:14:09 endpoint &{Id:84abbef0-eth0 HnsId: SandboxKey: IfName:eth0 HostIfName:azvfd4a48dc715 MacAddress:6e:6e:f8:9b:a8:30 InfraVnetIP:{IP:<nil> Mask:<nil>} IPAddresses:[{IP:10.234.20.120 Mask:fffff000}] Gateways:[10.234.16.1] DNS:{Suffix: Servers:[168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Src:<nil> Gw:10.234.16.1 Protocol:0 DevName: Scope:0}] VlanID:0 EnableSnatOnHost:false EnableInfraVnet:false EnableMultitenancy:false NetworkNameSpace:/proc/6466/ns/net ContainerID:84abbef0957c86a73b386d612be13ef7f48cda018a171a901efc2619ccf3cd1b PODName:omsagent-dqh6d PODNameSpace:kube-system InfraVnetAddressSpace:}
2019/07/30 11:14:09 [cni-net] Plugin started.
2019/07/30 11:14:09 [cni-net] Processing DEL command with args {ContainerID:d5f6a276ade29de707dc2b35dc7d8ac3341a50b64dd2eab4744b4819f177d9cf Netns: IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=;K8S_POD_NAME=;K8S_POD_INFRA_CONTAINER_ID=d5f6a276ade29de707dc2b35dc7d8ac3341a50b64dd2eab4744b4819f177d9cf Path:/opt/cni/bin}.
2019/07/30 11:14:09 [cni-net] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: InfraVnetAddressSpace: PodNamespaceForDualNetwork:[] MultiTenancy:false EnableSnatOnHost:false EnableExactMatchForPodName:false CNSUrl: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RuntimeConfig:{PortMappings:[] DNS:{Servers:[] Searches:[] Options:[]}} AdditionalArgs:[]}.
2019/07/30 11:14:09 Get number of endpoints for ifname eth0 network azure
2019/07/30 11:14:09 Pod Namespace not specified in CNI Args
2019/07/30 11:14:09 [azure-vnet] Pod Namespace not specified in CNI Args.
2019/07/30 11:14:09 [cni-net] DEL command completed with err:Pod Namespace not specified in CNI Args.
2019/07/30 11:14:09 Failed to execute network plugin, err:Pod Namespace not specified in CNI Args.
2019/07/30 11:14:09 [cni-net] Plugin stopped.

**Comment by jackfrancis** [comment]
@tamilmani1989 Are you aware of the above behavior?

Thanks for reporting @kwaazaar!

**Comment by tamilmani1989** [comment]
@jackfrancis kubelet calls CNI DEL with empty pod name and namespace. Might be pod already deleted. This is not an issue.

Processing DEL command with args {ContainerID:d5f6a276ade29de707dc2b35dc7d8ac3341a50b64dd2eab4744b4819f177d9cf Netns: IfName:eth0 Args:IgnoreUnknown=1**;K8S_POD_NAMESPACE=;K8S_POD_NAME=;**K8S_POD_INFRA_CONTAINER_ID=d5f6a276ade29de707dc2b35dc7d8ac3341a50b64dd2eab4744b4819f177d9cf Path:/opt/cni/bin}.

**Comment by tamilmani1989** [comment]
@jackfrancis Sorry i didn't notice this log:
2019/07/31 10:04:35 Failed to initialize key-value store of network plugin, err:**timed out locking store.**
2019/07/31 10:04:35 Report plugin error

This looks like cni issue and might be the issue I fixed in latest release v1.0.25

**Comment by kwaazaar** [comment]
Hi, running into this issue again. AKS running Kubernetes 1.14.8. Shouldn't this have been resolved?

I try to find the AKS-engine version used by AKS. I used this statement: az vm show -n aks-agentpool-24722116-2 -g MC_aks-acc-rg_aahnl-kubernetes-acc_westeurope --query tags
This is the output:
~~~
{
  "aksEngineVersion": "v0.41.5-aks",
  "creationSource": "aks-aks-agentpool-24722116-2",
  "orchestrator": "Kubernetes:1.14.8",
  "poolName": "agentpool",
  "resourceNameSuffix": "24722116"
}
~~~

**Comment by kwaazaar** [comment]
I'm seeing these errors again:
Events:
  Type     Reason                  Age                      From                               Message
  ----     ------                  ----                     ----                               -------
  Normal   SandboxChanged          24m (x353 over 7h3m)     kubelet, aks-agentpool-24722116-7  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  3m28s (x354 over 6h50m)  kubelet, aks-agentpool-24722116-7  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c3be15f1752b72c414c084115c4256ae3b05f8a8582ff720f0fbecaf31b757e0" network for pod "berichten-jobs-stuuringeplandeberichten-cronjob-15815910602mzx4": **NetworkPlugin cni failed to set up pod** "berichten-jobs-stuuringeplandeberichten-cronjob-15815910602mzx4_acceptatie" network: **unexpected end of JSON input**

**Comment by Michael-Sinz** [comment]
We just had this happen again on some v1.15 kubernetes clusters.

Is this supposed to be fixed?  If so, which versions have the fix?

**Comment by jackfrancis** [comment]
@tamilmani1989 can you remind us how to find the Azure CNI version on a host?

**Comment by gurudattest** [comment]
Hi,
We're facing the exact same issue. Any update on this ?

**Comment by tamilmani1989** [comment]
There was a fix made related to lock issue in v1.0.30. The current latest version of cni is v1.0.33

@jackfrancis Running `/opt/cni/bin/azure-vnet -v ` will show version.  It looks like @kwaazaar was using old version v.10.29 which doesn't have that fix. can you please upgrade your aks-engine cluster?

**Comment by Incarnation-p-lee** [comment]
@tamilmani1989 
Is there any mapping between cni version and aks version, just take a look from node, aks 1.13.11 have had cni v1.0.27 which is too old.

As I understanding, this can be fixed by upgrade aks version, right ?

**Comment by shiyuan-extreme** [comment]
we met the same issue, too

> root@aks-ignite4-31975340-vmss000000:/var/log/azure# /opt/cni/bin/azure-vnet -v
Azure CNI Version v1.1.6
