### ISSUE TITLE
Default cluster setup with multiple agent pools does not properly deal with ingress

### ISSUE THREAD

**Issue by rocketraman** [Azure/aks-engine#172]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.25.3

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

**What happened**:

Building a pretty bog standard cluster (vmss, managed disks, azure CNI, default settings for accelerated networking), but with more than one agent pool, results in problems with ingress into the cluster. For example, configuring an nginx ingress controller configures one vmss as a backend in the load balancer. If the nginx ingress pod is scheduled onto the other vmss, it is unable to receive any traffic. Presumably this is the case for any inbound pod traffic using a Cluster or Node IP, but I did not test it.

**What you expected to happen**:

I expect that networking would work correctly in this relatively simple setup.

**How to reproduce it** (as minimally and precisely as possible):

Create a standard cluster with multiple agent pools, vmss, azure CNI, and defaults for accelerated networking. Schedule an nginx ingress controller onto the agent pool vmss that is *not* shown as a backend in the load balancer. Attempt to use it.

**Anything else we need to know**:

**Comment by rocketraman** [comment]
@andyzhangx If that is so, then shouldn't a standard load balancer be the default if there is more than one agent pool? At the very least, the documentation for `loadBalancerSku` should mention this case.

**Comment by andyzhangx** [comment]
@feiskyer

**Comment by feiskyer** [comment]
> If that is so, then shouldn't a standard load balancer be the default if there is more than one agent pool? At the very least, the documentation for loadBalancerSku should mention this case.

Reasonable. One mitigation is binding the ingress pod to the nodes of primary scale set.

@jackfrancis What do you think of defaulting to standard load balancer?

**Comment by jackfrancis** [comment]
@sozercan @ritazh making standard LB the default means we have our "rebooting vmss instances" problem during upgrades, right?

**Comment by sozercan** [comment]
@jackfrancis standard LB is part of it (requires v1.11+) for adding multiple VMSS to LB backendpools. we also need to create a new vmss instead of +1/-1 in existing vmss, so need to change upgrade logic as well (which we are testing currently).

**Comment by rocketraman** [comment]
Not sure why this was closed, requesting re-open.

**Comment by jackfrancis** [comment]
@rocketraman does the current aks-engine implementation of Standard LB-enabled cluster have gaps? Or is the ask to move Standard LB to default?

**Comment by rocketraman** [comment]
> @rocketraman does the current aks-engine implementation of Standard LB-enabled cluster have gaps? Or is the ask to move Standard LB to default?

Honestly, I don't know, I haven't tested this in a while. It appears to have gaps for upgrades based on this earlier comment, though perhaps this information is out of date:

https://github.com/Azure/aks-engine/issues/172#issuecomment-448705308

If that issue is resolved, I'm fine with closing this (ideally with note in the documentation that if multiple agent pools are configured, a standard LB is recommended).

**Comment by jackfrancis** [comment]
Let's assume this is not fixed as a forcing function for us to repro. What's the repro?

1) Build a cluster with > 1 VMSS agent pools
2) Use Standard LB
3) nginx + svc + ingress
4) send traffic to nginx endpoint

Is that it?

**Comment by rocketraman** [comment]
> Is that it?

- Validate nginx ingress works regardless of which VMSS agent pool it is scheduled in
- Validate upgrades work (I don't know anything about issues with standard LB and upgrades, but clearly there have been issues with this in the past)

**Comment by jackfrancis** [comment]
This PR may have addressed (at least some) of these issues:

https://github.com/Azure/aks-engine/pull/1622
