### ISSUE TITLE
Clean up cloud-init artifacts on VHD-built images

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1720]
@jasonzio said:

> Running waagent –deprovision cleans up the contents of /var/lib/waagent, removes user authentication credentials, (usually) removes user home directories, etc. When preparing a cloud-init based VM for clean reuse, you also need to tell cloud-init to reset itself. The command cloud-init clean -logs will remove cloud-init artifacts from /var/lib/cloud so cloud-init will re-run all stages as it did on first boot, and it cleans up the cloud-init log files so the next boot of the VM gets a clean log.
 
> When we build cloud-init-ready images, we perform both actions as the last commands in our packer scripts.

**Comment by jackfrancis** [comment]
`cloud-init clean --logs` is the correct usage

**Comment by jackfrancis** [comment]
`waagent -force -deprovision` is the correct usage

**Comment by CecileRobertMichon** [comment]
see #1717 on some notes I had on how to do this
