### ISSUE TITLE
Metrics-server `CreateContainerConfigError` in 1.16.0-alpha.2

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#1742]
**Describe the bug**
On an AKS Engine Kubernetes 1.16.0-alpha.2 cluster, the metrics-server deployment fails to start a pod.

See also #1714

**Steps To Reproduce**
Create a vanilla aks-engine cluster with `--set orchestratorProfile.orchestratorRelease=1.16`. When it's up, notice that the metrics-server pod didn't start:
`Error: container has runAsNonRoot and image will run as root`

**Expected behavior**
metrics-server starts without errors.

**AKS Engine version**
v0.39.0 or master

**Kubernetes version**
1.16.0-alpha.2. This is not an issue on earlier versions of Kubernetes. 

**Additional context**

**Comment by mboersma** [comment]
This is not reproducible with Kubernetes 1.16.0-alpha.3.

**Comment by palmerabollo** [comment]
I think this might be related https://github.com/Azure/aks-engine/issues/1851
