### ISSUE TITLE
package update failure when walinuxagent upgrading and call the custom script at the same time.

### ISSUE THREAD

**Issue by andyliuliming** [Azure/aks-engine#1743]
**Describe the bug**
when the walinuxagent upgrading, the custom script extension call will fail.
**Steps To Reproduce**

**Expected behavior**
I think may be we should think about to use the customData in the os profile( cloud-init ) do the setup steps, or just do a hold on the walinuxagent when we call the custom script.

apt-mark hold walinuxagent
... our custom script ...
apt-mark unhold walinuxagent

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by CecileRobertMichon** [comment]
We are already placing a hold on walinuxagent in cloud init run cmd: https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/nodecustomdata.yml#L334

**Comment by CecileRobertMichon** [comment]
We are also holding walinuxagent in CSE before the first apt-get update operation as a precaution (should be a no-op if cloud-init already ran) in case CSE starts before cloud-init finishes: https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/artifacts/cse_install.sh#L41

**Comment by CecileRobertMichon** [comment]
Already fixed in aks-engine v0.33.0+
