### ISSUE TITLE
aks-engine vs aks managed cluster 

### ISSUE THREAD

**Issue by rexhinvorpsi** [Azure/aks-engine#1744]
Hi everyone, 
I have to do a custom cluster enabling feature gates so normally i used aks-engine in my own test Azure account with everything enabled. 
Now my company has an Azure Enterprise account with only certain services enabled( Kubernetes service is not enabled). 
Do i need the Kubernetes service enabled in the subscription to be able to deploy the custom cluster? 

Thank you!

**Comment by CecileRobertMichon** [comment]
Hi there, for docs about AKS Engine vs. AKS see https://github.com/Azure/aks-engine/blob/master/docs/faq.md#whats-the-difference-between-aks-and-aks-engine.

I'm not sure I understand you question about deploying a "custom" cluster? What do you call custom cluster? If you are trying to deploy a cluster with AKS Engine (this repo), you don't need the AKS service to be enabled in the sub. If you want an AKS managed cluster, you will need AKS enabled in the sub. Does that answer your question @rexhinvorpsi ?

**Comment by rexhinvorpsi** [comment]
Sorry for the naming i just meant not a managed cluster. Yes that does answer my question. 
Thank you very much Cecile
