### ISSUE TITLE
extensionProfiles is failing with aks-binary > 0.36 

### ISSUE THREAD

**Issue by satishsudini** [Azure/aks-engine#1751]
**Describe the bug**
extensionProfiles is failing with aks-binary > 0.36  working fine with 0.32 and below

**Steps To Reproduce**
{
  ...
  "extensionProfiles": [
    {
        "name": "hello-world-dcos",
        "version": "v1",
        "extensionParameters": "parameters",
        "rootURL": "http://mytestlocation.com/hello-world-dcos/",
        "script": "hello-world-dcos.sh"
    }
  ]
}

**AKS Engine version**
>0.36 (0.36-0.39)

**Kubernetes version**
1.15 

**Additional context**

"extensionProfiles": [
      {
          "name": "bootstrap",
          "version": "v1”,
          "extensionParameters": “*”,
          "rootURL": "https://*.blob.core.windows.net/",
          "script": “script.sh",
          "urlQuery": “token”
      },

**Comment by CecileRobertMichon** [comment]
Any reason you're using the DCOS hello world? Not Kubernetes?

**Comment by satishsudini** [comment]
Just i mentioned sample but actual snippet is below 

"extensionProfiles": [
{
"name": "bootstrap",
"version": "v1”,
"extensionParameters": “”,
"rootURL": "https://.blob.core.windows.net/",
"script": “script.sh",
"urlQuery": “token”
},

**Comment by CecileRobertMichon** [comment]
@satishsudini what error are you getting exactly?

**Comment by CecileRobertMichon** [comment]
I was not able to repro with the following api model (latest aks-engine version):

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v3",
      "extensions": [
        {
          "name": "hello-world-k8s"
        }
      ]
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v3"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "extensionProfiles": [
      {
        "name": "hello-world-k8s",
        "version": "v1"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

```

**Comment by satishsudini** [comment]
cluster installation is successful only extension is failing with the below error . same template its working with aks binary 0.32 

{
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter publisher is invalid.",
    "target": "publisher"
  }
}

**Comment by CecileRobertMichon** [comment]
Can you check in the portal what the `publisher` parameter value is? Sounds like this error is extension specific.

**Comment by satishsudini** [comment]
@CecileRobertMichon  : This is ouput for working and not working 

Additional context
output generated with aks binary v0.40 (which is having issue)
"dependsOn": [
"[concat('Microsoft.Compute/virtualMachines/', variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/extensions/cse', '-master-', copyIndex(variables('masterOffset')))]"
],
"location": "[resourceGroup().location]",
"name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/testcse', '-', 'master', '-', copyIndex(variables('masterOffset')))]",
"properties": {},
"type": "Microsoft.Compute/virtualMachines/extensions"
},

output generated with aks binary v0.31.3 (which is working fine)
"dependsOn": [
"[concat('Microsoft.Compute/virtualMachines/', variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/extensions/cse', '-master-', copyIndex(variables('masterOffset')))]"
],
"location": "[resourceGroup().location]",
"name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/testcse', '-', 'master', '-', copyIndex(variables('masterOffset')))]",
"properties": {
"autoUpgradeMinorVersion": true,
"protectedSettings": {
"storageAccountKey": "",
"storageAccountName": ""
},
"publisher": "Microsoft.OSTCExtensions",
"settings": {
"commandToExecute": "[concat('/bin/bash -c "/bin/bash ./bootstrap.sh ', parameters('bootstrapParameters'), ' >> /var/log/azure/bootstrap.log 2>&1 &" &')]",
"fileUris": [
"",
"",
"",
""
]
},
"type": "CustomScriptForLinux",
"typeHandlerVersion": "1.5"
},
"type": "Microsoft.Compute/virtualMachines/extensions"
},

**Comment by satishsudini** [comment]
@jackfrancis @CecileRobertMichon  In which version can expect fix for this issue ?
