### ISSUE TITLE
Unable to deploy a 1.15 cluster

### ISSUE THREAD

**Issue by zachomedia** [Azure/aks-engine#1753]
**Describe the bug**

Due to multiple issues, we're currently unable to successfully deploy a 1.15 Kubernetes cluster.

1. Generating the cluster with distro "aks-ubuntu-1804" references "aks-ubuntu-1804-201907:2019.07.25". Wet got an error "The subscription is not authorized". After a bunch of searching, we discovered that the image no longer exists? `az vm image list --publisher microsoft-aks --all -o table` doesn't list it
2. Switching to the latest 1804 image available (aks-ubuntu-1809-201906:2019.06.20) failed the deployment due to CSE Exit 99 (apt-get update timeout). The apt repositories fail to update because the clear container runtime repo has an expired GPG key

So at that point we decided to go back to 1604 and see if we can get a cluster deployed. That failed for it's own reason:

3. Kubelet is unable to start the containers on the master (api server, controller manager, etc.) because the ` /run/systemd/resolve/resolv.conf` isn't found. On 1604, `systemd-resolved` is disabled by default but kubelet has it in the it's `--resolve-conf` setting.

**Steps To Reproduce**

1. Install aks-engine (we used `0.38.6`)
2. Attempt to deploy a 1.15 cluster using aks-ubuntu-1804 as the distro for master and Linux pool (or aks-ubuntu-1604)

**Expected behavior**

The cluster deploys.

**AKS Engine version**

0.38.6

**Kubernetes version**

1.15

**Additional context**

**Comment by zachomedia** [comment]
Also: will this affect previously deployed clusters that use scale sets if we attempt to scale them up?

**Comment by CecileRobertMichon** [comment]
@zachomedia we are aware of this issue and are investigating. Those images are missing from the marketplace and were not intentionally removed.

**Comment by zachomedia** [comment]
Great, thanks!

**Comment by jackfrancis** [comment]
This should be resolved by EOD. If you need a cluster right now, you could add `"distro": "ubuntu-18.04"` to your apimodel.json input in both your `masterProfile` and for every pool in the `agentPoolProfiles` array and you should have a working cluster.

**Comment by jackfrancis** [comment]
Missing images should be restored.

**Comment by zachomedia** [comment]
Thanks @jackfrancis! Confirmed that the image are back and functional now.

**Comment by jackfrancis** [comment]
yay
