### ISSUE TITLE
[Question] Enabling RBAC on existing AKS0Engine cluster recommendation

### ISSUE THREAD

**Issue by AhmedMoAli** [Azure/aks-engine#1759]
**Enabling RBAC on existing AKS-Engine cluster recommendation**

**Steps To Reproduce**
Currently we have AKS-Engine clusters provisioned without RBAC in place (RBAC set to false), what we want is to enable the RBAC without the need of re-provisioning customers' clusters.

Currently we configuring the RBAC in a manual way through script that we apply to our existing clusters which does the follow:
1. Deploy a daemonset to the cluster which will only be scheduled on ‘Master’ nodes
2. Try to modify the API-SERVER yaml file located in “/etc/kubernetes/manifests/kube-apiserver.yaml”
3. Add extra argument to the command by modifying “args” and appending  "--authorization-mode=Node,RBAC”
4. The changes will be picked up and the API-Server pod will restart and pick up the changes.
  
5. We are currently not integrating with AAD we want to enable RBAC and we have k8s service accounts which will be controlled through RBAC.

It seems it is working fine but we are not sure if this is recommended approach from MS side for existing clusters or no, maybe we are missing some other configurations to have a correctly configured cluster?.

 
**Expected behavior**
RBAC is enabled without any issues

**AKS Engine version**
0.35.1

**Kubernetes version**
1.12.10

**Comment by AhmedMoAli** [comment]
Hello, is that a valid approach to follow for now from your side?

**Comment by hfuss** [comment]
For anyone who comes across this, you can update the `properties.orchestratorProfile.kubernetesConfig.enableRbac` in your clusters' `apimodel.json` file and then "apply" that using `aks-engine upgrade`. I haven't tried only enabling RBAC w/o also doing a minor version upgrade though fwiw.
