### ISSUE TITLE
Allow node selectivity when scaling down or provide replace command

### ISSUE THREAD

**Issue by rocketraman** [Azure/aks-engine#176]
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of acs-engine?**: 0.11.0 (but same thing on 0.12.x AFAIK)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes 1.7.5+

---

ACS Engine provides a `scale` command now, which is great. However, the documentation states "Nodes will always be added or removed from the end of the agent pool."

When scaling down, this is not ideal for every use case. If the use case is simply capacity, then it is fine. However, following the "cattle, not pets" concept i.e. a bad node doesn't deserve attention, it just needs to be shot and replaced, it should be possible to select specific nodes when scaling down.

One example right now with my cluster is that I have Ubuntu nodes that are using the "generic" kernel. I want to update all of these nodes to use the "azure" kernel announced a month or two ago. However, this is impossible since the *earlier* nodes are `generic` and the later nodes are `azure`.

Another example is that I have 2 nodes that are regularly having an issue with omiagent taking 100% CPU. I'd like to remove these specific nodes from my cluster. This is also not possible since these are nodes 2 and 3.

One potentially simple implementation that wouldn't be ideal but could address a few use cases is to scale up by adding nodes to the end of the cluster, but scale down by removing nodes from the beginning. At least this way, one can replace any particular node simply by scaling.

Another possible implementation might be to allow the user to pass the nodes they wish to decommission on the command line, or by adding a specific tag to the relevant VMs.

A third possible implementation, which would actually probably address my use cases even better, is to provide a `replace` command. Instead of `scale`, this command would destroy a particular node, and replace it with a new one. This would also have the nice side-effect of keeping the node numbering contiguous.

A last possible implementation is to inspect what is running on each node -- if there are no pods (other than DaemonSet pods) and the node is cordoned, then that node should be a candidate for scaling down before other nodes.

cc: @itowlson

**Comment by ai2admin** [comment]
Hi, it there progress on this? Currently, if my node 0 reports its status as NotReady (for some reason), I'm stuck with having to recover it. Instead, I want to be able to replace it with another node.

**Comment by rocketraman** [comment]
Adding a comment to avoid "stale". This is an important issue, please review.

**Comment by rocketraman** [comment]
Not stale, just ignored :-(

**Comment by mboersma** [comment]
It is possible to achieve scale down of a specific node or nodes with some manual work. Let's document that for VMAS and VMSS as a workaround.
