### ISSUE TITLE
Update azure-sdk-for-go to v29.0.0+

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1777]
AKS would like the fix here so that it can stop using the boolean `AccountEnabled` property as a string pointer:

https://github.com/Azure/azure-sdk-for-go/commit/f354e2e940568f158a54d84be05e8b65bd2206e2

**Comment by devigned** [comment]
@jhendrixMSFT is going to be cutting a new version of go-autorest without direct opencensus export agent dependencies soon. It might be good to wait for that PR to merge, then update the dep.
