### ISSUE TITLE
Error Deploying MSI Cluster

### ISSUE THREAD

**Issue by DavidLangworthy** [Azure/aks-engine#1780]
Deployment fails with the following error.  However, i can kubectl into the cluster.  Api model and logs are below.  the Api model is straight from the examples directory and the logs look clean.  

PS C:\repos\kube\aks-engine\managed-identity> aks-engine deploy --subscription-id 7421b5fd-cf60-4260-b2a2-dbb76e98458b --resource-group mis-1 --location eastus --api-model mis.json --dns-prefix mis-1  -f --debug --client-id $appId --client-secret $password
DEBU[0000] Resolving tenantID for subscriptionID: 7421b5fd-cf60-4260-b2a2-dbb76e98458b
DEBU[0002] Already registered for "Microsoft.Compute"
DEBU[0002] Already registered for "Microsoft.Storage"
DEBU[0002] Already registered for "Microsoft.Network"
WARN[0002] apimodel: missing masterProfile.dnsPrefix will use "mis-1"
DEBU[0005] output: wrote _output/mis-1/azureuser_rsa
DEBU[0013] pki: PKI asset creation took 1.9217526s
DEBU[0013] output: wrote _output/mis-1/apimodel.json
DEBU[0013] output: wrote _output/mis-1/azuredeploy.json
DEBU[0013] output: wrote _output/mis-1/azuredeploy.parameters.json
DEBU[0013] output: wrote _output/mis-1/kubeconfig/kubeconfig.eastus.json
DEBU[0013] output: wrote _output/mis-1/ca.key
DEBU[0013] output: wrote _output/mis-1/ca.crt
DEBU[0013] output: wrote _output/mis-1/apiserver.key
DEBU[0013] output: wrote _output/mis-1/apiserver.crt
DEBU[0013] output: wrote _output/mis-1/client.key
DEBU[0013] output: wrote _output/mis-1/client.crt
DEBU[0013] output: wrote _output/mis-1/kubectlClient.key
DEBU[0013] output: wrote _output/mis-1/kubectlClient.crt
DEBU[0013] output: wrote _output/mis-1/etcdserver.key
DEBU[0013] output: wrote _output/mis-1/etcdserver.crt
DEBU[0013] output: wrote _output/mis-1/etcdclient.key
DEBU[0013] output: wrote _output/mis-1/etcdclient.crt
DEBU[0013] output: wrote _output/mis-1/etcdpeer0.key
DEBU[0013] output: wrote _output/mis-1/etcdpeer0.crt
INFO[0013] Starting ARM Deployment (mis-1-1051675944). This will take some time...
INFO[0277] Finished ARM Deployment (mis-1-1051675944). Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PrincipalNotFound\",\r\n    \"message\": \"Principal c9e1d0a8795e463593f93346a1038c3d does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PrincipalNotFound\",\r\n    \"message\": \"Principal df5907d01b194f688d690e50c74aa7c9 does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PrincipalNotFound\",\r\n    \"message\": \"Principal d1a9f3d606af42d6a3d417c900786304 does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\"\r\n  }\r\n}"}]
Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PrincipalNotFound\",\r\n    \"message\": \"Principal c9e1d0a8795e463593f93346a1038c3d does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PrincipalNotFound\",\r\n    \"message\": \"Principal df5907d01b194f688d690e50c74aa7c9 does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PrincipalNotFound\",\r\n    \"message\": \"Principal d1a9f3d606af42d6a3d417c900786304 does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\"\r\n  }\r\n}"}]

API Model
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.15",
        "kubernetesConfig": {
          "useManagedIdentity": true
        }
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "",
        "vmSize": "Standard_D2_v3"
      },
      "agentPoolProfiles": [
        {
          "name": "linuxpool1",
          "count": 2,
          "vmSize": "Standard_D2_v3",
          "availabilityProfile": "AvailabilitySet"
        }
      ],
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": ""
            }
          ]
        }
      }
    }
  }
Logs look clean
PS C:\repos\kube\aks-engine\managed-identity> az vm run-command invoke -n k8s-master-24803758-0 --command-id RunShellScript --scripts 'cat /var/log/cloud-init-output.log'
{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\n amd64 1:2.0.21-1 [45.5 kB]\nFetched 45.5 kB in 0s (1,659 kB/s)\nSelecting previously unselected package traceroute.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 82273 files and directories currently installed.)\r\nPreparing to unpack .../traceroute_1%3a2.0.21-1_amd64.deb ...\r\nUnpacking traceroute (1:2.0.21-1) ...\r\nProcessing triggers for man-db (2.7.5-1) ...\r\nSetting up traceroute (1:2.0.21-1) ...\r\nupdate-alternatives: using /usr/bin/traceroute.db to provide /usr/bin/traceroute (traceroute) in auto mode\r\nupdate-alternatives: using /usr/bin/lft.db to provide /usr/bin/lft (lft) in auto mode\r\nupdate-alternatives: using /usr/bin/traceproto.db to provide /usr/bin/traceproto (traceproto) in auto mode\r\nupdate-alternatives: using /usr/sbin/tcptraceroute.db to provide /usr/sbin/tcptraceroute (tcptraceroute) in auto mode\r\n+ . /opt/azure/containers/provision_source.sh\n+ ERR_SYSTEMCTL_START_FAIL=4\n+ ERR_CLOUD_INIT_TIMEOUT=5\n+ ERR_FILE_WATCH_TIMEOUT=6\n+ ERR_HOLD_WALINUXAGENT=7\n+ ERR_RELEASE_HOLD_WALINUXAGENT=8\n+ ERR_APT_INSTALL_TIMEOUT=9\n+ ERR_ETCD_DATA_DIR_NOT_FOUND=10\n+ ERR_ETCD_RUNNING_TIMEOUT=11\n+ ERR_ETCD_DOWNLOAD_TIMEOUT=12\n+ ERR_ETCD_VOL_MOUNT_FAIL=13\n+ ERR_ETCD_START_TIMEOUT=14\n+ ERR_ETCD_CONFIG_FAIL=15\n+ ERR_DOCKER_INSTALL_TIMEOUT=20\n+ ERR_DOCKER_DOWNLOAD_TIMEOUT=21\n+ ERR_DOCKER_KEY_DOWNLOAD_TIMEOUT=22\n+ ERR_DOCKER_APT_KEY_TIMEOUT=23\n+ ERR_DOCKER_START_FAIL=24\n+ ERR_MOBY_APT_LIST_TIMEOUT=25\n+ ERR_MS_GPG_KEY_DOWNLOAD_TIMEOUT=26\n+ ERR_MOBY_INSTALL_TIMEOUT=27\n+ ERR_K8S_RUNNING_TIMEOUT=30\n+ ERR_K8S_DOWNLOAD_TIMEOUT=31\n+ ERR_KUBECTL_NOT_FOUND=32\n+ ERR_IMG_DOWNLOAD_TIMEOUT=33\n+ ERR_KUBELET_START_FAIL=34\n+ ERR_CONTAINER_IMG_PULL_TIMEOUT=35\n+ ERR_CNI_DOWNLOAD_TIMEOUT=41\n+ ERR_MS_PROD_DEB_DOWNLOAD_TIMEOUT=42\n+ ERR_MS_PROD_DEB_PKG_ADD_FAIL=43\n+ ERR_SYSTEMD_INSTALL_FAIL=48\n+ ERR_MODPROBE_FAIL=49\n+ ERR_OUTBOUND_CONN_FAIL=50\n+ ERR_KATA_KEY_DOWNLOAD_TIMEOUT=60\n+ ERR_KATA_APT_KEY_TIMEOUT=61\n+ ERR_KATA_INSTALL_TIMEOUT=62\n+ ERR_CONTAINERD_DOWNLOAD_TIMEOUT=70\n+ ERR_CUSTOM_SEARCH_DOMAINS_FAIL=80\n+ ERR_GPU_DRIVERS_START_FAIL=84\n+ ERR_GPU_DRIVERS_INSTALL_TIMEOUT=85\n+ ERR_SGX_DRIVERS_INSTALL_TIMEOUT=90\n+ ERR_SGX_DRIVERS_START_FAIL=91\n+ ERR_APT_DAILY_TIMEOUT=98\n+ ERR_APT_UPDATE_TIMEOUT=99\n+ ERR_CSE_PROVISION_SCRIPT_NOT_READY_TIMEOUT=100\n+ ERR_APT_DIST_UPGRADE_TIMEOUT=101\n+ ERR_SYSCTL_RELOAD=103\n+ ERR_CIS_ASSIGN_ROOT_PW=111\n+ ERR_CIS_ASSIGN_FILE_PERMISSION=112\n+ ERR_CIS_COPY_FILE=113\n+ ERR_CIS_APPLY_PASSWORD_CONFIG=115\n+ gawk match($0, /^(ID_LIKE=(coreos)|ID=(.*))$/, a) { print toupper(a[2] a[3]); exit }\n+ sort -r /etc/lsb-release /etc/os-release\n+ OS=UBUNTU\n+ UBUNTU_OS_NAME=UBUNTU\n+ RHEL_OS_NAME=RHEL\n+ COREOS_OS_NAME=COREOS\n+ KUBECTL=/usr/local/bin/kubectl\n+ DOCKER=/usr/bin/docker\n+ GPU_DV=418.40.04\n+ GPU_DEST=/usr/local/nvidia\n+ NVIDIA_DOCKER_VERSION=2.0.3\n+ DOCKER_VERSION=1.13.1-1\n+ NVIDIA_CONTAINER_RUNTIME_VERSION=2.0.0\n+ aptmarkWALinuxAgent hold\n+ wait_for_apt_locks\n+ fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock\n+ retrycmd_if_failure 120 5 25 apt-mark hold walinuxagent\n+ retries=120\n+ wait_sleep=5\n+ timeout=25\n+ shift\n+ shift\n+ shift\n+ seq 1 120\n+ timeout 25 apt-mark hold walinuxagent\nwalinuxagent was already set on hold.\n+ break\n+ echo Executed \"apt-mark hold walinuxagent\" 1 times\nExecuted \"apt-mark hold walinuxagent\" 1 times\nCloud-init v. 19.1-1-gbaa47854-0ubuntu1~16.04.1 running 'modules:final' at Wed, 14 Aug 2019 22:09:54 +0000. Up 53.36 seconds.\nCloud-init v. 19.1-1-gbaa47854-0ubuntu1~16.04.1 finished at Wed, 14 Aug 2019 22:10:18 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 78.11 seconds\n\n[stderr]\n",
      "time": null
    }
  ]
}
PS C:\repos\kube\aks-engine\managed-identity>
PS C:\repos\kube\aks-engine\managed-identity> az vm run-command invoke -n k8s-master-24803758-0 --command-id RunShellScript --scripts 'cat /var/log/azure/cluster-provision.log'
{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\n357feacd73679ecf13d142bdc04f0c376d7c30\nDeleted: sha256:bf72f7f1f646f0eeda65cbb62f9b7a71a97ca43574c2c420df5456e9e88ff9b1\nDeleted: sha256:262a3c498b0e40df8ead213847146d33bb55889285153e715a2c418addd3d59d\nUntagged: k8s.gcr.io/hyperkube-amd64:v1.13.5\nUntagged: k8s.gcr.io/hyperkube-amd64@sha256:548b8fa78eed795509184885ad6ddc6efc1e8cae3b21729982447ca124dfe364\nDeleted: sha256:7740a148dcf0870f8c72b1fd9c7ec6f41560ef7dddb74269d75486e27b2b9b85\nDeleted: sha256:ad74e567097e54c108762a59796c3291e860ad97244f46f0c26748390723b5a3\nDeleted: sha256:07b16eebd486b6b27f31a8c5a320e66c077a38061e5a8488ca0fb1f8daa81b6a\nDeleted: sha256:8744b03b0ae13719a16a1722c008cafc84c87692ec57c04a414e314ef3cfbbbd\nDeleted: sha256:3772c7f3857782941c48c820957678d216276b2cd88677a7a8cea99ac870d409\nDeleted: sha256:158938159f90e160dc487c87d1c1763cf8249a855ecb8919695a4f2de1f59b64\nDeleted: sha256:ecfafacff829a67d2852dca0cbfd920bc7ea2659f0e171b59acb11e6c5a7d51d\nDeleted: sha256:1102ac8eec366e40d6a89007334a7154417ce2b14faa4c68659a3ce039fb5e6a\nUntagged: k8s.gcr.io/hyperkube-amd64:v1.11.9\nUntagged: k8s.gcr.io/hyperkube-amd64@sha256:f2db543e78a8a1f055d4738916188ed8ea8bb76c0e3d1a02ef189c30afbb1c82\nDeleted: sha256:3530e7eb061d6459c8ece5ba3edc33e452c9a51fba7b40cd47a4300cac5826da\nDeleted: sha256:2a3e9ce3092f236c8c3c5e435eb3c6f5dbd47c36a6c0754835174988ca75f630\nDeleted: sha256:902ddc30d83e18f81ced6d3d8ee7cfdf0ee16be78a075fa620c812544357dd23\nUntagged: k8s.gcr.io/hyperkube-amd64:v1.12.7\nUntagged: k8s.gcr.io/hyperkube-amd64@sha256:db736d836f8d954178d121c00cfcf7c61ef0d433ca865c57ca5ddc905241fb9f\nDeleted: sha256:417c9a1be9d5943b76e439b015b23c9ed5db1bda6684dfd4941cc94d4268e010\nDeleted: sha256:7ca13df6ef13df8fe03d827fa23f773b170d7b8ec0061d51a3f8d768afa7248b\nDeleted: sha256:1f44d96f7df7804ba535dc589a3578c3800d7cd97cec586ccc46f463f2485e4f\nUntagged: k8s.gcr.io/hyperkube-amd64:v1.10.13\nUntagged: k8s.gcr.io/hyperkube-amd64@sha256:b835a26ac4bdf6033cd141bbe2b22b040ae1fbd873165fb4194971e3aefafec0\nDeleted: sha256:92e8364db5b0e33461a1bf4821c916de0438b37a7c710804e61dd639ee503105\nDeleted: sha256:ff64f0875715074ee915ce8075dc6e5352fef5b8146a046062657db0044de981\nDeleted: sha256:b0aaad943e5c4f263caf69518393fe424cbba0ff61a28f579c10c7987bc45849\n+ fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock\n+ echo 'Waiting for release of apt locks'\nWaiting for release of apt locks\n+ sleep 3\nUntagged: k8s.gcr.io/hyperkube-amd64:v1.10.12\nUntagged: k8s.gcr.io/hyperkube-amd64@sha256:946e421d443bd9417df02da7c68c70a5a3c6effd86ff0e9993eecd53fc13d1f4\nDeleted: sha256:99a8eada1f9cafc2334385fc6178fccaabfa096e254752dd43a64653e882abc2\nDeleted: sha256:f4b6fcdf27e3dbbcf657146b5a8cc0ac0770d1df549ffc0081eb735fcc5bf6d3\nDeleted: sha256:a4f56f658452f0cf68688a2e774a23b14a85c2046e67d4fb74ecaf5dd99ba016\nDeleted: sha256:7bccead2e89c2e22e4069b4de6143c75d4211abd6c99aff562745327daaa2b68\nDeleted: sha256:223165ef645b8f698fd045c4680046b38e02022dde34cf3fe53b9dd87d8e1a0e\nDeleted: sha256:373025e3a7d9f2465dd96094d77d5ee3fbbad2f83414fa4e4c0379f65b6c8870\nDeleted: sha256:47a633707bc5ef6708bc872a783906f695a90241871fcf445a367e5b02c3c41a\nDeleted: sha256:f35f2ebb6be076bc21d225ad99c4710e187934ef6e49e1f2f0f5f94248986648\n+ fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock\n+ echo 'Waiting for release of apt locks'\nWaiting for release of apt locks\n+ sleep 3\n+ fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock\n+ echo 'Waiting for release of apt locks'\nWaiting for release of apt locks\n+ sleep 3\n+ fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock\n+ echo 'Waiting for release of apt locks'\nWaiting for release of apt locks\n+ sleep 3\n+ fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock\n+ retrycmd_if_failure 120 5 25 apt-mark unhold walinuxagent\n+ retries=120\n+ wait_sleep=5\n+ timeout=25\n+ shift\n+ shift\n+ shift\n++ seq 1 120\n+ for i in '$(seq 1 $retries)'\n+ timeout 25 apt-mark unhold walinuxagent\nCanceled hold on walinuxagent.\n+ break\n+ echo Executed '\"apt-mark' unhold 'walinuxagent\"' 1 times\nExecuted \"apt-mark unhold walinuxagent\" 1 times\n\n[stderr]\n",
      "time": null
    }
  ]
}

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by jackfrancis** [comment]
Are you sure that the passed in service principal is a part of the tenant?

**Comment by DavidLangworthy** [comment]
What do you mean "part of the tenant"?  The service principle I call aks-engine deploy with has sufficient permissions to create the cluster.  I can see the resources in the Azure portal and can even kubectl into the cluster.  However the deployment throws these errors and I do not see the MSIs.
