### ISSUE TITLE
Support cilium network plugin v1.5.5

### ISSUE THREAD

**Issue by pengzhisun** [Azure/aks-engine#1782]
**Describe the request**

Support cilium network plugin v1.5.5

**Explain why AKS Engine needs it**

There is a new network encryption beta feature in cilium v1.5.5 (https://cilium.readthedocs.io/en/stable/gettingstarted/encryption/ ), we want to test it in Azure environment.

**Describe the solution you'd like**

To specify which version of network plugin to be deployed in cluster definition file.

**Describe alternatives you've considered**

To manually upgrade cilium version in master node after aks-engine deployed, but haven't test yet.

**Additional context**
Network encryption feature is a must to have requirements in our project, we need to resolve it in either network plugin or leverage service mesh solution like istio or linkerd 2.

**Comment by jackfrancis** [comment]
@skinny is this as simple as `s/docker.io/cilium/cilium:v1.4/docker.io/cilium/cilium:v1.5.5` and `s/docker.io/cilium/operator:v1.4/docker.io/cilium/operator:v1.5.5` against the current spec:

https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml

?

(More likely is that we'll have to tweak that spec as a minor version bump likely includes some changes that will want to be reflected in the Kubernetes spec.)

**Comment by pengzhisun** [comment]
@jackfrancis is it possible to provide a network plugin version parameter in cluster definition file, instead of hard coding the version in addon yaml file?

**Comment by yixwang** [comment]
is there any work that's currently being worked on for this one? we are also in need of this feature. Thanks.
