### ISSUE TITLE
Upgrade with multiple nodepools is not detecting not upgraded nodes

### ISSUE THREAD

**Issue by mtgerb** [Azure/aks-engine#1794]
**Describe the bug**

**Steps To Reproduce**

1. Create a cluster with two nodepools and version 1.13.8
2. Upgrade to version 1.13.9 and stop the upgrade process after all nodes of the first nodepool have been upgraded (with control-c)
3. Run the upgrade command again

All nodes of first nodepool are correctly detected as already upgraded, but all nodes of the second nodepool are not upgraded. Instead of upgrading the nodes of the second nodepool, aks-engine erroneously detects that the whole cluster has already been upgraded and does nothing.

**Expected behavior**

All nodes of the second nodepool are getting upgraded upon the second run of the upgrade command

**AKS Engine version**

Version: v0.39.1
GitCommit: 6fff62731
GitTreeState: clean

**Kubernetes version**

1.13.8

**Additional context**

Using Linux nodes only (in both nodepools)

**Comment by vmrm** [comment]
**Steps To Reproduce**

Upgrade a cluster with three nodepools and version 1.11.9
Upgrade to version 1.12.8 was stopped during upgrade with errors from Azure API (about concurrent operations and etc, pretty usual, not a problem with aks-engine)
Run the upgrade command again: 
`Error: loading existing cluster: error validating the api model: Invalid upgrade target version. Consider using --force if you really want to proceed: upgrading from Kubernetes version 1.12.8 to version 1.12.8 is not supported. To see a list of available upgrades, use 'aks-engine get-versions --version 1.12.8'
Usage:
  aks-engine upgrade [flags]`

Fixed apimodel.json manually to restart upgrade process and got output, posted below.
Absolutely the same with v0.39.2

**AKS Engine version**

Version: v0.40.0
GitCommit: e52789fae
GitTreeState: clean

**Kubernetes version**

between 1.11.9 to 1.12.8

`INFO[0003] Upgrading cluster with name suffix: 15353000
INFO[0004] Skipping VM: iota for upgrade as it does not belong to cluster with expected name suffix: 15353000
INFO[0004] Master VM name: k8s-master-15353000-0, orchestrator: 1.12.8 (UpgradedMasterVMs)
INFO[0004] Evaluating VM: k8s-node-15353000-0 in pool: node...
INFO[0004] Adding Agent VM: k8s-node-15353000-0, orchestrator: Kubernetes:1.12.8 to pool: node (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-node-15353000-2 in pool: node...
INFO[0004] Adding Agent VM: k8s-node-15353000-2, orchestrator: Kubernetes:1.12.8 to pool: node (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-node-15353000-3 in pool: node...
INFO[0004] Adding Agent VM: k8s-node-15353000-3, orchestrator: Kubernetes:1.12.8 to pool: node (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-node-15353000-4 in pool: node...
INFO[0004] Adding Agent VM: k8s-node-15353000-4, orchestrator: Kubernetes:1.12.8 to pool: node (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-node-15353000-5 in pool: node...
INFO[0004] Adding Agent VM: k8s-node-15353000-5, orchestrator: Kubernetes:1.12.8 to pool: node (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-node-15353000-6 in pool: node...
INFO[0004] Adding Agent VM: k8s-node-15353000-6, orchestrator: Kubernetes:1.12.8 to pool: node (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-stress-15353000-0 in pool: stress...
INFO[0004] Adding Agent VM: k8s-stress-15353000-0, orchestrator: Kubernetes:1.11.9 to pool: stress (AgentVMs)
INFO[0004] Evaluating VM: k8s-stress-15353000-1 in pool: stress...
INFO[0004] Adding Agent VM: k8s-stress-15353000-1, orchestrator: Kubernetes:1.11.9 to pool: stress (AgentVMs)
INFO[0004] Evaluating VM: k8s-stress-15353000-2 in pool: stress...
INFO[0004] Adding Agent VM: k8s-stress-15353000-2, orchestrator: Kubernetes:1.12.8 to pool: stress (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-stress-15353000-3 in pool: stress...
INFO[0004] Adding Agent VM: k8s-stress-15353000-3, orchestrator: Kubernetes:1.12.8 to pool: stress (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-stress-15353000-4 in pool: stress...
INFO[0004] Adding Agent VM: k8s-stress-15353000-4, orchestrator: Kubernetes:1.12.8 to pool: stress (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-system-15353000-0 in pool: system...
INFO[0004] Adding Agent VM: k8s-system-15353000-0, orchestrator: Kubernetes:1.11.9 to pool: system (AgentVMs)
INFO[0004] Evaluating VM: k8s-system-15353000-1 in pool: system...
INFO[0004] Adding Agent VM: k8s-system-15353000-1, orchestrator: Kubernetes:1.11.9 to pool: system (AgentVMs)
INFO[0004] Evaluating VM: k8s-system-15353000-2 in pool: system...
INFO[0004] Adding Agent VM: k8s-system-15353000-2, orchestrator: Kubernetes:1.12.8 to pool: system (UpgradedAgentVMs)
INFO[0004] Evaluating VM: k8s-system-15353000-3 in pool: system...
INFO[0004] Adding Agent VM: k8s-system-15353000-3, orchestrator: Kubernetes:1.12.8 to pool: system (UpgradedAgentVMs)
INFO[0004] Upgrading to Kubernetes version 1.12.8
INFO[0004] Master nodes StorageProfile: ManagedDisks
WARN[0004] etcd will be upgraded to version 3.3.13
INFO[0004] Prepping master nodes for upgrade...
INFO[0004] Resource count before running NormalizeResourcesForK8sMasterUpgrade: 24
INFO[0004] Removing nic: [concat(variables('nodeVMNamePrefix'), 'nic-', copyIndex(variables('nodeOffset')))] from template
INFO[0004] Evaluating if agent pool: node, resource: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing agent pool: node, resource: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')),'/cse', '-agent-', copyIndex(variables('nodeOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing extension: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')),'/cse', '-agent-', copyIndex(variables('nodeOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')), '/computeAksLinuxBilling')] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing extension: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')), '/computeAksLinuxBilling')] from template
INFO[0004] Removing nic: [concat(variables('systemVMNamePrefix'), 'nic-', copyIndex(variables('systemOffset')))] from template
INFO[0004] Evaluating if agent pool: system, resource: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing agent pool: system, resource: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')),'/cse', '-agent-', copyIndex(variables('systemOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing extension: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')),'/cse', '-agent-', copyIndex(variables('systemOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')), '/computeAksLinuxBilling')] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing extension: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')), '/computeAksLinuxBilling')] from template
INFO[0004] Removing nic: [concat(variables('stressVMNamePrefix'), 'nic-', copyIndex(variables('stressOffset')))] from template
INFO[0004] Evaluating if agent pool: stress, resource: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing agent pool: stress, resource: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')),'/cse', '-agent-', copyIndex(variables('stressOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing extension: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')),'/cse', '-agent-', copyIndex(variables('stressOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')), '/computeAksLinuxBilling')] needs to be removed
INFO[0004] agentPoolsToPreserve: map[]...
INFO[0004] Removing extension: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')), '/computeAksLinuxBilling')] from template
INFO[0004] Evaluating if agent pool: master, resource: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))] needs to be removed
INFO[0004] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', '-master-', copyIndex(variables('masterOffset')))] needs to be removed
INFO[0004] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/computeAksLinuxBilling')] needs to be removed
INFO[0004] Resource count after running NormalizeResourcesForK8sMasterUpgrade: 12
INFO[0004] Total expected master count: 1
INFO[0004] Master nodes that need to be upgraded: 0
INFO[0004] Master nodes that have been upgraded: 1
INFO[0004] Starting upgrade of master nodes...
INFO[0004] masterNodesInCluster: 1
INFO[0004] Master VM: k8s-master-15353000-0 is upgraded to expected orchestrator version
INFO[0004] Expected master count: 1, Creating 0 more master VMs
INFO[0004] Completed upgrading all VMSS
INFO[0004] Prepping agent pool 'node' for upgrade...
INFO[0004] Running NormalizeResourcesForK8sMasterUpgrade....
INFO[0004] Resource count before running NormalizeResourcesForK8sMasterUpgrade: 24
INFO[0004] Evaluating if agent pool: node, resource: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Evaluating if extension: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')),'/cse', '-agent-', copyIndex(variables('nodeOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Evaluating if extension: [concat(variables('nodeVMNamePrefix'), copyIndex(variables('nodeOffset')), '/computeAksLinuxBilling')] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Evaluating if agent pool: system, resource: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Removing agent pool: system, resource: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')),'/cse', '-agent-', copyIndex(variables('systemOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Removing extension: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')),'/cse', '-agent-', copyIndex(variables('systemOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')), '/computeAksLinuxBilling')] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Removing extension: [concat(variables('systemVMNamePrefix'), copyIndex(variables('systemOffset')), '/computeAksLinuxBilling')] from template
INFO[0004] Evaluating if agent pool: stress, resource: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Removing agent pool: stress, resource: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')),'/cse', '-agent-', copyIndex(variables('stressOffset')))] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Removing extension: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')),'/cse', '-agent-', copyIndex(variables('stressOffset')))] from template
INFO[0004] Evaluating if extension: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')), '/computeAksLinuxBilling')] needs to be removed
INFO[0004] agentPoolsToPreserve: map[node:true]...
INFO[0004] Removing extension: [concat(variables('stressVMNamePrefix'), copyIndex(variables('stressOffset')), '/computeAksLinuxBilling')] from template
INFO[0004] Evaluating if agent pool: master, resource: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))] needs to be removed
INFO[0004] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', '-master-', copyIndex(variables('masterOffset')))] needs to be removed
INFO[0004] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/computeAksLinuxBilling')] needs to be removed
INFO[0004] Resource count after running NormalizeResourcesForK8sMasterUpgrade: 18
INFO[0004] Running NormalizeForK8sVMASScalingUp....
INFO[0004] Agent VM: k8s-node-15353000-0, pool name: node on expected orchestrator version
INFO[0004] Agent VM: k8s-node-15353000-2, pool name: node on expected orchestrator version
INFO[0004] Agent VM: k8s-node-15353000-3, pool name: node on expected orchestrator version
INFO[0004] Agent VM: k8s-node-15353000-4, pool name: node on expected orchestrator version
INFO[0004] Agent VM: k8s-node-15353000-5, pool name: node on expected orchestrator version
INFO[0004] Agent VM: k8s-node-15353000-6, pool name: node on expected orchestrator version
INFO[0004] Starting upgrade of 0 agent nodes (out of 6) in pool identifier: node, name: node...
INFO[0004] No nodes to upgrade
INFO[0004] Cluster upgraded successfully to Kubernetes version 1.12.8`

**Comment by mtgerb** [comment]
The problem is here:
`
		if toBeUpgradedCount == 0 {
			ku.logger.Infof("No nodes to upgrade")
			return nil
}
`
It should not return nil, but continue as it is in the loop over all agentpools
