### ISSUE TITLE
Aks engine vmss auto os upgrade failed

### ISSUE THREAD

**Issue by Banani-Rath** [Azure/aks-engine#1795]
**Describe the bug**

Update-AzureRmVmss : Automatic OS Upgrade cannot be enabled on virtualMachineScaleSets configured with a Platform Image.
ErrorCode: BadRequest
ErrorMessage: Automatic OS Upgrade cannot be enabled on virtualMachineScaleSets configured with a Platform Image.
ErrorTarget: 
StatusCode: 400
ReasonPhrase: Bad Request

**Through Azure cli:**

windowsConfiguration.enableAutomaticUpdates cannot be set to true if upgradePolicy.automaticOSUpgradePolicy.enableAutomaticOSUpgrade is already true, starting from APIversion 2019-03-01

**Steps To Reproduce**

**Expected behavior** Should upgrade

**AKS Engine version**v0.31.1

**Kubernetes version**Kubernetes:1.13.3

**Additional context**

**Comment by CecileRobertMichon** [comment]
is this on a Windows or Linux node? what OS image is it currently using?

**Comment by Banani-Rath** [comment]
Its windows VMSS: Windows

{
  "name": "1916k8s00",
  "id": "/subscriptions/fef9897e-e4c6-451a-9e2e-850f9876fdc7/resourceGroups/ops-build-service-k8s-prod/providers/Microsoft.Compute/virtualMachineScaleSets/1916k8s00",
  "type": "Microsoft.Compute/virtualMachineScaleSets",
  "location": "westus",
  "tags": {
    "aksEngineVersion": "v0.31.1",
    "creationSource": "aksengine-1916k8s00",
    "orchestrator": "Kubernetes:1.13.3",
    "poolName": "windowspool2",
    "resourceNameSuffix": "19160"
  },
  "identity": {
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "/subscriptions/fef9897e-e4c6-451a-9e2e-850f9876fdc7/resourceGroups/ops-build-service-k8s-prod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/user-ops-build-service-k8s-prod": {
        "principalId": "8a145dc6-7ecd-4878-91bd-573b8b0cc6e3",
        "clientId": "97f8fd39-eb2c-43de-9d90-1da4467a1c22"
      }
    }
  },
