### ISSUE TITLE
Unable to upgrade a cluster with two nodepools

### ISSUE THREAD

**Issue by mtgerb** [Azure/aks-engine#1799]
**Describe the bug**

**Steps To Reproduce**

1. Create a cluster with two nodepools (both VMAS) and version 1.13.8
2. Run aks-engine upgrade to version 1.13.9

Actual behavior: The first nodepool is upgraded succesful. The upgrade of the second nodepool fails, because of the following message (I removed the UUIDs from the message):
``
 "status": "Canceled", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Canceled'.", "details": [ { "code": "Canceled", "message": "Operation was canceled.", "details": [ { "code": "CanceledAndSupersededDueToAnotherOperation", "message": "Operation PutNicOperation was canceled and superseded by operation InternalOperation." } ] } ] } }
``
It seems like upon upgrade of the second nodepool the arm template which aks-engine generates contains the NIC of all nodes of the first nodepool.

**Expected behavior**

aks-engine upgrades the second nodepool

**AKS Engine version**

Version: v0.39.1
GitCommit: 6fff627
GitTreeState: clean

**Kubernetes version**

1.13.8

**Additional context**

Using Linux nodes only (in both nodepools)

**Comment by satishsudini** [comment]
You can still update your apimodel.json in the output folder and try aks-engine scale

**Comment by mtgerb** [comment]
> 
> 
> You can still update your apimodel.json in the output folder and try aks-engine scale

No this will not work, because you can not scale down to zero nodes. Therefore one old node will always stay.

**Comment by vmrm** [comment]
https://github.com/Azure/aks-engine/issues/1794
