### ISSUE TITLE
High number of restarts for pods running on Windows agent nodes

### ISSUE THREAD

**Issue by david-jarman** [Azure/aks-engine#1815]
**Describe the bug**
Pods running on Windows agent nodes are being restarted frequently due to liveness and readiness probes not responding. 

**Steps To Reproduce**
Create a kubernetes cluster in Azure with a Windows agent node pool with below context (same windows os version, kubernetes version, etc...)
Create a deployment with the [virtual service that I created](https://github.com/david-jarman/virtual-service) (deployment.yaml, pre-built docker image included)

Wait ~2-6 hours

Pods are restarted with events on the pod indicating that liveness and readiness probes fail. Sample: ```Warning  Unhealthy  63m (x42 over 3d)     kubelet, 1144k8s004  Liveness probe failed: Get http://10.240.0.112:80/api/health/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)```

**Expected behavior**
Pods run without being restarted

**AKS Engine version**
0.38.5

**Kubernetes version**
1.15.1

**Additional context**
Windows OS-Image: Windows Server 2019 Datacenter
Windows OS-Version: 10.0.17763.678 (version after installing OS updates on all nodes after initial creation)
azure-vnet version: v1.0.25 (was originally on v1.0.22, observed issues, upgraded nodes to use v1.0.25 to try to fix it, still observe pod restart behavior)

**Comment by zhiweiv** [comment]
It is a Windows bug, https://github.com/Azure/AKS/issues/1014#issuecomment-522701063.

**Comment by david-jarman** [comment]
Thanks for the link! Says a patch is out for it as of a couple of days ago. I'll try updating my nodes and update with result tomorrow.

**Comment by david-jarman** [comment]
Pods have been up for 15 hours now with no restarts. Thanks again @zhiweiv!
