### ISSUE TITLE
kube-proxy still running old version after upgrade

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1817]
#679 appears to be a symptom of the fact that the kube-proxy daemonset is still running the older version after an `aks-engine upgrade` operation.

Investigate whether or not the daemonset spec is configured properly to reconcile via kube-addon-manager.

**Comment by feiskyer** [comment]
@jackfrancis Have we configured "addonmanager.kubernetes.io/mode" to Reconcile for the daemonset?
