### ISSUE TITLE
aks-engine shall not add standard LB with outboud publicIP in AKS scenario

### ISSUE THREAD

**Issue by weinong** [Azure/aks-engine#1834]
**Describe the bug**
in AKS, when `networkprofile.loadbalancerSku: Standard`, it will trip this [code](https://github.com/Azure/aks-engine/blob/6e505a7750a71fc54bfac931f569d38d6fdb4b00/pkg/engine/armresources.go#L39) which undesirably added the SLB.

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by ritazh** [comment]
https://github.com/Azure/aks-engine/blob/6e505a7750a71fc54bfac931f569d38d6fdb4b00/pkg/engine/armresources.go#L37-L39
In the same if statement, if no `LoadBalancerBackendAddressPoolIDs` is provided in any of the agentPoolProfiles in the api model and it's a SLB, then we will hit the logic to create the outbound public ip.  Can you provide the repro steps so I can try to repro this with aks-engine?

**Comment by ritazh** [comment]
Looks like `LoadBalancerBackendAddressPoolIDs` is not provided in this case so we should skip creating SLB when `isHostedMaster`.
