### ISSUE TITLE
Drop requirement for hyperkube

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#1842]
**Describe the request**
Hyperkube is being deprecated & removed in 1.17. This will break AKS-Engine deployments.

References:

- Thread asking for owners, people still using it https://groups.google.com/forum/#!msg/kubernetes-sig-architecture/4uTHr74ucv0/KImea_0RFAAJ
- https://github.com/kubernetes/kubernetes/pull/81268 - removing from GCE setup scripts

**Describe the solution you'd like**

Use the tarballs published in Kubernetes releases and builds from PR tests

**Describe alternatives you've considered**

**Additional context**

**Comment by PatrickLang** [comment]
cc @adelina-t

**Comment by jchauncey** [comment]
can someone explain this to me because im confused

**Comment by jchauncey** [comment]
So one issue says they are moving hyperkube out of tree... But this issue says to move away from using hyperkube... So do we just want to use the individual images that hyperkbue is based on? Are those staying in tree?

**Comment by ritazh** [comment]
This probably needs to happen in 2 stages:
1) we need to build/release our own hyperkube image
2) replace hyperkube with individual binaries

**Comment by jchauncey** [comment]
alright so we are already doing 1. we just need to consume it. granted its coming from the k/k repo so if they yank it out in 1.17 we need to be building from whatever source tree it lands in. I also have the individual binaries for both linux and windows built and in tarball form and in blob storage ready to be consumed. So most of this work will be integration into aks-engine

**Comment by PatrickLang** [comment]
See https://github.com/kubernetes/test-infra/pull/14639/files - workaround for the build script that was deleted in 1.17
