### ISSUE TITLE
runAsNonRoot transient error

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1851]
Our E2E tests occasionally see this error in "verify dashboard pod(s) are in a Ready state" test:

```
vents:
  Type     Reason     Age                  From                                         Message
  ----     ------     ----                 ----                                         -------
  Normal   Scheduled  <unknown>            default-scheduler                            Successfully assigned kube-system/kubernetes-dashboard-5df5c7c989-hcr88 to k8s-linuxpool1-26839328-vmss000000
  Warning  Failed     28m (x12 over 30m)   kubelet, k8s-linuxpool1-26839328-vmss000000  Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     10s (x142 over 30m)  kubelet, k8s-linuxpool1-26839328-vmss000000  Container image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1" already present on machine
```

The pod state in such scenarios is stuck in `Pending`. Why is this error only happening occasionally? One would think that if a container's privilege configuration didn't match the cluster's runtime privilege configuration, the error would be consistent. What is going on here?

**Comment by jackfrancis** [comment]
@feiskyer @andyzhangx have you ever seen this?

**Comment by feiskyer** [comment]
Is this an issue only happening on the latest version, or it also happens on older versions?

**Comment by feiskyer** [comment]
I see we don't set `runAsNonRoot` in pod spec, any possible PodSecurityPolicy is enabled for some test cases?

**Comment by jackfrancis** [comment]
We install a PodSecurityPolicy that delivers this for all >= 1.15 clusters:

https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/kubernetesmasteraddons-pod-security-policy.yaml#L58

Here's the 1.15 spec we use:

https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/1.15/kubernetesmasteraddons-pod-security-policy.yaml

And here's the 1.16 spec we use:

https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/1.16/kubernetesmasteraddons-pod-security-policy.yaml

Those definitely suggest we're enforcing `RunAsNonRoot`, the question is: why are these errors transient? We deliver static (more or less) dashboard, metrics-server specs, and static PodSecurityPolicy specs. Wouldn't we see this fail every time, or succeed every time?

**Comment by jackfrancis** [comment]
observed in metrics-server and rescheduler too, experimenting here: https://github.com/Azure/aks-engine/pull/1856

**Comment by feiskyer** [comment]
possible PodSecurityPolicy is applied after dashboard Pod start or before? do we have any logs to check their sequence?

**Comment by sukhong** [comment]
I am also seeing this issue transiently from kubernetes-dashboard pods.

I am creating new kubernetes clusters in multiple DCs using aks-engine, this issue only happens randomly sometimes.

**Comment by sukhong** [comment]
Name:               kubernetes-dashboard-66dd8b8df7-pmpbq
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               k8s-agentpool-39762526-vmss000001/10.248.0.35
Start Time:         Sun, 25 Aug 2019 22:29:22 -0700
Labels:             k8s-app=kubernetes-dashboard
                    pod-template-hash=66dd8b8df7
Annotations:        container.apparmor.security.beta.kubernetes.io/kubernetes-dashboard: runtime/default
                    kubernetes.io/psp: restricted
                    seccomp.security.alpha.kubernetes.io/pod: docker/default
Status:             Pending
IP:                 10.248.0.39
Controlled By:      ReplicaSet/kubernetes-dashboard-66dd8b8df7
Containers:
  kubernetes-dashboard:
    Container ID:
    Image:         k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
    Image ID:
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --auto-generate-certificates
      --heapster-host=http://heapster.kube-system:80
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     300m
      memory:  150Mi
    Requests:
      cpu:        300m
      memory:     150Mi
    Liveness:     http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-7tskv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kubernetes-dashboard-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kubernetes-dashboard-token-7tskv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-7tskv
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                        Message
  ----     ------     ----                 ----                                        -------
  Normal   Scheduled  30m                  default-scheduler                           Successfully assigned kube-system/kubernetes-dashboard-66dd8b8df7-pmpbq to k8s-agentpool-39762526-vmss000001
  Warning  Failed     28m (x12 over 30m)   kubelet, k8s-agentpool-39762526-vmss000001  Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     42s (x143 over 30m)  kubelet, k8s-agentpool-39762526-vmss000001  Container image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1" already present on machine

**Comment by sukhong** [comment]
The funny thing is, if I manually delete that pod and re-deploy the pod, it runs completely fine...

**Comment by sukhong** [comment]
We are using 1.15.3

**Comment by jackfrancis** [comment]
This is still an issue, remediation is still manual (delete the pod).

**Comment by palmerabollo** [comment]
Just in case it's useful, we have seen it a couple of times in the last few weeks with aks-engine 0.45.0.

**Comment by jackfrancis** [comment]
@palmerabollo Thanks for sharing. We still occasionally observe this in E2E tests as well. Does manually deleting the pods that fail to start fix things for you?
