### ISSUE TITLE
Automate accelerated networking VM sizes whitelist

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#1894]
https://github.com/Azure/aks-engine/blob/master/pkg/helpers/helpers.go#L118

At least Standard_D16_v3 is missing.

**Comment by mboersma** [comment]
Hmm, I see [`Standard_D16_v3`](https://github.com/Azure/aks-engine/blob/master/pkg/helpers/helpers.go#L126) at the end of one line, so it appears it is in the whitelist.

I ran `./pkg/helpers/generate_azure_constants.py` and it added several new VM types, so I'll make a PR for that, but I'm not sure what the root problem is/was here.

**Comment by CecileRobertMichon** [comment]
Ah you're right, I didn't see it there... Not sure why it wouldn't get enabled. Maybe the action item here is to verify that building a cluster with Standard_D16_v3 nodes results in accelerated networking enabled and to audit the rest of the whitelist then.

**Comment by mboersma** [comment]
Sounds like a plan–I can do that.

**Comment by sozercan** [comment]
There is a new API (`2019-04-01`) for this (finally!) to avoid manual whitelist process. I don't believe it's integrated in CLI yet.

`https://management.azure.com/subscriptions/<subId>/Microsoft.Compute/skus?api-version=2019-04-01`

```
...
        {
          "name": "AcceleratedNetworkingEnabled",
          "value": "False"
        },
...
```

**Comment by mboersma** [comment]
Here's an `az` CLI one-liner with [JMESPath](http://jmespath.org/) query that returns the name and capability value of SKUs with the "AcceleratedNetworkingEnabled" property set to something other than `null`:

```shell
$  az vm list-skus -o json \
  --query '[? starts_with(name, `Standard`) && !ends_with(name, `Promo`)].{name: name, caps: capabilities[? name==`AcceleratedNetworkingEnabled`]}[].{sku: name, acceleratedNetworking: caps[0].value}[? acceleratedNetworking != null]'
[
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_B1ls"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_B1ms"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_B1s"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_B2ms"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_B2s"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_B4ms"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_B8ms"
  },
  {
    "acceleratedNetworking": "True",
    "sku": "Standard_B12ms"
  },
  {
    "acceleratedNetworking": "True",
    "sku": "Standard_B16ms"
  },
  {
    "acceleratedNetworking": "True",
    "sku": "Standard_B20ms"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_A0"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_A1"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_A2"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_A3"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_A5"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_A4"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_A6"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_A7"
  },
  {
    "acceleratedNetworking": "False",
    "sku": "Standard_D1_v2"
  },
  {
    "acceleratedNetworking": "True",
    "sku": "Standard_D2_v2"
  },
  {
    "acceleratedNetworking": "True",
    "sku": "Standard_D3_v2"
  },
  {
    "acceleratedNetworking": "True",
    "sku": "Standard_D4_v2"
  },
...
```

**Comment by jackfrancis** [comment]
Referring to #2235 so we can possibly optimize any work on the acclerated networking surface area generally.

**Comment by mboersma** [comment]
#2566 got things up-to-date, but if we want actually to make this automated, there is more work to do.

**Comment by mboersma** [comment]
Currently there isn't a `cron`-type job to run this on a schedule, but you can easily update locations and SKUs with this script:

```shell
$ ./scripts/azure-const.sh
No modifications found! Exiting 0
```

**Comment by jackfrancis** [comment]
Won't do
