### ISSUE TITLE
Automatic OS update for windows nodes

### ISSUE THREAD

**Issue by yixwang** [Azure/aks-engine#1898]
I am wondering what is recommended approach for updating OS for windows nodes. Currently we see there is "enableAutomaticUpdates" attribute for "windowsProfile" and we assume by setting this to true, the windows nodes will have automatic OS updates. 

I saw in the following example cluster definition files, this attribute is set to false.  So we would like to understand the potential risk of enabling the automatic OS udpate on windows node? 

https://github.com/Azure/aks-engine/blob/7726812e60199d68fe1fe1cd76d9705e4ea6bc71/examples/e2e-tests/kubernetes/windows/hybrid/definition.json

https://github.com/Azure/aks-engine/blob/3101db873ee1df5974b591d28995b79b94386393/examples/windows/kubernetes-windows-automatic-update.json

**Comment by yixwang** [comment]
We are currently using aks-engine to deploy the cluster. Essentially what we need is to upgrade the windows nodes. We see that AKS currently has the command to upgrade the node pool. https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#upgrade-a-node-pool
```
az aks nodepool upgrade \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --name mynodepool \
    --kubernetes-version 1.13.10 \
    --no-wait
```
I am wondering what's the process to ugprade the nodepool behind scene. Does it use aks-engine command to do so?

**Comment by brunhil** [comment]
Hi @yixwang , you can see the following documentation around disabling/enabling windows updates located [here](https://github.com/Azure/aks-engine/blob/3101db873ee1df5974b591d28995b79b94386393/docs/topics/windows-and-kubernetes.md#disabling-automatic-updates).

This feature was introduced to address [#402 - Disable automatic windows update](https://github.com/Azure/aks-engine/issues/402).

As you can read on the feature, the reason for disabling windows update would be as follows

> Windows VMs are currently set to auto update. Come patch Tuesday an entire FD/UD/Zone can go down as machines updates themselves. Windows autoupdates should be turned off (or use external tools to manage windows servers).

**Comment by yixwang** [comment]
Hi @brunhil, thanks for your reply. Do you know what does aks use to achieve the windows node OS updates with the `az aks nodepool upgrade` command? Is that something could be supported in aks-engine?
