### ISSUE TITLE
SwitzerlandNorth and SwitzerlandWest missing from constants/TLS generation

### ISSUE THREAD

**Issue by donaldguy** [Azure/aks-engine#1901]
**Describe the bug**

These two Azure regions GAed a week ago https://azure.microsoft.com/en-us/blog/microsoft-azure-available-from-new-cloud-regions-in-switzerland/ but are absent from 

https://github.com/Azure/aks-engine/blob/master/pkg/helpers/azureconst.go#L11-L67 at this time

resulting in TLS errors went attempting validation. 

As the work for #1897 did not pick these up, it may indicate a bug or edge case in your constant generation scripts

**AKS Engine version**
master

**Kubernetes version**
all

**Additional context**

**Comment by CecileRobertMichon** [comment]
`az account list-locations -o table` doesn't show the new regions for me

**Comment by CecileRobertMichon** [comment]
confirmed the Switzerland regions aren't available yet. we will pick up the new regions once they are available.
