### ISSUE TITLE
Custom resource tags are not working for availabilityset

### ISSUE THREAD

**Issue by satishsudini** [Azure/aks-engine#1902]
**Describe the bug**
Custom resource tags are not working for availabilityset. 
When mandatory tags are enforced at subscription level cluster creation failing with the availability set disallowed by policy . Custom tags working fine at vm but not for availability set 

**Steps To Reproduce**

    "masterProfile": {
      "count": 3,
      "dnsPrefix": "testenv",
      "distro": "ubuntu",
      "vmSize": "Standard_*",
      "vnetSubnetId": "",
      "availabilityProfile": "AvailabilitySet",
      "firstConsecutiveStaticIP": "*",
      "OSDiskSizeGB": 128,
      "customVMTags": {
          "key1"        : "value1",
          "key2"        : "value2 ",
          "key3"        : "value3",
          "key4"        : "value4",
          },      
      "extensions": [
        {
          "name": "bootstrap",
          "singleOrAll": "All"
        }
     ]

**Expected behavior**
Tags should enforced for the availability set 

**AKS Engine version**
v0.40

**Kubernetes version**
1.15

**Additional context**

Error Code: RequestDisallowedByPolicy
	Message: Resource 'master-availabilityset' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"resource-tags","id":"/subscriptions/

**Comment by CecileRobertMichon** [comment]
This is by design, the `customVMTags` are only meant to tag VM resources. Will leave this feature open as a feature request.

**Comment by josh-hetland** [comment]
I'd like to vote on this feature request. ideally the ability to tag ALL resources generated would be ideal for large corporations that have fine grain charge back.

**Comment by jackfrancis** [comment]
I don't understand the ask here. An AvailabilitySet *is* a VM type structure. And we support tags for VMs. What's missing?
