### ISSUE TITLE
Permisssions errors in cluster-autoscaler

### ISSUE THREAD

**Issue by oronboni** [Azure/aks-engine#1903]
**Describe the bug**
From the autoscaler pod I get the following errors:
E0904 05:48:00.422464       1 reflector.go:126] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:339: Failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "jobs" in API group "batch" at the cluster scope
I0904 05:48:00.442419       1 reflector.go:161] Listing and watching *v1.DaemonSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:319
E0904 05:48:00.443958       1 reflector.go:126] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:319: Failed to list *v1.DaemonSet: daemonsets.apps is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "daemonsets" in API group "apps" at the cluster scope
I0904 05:48:01.422737       1 reflector.go:161] Listing and watching *v1.Job from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:339
E0904 05:48:01.424695       1 reflector.go:126] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:339: Failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "jobs" in API group "batch" at the cluster scope

**Steps To Reproduce**

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "@__orchestratorVersion__@",
      "kubernetesConfig": {
	    "cloudProviderBackoff": true,
        "cloudProviderBackoffRetries": 6,
        "cloudProviderBackoffJitter": 1,
        "cloudProviderBackoffDuration": 6,
        "cloudProviderBackoffExponent": 1.5,
        "cloudProviderRateLimit": true,
        "cloudProviderRateLimitQPS": 6,
        "cloudProviderRateLimitBucket": 15,
        "apiServerConfig": {
           "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration",
           "--oidc-client-id": "@__oidcclientid__@",
           "--oidc-groups-claim": "roles",
           "--oidc-issuer-url": "https://login.microsoftonline.com/@__tenantid__@/v2.0",
           "--oidc-username-claim": "email",
           "--oidc-username-prefix": "oidc:"           
          },
        "useManagedIdentity": true,
		"userAssignedID": "@__userAssignedName__@",
        "addons": [
          {
            "name": "cluster-autoscaler",
            "enabled": true,
			"containers": [
            {
              "name": "cluster-autoscaler",
              "image": "gcr.io/google-containers/cluster-autoscaler:v1.14.4",
              "cpuRequests": "100m",
              "memoryRequests": "300Mi",
              "cpuLimits": "100m",
              "memoryLimits": "300Mi"
            }
            ],
            "config": {
              "max-nodes": "99",
              "min-nodes": "5",
              "scan-interval": "30s"
			  }
          },
		  {
            "name": "tiller",
            "enabled" : false
          },
		  {
            "name": "kubernetes-dashboard",
            "enabled" : false
          },
          {
           "name": "ip-masq-agent",
           "enabled": true,
           "containers": [
           {
           "name": "ip-masq-agent",
           "image": "k8s.gcr.io/ip-masq-agent-amd64:v2.4.1",
           "cpuRequests": "50m",
           "memoryRequests": "50Mi",
           "cpuLimits": "50m",
           "memoryLimits": "250Mi"
           }
           ],
           "config": {
           "non-masq-cni-cidr": "168.63.129.16/32",
           "non-masquerade-cidr": "10.10.0.0/16"
           }
           }		  
        ]
		}
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "@__Master_dnsPrefix__@",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/@__subscriptionID__@/resourceGroups/@__resourceGroupName__@/providers/Microsoft.Network/virtualNetworks/@__clusterVnetName__@/subnets/@__Master_vnetSubnetName__@",
      "firstConsecutiveStaticIP": "10.10.0.230",
      "vnetCidr": "10.10.0.0/16",
      "subjectAltNames": [
        "@__Master_dnsPrefix__@.@__Master_DomainSuffix__@"
      ]
    },
    "agentPoolProfiles": [
      {
        "name": "@__k8s_agents_name__@",
        "count": 5,
        "vmSize": "Standard_D4_v2",
        "vnetSubnetId": "/subscriptions/@__subscriptionID__@/resourceGroups/@__resourceGroupName__@/providers/Microsoft.Network/virtualNetworks/@__clusterVnetName__@/subnets/@__agent_vnetSubnetName__@",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "osDiskSizeGB":  400,
        "acceleratedNetworkingEnabled": true
      }
    ],
    "linuxProfile": {
      "adminUsername": "user",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "@__ClusterSshPublicKey__@"
          }
        ]
      }
    }   
  }
}

**Expected behavior**

* The logs from the autoscaler contains repeated permissions issue Autosaler installed in version 1.14.2 and not in 1.14.4. 

**AKS Engine version**
0.37.0

**Kubernetes version**
1.14.1

**Additional context**

**Comment by mboersma** [comment]
@oroboni this should be fixed by @nilo19's work in #1582 (adds `batch` permissions as well as couple other tweaks). Not in a released version yet, but soon.
