### ISSUE TITLE
Deploy does not pre-validate Kubernetes version

### ISSUE THREAD

**Issue by danmassie** [Azure/aks-engine#191]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.27.0
---

**Kubernetes version**:
1.12.4

**What happened**:
1.10.9 was used by aks-engine without any errors being reported

**What you expected to happen**:
either 1.12.4 to be used or an error when validating the cluster configuration if unsupported

**How to reproduce it** (as minimally and precisely as possible):
run aks-engine with orchestratorRelease set to 1.12 and orchestratorVersion set to 1.12.4

**Anything else we need to know**:

**Comment by mboersma** [comment]
I was able to reproduce this with v0.27.0 with this apimodel (excerpt):

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.12",
      "orchestratorVersion": "1.12.4"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "mbtest",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
...
```

But with v0.28.0 or aks-engine master, I got a v1.12.4 cluster as expected. @danmassie I haven't pinpointed where the bug was, but testing indicates it's fixed. Can you try aks-engine v0.28.0?

(In general, you only need to specify one of these fields. `orchestratorVersion` is for requesting a specific patch release, and `orchestratorRelease` will take the requested minor version and use the latest patch release available for it.)

**Comment by danmassie** [comment]
Yes, 0.28.0 supports this version of k8s and creates the cluster as
expected, but this bug was not about supporting 1.12.4. I suspect the same
will occur with 0.28.0 and 1.12.5.

**Comment by CecileRobertMichon** [comment]
@danmassie can you please share the exact command/steps to repro? I am not able to reproduce.

**Comment by mboersma** [comment]
I was able to reproduce this as described, using `aks-engine deploy` with v0.27.0 and `"orchestratorVersion": "v1.12.4"`.  Probably using master and `v1.13.2` or another unsupported version would produce the same results: a 1.10.9 cluster and no obvious errors.

**Comment by CecileRobertMichon** [comment]
Thanks @mboersma, I've updated the issue title to better reflect the issue. I believe this is a discrepancy between `generate` and `deploy` as `generate` does pre-validation of the orchestratorVersion and returns an error as expected for unsupported versions.

/kind bug
