### ISSUE TITLE
Add cloud-controller-manager configuration.

### ISSUE THREAD

**Issue by nilo19** [Azure/aks-engine#1914]
**Describe the request**
Add API support to enable cloud-controller-manager configuration.

**Explain why AKS Engine needs it**
We need to enable some feature flag of ccm, e.g., `ServiceLoadBalancerFinalizer`

**Comment by feiskyer** [comment]
The setting of cloud-controller-manager is required for the following test

```
test/e2e/network/service.go:2049
Sep  6 00:03:02.078: Failed to wait for service to hasFinalizer=true: timed out waiting for the condition
test/e2e/framework/service/wait.go:115
```

/assign @ritazh

**Comment by jackfrancis** [comment]
Are we talking about this kind of configuration that is already possible?

**Comment by jackfrancis** [comment]
Sorry: https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#feat-cloud-controller-manager-config

**Comment by ritazh** [comment]
Seems like a feature-gate https://github.com/kubernetes/cloud-provider-azure/blob/master/tests/k8s-azure/manifest/e2e-slow.json#L16

**Comment by jackfrancis** [comment]
So aks-engine cloud-controller-manager generic config interface doesn't currently support `--feature-gates` is the gap?

**Comment by ritazh** [comment]
does `--feature-gates` in `controllerManagerConfig` get propagated?

**Comment by jackfrancis** [comment]
Yeah, actually nevermind, the current `cloudControllerManagerConfig` configuration object under `kubernetesConfig` supports a standard `--feature-gates` configuration, e.g.:

```
...
    "kubernetesConfig": {
        "cloudControllerManagerConfig": {
            "--feature-gates": "ServiceLoadBalancerFinalizer=true"
        }
    }
...
```

(Not sure that's a 100% correctly formulated CCM feature gate btw. But something like the above should work w/ the current code.)

Also, we're talking about cloud-controller-manager feature gates, not controller-manager feature gates, right?

**Comment by ritazh** [comment]
hmm @jackfrancis you are right, i don't see `cloudControllerManagerConfig` used in https://github.com/kubernetes/cloud-provider-azure/blob/master/tests/k8s-azure/manifest/e2e-slow.json 

@nilo19  Can you give `"--feature-gates"` in `cloudControllerManagerConfig` a try?

**Comment by feiskyer** [comment]
Thanks @jackfrancis @ritazh, and sorry didn't notice this is already supported.

@nilo19 let's add the feature gates using cloudControllerManagerConfig.

**Comment by nilo19** [comment]
> Thanks @jackfrancis @ritazh, and sorry didn't notice this is already supported.
> 
> @nilo19 let's add the feature gates using cloudControllerManagerConfig.

OK. Thank you again @jackfrancis @ritazh.
