### ISSUE TITLE
aks-engine and gmsa support. 

### ISSUE THREAD

**Issue by rexhinvorpsi** [Azure/aks-engine#1917]
Hi guys , 
I have been trying to enable gmsa on my cluster using aks-engine but with no luck . 
Does anyone know of a guide to follow on how to make this possible in Azure . 
I have followed the guide in [Kubernetes and  gmsa for windows nodes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/). 
I think i am stuck on the part of the domain joining the windows node to AD . 

Thank you in advance

**Comment by CecileRobertMichon** [comment]
related to #1225

**Comment by jjburr** [comment]
I just added a load balancer and a NAT rule for RDP to the node then used SConfig to join the device to AD.
Curious as to how you enabled the feature flag as im stuck on this part?

**Comment by rexhinvorpsi** [comment]
Hi @jjburr , you can enable feature gates in the kubernetes config part  of the api model , 
 `    "kubernetesConfig": {
        "kubeletConfig": {
          "--feature-gates": "WindowsGMSA=true"
        },
        "apiServerConfig": {
          "--feature-gates": "WindowsGMSA=true"
        }`

I followed these links on the aks-engine page: [feature-gates](https://github.com/Azure/aks-engine/tree/master/examples/feature-gates) and [windowspool](https://github.com/Azure/aks-engine/tree/master/examples/windows)
Hope it helps.

**Comment by jjburr** [comment]
thanks @rexhinvorpsi - I did see that after i deployed, any tips or ideas how it can be done without reploying have all my gmsa's configured and nodes domain joined so trying to avoid starting over :)

**Comment by rexhinvorpsi** [comment]
I think having the feature gates enabled for windows gmsa i may be wrong i am pretty new at this, in this article from the kubernetes page [gmsasupport](https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/) it does say it needs to be enabled as it is in alpha stage.

**Comment by rexhinvorpsi** [comment]
@jjburr Hey , one small question did you do a custom vnet to do the domain join of the node ? 
Thanks

**Comment by jjburr** [comment]
@rexhinvorpsi yep created two new subnets on an existing vnet with AD and deployed following the custom vnet example.
