### ISSUE TITLE
Installing certifcate from keyvault to windowspool vm using AKS engine

### ISSUE THREAD

**Issue by Ashish-009** [Azure/aks-engine#1930]
Hi all,

I am using AKS engine to create linux vms and windows vm. I am looking for a way to install certificate from keyvault to windows store on windows vm using the configuration file. This certificate then will be used to authenticate to Geneva monitoring.
Can anyone please tell me how to do that Or if there's any other way to achieve this scenario?

**Comment by devigned** [comment]
Check out [Azure Key Vault FlexVolume Add-on](https://github.com/Azure/aks-engine/blob/1904443389f15d671fe2d3c29c37f42eca4d66e8/examples/addons/keyvault-flexvolume/README.md).
