### ISSUE TITLE
How to know whether aks-engine requires version upgrade?

### ISSUE THREAD

**Issue by Banani-Rath** [Azure/aks-engine#1936]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by devigned** [comment]
Can you explain your question in a bit more detail?

**Comment by Banani-Rath** [comment]
Thank you @devigned for quick response!At present AKS managed cluster sends a notification to take action for to apply latest kubernetes version with cluster upgrade!My question is ,how do we know when do we have to upgrade our aks-engine, for above scenario?Is there a way to get notified?If we are running on a lower version,high chances are there we might be hitting some security bugs.

**Comment by devigned** [comment]
My pleasure! I think I get it. Thank you for the clarification. 

So, running `aks-engine version` and then checking if there's a newer version listed on https://github.com/Azure/aks-engine/releases is the experience you'd like for checking if there is a newer version of aks-engine available?

**Comment by Banani-Rath** [comment]
Is there a way to get email notification\RSS feed?

**Comment by devigned** [comment]
You should be able to watch (the GitHub watch dropdown above) the project for releases only. Then you will get notified anytime we drop a new release :).

**Comment by senordeveloper** [comment]
@devigned  when will v0.41.0 be released?

**Comment by devigned** [comment]
I expect we will release v0.41.0 this week. 

As a meta note, we (the aks-engine project) should probably do a better job of adding a milestone for the releases to indicate when the next release is scheduled.

I'm going to close out the issue as I think the original query was answered. If you feel like this issue should stay open, please don't hesitate to reopen it.
