### ISSUE TITLE
Windows VM extensions return success even if powershell script failed 

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#1937]
**Steps To Reproduce**

`exit 1` at the beginning of `parts/k8s/kuberneteswindowssetup.ps1`. 
Deploy a hybrid cluster. Notice that the ARM deployment is successful, including the Windows extensions. However, the windows nodes never come up in the cluster.

**Comment by marosset** [comment]
I think @PatrickLang mentioned this behavior as well - I'll take a look

**Comment by CecileRobertMichon** [comment]
this is the equivalent for linux: https://github.com/Azure/aks-engine/blob/master/docs/howto/troubleshooting.md#cse-exit-codes

**Comment by marosset** [comment]
This work has been completed and deployments should fail if CSEs encounter an error.
