### ISSUE TITLE
Enabling pod security policies prevents kv and flex pods starting

### ISSUE THREAD

**Issue by danmassie** [Azure/aks-engine#195]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.28.0
---

**Kubernetes version**:
1.12.4

**What happened**:
When enableRbac and enablePodSecurityPolicy are both set to true, default pod security policies are created. The restrictive policy is applied to all pods that either don't have a service account with a role binding to a less restrictive policy or a policy bound to the namespace. This results in pods in the kv and flex namespaces being unable to start.

**What you expected to happen**:
All pods provided by aks-engine should have appropriate pod security policies to allow them to run.

**How to reproduce it** (as minimally and precisely as possible):
Set enableRbac and enablePodSecurityPolicy to true.

**Anything else we need to know**:

**Comment by andyzhangx** [comment]
@danmassie It looks like if I changed the namespace to `kube-system` of all pods under kv and flex would fix this issue, is that correct?
cc @ritazh

**Comment by danmassie** [comment]
If they were in the kube system namespace, then yes the privileged policy
would be used.

**Comment by danmassie** [comment]
But it may be more appropriate to have custom policies for these services.
