### ISSUE TITLE
Windows Nodes on custom VNET - cant get logs or kubectl exec

### ISSUE THREAD

**Issue by jjburr** [Azure/aks-engine#1958]
**Describe the bug**
Cannot get logs or kubectl exec: 

Get https://k8s-master-13984109-0:10250/containerLogs/kube-system/kubernetes-dashboard-54b795b69b-9gqgs/kubernetes-dashboard?tailLines=5000&timestamps=true: dial tcp: lookup k8s-master-13984109-0 on 172.21.1.4:53: **server misbehaving**

**Steps To Reproduce**
Deploy windows node cluster to a custom VNET that is configured to point at AD DNS IP address

Attempt to access logs or Kubectl EXEC

**Kubernetes version**
1.14

**Comment by jjburr** [comment]
Also containers are unable to resolve other containers IP addresses, for example I have two pods 1 with a web service and another with a SQL database, when adding the container name as a connection string on the web service it cannot resolve.

How does DNS work in k8s for windows containers? Im use to compose where you can just specify a windows DNS server and point connection strings at the container names

**Comment by rexhinvorpsi** [comment]
Hey @jjburr sorry for commenting on a closed issue, i was wondering how did you resolve this ?

**Comment by jjburr** [comment]
Was a DNS issue, master has to use azure provided DNS to be able to properly resolve the windows nodes.

I ended up deploying to its own vnet, then pairing with my AD vnet and pointing the windows nodes DNS to my AD DNS.

DM me on twitter @Ciresonjoe if you need any help took me a bit of trial and error but finally have a hybrid cluster up and running with GMSA working.
