### ISSUE TITLE
Add Windows CSI proxy to Windows-AKS VHDs

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#1968]
**Describe the request**

Windows support for CSI will require adding a new service. This is described in https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190714-windows-csi-support.md

**Explain why AKS Engine needs it**

It needs to be there for the out-of-tree Azure storage plugins to work

https://github.com/Azure/container-compute-upstream/issues/6

**Describe the solution you'd like**

It should be in the Windows AKS VHD (#1084) so it's preinstalled

**Describe alternatives you've considered**

Install CSI on host instead of using daemon sets. This means nodes need to be reprovisioned to get an updated CSI implementation.

**Additional context**

**Comment by jackfrancis** [comment]
@chewong @jsturtevant do you know if this issue was ever actually completed?

**Comment by jsturtevant** [comment]
Looking in the vhd configuraiton I don't see the csi proxy installed on the vhd: 

https://github.com/Azure/aks-engine/blob/master/vhd/packer/configure-windows-vhd.ps1

**Comment by jackfrancis** [comment]
@jsturtevant @marosset assigned this to you under the assumption that this is a trivial work item. Feel free to push back if not.
