### ISSUE TITLE
Private Zone in Windows hybrid model wont resolve using using CoreDNS or Kube-DNS configuration

### ISSUE THREAD

**Issue by jjburr** [Azure/aks-engine#1969]
Following the guide here:
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#impacts-on-pods

Trying to resolve services IP address outside the windows cluster in a Hybrid model, I have created a config map for Kube-DNS however containers still are unable to resolve external services.

When attempting to update the config map for core DNS it applys, however 30 seconds latter addonmanager.kubernetes.io/mode: Reconcile reverts it back to the default settings.

Need to be able to resolve windows services in the domain. How can I configure this correctly to resolve mydomain.local addresses?

**Comment by jjburr** [comment]
Managed to turnoff Reconcile in the Addons config so ConfigMap doesnt get over-written, however still unable to resolve any domain IP addresses with all the documented configuration

**Comment by marosset** [comment]
@PatrickLang can you take a look?

**Comment by jjburr** [comment]
This was resolved after restarting the master node.
