### ISSUE TITLE
Failing to drain node should not fail to upgrade VMSS nodes

### ISSUE THREAD

**Issue by chengliangli0918** [Azure/aks-engine#1979]
**Describe the bug**
In most places, draining node failure is just logged, and doesn't fail the upgrading process. But in upgrader.go, there is one place that the draining node failure fails the upgrading process.

https://github.com/Azure/aks-engine/blob/2f19e5a4b0cf045d473d0240110d80a058c033af/pkg/operations/kubernetesupgrade/upgrader.go#L551-L553

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by jackfrancis** [comment]
Dup of #1919
