### ISSUE TITLE
using aks-engine deploy with aks-engine generate

### ISSUE THREAD

**Issue by Ashish-009** [Azure/aks-engine#1994]
**Use Arm Templates to deploy using aks-engine deploy**

I am generating arm templates using aks-engine generate cmd. Can I use aks-engine delpoy cmd  to take these aks-engine generated arm files as input and create my cluster.  If yes then how?

**Comment by devigned** [comment]
Just use `az group deployment create` with the deployment template and variables.

https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest

**Comment by mboersma** [comment]
`aks-engine deploy` basically does both `aks-engine generate` and `az group deployment create` for you.

So the `deploy` command won't work with existing ARM templates. (It does leave its generated ARM templates and related artifacts on disk so they could be referenced or reused in the future.)

 The way @devigned points out is the way to go if you're using `aks-engine generate`.

**Comment by jackfrancis** [comment]
Feel free to re-open if we haven't answered your questions!
