### ISSUE TITLE
Api models with agent profiles specifying both AvailabilitySet and Ephemeral disks generate invalid ARM

### ISSUE THREAD

**Issue by marosset** [Azure/aks-engine#1996]
**Describe the bug**
API models with AgentProfiles with both "availabilityProfile": "AvailabilitySet" and "storageProfile": "Ephemeral" produce invalid ARM.

ARM objects for the availability sets are not created by the virtual machines objects have a depenecy on them.

I think this if condition should be if profile.IsManagedDisks() || profile.IsEphemalDisks {
https://github.com/Azure/aks-engine/blob/0ac7d36ee03453950a8827cacef136ce1a19ea99/pkg/engine/armresources.go#L124

**Steps To Reproduce**

 - Create an api model with at least one agentPoolProfile with availabilityProfile": "AvailabilitySet" and "storageProfile": "Ephemeral"
- Generate ARM deployment resources for that api model
- run az group deployment validate on those are deployment resources

**Expected behavior**
ARM deployment files should be valid.

**AKS Engine version**
Current

**Kubernetes version**
n/a

**Additional context**

**Comment by jackfrancis** [comment]
Good find 👍

**Comment by bridgetkromhout** [comment]
Thanks again for filing this issue. As AKS Engine is deprecated, I'm closing it at this time.
