### ISSUE TITLE
Rationalize localization requirements

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2]
The localization spec under `loc/` is no longer being actively maintained. Should we simply remove this overhead as cruft from a prior acs-engine era? Or should be prioritizing generating localized docs/code?

**Comment by CecileRobertMichon** [comment]
@jackfrancis can you please add more details to this issue so someone could pick it up?

**Comment by craiglpeters** [comment]
Delete the translations and associated machinery please
