### ISSUE TITLE
Remove NSSM dependency from Windows nodes

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#2003]
**Describe the bug**

NSSM is no longer required and makes it harder to track service states for kubelet and kube-proxy. We should remove it and start the services directly. The flags were added in https://github.com/kubernetes/kubernetes/pull/60144

Work needed:

- [ ] make sure services start, and have right dependency chain kube-proxy -> kubelet -> docker
- [ ] ensure logs created at same location and they're collected in the support tool https://github.com/Azure/azure-diskinspect-service/blob/bb52c8fd52a0aaeb1a738546a8c02443c4be39d6/pyServer/manifests/windows/aks

**Steps To Reproduce**

Deploy a windows node

**Expected behavior**

no nssm.exe in c:\k folder

**AKS Engine version**

all

**Kubernetes version**

1.10+

**Additional context**

Related issues: 

https://github.com/Azure/aks-engine/issues/1928

**Comment by marosset** [comment]
I'm starting to look into this.

**Comment by marosset** [comment]
We should probably get https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/kube-windows-services?tabs=ManagementIP updated as well
