### ISSUE TITLE
kubeadm is not support with AKS-Engine

### ISSUE THREAD

**Issue by Bougyz** [Azure/aks-engine#2018]
if a customer has created a Kubernetes cluster on Azure using aks-engine. They’re willing to administer the cluster – particularly to replace the CA Certificates, but seems like kubeadm is not supported in aks-engine. Any idea?

**Comment by devigned** [comment]
In the current version of aks-engine, we assume that if the cluster was built with aks-engine, then certificate rotation will be handled by using aks-engine (`aks-engine rotate-certs`). I don't think this is a feature we will commit to for the current version.

I think we would prefer to queue this up for the next version of aks-engine.

I'm going to close this issue and add it to design goals for vNext. Thank you for bring this up.
