### ISSUE TITLE
GMSA works for pods in the default namespace, but pods dont create when in custom namespace?

### ISSUE THREAD

**Issue by jjburr** [Azure/aks-engine#2025]
**Describe the bug**
I can create pods fine in the default namespace using the securityContext, and this works well.

When deploying the same deployement.yaml in a custom namespace the pod never gets created. As soon as I remove the securityContext from the yaml I can create the pod.

Is there extra steps required to configure a customnamespace to work correctly for GMSA accounts?

**Expected behavior**
Pod is created the same way as in the default namespace

**Kubernetes version**
1.15.3

**Comment by olcayunver** [comment]
Can you @jjburr share how you did resolve the issue?

**Comment by jjburr** [comment]
I had to create a rolebinding that allowed the default service account in the namespace read permissions on the gmsa account
