### ISSUE TITLE
networkPolicy / networkPlugin compatibility matrix

### ISSUE THREAD

**Issue by sylr** [Azure/aks-engine#2026]
**Describe the request**

Can we have a compatibility matrix of networkPolicy / networkPlugin, e.g. :

| networkPolicy / networkPlugin  | azure | kubenet | flannel | cilium |
| ------------------------------- | ----- | -------- | ------- | ------ |
| **azure** | Experimental | Supported |  |  |
| **calico** | Supported |  |  |  |
| **cilium** |  |  |  |  |

Possible values: `supported` / `unsupported` / `recommended` / `not recommended` / `experimental`

**Comment by devigned** [comment]
Great idea! 

I would also like to see each combination enter into our [test configurations here](https://github.com/Azure/aks-engine/tree/master/test/e2e/test_cluster_configs). That way we are constantly verifying the stability of each combination.

**Comment by bridgetkromhout** [comment]
Hi, @sylr - Thanks for the input. As AKS Engine is now deprecated, I'll resolve this issue at this time. Please look at AKS or CAPZ for your ongoing needs; thanks! https://github.com/Azure/aks-engine#project-status
