### ISSUE TITLE
Add support for runtimeclass scheduler for Linux & Windows nodes

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#2042]
**Describe the request**
https://github.com/kubernetes/enhancements/issues/894

This proposes a simpler way to specify what runtime a pod should use, and add the right taints / tolerations. Add an example runtime class to steer a pod towards Windows or Linux as appropriate.

**Explain why AKS Engine needs it**

Try out a new feature, see if it's easier to manage than taints/tolerations.

**Comment by jackfrancis** [comment]
@CecileRobertMichon @devigned should we create a new issue here for this request?:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues

**Comment by jackfrancis** [comment]
No plans to do this work in AKS Engine

**Comment by CecileRobertMichon** [comment]
> @CecileRobertMichon @devigned should we create a new issue here for this request?:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues

Correct me if I'm wrong but this doesn't look like it's an Azure specific feature so it wouldn't be a capz feature request. Could be a kubeadm feature request if not already supported.

**Comment by CecileRobertMichon** [comment]
looking at https://kubernetes.io/docs/concepts/containers/runtime-class/#cri-configuration it requires an update to the CRI config so that would be an addition to image-builder containerd config I believe.
