### ISSUE TITLE
Make Windows network debug tools work with IaasDiskInspector

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#2045]
**Describe the request**

A typical network troubleshooting workflow needs the tools here:
https://github.com/microsoft/SDN/tree/master/Kubernetes/windows/debug

They output logs to a few common directories. 

We need a workflow where:

1. (optional) open a support case for AKS
1. someone can log into a node with network issues
2. initiate log capture
3. reproduce the issue
3. stop log capture
1. run [IaasDiskInspector](https://github.com/Azure/azure-diskinspect-service) to extract logs from VM for these common paths

**Explain why AKS Engine needs it**

This will save a lot of steps in debugging network issues

**Comment by MikkelHegn** [comment]
I went over the differences between IaasDiskInspector and the current CollectLogs script:

Currently IaaSDiskInspector has an AKS manifest for copying log files: https://github.com/Azure/azure-diskinspect-service/blob/master/pyServer/manifests/windows/aks. This can be triggered from the Azure Support Center.

Aks-engine copies a script to collect log son to the VHDs: https://github.com/Azure/aks-engine/blob/master/scripts/collect-windows-logs.ps1

  | Aks-engine | IaaSDiskInspector
-- | -- | --
Execution | Local on node   (requires customer   action today) | From Azure Support   Center
File locks | Handles logs files   with locks | Not sure if this   is a problem, but is not handled?
Event Logs | Filtered | Not filtered
PageFileInfo | Included | Not included
Network logs and debugging info | [Runs this script to get additional network info](https://raw.githubusercontent.com/Microsoft/SDN/master/Kubernetes/windows/debug/collectlogs.ps1) | Not included

**Comment by MikkelHegn** [comment]
@AbelHu @marosset - this is a good supportability issue to get addresses.

**Comment by marosset** [comment]
@ksubrmnn too

**Comment by MikkelHegn** [comment]
@suimma74 - FYI for the AKS log collection. Not sure if IaaSDiskInspector can execute script?

**Comment by MikkelHegn** [comment]
I will close this for now, as there is good guidance on how to get further info from within the node.
