### ISSUE TITLE
Identitiy system not propagated from cli parameters

### ISSUE THREAD

**Issue by deaborch** [Azure/aks-engine#2054]
**Describe the bug**
When the identity system is specified from the cli, It does not get included in the final template generated where there is no identity system specified in the in the api model. It often results in the use of the default identity system (azure_ad) regardless of what is passed in the cli. 

**Steps To Reproduce**

- In the API model, do not specify the identity system
- Within when deploying the cluster using deploy command, specify the identity system as "adfs". 
- Check the generated arm template and notice the identity system set to "azure_ad"

**Expected behavior**
Where there is an Identity system specified in the cli, it should be used as the identity system when deploying the Kuberentes cluster. 

**AKS Engine version**
0.41.0
**Kubernetes version**
1.11
**Additional context**

**Comment by devigned** [comment]
I just repro'd this issue on master (baef53d6b) by running the following:
```bash
./bin/aks-engine deploy -m ./examples/kubernetes.json \
  --client-id $CLIENT_ID --client-secret $CLIENT_SECRET \
  -s $SUBSCRIPTION_ID -l southcentralus -p test2054 --identity-system adfs -f
```
In the generated `azuredeploy.json` the identity is set as follows: `"customCloudIdentifySystem": "azure_ad",`
