### ISSUE TITLE
Implement VMSS tagging for autoscaler

### ISSUE THREAD

**Issue by sylr** [Azure/aks-engine#2057]
**Describe the request**

Implement VMSS tagging according to https://github.com/kubernetes/autoscaler/pull/1982

**Explain why AKS Engine needs it**

aks-engine needs it so that kubernetes cluster using autoscaler can have VMSS scaled from 0 instances.

**Comment by jackfrancis** [comment]
Sorry, I saw #2079 first and tagged @mboersma on it. Let's track this work there.
