### ISSUE TITLE
aks-engine scale fails adding the availabilitySet created as part k8s nodes

### ISSUE THREAD

**Issue by maurya-m** [Azure/aks-engine#2058]
**Describe the bug**
Unable to add new nodes to k8s cluster even after the aks-engine scale 

**Steps To Reproduce**
aks-engine scale   --location westeurope --subscription-id "xxx" --resource-group "<my-resource-group" \
--api-model ./somedir/apimodel.json --node-pool <nodepool name> --new-node-count <desired number of nodes> --apiserver <apiserver endpoint FQDN or IP address>

**Expected behavior**
kubectl get nodes -o wide command return with new nodes as set in the <desired number of nodes>

**AKS Engine version**
Version: v0.40.0
GitCommit: e52789fae

**Kubernetes version**
v13.5
**Additional context**
This is the warnning message when running the scale command :
There are 0 nodes named "*agentpool1*" in the Kubernetes cluster, but there are 7 VMs named "*agentpool1*" in the resource group ABSCXXX

**Comment by devigned** [comment]
Hi @maurya-m, would it be possible to share a bit more detail? It would be super helpful to provide the API model or a representative API model, so we can repro the issue.

**Comment by maurya-m** [comment]
hi @devigned , here i am attaching the apimodel.json (portion where the agentpool is mentioned)

the node count was at 3 , need to increase to 6 . Please let me know if this suffice to repro the issue? thanks

"agentPoolProfiles": [
      {
        "name": "agentpool1",
        "**count": 3,**
        "vmSize": "Standard_DS13_v2",
        "osDiskSizeGB": 512,
        "osType": "Linux",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "vnetSubnetID": "/subscriptions/xxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.Network/virtualNetworks/xxxxxxxx/subnets/agent",
        "distro": "aks",
        "kubernetesConfig": {
          "kubeletConfig": {
            "--address": "0.0.0.0",
            "--allow-privileged": "true",
            "--anonymous-auth": "false",
            "--authorization-mode": "Webhook",
            "--azure-container-registry-config": "/etc/kubernetes/azure.json",
            "--cgroups-per-qos": "true",
            "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
            "--cloud-config": "/etc/kubernetes/azure.json",
            "--cloud-provider": "azure",
            "--cluster-dns": "10.0.0.10",
            "--cluster-domain": "cluster.local",
            "--enforce-node-allocatable": "pods",
            "--event-qps": "0",
            "--eviction-hard": "memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%",
            "--feature-gates": "PodPriority=true",
            "--image-gc-high-threshold": "85",
            "--image-gc-low-threshold": "80",
            "--image-pull-progress-deadline": "30m",
            "--keep-terminated-pod-volumes": "false",
            "--kubeconfig": "/var/lib/kubelet/kubeconfig",
            "--max-pods": "30",
            "--network-plugin": "cni",
            "--node-status-update-frequency": "10s",
            "--non-masquerade-cidr": "0.0.0.0/0",
            "--pod-infra-container-image": "k8s.gcr.io/pause-amd64:3.1",
            "--pod-manifest-path": "/etc/kubernetes/manifests",
            "--pod-max-pids": "100"
          }
        },
        "acceleratedNetworkingEnabled": true,
        "acceleratedNetworkingEnabledWindows": false,
        "vmssOverProvisioningEnabled": false,
        "fqdn": "",
        "preProvisionExtension": null,
        "extensions": []
      }

**Comment by devigned** [comment]
Hi @maurya-m, what I was really hoping for is a full API model, so I could run a deploy, then a scale and see if I can reproduce your results. Providing a portion of the API model is helpful, but not as much as it would be if I had the whole API model (without any of the secrets, of course).
