### ISSUE TITLE
Connecting (kubectl) from master node via private loadbalancer getting random: Unable to connect to the server: dial tcp 10.110.8.240:443: i/o timeout

### ISSUE THREAD

**Issue by ebandis** [Azure/aks-engine#2059]
Deployed AKS-Engine 0.39.2, K8s 1.15.3, kubectl is getting random timeouts (every third fourth request) then connecting (kubectl) from the master node via private (basic) loadbalancer IP 10.110.8.24. Strangely kubectl does not timeout if connecting remotely via the same loadbalancer IP. 

**Steps To Reproduce**
Here is  apimodel used to deploy the cluster:
Sensitive info deleted.
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.15.3",  
      "kubernetesConfig": {
        "privateCluster": {
          "enabled": true
        },
        
        "enableRbac": true ,
        "kubeProxyMode": "ipvs",
        "networkPolicy": "calico",
        "networkPlugin": "kubenet",
        "clusterSubnet": "10.100.72.0/21",
        "dnsServiceIP": "10.100.80.10",
        "serviceCidr": "10.100.80.0/20",  
        "kubeletConfig": {
          "--non-masquerade-cidr": "10.100.64.0/19"
        },
        "addons": [
          {
            "name": "container-monitoring",
            "enabled": true,
            "config": {
              "workspaceGuid": "",
              "workspaceKey": ""
            }
          }         
        ]
      }
    },
    "aadProfile": {
      "serverAppID": "",
      "clientAppID": "",
      "tenantID": ""
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "k8s-agent-",
      "vmSize": "Standard_D2s_v3",
      "vnetSubnetId": "/subscriptions//resourceGroups//providers/Microsoft.Network/virtualNetworks//subnets/K8S",
      "firstConsecutiveStaticIP": "10.100.64.230",
      "vnetCidr": "10.100.64.0/21"
    },
    "agentPoolProfiles": [
      {
        "name": "agent",
        "count": 3,
        "vmSize": "Standard_D4s_v3",
        "vnetSubnetId": "/subscriptions//resourceGroups//providers/Microsoft.Network/virtualNetworks//subnets/K8S",
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "AvailabilitySet"
        
      }
    ],
    "linuxProfile": {
      "adminUsername": "admin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": "",
      "keyvaultSecretRef": {
        "vaultID": "/subscriptions//resourceGroups//providers/Microsoft.KeyVault/vaults/",
        "secretName": ""
      }
    }  
  }
}

**Routing table attached to the K8s subnet**
Sensitive info deleted.
![timeout](https://user-images.githubusercontent.com/12116224/65897654-a93e8080-e3a7-11e9-9a85-2b533165fb55.PNG)

**Timeouts every third or fourth request then connecting from any master node via internal loadbalancer IP. Can ping all VMs, all VMs are up and running.**
Sensitive info deleted

![timeout1](https://user-images.githubusercontent.com/12116224/65897949-5a451b00-e3a8-11e9-99b0-2fbbb0947016.PNG)

Never timeouts if connecting (kubectl) through the private load balancer from outside (not k8s master node)

**Comment by sylr** [comment]
You can't use a private load balancer to connect to a master from a master.

Why ? Because every time the load balancer will choose to redirect your request to the master it originated from the master will fail to reply back because it will not understand how he is supposed to reply to himself through a load balancer.

**Comment by ebandis** [comment]
Thanks for the reply. What you are saying and what is explained in [#243](https://github.com/Azure/aks-engine/pull/243) it all make sense...but here is more odd thing, this behavior can be replicated only if I am logging in as local administrator. All master and agent nodes are domain joined and if I login as domain user I DO NOT get  any request drops from the same server going through the ILB. Any thoughts on this? Appreciate.
