### ISSUE TITLE
E2E: only run Windows custom image test variations on a single k8s version

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2072]
As a practical way of reducing our test overhead, let's run the various Windows custom image / VHD / etc tests against a single version of k8s; perhaps the default that ships for cluster w/ Windows node pools?

That would be modifying the JSON files here:

`test/e2e/test_cluster_configs/windows`

That would be adding a root `"options"` object that has the `"allowedOrchestratorVersions"` array in it, e.g.:

```
"options": {
	"allowedOrchestratorVersions": ["1.15"]
},
```

**Comment by jackfrancis** [comment]
@devigned @marosset FYI

**Comment by devigned** [comment]
I think this would be relatively trivial to implement.

Check out: https://github.com/Azure/aks-engine/blob/7a6981d8367d3bf135e6e043916bfa8cbe92b2f1/Jenkinsfile#L154-L159

I believe all one would need to do is the following:
```groovy
// define some job level or server parameter that is "CurrentVersion", 
// thus `params.CurrentVersion`

def isAllowedVersion = jobCfg.options?.allowedOrchestratorVersions == null ? true : version in jobCfg.options.allowedOrchestratorVersions

isAllowedVersion |= jobCfg.options?.useCurrentVersion && params.CurrentVersion == version

// ....
```

**Comment by marosset** [comment]
Cool, we can start using this with the windows tests but i imaging this would be useful for more test cluster configs

**Comment by marosset** [comment]
This work was completed but the issue was not closed
