### ISSUE TITLE
proposal: fail fast if OS image is not available

### ISSUE THREAD

**Issue by jadarsie** [Azure/aks-engine#2076]
**What**

Add a new command that returns the OS image metadata for a given AKSe distro. Something like this maybe.

```
$> aks-engine distro --name aks-ubuntu-16.04 [--cloud AzurePublicCloud]
Offer: aaa
Publisher: bbb
SKU: ccc
Version: xxxx.yy.zz
```

**Why**

The Azure Stack doc page documents which VHD is required for a specific AKSe version. However, this approach is not sufficient, users do not read the docs or are not aware of them. 

Users (and troubleshooters) of disconnected AzS stamps  will enjoy a better experience if they can quickly figure out  which VHD is expected.

**Next Steps**

In addition to the proposed command, it would be nice to short-circuit the execution of the `deploy` command (and print a nicer error message) if the expected VHD is not available in the local marketplace.

**Comment by jadarsie** [comment]
The original proposal is not properly addressing the Windows VHD case.

A next iteration of this proposal would be to short-circuit the execution of the `deploy` command if any of the VHDs specified in the generated apimodel is not available in the target cloud's marketplace.

In that case, AKSe should NOT start the deployment and print a clean message (currently a stacktrace), that roughly says: "Hey, you are trying to use image XYZ, but it is not available, go get it before you re-try."

The `deploy` command output could potentially include the list of available images, but this may be confusing to users (at least for Linux nodes) as it won't give them the entire picture. The corresponding AKSe version that goes with the image will be missing.

**Comment by jadarsie** [comment]
FYI @marosset

**Comment by marosset** [comment]
Right now all windows agent pools must use the same image and the image details are stored in the windowsProfile.
https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#marketplace-images has more details

**Comment by marosset** [comment]
(in case you were looking for info on how windows images are referenced to perform the check :))

**Comment by jadarsie** [comment]
I was mostly interested in feedback to make sure this works for everyone. Thx for the details!

**Comment by marosset** [comment]
This seems like a useful check to perform as part of  `deploy` operations

**Comment by CecileRobertMichon** [comment]
sgtm
