### ISSUE TITLE
Set VMSS Tags to enable scale to zero 

### ISSUE THREAD

**Issue by DavidLangworthy** [Azure/aks-engine#2079]
AKS Engine needs to set VMSS tags to enable scale to zero as defined in the cluster-autoscaler azure provider Readme.  [https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#scaling-a-vmss-node-group-to-and-from-0](url)

Scaling a VMSS node group to and from 0
If you are using nodeSelector, you need to tag the VMSS with a node-template key "k8s.io_cluster-autoscaler_node-template_label_" for using labels and "k8s.io_cluster-autoscaler_node-template_taint_" if you are using taints.

Note that these tags use the pipe _ character compared to a forward slash due to Azure tag name restrictions.

Examples
Labels
To add the label of foo=bar to a node from a VMSS pool, you would add the following tag to the VMSS k8s.io_cluster-autoscaler_node-template_label_foo: bar.

You can also use forward slashes in the labels by setting them as an underscore in the tag name. For example to add the label of k8s.io/foo=bar to a node from a VMSS pool, you would add the following tag to the VMSS k8s.io_cluster-autoscaler_node-template_label_k8s.io_foo: bar

Taints
To add the taint of foo=bar:NoSchedule to a node from a VMSS pool, you would add the following tag to the VMSS k8s.io_cluster-autoscaler_node-template_taint_foo: bar:NoSchedule.

You can also use forward slashes in taints by setting them as an underscore in the tag name. For example to add the taint of k8s.io/foo=bar:NoSchedule to a node from a VMSS pool, you would add the following tag to the VMSS k8s.io_cluster-autoscaler_node-template_taint_k8s.io_foo: bar:NoSchedule

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by jackfrancis** [comment]
@mboersma I think this is related to the general cluster-autoscaler improvement efforts we're doing

**Comment by mboersma** [comment]
OT: The documentation pasted above is a mess. (Do you understand it? And `_` is the pipe character? No.)

I read the PRs and I think I understand the change now. (This isn't in a cluster-autoscaler release yet, so there's no urgency.)

**Comment by mboersma** [comment]
Note that aks-engine can already scale a node pool down to zero if `"min_nodes": "0"` is in the addon config for cluster-autoscaler: no code changes necessary at least for Kubernetes 1.16.1 / cluster-autoscaler 1.16.1.

**Comment by DavidLangworthy** [comment]
Yes, but how does it scale it back up?

**Comment by mboersma** [comment]
cluster-autoscaler scales up as needed when load increases. I've tested this with a 1.16.1 cluster and it scaled one node pool to zero, then added nodes back to it as load increased.

AFAICT cluster-autoscaler behaves as expected in an AKS Engine cluster (although see #2030). The documentation posted here relates to code that isn't in a Kubernetes release yet, but doesn't appear to be breaking. @DavidLangworthy is there a specific bug you found?

**Comment by mboersma** [comment]
I don't think there's a specific bug to fix here, so I'm going to close this. But I can certainly be wrong, so @DavidLangworthy please reopen if there's something we should follow up on here.
