### ISSUE TITLE
cluster-autoscaler (addon) repeatedly crashes.

### ISSUE THREAD

**Issue by SidhuG** [Azure/aks-engine#209]
**Is this a request for help?**:
BUG
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.28.1
---

**Kubernetes version**:1.13.1

**What happened**:
I have configured to use VM scale sets for agents nodes. However, cluster-autoscaler is pod is repeatedly getting crashed, with following error 
 Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:132
E1228 10:23:20.286156       1 azure_scale_set.go:199] VirtualMachineScaleSetVMsClient.List failed for k8s-bodev-15912895-vmss: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/XXXXXXX-XXXXXX-XXXX-XXX/resourceGroups/exxxxxxxx-dev/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-bodev-15912895-vmss/virtualMachines?api-version=2018-10-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/XXXXX-XXXXXXX-XXXXXX-XXXXX/oauth2/token?api-version=1.0: dial tcp: i/o timeout'
F1228 10:23:20.286206       1 azure_cloud_provider.go:139] Failed to create Azure Manager: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/XXXXX-XXXXXXX-XXXXXX-XXXXX/resourceGroups/eXXXXX-XXXXXXX-XXXXXX-XXXXX-dev/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-bodev-15912895-vmss/virtualMachines?api-version=2018-10-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/XXXXX-XXXXXXX-XXXXXX-XXXXX/oauth2/token?api-version=1.0: dial tcp: i/o timeout'

**What you expected to happen**:
The cluster-autoscaler pod should start without any errors, and should update configmap "cluster-autoscaler-status" with success status.

**How to reproduce it** (as minimally and precisely as possible):
set "availabilityProfile": "VirtualMachineScaleSets", for agentpoolprofiles

**Anything else we need to know**:
Similar error was seen on previous version of acs-engine, however it was fixed in subsequent release.
https://github.com/Azure/acs-engine/issues/4016

**Comment by CJJ69** [comment]
Could be related to  https://github.com/Azure/acs-engine/issues/4055
This is still an issue in aks-engine v0.28.1

Check the actual name of your VMSS
Is your VMSS named: "k8s-bodev-15912895-vmss" ?

It's probably named: "1591k8s00"

Try updating the cluster-autoscaler Deployment yaml in kube-system namespace
e.g. "--nodes=1:5:1591k8s00",
