### ISSUE TITLE
Windows nodes initialization script fails in hybrid cluster with custom VNet 

### ISSUE THREAD

**Issue by 4ux-nbIx** [Azure/aks-engine#210]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
Version: v0.28.1
GitCommit: efc9dcfd
GitTreeState: clean
---

**Kubernetes version**:
1.11.5

**What happened**:
Deployed hybrid cluster in custom vnet with one subnet. kuberneteswindowssetup.ps1 failed to configure networking because MasterSubnet parameter was null or empty. 

Fixed this manually by providing 'masterSubnet' parameter in azuredeploy.parameters.json and deploying generated ARM template.

Cluster definition:
```json
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.11",
            "orchestratorVersion": "1.11.5"
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "dnsPrefix",
            "vmSize": "Standard_D2_v2",
            "vnetSubnetId": "subnet",
            "agentVnetSubnetId": "subnet",
            "firstConsecutiveStaticIP": "192.168.255.200",
            "vnetCidr": "192.168.255.0/24"
        },
        "agentPoolProfiles": [{
                "name": "win",
                "count": 1,
                "vmSize": "Standard_DS2_v2",
                "vnetSubnetId": "subnet",
                "osType": "Windows"
            },
            {
                "name": "linux",
                "count": 1,
                "vmSize": "Standard_DS2_v2",
                "vnetSubnetId": "subnet"
            }
        ],
        "windowsProfile": {
            "adminUsername": "adminUsername",
            "adminPassword": "adminPassword"
        },
        "linuxProfile": {
            "adminUsername": "adminUsername",
            "ssh": {
                "publicKeys": [{
                    "keyData": "ssh-rsa ..."
                }]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "clientId",
            "secret": "secret"
        }
    }
}
```

**What you expected to happen**:
masterSubnet parameter is set during ARM template generation process

**How to reproduce it** (as minimally and precisely as possible):
Deploy provided cluster into a custom VNet with a single subnet.

**Anything else we need to know**:

**Comment by sylus** [comment]
@4ux-nbIx I was trying to see if I came across the same issue. Did your deployment still succeed and was all green? Everything worked perfectly for me except my windows node doesn't show up when do kubectl get nodes, but I can ssh in. It seems kubelet and everything wasn't installed though. Was curious where u saw this error so I can check on my install as well.

**Comment by sylus** [comment]
Yup it was that, honestly super annoying since wasn't immediately clear. I remember had to do this last time as well. :S

**Comment by 4ux-nbIx** [comment]
@sylus Everything was green, but windows node wasn't wired up to the cluster correctly by the startup script. Figured it out by checking the script's log file at c:\AzureData. After setting masterSubnet manually and deploying the ARM template everything worked. The windows node seems to be working correctly. No more issues so far...

**Comment by zhiweiv** [comment]
@4ux-nbIx 
My agent pool name is windowspool1, windowspool1Subnet is also missing from azuredeploy.parameters.json compared with regular one, will it matter?

Here is my template, which value masterSubnet should be? 10.1.0.0/16 too?

```
"masterProfile": {
	"vnetSubnetId": "subnet",
	"firstConsecutiveStaticIP": "10.1.255.239",
	"vnetCidr": "10.1.0.0/16"
}
```

**Comment by zhiweiv** [comment]
windowspool1Subnet is invalid in azuredeploy.parameters.json with custom vnet, no need to add it.

**Comment by JoaquimFreitas** [comment]
Hi, 

Getting exactly this same error, with **aks-engine 0.28.1** and **0.29.1**, on hybrid cluster deployments with custom vnet (address space` 10.10.0.0/6`), and a subnet for the cluster `10.10.0.0/17.`

My ARM Template is very similar, and I even added the additional definitions:

```
            "kubernetesConfig": {
                "clusterSubnet":      "10.10.0.0/17",
                "serviceCidr":        "10.10.128.0/17",
                "dnsServiceIP":       "10.10.128.10",
                "dockerBridgeSubnet": "172.17.0.1/16",
                "networkPlugin":      "azure",
                "enableRbac":         true
            }

    "masterProfile": {
    	"vnetSubnetId": "subnet",
	"firstConsecutiveStaticIP": "10.10.255.239",
	"vnetCidr": "10.10.0.0/16"
    }
```

Everything deploys without any errors, but at the end ALL Windows nodes are not present/available in the k8s cluster, the cluster don't even recognize them.

I'm getting the following error on the Windows VMs, @`C:\AzureData\CustomDataSetupScript.log` :

```
2019-01-25T15:35:05.6075413+00:00: Found version 18.09.0. Installing...
WARNING: Cannot verify the file SHA256. Deleting the file.
WARNING: C:\windows\TEMP\DockerMsftProvider\Docker-18-09-0.zip does not exist
Install-Package : Cannot find path 'C:\windows\TEMP\DockerMsftProvider\Docker-18-09-0.zip' because it does not exist.
At C:\AzureData\k8s\windowsconfigfunc.ps1:69 char:9
+         Install-Package -Name Docker -ProviderName DockerMsftProvider ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\windows\TEMP...ker-18-09-0.zip:String) [Install-Package], Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand,Microsoft.PowerShell.Packag
   eManagement.Cmdlets.InstallPackage

The service name is invalid.

More help is available by typing NET HELPMSG 2185.
```
