### ISSUE TITLE
Azure Stack deployment - CSE error: exit code 30

### ISSUE THREAD

**Issue by blunozr** [Azure/aks-engine#2110]
**Describe the bug**
Deploying a single master / single worker cluster on Azure Stack rel 1907 with ADFS identity provider.  The infrastructure is deployed successfully, but fails on the "kubectl cluster-info" command due to a timeout.

**Steps To Reproduce**
Contents of kubernetes-azurestack.json
#####
{
    "apiVersion": "vlabs",
    "location": "ssccentral",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorVersion": "1.13.9",
            "kubernetesConfig": {
                "kubernetesImageBase": "mcr.microsoft.com/k8s/azurestack/core/",
                "useInstanceMetadata": false,
                "networkPlugin": "kubenet"
            }
        },
        "customCloudProfile": {
            "portalURL": "https://portal.ssccentral.dev.azs.cloud-nuage.gc.ca"
        },
        "masterProfile": {
            "dnsPrefix": "akse-dev",
            "distro": "aks-ubuntu-16.04",
            "count": 1,
            "vmSize": "Standard_D2_v2"
        },
        "agentPoolProfiles": [
            {
                "name": "linuxpool",
                "count": 1,
                "vmSize": "Standard_D2_v2",
                "distro": "aks-ubuntu-16.04",
                "availabilityProfile": "AvailabilitySet",
                "AcceleratedNetworkingEnabled": false
            }
        ],
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": "ssh-rsa XXX"
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "ddc55e30-9b0d-4131-be0a-3b45365a84c6",
            "secret": "XXX"
        }
    }
}
####

**Expected behavior**
Expect successful deployment of K8s cluster on Azure Stack.

**AKS Engine version**
~/akse » aks-engine version
Version: v0.39.2
GitCommit: ceec59885
GitTreeState: clean

**Kubernetes version**
13.9

**Additional context**
- Verified that SPN has been assigned contributor role.
- Able to successfully authenticate to the stack using "az login --service-principal"
[cloud-init-output.log](https://github.com/Azure/aks-engine/files/3691563/cloud-init-output.log)
[cluster-provision.log](https://github.com/Azure/aks-engine/files/3691567/cluster-provision.log)

**Comment by blunozr** [comment]
Command used to initiate deployment:

~/akse » aks-engine deploy \
--azure-env AzureStackCloud \
--location ssccentral \
--resource-group aksengine-dev-rg \
--api-model ./kubernetes-azurestack.json \
--output-directory akse-dev-rg \
--client-id ddc55e30-9b0d-4131-be0a-3b45365a84c6 \
--client-secret XXXX \
--subscription-id b903a034-f7e0-480f-9989-ff54fd4ff578 \
--identity-system adfs --force-overwrite

**Comment by jadarsie** [comment]
@blunozr, I think this was fixed by #2054

**Comment by jadarsie** [comment]
Please re-open if that's not the case
