### ISSUE TITLE
Calico FELIX_LOGSEVERITYSCREEN customization

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/aks-engine#2111]
**Describe the request**

When using calico network plugin, I would like to be able to configure `FELIX_LOGSEVERITYSCREEN`, and other parameters. 

Currently, there are some calico configurations that are hardcoded as env variables. env variables are the first configuration option for calico, so you can't configure these parameters using `FelixGlobalConfiguration` object. 

**Explain why AKS Engine needs it**

Improves network plugin customization. In my case, I want to change `FELIX_LOGSEVERITYSCREEN` from default `info` level to `warning`, because `info` level is too verbose. 

**Describe the solution you'd like**

Remove the hardcoded value from env variables to allow configure parameters using `FelixGlobalConfiguration`.  Also I'm open to other solutions/workarounds. 

**Describe alternatives you've considered**

I have tried to configure log level via `kubectl set env` after cluster creation, but `kube-addon-manager` reconfigures the `calico-node` daemonset. So as workaround, I'm trying to modify `/etc/kubernetes/addons/calico-daemonset.yaml` using a script in an extension, but it's a tricky solution that I would like to avoid.  

**Additional context**

**Comment by devigned** [comment]
Thank you for opening this issue. Seems like a popular enhancement. 

@craiglpeters, what do you think about this one?

**Comment by craiglpeters** [comment]
I think it makes a ton of sense. It would be great if a community member could contribute. Is it a straight forward change? Could we mark it as 'good first issue'?

**Comment by axel-grossmann-sap** [comment]
Please re-open the issue. We're facing the same problem (config map settings not applied) and need to limit the verbose calico logs. 
Thank you!
