### ISSUE TITLE
Enable moby 3.0.7

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2113]
`moby-engine` and `moby-cli` versions 3.0.7 have been published at the standard apt repos:

- `https://packages.microsoft.com/config/ubuntu/16.04/prod.list`
- `https://packages.microsoft.com/config/ubuntu/18.04/prod.list`

**Comment by cpuguy83** [comment]
That works, but there's also a multi-arch repo as well which I'd like to migrate people to: https://packages.microsoft.com/config/ubuntu/18.04/multiarch/prod.list

Also note there's debian packages that you can install which pulls in prod.list.

https://packages.microsoft.com/config/ubuntu/18.04/multiarch/prod.list
https://packages.microsoft.com/config/ubuntu/18.04/multiarch/packages-microsoft-prod.deb

**Comment by jackfrancis** [comment]
As the simplest iterative change forward, could we just replace instances of:

- `https://packages.microsoft.com/config/ubuntu/${UBUNTU_RELEASE}`

with:

- `https://packages.microsoft.com/config/ubuntu/18.04/multiarch`

from this func?

https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/artifacts/cse_install.sh#L111

**Comment by cpuguy83** [comment]
Yes, but seems like you might want to keep `${UBUNTU_RELEASE}`
The newer repos support 16.04 as well.
