### ISSUE TITLE
Enable users to kick off E2E runs against PRs

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#214]
@sylr in particular would like to be able to do this in order to accelerate the velocity of his contributions

**Comment by CecileRobertMichon** [comment]
In the meantime, anyone can run E2E locally using:
 ```CLUSTER_DEFINITION=examples/kubernetes.json SUBSCRIPTION_ID="<YOUR_SUB_ID>" CLIENT_ID="<YOUR_CLIENT_ID" CLIENT_SECRET="<YOUR_CLIENT_SECRET>" TENANT_ID="<YOUR_TENANT_ID>" LOCATION=<REGION> CLEANUP_ON_EXIT=true make test-kubernetes```

Your can change the cluster definition for testing different configurations.

**Comment by CecileRobertMichon** [comment]
This is going to be indirectly "fixed" by https://github.com/Azure/aks-engine/pull/135 when we move to Azure DevOps for PR E2E

**Comment by CecileRobertMichon** [comment]
fixed in #135
