### ISSUE TITLE
Erro reading json file

### ISSUE THREAD

**Issue by ales-blaze** [Azure/aks-engine#2149]
**Describe the bug**
when tried to deploy a k8s cluster using aks-engine , i got this output
```
INFO[0000] new api model file has been generated during merge: /tmp/mergedApiModel552566077 
Error: loading API model: error parsing the api model: Unknown JSON tag client
```

**Steps To Reproduce**
run aks-engine deploy command with specified --api-model tag (i have used examples/kubernetes.json as my api model)

**Expected behavior**
output must be these things ,Azure Resource Manager (ARM) templates, SSH keys, and a kubeconfig file
**AKS Engine version**
Version: v0.41.4
**Kubernetes version**
Kubernetes version:1.13.10

**Additional context**
i have set my client id with value in app id 
and i have set my client secrets with value of password 
i have taken these values from generated service principal

**Comment by devigned** [comment]
That shouldn't be happening. Let's get this resolved.

I'm a little unclear as to how you are executing the deploy command. Please provide the exact command you are issuing with deploy with any sensitive input redacted.

For example: 
```bash
aks-engine deploy -m ./examples/kubernetes.json \ 
  --client-id $CLIENT_ID --client-secret $CLIENT_SECRET \
  -s $SUBSCRIPTION_ID -l southcentralus -p test2054
```
