### ISSUE TITLE
aks-enginer generate not updating linuxprofile ssh key 

### ISSUE THREAD

**Issue by Ashish-009** [Azure/aks-engine#2181]
**aks-engine not  updating linuxprofile ssh publickeys keydata**

**Steps To Reproduce**
If i run this command aks-enginer generate runs fine
aks-engine generate --set windowsProfile.adminPassword=$WINDOWS_SSH_ADMIN_PASSWORD,servicePrincipalProfile.secret=$CLUSTER_SP_SECRET,linuxProfile.ssh.publicKeys[0].keyData=$sshKey  $clusterDefinition

However when i try to update keydata for path 'linxuprofile.ssh.publicKeys[0].keyData' (highlighted in bold) in clusterdefinition.json. it fails saying that too many arguments.(see snapshot below)
aks-engine generate --set windowsProfile.adminPassword=$WINDOWS_SSH_ADMIN_PASSWORD,servicePrincipalProfile.secret=$CLUSTER_SP_SECRET,**linuxProfile.ssh.publicKeys[0].keyData=$sshKey**  $clusterDefinition

**Expected behavior**
should update the value
**AKS Engine version**
0.41.4
**Kubernetes version**

**Error output**
![image](https://user-images.githubusercontent.com/42860787/67185424-a7f6e700-f39a-11e9-969f-914c850169bf.png)

**Comment by CecileRobertMichon** [comment]
@Ashish-009 I might be missing something but I can't see the difference between the first and the second command...

**Comment by Ashish-009** [comment]
@CecileRobertMichon  the first command does not have this part linuxProfile.ssh.publicKeys[0].keyData=$sshKey
