### ISSUE TITLE
Upgrade process with VMSS issues

### ISSUE THREAD

**Issue by sylr** [Azure/aks-engine#2182]
I'm deep down in the upgrade process and I've uncovered some problems.

I'm in a process of upgrading a 1.13.5 cluster.

As you may now, before 1.13.6 kubernetes cloudprovider was using Azure APIs which would remove all nodes and recreate them when a change in the VMSS properties is applied.

So when the aks-engine upgrade process does what it is supposed to do, it creates an outage as all nodes are deleted and recreated by kubernetes.

What I did not understand is why the VMSS objects are modified when the process is still doing the upgrade of the master nodes.

After some digging I found the following things.

# NormalizeResourcesForK8sMasterUpgrade(...)

https://github.com/Azure/aks-engine/blob/aa114c691bff3122acc5c922b242a699cf6b8e59/pkg/engine/transform/transform.go#L326-L455

- Does not remove `virtualMachineScaleSets` objects from the template, **so VMSS are upgraded as soon as the FIRST master is recreated**.
- Does not remove `loadBalancer` objects from the template, custom load balancing rules are deleted (especially the one that allows outbound UDP connections when master VMs are linked to a Standard Load Balancers).
- Does not remove `networkSecurityGroups` objects from the template, all rules created manually or by kubernetes for services are removed until kubernetes reapplies them.

Removing those objects from the template would imply to remove the `dependsOn` references of those objects in the remaining objects.

# NormalizeResourcesForK8sAgentUpgrade(...)

https://github.com/Azure/aks-engine/blob/aa114c691bff3122acc5c922b242a699cf6b8e59/pkg/engine/transform/transform.go#L457-L472

- This, in a VMSS agent context, **should only output a template with the `virtualMachineScaleSets` object being updated**. It currently generates a template with almost all master and agent resources.

Regards.

**Comment by sylr** [comment]
Current flow:
- Master VM 1 UPGRADE
   -  Delete master VM 1
   - Recreate master VM 1, reapply `loadBalancer` and `networkSecurityGroup` properties and upgrade all VMSS
- Master VM 2 UPGRADE
   - Delete master VM 2
   - Recreate master VM 2, reapply `loadBalancer` and `networkSecurityGroup` properties and upgrade all VMSS
- Master VM 3 UPGRADE
   - Delete master VM 3
   - Recreate master VM 3, reapply `loadBalancer` and `networkSecurityGroup` properties and upgrade all VMSS
- VMSS N UPGRADE
   - Reapply all template objects, does nothing to VMSS as they were already upgraded when upgrading Master VM 1
- VMSS N+1 UPGRADE
   - Reapply all template objects, does nothing to VMSS as they were already upgraded when upgrading Master VM 1
- VMSS N+x UPGRADE
   - Reapply all template objects, does nothing to VMSS as they were already upgraded when upgrading Master VM 1

Expected Flow:

- Master VM 1 UPGRADE
   - Delete master VM 1
   - Recreate VM 1 only
- Master VM 2 UPGRADE
   - Delete master VM 2
   - Recreate VM 2 only
- Master VM 3 UPGRADE
   - Delete master VM 3
   - Recreate VM 3 only
- VMSS N UPGRADE
   - Upgrade VMSS N only
- VMSS N+1 UPGRADE
   - Upgrade VMSS N+1 only
- VMSS N+x UPGRADE
   - Upgrade VMSS N+X only

Leave NSG, Load Balancers ... etc alone in the upgrade process.

**Comment by sylr** [comment]
@CecileRobertMichon, @jackfrancis @devigned could I have your thoughts about this ?

Thanks.

**Comment by CecileRobertMichon** [comment]
@sylr thanks for the ping. I agree with you on this:
> This, in a VMSS agent context, should only output a template with the virtualMachineScaleSets object being updated. It currently generates a template with almost all master and agent resources.

The upgrade code was written a while ago and has slowly evolved over time but as it's such a critical piece of the code that was also used by ACS and now AKS we historically tried to minimize the changes. I think what you found is totally valid and a de-optimization in the implementation which I would love to see fixed though, it would just require a non-trivial amount of work and extensive testing to make sure we don't regress upgrade functionality.
