### ISSUE TITLE
Validity is too long for SSL cert on the API server endpoint

### ISSUE THREAD

**Issue by yixwang** [Azure/aks-engine#2186]
**Describe the bug**
Currently it seems that the validity of the SSL cert used for the API server endpoint is configured to be 30 years. We are getting flagged on sslscanner.trafficmanager.net because of the validity is too long. According to https://microsoft.sharepoint.com/teams/CESecEngineering/SiteAssets/xca/Home/CertificateAnalyzer_policies_Explained.pdf, the requirement is to have a max 2 years of validity. 

**Steps To Reproduce**
Deploy the cluster and scan the master url, https://(master_prefix).(location).cloudapp.azure.com with SSL scanner: https://sslscanner.trafficmanager.net/

**Expected behavior**
Pass the test or provide a way to allow us configure it. According to https://github.com/Azure/aks-engine/blob/da5ad7c157c0e172703fff00f834cf7c9e3f28c7/docs/topics/clusterdefinitions.md, the apiserver.crt and key are not configurable. 

**AKS Engine version**
0.41.4

**Kubernetes version**
1.15.4

**Additional context**
![image](https://user-images.githubusercontent.com/47333969/67231336-fdabad80-f3f3-11e9-82fd-6af795137992.png)

**Comment by CecileRobertMichon** [comment]
You can pass in your own certificates with the desired validity using the `certificateProfile`, using [key vault references](https://github.com/Azure/aks-engine/blob/master/examples/keyvault-params/README.md#L7) or plain text values.

**Comment by yixwang** [comment]
@CecileRobertMichon The problem with creating our own apiserver.crt is that, currently these DNS are added as SAN to the apiserver.crt, which I assume these are needed for internal communication to apiservice within the cluster. So we need to do the same thing when creating our own cert but as soon as aks-engine change the implementation, it will break. I think it's much cleaner for aks-engine to make the expiry time on the apiserver.crt configurable as it's a publicly exposed endpoint.

**Comment by CecileRobertMichon** [comment]
@yixwang we would gladly accept a PR to make the validity configurable. FWIW, the FQDNs have not been changed [for 3 years](https://github.com/Azure/aks-engine/commit/3c352ecb3682f9c3455d04f394a980be09d439db#diff-a684d9601dd259c9e06a504247fac01bR28) (basically since aks-engine exists) so I don't expect that part of the code to change, using your own cert seems like a valid long term option.
