### ISSUE TITLE
Custom data exceeds max length with multiple addons and network policies

### ISSUE THREAD

**Issue by sozercan** [Azure/aks-engine#2205]
**Describe the bug**
When too many addons, network policies are enabled, custom data size hits ARM length limitation and deployment fails with `Custom data in OSProfile must be in Base64 encoding and with a maximum length of 87380 character` error.

Related issues:
https://github.com/Azure/aks-engine/issues/1260
https://github.com/Azure/aks-engine/issues/1663

As Jack suggested at https://github.com/Azure/aks-engine/pull/2173#discussion_r335754411
It might be a good idea to move away from delivering the entire k8s app layer spec (i.e., all these yaml files) via cloud-init.

**Steps To Reproduce**
Deploy multiple addons with large addon yaml files like azure-policy, cluster-autoscaler, aad-pod-identity, aci-connector and calico network policy.

**Expected behavior**
Successful AKS-Engine cluster with all specified addons and network policies running.

**AKS Engine version**
0.42.2

**Comment by chreichert** [comment]
Is there a way to work around this issue?
It prevents us from upgrading our cluster at the moment, as the same error occurs during aks-engine upgrade for a private cluster with 3 master nodes, 4 vmss agent pools and networkpolicy calico enabled.
