### ISSUE TITLE
Failure when processing extension 'vmssCSE'. Exit status=50

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/aks-engine#2212]
**Describe the bug**

We have problems to deploy with aks-engine because some agent pools can't access to internet during bootstrapping. This is the error:

`
Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=50\\n[stdout]\\nThu Oct 24 14:18:01 UTC 2019,k8s-genm-21270049-vmss000000\\n\\n[stderr]\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"}]
`

Checking documentation and code, I have seen that node executes some `nc` command to check connectivity with some docker registries. If these commands fail, error 50 is returned.  Also, I have connected manually to a failed node and it had connectivity issues. 

I don't know if it's an aks-engine issue or an Azure cloud issue. Are you having similar issues?

**Steps To Reproduce**
Execute `aks-engine deploy` command. 

**Expected behavior**
Correct deployment. 

**AKS Engine version**
0.42.2

**Kubernetes version**
1.14.7

**Additional context**

**Comment by sukhong** [comment]
We are also occasionally experiencing this issue. But usually retry succeeds, but annoying sometimes.

**Comment by nidiculageorge** [comment]
![image](https://user-images.githubusercontent.com/43850474/81962514-73e25c80-9631-11ea-9361-e6833c7fbad8.png)
We have disabled outbound connectivity to internet in NSG for the aks agent pool. Seems this occurred because of that
