### ISSUE TITLE
MountVolume.WaitForAttach error

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2221]
With a `StatefulSet` spec like this, not all replicas are being fulfilled:

```
$ cat statefulset.yaml 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  podManagementPolicy: "Parallel"
  replicas: 50
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-standard"
      resources:
        requests:
          storage: 1Gi
```

On a cluster w/ 50 VMSS nodes:

```
$ kubectl get nodes | grep 'Ready' | grep -v 'k8s-master-' | wc -l
      50
```

I see two pods unable to mount volumes:

```
Events:
  Type     Reason       Age                    From                                         Message
  ----     ------       ----                   ----                                         -------
  Warning  FailedMount  9m1s (x357 over 13h)   kubelet, k8s-agentpool1-30952931-vmss00000r  Unable to mount volumes for pod "web-30_default(cc7008d7-f6cb-11e9-a3d8-000d3afe2e57)": timeout expired waiting for volumes to attach or mount for pod "default"/"web-30". list of unmounted volumes=[www]. list of unattached volumes=[www default-token-p82ft]
  Warning  FailedMount  3m38s (x390 over 13h)  kubelet, k8s-agentpool1-30952931-vmss00000r  MountVolume.WaitForAttach failed for volume "pvc-32fcf0dc-f6b1-11e9-a3d8-000d3afe2e57" : azureDisk - WaitForAttach failed within timeout node (k8s-agentpool1-30952931-vmss00000r) diskId:(kubernetes-westus2-55996-dynamic-pvc-32fcf0dc-f6b1-11e9-a3d8-000d3afe2e57) lun:(1)
```

**Comment by jackfrancis** [comment]
A known-working remediation

From the node I can see which VMSS instance this is:

```
$ k describe node k8s-agentpool1-30952931-vmss00000r | grep ProviderID
ProviderID:                  azure:///subscriptions/aa3d3369-e814-4495-899d-d31e8d7d09ce/resourceGroups/kubernetes-westus2-55996/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-agentpool1-30952931-vmss/virtualMachines/27
```

Re-image the vmss instance:

```
$ az vmss reimage --resource-group kubernetes-westus2-55996 --name k8s-agentpool1-30952931-vmss --instance-id 27
```

This seems to a pathology between VMSS<--->disk

**Comment by andyzhangx** [comment]
@jackfrancis should be disk issue on vmss, I also hit that issue before, when disk is attached to one node, sometimes disk with that specific lun could not be detected inside vmss instance within 2min.
k8s will retry WaitForAttach process after that, it would succeed finally, right?

**Comment by joekottke** [comment]
I'm seeing this issue as well.  I can see the the volume attached to the instance (by verifying with an `sudo fdisk -l /dev/sdc`, but the volume never mounts within the container.

**Comment by andyzhangx** [comment]
> I'm seeing this issue as well. I can see the the volume attached to the instance (by verifying with an `sudo fdisk -l /dev/sdc`, but the volume never mounts within the container.

@joekottke
could you also run `ll /dev/disk/azure/scsi1/`, there should be a few symlink files under that dir, sometimes that symlink files won't show up one minute or two, k8s would retry, and finally would work:
```
lun0 -> ../../../sdc
```

**Comment by cdelacruzpinto** [comment]
2020 and hitting the same issue here, so please don't mark it as stale :-)

**Comment by andyzhangx** [comment]
> 2020 and hitting the same issue here, so please don't mark it as stale :-)

@cdelacruzpinto pls provide detailed error message, k8s version, vm type,
We have already fixed an issue [azure disk could not mounted on Standard_DC4s/DC2s instances](https://github.com/kubernetes/kubernetes/pull/86612)

**Comment by cdelacruzpinto** [comment]
Now that is what I call first class support ;) We are using Standard_DS2_v2 instances. K8s version: 1.14.8 

` 
  Warning  FailedScheduling        4m8s (x4 over 4m21s)  default-scheduler                           pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled               3m59s                 default-scheduler                           Successfully assigned styx7/gdb-5b7d968d9b-nch2v to aks-nodepool1-42586154-vmss000000
  Normal   SuccessfulAttachVolume  3m6s                  attachdetach-controller                     AttachVolume.Attach succeeded for volume "pvc-17201990-6509-11ea-a5d7-9ebbc8e87a31"
  Warning  FailedMount             116s                  kubelet, aks-nodepool1-42586154-vmss000000  Unable to mount volumes for pod "gdb-5b7d968d9b-nch2v_styx7(1827d4e9-6509-11ea-a5d7-9ebbc8e87a31)": timeout expired waiting for volumes to attach or mount for pod "styx7"/"gdb-5b7d968d9b-nch2v". list of unmounted volumes=[gdb-volume]. list of unattached volumes=[gdb-volume default-token-n246q]
  Warning  FailedMount             47s (x9 over 2m55s)   kubelet, aks-nodepool1-42586154-vmss000000  MountVolume.WaitForAttach failed for volume "pvc-17201990-6509-11ea-a5d7-9ebbc8e87a31" : Cannot find Lun for disk kubernetes-dynamic-pvc-17201990-6509-11ea-a5d7-9ebbc8e87a31 
 
`

**Comment by andyzhangx** [comment]
sometimes disk detection inside vm is slow, so sometimes you may hit such issue, to mitigate this issue, we already have some wait loop in the new fix: https://github.com/kubernetes/kubernetes/pull/88158
1.15.9,1.16.8,1.17.4 would have this fix.

**Comment by andyzhangx** [comment]
so even you get `Cannot find Lun` error, after some retry by k8s, it would work, right?

**Comment by cdelacruzpinto** [comment]
...after one hour in this case, yes.

`Events:
  Type     Reason       Age                From                                        Message
  ----     ------       ----               ----                                        -------
  Warning  FailedMount  59m (x5 over 68m)  kubelet, aks-nodepool1-42586154-vmss000001  Unable to mount volumes for pod "rdb-5986884645-c2qhl_blah(6b272611-6514-11ea-a5d7-9ebbc8e87a31)": timeout expired waiting for volumes to attach or mount for pod "blah"/"rdb-5986884645-c2qhl". list of unmounted volumes=[postgres-volume]. list of unattached volumes=[postgres-volume default-token-n246q]
  Normal   Pulling      58m                kubelet, aks-nodepool1-42586154-vmss000001  Pulling image "postgres:latest"
  Normal   Pulled       58m                kubelet, aks-nodepool1-42586154-vmss000001  Successfully pulled image "postgres:latest"
  Normal   Created      58m                kubelet, aks-nodepool1-42586154-vmss000001  Created container postgres
  Normal   Started      58m                kubelet, aks-nodepool1-42586154-vmss000001  Started container postgres
`

**Comment by andyzhangx** [comment]
o, this is an issue in 1.14.x, fixed in 1.15.x

**Comment by andyzhangx** [comment]
same as this issue: https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#24-attach-disk-costs-10min

**Comment by cdelacruzpinto** [comment]
Thank you very much for your help @andyzhangx . Will update the cluster to the recommended version.
