### ISSUE TITLE
Configurable SGX Driver version, or location of driver download

### ISSUE THREAD

**Issue by joekottke** [Azure/aks-engine#2229]
**Describe the request**
I would like to be able to specify either the version of (or download location of) the Intel SGX driver for SGX-configured agent pools.

**Explain why AKS Engine needs it**
We are running SGX workloads in our cluster, and while we are working towards running with the latest minor version of the SGX driver, I would like to be able to specify an older (yet still supported) version of the driver.  We are currently using version 2.5 of SGX, and the SGX version that aks-engine installs is hard-coded and does not suit our needs.

**Describe the solution you'd like**
A configurable parameter that either allows for driver version choice, (2.5, 2.6. etc) or a URL to a specific driver installer.

**Describe alternatives you've considered**
Currently we are modifying the driver download URL manually, as specified in `installSGXDrivers()` in the file `parts/k8s/cloud-init/artifacts/cse_install.sh`.

**Additional context**
None

**Comment by jackfrancis** [comment]
We can use the CSE env vars `CONTAINERD_DOWNLOAD_URL_BASE` and `CONTAINERD_VERSION` as a reference for how this can be done.

**Comment by jackfrancis** [comment]
@joekottke is the version you want to install hosted at the same location that hosts this (e.g. 18.04) artifact?:

- https://download.01.org/intel-sgx/dcap-1.2/linux/dcap_installers/ubuntuServer18.04/sgx_linux_x64_driver_1.12_c110012.bin

**Comment by joekottke** [comment]
Hey there, sorry for being asleep at the wheel on this one.  The drivers we are installing are the EPID version of the driver, not the DCAP version.  Current version we are installing is now located here: https://download.01.org/intel-sgx/sgx-linux/2.9/distro/ubuntu18.04-server/
