### ISSUE TITLE
Support associating existing user assigned identity to nodes

### ISSUE THREAD

**Issue by norshtein** [Azure/aks-engine#2233]
**Describe the request**
Support associating existing user assigned identity to nodes. Currently AKS-Engine only supports creating a new one when creating the cluster.
**Explain why AKS Engine needs it**
We're working on switching all addons in AKS to use user assigned identity to authenticate, and AKS RP will create one user assigned identity for each addon. After this, we need to associate the identity to every agent node in the cluster, it would be very convenient if AKS-Engine supports associating existing identity to agent nodes.
**Describe the solution you'd like**
A new struct containing the resource id of existing user assigned identities will be added to “ContainerService” and specified identities will be associated to every (agent) node in generated template. 
**Describe alternatives you've considered**
Associating identities can also be done by AKS RP, but this way has a big shortcoming: when upgrading the cluster, for a newly created VM, identities will not be associated with it. So if addon pod is scheduled to a newly created VM, it can't work correctly for a period of time.
**Additional context**

**Comment by yangl900** [comment]
I suggest we keep the array of managed identity resource ID in agent pool profiles, so that it is possible each agent pool have different identity assigned. It will be more flexible and future proof.

**Comment by ritazh** [comment]
So basically check if `userAssignedID` is provided, if not, then call `userAssignedID := createUserAssignedIdentities()`?
https://github.com/Azure/aks-engine/blob/master/pkg/engine/armresources.go#L38-L39

**Comment by ritazh** [comment]
cc @kkmsft

**Comment by norshtein** [comment]
> So basically check if `userAssignedID` is provided, if not, then call `userAssignedID := createUserAssignedIdentities()`?
> https://github.com/Azure/aks-engine/blob/master/pkg/engine/armresources.go#L38-L39

Hi Rita, that's two different topic:
- `userAssignedID` records the resource name of the user assigned identity that will be used by **kubelet**. This identity is created by AKS-Engine(via generated ARM template), and this proposal has little relationship with it.
- Each addon in AKS will get one dedicated user assigned identity created by **AKS RP**(for fine-grained access control), the identity is different from the identity kubelet uses. Before AKS RP invokes AKS-Engine, the identity is already created, AKS RP will pass the resourceID of the identity to AKS-Engine and expect AKS-Engine to associate the existing identity to every agent node in generated ARM template. So basically we need a struct in AKS-Engine's API to receive identities' resourceID.

**Comment by norshtein** [comment]
> I suggest we keep the array of managed identity resource ID in agent pool profiles, so that it is possible each agent pool have different identity assigned. It will be more flexible and future proof.

We need to let every addon knows which identity is assigned to it. So I'm thinking about add identity information to `AddonProfile`, then addons and customers can see each addon's identity pretty straightforward. Adding it in `AgentPoolProfile` is also OK, we can add additional property such as `BelongsTo` to record the identity's owner, it's a little bit more complicated but it makes it possible to associate different identity to different agent pool. One thing I'm not sure is when will we associate different identity to different agent pool? I can't imagine a scenario need this.

**Comment by norshtein** [comment]
I've drafted a [PR](https://github.com/Azure/aks-engine/pull/2238) to implement the feature,  @jackfrancis @ritazh @yangl900 could you please have a review?

**Comment by kkmsft** [comment]
Current implementation of aks-engine has the facility to create userMSI clusters, ie. user assigned MSI as cluster identity. In such clusters the user identity is used by cloud provider and other k8s components to access cloud resources using this identity. In my understanding, the requirement here is to add a set of pre-specified user identities to the template, which is different from the current facility.
