### ISSUE TITLE
Enable configuration of disk caching type

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2249]
Currently we statically set the disk caching type to `"ReadWrite"` for all OS disks, and `"ReadOnly"` for all data disks.

The azure-sdk-for-go defines three caching types:

```
const (
	// CachingTypesNone ...
	CachingTypesNone CachingTypes = "None"
	// CachingTypesReadOnly ...
	CachingTypesReadOnly CachingTypes = "ReadOnly"
	// CachingTypesReadWrite ...
	CachingTypesReadWrite CachingTypes = "ReadWrite"
)
```

Let's enable user-configurable caching types (validate against the three sane values above) per-masterProfile, and per-agentPoolProfile, for both OS disks and data disks.

**Comment by craiglpeters** [comment]
Is this really a priority?

**Comment by PacoGuy** [comment]
From my standpoint it is a priority considering we have to modify the apimodel to accomplish this right now.

I'd like to avoid a hack like that if at all possible and our workload requires this change to the disk caching.
