### ISSUE TITLE
feat: enable configurable image source

### ISSUE THREAD

**Issue by craiglpeters** [Azure/aks-engine#2251]
**Describe the request**
The repository for Kubernetes and related images is being moved from ACR to mcr.microsoft.com. AKS Engine needs the ability to be configured to pull from the old or the new location to enable testing of the new images as an optional configuration, and then later make the new location the default. The configuration needs to apply to both the images packaged into VHDs and to the CSE.

**Explain why AKS Engine needs it**
AKS and other customers of AKS Engine need to be able to consume the new images from MCR

**Describe the solution you'd like**
- work w/ aks-engine team to validate that image changes are applied to VHD CI spec
- do not merge changes to AKS until above changes have been applied to a new VHD publication iteration, and the resultant VHD is being referenced in the RP @ HEAD

**Describe alternatives you've considered**

**Additional context**

**Comment by thomas1206** [comment]
Here is the image list currently used by AKS:

rp: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=%2Fpkg%2Fmicrosoft.com%2Fcommon%2Fk8sversions%2Fk8sversions.go&version=GBmaster&line=120&lineStyle=plain&lineEnd=491&lineStartColumn=1&lineEndColumn=1

overlay: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-overlaymgr?path=%2Fpkg%2Fhelmctlr%2Fhelmvalues%2Fconst.go&version=GBguwe%2Fexpose-diagnostic-settings&line=33&lineStyle=plain&lineEnd=95&lineStartColumn=1&lineEndColumn=1

**Comment by jackfrancis** [comment]
Status update: a stream of addons refactor PRs is landing in master right now, which will contribute to cleaning up the underlying surface area for custom images.

**Comment by jackfrancis** [comment]
See #2408 for the design doc that will guide this work
