### ISSUE TITLE
VMSS Failed with Provisioning of VM extension 'OmsAgentForLinux' has timed out

### ISSUE THREAD

**Issue by sylus** [Azure/aks-engine#2254]
**Describe the bug**

Provisioning of VM extension 'OmsAgentForLinux' has timed out. Extension installation may be taking too long, or extension status could not be obtained. Oddly all of our instances are in the success state. Should also note two different clusters have this issue which occurred over the weekend, and there is nothing we can do to mitigate since instances are all green and did reimage them.

**Steps To Reproduce**

1) Launch a cluster
2) Launch a few workloads and then delete them

**Expected behavior**

The VMSS actually works

**AKS Engine version**

v0.42.2

**Kubernetes version**

v1.15.5

**Additional context**

This would be the 3rd issue with VMSS in the past 2-3 weeks. Really starting to get concerned about this service as we haven't had a reliable env to work on for all of our teams. Will mention that our cluster was perfectly healthy a few days ago and came back to it in a failed state. 

Is also likely related to: https://github.com/Azure/aks-engine/issues/2221

**Comment by sylus** [comment]
@jackfrancis @CecileRobertMichon

**Comment by zachomedia** [comment]
This is the full error message:

```
Handler 'Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux' has reported failure for VM Extension 'OmsAgentForLinux' with terminal error code '1007' and error message: '[ExtensionOperationError] Non-zero exit code: 60, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.0.217.0/omsagent.py -install [stdout] 2019/11/04 17:02:57 [stderr] Running scope as unit: Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux_1.0.217.0_fbf9ec70-0318-4967-8691-74430a4185c7.scope '
```

**Comment by zachomedia** [comment]
At /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/extension.log

I see this in the logs:

```
2019/11/04 17:18:55 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.0.217.0] Command returned an error.
2019/11/04 17:18:55 ERROR:---stdout---
2019/11/04 17:18:55 ERROR:Checking for ctypes python module ...
2019/11/04 17:18:55 ERROR:Extracting...
2019/11/04 17:18:55 ERROR:Updating OMS agent ...
2019/11/04 17:18:55 ERROR:----- Checking package: omi (omi-1.0.8-6.universal.x64) -----
2019/11/04 17:18:55 ERROR:Error: This system does not have a supported version of OpenSSL installed.
2019/11/04 17:18:55 ERROR:This system's OpenSSL version: 1.1.1
2019/11/04 17:18:55 ERROR:Supported versions: 0.9.8*, 1.0.*
2019/11/04 17:18:55 ERROR:
2019/11/04 17:18:55 ERROR:---errout---
2019/11/04 17:18:55 ERROR:
2019/11/04 17:18:55 ERROR:
2019/11/04 17:18:55 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.0.217.0] Install,failed,60,Command returned an error.
2019/11/04 17:18:55 ---stdout---
2019/11/04 17:18:55 Checking for ctypes python module ...
2019/11/04 17:18:55 Extracting...
2019/11/04 17:18:55 Updating OMS agent ...
2019/11/04 17:18:55 ----- Checking package: omi (omi-1.0.8-6.universal.x64) -----
2019/11/04 17:18:55 Error: This system does not have a supported version of OpenSSL installed.
2019/11/04 17:18:55 This system's OpenSSL version: 1.1.1
2019/11/04 17:18:55 Supported versions: 0.9.8*, 1.0.*
2019/11/04 17:18:55
2019/11/04 17:18:55 ---errout---
```

**Comment by jackfrancis** [comment]
@ganga1980 @rashmichandrashekar does the above error ring a bell?

**Comment by sylus** [comment]
So this was another developer forcing policy on us and installed OMSAgentForLinux on the Scaleset without informing us. We still have the larger problem in https://github.com/Azure/aks-engine/issues/2221 being looked at but can close this. So closing :D thx!

**Comment by ganga1980** [comment]
> o this was another developer forcing policy on us and installed OMSAgentForLinux on the Scaleset without informing us. We still have the larger problem in #2221 being looked at but can close this. So closing :D thx!



> @ganga1980 @rashmichandrashekar does the above error ring a bell?
Hi, @jackfrancis ,  @sylus  is using VM extension not the container monitoring addon . The VM extension we dont own and probably @rashmichandrashekar might know who owns this.

Hi, @sylus , We have container monitoring addon support for the AKS-Engine. Did you aware of this   feature 
https://github.com/Azure/aks-engine/blob/master/docs/tutorials/containermonitoringaddon.md ? Please review and let us know if you have any questions and need help on using this feature.

**Comment by rashmichandrashekar** [comment]
@sylus @jackfrancis - This might be because the OS version on the vm is older than what omsagent is using.
What os and version is running on the vmss?

**Comment by zachomedia** [comment]
@rashmichandrashekar In this case we are using the Ubuntu 18.04 AKS image.
