### ISSUE TITLE
MCR image reference migration

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2263]
TODO:

- manually audit VHD CI spec
- migrate mcr.microsoft.com/k8s/core/pause to mcr.microsoft.com/oss/kubernetes/pause
- tiller no longer needs its own image base value
- virtual-kubelet
- oms
- Azure CNI networkmonitor
- nvidia no longer needs its own image base value
- China cloud follow-up

**Comment by craiglpeters** [comment]
@jackfrancis  Is this still pending?

**Comment by jackfrancis** [comment]
done!
