### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by dmlemos** [Azure/aks-engine#227]
**Is this a request for help?**:
NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

Any plans for an [homebrew](https://brew.sh/) formula to install `acs-engine`?

**Comment by bacongobbler** [comment]
FYI, I've got a personal tap set up over here: https://github.com/bacongobbler/homebrew-aks-engine

Usage: `brew install bacongobbler/aks-engine/aks-engine`

We should see what we can do to get that moved over to the Azure org at some point (when convenient!).

**Comment by mboersma** [comment]
I'll set up the Azure repo for this and update it for more current releases. Thanks @bacongobbler!

**Comment by mboersma** [comment]
@dmlemos you can `brew install Azure/aks-engine/aks-engine` now (finally!).
