### ISSUE TITLE
Need no-outbound connectivity test for Windows

### ISSUE THREAD

**Issue by marosset** [Azure/aks-engine#2272]
**Describe the request**
We need to enable a no-outbound connectivity test for Windows.

**Explain why AKS Engine needs it**
We now have customers running aks-engine in disconnected environments using Windows nodes and should have automated tests to ensure all required bits are present in the Windows VHD

**Describe the solution you'd like**
Either add windows nodes to existing no-outbound connectivity tests (currently linux only) or create a new test with a configuration with only Windows agent nodes.

**Describe alternatives you've considered**

**Additional context**

**Comment by marosset** [comment]
@rjaini as FYI

**Comment by CecileRobertMichon** [comment]
I think we can reuse the `BlockOutboundInternet` feature flag but not sure how much work is required to make it work with windows pools (might be very little).
