### ISSUE TITLE
multiple agent pools scaleup issue

### ISSUE THREAD

**Issue by satishsudini** [Azure/aks-engine#2278]
**Describe the bug**
Cluster autoscaler is spinning up new nodes with only larger specification when cluster is having multiple agents pools

**Steps To Reproduce**

"agentPoolProfiles": [
  {
    "name": "AGENT_NAME1",
    "count": 1,
    "distro": "ubuntu",
    "vmSize": "Standard_D4s_v3",
    "vnetSubnetId": "SUBNET_ID",
    "availabilityProfile": "AvailabilitySet",
    "storageProfile" : "ManagedDisks",
    "diskSizesGB": *,
    "OSDiskSizeGB": *,
    "acceleratedNetworkingEnabled": true,
    "customVMTags": {
        "key1"             : "value1",
        "key2"        : "value2 ",
        "key3"         : "value3",
      },
    "preProvisionExtension": {
        "name": "prepare_vm_disks",
        "singleOrAll": "All"
    },
    "extensions": [
      {
        "name": "bootstrap",
        "singleOrAll": "All"
      }
   ]
   },
   {
   "agentPoolProfiles": [
     {
       "name": "AGENT_NAME3",
       "count": 1,
       "distro": "ubuntu",
       "vmSize": "Standard_D16s_v3",
       "vnetSubnetId": "SUBNET_ID",
       "availabilityProfile": "AvailabilitySet",
       "storageProfile" : "ManagedDisks",
       "diskSizesGB": *,
       "OSDiskSizeGB": *,
       "acceleratedNetworkingEnabled": true,
       "customVMTags": {
           "key1"             : "value1",
           "key2"        : "value2 ",
           "key3"         : "value3",
         },
       "preProvisionExtension": {
           "name": "prepare_vm_disks",
           "singleOrAll": "All"
       },
       "extensions": [
         {
           "name": "bootstrap",
           "singleOrAll": "All"
         }
      ]
      },

   
**Cluster Autoscaler**  
      containers:
        - command:
            - ./cluster-autoscaler
            - --v=3
            - --logtostderr=true
            - --cloud-provider=azure
            - --skip-nodes-with-local-storage=false
            - --nodes=1:10:agentpool1
            - --nodes=1:10:agentpool2
            - --nodes=1:10:agentpool3

Create cluster with multiple agent pools and test cluster autoscaler. It always spinnup agentpool3 which is higher spec 
agentpool1 - D4s
agentpool1 - D8s
agentpool1 - D16s

**Expected behavior**

Cluster autoscaler should able to trigger the new nodes based on the pods pending state . If only one pod is pending it should trigger small node

**AKS Engine version**

> 0.36

**Kubernetes version**
K8-1.13

**Additional context**

**Comment by CecileRobertMichon** [comment]
@jackfrancis will this be fixed by your ongoing PR?

**Comment by jackfrancis** [comment]
#2138 will provide the full set of cluster-autoscaler configuration, and enable enforcement across all nodepools as desired.

I'm not 100% sure what the exact symptom is here, but I'm confident #2138 is a fully functional cluster-autoscaler implementation that spans linux node pools in aks-engine-created clusters.
