### ISSUE TITLE
PrincipalNotFound caused by MSI propagation issue

### ISSUE THREAD

**Issue by yixwang** [Azure/aks-engine#2280]
**Describe the bug**
We are seeing error “PrincipalNotFound” in role assignment during deployment. The problem is that we are creating VMs with managed identities within a resource group. And the role assignments were to assign these identities with Read role to the resource. Some of them succeeded while some other failed with “PrincipalNotFound” errors, though I checked that all the VM had the system assigned identity enabled

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"PrincipalNotFound\",\r\n \"message\": \"Principal 7a6caeea6166413eb7a4a5249ca7e718 does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\"\r\n }\r\n}"}]}

**Steps To Reproduce**

set "useManagedIdentity": "true" and run deployment. Sometimes the deployment will fail with the error "PrincipalNotFound"

**Expected behavior**
Deployment should succeed

**AKS Engine version**
0.43.0

**Kubernetes version**

**Additional context**
We already talked to the AuthZEng team about this issue. This is caused by a bug on the older api version, "2018-01-01-preview", for "Microsoft.Authorization/roleAssignments", which the aks-engine currently use. The issue is fixed in "2018-09-01-preview" so to fix for the bug is to upgrade the api version and also set principalType to "ServicePrincipal" as suggested by the AuthZEng team.

**Comment by ams0** [comment]
I have the same issue. Currently `useManagedIdentity` feature is broken for me.
