### ISSUE TITLE
API Limit 

### ISSUE THREAD

**Issue by nithinkumarsirigir** [Azure/aks-engine#2295]
** Our kubernetes clusters are having issues in our staging subscription because we are hitting quite a bit of API limits.  Can you increase our API limits for Storage (5x the current limit at least), and Compute (10x the current limit at least).**

**error message which we got **
Here are some example errors we are getting:

The server rejected the request because too many requests have been received for this subscription. (Code: OperationNotAllowed) {"operationgroup":"HighCostGetVMScaleSet3Min","starttime":"2019-11-09T03:41:38.0057434+00:00","endtime":"2019-11-09T03:43:38.0057434+00:00","allowedrequestcount":180,"measuredrequestcount":478} (Code: TooManyRequests, Target: HighCostGetVMScaleSet3Min) {"operationgroup":"HighCostGetVMScaleSet30Min","starttime":"2019-11-09T03:41:38.0057434+00:00","endtime":"2019-11-09T04:05:00+00:00","allowedrequestcount":900,"measuredrequestcount":4805} (Code: TooManyRequests, Target: HighCostGetVMScaleSet30Min)

Requests throttled
Requests to the server are being throttled. Please retry after 1235 seconds.
a few seconds ago

azure - cloud provider rate limited(read) for operation:GetDisk

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits

**Comment by devigned** [comment]
Please creat an Azure support ticket. We are not able to service this request via GitHub: https://azure.microsoft.com/en-us/support/create-ticket/
