### ISSUE TITLE
Remove registry container image reference

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2307]
We pre-download registry right now via public dockerhub. We're doing this while we wait for ACR to be available on Azure Stack.

**Comment by jackfrancis** [comment]
@jadarsie can add more details

**Comment by sukhong** [comment]
@jackfrancis Unfortunately, we have a hard dependency on registry image, to be able to spawn our local container registry in non-Azure Stack air-gapped environments. Can we please keep registry image as part of aks-engine base os image?

**Comment by jackfrancis** [comment]
@sukhong Sure thing, and I've created this PR so we no longer comment in the VHD build script that we want to remove the image:

https://github.com/Azure/aks-engine/pull/2602

@CecileRobertMichon FYI
