### ISSUE TITLE
Upgrade older cluster fails with error "Custom data in OSProfile must be in Base64 encoding and with a maximum length of 87380 characters."

### ISSUE THREAD

**Issue by chreichert** [Azure/aks-engine#2328]
**Describe the bug**
Upgrading an older cluster, that was initially created with ACS-Engine 0.21.2, from 1.14.7 to 1.15.4 stops after deploying second master with error: "Custom data in OSProfile must be in Base64 encoding and with a maximum length of 87380 characters."

Restarting the upgrade again (idempotence?) results in the second master being also deleted and deployment crashing with same error, finally rendering the cluster unusable.

**Steps To Reproduce**

- Set up Cluster with attached apimodel using ACS-Engine 0.21.1
- Upgrade to 1.11.5 using ACS-Engine 0.26.2
- Upgrade to 1.11.6 using AKS-Engine 0.29.1
- Upgrade to 1.12.8 using AKS-Engine 0.36.4
some manual tweaking necessary due to Calico upgrade but finally working fine (first master became ready after adding tolerations to calico-node pod, Agent nodes needed Re-Imaging to become ready)
- Upgrade to 1.13.5 using AKS-Engine 0.36.4
- Upgrade to 1.14.7 using AKS-Engine 0.41.5
Up to here, all upgrades ran more or less without problems.

- Upgrade to 1.15.4 using AKS-Engine 0.41.5 with command:
> aks-engine upgrade --subscription-id <Subscription-ID> --resource-group <RG-Name> --location northeurope --api-model deployment-20191115_131752/arm-deploy/apimodel.json --upgrade-version 1.15.4 --auth-method client_secret --client-id <Client-ID> --client-secret <Client-Secret> --debug

<details><summary>api-model</summary>
 <p>

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10",
      "kubernetesConfig": {
        "addons": [
          {
            "name": "blobfuse-flexvolume",
            "enabled": false
          },
          {
            "name": "smb-flexvolume",
            "enabled": false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled": false
          },
          {
            "name": "cluster-autoscaler",
            "enabled": false,
            "containers": [
              {
                "name": "cluster-autoscaler",
                "cpuRequests": "100m",
                "memoryRequests": "300Mi",
                "cpuLimits": "100m",
                "memoryLimits": "300Mi"
              }
            ],
            "config": {
              "maxNodes": "5",
              "minNodes": "1"
            }
          }
        ],
        "enableRbac": true,
        "privateCluster": {
          "enabled": true
        },
        "networkPlugin": "kubenet",
        "networkPolicy": "calico",
        "cloudProviderBackoff": true,
        "cloudProviderBackoffRetries": 6,
        "cloudProviderBackoffJitter": 1,
        "cloudProviderBackoffDuration": 5,
        "cloudProviderBackoffExponent": 1.5,
        "cloudProviderRateLimit": false,
        "cloudProviderRateLimitQPS": 3,
        "cloudProviderRateLimitBucket": 10
      }
    },
    "aadProfile": {
      "serverAppID": "***",
      "clientAppID": "***",
      "tenantID": "***"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "***",
      "vmSize": "Standard_D2s_v3",
      "OSDiskSizeGB": 128,
      "vnetSubnetId": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Network/virtualNetworks/kubernetes-vnet/subnets/kubernetes-subnet",
      "firstConsecutiveStaticIP": "10.239.255.10",
      "vnetCidr": "10.239.0.0/16"
    },
    "agentPoolProfiles": [
      {
        "name": "dynamic",
        "count": 1,
        "vmSize": "Standard_D16s_v3",
        "OSDiskSizeGB": 128,
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "VirtualMachineScaleSets",
        "vnetSubnetId": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Network/virtualNetworks/kubernetes-vnet/subnets/kubernetes-subnet"
      },
      {
        "name": "graph",
        "count": 1,
        "vmSize": "Standard_E32s_v3",
        "OSDiskSizeGB": 128,
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "VirtualMachineScaleSets",
        "vnetSubnetId": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Network/virtualNetworks/kubernetes-vnet/subnets/kubernetes-subnet"
      },
      {
        "name": "static",
        "count": 1,
        "vmSize": "Standard_D16s_v3",
        "OSDiskSizeGB": 128,
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "VirtualMachineScaleSets",
        "vnetSubnetId": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Network/virtualNetworks/kubernetes-vnet/subnets/kubernetes-subnet"
      },
      {
        "name": "elastic",
        "count": 1,
        "vmSize": "Standard_D32s_v3",
        "OSDiskSizeGB": 128,
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "VirtualMachineScaleSets",
        "vnetSubnetId": "/subscriptions/***/resourceGroups/***/providers/Microsoft.Network/virtualNetworks/kubernetes-vnet/subnets/kubernetes-subnet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "***"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "***",
      "secret": "***"
    }
  }
}
```
</p>
</details>

**Expected behavior**
Cluster can be upgraded to 1.15.4 without any error

**AKS Engine version**
0.41.5

**Kubernetes version**
1.14.7

**Additional context**

**Comment by jackfrancis** [comment]
@chreichert There are changes coming in v0.44.0 (ETA this week) which will:

1. Reduce cloud-init (customData) overhead to improve reliability of cluster configurations being delivered via ARM without hitting data limits
2. An improvement to the upgrade implementation that doesn't slowly delete masters

**Comment by jackfrancis** [comment]
See these commits for reduction to cloud-init:

https://github.com/Azure/aks-engine/pull/2290
https://github.com/Azure/aks-engine/pull/2304
https://github.com/Azure/aks-engine/pull/2313

This PR addresses the upgrade symptom (thanks again @sylr!)

https://github.com/Azure/aks-engine/pull/2275

**Comment by chreichert** [comment]
@jackfrancis This PR solved the problem but unfortunately introduced a new one: #2344
