### ISSUE TITLE
Azure Oss Db Tools Pgbouncer Sidecar - Trust auth

### ISSUE THREAD

**Issue by jakekreider** [Azure/aks-engine#2363]
**Describe the issue**
_I don't know if this is even the place where the image is maintained. If not here, I apologize._   
 This is for the [Azure Oss Db Tools Pgbouncer Sidecar image on Docker Hub](https://hub.docker.com/_/microsoft-azure-oss-db-tools-pgbouncer-sidecar?tab=description)

The documentation explicitly says 
> Warning! Do not change listen_addr, auth_file, auth_type, server_tls_sslmode or server_tls_ca_file. Changing any of these settings will prevent successful connections to the server.  

Because that value is `auth_type = trust`, that means anything that can access the K8s service will be allowed access to Postgres. 

It also says below 
> Note: Applications accessing PostgresSQL via this PgBouncer Sidecar must use credentials with a password.  

That also doesn't seem accurate if `auth_type = trust`, per [PGBouncer's docs](https://www.pgbouncer.org/config.html). Am I misunderstanding something here? 

**AKS Engine Version***
N/A, question is to documentation on [Docker hub](https://hub.docker.com/_/microsoft-azure-oss-db-tools-pgbouncer-sidecar)

**Kubernetes Version**
N/A

**Gatekeeper Version**
N/A
**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Please don't remove the text below**
Notify @az-policy-kube

**Comment by mragh** [comment]
I just noticed this comment that the image isn't maintained here. https://github.com/Azure/aks-engine/issues/889#issuecomment-478088504

Could this information be forward to the Azure OSS Database service team, or is there somewhere I can file with them?
