### ISSUE TITLE
DNS lookup error then trying to manage k8s cluster from AKS Engine workstation

### ISSUE THREAD

**Issue by werton13** [Azure/aks-engine#2365]
Hello team! Please help me to understand what is wrong with my configuration

I'm in process of configuring K8s cluster in Azure Stack environment. My Azure Stack deployment is a integrated environment on version 1908.
I just installed AKS Engine on Ubuntu 16.04 and deployed K8s cluster with 3 master and 3 nodes.

i deployed cluster on: "orchestratorVersion": "1.16.1" 
so now i have 3 worker nodes with names:

- k8s-linuxpool-36691240-0
- k8s-linuxpool-36691240-1
- k8s-linuxpool-36691240-2

these nodes doesn't have public ip addresses, and also i have 3 master nodes with public ip addresses assigned.

Now i'm trying to manage K8s cluster from AKS Engine machine, here I have kubectl and helm installed, and I want to deploy the NGINX Ingress Controller via Helm:
```bash
helm install stable/nginx-ingress \
--name nginx-ingress \
--namespace nginx-ingress \
--set controller.replicaCount=2
```

but I receive an error:
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp: lookup k8s-linuxpool-36691240-1 on 168.63.129.16:53: server misbehaving

so if i understand correctly it should work, but why it try to resolve internal hosts names? i cannot add anything manually to this dns service and even if i can - what can i addto it..?

i configured my AKS Engine to connect to K8s cluster with thiis command:
 export KUBECONFIG=/home/aksadmin/kube-rg/kubeconfig/kubeconfig.azuremsk.json

after that i can list of PODs and Services but:
kubectl get componentstatuses
NAME                 AGE
scheduler            <unknown>
controller-manager   <unknown>
etcd-0               <unknown>

**Comment by werton13** [comment]
I think the required DNS configuration for this solution have to be clarified, because I find some odd things.
Below is the file, which I used to configure my AKS Engine workstation to connect K8s cluster:

 *cat  /home/aksadmin/kube-rg/kubeconfig/kubeconfig.azuremsk.json*
```json

    {
        "apiVersion": "v1",
        "clusters": [
            {
                "cluster": {
                    "certificate-authority-data": " a long key here truncated ",
                    "server": "https://AKSEngine.azuremsk.cloudapp.ec.mts.ru"
                },
                "name": "AKSEngine"
            }
        ],
        "contexts": [
            {
                "context": {
                    "cluster": "AKSEngine",
                    "user": "AKSEngine-admin"
                },
                "name": "AKSEngine"
            }
        ],
        "current-context": "AKSEngine",
        "kind": "Config",
        "users": [
            {
                "name": "AKSEngine-admin",
                "user": {"client-certificate-data":"client certificate data was heere"}
            }
        ]
    }
```
"server": "https://AKSEngine.azuremsk.cloudapp.ec.mts.ru" - this string is a little confusing me, because I don't have cloudapp.ec.mts.ru this zone in AzureStack - can someone clarify how this FQDN is  built?

**Comment by werton13** [comment]
it is look like I have some issue in Azure Stack, I will fix it and then  write here if it help.

**Comment by werton13** [comment]
Hi there! I resolved  the issue with DNS zone azuremsk.cloudapp.ec.mts.ru and at a moment hostname AKSEngine.azuremsk.cloudapp.ec.mts.ru is resolved successfully, but this does not fix an error. I still get the error:

`Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp: lookup k8s-linuxpool-36691240-1 on 168.63.129.16:53: server misbehaving
`
Please advice me 
below is the cluster specification I used to deploy my K8s cluster:
```json
{
    "apiVersion": "vlabs",
    "location": "",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.16",
            "orchestratorVersion": "1.16.1",
            "kubernetesConfig": {
                "kubernetesImageBase": "mcr.microsoft.com/k8s/azurestack/core/",
                "useInstanceMetadata": false,
                "networkPlugin": "kubenet"
            }
        },
        "customCloudProfile": {
            "portalURL": "https://portal.azuremsk.ec.mts.ru"
        },
        "masterProfile": {
            "dnsPrefix": "AKSEngine",
            "distro": "aks-ubuntu-16.04",
            "count": 3,
            "vmSize": "Standard_D2_v2"
        },
        "agentPoolProfiles": [
            {
                "name": "linuxpool",
                "count": 3,
                "vmSize": "Standard_D2_v2",
                "distro": "aks-ubuntu-16.04",
                "availabilityProfile": "AvailabilitySet",
                "AcceleratedNetworkingEnabled": false
            }
        ],
        "linuxProfile": {
            "adminUsername": "adminusername",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": "ssh-rsa  ssh key was here"
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "client id was here",
            "secret": "secret was here"
        }
    }
}
```

**Comment by werton13** [comment]
any ideas?

**Comment by jadarsie** [comment]
hey, will check it out, could you please post what AKSe you are using?

**Comment by alexsmithMSFT** [comment]
I discussed with this customer, and seemed to be a version mismatch with Helm v2.16.1 on the client VM ([install script](https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get)), and v3.0.0 on the Kubernetes master. I'll let them provide details after confirming tomorrow.

**Comment by werton13** [comment]
Hi there, the root cause of this issue was Helm version mismatch, because in each AKS cluster node by default installed Helm 3.0. On AKS Engine VM I installed helm client   by default method:
```bash
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
```
So when  i I have installed Helm 3.0  by this specific for v3 script:
```bash
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
```
the issue has gone.

Thanks all
Thread can be closed

**Comment by jadarsie** [comment]
thx @werton13
