### ISSUE TITLE
CSI limitiations in v1.17

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2369]
1. 1.16+ cloud-controller-manager requires CSI drivers for storage
2. CSI drivers do not support Windows storage
3. CSI drivers do not support zones

ergo

- 1.16 and 1.17 w/ CCM do not support Windows nodes + storage
- 1.16 and 1.17 w/ CCM do not support zones + storage

**Comment by jackfrancis** [comment]
@feiskyer @andyzhangx can you confirm that the above statements are true?

**Comment by andyzhangx** [comment]
@jackfrancis correct, 
 - about zone support, there is a working PR: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/176
 - about windows support, would be alpha in 1.18

**Comment by mboersma** [comment]
Is cloud-controller-manager required for 1.17? We've had it on by default up to 1.17.0-rc.1, but #2372 turns it off to get zones and Windows working again (hopefully).

**Comment by andyzhangx** [comment]
> Is cloud-controller-manager required for 1.17? We've had it on by default up to 1.17.0-rc.1, but #2372 turns it off to get zones and Windows working again (hopefully).

@mboersma cloud-controller-manager is optional, not required, the removal of cloud provider would happen in 1.21

**Comment by jackfrancis** [comment]
Thanks @andyzhangx for the clarification, I've updated the issue description. @mboersma can you proofread for falsehoods?

**Comment by mboersma** [comment]
AFAICT the description is accurate now, thanks @jackfrancis.
