### ISSUE TITLE
containerd integration using deprecated "cri" binary

### ISSUE THREAD

**Issue by cpuguy83** [Azure/aks-engine#2370]
**Describe the bug**

For containerd we are fetching the deprecated standalone cri-containerd binary.
CRI is now compiled into containerd directly, this should be used instead.

**Additional context**

https://github.com/Azure/aks-engine/blob/f8f373d241780a7945e40cdc9dc0d4b326d334b2/parts/k8s/cloud-init/artifacts/cse_install.sh#L173-L178

From cri-containerd repo:

> Note: The standalone cri-containerd binary is end-of-life. cri-containerd is transitioning from a standalone binary that talks to containerd to a plugin within containerd. This github branch is for the cri plugin. See standalone-cri-containerd branch for information about the standalone version of cri-containerd.

I already have some packaging for containerd, but have not tested extensively or finalized the pipeline to publish such packages.

**Comment by CecileRobertMichon** [comment]
Thanks @cpuguy83. Is this ready to be fixed or do we need to wait for 
> I already have some packaging for containerd, but have not tested extensively or finalized the pipeline to publish such packages.

?

**Comment by cpuguy83** [comment]
We could use the version of containerd that we package with our moby packages, and it may even be worth it to have access to docker (for users) in the containerd-based setups.
