### ISSUE TITLE
Support for Spot VMs / VMSS

### ISSUE THREAD

**Issue by desek** [Azure/aks-engine#2391]
**Describe the request**
With the deprecation and replacement of Low-priority VM's and VM Scale Sets for Spot VM's / VMSS we need to be able to configure Priority=Spot and BilliingProfile.maxPrice which was introduced in apiVersion 2019-03-01.
 
**Explain why AKS Engine needs it**
Low-priority functionality already exists and should be lifecycled to Spot.

**Describe the solution you'd like**
Incrementing the hard coded api version parameter to at least 2019-03-01, but 2019-07-01 (lastest) is preferred, found here:
https://github.com/Azure/aks-engine/blob/4ec6504bc6da674d98edde6bcf40c168bde99dc9/pkg/engine/armvariables.go#L151

And allow billingProfile.maxPrice to be configurable with a default value of "-1.0".

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by jackfrancis** [comment]
Hi @desek, thanks for adding this issue. Let's circle back on this after the Christmas break, I imagine any deprecation effects aren't near term.

**Comment by desek** [comment]
As far as I understand the information sent by Microsoft the `Priority=Low` parameter will be deprecated as of 3rd of January 2020 and Low-Priority instances will be converted to Spot instances.
I'm afraid this might break new deployments towards api versions older than 2019-03-01 and deployments with `Priority=Low` rather than doing translation of Low to Spot in the backend.

**Comment by devigned** [comment]
Even if the feature is deprecated, I can't imagine the old API version (2018-10-01) will not continue to work.

**Comment by posix4e** [comment]
I've been told we will be charged at the full spot price unless we set the price. I would expect things to keep working but get expensive

**Comment by som-nitjsr** [comment]
By when i can expect azure spot vm support for aks
