### ISSUE TITLE
Custom coredns config

### ISSUE THREAD

**Issue by jon-walton** [Azure/aks-engine#240]
**Is this a request for help?**:

yes and no

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature request

**What version of aks-engine?**:

v0.28.1

---

Hi!

Is there a way to customise the coredns config, such as adding stub zones or secondaries to resolve internal zones. for example:

```
proxy mycorp.org 10.10.1.10:53
```

If this isn't currently possible, are you open to a pull request and have any suggestions on how you would want this achieved?

There are currently 2 ways that I can think of for achieving this, however neither are ideal;

1. Change the DNS servers for the virtual network. In my case, this would cause all DNS requests to go over our VPN and incur a 170+ms latency
2. Use `.spec.hostAliases` to populate the `/etc/hosts`. This is not ideal as these entries need to be manually updated for each resource the pod needs to resolve.

Thanks!

**Kubernetes version**:

1.13.1

**What happened**:

No clear way to customise the coredns configuration. Such as defining stub zone

**What you expected to happen**:

Be able to customise the coredns configuration

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by tariq1890** [comment]
We definitely accept PRs for this :). If you need to add configurability to coredns.yaml, feel free to take a PR. I am also happy to walk you the through the areas (if you want) where you'd need to make these changes.

**Comment by mhyllander** [comment]
AFAIK you can customize coredns by modifying the `kube-system/coredns` configmap. coredns will automatically detect and reload the configuration changes.

**Comment by agashkov** [comment]
I can't configure the configmap, because after the change after some time (60s) it returns to its original state. This is due to the use of the Reconsile mode in the cofigmap:

`apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
addonmanager.kubernetes.io/mode: Reconcile`

**Comment by agashkov** [comment]
My AKS cluster is new without updates (version 1.12.4 kubernetes)

**Comment by jsnider-mtu** [comment]
I'm having the same issue, need to configure a stub domain but the configmap is reconciled back to the original.

**Comment by jon-walton** [comment]
https://github.com/Azure/AKS/blob/master/CHANGELOG.md lists coredns config changes as an ongoing issue that'll be fixed in the coming weeks. I suggest hanging tight and waiting for that

But for me, I no longer see value in adding templating to coredns configs in aks-engine so I'll close this issue

**Comment by mleneveut** [comment]
You can add your custom config in the kube-system/coredns-custom configMap
