### ISSUE TITLE
Add keyvault support for container-monitoring workspaceKey

### ISSUE THREAD

**Issue by davidmatson** [Azure/aks-engine#242]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of aks-engine?**:
0.28.1
---

**Anything else we need to know**:
Other secrets do not need to be persisted in the apimodel file but can be pulled from keyvault instead. IT would be great to do the same for the workspaceKey parameter of the container-monitoring addon. This is the only secret we would otherwise have to check in.

**Comment by davidmatson** [comment]
How do I mark this issue non-stale?

**Comment by jackfrancis** [comment]
@rashmichandrashekar @ganga1980 do you have any plans to support this?

**Comment by ganga1980** [comment]
> @rashmichandrashekar @ganga1980 do you have any plans to support this?
> @jackfrancis, As I know, we dont have any plans to integrate with Key vault. But customer can use container monitoring add-on with default workspace  and in this case, customer doesnt require to add the workspace key in API model. Let me reach out the customer and ask him to use container monitoring with default workspace to avoid keeping the workspace id and key in the definition.

**Comment by ganga1980** [comment]
> ## **Is this a request for help?**:
> No
> ## **Is this an ISSUE or FEATURE REQUEST?** (choose one):
> FEATURE REQUEST
> ## **What version of aks-engine?**:
> 0.28.1
> **Anything else we need to know**:
> Other secrets do not need to be persisted in the apimodel file but can be pulled from keyvault instead. IT would be great to do the same for the workspaceKey parameter of the container-monitoring addon. This is the only secret we would otherwise have to check in.

Hi, @davidmatson,  We have improved container monitoring add-on onboarding in AKS-Engine significantly, if you use either option 1 or 2, then you dont need to specify the workspace Guid and key in the API definition.  Here is the doc  which has detailed instructions
https://github.com/Azure/aks-engine/blob/master/docs/tutorials/containermonitoringaddon.md
Please let me know if you need any help or have any questions.

**Comment by rbitia** [comment]
@davidmatson closing for now since there's a workaround with using the container monitor add-on!
