### ISSUE TITLE
Request: enable NodeRestriction Admission Controller

### ISSUE THREAD

**Issue by AkihiroSuda** [Azure/aks-engine#2422]
**Describe the request**
Enable [NodeRestriction Admission Controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#noderestriction)

**Explain why AKS Engine needs it**

To prevent a compromised node from gaining privileges on other nodes by running privileged pods with the compromised node's kubelet kubeconfig.

This is requirement for https://github.com/AkihiroSuda/instance-per-pod .

**Describe the solution you'd like**

Enable the controller by modifying the kube-apiserver flag.

Also, [kubelet needs to be configured to use unique cert pair with unique CN prefixed with `"system:node:"`](https://github.com/kubernetes/kubernetes/blob/v1.17.0/pkg/auth/nodeidentifier/default.go#L37).

Currently,  kubelet CN seems always set to `nodeclient` on all nodes.

**Describe alternatives you've considered**
None

**Additional context**

This seems to have been suggested in the past several times, but seems still unimplemented.

https://feedback.azure.com/forums/34192--general-feedback/suggestions/34719424-aks-security-enable-the-noderestriction-admissio
https://github.com/Azure/acs-engine/issues/2133

**Comment by AkihiroSuda** [comment]
no stale

**Comment by AkihiroSuda** [comment]
no stale

**Comment by jackfrancis** [comment]
Is there a cluster-api + Azure story for this?

I think this functionality is promising, but I'm not confident it will happen in the AKS Engine project.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues
