### ISSUE TITLE
kubelet suddenly stop functioning

### ISSUE THREAD

**Issue by yixwang** [Azure/aks-engine#2441]
**Describe the bug**
We noticed that one of the windows node in our cluster suddenly stop functioning. Run the command `kubectl describe node <node_name>` and saw the following in the event:
```
MemoryPressure   Unknown   Sun, 08 Dec 2019 09:43:08 -0800   Sun, 08 Dec 2019 09:44:15 -0800   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure     Unknown   Sun, 08 Dec 2019 09:43:08 -0800   Sun, 08 Dec 2019 09:44:15 -0800   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure      Unknown   Sun, 08 Dec 2019 09:43:08 -0800   Sun, 08 Dec 2019 09:44:15 -0800   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready            Unknown   Sun, 08 Dec 2019 09:43:08 -0800   Sun, 08 Dec 2019 09:44:15 -0800   NodeStatusUnknown   Kubelet stopped posting node status.
```

This caused the node to go into "Not Ready" state. Along with that the CPU usage on the node surged to 90%. We were trying to ssh into the node but the request takes forever and eventually timeouts. We had to restart the VM and everything is back to healthy after the restart. 

In the kubelet.err.log we found the following around the time when the node droped:
```
E1208 17:38:16.556786    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
E1208 17:38:58.574752    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
E1208 17:39:29.589913    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
E1208 17:40:11.605749    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
E1208 17:40:42.637678    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
E1208 17:41:24.689907    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
E1208 17:41:55.725867    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
E1208 17:42:37.771764    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
E1208 17:43:08.805606    5748 azure_dd.go:162] Failed to get instance type from Azure cloud provider, nodeName: 3006k8s00000000
ERROR: The process "azure-vnet.exe" not found.
ERROR: The process "azure-vnet-ipam.exe" not found.
```

**Steps To Reproduce**
Run the cluster for a about week. 

**Expected behavior**
The node should stay healthy

**AKS Engine version**
0.44.0

**Kubernetes version**
1.15.4

**Additional context**
![node_not_ready](https://user-images.githubusercontent.com/47333969/70666812-52191f80-1c24-11ea-81b9-e612992a0cf0.png)

![cpu](https://user-images.githubusercontent.com/47333969/70666861-6bba6700-1c24-11ea-95ab-6ddcd4ecbfac.png)

**Comment by marosset** [comment]
@yixwang If you see this again can you try running https://github.com/Azure/aks-engine/blob/master/scripts/collect-windows-logs.ps1? This collects logs and ETW events for a bunch of different components.
