### ISSUE TITLE
Add validation to make sure kubernetesConfig.networkPlugin is coherent with -kubletconfig's -network-plugin

### ISSUE THREAD

**Issue by paulgmiller** [Azure/aks-engine#2448]
**Describe the bug**
When we deploy our arm template we always fail (6+ repros) on the CSE that runs on master always faails with:
"VM has reported a failure when processing extension 'cse-master-1'. Error message: \"Enable failed: failed to execute command: command terminated with exit stat
us=30\n[stdout]\nThu Dec 12 18:04:25 UTC 2019,k8s-master-12547266-1\n\n[stderr]\nConnection to aksrepos.azurecr.io 443 port [tcp/https] succeeded!\n\"\r\n\r\nMore information on tr
oubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "

**Steps To Reproduce**
Getting our api model so you can try and reproduce stand by. 

**Expected behavior**
Cluster created. This worked maybe a month ago with same configuration. 

**AKS Engine version**
42.0 or 44.2 (both fail)

**Kubernetes version**
1.14.7

**Additional context**
Found this similar old issue. 
https://github.com/Azure/aks-engine/issues/328 
We're still tyring to ssh in to our master.

**Comment by paulgmiller** [comment]
Dec 12 18:05:12 k8s-master-12547266-1 kubelet[5670]: E1212 18:05:12.155895    5670 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.255.255.6:443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8s-master-12547266-1&limit=500&resourceVersion=0: dial tcp 10.255.255.6:443: connect: connection refused     Dec 12 18:05:12 k8s-master-12547266-1 kubelet[5670]: E1212 18:05:12.156046    5670 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get https://10.255.255.6:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.255.255.6:443: connect: connection refused
Dec 12 18:05:12 k8s-master-12547266-1 kubelet[5670]: E1212 18:05:12.156493    5670 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Get https://10.255.255.6:443/api/v1/nodes?fieldSelector=metadata.name%3Dk8s-master-12547266-1&limit=500&resourceVersion=0: dial tcp 10.255.255.6:443: connect: connection refused
Dec 12 18:05:12 k8s-master-12547266-1 kubelet[5670]: I1212 18:05:12.157974    5670 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Dec 12 18:05:12 k8s-master-12547266-1 kubelet[5670]: I1212 18:05:12.158000    5670 client.go:104] Start docker client with request timeout=2m0s
Dec 12 18:05:12 k8s-master-12547266-1 kubelet[5670]: W1212 18:05:12.172293    5670 docker_service.go:561] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Dec 12 18:05:12 k8s-master-12547266-1 kubelet[5670]: I1212 18:05:12.172314    5670 docker_service.go:238] Hairpin mode set to "hairpin-veth"
Dec 12 18:05:12 k8s-master-12547266-1 kubelet[5670]: F1212 18:05:12.174141    5670 server.go:266] failed to run Kubelet: failed to create kubelet: didn't find compatible CNI plugin with given settings &{HairpinMode:hairpin-veth NonMasqueradeCIDR:0.0.0.0/0 PluginName:azure PluginBinDirString:/opt/cni/bin PluginBinDirs:[/opt/cni/bin] PluginConfDir:/etc/cni/net.d MTU:0}: Network plugin "azure" not found.
Dec 12 18:05:12 k8s-master-12547266-1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Dec 12 18:05:12 k8s-master-12547266-1 systemd[1]: kubelet.service: Unit entered failed state.

**Comment by paulgmiller** [comment]
Seems like our cni is misconfigured. I think there was a change in our api model here so ripping it out and seeing if it helps

**Comment by paulgmiller** [comment]
Yeah so this was us confusing kubernetesConfig.networkPlugin with -kubletconfig's -network-plugin.

Be nice validation caught that but assumeing you have bigger fish to fry.

**Comment by CecileRobertMichon** [comment]
Thanks for updating the issue @paulgmiller. @jackfrancis was just telling me yesterday he wants to get rid of the double input for network plugin because of this possible exact confusion. In the meantime I'm reopening this issue and marking it as good first issue for someone to add validation.
