### ISSUE TITLE
Container Monitoring AddOn fails with Windows agent pool

### ISSUE THREAD

**Issue by davidmatson** [Azure/aks-engine#245]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.28.1
---

**What happened**:
Deployed with the container-monitoring addon enabled when using a Windows agent pool.

**What you expected to happen**:
Expected that container monitoring worked.
What actually happened is that the following deployment could not run due to the os=linux node selector:
deployment.apps/omsagent-rs

**How to reproduce it** (as minimally and precisely as possible):
Use an API model that has the container-monitoring addon enabled but has a single Windows agent pool.

**Anything else we need to know**:
Is there a Docker image for running container monitoring as a daemonset on Windows? If not, should aks-engine fail with an error?

**Comment by davidmatson** [comment]
Ping to remove stale tag

**Comment by jackfrancis** [comment]
@rashmichandrashekar @ganga1980 Are there any plans to enable Windows support for container-monitoring?

**Comment by ganga1980** [comment]
> @rashmichandrashekar @ganga1980 Are there any plans to enable Windows support for container-monitoring?

> @jackfrancis, we do support windows container monitoring as long as at least they have one Linux node. Looks like customer has the cluster with all windows nodes. Will follow up with him understand more on the customer environment.

**Comment by ganga1980** [comment]
Hi, @davidmatson,  We do support monitoring of windows container inventory and perf counters though there are some gaps as described here in https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-analyze compared to Linux node. We have plans to bring the parity of the containers running on windows with containers running on the Linux. Please note that, at this point of time, we need at leas one Linux node in the cluster. Looks like in your case everything is Windows and also you are using old version of the AKS-Engine. Can you please try latest version of the aks-engine  or  Azure Monitor for containers HELM chart to add monitoring addon? Following docs  has detailed instructions on how to enable container monitoring addon for AKS-Engine clusters
https://github.com/Azure/aks-engine/blob/master/docs/tutorials/containermonitoringaddon.md
https://github.com/helm/charts/tree/master/incubator/azuremonitor-containers

**Comment by jackfrancis** [comment]
Thanks @ganga1980!

**Comment by davidmatson** [comment]
@ganga1980 - since we only have Windows nodes in our cluster (well other than the required Linux master), is there anything to try out at this time? (I think I'm not quite following fully.) Thanks!

**Comment by jackfrancis** [comment]
Is this still an issue?

**Comment by davidmatson** [comment]
As of last month, yes, we heard from folks on the team that this add-on still required at least one Linux non-master node.

**Comment by jackfrancis** [comment]
@ganga1980, is the requirement for at least one Linux node going to change? If not, we should probably close this issue and just document that requirement.

**Comment by ganga1980** [comment]
> @ganga1980, is the requirement for at least one Linux node going to change? If not, we should probably close this issue and just document that requirement.

> @jackfrancis , Few of our customers reported that,  when we run our rs pod on master node, all the API server calls are failing so we made change not to schedule on master node and because of this constraint we would need at least one linux node other than master to rs pod which will be collect the performance and inventory of windows via remote cAdvisor API calls. We are working having separate agent (i.e.Deamonset) to run on windows but initially it will be collecting only logs. 

to answer your question, yes, we would one non-master linux node to get the metrics of windows nodes and containers.

**Comment by jackfrancis** [comment]
Thanks @ganga1980, I'm going to close this issue as the undesired behavior described is (unfortunately) by design.
