### ISSUE TITLE
error scaling aks engine cluster in azure

### ISSUE THREAD

**Issue by elieassi** [Azure/aks-engine#2454]
**Describe the bug**
Starting on 13/12/2019 we are having issue when the aks engine cluster needs to scale up, upon creating new nodes , the autoscale status is on Failed

**Steps To Reproduce**
using version 0.38.2 , from 4 am this morning (13/12/2019), multiple clusters are failing across many azure regions while attempting to scale up

Error Message in Azure
Multiple VM extensions failed to be provisioned on the VM. Please see the VM extension instance view for other failures. The first extension failed due to the error: Provisioning of VM extension k8s-pool1-39869008-vmss-computeAksLinuxBilling has timed out. Extension provisioning has taken too long to complete. The extension did not report a message. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot

Entering one of the failing machines and trying to do an apt-get update

the following error is receiving, related to the MS repo

Hit:1 http://azure.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:5 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages [156 kB]
Err:5 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
  Hash Sum mismatch
Hit:6 http://security.ubuntu.com/ubuntu xenial-security InRelease
Fetched 110 kB in 0s (205 kB/s)
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Expected behavior**
For the scale to work up

**AKS Engine version**
0.38.2
**Kubernetes version**
1.14.1

**Comment by CecileRobertMichon** [comment]
@elieassi there's an issue with a package in the msft apt repo, Microsoft is aware of the issue and working on fixing it asap. Thanks for the report.

**Comment by CecileRobertMichon** [comment]
this is now fixed https://github.com/dotnet/core/issues/3988
