### ISSUE TITLE
Clarify documentation on agentpool extensions

### ISSUE THREAD

**Issue by jeffb4** [Azure/aks-engine#2464]
**Describe the request**

Allow extensions to be specified for agent pools

**Explain why AKS Engine needs it**

Certain pre-Kubernetes configuration may need to be done on instances (for instance, ephemeral volume encryption), even if they are agents and not master nodes.

**Describe the solution you'd like**

Extend the agentPool configuration to allow defined extensions to be enabled, similar to the current master node configuration.

**Describe alternatives you've considered**

Alternatively, allowing locally defined shell scripts to be injected post/pre instance cloud-init would be equivalently useful

**Additional context**

**Comment by CecileRobertMichon** [comment]
Hi @jeffb4, both [extensions](https://github.com/Azure/aks-engine/blob/master/examples/extensions/prometheus-grafana-k8s.json#L18) (post deployment) and [preProvisionExtensions](https://github.com/Azure/aks-engine/blob/master/examples/extensions/kubernetes.preprovision.json#L22) (pre cloud-init) are supported for agentPools. They are not supported for VMSS (see #422) but should work with regular VMs.

What made you think that they weren't? Is it a gap in documentation or are you running into errors using them?

**Comment by jeffb4** [comment]
Thank you for the clarification. The documentation aspects that led me to believe it was not supported were:

missing attribute from agentPools table at https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#agentpoolprofiles

no example of agentPools.extensions in https://github.com/Azure/aks-engine/blob/master/docs/topics/extensions.md

text of https://github.com/Azure/aks-engine/blob/master/docs/topics/extensions.md#masterprofile "Extensions, in the current implementation run a script on a master node. The extensions array in the masterProfile define that the master pool will have the script run on a single node on it." implied to the uninitiated (me) that extensions were only intended for master pool, not agent pools.

**Comment by CecileRobertMichon** [comment]
Great, let's clarify the docs then.

**Comment by jeffb4** [comment]
PR opened for docs. Thanks again for the help, Cecile.
