### ISSUE TITLE
hyperVGeneration required in 2019-07-01 compute API

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2486]
This PR introduced a new compute API version:

https://github.com/Azure/aks-engine/pull/2412

Test signal is telling us that the new API version delivered w/ that change requires a `hyperVGeneration` value:

```
Error from deployment for kubernetes-westus-65081 in resource group kubernetes-westus-65081:exit status 1
 2019/12/19 16:19:29 Command Output: ERROR: Deployment failed. Correlation ID: aae2de58-6ece-4430-ad90-0a7e2cc9055a. {
   "error": {
     "code": "InvalidParameter",
     "message": "Required parameter 'hyperVGeneration' is missing (null).",
     "target": "hyperVGeneration"
   }
 }
```

**Comment by marosset** [comment]
A quick fix for this was checked it with https://github.com/Azure/aks-engine/pull/2487 but that change hard-coded hyperVGeneration to 1 (the previous default).

A proper fix is still needed and likely involved specifying the generation in the apimodel
