### ISSUE TITLE
kubelet paramters are getting removed on the nodes 

### ISSUE THREAD

**Issue by satishsudini** [Azure/aks-engine#2495]
**Describe the bug**
Kubelet parameter (--authentication-token-webhook) is getting removed on the master and agent nodes causing issues with HPA

**Expected behavior**
/etc/default/kublet should have --authentication-token-webhook for HPA metrics and this should not be removed/updated

**AKS Engine version**
0.36

**Kubernetes version**
1.13

**Comment by mboersma** [comment]
Could you post specific steps to reproduce this? This parameter is only enabled by default for Kubernetes 1.16 and later, so it would help to show via your apimodel specifically how you're enabling it for 1.13 and how to trigger this bad behavior.

Also, is this still the case in AKS Engine v0.45.0?
