### ISSUE TITLE
Add new Dav4 and Eav4 VM SKUs to supported list

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#2498]
**Describe the request**
AKS Engine should support two new Azure VM SKU groups: [Dav4](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dav4-series) and [Eav4](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-memory#eav4-series).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by palma21** [comment]
Added on https://github.com/Azure/aks-engine/pull/2418 :)
And they already are present in v0.45.0
https://github.com/Azure/aks-engine/releases/tag/v0.45.0
