### ISSUE TITLE
Windows container disk performance is slower in container than the VM

### ISSUE THREAD

**Issue by Banani-Rath** [Azure/aks-engine#2499]
**Describe the bug**

**Steps To Reproduce**
VM |  
-- | --
VMSize | Standard_DS13_v2CPU8Memory56G | CPU | 8 | Memory | 56G
CPU | 8
Memory | 56G
region | West US
OS | 2019-Datacenter-with-Containers-smalldisk: 17763.737.1909062324
OS disk | Ephemeral OS disk(288G)
Container | CPU8Memory54GOS Versionmcr.microsoft.com/dotnet/framework/runtime:4.7.2 | CPU | 8 | Memory | 54G | OS Version | mcr.microsoft.com/dotnet/framework/runtime:4.7.2
CPU | 8
Memory | 54G
OS Version | mcr.microsoft.com/dotnet/framework/runtime:4.7.2

we usea script to test DiskIO on VM and container respectively, and the script downloads a zip file with large small files and expand it to local folder first, we use the elapsed time of removing these files to test the DiskIO
aksEngineVersion": "v0.31.1",
        "creationSource": "aksengine-4269k8s00",
        "orchestrator": "Kubernetes:1.13.3",
        "poolName": "windowspool2",
        "resourceNameSuffix": "42692"

Times | Node(Test on D:\) | Node(Test on C:\) | Container (windows defender on)(Run docker on C:\) | Container(windows defender off)(Run docker on C:\) | Container (windows defender on)(Run docker on D:\) | Container (windows defender off)(Run docker on D:\) | Container(windows defender on)(Mount volume: mount D:\data to Container, and test on that folder)
-- | -- | -- | -- | -- | -- | -- | --
1 | 4004.99ms | 6997.05ms | 9355.45ms | 9250.08ms | 8501.11ms | 8450.04ms | 8119.0497ms
2 | 4009.02ms | 6836.06ms | 9062.08ms | 9056.01ms | 8525.08ms | 8426.09ms | 8219.054ms
3 |   | 6834.06ms | 9281.04ms | 9012.82ms | 8381.09ms | 8387.09ms | 8268.0767ms

My question is: ANy suggestion to improve performance?

**Comment by marosset** [comment]
@Banani-Rath is the slower performance specific to containers running in Kuberenetes clusters or are you seeing the same performance decreases when running containers with Docker on VMs manually created in Azure?

**Comment by Banani-Rath** [comment]
@marosset : Thank you for quick response.We observed slower performance issue in containers created in Kubernetes cluster.

**Comment by Banani-Rath** [comment]
Sorry closed by mistake

**Comment by marosset** [comment]
@Banani-Rath I'm still not clear what you are using to compare the performance on disks.
Can you please describe the setup you were using to compare performance against?
Was it a VM in azure with the same image/sku/specs as the  kubernetes Windows node?

**Comment by Banani-Rath** [comment]
@marosset , sure please find more details here:
We have a VM in azure with following environment:

VMSize | Standard_DS13_v2CPU8Memory56G | CPU | 8 | Memory | 56G
-- | -- | -- | -- | -- | --
CPU | 8
Memory | 56G
region | West US
OS | 2019-Datacenter-with-Containers-smalldisk: 17763.737.1909062324
OS disk | Ephemeral OS disk(288G)

And for container we have : 

CPU | 8
-- | --
Memory | 54G
OS Version | mcr.microsoft.com/dotnet/framework/runtime:4.7.2
Then using the following script to test DiskIO on VM and container respectively, and the script downloads a zip file with large small files and expand it to local folder first, we use the elapsed time of removing these files to test the DiskIO

if(-Not (Test-Path ".\package")){

    wget -Uri "storageurl" -OutFile package.zip

    Expand-Archive -Path .\package.zip -DestinationPath .\package

}

$tempFolder = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | %{[char]$_})

mkdir $tempFolder

Copy-Item -Path ".\package\" -Destination $tempFolder -Recurse -Force

$BeginTime = Get-Date

Remove-Item "$tempFolder" -Recurse -Force | Out-Null

$EndTime = Get-Date

Write-Output $([string]::Format("Elapsed time: {0}ms", ($EndTime-$BeginTime).TotalMilliseconds))

Results we get:

Times | Node(Test on D:\) | Node(Test on C:\) | Container (windows defender on)(Run docker on C:\) | Container(windows defender off)(Run docker on C:\) | Container (windows defender on)(Run docker on D:\) | Container (windows defender off)(Run docker on D:\) | Container(windows defender on)(Mount volume: mount D:\data to Container, and test on that folder)
-- | -- | -- | -- | -- | -- | -- | --
1 | 4004.99ms | 6997.05ms | 9355.45ms | 9250.08ms | 8501.11ms | 8450.04ms | 8119.0497ms
2 | 4009.02ms | 6836.06ms | 9062.08ms | 9056.01ms | 8525.08ms | 8426.09ms | 8219.054ms
3 |   | 6834.06ms | 9281.04ms | 9012.82ms | 8381.09ms | 8387.09ms | 8268.0767ms

**Comment by Banani-Rath** [comment]
If you notice container performance is slow compared to node.Hope this helps

**Comment by MikkelHegn** [comment]
@immuzz @weijuans-msft - can you help validate and investigate from the Windows side?
