### ISSUE TITLE
get-akse.sh installs newest release in terms of date, not semver version

### ISSUE THREAD

**Issue by Timost** [Azure/aks-engine#2507]
**Describe the bug**
I'm not sure if this is a bug or an intended behaviour, but it's confusing.

Right now, the latest release in terms of date is [v0.43.3](https://github.com/Azure/aks-engine/releases/tag/v0.43.3) but the latest in terms of semver versionning is [v0.45.0](https://github.com/Azure/aks-engine/releases/tag/v0.45.0).
When I run `get-akse.sh` to update the aks-engine version, it installs the `v0.43.3` release, even though I already have a more recent version installed in semver terms. 

**Steps To Reproduce**
```bash
./get-akse.sh -v v0.44.2 
./get-akse.sh
```

Example:
```bash
➜ ./get-akse.sh -v v0.44.2 
AKS-Engine v0.44.2 is available. Changing from version v0.45.0.
Downloading https://github.com/Azure/aks-engine/releases/download/v0.44.2/aks-engine-v0.44.2-linux-amd64.tar.gz
Preparing to install aks-engine into /usr/local/bin
aks-engine installed into /usr/local/bin/aks-engine
Run 'aks-engine version' to test.
➜ aks-engine version      
Version: v0.44.2
GitCommit: b608449a2
GitTreeState: clean
➜  ./get-akse.sh           
AKS-Engine v0.43.3 is available. Changing from version v0.44.2.
Downloading https://github.com/Azure/aks-engine/releases/download/v0.43.3/aks-engine-v0.43.3-linux-amd64.tar.gz
Preparing to install aks-engine into /usr/local/bin
aks-engine installed into /usr/local/bin/aks-engine
Run 'aks-engine version' to test.
➜  aks-engine version
Version: v0.43.3
GitCommit: d9d73c3f6
GitTreeState: clean
```

**Expected behavior**
I would expect `get-akse.sh` to try to install the latest release in terms of semver versions.

**Comment by mboersma** [comment]
This is because the script uses https://github.com/Azure/aks-engine/releases/latest by default, which returns most recently created release. You can override this with `get-akse.sh --version v0.45.0`, but I agree that the expected behavior is that it defaults to the most recent *semver* release.

**Comment by Timost** [comment]
Yes I ended up using the --version flag which works. 

I have a cluster using the auto-scaler plugin which is not supported in 0.43.x so it was kind of confusing to get errors from a configuration which was perfectly fine before the aks-engine "upgrade"
