### ISSUE TITLE
VMSS windowspool ResourceNotFound error(but successfully created) when deploy with Az cli 2.0.74

### ISSUE THREAD

**Issue by HuaTang92** [Azure/aks-engine#2514]
**Describe the bug**
After upgrading Az cli from 2.0.72 to 2.0.74(nothing else changed), deployment with generated azuredeploy files failed due to VMSS windowspool was not found. But checked the resourece group and can find the VMSS had been successfully created under the correct resource group.
```
"error": {
  "code": "ResourceNotFound",
  "message": "The Resource 'Microsoft.Compute/virtualMachineScaleSets/xx' under resource group 'xxx' was not found."
}
```
**Steps To Reproduce**

Upgrade az cli 2.0.72 to 2.0.74. 
Run az group deployment create 

**Expected behavior**
deployment can find the windowspool VMSS
**AKS Engine version**
V0.44.0
**Kubernetes version**
1.15.4
**Additional context**

**Comment by CecileRobertMichon** [comment]
@marosset does this ring any bells?

**Comment by mboersma** [comment]
AKS Engine CI has been using `az` CLI 2.0.75 since late October, and 2.0.77 for most of December without incident, just FYI. Is this also a problem with the current 2.0.78 client (that is, did the CLI fix something since 2.0.74)?

**Comment by marosset** [comment]
This does not sound familiar to me.

**Comment by HuaTang92** [comment]
Hi @mboersma, with az cli 2.0.77, I see the same error.

**Comment by marosset** [comment]
I'm using az cli 2.0.77 (on Linux) to deploy windows clusters and not seeing this issue.
@HuaTang92 can you share the aks-engine api model you are using (minus the secrets)?

**Comment by HuaTang92** [comment]
The issue was not with VMSS. It's due to ARM template changed with MSI. Instead of referencing VMSS Identity resource, it should reference the VMSS resource and then get identity. 
Should do this:
```
"tenantId": "[reference('Microsoft.Compute/virtualMachineScaleSets', '2019-03-01', 'Full').identity.tenantId]"
```
instead of 
"tenantId": "[reference(concat(resourceId('Microsoft.Compute/virtualMachineScaleSets'),'/providers/Microsoft.ManagedIdentity/Identities/default'), '2019-03-01').tenantId]"
