### ISSUE TITLE
EnableAcceleratedNetworking helper method is not up to date with list of skus supported

### ISSUE THREAD

**Issue by serbrech** [Azure/aks-engine#2519]
**Describe the bug**
When generating the list of skus supported by aks-engine, the script does not generate the skus that allow accelerated networking.
This list is therefore very outdated. The ideal fix would be to generate the list when running `aks-engine/scripts/azure-const.sh`

**Comment by CecileRobertMichon** [comment]
related to https://github.com/Azure/aks-engine/issues/1894
