### ISSUE TITLE
Update virtual-kubelet image to latest version

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#2539]
**Describe the request**

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
See https://github.com/Azure/aks-engine/pull/2535#issuecomment-571848095

**Comment by mboersma** [comment]
@feiskyer we are currently referencing `virtual-kubelet:latest` when we deploy the aci-connector addon. Is there anything to update?

(I tested this manually after #2535 merged and things seem to be working.)

**Comment by feiskyer** [comment]
@mboersma cool, thanks a lot.
