### ISSUE TITLE
Failure to Create Azure Compliant Clusters

### ISSUE THREAD

**Issue by jaer-tsun** [Azure/aks-engine#2551]
**Describe the issue**
Due to ongoing effort to be Azure compliant, we need to deploy clusters with [specific ssl cipher suite ordering](https://www.1eswiki.com/wiki/SSLScanner_Guide#1.1_OpenSSL_Cipher_Suites). 
The following error is returned when creating a cluster.
![image](https://user-images.githubusercontent.com/13284103/72119607-d46f2f00-3309-11ea-93bc-3ad58eb05048.png)

**AKS Engine Version***
v0.43.3

**Kubernetes Version**
1.14, 1.15

**To Reproduce**
1. Add the following apiServerConfig with the first OpenSSL cipher spec linked above
![image](https://user-images.githubusercontent.com/13284103/72119733-3e87d400-330a-11ea-981b-e306f114952e.png)

2. Deploy the cluster

**Expected behavior**
We should not fail with VMExtension error

**Screenshots**

**Additional context**
I'm unfamiliar with the ordering of the cipher spec, but I've tried this
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
and via [manual scan](https://sslscanner.trafficmanager.net/EndPointDetails.aspx?resultId=656822686&targetID=650056347&hostName=52.177.15.117) we see that we're missing 2 ciphers. After adding those missing ciphers we fail to deploy the cluster.

**Please don't remove the text below**
Notify @az-policy-kube

**Comment by jaer-tsun** [comment]
resolved via scanner changes

**Comment by sozercan** [comment]
@jaer-tsun what did you mean by `resolved via scanner changes`?
