### ISSUE TITLE
Enable telemetry to log to more than one App Insights resource (Linux)

### ISSUE THREAD

**Issue by devigned** [Azure/aks-engine#2575]
Users of aks-engine should be able to take advantage of telemetry too. A user should be able to add their own AppInsights key as well as the aks-engine telemetry endpoint. These telemetry endpoints should be able to be turned on or off independent of each other. That is to say, a user should be able to opt out of sending telemetry to aks-engine and send to only their AppInsights resource.

related to #2415 and #2400, /cc @marosset and @craiglpeters

**Comment by devigned** [comment]
Ok, so after reviewing https://github.com/Azure/aks-engine/blob/master/docs/topics/telemetry.md again, here's what I propose.

We keep the outward api-model exactly that same as has already been defined. That is to say, we will have the following where applicationInsightsKey is the user's App Insights key.
```json
{
  "properties": {
    "featureFlags": {
      "enableTelemetry": true
    },
    "telemetryProfile": {
      "applicationInsightsKey": "7440e089-79e1-4cb4-96b7-d8e9a460eb74"
    }
  }
}
```

Internal to aks-engine, we will also have our own App Insights key which will log telemetry to our AppInsights when `enableTelemetry` is true. The api-model will not contain this key. The key will be held internal to aks-engine and will not be able to be manipulated by a user. This key will either be defined in code or be passed in as a build parameter.

| Telemetry Enabled  | App Insights Key Set | Result |
| ------------- | ------------- | ------------- |
| true | true | both user and aks-e telemetry is tracked |
| false  | true  | no telemetry is tracked |
| true | false | only aks-e telemetry is tracked |
| false | false | no telemetry is tracked |

The above functionality implies the CSE script can accomadate multiple App Insights keys. While this is true for the Linux CSE with the recent release of [v0.5.0 of apmz](https://github.com/devigned/apmz/releases/tag/v0.5.0). This may be more difficult on the Windows side as we are currently using [a single App Insights client which only logs to a single endpoint](https://github.com/Azure/aks-engine/blob/495701a5e0c1b96029843fb9941db4300f5ec081/parts/k8s/kuberneteswindowssetup.ps1#L175). We can solve this problem in multiple ways.
1) we could make a proxy AI client for PS which fronts multiple underlying AI clients
2) we could use apmz on the Windows side as well, but would probably need something like the [Bash eval functionality for PS](https://github.com/devigned/apmz#tracing-and-time-metrics).

For what it's worth, apmz creates multiple AI clients just as option #1 would. I have no strong opinion on either option.

While the ambiguity on Windows implementation is sorted out, I'm going to start on an implementation for Linux which follows these principals.

@marosset and @craiglpeters, I'm super interested in your takes. What do y'all think about this?

**Comment by marosset** [comment]
Just for clarity if an API model loosk like

```json
{
  "properties": {
    "featureFlags": {
      "enableTelemetry": true
    }
}
```
then only aks-e telemetry is gather correct?

And in the Windows case for now we will only be able to collect aks-e telemetry and not user telemetry (because current application insights powershell/.NET classes only allow 1 key to be specified)

Let's make sure to update telemetry.md with this data.

**Comment by marosset** [comment]
Also, I think there are other less-invasive ways to handle multiple app insights publishers for Windows CSE other than 2 mentioned above.
I'll create a separate issue for that.

**Comment by devigned** [comment]
per https://github.com/Azure/aks-engine/issues/2575#issuecomment-577314588, yes. That is precisely what that means. I'll be sure to add that to the telemetry.md doc. I'll also add the truth table from the issue.
