### ISSUE TITLE
slb-enabled akse private cluster upgrade failed 

### ISSUE THREAD

**Issue by vossss** [Azure/aks-engine#2580]
**Describe the bug**
slb-enabled akse  private cluster was upgraded from 1.15.7 to 1.16.1, but the upgrade failed. 
**Steps To Reproduce**
AKS Engine version
0.45.0

Kubernetes version
v1.15.7

1. We created a cluster with this cluster definition:
`{
  "apiVersion": "vlabs",
  "location": "chinanorth2",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.15",
      "orchestratorVersion": "1.15.7",
      "kubernetesConfig": {
        "loadBalancerSku": "Standard",
        "excludeMasterFromStandardLB": true,
        "kubeProxyMode" : "ipvs",
        "networkPlugin": "flannel",
        "privateCluster": {
          "enabled": true,
          "jumpboxProfile": {
             "name": "jumpbox",
             "vmSize": "Standard_D2_v3",
             "osDiskSizeGB": 30,
             "username": "vmadmin",
             "publickey": ""
           }
        },
        "addons": [
        {
            "name": "cluster-autoscaler",
            "enabled": true,
              "config":
                {
              "min-nodes": "5",
              "max-nodes": "10",
              "scan-interval": "10s"
              }
          },
          {
            "name": "heapster",
            "enabled": true
          },
          {
            "name": "dns-autoscaler",
            "enabled": false
          },
          {
            "name": "container-monitoring",
            "enabled": true
          },
          {
            "name": "tiller",
            "enabled": true,
            "containers": [
              {
                "name": "tiller",
                "image": "gcr.azk8s.cn/kubernetes-helm/tiller:v2.13.0",
                "cpuRequests": "50m",
                "memoryRequests": "150Mi",
                "cpuLimits": "50m",
                "memoryLimits": "150Mi"
              }
            ],
            "config": {
              "max-history": "0"
            }
          },
          {
            "name": "blobfuse-flexvolume",
            "enabled": true
          },
          {
            "name": "keyvault-flexvolume",
            "enabled": true
          },
          {
            "name": "kubernetes-dashboard",
            "enabled": true
          },
          {
            "name": "aci-connector",
            "enabled": false
          },
          {
            "name": "smb-flexvolume",
            "enabled": false
          },
          {
            "name": "rescheduler",
            "enabled": false
          },
          {
            "name": "nvidia-device-plugin",
            "enabled": false
          }
        ]
       }
    },
      "masterProfile": {
        "count": 3,
        "dnsPrefix": "aksereh",
        "vmSize": "Standard_D2_v3",
        "vnetSubnetId": "",
        "firstConsecutiveStaticIP": "172.16.1.160",
        "distro": "aks-ubuntu-18.04",
        "customVMTags": {
            "Name": "k8s-master",
            "ProjectID": "ICTO-27027",
            "ApplicationID": "AKSE",
            "ApplicationVersion": "v0.44.2",
            "CostCenterID": "8120020",
            "Role": "Shareservice",
            "SupportContact": ""
        }
      },
      "agentPoolProfiles": [
        {
            "name": "dpcrb",
            "count": 5,
            "vmSize": "Standard_D4s_v3",
            "vnetSubnetId": "",
            "distro": "aks-ubuntu-18.04",
            "availabilityProfile": "VirtualMachineScaleSets",
            "storageProfile": "ManagedDisks",
            "OSDiskSizeGB": 200,
            "customVMTags": {
                "Name": "k8s-vmss",
                "ProjectID": "ICTO-27027",
                "ApplicationID": "AKSE",
                "ApplicationVersion": "v0.44.2",
                "CostCenterID": "8120020",
                "Role": "Shareservice",
                "SupportContact": ""
            }
        }
      ],
      "linuxProfile": {
        "adminUsername": "vmadmin",
        "ssh": {
          "publicKeys": [
            {
              "keyData": ""
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId": "",
        "secret": ""
      },
      "certificateProfile": {}
  }
}
`
1. Upgraded using the following command 
`aks-engine upgrade --azure-env  AzureChinacloud --api-model ./apimodel.json --location chinanorth2 --resource-group xxxx --subscription-id xxx --upgrade-version 1.16.1 --client-id xxx  --client-secret xxx`
2. Failed upgrade, below is error log 
![图片](https://user-images.githubusercontent.com/16187999/72403357-c0ee1900-378c-11ea-9729-3220a3051a0f.png)

**Comment by jackfrancis** [comment]
I can repro this upgrade failure on a private cluster using both Basic and Standard Load Balancer configurations, so it is likely an issue w/ private cluster + upgrade generally.

**Comment by CecileRobertMichon** [comment]
this is the same error that was reported in https://github.com/Azure/acs-engine/issues/4065, unfortunately the issue went stale.

**Comment by mboersma** [comment]
I can reproduce this error by creating a cluster with SLB + private cluster + jumpbox with AKS Engine master.

1. Create a cluster using this apimodel.
    ```json
    {
      "apiVersion": "vlabs",
      "properties": {
        "orchestratorProfile": {
          "orchestratorType": "Kubernetes",
          "orchestratorRelease": "1.15",
          "kubernetesConfig": {
            "loadBalancerSku": "Standard",
            "excludeMasterFromStandardLB": true,
            "privateCluster": {
              "enabled": true,
              "jumpboxProfile": {
                "name": "vm-jumpbox",
                "vmSize": "Standard_D2_v3",
                "username": "azureadmin",
                "publickey": "<insert pub key>"
              }
            }
          }
        },
        "masterProfile": {
          "count": 3,
          "dnsPrefix": "",
          "vmSize": "Standard_D2_v3"
        },
        "agentPoolProfiles": [
          {
            "name": "agentpool1",
            "count": 2,
            "vmSize": "Standard_D2_v3"
          }
        ],
    "linuxProfile": {
      "adminUsername": "azureuser",
          "ssh": {
            "publicKeys": [
              {
                "keyData": ""
              }
            ]
          }
        },
        "servicePrincipalProfile": {
          "clientId": "",
          "secret": ""
        }
      }
    }
    ```
    and a command like this:

    ```shell
   $ ./bin/aks-engine deploy --debug \
      --dns-prefix k8s-jumpbox -f \
      -m ./kubernetes-jumpbox.json \
      -l eastus \
      --client-id=${CLIENT_ID} \
      --client-secret=${CLIENT_SECRET} \
      --set linuxProfile.ssh.publicKeys\[0\].keyData="${AKSE_PUB_KEY}"
    ```

2. Upgrade the cluster with a command like this:

    ```shell
    $ ./bin/aks-engine upgrade --debug \
      -m ./_output/k8s-jumpbox/apimodel.json \
      -b ./_output/k8s-jumpbox/kubeconfig/kubeconfig.eastus.json \
      -k 1.16.1 \
      -g k8s-jumpbox \
      -l eastus \
      --client-id=${CLIENT_ID} \
      --client-secret=${CLIENT_SECRET}
    ```

3. You'll get this error:
    ```shell
    % ./bin/aks-engine upgrade --debug \
    -m ./_output/k8s-jumpbox/apimodel.json \
    -b ./_output/k8s-jumpbox/kubeconfig/kubeconfig.eastus.json \
    -k 1.16.1 \
    -g k8s-jumpbox \
    -l eastus \
    --client-id=${CLIENT_ID} \
    --client-secret=${CLIENT_SECRET}
    INFO[0000] No subscription provided, using selected subscription from azure CLI: abcdefg-123456789 
    DEBU[0000] Resolving tenantID for subscriptionID: abcdefg-1234567689 
    DEBU[0003] Already registered for "Microsoft.Compute"   
    DEBU[0003] Already registered for "Microsoft.Storage"   
    DEBU[0003] Already registered for "Microsoft.Network"   
    INFO[0004] Upgrading cluster with name suffix: 95960914 
    INFO[0004] VM k8s-agentpool1-95960914-vmss_0 in VMSS k8s-agentpool1-95960914-vmss has a current version of 1.15.7 and a desired version of 1.16.1. Upgrading this node. 
    INFO[0004] VM k8s-agentpool1-95960914-vmss_1 in VMSS k8s-agentpool1-95960914-vmss has a current version of 1.15.7 and a desired version of 1.16.1. Upgrading this node. 
    INFO[0005] Master VM name: k8s-master-95960914-0, orchestrator: 1.15.7 (MasterVMs) 
    INFO[0005] Master VM name: k8s-master-95960914-1, orchestrator: 1.15.7 (MasterVMs) 
    INFO[0005] Master VM name: k8s-master-95960914-2, orchestrator: 1.15.7 (MasterVMs) 
    INFO[0005] Skipping VM: vm-jumpbox for upgrade as it does not belong to cluster with expected name suffix: 95960914 
    INFO[0005] Upgrading to Kubernetes version 1.16.1       
    INFO[0005] Master nodes StorageProfile: ManagedDisks    
    INFO[0005] Prepping master nodes for upgrade...         
    INFO[0005] Resource count before running NormalizeResourcesForK8sMasterUpgrade: 16 
    INFO[0005] Removing nsg resource: [variables('nsgName')] from template 
    INFO[0005] Removing Microsoft.Compute/availabilitySets dependency from [parameters('jumpboxVMName')] 
    INFO[0005] Evaluating if agent pool: <nil>, resource: [parameters('jumpboxVMName')] needs to be removed 
    INFO[0005] Removing nsg resource: [variables('jumpboxNetworkSecurityGroupName')] from template 
    INFO[0005] Removing nic: [variables('jumpboxNetworkInterfaceName')] from template 
    INFO[0005] Removing Microsoft.Compute/availabilitySets dependency from [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))] 
    INFO[0005] Evaluating if agent pool: master, resource: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))] needs to be removed 
    INFO[0005] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', '-master-', copyIndex(variables('masterOffset')))] needs to be removed 
    INFO[0005] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/computeAksLinuxBilling')] needs to be removed 
    INFO[0005] Resource count after running NormalizeResourcesForK8sMasterUpgrade: 12 
    INFO[0005] Removing singlePlacementGroup property from [variables('agentpool1VMNamePrefix')] 
    INFO[0005] Total expected master count: 3               
    INFO[0005] Master nodes that need to be upgraded: 3     
    INFO[0005] Master nodes that have been upgraded: 0      
    INFO[0005] Starting upgrade of master nodes...          
    INFO[0005] masterNodesInCluster: 3                      
    INFO[0005] Expected master count: 3, Creating 0 more master VMs 
    INFO[0005] Upgrading Master VM: k8s-master-95960914-0   
    INFO[0005] deleting VM k8s-master-95960914-0 in resource group k8s-jumpbox ... 
    INFO[0336] deleting NIC k8s-master-95960914-nic-0 in resource group k8s-jumpbox ... 
    INFO[0346] deleting managed disk k8s-master-95960914-0_OsDisk_1_619ce909b41c4f079de6c5e0dc383189 in resource group k8s-jumpbox ... 
    INFO[0407] Master offset: 0                             
    INFO[0407] Master pool set count to: 1 temporarily during upgrade... 
    INFO[0407] Starting ARM Deployment master-20-01-21T10.16.14-1522497474 in resource group k8s-jumpbox. This will take some time... 
    INFO[0408] Error creating upgraded master VM: k8s-master-95960914-0 
    Error: upgrading cluster: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplate" Message="Deployment template validation failed: 'The resource 'Microsoft.Network/networkInterfaces/vm-jumpbox-nic' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'." AdditionalInfo=[{"info":{"lineNumber":0,"linePosition":0,"path":""},"type":"TemplateViolation"}]
    Usage:
    aks-engine upgrade [flags]

    Flags:
    -m, --api-model string            path to the generated apimodel.json file
        --auth-method client_secret   auth method (default:client_secret, `cli`, `client_certificate`, `device`) (default "client_secret")
        --azure-env string            the target Azure cloud (default "AzurePublicCloud")
        --certificate-path string     path to client certificate (used with --auth-method=client_certificate)
        --client-id string            client id (used with --auth-method=[client_secret|client_certificate])
        --client-secret string        client secret (used with --auth-method=client_secret)
        --cordon-drain-timeout int    how long to wait for each vm to be cordoned in minutes (default -1)
    -f, --force                       force upgrading the cluster to desired version. Allows same version upgrades and downgrades.
    -h, --help                        help for upgrade
        --identity-system azure_ad    identity system (default:azure_ad, `adfs`) (default "azure_ad")
    -b, --kubeconfig string           the path of the kubeconfig file
        --language string             language to return error messages in (default "en-us")
    -l, --location string             location the cluster is deployed in (required)
        --private-key-path string     path to private key (used with --auth-method=client_certificate)
    -g, --resource-group string       the resource group where the cluster is deployed (required)
    -s, --subscription-id string      azure subscription id (required)
    -k, --upgrade-version string      desired kubernetes version (required)
        --vm-timeout int              how long to wait for each vm to be upgraded in minutes (default -1)

    Global Flags:
        --debug   enable verbose debug logs
    ```
