### ISSUE TITLE
Use VM scheduled events to cordon and drain in K8s

### ISSUE THREAD

**Issue by devigned** [Azure/aks-engine#2584]
**Describe the request**
When using VMSS, it would be super awesome if K8s would get alerted to cordon and drain nodes that were getting reaped especially in the case of Azure low priority or spot priority types.

@awesomenix created https://github.com/awesomenix/drainsafe and looks pretty promising for alerting K8s via scheduled events on the node.

/cc @jackfrancis

**Comment by awesomenix** [comment]
Its already part of addons (which customer can choose to optionally enable) under [`scheduled-maintenance`](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#addons)
