### ISSUE TITLE
Create gen2 compatable aks-engine VHDs 

### ISSUE THREAD

**Issue by marosset** [Azure/aks-engine#2601]
Create gen2 compatable aks-engine VHDs because some new VM skus (DC series for example) with useful features like SGX  only support gen2 VMs and current aks-engine VHDs are only compatible with Gen1 VMs.

We could either
- Create gen1 and gen2 VHDs for currently supported OS skus (Ubuntu 16.04, Ubuntu 18.04, WS2019)
- Only create gen2 VHDs for new OS skus (Ubuntu 20.04, windows vNext)
- Switch existing OS skus to gen2 images

A few data points:
- VHDs can only be booted by specific VM generations in Hyper-V (Gen1 only supports booting from MBR partitioned VHD images while Gen2 only supports booting from GPT portioned VHD images)
- Some older VM skus only support gen1 VMs

For now customers can use non-aks engine gen2 VHDs from Canonical/Microsoft to work on gen2 only VM skus.

**Comment by marosset** [comment]
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/generation-2#generation-2-vm-sizes lists which VM sizes support gen2 VMs

**Comment by rbitia** [comment]
@marosset are there any blockers for this issue becoming a PR in the future? :D

**Comment by marosset** [comment]
Yes - Marketplace Image publishing currently only supports publishing images from classic storage accounts and Packer (which we use to build our VHDs) does not support writing Gen2 VHDs to classic storage accounts.
We either need Marketplace to support publishing from Manager Images or a SIG or Packer needs to be able to create Gen2 VHDs in classic storage accounts.
