### ISSUE TITLE
Unable to add windows node pool to existing aks cluster with default node pool attached to custom vnet

### ISSUE THREAD

**Issue by kannappan-v** [Azure/aks-engine#2609]
**Describe the bug**

We are unable to add windows node pool to aks cluster with default node pool that is attached to custom vnet. Below is the error code related to "vmss reconcile".
```
msrest.http_logger : {
  "name": "aee375cf-4f42-fe4f-946e-95aa2476e603",
  "status": "Failed",
  "startTime": "2020-01-21T09:32:54.7450832Z",
  "endTime": "2020-01-21T09:39:40.2874612Z",
  **"error": {
   "code": "ReconcileVMSSAgentPoolFailed",
   "message": "We are unable to serve this request due to an internal error, Correlation ID: 6d54e404-5e74-489a-bda8-46708a7976fd, Operation ID: cf75e3ae-424f-4ffe-946e-95aa2476e603, Timestamp: 2020-01-21T09:39:39Z."**
  }
 }
msrest.exceptions : We are unable to serve this request due to an internal error, Correlation ID: 6d54e404-5e74-489a-bda8-46708a7976fd, Operation ID: cf75e3ae-424f-4ffe-946e-95aa2476e603, Timestamp: 2020-01-21T09:39:39Z.
cli.azure.cli.core.util : Deployment failed. Correlation ID: b245b59a-e1b1-40ae-8f29-1bb1be1b1c52. We are unable to serve this request due to an internal error, Correlation ID: 6d54e404-5e74-489a-bda8-46708a7976fd, Operation ID: cf75e3ae-424f-4ffe-946e-95aa2476e603, Timestamp: 2020-01-21T09:39:39Z.
Deployment failed. Correlation ID: b245b59a-e1b1-40ae-8f29-1bb1be1b1c52. We are unable to serve this request due to an internal error, Correlation ID: 6d54e404-5e74-489a-bda8-46708a7976fd, Operation ID: cf75e3ae-424f-4ffe-946e-95aa2476e603, Timestamp: 2020-01-21T09:39:39Z.
```
**Steps To Reproduce**
1) Execute below commands to create aks cluster that is attached to custom vnet- command Execution is success. **No problems found in default Linux node pool**.

az aks create \
    --resource-group ***** \
    --name **** \
    --node-count * \
    --enable-addons monitoring \
    --kubernetes-version 1.15.7 \
    --generate-ssh-keys \
    --windows-admin-password $PASSWORD_WIN \
    --windows-admin-username azureuser \
    --vm-set-type VirtualMachineScaleSets \
    --load-balancer-sku standard \
    --network-plugin azure \
    --vnet-subnet-id *****
    --service-principal **** \
    --client-secret ******
2) Add windows node pool to above existing cluster . Execution is failed. **Error in windows vmss deployment**

az aks nodepool add \
    --resource-group ****** \
    --cluster-name ******* \
    --os-type Windows \
    --name npwin \
    --node-count 1 \
    --kubernetes-version 1.15.7 \

```
msrest.http_logger : {
  "name": "aee375cf-4f42-fe4f-946e-95aa2476e603",
  "status": "Failed",
  "startTime": "2020-01-21T09:32:54.7450832Z",
  "endTime": "2020-01-21T09:39:40.2874612Z",
  **"error": {
   "code": "ReconcileVMSSAgentPoolFailed",
   "message": "We are unable to serve this request due to an internal error, Correlation ID: 6d54e404-5e74-489a-bda8-46708a7976fd, Operation ID: cf75e3ae-424f-4ffe-946e-95aa2476e603, Timestamp: 2020-01-21T09:39:39Z."**
```

**Expected behavior**
Windows node pool should be added to existing aks cluster which is attached to custom vnet
**AKS Engine version**
version - 0.45.0-1-aks
**Kubernetes version**
1.15.7

**Comment by devigned** [comment]
Hi @kannappan-v, 

Thank you for reaching out about this error. I'm sorry, but I'm a little confused by this issue. It appears you are using AKS via Azure CLI, not aks-engine. They are related projects, but distinctly different. 

If you are using AKS, the Azure Service, you'd be best served to [open a ticket with Azure Support](https://azure.microsoft.com/en-us/support/create-ticket/).

If this is really about aks-engine, please elaborate a bit on where aks-engine is in use.

/cc for AKS awareness @palma21

**Comment by palma21** [comment]
Also CC @MikkelHegn

**Comment by MikkelHegn** [comment]
Briefly looking at the deployment, the Custom Script Extension which installs K8 on the Windows nodes failed, but I don't have more data than that. To get the data we need you to set up a supprot case.

Thanks.
