### ISSUE TITLE
How to turn on alertmanager = true in apiModel file ?

### ISSUE THREAD

**Issue by sd2302** [Azure/aks-engine#2616]
**Describe the bug**

How to turn on alertmanager = true in apiModel file ?

**Steps To Reproduce**

"extensionProfiles": [
      {
        "name": "prometheus-grafana-k8s",
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/aks-engine/master/"
        "extensionParameters": "monitoring;;" 
      }
    ],

**Expected behavior**

**AKS Engine version**

Version: v0.45.0
GitCommit: b5efa8642
GitTreeState: clean

**Kubernetes version**

1.15.4
**Additional context**

we need to turn on alertmanger=true in prometheus_values.yaml but unable to find our how to override the default value using extensionParameters

**Comment by jackfrancis** [comment]
Hi @sd2303, what you can do is fork Azure/aks-engine into your personal github account, create a branch, manually change the yaml file in `extensions/prometheus-grafana-k8s/v1/prometheus_values.yaml` on your fork+branch, and then change the `rootURL` to point to your fork + branch:

"rootURL": "https://raw.githubusercontent.com/sd2303/aks-engine/<branch>/"

The aks-engine template generator will then source the data from your fork to compose the resultant extensions that will attach to your master vms at cluster provisioning time (ARM deployment).

Does that add up?

**Comment by jackfrancis** [comment]
See https://github.com/Azure/aks-engine/blob/master/docs/topics/extensions.md for more info, and let us know if the docs need any TLC (feel free to submit a PR w/ changes as well if you struggle through this based on the docs not being 100% clear/accurate!)

**Comment by sd2302** [comment]
Thanks @ jackfrancis

I will give this a shot.
