### ISSUE TITLE
kata-containers broken for Ubuntu 16.04-LTS

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2618]
The download URL we depend upon for Ubuntu 16.04-LTS + kata-containers no longer exists. See:

http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.7/

(Note the lack of a `xUbuntu_18.04/` subdir)

**Comment by CecileRobertMichon** [comment]
https://github.com/kata-containers/documentation/tree/master/install#supported-distributions

**Comment by jackfrancis** [comment]
Filed https://github.com/kata-containers/kata-containers/issues/128
