### ISSUE TITLE
Automate subnet configuration for the kubenet + BYO-VNET use case

### ISSUE THREAD

**Issue by jadarsie** [Azure/aks-engine#2621]
**Describe the request**
It would be more convenient for users if we could simplify kubenet+BYO-VNET deployments.  

Right now, it is required to [manually set the subnet's route table](https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#kubenet-networking-custom-vnet) once the deployment completes.

**Comment by popsikle** [comment]
Its not hard to do in a bash script (yes, it should be part of aks-engine imho) but we just drop this into our bootstrap script that kicks off a cluster.  We use terraform for RG+VNET+SN creation, so we can dont need to look up vnets or anything but you could do it with like jq or something.


```# We need to add the k8s route table to the subnets for pod to pod communication to work
ROUTE_TABLE=$(az network route-table list -g "${RG_NAME}" -o json --subscription "${SUBSCRIPTION}" | jq -r '.[].id' | grep k8s)
ROUTE_TABLE_NAME=$(basename $ROUTE_TABLE)
VNET_NAME="${RG_NAME/RG/VNET-rg}"

# Add the vnets to the k8s route table
az network vnet subnet update -n "${RG_NAME/RG/SN}-compute" -g "${RG_NAME}" --vnet-name ${VNET_NAME} --route-table ${ROUTE_TABLE} --subscription "${SUBSCRIPTION}"
az network vnet subnet update -n "${RG_NAME/RG/SN}-master"  -g "${RG_NAME}" --vnet-name ${VNET_NAME} --route-table ${ROUTE_TABLE} --subscription "${SUBSCRIPTION}"
```

**Comment by jackfrancis** [comment]
@jadarsie would you like me to keep this open? I don't think we'll prioritize this work, and I don't see anyone volunteering to do it.

**Comment by jadarsie** [comment]
someone should pick it up eventually, probably @deaborch
