### ISSUE TITLE
az aks browse now results in ERR_CERT_INVALID on 1.17 cluster

### ISSUE THREAD

**Issue by eox-dev** [Azure/aks-engine#2622]
```
az aks browse -g <resource_group> -n <aks_name>
```
This was working on a 1.14 I had. Made a 1.17 and now this doesn't seem to work. Just get this error:

![image](https://user-images.githubusercontent.com/59094233/73087092-cb906880-3e86-11ea-903f-e4067011a1a3.png)

Tried incognito, clear browse cache, [reseting the credentials](https://docs.microsoft.com/en-us/azure/aks/update-credentials), and also made sure to [ClusterRoleBinding](https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#start-the-kubernetes-dashboard).

Not sure what else to do at this point. Perhaps just an issue with 1.17 and I should just revert back.

**Comment by jackfrancis** [comment]
Hi @eox-dev, this issue queue is for `aks-engine` specifically, which doesn't speak to the issue you're having w/ `az aks` (an AKS cluster).

There is an AKS issue queue:

https://github.com/Azure/AKS/issues

Additionally, AKS is a managed service, meaning that you may open up an Azure support issue via the standard channels, and your request will be routed back to an AKS engineer.
