### ISSUE TITLE
Enable "mode" configuration for all addons

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2672]
Like the `cluster-autoscaler` addon, we should allow user-configurable `Reconcile` or `EnsureExists`.

**Comment by tommyJimmy87** [comment]
@jackfrancis Do you have any news on this? Thanks.

**Comment by davidbIQ** [comment]
same question for me, I could edit this until a day or 2 ago?

**Comment by bridgetkromhout** [comment]
Consulted @jackfrancis and given the AKS Engine deprecation, we're not going to make this change.
