### ISSUE TITLE
NSG Service tag for AKS

### ISSUE THREAD

**Issue by tdelfairere** [Azure/aks-engine#2691]
According to https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic, AKS requires some specific flow in order to work properly.

Those flow filtering are based on TCP/UDP ports and FQDN  based destination.

Nevertheless, Network Security Group does not support FQDN. So it implies to allow full internet flows.

Could you implement a specific service tag in the NSG which could be used in the NSG to allow only the required eggress traffic?

**Comment by hakabo** [comment]
+1  for this.
As described above, without a service tag we're having to let all traffic out through the NSG. We would ideally like to be specific with the traffic that we let out. 
Please reopen - thanks.
