### ISSUE TITLE
Allow for pulling customHyperkubeImage from private repository

### ISSUE THREAD

**Issue by jsturtevant** [Azure/aks-engine#271]
**Is this a request for help?**: 
---
no

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
feature request

**What version of acs-engine?**:
---
any

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kuberentes 

**What happened**:
Would like to be able to pull `customHyperkubeImage` as describe in https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/k8s-developers.md from a private Azure Container Registry. 

Would it be possible to pass Service Principle credentials or use MSI to pull the image?  What would be the effort for making this possible?

Looks like this happens in https://github.com/Azure/acs-engine/blob/8b616722debcddaf0d0d9d2baa605bb7aa77eddb/parts/k8s/kubernetesinstalls.sh#L178:1

**Anything else we need to know**:
cc: @PatrickLang and @ritazh.

**Comment by jchauncey** [comment]
Definitely think this is an issue we should consider. When building private hyperkube images from our CI system for testing I would rather not put those in a public repo. Instead it would be great to place them in ACR which is private only. Cursory thoughts on how we might possibly do this is to just have an extension do a docker login with some provided credentials. Thoughts?
