### ISSUE TITLE
Kubelet server should not use a self signed certificate

### ISSUE THREAD

**Issue by PascalVA** [Azure/aks-engine#2737]
**Describe the bug**
By default, when deploying a new cluster, the kubelet on each node generates a self-signed certificate and uses it for the kubelet server. The kubelet certificates should be generated from the CA that issues the kube-apiserver certificates (or another CA if preferred). The  **--kubelet-certificate-authority** flag should then be set on the apiserver flag to make sure connections are properly verified.

The user can choose to manage their own kubelet certificates to get around this, but it would be better if the default deployment included this.

**Steps To Reproduce**
Deploy an aks-engine cluster without specifying the **--tls-cert-file** and **--tls-private-key-file** for kubelet.

**Expected behavior**
Kubelet should not use a self-signed certificate because this prohibits the kube-apiserver to validate the certificate (using the **--kubelet-certificate-authority** flag).

**AKS Engine version**
0.46.3

**Kubernetes version**
1.17.0

**Comment by PascalVA** [comment]
When this is fixed, `--kubelet-insecure-tls` can also be removed from the config of metrics-server

**Comment by hannesg** [comment]
This issue is very annoying because e.g. Datadog doesn't work out of the box. Please reconsider this bug.

**Comment by kiss-less** [comment]
@hannesg we are facing exactly the same problem with Datadog, but our AKS cluster with self-signed kubelet certificates is already up and running. Could you please clarify how did you resolve the problem? Is it mandatory to re-deploy the cluster with the kubelet-certificate-authority flag, or it can be changed on the fly somehow? Thanks in advance!

**Comment by idanme-tr** [comment]
> This issue is very annoying because e.g. Datadog doesn't work out of the box. Please reconsider this bug.



> @hannesg we are facing exactly the same problem with Datadog, but our AKS cluster with self-signed kubelet certificates is already up and running. Could you please clarify how did you resolve the problem? Is it mandatory to re-deploy the cluster with the kubelet-certificate-authority flag, or it can be changed on the fly somehow? Thanks in advance!

I am having the same problem with Datadog, would love if you guys could share a solution if you come across one.
I'll do the same, thanks!

**Comment by mikenri** [comment]
I realize this is an old thread but did anyone ever get this sorted out?
For now when using datadog we need to confirm it to not verify the certificate due to the self signing issue.

**Comment by dploeger** [comment]
Can this be reopened please? Either enable this feature or give the kubelets a publicly known certificate or a certificate from the same CA as the API server.

**Comment by fightwithpen** [comment]
I ran into same issue. 
My setup is behind a firewall where nodes cannot access the web.
I setup a  local repo/artifactory added required images to it.
I created a self signed cert for artifactory as this is only for testing.  
When I try to run a container using an image from local repo

apiVersion: v1
kind: Pod
metadata:
  name: splunk
  labels:
    app: splunk
spec:
  containers:
    - name: app
      image: x.x.x.x/splunk
        #imagePullPolicy: Never



 I get this message


_Failed to pull image "x.x.x.x/splunk": rpc error: code = Unknown desc = failed to pull and unpack image "x.x.x.x/splunk:latest": failed to resolve reference "x.x.x.x/splunk:latest": failed to do request: Head "https://x.x.x.x/v2/splunk/manifests/latest": x509: certificate signed by unknown authority_

I have not found any way to add my self signed cert to kubelet trust store. Please advise if anyone has a solution.
