### ISSUE TITLE
Packer user not fully cleaned up after cluster deploy (cloud init?)

### ISSUE THREAD

**Issue by PascalVA** [Azure/aks-engine#2740]
**Describe the bug**
When deploying a new cluster, the packer user and its home directory are cleaned up. However, the packer user remains in the sudoers with NOPASSWD even though the user does not exist.
```
root@k8s-master-xxxxxxxx-0:~# grep -R packer /etc
/etc/sudoers.d/90-cloud-init-users:# User rules for packer
/etc/sudoers.d/90-cloud-init-users:packer ALL=(ALL) NOPASSWD:ALL
```

**Steps To Reproduce**
Deploy a kubernetes cluster, log in to a node and run:
```
sudo grep -R packer /etc
```

**Expected behavior**
packer should not be in **/etc/sudoers.d/90-cloud-init-users** even if the user does not exist.

**AKS Engine version**
0.46.3

**Kubernetes version**
1.17.0

**Comment by jackfrancis** [comment]
@CecileRobertMichon, is this a gap we can address, or is there something about the packer + VHD process that makes this especially difficult/tricky?

**Comment by CecileRobertMichon** [comment]
It shouldn't be, and I'm surprised this is the case it should be taken care of in the deprovision step, https://github.com/Azure/aks-engine/blob/master/vhd/packer/vhd-image-builder.json#L216 not sure why it isn't.
