### ISSUE TITLE
Support a configuration that does not add service principal to worker nodes

### ISSUE THREAD

**Issue by shliderm** [Azure/aks-engine#2747]
**Describe the request**
The current behavior of AKS-engine is to push service principal credentials to all nodes in the cluster.
In a multi tenant scenario, it is desirable to disallow azure credentials from the nodes.
One such scenario is a case where some nodes in the cluster expose external-facing API endpoints, and thus can be more easily compromised. Once compromised, it's better that the attacker won't have access to the ARM resources the service principal has access to.

More specifically, it would be beneficial to have the service principal available to the master node, but not to the worker nodes

**Explain why AKS Engine needs it**
This feature will provide an additional configuration option for customers that will provide a secure cluster configuration for customers that can get to a situation where untrusted code runs on worker nodes.

**Describe the solution you'd like**
We would like to be able to configure this by agent pool. as part of agent pool configuration we would like to have the following config key
`install-service-identity=false `  (for example).
for all vms in agent pool that have this configuration key set to false,  service principal won't be provisioned. We do want that the Master node will have the service principle installed. 

**Describe alternatives you've considered**
N/A

**Additional context**
In our case we are going to run 3rd party OSS software on the worker node - code that we did not write and we do not trust. if the node is compromised we want to make sure there is no privilege escalation in this case. 
If the node has a service principle installed on it the hacker will be able to use it to access ARM resources and we want to prevent this from occurring. 
The application that runs on worker nodes does not require access to any ARM resource.

**Comment by devigned** [comment]
Should we require the flag to opt out or opt into having identities on all of the nodes. Upon first thought, it seems like we should default to only having credentials or managed identities on the master nodes.

Anyone have any opinions on this?

**Comment by jackfrancis** [comment]
@devigned without thinking deeply about this, I agree that my bias is to assume the current way we do things (paving creds onto worker nodes) as "wrong", and we should fix that.
