### ISSUE TITLE
Issue while deploying AKS-engine using latest binary version.

### ISSUE THREAD

**Issue by vinaycs0035** [Azure/aks-engine#2758]
Not able to create AKS-ENGINE with latest version.Below is the error i am facing.

**cli.azure.cli.core.util : Deployment failed.. {
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter publisher is invalid.",
    "target": "publisher"
  }
}**

And i assume that error refers to the Publisher Parameter related to **extensions** config of ARM template.

Below is config related to one of the extensions inside the ARM template:
    _**{
      "apiVersion": "[variables('apiVersionCompute')]",
      "copy": {
        "count": "[sub(variables('masterCount'), variables('masterOffset'))]",
        "name": "vmLoopNode"
      },
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))]",
        "[concat('Microsoft.KeyVault/vaults/', variables('clusterKeyVaultName'))]"
      ],
      "location": "[variables('location')]",
      "name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', '-master-', copyIndex(variables('masterOffset')))]",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "protectedSettings": {
          "commandToExecute": ""
        },
        "publisher": "Microsoft.Azure.Extensions",
        "settings": {},
        "type": "CustomScript",
        "typeHandlerVersion": "2.0"
      },
      "tags": {},
      "type": "Microsoft.Compute/virtualMachines/extensions"
    },**_
    
Below is how the Input JSON looks like:

_{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.17",
      "orchestratorVersion": "1.17.1",
      "kubernetesConfig": {
        "enableRbac": true,
        "enableSecureKubelet": true,
        "enableAggregatedAPIs": true,
        "networkPlugin": "kubenet",
        "clusterSubnet": "",
        "serviceCidr": "",
        "dnsServiceIP": "",
        "dockerBridgeSubnet": "",
        "etcdDiskSizeGB": "",
        "privateCluster": {
          "enabled": true
        },
        "kubeletConfig": {
          "--non-masquerade-cidr": "",
          "--feature-gates": "PodPriority=true"
        },
        "apiServerConfig": {
          "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
        },
        "useInstanceMetadata": false,
        "enableEncryptionWithExternalKms": true,
        "cloudProviderRateLimit": false,
        "cloudProviderRateLimitBucket": 0,
        "cloudProviderRateLimitQPS": 0,
        "addons": [
          {
            "name": "blobfuse-flexvolume",
            "enabled" : false
          },
          {
            "name": "smb-flexvolume",
            "enabled" : false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled" : false
          },
          {
            "name": "nvidia-device-plugin",
            "enabled" : false
          },
          {
            "name": "azure-cni-networkmonitor",
            "enabled" : false
          },
          {
           "name": "ip-masq-agent",
           "enabled" : false
          }
        ]
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "test",
      "distro": "ubuntu",
      "vmSize": "Standard_D4s_v3",
      "vnetSubnetId": "",
      "availabilityProfile": "AvailabilitySet",
      "firstConsecutiveStaticIP": "",
      "OSDiskSizeGB": ,
      "extensions": [
        {
          "name": "test1",
          "singleOrAll": "All"
        }
     ]
    },
    "agentPoolProfiles": [
      {
        "name": "",
        "count": ,
        "distro": "ubuntu",
        "vmSize": "Standard_D16s_v3",
        "vnetSubnetId": "",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile" : "ManagedDisks",
        "diskSizesGB": [],
        "OSDiskSizeGB": ,
        "acceleratedNetworkingEnabled": ,
        "preProvisionExtension": {
            "name": "test2",
            "singleOrAll": "All"
        },
        "extensions": [
          {
            "name": "test1",
            "singleOrAll": "All"
          }
       ]
      }
    ],
    "extensionProfiles": [
      {
          "name": "test1",
          "version": "v1",
          "rootURL": "https://test01.blob.core.windows.net/",
          "script": "test1.sh",
          "urlQuery": ""
      },
      {
          "name": "test2",
          "version": "v5",
          "extensionParameters": " ",
          "rootURL": "https://test2.blob.core.windows.net/",
          "script": "test2.sh",
          "urlQuery": ""
      }
    ],
    "linuxProfile": {
      "adminUsername": "",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "aadProfile": {
      "clientAppID": 
      "serverAppID": 
      "tenantID": "
      "adminGroupID": 
    },
    "servicePrincipalProfile": {
      "clientId": 
      "secret": 
      "objectId": 
    }
  }
}_

**AKS Engine version**
v0.46.3

**Kubernetes version**
1.17.1

**Additional context**
I am struggling to figure out the issue since 4 days. I have also tried to use the older version and i am still facing the same issue.

**Comment by jackfrancis** [comment]
Hi @vinaycs0035, it doesn't look like these URLs are valid, which should be according to your spec:

- https://test01.blob.core.windows.net/extensions/test1/v1/test1.sh
- https://test2.blob.core.windows.net/extensions/test2/v5/test2.sh

**Comment by vinaycs0035** [comment]
@jackfrancis  I have only modified the blob and script names, instead of giving the details the ones(what i use). But Can you let me know whats the issue with the URL or the info ??

**Comment by jackfrancis** [comment]
Those URLs are responding w/ 404.

**Comment by vinaycs0035** [comment]
Yeah!! Accessing those URL's doesn't work, because i didnot want to give Valid URL's.
 But i still feel, AKSengine binary is creating the ARM template in wrong way.(especially the **extensionsprofiles** block that we give in the input JSON).

For one the extensionsProfles, this is block generated in the ARM template (using latest binary).

    **{
      "apiVersion": "[variables('apiVersionCompute')]",
      "copy": {
        "count": "[sub(variables('test'), variables('test'))]",
        "name": "vmLoopNode"
      },
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('testVMNamePrefix'), copyIndex(variables('test')), '/extensions/cse-agent-', copyIndex(variables('testOffset')))]"
      ],
      "location": "[resourceGroup().location]",
      "name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/test', '-', 'agent', '-', copyIndex(variables('masterOffset')))]",
      "properties": {},
      "type": "Microsoft.Compute/virtualMachines/extensions"
    }
  ],**

In the above _extensionProfiles_ block, the **properties parameter has the Value as empty**.

But earlier when we created Cluster with Older version of AKS engine BINARY using same input JSON, below is the extensionProfiles part of generated ARM template. 
This doesnot have the **Properties Parameter's Value as empty.**

**{
"apiVersion": "[variables('apiVersionCompute')]",
      "copy": {
        "count": "[sub(variables('masterCount'), variables('masterOffset'))]",
        "name": "vmLoopNode"
      },
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/extensions/cse-master-', copyIndex(variables('masterOffset')))]"
      ],
      "location": "[resourceGroup().location]",
      "name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/test', '-', 'master', '-', copyIndex(variables('masterOffset')))]",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "protectedSettings": {
          "storageAccountKey": *******",
          "storageAccountName": "test"
        },
        "publisher": "Microsoft.Azure.Extensions",
        "settings": {
          "commandToExecute": "[concat('/bin/bash -c \"/bin/bash ./test.sh ', parameters('bootstrapParameters'), ' >> /var/log/azure/test.log 2>&1 &\" &')]",
          "fileUris": [
                        ***********
                       *********
          ]
        },
        "type": "CustomScript",
        "typeHandlerVersion": "2.0"
      },
      "type": "Microsoft.Compute/virtualMachines/extensions"
    }**

**Comment by jackfrancis** [comment]
This is the code flow where the master extension is compose for extensionProfiles:

 https://github.com/Azure/aks-engine/blob/master/pkg/engine/engine.go#L1036

It's a bit dusty here, as this is not actively maintained due to its not working w/ `aks-engine upgrade`, if you see something that looks wrong there or has regressed, let us know!
