### ISSUE TITLE
container-monitoring addon doesn't work w/ containerd

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2764]
This is probably known, but documenting here as a PSA.

Specifically:

```
$ kubectl describe pod omsagent-4srlc -n kube-system completed in 928.194641ms
 Name:                 omsagent-4srlc
 Namespace:            kube-system
 Priority:             2000001000
 Priority Class Name:  system-node-critical
 Node:                 k8s-master-23710449-0/10.255.255.5
 Start Time:           Fri, 21 Feb 2020 19:06:03 +0000
 Labels:               component=oms-agent
                       controller-revision-hash=658657d844
                       pod-template-generation=1
                       tier=node
 Annotations:          agentVersion: 1.10.0.1
                       dockerProviderVersion: 8.0.0-2
                       kubernetes.io/psp: privileged
                       schema-versions: v1
 Status:               Running
 IP:                   10.240.0.106
 IPs:
   IP:           10.240.0.106
 Controlled By:  DaemonSet/omsagent
 Containers:
   omsagent:
     Container ID:  containerd://ffe086f9ef2f338ea81f234158d48e2a438af836d26251b9a3a1b43dcfa63ab9
     Image:         mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod01072020
     Image ID:      mcr.microsoft.com/azuremonitor/containerinsights/ciprod@sha256:6a00d818e129b956a22b723e5543a6cdad1431666c090ea5e3676001a921c539
     Ports:         25225/TCP, 25224/UDP
     Host Ports:    0/TCP, 0/UDP
     State:         Running
       Started:     Fri, 21 Feb 2020 19:30:50 +0000
     Last State:    Terminated
       Reason:      Error
       Message:     agent or fluentbit not running
 
       Exit Code:    143
       Started:      Fri, 21 Feb 2020 19:26:50 +0000
       Finished:     Fri, 21 Feb 2020 19:30:48 +0000
     Ready:          True
     Restart Count:  6
     Limits:
       cpu:     1
       memory:  750Mi
     Requests:
       cpu:     150m
       memory:  250Mi
     Liveness:  exec [/bin/bash -c /opt/livenessprobe.sh] delay=60s timeout=1s period=60s #success=1 #failure=3
     Environment:
       NODE_IP:             (v1:status.hostIP)
       ACS_RESOURCE_NAME:  kubernetes-southeastasia-42983
       CONTROLLER_TYPE:    DaemonSet
       ISTEST:             true
     Mounts:
       /etc/config/settings from settings-vol-config (rw)
       /etc/kubernetes/host from azure-json-path (rw)
       /etc/omsagent-secret from omsagent-secret (ro)
       /hostfs from host-root (ro)
       /var/lib/docker/containers from containerlog-path (rw)
       /var/log from host-log (rw)
       /var/run/host from docker-sock (rw)
       /var/run/secrets/kubernetes.io/serviceaccount from omsagent-token-f4zvk (ro)
 Conditions:
   Type              Status
   Initialized       True 
   Ready             True 
   ContainersReady   True 
   PodScheduled      True 
 Volumes:
   host-root:
     Type:          HostPath (bare host directory volume)
     Path:          /
     HostPathType:  
   docker-sock:
     Type:          HostPath (bare host directory volume)
     Path:          /var/run
     HostPathType:  
   container-hostname:
     Type:          HostPath (bare host directory volume)
     Path:          /etc/hostname
     HostPathType:  
   host-log:
     Type:          HostPath (bare host directory volume)
     Path:          /var/log
     HostPathType:  
   containerlog-path:
     Type:          HostPath (bare host directory volume)
     Path:          /var/lib/docker/containers
     HostPathType:  
   azure-json-path:
     Type:          HostPath (bare host directory volume)
     Path:          /etc/kubernetes
     HostPathType:  
   omsagent-secret:
     Type:        Secret (a volume populated by a Secret)
     SecretName:  omsagent-secret
     Optional:    false
   settings-vol-config:
     Type:      ConfigMap (a volume populated by a ConfigMap)
     Name:      container-azm-ms-agentconfig
     Optional:  true
   omsagent-token-f4zvk:
     Type:        Secret (a volume populated by a Secret)
     SecretName:  omsagent-token-f4zvk
     Optional:    false
 QoS Class:       Burstable
 Node-Selectors:  beta.kubernetes.io/os=linux
 Tolerations:     :NoSchedule
                  :NoExecute
                  :PreferNoSchedule
                  node.kubernetes.io/disk-pressure:NoSchedule
                  node.kubernetes.io/memory-pressure:NoSchedule
                  node.kubernetes.io/not-ready:NoExecute
                  node.kubernetes.io/pid-pressure:NoSchedule
                  node.kubernetes.io/unreachable:NoExecute
                  node.kubernetes.io/unschedulable:NoSchedule
 Events:
   Type     Reason     Age                   From                            Message
   ----     ------     ----                  ----                            -------
   Normal   Scheduled  25m                   default-scheduler               Successfully assigned kube-system/omsagent-4srlc to k8s-master-23710449-0
   Normal   Started    16m (x3 over 24m)     kubelet, k8s-master-23710449-0  Started container omsagent
   Normal   Pulling    12m (x4 over 25m)     kubelet, k8s-master-23710449-0  Pulling image "mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod01072020"
   Normal   Pulled     12m (x4 over 25m)     kubelet, k8s-master-23710449-0  Successfully pulled image "mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod01072020"
   Normal   Killing    12m (x3 over 20m)     kubelet, k8s-master-23710449-0  Container omsagent failed liveness probe, will be restarted
   Normal   Created    12m (x4 over 24m)     kubelet, k8s-master-23710449-0  Created container omsagent
   Warning  Unhealthy  4m43s (x15 over 22m)  kubelet, k8s-master-23710449-0  Liveness probe failed:
```

**Comment by jackfrancis** [comment]
@cpuguy83 @ritazh @ganga1980 FYI

**Comment by ganga1980** [comment]
@jackfrancis,  container log format got changed in containerd  and also there is no docker.sock.  I am actively working on adding the support for containerD or any other CRI compatiable runtime. I am targeting to add this support by end of this month. If any of the AKS-engine customer blocked on this, please ask them to reach out me so that I can share the private bits to try out.

**Comment by jackfrancis** [comment]
Thanks @ganga1980! I'm unaware if anyone is trying (and failing) to use this combination currently. In our investigation of the viability of using containerd as the default CRI for AKS Engine clusters, we want to call out any gaps compared to moby/docker.

Definitely let us know if you need help testing your efforts to make omsagent containerd-compatible!

**Comment by ganga1980** [comment]
> Thanks @ganga1980! I'm unaware if anyone is trying (and failing) to use this combination currently. In our investigation of the viability of using containerd as the default CRI for AKS Engine clusters, we want to call out any gaps compared to moby/docker.
> 
> Definitely let us know if you need help testing your efforts to make omsagent containerd-compatible!
> @Jackfrancis, we have the changes for containerd support and targeting to get into AKS and AKS-Engine once the deployment lock down lifted.   But if any of AKS-Engine customer wants to use for azure monitor for container on containerD cluster, please help on directing to  use the HELM chart https://github.com/helm/charts/tree/master/incubator/azuremonitor-containers

**Comment by ganga1980** [comment]
> > Thanks @ganga1980! I'm unaware if anyone is trying (and failing) to use this combination currently. In our investigation of the viability of using containerd as the default CRI for AKS Engine clusters, we want to call out any gaps compared to moby/docker.
> > Definitely let us know if you need help testing your efforts to make omsagent containerd-compatible!
> > @jackfrancis, we have the changes for containerd support and targeting to get into AKS and AKS-Engine once the deployment lock down lifted.   But if any of AKS-Engine customer wants to use for azure monitor for container on containerD cluster, please help on directing to  use the HELM chart https://github.com/helm/charts/tree/master/incubator/azuremonitor-containers

>> @jackfrancis , we have added support for containerd and other CRI compatiable runtimes in addition to docker/moby with recent pr @rashmichandrashekar . I think, we can close this issue now.

**Comment by ganga1980** [comment]
> > > Thanks @ganga1980! I'm unaware if anyone is trying (and failing) to use this combination currently. In our investigation of the viability of using containerd as the default CRI for AKS Engine clusters, we want to call out any gaps compared to moby/docker.
> > > Definitely let us know if you need help testing your efforts to make omsagent containerd-compatible!
> > > @jackfrancis, we have the changes for containerd support and targeting to get into AKS and AKS-Engine once the deployment lock down lifted.   But if any of AKS-Engine customer wants to use for azure monitor for container on containerD cluster, please help on directing to  use the HELM chart https://github.com/helm/charts/tree/master/incubator/azuremonitor-containers
> 
> > > @jackfrancis , we have added support for containerd and other CRI compatiable runtimes in addition to docker/moby with recent pr merged from @rashmichandrashekar . I think, we can close this issue now.

**Comment by jackfrancis** [comment]
Will test and close if validated, thanks!

**Comment by jackfrancis** [comment]
It looks like Windows + containerd is not supported. @ganga1980 does that sound right to you? Is the Windows support for container monitoring still moby-only?

**Comment by ganga1980** [comment]
> It looks like Windows + containerd is not supported. @ganga1980 does that sound right to you? Is the Windows support for container monitoring still moby-only?

>Hi, @jackfrancis , I have added support for windows as well. But that change will go in upcoming agent release which we are planning in 2 to 3 weeks.

**Comment by jackfrancis** [comment]
Thanks for the response, I'll retest and conditionally close this issue after that release lands in AKS Engine. Thanks!

**Comment by jackfrancis** [comment]
Just a gentle ping @ganga1980 in case the new version is ready. :)

**Comment by ganga1980** [comment]
> Just a gentle ping @ganga1980 in case the new version is ready. :)

> @jack, thanks for pinging. we will be pushing the new version of the agent sometime in next week. we have task on the board to make the aks-engine changes as soon as we get new version of prod image.

**Comment by bridgetkromhout** [comment]
Closing per @jackfrancis as we wrap up for the AKS Engine deprecation.
