### ISSUE TITLE
aks-engine upgrade exited with "Errors occurred while preparing VM disks" and left master unusable

### ISSUE THREAD

**Issue by jprecuch** [Azure/aks-engine#2770]
**Describe the bug**
We were trying to upgrade our aks-engine cluster from 1.12.8 to 1.13.11 today but we ended with error and couldn't upgrade it. 

**Steps To Reproduce**
1. We checked cluster is healthy and is on 1.12.8. 
2. We upgraded aks-engine to version v0.43.2
3. We run the upgrade command 
`aks-engine upgrade \
--subscription-id xxx-xxx-xxx-xxx \
--api-model /root/_output/k8seastus2euapdc/apimodel.json \
--location eastus2euap \
--resource-group anf.dc.mgmt.eastus2euap.rg \
--upgrade-version 1.13.11 \
--auth-method client_secret \
--client-id blah \
--client-secret blah`

4. This ended with error afterwards
`LOGS:  Upgrading cluster with name suffix: 11577350
LOGS:  VM k8s-node-11577350-vmss_0 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  VM k8s-node-11577350-vmss_1 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  VM k8s-node-11577350-vmss_2 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  VM k8s-node-11577350-vmss_3 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  VM k8s-node-11577350-vmss_4 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  VM k8s-node-11577350-vmss_5 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  VM k8s-node-11577350-vmss_6 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  VM k8s-node-11577350-vmss_7 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  VM k8s-node-11577350-vmss_8 in VMSS k8s-node-11577350-vmss has a current version of 1.12.8 and a desired version of 1.13.11. Upgrading this node.
LOGS:  Skipping VM: anf-dc-eastus2euap-backup-1a-prd for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: anf-dc-eastus2euap-lmgmt-1a-prd for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: anf-dc-eastus2euap-lmgmt-1b-prd for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: anf-dc-eastus2euap-observium-1a-prd for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: anf-dc-eastus2euap-proxy-12-prd for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: anf-dc-eastus2euap-proxy-13-prd for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: eastus2euap-wmgmt-1 for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: eastus2euapRP-1 for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: eastus2euapRP-2 for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Skipping VM: eastus2euapRP-3 for upgrade as it does not belong to cluster with expected name suffix: 11577350
LOGS:  Master VM name: k8s-master-11577350-0, orchestrator: 1.12.8 (MasterVMs)
LOGS:  Master VM name: k8s-master-11577350-1, orchestrator: 1.12.8 (MasterVMs)
LOGS:  Master VM name: k8s-master-11577350-2, orchestrator: 1.12.8 (MasterVMs)
LOGS:  Upgrading to Kubernetes version 1.13.11
LOGS:  Master nodes StorageProfile: ManagedDisks
LOGS:  etcd will be upgraded to version 3.3.18
LOGS:  Moby will be upgraded to version 3.0.8
LOGS:  Prepping master nodes for upgrade...
LOGS:  Resource count before running NormalizeResourcesForK8sMasterUpgrade: 11
LOGS:  Removing nsg resource: [variables('nsgName')] from template
LOGS:  Removing Microsoft.Compute/availabilitySets dependency from [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))]
LOGS:  Evaluating if agent pool: master, resource: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))] needs to be removed
LOGS:  Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', '-master-', copyIndex(variables('masterOffset')))] needs to be removed
LOGS:  Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/computeAksLinuxBilling')] needs to be removed
LOGS:  Resource count after running NormalizeResourcesForK8sMasterUpgrade: 9
LOGS:  Removing singlePlacementGroup property from [variables('nodeVMNamePrefix')]
LOGS:  Total expected master count: 3
LOGS:  Master nodes that need to be upgraded: 3
LOGS:  Master nodes that have been upgraded: 0
LOGS:  Starting upgrade of master nodes...
LOGS:  masterNodesInCluster: 3
LOGS:  Expected master count: 3, Creating 0 more master VMs
LOGS:  Upgrading Master VM: k8s-master-11577350-0
LOGS:  deleting VM k8s-master-11577350-0 in resource group anf.dc.mgmt.eastus2euap.rg ...
LOGS:  deleting NIC k8s-master-11577350-nic-0 in resource group anf.dc.mgmt.eastus2euap.rg ...
LOGS:  deleting managed disk k8s-master-11577350-0_OsDisk_1_a12df54504be4009ad951cf083a9ece2 in resource group anf.dc.mgmt.eastus2euap.rg ...
LOGS:  Master offset: 0
LOGS:  Master pool set count to: 1 temporarily during upgrade...
LOGS:  Starting ARM Deployment master-20-02-24T08.07.06-1361254878 in resource group anf.dc.mgmt.eastus2euap.rg. This will take some time...
LOGS:  Finished ARM Deployment (master-20-02-24T08.07.06-1361254878). Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DiskProcessingError\",\r\n        \"message\": \"One or more errors occurred while preparing VM disks. See disk instance view for details.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]
LOGS:  Error creating upgraded master VM: k8s-master-11577350-0
LOGS: Error: upgrading cluster: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DiskProcessingError\",\r\n        \"message\": \"One or more errors occurred while preparing VM disks. See disk instance view for details.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]`

5. When I checked the details I could see also 
`Provisioning failed. Resource 'k8s-master-11577350-0-etcddisk' encrypted with customer managed key has disk encryption set missing resource id. Target: '/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/ANF.DC.MGMT.EASTUS2EUAP.RG/providers/Microsoft.Compute/disks/k8s-master-11577350-0-etcddisk'.. InvalidParameter`

6.  When we tried to re-run upgrade command again we got same for another master
`LOGS:  deleting VM k8s-master-11577350-1 in resource group anf.dc.mgmt.eastus2euap.rg ...
LOGS:  Error deleting master VM: k8s-master-11577350-1, err: Code="DiskProcessingError" Message="One or more errors occurred while preparing VM disks. See disk instance view for details."
LOGS:  Error: upgrading cluster: Code="DiskProcessingError" Message="One or more errors occurred while preparing VM disks. See disk instance view for details."`

7. apimodel.json
`{
  "apiVersion": "vlabs",
  "location": "eastus2euap",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.12",
      "orchestratorVersion": "1.12.8",
      "kubernetesConfig": {
        "kubernetesImageBase": "k8s.gcr.io/",
        "clusterSubnet": "10.244.0.0/16",
        "dnsServiceIP": "10.0.0.10",
        "serviceCidr": "10.0.0.0/16",
        "networkPlugin": "kubenet",
        "containerRuntime": "docker",
        "dockerBridgeSubnet": "172.17.0.1/16",
        "mobyVersion": "3.0.6",
        "useInstanceMetadata": true,
        "enableRbac": true,
        "enableSecureKubelet": true,
        "enableAggregatedAPIs": true,
        "privateCluster": {
          "enabled": false
        },
        "gchighthreshold": 85,
        "gclowthreshold": 80,
        "etcdVersion": "3.2.26",
        "etcdDiskSizeGB": "1024",
        "addons": [
          {
            "name": "heapster",
            "enabled": true,
            "containers": [
              {
                "name": "heapster",
                "image": "k8s.gcr.io/heapster-amd64:v1.5.4",
                "cpuRequests": "88m",
                "memoryRequests": "204Mi",
                "cpuLimits": "88m",
                "memoryLimits": "204Mi"
              },
              {
                "name": "heapster-nanny",
                "image": "k8s.gcr.io/addon-resizer:1.8.4",
                "cpuRequests": "88m",
                "memoryRequests": "204Mi",
                "cpuLimits": "88m",
                "memoryLimits": "204Mi"
              }
            ]
          },
          {
            "name": "tiller",
            "enabled": true,
            "containers": [
              {
                "name": "tiller",
                "image": "gcr.io/kubernetes-helm/tiller:v2.11.0",
                "cpuRequests": "50m",
                "memoryRequests": "150Mi",
                "cpuLimits": "50m",
                "memoryLimits": "150Mi"
              }
            ],
            "config": {
              "max-history": "0"
            }
          },
          {
            "name": "aci-connector",
            "enabled": false
          },
          {
            "name": "cluster-autoscaler",
            "enabled": false
          },
          {
            "name": "blobfuse-flexvolume",
            "enabled": true,
            "containers": [
              {
                "name": "blobfuse-flexvolume",
                "image": "mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume:1.0.8",
                "cpuRequests": "50m",
                "memoryRequests": "100Mi",
                "cpuLimits": "50m",
                "memoryLimits": "100Mi"
              }
            ]
          },
          {
            "name": "smb-flexvolume",
            "enabled": false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled": true,
            "containers": [
              {
                "name": "keyvault-flexvolume",
                "image": "mcr.microsoft.com/k8s/flexvolume/keyvault-flexvolume:v0.0.7",
                "cpuRequests": "50m",
                "memoryRequests": "100Mi",
                "cpuLimits": "50m",
                "memoryLimits": "100Mi"
              }
            ]
          },
          {
            "name": "kubernetes-dashboard",
            "enabled": true,
            "containers": [
              {
                "name": "kubernetes-dashboard",
                "image": "k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1",
                "cpuRequests": "300m",
                "memoryRequests": "150Mi",
                "cpuLimits": "300m",
                "memoryLimits": "150Mi"
              }
            ]
          },
          {
            "name": "rescheduler",
            "enabled": false
          },
          {
            "name": "metrics-server",
            "enabled": true,
            "containers": [
              {
                "name": "metrics-server",
                "image": "k8s.gcr.io/metrics-server-amd64:v0.2.1"
              }
            ]
          },
          {
            "name": "nvidia-device-plugin",
            "enabled": false
          },
          {
            "name": "container-monitoring",
            "enabled": false
          },
          {
            "name": "azure-cni-networkmonitor",
            "enabled": false
          },
          {
            "name": "azure-npm-daemonset",
            "enabled": false
          },
          {
            "name": "ip-masq-agent",
            "enabled": true,
            "containers": [
              {
                "name": "ip-masq-agent",
                "image": "k8s.gcr.io/ip-masq-agent-amd64:v2.3.0",
                "cpuRequests": "50m",
                "memoryRequests": "50Mi",
                "cpuLimits": "50m",
                "memoryLimits": "250Mi"
              }
            ],
            "config": {
              "non-masq-cni-cidr": "",
              "non-masquerade-cidr": "10.244.0.0/16"
            }
          },
          {
            "name": "dns-autoscaler",
            "enabled": false
          },
          {
            "name": "calico-daemonset",
            "enabled": false
          },
          {
            "name": "aad-pod-identity",
            "enabled": false
          },
          {
            "name": "appgw-ingress",
            "enabled": false
          }
        ],
        "kubeletConfig": {
          "--address": "0.0.0.0",
          "--allow-privileged": "true",
          "--anonymous-auth": "false",
          "--authorization-mode": "Webhook",
          "--azure-container-registry-config": "/etc/kubernetes/azure.json",
          "--cgroups-per-qos": "true",
          "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--cluster-dns": "10.0.0.10",
          "--cluster-domain": "cluster.local",
          "--enforce-node-allocatable": "pods",
          "--event-qps": "0",
          "--eviction-hard": "memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%",
          "--feature-gates": "PodPriority=true,RotateKubeletServerCertificate=true",
          "--image-gc-high-threshold": "85",
          "--image-gc-low-threshold": "80",
          "--image-pull-progress-deadline": "30m",
          "--keep-terminated-pod-volumes": "false",
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--max-pods": "110",
          "--network-plugin": "kubenet",
          "--node-status-update-frequency": "10s",
          "--non-masquerade-cidr": "0.0.0.0/0",
          "--pod-infra-container-image": "k8s.gcr.io/pause-amd64:3.1",
          "--pod-manifest-path": "/etc/kubernetes/manifests",
          "--pod-max-pids": "-1",
          "--rotate-certificates": "true",
          "--streaming-connection-idle-timeout": "5m",
          "--tls-cert-file": "/etc/kubernetes/certs/kubeletserver.crt",
          "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256",
          "--tls-private-key-file": "/etc/kubernetes/certs/kubeletserver.key"
        },
        "controllerManagerConfig": {
          "--allocate-node-cidrs": "true",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--cluster-cidr": "10.244.0.0/16",
          "--cluster-name": "k8seastus2euapdc",
          "--cluster-signing-cert-file": "/etc/kubernetes/certs/ca.crt",
          "--cluster-signing-key-file": "/etc/kubernetes/certs/ca.key",
          "--configure-cloud-routes": "true",
          "--controllers": "*,bootstrapsigner,tokencleaner",
          "--feature-gates": "LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true",
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--leader-elect": "true",
          "--node-monitor-grace-period": "40s",
          "--pod-eviction-timeout": "5m0s",
          "--profiling": "false",
          "--root-ca-file": "/etc/kubernetes/certs/ca.crt",
          "--route-reconciliation-period": "10s",
          "--service-account-private-key-file": "/etc/kubernetes/certs/apiserver.key",
          "--terminated-pod-gc-threshold": "5000",
          "--use-service-account-credentials": "true",
          "--v": "2"
        },
        "cloudControllerManagerConfig": {
          "--allocate-node-cidrs": "true",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--cluster-cidr": "10.244.0.0/16",
          "--cluster-name": "k8seastus2euapdc",
          "--configure-cloud-routes": "true",
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--leader-elect": "true",
          "--route-reconciliation-period": "10s",
          "--v": "2"
        },
        "apiServerConfig": {
          "--advertise-address": "<advertiseAddr>",
          "--allow-privileged": "true",
          "--anonymous-auth": "false",
          "--audit-log-maxage": "30",
          "--audit-log-maxbackup": "10",
          "--audit-log-maxsize": "100",
          "--audit-log-path": "/var/log/kubeaudit/audit.log",
          "--audit-policy-file": "/etc/kubernetes/addons/audit-policy.yaml",
          "--authorization-mode": "Node,RBAC",
          "--bind-address": "0.0.0.0",
          "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration",
          "--enable-bootstrap-token-auth": "true",
          "--etcd-cafile": "/etc/kubernetes/certs/ca.crt",
          "--etcd-certfile": "/etc/kubernetes/certs/etcdclient.crt",
          "--etcd-keyfile": "/etc/kubernetes/certs/etcdclient.key",
          "--etcd-servers": "https://<etcdEndPointUri>:2379",
          "--insecure-port": "8080",
          "--kubelet-client-certificate": "/etc/kubernetes/certs/client.crt",
          "--kubelet-client-key": "/etc/kubernetes/certs/client.key",
          "--profiling": "false",
          "--proxy-client-cert-file": "/etc/kubernetes/certs/proxy.crt",
          "--proxy-client-key-file": "/etc/kubernetes/certs/proxy.key",
          "--repair-malformed-updates": "false",
          "--requestheader-allowed-names": "",
          "--requestheader-client-ca-file": "/etc/kubernetes/certs/proxy-ca.crt",
          "--requestheader-extra-headers-prefix": "X-Remote-Extra-",
          "--requestheader-group-headers": "X-Remote-Group",
          "--requestheader-username-headers": "X-Remote-User",
          "--secure-port": "443",
          "--service-account-key-file": "/etc/kubernetes/certs/apiserver.key",
          "--service-account-lookup": "true",
          "--service-cluster-ip-range": "10.0.0.0/16",
          "--storage-backend": "etcd3",
          "--tls-cert-file": "/etc/kubernetes/certs/apiserver.crt",
          "--tls-cipher-suites": "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
          "--tls-private-key-file": "/etc/kubernetes/certs/apiserver.key",
          "--v": "4"
        },
        "schedulerConfig": {
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--leader-elect": "true",
          "--profiling": "false",
          "--v": "2"
        },
        "cloudProviderBackoff": true,
        "cloudProviderBackoffRetries": 6,
        "cloudProviderBackoffJitter": 1,
        "cloudProviderBackoffDuration": 5,
        "cloudProviderBackoffExponent": 1.5,
        "cloudProviderRateLimit": true,
        "cloudProviderRateLimitQPS": 3,
        "cloudProviderRateLimitBucket": 10,
        "loadBalancerSku": "Basic",
        "maximumLoadBalancerRuleCount": 250,
        "kubeProxyMode": "iptables"
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "k8seastus2euapdc",
      "subjectAltNames": null,
      "vmSize": "Standard_D2s_v3",
      "osDiskSizeGB": 100,
      "vnetSubnetID": "/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Network/virtualNetworks/anf.dc.mgmt.eastus2euap.vnet/subnets/anf.dc.mgmt.eastus2euap.subnet",
      "firstConsecutiveStaticIP": "10.5.0.50",
      "storageProfile": "ManagedDisks",
      "oauthEnabled": false,
      "preProvisionExtension": null,
      "extensions": [],
      "distro": "aks-ubuntu-16.04",
      "kubernetesConfig": {
        "kubeletConfig": {
          "--address": "0.0.0.0",
          "--allow-privileged": "true",
          "--anonymous-auth": "false",
          "--authorization-mode": "Webhook",
          "--azure-container-registry-config": "/etc/kubernetes/azure.json",
          "--cgroups-per-qos": "true",
          "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--cluster-dns": "10.0.0.10",
          "--cluster-domain": "cluster.local",
          "--enforce-node-allocatable": "pods",
          "--event-qps": "0",
          "--eviction-hard": "memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%",
          "--feature-gates": "PodPriority=true,RotateKubeletServerCertificate=true",
          "--image-gc-high-threshold": "85",
          "--image-gc-low-threshold": "80",
          "--image-pull-progress-deadline": "30m",
          "--keep-terminated-pod-volumes": "false",
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--max-pods": "110",
          "--network-plugin": "kubenet",
          "--node-status-update-frequency": "10s",
          "--non-masquerade-cidr": "0.0.0.0/0",
          "--pod-infra-container-image": "k8s.gcr.io/pause-amd64:3.1",
          "--pod-manifest-path": "/etc/kubernetes/manifests",
          "--pod-max-pids": "-1",
          "--protect-kernel-defaults": "true",
          "--rotate-certificates": "true",
          "--streaming-connection-idle-timeout": "5m",
          "--tls-cert-file": "/etc/kubernetes/certs/kubeletserver.crt",
          "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256",
          "--tls-private-key-file": "/etc/kubernetes/certs/kubeletserver.key"
        }
      },
      "availabilityProfile": "AvailabilitySet",
      "cosmosEtcd": false
    },
    "agentPoolProfiles": [
      {
        "name": "node",
        "count": 9,
        "vmSize": "Standard_D8s_v3",
        "osDiskSizeGB": 100,
        "osType": "Linux",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "vnetSubnetID": "/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Network/virtualNetworks/anf.dc.mgmt.eastus2euap.vnet/subnets/anf.dc.mgmt.eastus2euap.subnet",
        "distro": "aks-ubuntu-16.04",
        "kubernetesConfig": {
          "kubeletConfig": {
            "--address": "0.0.0.0",
            "--allow-privileged": "true",
            "--anonymous-auth": "false",
            "--authorization-mode": "Webhook",
            "--azure-container-registry-config": "/etc/kubernetes/azure.json",
            "--cgroups-per-qos": "true",
            "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
            "--cloud-config": "/etc/kubernetes/azure.json",
            "--cloud-provider": "azure",
            "--cluster-dns": "10.0.0.10",
            "--cluster-domain": "cluster.local",
            "--enforce-node-allocatable": "pods",
            "--event-qps": "0",
            "--eviction-hard": "memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%",
            "--feature-gates": "PodPriority=true,RotateKubeletServerCertificate=true",
            "--image-gc-high-threshold": "85",
            "--image-gc-low-threshold": "80",
            "--image-pull-progress-deadline": "30m",
            "--keep-terminated-pod-volumes": "false",
            "--kubeconfig": "/var/lib/kubelet/kubeconfig",
            "--max-pods": "110",
            "--network-plugin": "kubenet",
            "--node-status-update-frequency": "10s",
            "--non-masquerade-cidr": "0.0.0.0/0",
            "--pod-infra-container-image": "k8s.gcr.io/pause-amd64:3.1",
            "--pod-manifest-path": "/etc/kubernetes/manifests",
            "--pod-max-pids": "-1",
            "--protect-kernel-defaults": "true",
            "--rotate-certificates": "true",
            "--streaming-connection-idle-timeout": "5m",
            "--tls-cert-file": "/etc/kubernetes/certs/kubeletserver.crt",
            "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256",
            "--tls-private-key-file": "/etc/kubernetes/certs/kubeletserver.key"
          }
        },
        "acceleratedNetworkingEnabled": true,
        "acceleratedNetworkingEnabledWindows": false,
        "vmssOverProvisioningEnabled": false,
        "auditDEnabled": false,
        "fqdn": "",
        "preProvisionExtension": null,
        "extensions": [],
        "singlePlacementGroup": true,
        "enableVMSSNodePublicIP": false
      }
    ],
    "linuxProfile": {
      "adminUsername": "ubuntu",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "blah"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "blah",
      "secret": "blah"
    },
    "certificateProfile": {
REMOVED
      ]
    }
  }
}`
**Expected behavior**
Upgrade should go through 
**AKS Engine version**
v0.43.2
**Kubernetes version**
1.12.8
**Additional context**

**Comment by jackfrancis** [comment]
@jprecuch could you re-try `aks-engine upgrade` using v0.47.0 of aks-engine and report back?

**Comment by jprecuch** [comment]
It seems issue is on Azure side where they were forcing encryption of volumes.
