### ISSUE TITLE
Update to EncryptionConfiguration

### ISSUE THREAD

**Issue by ritazh** [Azure/aks-engine#2777]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**
https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#encrypting-your-data-with-the-kms-provider

**Comment by craiglpeters** [comment]
@ritazh can you please expand on the work that needs to be done? Seems like a high priority, but ??
