### ISSUE TITLE
Update coredns to 1.6.7

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2779]
See:

https://github.com/coredns/coredns/releases/tag/v1.6.7

**Comment by jackfrancis** [comment]
@jchauncey @sozercan to confirm that MCR automatically scoops in new coredns releases

**Comment by sozercan** [comment]
yep, available at `mcr.microsoft.com/oss/kubernetes/coredns:1.6.7`

**Comment by jchauncey** [comment]
We need a good way for you to know if we have published an image already.

**Comment by jackfrancis** [comment]
If the build pipeline could automatically create an issue like this one that would be 💯

**Comment by jchauncey** [comment]
opening a single issue per image update might be a bit spammy. What if we just opened a single issue with the images that we are building for a given trigger run?

**Comment by jackfrancis** [comment]
I actually disagree, I would love an issue per component image!
