### ISSUE TITLE
Kubernetes node going to unknown state

### ISSUE THREAD

**Issue by azharudheen1990** [Azure/aks-engine#2792]
Nodes in Kubernetes cluster are going to Unknown state often and requires redeploy and reboot of nodes to bring it back online.

Details of Cluster :
Region: North Central
Subscription: Sensitive Prod, Resource Group: loyalty-prod-sen-acs02
Latest Occurrences:
1. Node k8s-master-21337720-1 -  02/26 11 AM CT - till now 
2. Nodes : k8s-ltyprod2n012-21337720-0, k8s-ltyprod2n012-21337720-1, k8s-ltyprod2n011-21337720-3 - 02/25 7-8 PM CST

**Comment by jackfrancis** [comment]
Can you `kubectl describe <nodename>` a node when it's in this state?

**Comment by azharudheen1990** [comment]
Here is the output:


Name:               k8s-master-21337720-1

Roles:              master

Labels:             beta.kubernetes.io/arch=amd64

                    beta.kubernetes.io/instance-type=Standard_D4s_v3

                    beta.kubernetes.io/os=linux

                    failure-domain.beta.kubernetes.io/region=northcentralus

                    failure-domain.beta.kubernetes.io/zone=0

                    kubernetes.azure.com/cluster=loyalty-prod-sen-acs02

                    kubernetes.io/hostname=k8s-master-21337720-1

                    kubernetes.io/role=master

                    node-role.kubernetes.io/master=

Annotations:        node.alpha.kubernetes.io/ttl: 0

                    volumes.kubernetes.io/controller-managed-attach-detach: true

CreationTimestamp:  Tue, 03 Sep 2019 11:40:16 -0500

Taints:             node.kubernetes.io/unreachable:NoExecute

                    node-role.kubernetes.io/master=true:NoSchedule

                    node.kubernetes.io/unreachable:NoSchedule

Unschedulable:      false

Conditions:

  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason                   Message

  ----                 ------    -----------------                 ------------------                ------                   -------

  NetworkUnavailable   False     Tue, 03 Sep 2019 11:42:46 -0500   Tue, 03 Sep 2019 11:42:46 -0500   RouteCreated             RouteController created a route

  MemoryPressure       Unknown   Wed, 26 Feb 2020 10:04:04 -0600   Wed, 26 Feb 2020 10:49:23 -0600   NodeStatusUnknown        Kubelet stopped posting node status.

  DiskPressure         Unknown   Wed, 26 Feb 2020 10:04:04 -0600   Wed, 26 Feb 2020 10:49:23 -0600   NodeStatusUnknown        Kubelet stopped posting node status.

  PIDPressure          Unknown   Wed, 26 Feb 2020 10:04:04 -0600   Wed, 26 Feb 2020 10:49:23 -0600   NodeStatusUnknown        Kubelet stopped posting node status.

  Ready                Unknown   Wed, 26 Feb 2020 10:04:04 -0600   Wed, 26 Feb 2020 10:49:23 -0600   NodeStatusUnknown        Kubelet stopped posting node status.

  OutOfDisk            Unknown   Tue, 03 Sep 2019 11:40:16 -0500   Wed, 26 Feb 2020 10:49:23 -0600   NodeStatusNeverUpdated   Kubelet never posted node status.

Addresses:

  InternalIP:  10.217.88.153

  Hostname:    k8s-master-21337720-1

Capacity:

 attachable-volumes-azure-disk:  8

 cpu:                            4

 ephemeral-storage:              130046416Ki

 hugepages-1Gi:                  0

 hugepages-2Mi:                  0

 memory:                         16403392Ki

 pods:                           110

Allocatable:

 attachable-volumes-azure-disk:  8

 cpu:                            4

 ephemeral-storage:              119850776788

 hugepages-1Gi:                  0

 hugepages-2Mi:                  0

 memory:                         16300992Ki

 pods:                           110

System Info:

 Machine ID:                 f55fda4734be435bbd45111d937a99ee

 System UUID:                82E3A8C0-B034-CF4F-A628-2BBD65783878

 Boot ID:                    2227f253-defe-48bd-bfbc-d54667191257

 Kernel Version:             4.15.0-1056-azure

 OS Image:                   Ubuntu 16.04.6 LTS

 Operating System:           linux

 Architecture:               amd64

 Container Runtime Version:  docker://3.0.6

 Kubelet Version:            v1.13.4

 Kube-Proxy Version:         v1.13.4

PodCIDR:                     10.123.3.0/24

ProviderID:                  azure:///subscriptions/9bce7ccc-c659-410b-a272-80f570ccb1e4/resourceGroups/loyalty-prod-sen-acs02/providers/Microsoft.Compute/virtualMachines/k8s-master-21337720-1

Non-terminated Pods:         (8 in total)

  Namespace                  Name                                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE

  ---------                  ----                                             ------------  ----------  ---------------  -------------  ---

  dynatrace                  oneagent-9j7g9                                   0 (0%)        0 (0%)      0 (0%)           0 (0%)         75d

  kube-system                calico-node-rmpj6                                250m (6%)     0 (0%)      0 (0%)           0 (0%)         166d

  kube-system                kube-addon-manager-k8s-master-21337720-1         5m (0%)       0 (0%)      50Mi (0%)        0 (0%)         166d

  kube-system                kube-apiserver-k8s-master-21337720-1             0 (0%)        0 (0%)      0 (0%)           0 (0%)         166d

  kube-system                kube-controller-manager-k8s-master-21337720-1    0 (0%)        0 (0%)      0 (0%)           0 (0%)         166d

  kube-system                kube-proxy-qtsqk                                 100m (2%)     0 (0%)      0 (0%)           0 (0%)         166d

  kube-system                kube-scheduler-k8s-master-21337720-1             0 (0%)        0 (0%)      0 (0%)           0 (0%)         166d

  monitoring                 node-exporter-kp5n4                              112m (2%)     270m (6%)   200Mi (1%)       220Mi (1%)     146d

Allocated resources:

  (Total limits may be over 100 percent, i.e., overcommitted.)

  Resource                       Requests    Limits

  --------                       --------    ------

  cpu                            467m (11%)  270m (6%)

  memory                         250Mi (1%)  220Mi (1%)

  ephemeral-storage              0 (0%)      0 (0%)

  attachable-volumes-azure-disk  0           0

Events:                          <none>

**Comment by jackfrancis** [comment]
Is the kubelet running on that node? Anything interesting in `sudo journalctl -u kubelet`?

**Comment by azharudheen1990** [comment]
I am unable to ssh into the node currently.

Thanks,
Azhar

**Comment by mboersma** [comment]
If the inability to ssh to the node coincides with the node going into `Unknown` state, that might suggest network connectivity problems.

**Comment by azharudheen1990** [comment]
Could you please guide us here on next steps since this started happening all of a sudden.

**Comment by mboersma** [comment]
`Unknown` node status means the controller hasn't heard from the node for 40 seconds or more. That could be because the `kubelet` process on the node was unresponsive or died, or because network traffic failed during that time.

So we should try to determine what happened on the node during the event. The kubelet log on the node may show us something. The kernel logs on the node could also be informative.

It's possible that too much workload on a node could cause a host out-of-memory event, and the OOMKiller could have evicted kubelet or something else that Kubernetes needs. Is there a spike in CPU or memory usage that happens near this time?

It's also possible that a more general networking problem on the node causes this, which might show up in kernel logs. Do you have to reboot the node before you can access it again, or does it come back eventually?

**Comment by mboersma** [comment]
It's also possible that enabling the [`node-problem-detector`](https://github.com/Azure/aks-engine/blob/master/examples/addons/node-problem-detector/README.md) addon on this cluster could surface some underlying problems and expose them in the kube-apiserver logs.

**Comment by chewong** [comment]
@azharudheen1990 Are you still experiencing the same issue?

**Comment by azharudheen1990** [comment]
Hi, We have not experienced this issue after that occurrence - we didn't do any changes at our end. BUt we do not know the root cause yet.

**Comment by mboersma** [comment]
Since the problem has resolved and we don't have anything actionable here, I'm closing this. Please do re-open or create a new issue if this happens again.
