### ISSUE TITLE
Upgrade cluster from 1.10.x to 1.16.1

### ISSUE THREAD

**Issue by pjgerardo** [Azure/aks-engine#2798]
**Describe the bug**
Error when trying to upgrade cluster from 1.10.x to 1.16.1

**Steps To Reproduce**

Kubelet log
​============================
Feb 27 12:57:17 xxx-master-11111111-1 kubelet[1876]: E0227 12:57:17.373065    1876 kubelet_node_status.go:157] Previously node "xxx-master-11111111-1" had externalID "/subscriptions/xxxxxx-xxxxxx-xxxx-xxxxxx/resourceGroups/xxxxx-xxxxxx-xx/providers/Microsoft.Compute/virtualMachines/xxx-master-11111111-1"; now it is ""; will delete and recreate.
Feb 27 12:57:17 xxx-master-11111111-1 kubelet[1876]: E0227 12:57:17.373974    1876 kubelet_node_status.go:161] Unable to register node "xxx-master-11111111-1" with API server: error deleting old node: nodes "xxx-master-11111111-1" is forbidden: User "system:node:xxx-master-11111111-1" cannot delete resource "nodes" in API group "" at the cluster scope
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.374171    1876 kubelet_node_status.go:298] Setting node annotation to enable volume controller attach/detach
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: E0227 12:57:24.374248    1876 azure_vmss_cache.go:53] Failed to extract vmssVMName "xxx-master-11111111-1"
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: E0227 12:57:24.374268    1876 azure_vmss_cache.go:53] Failed to extract vmssVMName "xxx-master-11111111-1"
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.374282    1876 kubelet_node_status.go:354] Adding node label from cloud provider: beta.kubernetes.io/instance-type=Standard_F2s
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.374289    1876 kubelet_node_status.go:365] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=2
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.374293    1876 kubelet_node_status.go:369] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=westeurope
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.374312    1876 kubelet_node_status.go:528] Using Node Hostname from cloudprovider: "xxx-master-11111111-1"
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.397107    1876 kubelet_node_status.go:452] Recording NodeHasSufficientDisk event message for node xxx-master-11111111-1
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.397135    1876 kubelet_node_status.go:452] Recording NodeHasSufficientMemory event message for node xxx-master-11111111-1
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.397144    1876 kubelet_node_status.go:452] Recording NodeHasNoDiskPressure event message for node xxx-master-11111111-1
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.397150    1876 kubelet_node_status.go:452] Recording NodeHasSufficientPID event message for node xxx-master-11111111-1
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: I0227 12:57:24.397174    1876 kubelet_node_status.go:93] Attempting to register node xxx-master-11111111-1
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: E0227 12:57:24.420055    1876 kubelet_node_status.go:157] Previously node "xxx-master-11111111-1" had externalID "/subscriptions/xxxxxx-xxxxxx-xxxx-xxxxxx/resourceGroups/xxxxx-xxxxxx-xx/providers/Microsoft.Compute/virtualMachines/xxx-master-11111111-1"; now it is ""; will delete and recreate.
Feb 27 12:57:24 xxx-master-11111111-1 kubelet[1876]: E0227 12:57:24.421157    1876 kubelet_node_status.go:161] Unable to register node "xxx-master-11111111-1" with API server: error deleting old node: nodes "xxx-master-11111111-1" is forbidden: User "system:node:xxx-master-11111111-1" cannot delete resource "nodes" in API group "" at the cluster scope

Attempting to register node xxx-master-11111111-1

Unable to register node "xxx-master-11111111-1" with API server: error deleting old node: nodes "xxx-master-11111111-1" is forbidden: User "system:node:xxx-master-11111111-1" cannot delete resource "nodes" in API group "" at the cluster scop

Attempting to register node xxx-master-11111111-1

Unable to register node "xxx-master-11111111-1" with API server: error deleting old node: nodes "xxx-master-11111111-1" is forbidden: User "system:node:xxx-master-11111111-1" cannot delete resource "nodes" in API group "" at the cluster scop

**AKS Engine version**
1.16.1
**Kubernetes version**
1.16.1
**Additional context**

**Comment by jackfrancis** [comment]
What was the version of aks-engine (or acs-engine) used to build the original 1.10 cluster? With that information, and the original api model used to create the cluster, we could try to reproduce the failure.

**Comment by KevinFanton** [comment]
We are checking on that item and will get back to you soon. Thanks

**Comment by pjgerardo** [comment]
Customer does use the upgrade functionality in aks-engine.
Instead they have their own automation tool which follows an intricate process to upgrade a cluster.
Or more precisely create a second cluster, move over some Azure resources (e.g. IP, disks, etc.) and
then remove the old cluster.

Customer is not sure but they believe the original cluster was provisioned by acs-engine v0.18.8

**Comment by dennis-benzinger-hybris** [comment]
> Customer does use the upgrade functionality in aks-engine.

I think there's a "not" missing ;-).

**Comment by pjgerardo** [comment]
> > Customer does use the upgrade functionality in aks-engine.
> 
> I think there's a "not" missing ;-).

Fixed. Thanks

**Comment by jackfrancis** [comment]
O.K., thanks for the updates. It sounds like there's no aks-engine bug here?

**Comment by pjgerardo** [comment]
> O.K., thanks for the updates. It sounds like there's no aks-engine bug here?

Correct. Thank you for the help
