### ISSUE TITLE
VirtualMachineStorageOffline when requesting a pvc via azure-disk storageclass

### ISSUE THREAD

**Issue by philipp1992** [Azure/aks-engine#2805]
**Describe the bug**

We are using openshift 3.11 with kubernetes 1.11 and azure cloud-provider configuration to create PVC via the azure-disk storageclass.

Sometimes when we request new PVCs, it can happen, that the corresponding kubernetes-worker node will be unresponsive and changes the status to "notReady".

When we check the resource-health in azure for that machine we can see the reason why:

VirtualMachineStorageOffline
We're sorry, your virtual machine is unavailable because of connectivity loss to the remote disk. An unexpected problem is preventing us from automatically recovering your virtual machine

When this happens, we have to restart the machine via the azure api or recreate the worker node.

**Steps To Reproduce**

Can not be reproduced deliberately, but happened to us 7 times in the past 3 months on different VMs.

**Comment by jomeier** [comment]
Same here.

**Comment by philipp1992** [comment]
happened again today on a different worker

At Monday, March 2, 2020, 5:45:31 PM GMT+1, the Azure monitoring system received the following information regarding your Virtual machine:
We're sorry, your virtual machine is unavailable because of connectivity loss to the remote disk. We're working to reestablish disk connectivity. No additional action is required from you at this time.

Problem could only be solved by a restart of the VM

**Comment by andyzhangx** [comment]
It's more like a VM level issue

**Comment by jomeier** [comment]
Hi,

@andyzhangx 
why is that one closed? What‘s your recommendation to proceed with this problem?

Greetings,

Josef

**Comment by andyzhangx** [comment]
pls procceed to file support ticket if this issue happen again, thanks.

**Comment by philipp1992** [comment]
We did open a support ticket for. They assume it's because of the higher iops during Filesystem creation,which leads to throttling and then to the errors (disk connectivity lost). I've closed the support case because it seems to be a waste of time and just a Azure problem. I've never experienced such problems with other cloud providers.
