### ISSUE TITLE
The kubernetes dashboard can not accessed.

### ISSUE THREAD

**Issue by hepower** [Azure/aks-engine#2822]
**Describe the bug**
    
After I deployed a Kubernetes cluster via  https://github.com/Azure/aks-engine/blob/master/docs/tutorials/quickstart.md
    
I can not open the Kubernetes website https://qingh-aks-engine.westeurope.cloudapp.azure.com/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

The error message showed in Chrome:
    
Your connection is not private

Attackers might be trying to steal your information from qingh-aks-engine.westeurope.cloudapp.azure.com (for example, passwords, messages, or credit cards). Learn more

NET::ERR_CERT_AUTHORITY_INVALID

**Steps To Reproduce**

**Expected behavior**
Kubernetes website should be opened.

**AKS Engine version**
commit f0a0c371e5ab4d739ad81cd0d03cb4d14bae8b77
**Kubernetes version**

v1.13.11

**Additional context**

**Comment by mboersma** [comment]
The Kubernetes dashboard is not intended to be accessed directly via the cluster's URL. Instead, you have to [configure a token](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md), run [`kubectl proxy`](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui) locally, and then access the dashboard via this URL: http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

**Comment by mboersma** [comment]
As far as I can tell, this is working as designed. Please re-open this or create a new issue if there's something I missed that we can fix.

See also #3093.
