### ISSUE TITLE
Move Windows ContainerD CNI plugin to public builds

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#2828]
The experimental support for ContainerD #1322  in AKS-Engine depends on a custom, adhoc built ZIP file with ContainerD, and SDNBridge built from sources. That won't work for production, so we need to move to a proper release once its available.

Here's the code that's built manually today but needs a proper release: https://github.com/microsoft/windows-container-networking/releases

Areas needing update:

- Add new default URLs to SDNBridge download locations to https://github.com/Azure/aks-engine/blob/1c49d0825e1548f383d8a9ef06d4abb2505493e2/pkg/api/const.go. Consider splitting separate defaults for Windows & Linux if they need to be tested and updated separately.
- Update Parameter validation https://github.com/Azure/aks-engine/blob/1c49d0825e1548f383d8a9ef06d4abb2505493e2/pkg/api/vlabs/validate.go#L1597
- Remove unneeded parameter from APImodel https://github.com/Azure/aks-engine/blob/1c49d0825e1548f383d8a9ef06d4abb2505493e2/examples/windows/kubernetes-hybrid.containerd.json#L10
- Delete temporary build script https://github.com/Azure/aks-engine/blob/1c49d0825e1548f383d8a9ef06d4abb2505493e2/scripts/build-windows-containerd.sh

**Comment by jsturtevant** [comment]
partially fixed by https://github.com/Azure/aks-engine/pull/3508

Azure cni now supports containerd so we no longer need the win-bridge builds and `kubenet` (using win-bridge) windows cluster are not supported for production as of now.

/close
