### ISSUE TITLE
Install nvidia-smi on N-Series node to export gpu metrics

### ISSUE THREAD

**Issue by delulu** [Azure/aks-engine#2837]
**Describe the request**

Install nvidia-smi on N-Series node automatically in aks cluster initialization.

**Explain why AKS Engine needs it**

NVIDIA provides a tool to export GPU metrics into Prometheus, this tool is leveraging driver utility (nvidia-smi) to get gpu metrics and it's a prerequisite that this utility is installed on gpu node.

Also this driver utility seems the only way to get gpu metrics, and there should be a direct way to get gpu metrics beside other metrics (cpu/memory) on gpu node.

**Describe the solution you'd like**

Could you please install nvidia-smi along with GPU driver in aks cluster initialization?

**Describe alternatives you've considered**

**Additional context**
```
PS > .\kubectl.exe --kubeconfig k8s-hc -n prometheus logs prometheus-node-exporter-2t572 nvidia-dcgm-exporter
Starting NVIDIA host engine...
Collecting metrics at /run/prometheus/dcgm.prom every 1000ms...
/usr/local/bin/dcgm-exporter: line 53: nvidia-smi: command not found
```

nvidia-smi: https://developer.nvidia.com/nvidia-system-management-interface
metrics tool: https://github.com/NVIDIA/gpu-monitoring-tools

**Comment by delulu** [comment]
@CecileRobertMichon, could you take a look? or let me know if you need any more information.

**Comment by CecileRobertMichon** [comment]
@delulu added to backlog for triage by the team
/cc @delulu

**Comment by jackfrancis** [comment]
The driver installation you want is probably best delivered as a daemonset. If you can provide a working daemonset spec we can help w/ integration into the existing nvidia addon that is installed in a GPU-enabled VM SKU-backed node.

**Comment by delulu** [comment]
@jackfrancis thanks for your advice. but if it's deployed as a daemonset, this driver utility (CLI utility) will be provided in one serving container hosted on gpu node, and there's no direct access from other pods running on the same node. 

also usually the driver utility is installed along with driver, there should be a way to get metrics of gpu device on gpu node directly.

**Comment by delulu** [comment]
@jackfrancis with a further check, I found you already install this nvidia-smi in in aks cluster initialization.
https://github.com/Azure/aks-engine/blob/3e6b593c7d5e2878be2e536b62a596ad7e530ed7/parts/k8s/cloud-init/artifacts/cse_config.sh#L477

I can also found it from my aks agent, but it seems it's not added into system path and I met exceptions below when running it:
```sh
root@k8s-gpupool1-63423249-vmss000000:/# nvidia-smi
nvidia-smi: command not found

root@k8s-gpupool1-63423249-vmss000000:/# /usr/local/nvidia/bin/nvidia-smi
Failed to initialize NVML: Unknown Error
```

**Comment by delulu** [comment]
from strace log, I found the above exception is due to permission error as shown below:
```sh
open("/dev/nvidiactl", O_RDWR)          = -1 EPERM (Operation not permitted)
open("/dev/nvidiactl", O_RDONLY)        = -1 EPERM (Operation not permitted)
```
so I manually mount /usr/local/nvidia into a running container and finally run it successfully:

```sh
# /usr/local/nvidia/bin/nvidia-smi
Thu Mar 19 11:50:50 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00002BF4:00:00.0 Off |                  Off |
| N/A   34C    P8    33W / 149W |      0MiB / 12206MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by delulu** [comment]
Also it's said that "if you have driver installed on the host machine where the **runtime** will take care of injecting the right libs inside the container" in https://github.com/NVIDIA/gpu-monitoring-tools/issues/27 

It seems that **nvidia-container-runtime** will take care of it and we don't have to mount the libs manually.

do you have any idea about it?

**Comment by jackfrancis** [comment]
Thanks for all the data @delulu 

What is different from your manual mount step and this?

https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/artifacts/cse_config.sh#L475

In the above `${GPU_DEST}` is `/usr/local/nvidia` btw.

Also, are these symptoms 100% consistent?

**Comment by delulu** [comment]
The mount I mean is nvidia-container-runtime will help mount gpu driver capabilities into your containers before running it. 

According to [nvidia-container-runtime readme](https://github.com/NVIDIA/nvidia-container-runtime/blob/2c07b861b81afd4af683a0c1e71a250f1e2e3344/README.md#nvidia_driver_capabilities) there's a env variable NVIDIA_DRIVER_CAPABILITIES to "controls which driver libraries/binaries will be mounted inside the container." and containers should set this env variable accordingly to get the required capabilities.

And this env variable has been set in container as shown below but the utility capability required is not mounted inside the container as expected.
```sh
NVIDIA_DRIVER_CAPABILITIES=compute,utility
```
It might be an inconsistency issue in nvidia-docker2, will have a further check.

**Comment by delulu** [comment]
Opened an issue https://github.com/NVIDIA/nvidia-docker/issues/1226

and @jackfrancis, I noticed that the driver is installed with --utility-prefix="${GPU_DEST}", is it set in system path? It's possible that the utility is not discovered by nvidia-container-runtime so it's not mounted inside container.
https://github.com/Azure/aks-engine/blob/3e6b593c7d5e2878be2e536b62a596ad7e530ed7/parts/k8s/cloud-init/artifacts/cse_config.sh#L472

**Comment by ssbandari1** [comment]
Also this will be work once you physical ssh'd into the AKS node 

The debugger pod won't have the permissions to execute nvidia commads.  
sabanda@DESKTOP-FVMIGD1:~$ kubectl debug node/aks-nodepool1-26776728-vmss000000 -it --image=mcr.microsoft.com/dotnet/runtime-deps:6.0
Creating debugging pod node-debugger-aks-nodepool1-26776728-vmss000000-5j4bk with container debugger on node aks-nodepool1-26776728-vmss000000.
If you don't see a command prompt, try pressing enter.
root@aks-nodepool1-26776728-vmss000000:/# /usr/local/nvidia/bin/nvidia-smi
bash: /usr/local/nvidia/bin/nvidia-smi: No such file or directory
root@aks-nodepool1-26776728-vmss000000:/# nvidia-smi
bash: nvidia-smi: command not found
root@aks-nodepool1-26776728-vmss000000:/#

You will able to execute the nvidia commands once you ssh'd into the nodes 
ssh: https://learn.microsoft.com/en-us/azure/aks/node-access#create-the-ssh-connection-to-a-windows-node-using-a-password

azureuser@aks-nodepool1-26776728-vmss000000:~$ nvidia-smi
Fri Mar 10 21:19:18 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000001:00:00.0 Off |                    0 |
| N/A   37C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
azureuser@aks-nodepool1-26776728-vmss000000:~$ which nvidia-smi
/usr/bin/nvidia-smi
azureuser@aks-nodepool1-26776728-vmss000000:~$ ls -ltr  /usr/bin/nvidia-smi
-rwxr-xr-x 1 root root 678392 Mar 10 21:13 /usr/bin/nvidia-smi
azureuser@aks-nodepool1-26776728-vmss000000:~$
