### ISSUE TITLE
CSE master script failing with K8s Master: exit status 30

### ISSUE THREAD

**Issue by adelina-t** [Azure/aks-engine#2845]
**Describe the bug**

Using K8s built from master, cse-master fails with exit status 30.

ensureK8sControlPlane seems be retrying for the full 120 times, here:

https://github.com/Azure/aks-engine/blob/79ab03f62f628d80d300b5dee26c2e976bdf9266/parts/k8s/cloud-init/artifacts/cse_config.sh#L362

The odd thing is that kubectl cluster-info works just fine if called manually while cluster is starting.

**AKS Engine version**

0.46.3

**Kubernetes version**

k8s built from master

**Additional context**

This affects k8s-windows upstream master tests + azure provider tests.

** Additional info**

Running the cse-master script without redirecting errors to /dev/null, it seems that there kubectl doesn't find kubeconfig.:

```
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config
```

It's odd, as ./kube/config is clearly in the homedir for the current user. Under which user is the cse-master script running?

EDIT: this may have broke it (?): https://github.com/kubernetes/cli-runtime/commit/f26b0857ea34cb7fbd0b6d3201a82ca5cb6ad1fd

**Comment by adelina-t** [comment]
@marosset 
@chewong

**Comment by chewong** [comment]
I ssh into the master vm and saw the same error. But when I tried to run the same command manually, it returned the expected result: 
```
azureuser@k8s-master-23430338-0:/var/log/azure$ cat /var/log/azure/cluster-provision.log
...
+ timeout 25 /usr/local/bin/kubectl cluster-info
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
+ '[' 48 -eq 120 ']'
+ sleep 5
azureuser@k8s-master-23430338-0:/var/log/azure$ /usr/local/bin/kubectl cluster-info
Kubernetes master is running at https://chuwon-test.westus2.cloudapp.azure.com
CoreDNS is running at https://chuwon-test.westus2.cloudapp.azure.com/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
kubernetes-dashboard is running at https://chuwon-test.westus2.cloudapp.azure.com/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
Metrics-server is running at https://chuwon-test.westus2.cloudapp.azure.com/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
```

**Comment by adelina-t** [comment]
It's odd that this is not happening on 1.17 or lower, so it's most probably k8s related, but for the I can't seem to crack it.

**Comment by chewong** [comment]
That's because the PR hasn't been cherry-picked to older releases. It will start affecting 1.17 jobs if it is backported to older releases.
