### ISSUE TITLE
Test Gen2 Ubuntu 18.04 and Windows base images

### ISSUE THREAD

**Issue by craiglpeters** [Azure/aks-engine#2846]
**Describe the request**
Users need the capabilities of the [DC2 series](https://docs.microsoft.com/en-us/azure/virtual-machines/dcv2-series) VMs which are very large and support confidential compute and AI workloads. The DC2 series only works with  [Gen2 VM images](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/generation-2)

**Explain why AKS Engine needs it**
Some users need to manage their own clusters, and thus can't use a managed service, but have workloads that require DC2-series VMs

**Describe the solution you'd like**
Test the Gen2 Ubuntu and Windows base images in AKS Engine. Provisioning will become faster and more reliable once there is an [AKS Engine VHD](https://github.com/Azure/aks-engine/issues/2601), but until then it'd be useful to make sure it works with the base images

**Describe alternatives you've considered**

**Additional context**

**Comment by marosset** [comment]
For linux we can test with
Publisher: Canonical
Offer: UbuntuServer
Sku: 16.04-LTS-gen2
Version: latest

For Windows we can test with
Publisher: MicrosoftWindowsServer
Offer: WindowsServer
Sku:  2019-datacenter-core-with-containers-smalldisk-g2
Version: latest

**Comment by craiglpeters** [comment]
@marosset we should target Ubuntu 18.04 as this is what users are asking for. 16.04 should be a lower priority

**Comment by jackfrancis** [comment]
@marosset is the existent custom image interface foo in aks-engine enough to allow folks to build clusters w/ arbitary image offers like the above? (assuming it's ubuntu-ish and will play well w/ CSE)

**Comment by marosset** [comment]
@jackfrancis  For Windows you can specify the publisher/offer/sku/version - for Linux I was going to introduce a new 'Distro' to use the Canonical 18.04 latest image

**Comment by jackfrancis** [comment]
Fair enough. While you're doing so could you validate that for sure this is functionality that is WindowsProfile-only? (if so we should call that a gap and address it at some point)

**Comment by marosset** [comment]
This is a confirmed gap
