### ISSUE TITLE
chore: Windows ContainerD - don't use ctr.exe to pull images

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#2848]
**Describe the bug**

The current containerd setup scripts (see #1322) use ctr.exe to pull images. This app is "unstable" per https://github.com/containerd/containerd/blob/da2890a90826458c0573cdbc4e3e3768d69197b8/cmd/ctr/app/main.go#L61

It needs to be replaced with either direct API calls, or possibly crictl.exe if that's stable.

**Comment by jackfrancis** [comment]
@marosset @ksubrmnn is this issue still current?

**Comment by marosset** [comment]
Looks like it - @cpuguy83 can you confirm we should not be using ctr.exe to pull container images?

**Comment by cpuguy83** [comment]
That's correct, `ctr` is not considered a stable interface.

**Comment by cpuguy83** [comment]
If we want to replace the use of ctr, it's fairly trivial to implement a pull client using the go containerd client.
It's a trade-off... `ctr` probably won't give us a problem, but could... and PR's to it are a bit more lax in my experience than the rest of the codebase.
On the otherhand we'd have to maintain our own thing just to pull images.

**Comment by jackfrancis** [comment]
Should we move this aspirational backlog issue to cluster-api? I don't think we'll do this work anytime soon in AKS Engine.

**Comment by jackfrancis** [comment]
@marosset did we ever do this work in capz?

cc @bridgetkromhout

**Comment by marosset** [comment]
> @marosset did we ever do this work in capz?
> 
> cc @bridgetkromhout

Not that I am aware of.

**Comment by marosset** [comment]
/close
This hasn't been a problem so I'm not even sure it is worth it to open an issue in CAPZ at this point.
