### ISSUE TITLE
kube-system pods are not running in AKS-Engine Dual Stack with kubenet

### ISSUE THREAD

**Issue by tamilmani1989** [Azure/aks-engine#2868]
**Describe the bug**

**Steps To Reproduce**

Used kubernetes cluster config from https://raw.githubusercontent.com/Azure/aks-engine/master/examples/dualstack/kubernetes.json and created a dual stack cluster.

**kubectl get pods -n kube-system
No resources found in kube-system namespace.**

**Expected behavior**
kubectl get pods -n kube-system should show some kubernetes service pods in running state

**AKS Engine version**
Pulled latest master and build it

**Kubernetes version**
1.16

**Additional context**
saw this error message in kubelet logs:

kube-controller-manager-k8s-master-94730297-0" is forbidden: no providers available to validate pod request
7c97625fa9d6)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 1m20s restarting failed container=kube-c
net does not have netConfig. This is most likely due to lack of PodCIDR
net does not have netConfig. This is most likely due to lack of PodCIDR
kube-controller-manager-k8s-master-94730297-0" is forbidden: no providers available to validate pod request
7c97625fa9d6)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 1m20s restarting failed container=kube-c
net does not have netConfig. This is most likely due to lack of PodCIDR
net does not have netConfig. This is most likely due to lack of PodCIDR
net does not have netConfig. This is most likely due to lack of PodCIDR
kube-controller-manager-k8s-master-94730297-0" is forbidden: no providers available to validate pod request
7c97625fa9d6)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 1m20s restarting failed container=kube-c
net does not have netConfig. This is most likely due to lack of PodCIDR
net does not have netConfig. This is most likely due to lack of PodCIDR
kube-controller-manager-k8s-master-94730297-0" is forbidden: no providers available to validate pod request
7c97625fa9d6)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 1m20s restarting failed container=kube-c
net does not have netConfig. This is most likely due to lack of PodCIDR

**Comment by aramase** [comment]
Tried to repro using the master branch, but unable to repro it on a new cluster using master branch. Will try and take a look at existing cluster to see what the issue is.

**Comment by tamilmani1989** [comment]
Debugged offline with anish. this issue was due to recent change in default mask size of ipv6. In k8 1.16, /48 is not supported. Anish will make a change so that defining mask size based on k8 version
