### ISSUE TITLE
Build new VHD w/ new component versions

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#288]
- k8s 1.13.2
- addon-resizer 1.8.4
- etcd 3.2.25
- kube-dns 1.15.0
- heapster 1.5.4
- tiller 2.11.0
- blobfuse-flexvolume 1.0.7

**Comment by CecileRobertMichon** [comment]
let's wait until https://github.com/Azure/aks-engine/pull/284 is in?

**Comment by jackfrancis** [comment]
Thanks, updated description :)

**Comment by jackfrancis** [comment]
Also https://github.com/Azure/aks-engine/pull/292

**Comment by scottzilla** [comment]
I thought heapster was deprecated?
https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md

**Comment by CecileRobertMichon** [comment]
@scottzilla heapster is deprecated for K8s starting at version 1.11. We still support heapster for previous K8s versions.
