### ISSUE TITLE
Error with cluster-autoscaler "Failed to get current size for vmss"

### ISSUE THREAD

**Issue by chzbrgr71** [Azure/aks-engine#2909]
I've deployed the cluster successfully, however when the autoscaler attempts to scan the agentpool and potentially scale, it errors and CrashLoopBackoff. My Service Principal is an Owner at the subscription level. 

The relevant errors in the logs are: 

E0316 18:57:29.925863       1 azure_scale_set.go:569] Failed to get current size for vmss "k8s-agentpool1-19133377-vmss": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/471d33fd-a776-405b-947c-467c291dc741/resourceGroups/claro-aks-engine/providers/Microsoft.Compute/virtualMachineScaleSets?api-version=2018-10-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token?api-version=1.0: dial tcp: i/o timeout'
F0316 18:57:29.926213       1 azure_cloud_provider.go:169] Failed to create Azure Manager: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/471d33fd-a776-405b-947c-467c291dc741/resourceGroups/claro-aks-engine/providers/Microsoft.Compute/virtualMachineScaleSets?api-version=2018-10-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token?api-version=1.0: dial tcp: i/o timeout'

**Steps To Reproduce**
My aks-engine deployment manifest: https://gist.github.com/chzbrgr71/e357f2c1bb11f21c1fed43c974db0562

**Expected behavior**
cluster-autoscaler should read in proper current # nodes and scale if pods are pending.

**AKS Engine version**
v0.47.0

**Kubernetes version**
1.15.10

**Additional context**
We've seen this error on multiple Azure subs and accounts.

**Comment by jackfrancis** [comment]
This could be a transient error, assuming you delivered cluster-autoscaler via aks-engine as an addon, they would share the same sp (and thus, said sp would be proven as functional, as they were used to create the IaaS running the cluster). Are these errors persistent in the logs? What happens if you delete the pod and let the deployment recreate a new one?
