### ISSUE TITLE
Deployment on Azure Stack

### ISSUE THREAD

**Issue by avaranovich** [Azure/aks-engine#294]
**Is this a request for help?**:
NO
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
Latest
---
Is Azure Stack on the roadmap of ACS Engine? I am trying to get K8S up and running on Azure Stack and curious, if this should be tracked here, in the same stream as ACS Engine for Public Azure. Or I should just install K8S on IaaS "from scratch".

**Comment by jackfrancis** [comment]
@honcao Is there guidance we can add to this issue?

**Comment by honcao** [comment]
@jackfrancis 

Currently we are working on AKS engine upstream to support Azure Stack. 
Before the work is done, please follow the following instruction to deploy k8s cluster on Azure Stack.
https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-solution-template-kubernetes-deploy 

The feature is in public preview.
