### ISSUE TITLE
Issue with DNS resolution 

### ISSUE THREAD

**Issue by satishsudini** [Azure/aks-engine#2940]
**Describe the bug**
DNS resolution is not working with k8 1.17.2 

**Steps To Reproduce**

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.17",
      "orchestratorVersion": "1.17.2",
      "kubernetesConfig": {
        "enableRbac": true,
        "enableSecureKubelet": true,
        "enableAggregatedAPIs": true,
        "networkPlugin": "kubenet",
        "clusterSubnet": "*",
        "serviceCidr": "*",
        "dnsServiceIP": "*",
        "dockerBridgeSubnet": "*",
        "etcdDiskSizeGB": "*",
        "privateCluster": {
          "enabled": true
        },
        "kubeletConfig": {
          "--non-masquerade-cidr": "*",
          "--feature-gates": "PodPriority=true"
        },
        "apiServerConfig": {
          "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
        },
        "useInstanceMetadata": false,
        "enableEncryptionWithExternalKms": true,
        "cloudProviderRateLimit": false,
        "cloudProviderRateLimitBucket": 0,
        "cloudProviderRateLimitQPS": 0,
        "addons": [
          {
            "name": "blobfuse-flexvolume",
            "enabled" : false
          },
          {
            "name": "smb-flexvolume",
            "enabled" : false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled" : false
          },
          {
            "name": "nvidia-device-plugin",
            "enabled" : false
          },
          {
            "name": "azure-cni-networkmonitor",
            "enabled" : false
          },
          {
           "name": "ip-masq-agent",
           "enabled" : false
          }
        ]
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "CLUSTER_NAME",
      "distro": "ubuntu",
      "vmSize": "Standard_D4s_v3",
      "vnetSubnetId": "SUBNET_ID",
      "availabilityProfile": "AvailabilitySet",
      "firstConsecutiveStaticIP": "MASTER_IP",
      "OSDiskSizeGB": 128,
      "customVMTags": {
          "EnvType"         : "*",
          "Deployer"        : "*"
          },
      "extensions": [
        {
          "name": "bootstrap",
          "singleOrAll": "All"
        }
     ]
    },
    "agentPoolProfiles": [
      {
        "name": "AGENT_NAME",
        "count": *,
        "distro": "ubuntu",
        "vmSize": "Standard_D16s_v3",
        "vnetSubnetId": "SUBNET_ID",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile" : "ManagedDisks",
        "diskSizesGB": [64],
        "OSDiskSizeGB": 128,
        "acceleratedNetworkingEnabled": true,
        "customVMTags": {
            "EnvType"         : "*",
            "Deployer"        : "*"
          },
        "preProvisionExtension": {
            "name": "prepare_vm_disks",
            "singleOrAll": "All"
        },
        "extensions": [
          {
            "name": "bootstrap",
            "singleOrAll": "All"
          }
       ]
      }
    ],
    "extensionProfiles": [
      {
          "name": "*",
          "version": "v1",
          "rootURL": "*",
          "script": "*",
          "urlQuery": "*"
      },
      {
          "name": "bootstrap",
          "version": "*",
          "extensionParameters": "* ",
          "rootURL": "*",
          "script": "*.sh",
          "urlQuery": "*"
      }
    ],
    "linuxProfile": {
      "adminUsername": "ADMIN_ACCOUNT",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "PUBLIC_KEY"
          }
        ]
      }
    },
    "aadProfile": {
      "serverAppID": "AAD_SERVER_APP_ID",
      "clientAppID": "AAD_CLIENT_APP_ID",
      "tenantID": "AZURE_TENANT_ID",
      "adminGroupID": "AAD_ADMIN_GROUP_ID"
    },
    "servicePrincipalProfile": {
      "clientId": "CLIENT_ID",
      "secret": "CLIENT_SECRET",
      "objectId": "OBJECT_ID"
    }
  }
}

**AKS Engine version**
v0.47.0

**Kubernetes version**
1.7.2

**Additional context**
Errors

kubectl --kubeconfig ~/kubeconfig exec -ti dnsutils -- nslookup kubernetes.default
;; connection timed out; no servers could be reached

command terminated with exit code 1

for i in `kubectl --kubeconfig ~/kubeconfig -n kube-system get pods -l k8s-app=kube-dns -o name`; do echo $i $(kubectl --kubeconfig ~/kubeconfig -n kube-system logs $i | grep -c SERVFAIL); done;
pod/coredns-5bcf8cc6dd-6xrs9 0
pod/coredns-5bcf8cc6dd-jv7jk 0
pod/coredns-5bcf8cc6dd-lwt7h 0

**Comment by jackfrancis** [comment]
Hi @satishsudini, why the `"--non-masquerade-cidr": ""` kubelet configuration? If ip-masq-agent is disabled, you want that to be set to the same value as your clusterSubnet (perhaps you are doing that manually and you have redacted that value?)

**Comment by jackfrancis** [comment]
It is possible there's a regression in the extensions interface, that is not always well tested.

Also, you could try the same configuration in v0.48.0 (just released) to get v1.17.4, which has Azure cloudprovider improvements to manage HTTP 429 throttling.
