### ISSUE TITLE
Get-ComputerInfo in New-InfraContainer spends ~44s to get WindowsVersion

### ISSUE THREAD

**Issue by AbelHu** [Azure/aks-engine#2946]
**Describe the bug**
Get-ComputerInfo in New-InfraContainer spends ~44s to get WindowsVersion
https://github.com/Azure/aks-engine/blob/13e72f24a00cade87c0e9773afd0404edf3c6b61/parts/k8s/windowskubeletfunc.ps1#L195-L204

**Steps To Reproduce**

**Expected behavior**
It should take less than 1 second to get WindowsVersion.

**AKS Engine version**
0.47.0
**Kubernetes version**

**Additional context**
We can use “(Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").ReleaseId” to get WindowsVersion in less than 1 second.

**Comment by marosset** [comment]
Nice find @AbelHu
