### ISSUE TITLE
Wrong configuration of azure-ip-masq-agent

### ISSUE THREAD

**Issue by dmeytin** [Azure/aks-engine#2947]
**Describe the bug**
After the k8s cluster deployment with aks-engine v0.48, azure-ip-masq-agent pods are failing with exception
**Steps To Reproduce**

apimodel should contain 
{ "addons": [
{
           "name": "ip-masq-agent",
           "enabled": true,
           "containers": [
           {
           "name": "ip-masq-agent",
           "image": "k8s.gcr.io/ip-masq-agent-amd64:v2.4.1",
           "cpuRequests": "50m",
           "memoryRequests": "50Mi",
           "cpuLimits": "50m",
           "memoryLimits": "250Mi"
           }
           ],
           "config": {
           "non-masq-cni-cidr": "168.63.129.16/32",
           "non-masquerade-cidr": "10.10.0.0/16"
           }
           }
]
}
**Expected behavior**
the component is deployed and all pods are running
**AKS Engine version**
v0.48
**Kubernetes version**
v1.16.8, v1.17.1, v1.17.3, v1.17.4
**Additional context**
kubectl logs azure-ip-masq-agent-g6xq8 -n kube-system 
flag provided but not defined: -enable-ipv6
Usage of /ip-masq-agent:
-alsologtostderr
log to standard error as well as files
-log_backtrace_at value
when logging hits line file:N, emit a stack trace
-log_dir string
If non-empty, write log files in this directory
-logtostderr
log to standard error instead of files
-masq-chain string
Name of nat chain for iptables masquerade rules. (default "IP-MASQ-AGENT")
-nomasq-all-reserved-ranges
Whether to disable masquerade for all IPv4 ranges reserved by RFCs.
-stderrthreshold value
logs at or above this threshold go to stderr
-v value
log level for V logs
-vmodule value
comma-separated list of pattern=N settings for file-filtered logging

**Workaround**
modify /etc/kubernetes/addons/ip-masq-agent by removing the two following lines:
--args
   - --enable-ipv6=false

**Comment by jackfrancis** [comment]
@dmeytin What is the input api model used to create the cluster?

**Comment by jackfrancis** [comment]
@aramase Any idea why the ip-masq-agent pod would be complaining about the `--enable-ipv6` flag? We're not seeing this anywhere in our E2E test data.

**Comment by aramase** [comment]
`--enable-ipv6` flag is only available from ip-masq-agent `v2.5.0`.

**Comment by jackfrancis** [comment]
@dmeytin you should be able to fix this by removing the `"image": "k8s.gcr.io/ip-masq-agent-amd64:v2.4.1"` configuration from your api model input. AKS Engine will choose the version of ip-masq-agent that works with its spec automatically (in the case of v0.48.0, it will use v2.5.0).
