### ISSUE TITLE
 Azure internal master load balancer doesn't respond to requests originated from within masters' nodes

### ISSUE THREAD

**Issue by dmeytin** [Azure/aks-engine#2948]
**Describe the bug**
Some workloads are executed from within the master nodes (e.g. kured).
When the workload needs to interact with apiserver using internal master lb 10.10.0.240, some  requests will fail since lb can't respond to the request originated from within the master
**Steps To Reproduce**
From within the master node use curl to interact with the apiserver:
curl 10.10.0.240/api/v2 
**Expected behavior**
Some requests (depends on amount of the master nodes) will fail. 
**AKS Engine version**
v0.48
**Kubernetes version**
1.16.*, 1.17.*
**Additional context**
The workaround is simple: modify apiserver configuration to advertise the local ip and not the LB:
/etc/kubernetes/manifests/apiserver.yaml - advertise 10.10.0.23* (on master 0: 230, on master 1: 231, etc.)

**Comment by jackfrancis** [comment]
@dmeytin, thank you for the workaround solution, I will try that
