### ISSUE TITLE
Audit addon is enabled by default, but apiserver is not configured to support audit policies

### ISSUE THREAD

**Issue by dmeytin** [Azure/aks-engine#2950]
**Describe the bug**
When deploying a new kubernetes cluster there are errors in the apiserver log: error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1"
**Steps To Reproduce**
This addon is enabled by default. 
**Expected behavior**
apiserver should be configured with --audit-dynamic-configuration=true
**AKS Engine version**
v0.48
**Kubernetes version**
0.16.*, 0.17.*
**Additional context**

**Comment by jackfrancis** [comment]
There are two different things being mentioned here.

1) the audit-policy error is spurious, we have a bug for that here: #1749 
2) What is the relationship of #1 to the `--audit-dynamic-configuration=true` apiserver configuration?

**Comment by jackfrancis** [comment]
Is this still an issue?
