### ISSUE TITLE
Use Standard LB by default

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2952]
We need to first ensure that these issues are addressed:

- https://github.com/Azure/aks-engine/issues/1970
- https://github.com/Azure/aks-engine/issues/2033

And test all known-working cluster configurations against Standard to surface any cluster configurations that don't play well w/ Standard LB.

In favor of changing:

- Standard is the default in AKS
- No Azure SLA for Basic LoadBalancer

In favor of keeping Basic:

- Fewer Azure IaaS resources to maintain (e.g., more LoadBalancer resources when using Standard)
- No Azure IaaS cost

**Comment by CecileRobertMichon** [comment]
references: 
https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard
https://docs.microsoft.com/en-us/azure/load-balancer/concepts-limitations#skus
https://docs.microsoft.com/en-us/azure/load-balancer/concepts-limitations#limitations

**Comment by jackfrancis** [comment]
In the above limitations, a key one is that Basic LB can only support one VMSS or AvailabilitySet in its backend pool. This means, essentially, that you can't run multiple node pool clusters w/ Load Balancers.
