### ISSUE TITLE
Feature Request: Cache .net/asp.net base image in Windows vhd by default

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#2961]
Most workloads run in Windows containers are using .net framework. We'd like speed up the boot time of Windows pods in newly scaled Windows nodes, cache .net/asp.net base image in Windows vhd by default will help much.

**Comment by marosset** [comment]
I don't think we will support this in aks-engine VHDs but you are more than welcome to build your own VHDs on top of the ask-engine produced VHDs.

We use package to produce images and you can find templates in /vhd/

After you produce VHDs with your container images cached you can use them with aks-engine deployments by looking at https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#windows-images

Hope this helps!

**Comment by zhiweiv** [comment]
OK, Thanks.
