### ISSUE TITLE
Signed Azure CNI binaries

### ISSUE THREAD

**Issue by jchauncey** [Azure/aks-engine#2973]
You can find the artifacts here - 

linux: `https://kubernetesartifacts.azureedge.net/azure-cni/<version>/binaries/azure-vnet-cni-linux-amd64-<version>-signed.tar`
windows: `https://kubernetesartifacts.azureedge.net/azure-cni/<version>/binaries/azure-vnet-cni-windows-amd64-<version>-signed.zip`

The following versions have been uploaded:
* 2020.1.31.1
* 2020.2.21.1
* 2020.2.27.1

**Comment by mboersma** [comment]
Fixed in #3075, and the publishing pipeline should be using signed binaries going forward. cc: @jchauncey
