### ISSUE TITLE
Add documentation for VMSS best practices

### ISSUE THREAD

**Issue by marosset** [Azure/aks-engine#2995]
**Describe the request**
Aks-engine should add documentation around best practices in configuring/working with VirtualMachineScaleSets

**Explain why AKS Engine needs it**
VMSS automated/rolling upgrade strategies can be dangerous for Kubernetes workloads because VMSS does not have the ability to cordon/drain pods from nodes before shutting them down.

Because of this we recommend not enabling automated upgrade strategies and instead use custom scripting or aks-egine upgrade/scale commands to perform upgrades and scaling.

**Describe the solution you'd like**
Document the above with more details.

**Describe alternatives you've considered**

**Additional context**

**Comment by marosset** [comment]
@craiglpeters @jackfrancis FYI

**Comment by fiunchinho** [comment]
is this documentation somewhere I can read? Thanks!

**Comment by jackfrancis** [comment]
@fiunchinho the issue was closed because of a lack of activity, I'll re-open.

**Comment by craiglpeters** [comment]
Are we actually going to do this? I think it makes sense to add this to cluster-api-provider-azure for sure

**Comment by jackfrancis** [comment]
@fiunchinho We've done a considerable documentation refresh, which covers lots of VMSS-specific guidance. Start here:

https://github.com/Azure/aks-engine/blob/master/docs/tutorials/cli-overview.md

Let us know if there's more you'd like covered!
