### ISSUE TITLE
Managed Identity support

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#3004]
AKS now supports Managed Identity(https://docs.microsoft.com/en-us/azure/aks/use-managed-identity), does AKS-Engine has equivalent feature?
I found a setting useManagedIdentity in clusterdefinitions.md, and it says it is still in alpha state.

**Comment by jackfrancis** [comment]
Hi @zhiweiv, Managed Identity is definitely supported, sorry for the stale docs! In fact we just merged a change to enable the use of pre-existing user assigned managed identity resources, and that came with a doc update:

https://github.com/Azure/aks-engine/pull/2960/files#diff-39c0bce26100cd1dcbe3f5b2a0ad31a4R75

**Comment by jackfrancis** [comment]
Let us know if the docs are still not clear!
