### ISSUE TITLE
Disable dashboard addon by default

### ISSUE THREAD

**Issue by sblinz** [Azure/aks-engine#3021]
**Describe the bug**

I cannot delete the Kubernetes dashboard deployment on a cluster deployed with aks-engine. I tried deleting all possible objects related to the kubernetes dashboard (and metrics-server) in the kube-system namespace and they are both simply re-created.

I know that you can disable the dashboard in the API model with the setting below but a) I do not want to recreate my cluster and b) I want to understand what process is force re-creating the dashboard.

```    
{
  "name": "kubernetes-dashboard",
  "enabled": false
},
```

**Steps To Reproduce**

After deploying the cluster with the following API model I tried to delete all objects associated with the dashboard in the kube-system namespacae.

`kubectl delete deployment,service,role,rolebinding,sa,secret,replicaset -n kube-system -l k8s-app=kubernetes-dashboard`

I also tried manually deleting them without using labels and looked through the various object types and other namespaces for dashboard items to delete.

I also did the same for the metrics-server and still both are re-created.

I also tried editing the dashboard deployment and setting replicas from 1 to 0 with `kubectl edit deployment kubernetes-dashboard -n kube-system1` but when it gets re-created after delete it has 1 again. It seems the metrics-server and dashboard deployment manifests are located in /etc/kubernetes/addons/ on the master. I'd like to understand what Kubernetes process/item/deployment is using these to re-create the metrics-server and dashboard.

An additional thing to know about my deployment: I patch the dashboard, metrics-server, and coredns to run on master (instead of a node). When I delete all items they are re-created back on master.

The api model used is below.

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.16",
      "kubernetesConfig": {
        "useManagedIdentity": false,
        "addons": [
          {
            "name": "blobfuse-flexvolume",
            "enabled": false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled": false
          },
          {
            "name": "nvidia-device-plugin",
            "enabled": false
          },
          {
            "name": "tiller",
            "enabled": false
          },
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "config": {
              "min-count": "0",
              "max-count": "20",
              "scan-interval": "10s",
              "max-total-unready-percentage": "80",
              "skip-nodes-with-system-pods": "false",
              "unremovable-node-recheck-timeout": "10s",
              "scale-down-unneeded-time": "10s",
              "scale-down-delay-after-add": "10s",
              "scale-down-delay-after-failure": "10s",
              "scale-down-delay-after-delete": "10s"
            }
          }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "<VPC>",
      "vmSize": "<VM size>",
      "vnetSubnetId": "<subnet id>",
      "firstConsecutiveStaticIP": "<first IP>"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool",
        "count": 1,
        "vmSize": "<VM size>",
        "imageReference": {
          "name": "<name>",
          "resourceGroup": "<resource group>",
          "subscriptionId": "<subscription id>",
          "gallery": "<gallery>",
          "version": "<version>"
        },        
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "vnetSubnetId": "<subnet id>"
      }
    ],
    "linuxProfile": {
      "adminUsername": "<username>",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

```

**Expected behavior**

Deleting all the kubernetes-dashboard items, especially the deployment, should kill it but some other process is re-creating it.

**AKS Engine version**

v0.48.0

**Kubernetes version**

v1.16

**Additional context**

the v0.48.0 AKS Engine deploying v1.16 Kubernetes will deploy v1.10 Dashboard which has a known bug with v1.16 Kubernetes. The dashboard gives 404 errors when trying to login and is unusable. I want to delete it and install the dashboard v2.0.0-rc3, the most recent release compatible with Kubernetes v1.16

**Comment by jackfrancis** [comment]
Hi @sblinz, what you are seeing is the effects of the `kube-addon-manager` reconcile the dashboard resources when they are removed from the cluster. If you want to make this manual removal persistent, ssh into your master and remove the dashboard yaml spec from:

- `/etc/kubernetes/addons/`

Then, manually remove all of the resources.

The `kube-addon-manager` component sources from that directory, and regularly compares the specs therein to the active resource state in the cluster; when it notices missing resources, it reconciles that.

**Comment by jackfrancis** [comment]
Let's use this issue as a reminder to remove the stale dashboard addon implementation from the list of automatically enabled addons. Do you mind if I change the title of the issue?

**Comment by sblinz** [comment]
@jackfrancis Thanks for the reply, that makes sense. I see that in /etc/kubernetes/addons/kubernetes-dashboard-deployment.yaml the deployment metadata includes `addonmanager.kubernetes.io/mode: Reconcile`.

Yes, feel free to change the title of the issue.
