### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by rbitia** [Azure/aks-engine#303]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
N/A
---

There's a bunch of broken links!

On this page https://github.com/Azure/aks-engine/blob/master/docs/README.md this link is broken https://github.com/Azure/aks-engine/blob/master/docs/how-to/README.md

Also these links are broken or gone?
https://github.com/Azure/aks-engine/blob/master/docs/kubernetes/deploy.md#aks-engine-the-long-way
https://github.com/Azure/aks-engine/blob/master/docs/aksengine.md#install-aks-engine

**Comment by bacongobbler** [comment]
Thanks @rbitia! This was my fault. I'll assign this to myself and fix up those broken links. Thanks for pointing that out!

**Comment by bacongobbler** [comment]
For reference, here are the correct links:

https://github.com/Azure/aks-engine/blob/master/docs/howto/README.md
https://github.com/Azure/aks-engine/blob/master/docs/tutorials/deploy.md#aks-engine-the-long-way (this is moving in #301 to the Quickstart Guide)
https://github.com/Azure/aks-engine/blob/master/docs/tutorials/quickstart.md#install

If you find any others please let me know.
