### ISSUE TITLE
EnableTcpReset for LoadBalancer rules on aks-engine provisioned LoadBalancers

### ISSUE THREAD

**Issue by juan-lee** [Azure/aks-engine#305]
Feature Request
Basic Azure LoadBalancers have long had the problem that they don't send tcp reset (RST) for an idle timeout. This causes a bad experience for clients because from their perspective the connection is still live. The client is unaware of the severed connection until they try to send data, at which time they get an error that the connection was closed. Consider a situation where the client is performing a `kubectl get po --watch`. If the connection silently times out w/out an RST, the watch will stop receiving events. 

Standard LoadBalancer now has the option to send an RST on idle timeout and is configured on each load balancer rule. We should enable this setting for the master and internal load balancer rules to improve the callers reliability. I've already spoken to @ritazh about the issue. We should consider enabling this in the azure cloud provider as well for Standard LoadBalancer.

k8s version: all supported versions that support standard load balancer
aks-engine version: 0.29.0

**Comment by ritazh** [comment]
Once this PR https://github.com/kubernetes/kubernetes/pull/72813 is merged, we can configure enableTcpReset.
