### ISSUE TITLE
Support customized daemonset created by nvidia-device-plugin addson

### ISSUE THREAD

**Issue by frcai** [Azure/aks-engine#3051]
**Describe the request**
We wish to add tolerations entry (e.g.  "foo") to the daemonset created by nvidia-device-plugin addson.
https://github.com/Azure/aks-engine/tree/master/examples/addons/nvidia-device-plugin

      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: "true"
      - key: "foo"
        operator: Exists

**Explain why AKS Engine needs it**

**Describe the solution you'd like**
Support specify customized properties in the addons entry.
"addons": [
          {
            "name": "nvidia-device-plugin",
            "enabled": true
            "tolerations": "foo"
          }
        ]

**Describe alternatives you've considered**
I could deploy one yaml file (with customized tolerations) to create daemonset per https://docs.microsoft.com/en-us/azure/aks/gpu-cluster

**Additional context**

**Comment by jackfrancis** [comment]
@frcai, just making sure you understand if we do this work it will be for AKS Engine-created clusters only, it won't have any affect on AKS clusters.

**Comment by frcai** [comment]
yes - we use AKS-Engine managed cluster.
