### ISSUE TITLE
Azure Kubernetes VM node size change not reflecting in Azure Kubernetes Service

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/aks-engine#3057]
Hi Team,

We had scaled down the VM size (VM SCaleset) of the Node to a Lower Standard DS2_V2 from Standard DS4_V3.The node size got reduced.

But when we check in the portal for the Kubernetes the node VM size is still showing as Standard DS4_V3

![image](https://user-images.githubusercontent.com/43850474/78989851-6af1fd00-7b52-11ea-8403-02067af18952.png)

Can someone till whether this is a bug or an issue

We have successfully resized the machine ?

**Comment by andyzhangx** [comment]
change vm size of existing node pool in aks is not supported actually, that is a workaround, you may add a new node pool with new vm size and then delete original node pool

**Comment by nidiculageorge** [comment]
@andyzhangx we have resized the size of the vm scale set to standard ds2ve and we didnt face any issue.What is the problem in resizing the same

**Comment by nidiculageorge** [comment]
can this issue be opened as we have to find a solution

**Comment by andyzhangx** [comment]
why not add a new node pool with new vm size?

**Comment by nidiculageorge** [comment]
cant we resize theexisting node,we have done in the existing environment will it cause any issues

**Comment by mboersma** [comment]
This is the AKS Engine open source project, [not the AKS](https://github.com/Azure/aks/issues) managed service. For questions about AKS, please open an issue at https://github.com/Azure/aks/issues.
