### ISSUE TITLE
Allow the full ip-masq-agent config map to be specified

### ISSUE THREAD

**Issue by juan-lee** [Azure/aks-engine#306]
Bug
Allow specifying the full ip-masq-agent config map in the model. Users will need to be able to specify multiple CIDRs under nonMasqueradeCIDRs, which is not allowed via the model now. @tariq1890 

k8s version: all supported
aks-engine version: 0.29.0

**Comment by jackfrancis** [comment]
It’s already possibly to completely override the default definition for any addon w/ a static config at cluster creation time. Tariq can provide details.

**Comment by sgoings** [comment]
@tariq1890 - could you give some pointers here?
