### ISSUE TITLE
Support Azure Government

### ISSUE THREAD

**Issue by bspann** [Azure/aks-engine#307]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of aks-engine?**:Latest

---

**Kubernetes version**: ANY

**What happened**: Microsoft Azure for Government is not supported.  I have a Government tenant and would like to be able to use Kubernetes much like the AKS service in Azure Commercial.  You have support for Mooncake, why not Fairfax?

**What you expected to happen**: The ability to deploy into Azure for Government.  Probably just specify a flag on the aks-engine when building the templates to swap out the ".com" for ".us"  

**How to reproduce it** (as minimally and precisely as possible): Just follow the steps but point it at the Azure for Government cloud and you will get an error saying it cannot find the needed image type.

**Anything else we need to know**: None

**Comment by CecileRobertMichon** [comment]
Hi @bspann, which distro value are you using in your apimodel? You will need to use distro "ubuntu" as we do not yet have support for VHDs in us gov.

**Comment by GreenCee** [comment]
@CecileRobertMichon I was able to replicate by creating a minimal api-model for aks-engine generate which does not have any indication that the target environment will be used in gov.
The templates created will default to using "distro": "aks".

Workarounds: 
1. Use aks-engine deploy … --azure-env=AzureUSGovernmentCloud
2. Generate the templates then modify the "distro" argument to "ubuntu"

I'll add these to the updated aks-engine on Azure Government documentation I'm writing until VHDs are available

**Comment by CecileRobertMichon** [comment]
I believe you can also specify a location in your apimodel when using `generate`. 

This makes sense since the default distro is "aks" unless the location is a gov cloud, aks-engine needs to know the location is gov in order to set the right default.
