### ISSUE TITLE
aks-engine cluster creation fails with VM extension error

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/aks-engine#3077]
**Describe the bug**

aks-engine cluster creation fails with VM extension error

**Steps To Reproduce**

1. 1. Trying to follow Azure Arc private preview instructions, I did follow the steps to create a cluster using AKS-Engine. Configure API Model JSON file :
{
"apiVersion": "vlabs",
"properties": {
"orchestratorProfile": {
"orchestratorType": "Kubernetes",
"orchestratorRelease": "1.16"
},
"masterProfile": {
"count": 1,
"dnsPrefix": "",
"vmSize": "Standard_B1s"
},
"agentPoolProfiles": [
{
"name": "arcpool1",
"count": 2,
"vmSize": "Standard_B1s"
}
],
"linuxProfile": {
"adminUsername": "azureuser",
"ssh": {
"publicKeys": [
{
"keyData": ""
}
]
}
},
"servicePrincipalProfile": {
"clientId": "<my client ID was set here !>",
"secret": "<my secret was set here !>"
}
}
}

2.  Run CLI
aks-engine deploy --subscription-id $subId -g $azurearc_rg_name --client-id $spnAppId --client-secret $spnAppPassword --dns-prefix $dnsPrefix --location $arc_location --api-model $apimodel --force-overwrite

3.  After 10 minutes all resources should be created in the RG , you can check it from the portal
4. After 1h , the CLI will finally stop and returns error

**Expected behavior**

CLI should end without any error

**AKS Engine version**

aks-engine version: v0.49.0

Azure details:
arc_location="eastus"

Kubernetes version: 1.16
Agent version(s) 0.1.6
az version
This command is in preview. It may be changed/removed in a future release.
{
"azure-cli": "2.3.1",
"azure-cli-command-modules-nspkg": "2.0.3",
"azure-cli-core": "2.3.1",
"azure-cli-nspkg": "3.0.4",
"azure-cli-telemetry": "1.0.4",
"extensions": {
"aks-preview": "0.4.39",
"azure-firewall": "0.3.0",
"connectedk8s": "0.1.3",
"k8sconfiguration": "0.1.6"
}
}

**Kubernetes version**

**Additional context**

I reported https://github.com/Azure/azure-arc-kubernetes-preview/issues/111

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n "status": "Failed",\r\n "error": {\r\n "code": "ResourceDeploymentFailure",\r\n "message": "The resource operation completed with terminal provisioning state 'Failed'.",\r\n "details": [\r\n {\r\n "code": "**VMExtensionProvisioningError",\r\n "message": "VM has reported a failure when processing extension 'cse-master-0'**. Error message: \"Enable failed: failed to execute command: command terminated with exit status=30\n[stdout]\nWed Apr 15 18:23:04 UTC 2020,k8s-master-33314784-0\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "\r\n }\r\n ]\r\n }\r\n}"}]}
I have no log at /var/log/azure/custom-script/handler.log but a few days ago while I worked on an AKS cluster I did use :
az vmss extension set 
--resource-group $managed_rg 
--vmss-name $vmss_name 
--name VMAccessForLinux 
--publisher Microsoft.OSTCExtensions 
--protected-settings "{"username":"${aks_admin_username}", "ssh_key":"$(cat ~/.ssh/${ssh_key}.pub)"}" 
--version 1.4 
--verbose
az vmss update-instances --instance-ids '*' 
--resource-group $managed_rg 
--name $vmss_name
az vmss extension set 
--resource-group $managed_rg 
--vmss-name $vmss_name 
--name AADLoginForLinux 
--publisher Microsoft.Azure.ActiveDirectory.LinuxSSH 
--verbose

**Logs**

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=30\\n[stdout]\\nWed Apr 15 18:23:04 UTC 2020,k8s-master-33314784-0\\n\\n[stderr]\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

```console
WARN[0004] apimodel: missing masterProfile.dnsPrefix will use "azurearc-secgov-eastus"
INFO[0015] Starting ARM Deployment rg-azurearc-secgov-eastus-880710241 in resource group rg-azurearc-secgov-eastus. This will take some time...

INFO[4214] Finished ARM Deployment (rg-azurearc-secgov-eastus-880710241). Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=30\\n[stdout]\\nWed Apr 15 18:23:04 UTC 2020,k8s-master-33314784-0\\n\\n[stderr]\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"}]
Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=30\\n[stdout]\\nWed Apr 15 18:23:04 UTC 2020,k8s-master-33314784-0\\n\\n[stderr]\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"}]
```

**Comment by jackfrancis** [comment]
Hi @ezYakaEagle442, are the VMs still around? If so, you can hop onto the master-0 VM and look at CSE (CustomScriptExtension) provisioning logs at `/var/log/azure/cluster-provision.log`, which should give more information why Kubernetes failed to launch.

**Comment by ezYakaEagle442** [comment]
the VM are still there but unfortunately it looks like I can not connect through SSH as no public keys was set in the API model (it did failed when I did copy/paste the pub key) : 

      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              **"keyData": ""**
            }
          ]
        }

**Comment by jackfrancis** [comment]
If this is reproducible in your environment, build a new cluster w/ an ssh key in the api model, and then gather the provisioning logs, which should tell us if anything failed in provisioning.

Also, `sudo journalctl -u kubelet` will give you more detailed logs on why the kubelet service didn't launch reliably.

**Comment by jackfrancis** [comment]
I think the fact that you ran into this error suggests a documentation gap. What can we do to shore up docs so folks building AKS Engine for the first time (you mention you're experimenting w/ Arc) don't have these issues?
