### ISSUE TITLE
Labels of master node aren't set correctly by cloud-node-manager after upgrading

### ISSUE THREAD

**Issue by chewong** [Azure/aks-engine#3090]
**Describe the bug**

**Steps To Reproduce**

- Create an aks-engine cluster with `useCloudControllerManager` enabled
- Change the master's VM size in the API model and upgrade the cluster
- `beta.kubernetes.io/instance-type` and `node.kubernetes.io/instance-type` labels on the master node don't reflect the updated VM size

**Expected behavior**
`beta.kubernetes.io/instance-type` and `node.kubernetes.io/instance-type` labels on the master node should reflect the updated VM size after upgrading.

**AKS Engine version**
master

**Kubernetes version**
1.16+

**Additional context**
/cc @feiskyer

**Comment by chewong** [comment]
I think the issue is that aks-engine didn't unregister the master node from the API server before deleting the VM. When the new master node comes online, kubelet is able to find a copy of the old master node and decides to [update the new node status using the old one](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L114-L125).
Therefore, [`initializeNode`](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/nodemanager/nodemanager.go#L350) from cloud-node-manager is not triggered since technically no node is added or updated.

**Comment by feiskyer** [comment]
exactly, the node initialize is only triggered on node register phase. Master node need to unregister and register again to get these labels updated.

**Comment by bridgetkromhout** [comment]
Closing due to AKS Engine deprecation, after consulting with @mboersma; no features will be added at this juncture.
