### ISSUE TITLE
Getting 429 TooManyRequests when doing Managed disk attach operation

### ISSUE THREAD

**Issue by amodm** [Azure/aks-engine#3097]
**Describe the bug**
When attaching managed disks to a node, our cluster goes into a spin with lots of `429 TooManyRequests` error messages like the following

```
E0419 19:06:19.573411       1 attacher.go:122] azureDisk - Error checking if volumes ([ads-solr-master-prod-disk]) are attached to current node ("k8s-agentpool1-sin0-vmss00002z"). err=compute.VirtualMachineScaleSetVMsClient#Get: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="OperationNotAllowed" Message="The server rejected the request because too many requests have been received for this subscription." Details=[{"code":"TooManyRequests","message":"{\"operationGroup\":\"GetVMScaleSetVM30Min\",\"startTime\":\"2020-04-19T19:06:19.4543443+00:00\",\"endTime\":\"2020-04-19T19:21:19.4543443+00:00\",\"allowedRequestCount\":5000,\"measuredRequestCount\":6756}","target":"GetVMScaleSetVM30Min"}] InnerError={"internalErrorCode":"TooManyRequestsReceived"}
```

**Steps To Reproduce**
The issue isn't completely reproducible, and seems to show up in our larger clusters only unfortunately, which are our production clusters. On our production cluster, this seems to show up once every 5-7 attempts, post which we need to scramble.

The issue is always triggered immediately after a `az vmss disk attach` command, which when stuck indicates that the issue has been triggered. Having the autoscaler running obviously seems to amplify the issue, but even after many hours of the autoscaler shut down, the controller manager doesn't seem to calm down (if there's an existing azureDisk in the cluster somewhere).

API model is here: [apimodel.json.zip](https://github.com/Azure/aks-engine/files/4500012/apimodel.json.zip)

**Expected behavior**
The disk attach should have no effect on cluster's stability.

**AKS Engine version**
v0.44.0

**Kubernetes version**
1.16.1

**Additional context**
Autoscaler was disable shortly after the incident occurred, and even after 6 hours of that, the call rate to Azure control plane didn't come down.

When debugging this with Azure support team (SR 120041924000251), we saw that even before we did `az vmss disk attach`, the controller manager had been sending requests at a fairly high rate. I'll try to include that info once I receive it from Azure support team.

**Comment by amodm** [comment]
Apparently, the controller manager was already sending a very large number of requests: ~7000/hr, and the number of requests seems to scale linearly with number of nodes in the cluster. So it's possible that the disk operation was just the last straw. Either ways, the number of calls being made is currently not compatible with Azure VMSS rate limits at all.

**Comment by jackfrancis** [comment]
@amodm a lot of cloudprovider optimizations have been made between 1.16.1 and the latest 1.16 (1.16.9) that should move the subscription requests downward for this cluster.

What's your current cluster maintenance workflow? How can we get you to 1.16.9 (or newer versions of 1.17/1.18)?

**Comment by amodm** [comment]
Thanks @jackfrancis. We'll attempt shifting to 1.16.9 over the next couple of days at low traffic hours, and revert with findings.

On our current running SR, I was pointed to https://github.com/kubernetes-sigs/cloud-provider-azure/issues/247 - Is this what you were referring to when you mentioned cloud provider optimisations?

**Comment by amodm** [comment]
@jackfrancis upgrading resolved the issue. Thanks.

**Comment by jackfrancis** [comment]
@amodm Thank you for checking back w/ your findings, glad that recent releases of cloudprovider are improving your operational scenario!

cc @aramase @ritazh
