### ISSUE TITLE
Reinforce dual stack and ipv6 documentation

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3105]
**Describe the request**

Let's purposefully add some more user documentation for all the ipv6 scenarios now supported by aks-engine.

**Explain why AKS Engine needs it**

ipv6 scenarios are mostly dev-focused at this point; without documentation we're discouraging users from experimenting

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackfrancis** [comment]
@aramase Do you think we can close this issue, or has sufficient additional documentation been added over the past few months?

**Comment by aramase** [comment]
@jackfrancis We have started docs for dualstack and IPv6. We can close this issue.
