### ISSUE TITLE
Rationalize defaults enforcement flows for ipv6 cluster configurations

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3106]
At present, the ipv6 surface area offers a lot of configuration:

- ipv6 only
- dual stack
- + kubenet
- + Azure CNI

Let's audit the defaults enforcement to produce the simplest possible "blessed defaults", with E2E configurations to support them.

**Comment by jackfrancis** [comment]
@aramase has this surface area stabilized? If so, I think we should prioritize this work item so that AKS Engine has the appropriate test coverage.

**Comment by aramase** [comment]
@jackfrancis Nothing much has changed since this issue was opened. IPv6 is still in beta and dualstack is in alpha.

**Comment by jackfrancis** [comment]
Cool, I'll work with you to get some prototype E2E jobs defined so we can have basic coverage and be ready when things graduate beyond alpha/beta.

**Comment by jackfrancis** [comment]
won't do
