### ISSUE TITLE
Can't upgrade cluster using aks-engine 0.49 that was created using previous aks-engine versions

### ISSUE THREAD

**Issue by dmeytin** [Azure/aks-engine#3114]
**Describe the bug**
The new release of aks-engine (0.49) includes update of azure-sdk-for-go that brought in new ARM APIs. As a result some elder api models are not working.
Example, the name of the load balancer equals to the managed identity name

Error: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplate" Message="Deployment template validation failed: 'The template reference 'xxx-1' is ambiguous: there are multiple template resources '/subscriptions/SUBS_ID/resourceGroups/RG_ID/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxx-1,/subscriptions/SUBS_ID/resourceGroups/RES_IDproviders/Microsoft.Network/loadBalancers/xxx-1' defined with this name. Please use fully qualified resource identity instead. Please see https://aka.ms/arm-template-expressions/#reference for usage details.'." AdditionalInfo=[{"info":{"lineNumber":0,"linePosition":0,"path":""},"type":"TemplateViolation"}]
**Steps To Reproduce**
{
  "apiVersion": "vlabs",
  "properties": {
  
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.16.8",
      "kubernetesConfig": {
        "loadBalancerSku": "standard",
        "apiServerConfig": {
           "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration",
           "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
           "--oidc-client-id": "CLIENT_ID",
           "--oidc-groups-claim": "roles",
           "--oidc-issuer-url": "https://login.microsoftonline.com/TENANT_ID/v2.0",
           "--oidc-username-claim": "email",
           "--oidc-username-prefix": "oidc:"           
          },
          "useManagedIdentity": true,
          "userAssignedID": "xxx-identity-1",
          "addons": [
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "pools": [
              {
                "name": "atpdev1neu",
                "config": {
                  "min-nodes": "8",
                  "max-nodes": "99"
                }
              }
			],
			"containers": [
            {
              "name": "cluster-autoscaler",
              "image": "gcr.io/google-containers/cluster-autoscaler:v1.16.4",
              "cpuRequests": "100m",
              "memoryRequests": "2Gi",
              "cpuLimits": "100m",
              "memoryLimits": "2Gi"
            }
            ],
            "config": {
              "scan-interval": "30s"
			  }
          },
		  {
            "name": "tiller",
            "enabled" : false
          },
		  {
            "name": "keyvault-flexvolume",
            "enabled" : false
          },
		  {

            "name": "blobfuse-flexvolume",
            "enabled": false
          },
		  {
            "name": "kubernetes-dashboard",
            "enabled" : false
          },
          {
           "name": "ip-masq-agent",
           "enabled": true,
           "containers": [
           {
           "name": "ip-masq-agent",
           "image": "k8s.gcr.io/ip-masq-agent-amd64:v2.5.0",
           "cpuRequests": "50m",
           "memoryRequests": "50Mi",
           "cpuLimits": "50m",
           "memoryLimits": "250Mi"
           }
           ],
           "config": {
           "non-masq-cni-cidr": "168.63.129.16/32",
           "non-masquerade-cidr": "10.10.0.0/16"
           }
           }		  
        ]
		}
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "xxx-1",
      "vmSize": "Standard_D4_v2",
	  "osDiskSizeGB": 64,
      "vnetSubnetId": "/subscriptions/SUBSCRIPTION_ID1/resourceGroups/xxx-1/providers/Microsoft.Network/virtualNetworks/clusterVnet/subnets/masterSubnet",
      "firstConsecutiveStaticIP": "10.10.0.230",
      "vnetCidr": "10.10.0.0/16",
      "subjectAltNames": [
        "xxx-1.wdatp.windows.com"
      ]
    },
    "agentPoolProfiles": [
      {
        "name": "atpdev1neu",
        "count": 8,
        "vmSize": "Standard_D4_v2",
        "vnetSubnetId": "/subscriptions/SUBSCRIPTION_ID1/resourceGroups/xxx-1/providers/Microsoft.Network/virtualNetworks/clusterVnet/subnets/agentSubnet",
        "availabilityProfile": "VirtualMachineScaleSets",
		"scaleSetPriority": "Low",
        "storageProfile": "ManagedDisks",
        "osDiskSizeGB":  400,
        "acceleratedNetworkingEnabled": true,
		"singlePlacementGroup": false
      }
    ],
    "linuxProfile": {
      "adminUsername": "wdatpuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    }   
  }
}

**Expected behavior**

**AKS Engine version**
0.49
**Kubernetes version**
1.16.8
**Additional context**

**Comment by jackfrancis** [comment]
I'm able to reproduce this.

I think the near term guidance would be to *not* use the same name for your Managed Identity resource (userAssignedID) and the MasterProfile.DNSPrefix.

AKS Engine has a convention of re-using the MasterProfile.DNSPrefix value as the name of the Standard LoadBalancer resource. For now, let's keep that convention, and validate that using a discrete userAssignedID value works for all new clusters after v0.48.0.

I think for any existing clusters built prior to v0.49.0 that share a common value for MasterProfile.DNSPrefix and userAssignedID there won't be an upgrade path due to the change in ARM validation. :(
