### ISSUE TITLE
Creating cluster in AzureUSGovernment environment with aks-engine v0.48.0 fails with CSE extension failure on master

### ISSUE THREAD

**Issue by gurudattest** [Azure/aks-engine#3145]
**Describe the bug**
When creating cluster with aks-engine v0.48.0 in the AzureUSGovernment environment, its failing at some CSE on master. The same setup works fine in the Public cloud.

Here's the error I'm getting

_{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "VMExtensionProvisioningError",
                "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=30\n[stdout]\nTue Apr 21 00:52:19 UTC 2020,k8s-master-13594280-0\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
            }
        ]
    }
}_

**Steps To Reproduce**
Download aks-engine v0.48.0

run aks-engine generate and az deploy with the generated templates.

**Expected behavior**
Cluster created successfully

**AKS Engine version**
0.48.0

**Kubernetes version**
1.15.11

**Additional context**

**Comment by jackfrancis** [comment]
This is due to the requirement for including a `"location"` value in the input api model. That requirement has been documented.
