### ISSUE TITLE
enable the "canal" in aks-engine?

### ISSUE THREAD

**Issue by andyliuliming** [Azure/aks-engine#3147]
**Describe the request**
enable the flannel + calico in aks engine.

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackfrancis** [comment]
Hi @andyliuliming, I suspect this is possible, but no one is working on it to my knowledge.

cc @rbitia @craiglpeters
