### ISSUE TITLE
Should expose error details in Windows CSE for better troubleshooting

### ISSUE THREAD

**Issue by AbelHu** [Azure/aks-engine#3156]
**Describe the bug**
exit 1 in Windows CSE does not help troubleshooting
https://github.com/Azure/aks-engine/blob/95b7254ec553c4397bea26cbc7dcc10fd5d1f07d/parts/k8s/kuberneteswindowssetup.ps1#L437

**Steps To Reproduce**

**Expected behavior**
We can identify the failed step via exit code in Windows CSE.

**AKS Engine version**
v0.50.0
**Kubernetes version**

**Additional context**

**Comment by AbelHu** [comment]
How do we change it from 
```
    Write-Error $_
    exit 1
```
to
```
    Write-Error $_
    throw $_
```

**Comment by AbelHu** [comment]
cc @marosset

**Comment by marosset** [comment]
When I looked into this in the Fall 2019 I found that the Windows VM agent could only report  pass/fail for custom script extensions and the only way to get error details was to check the logs in c:\azuredata\
Let me try and find the docs  where i found this info.

**Comment by jackfrancis** [comment]
Can we send @AbelHu a trophy for the best issue title in the queue?!

🏆

**Comment by AbelHu** [comment]
@marosset CSE still returns exit code 1 but it can expose the error output if we throw the error in the catch block.

I tested this custom script: [https://abeltestcse.blob.core.windows.net/scripts/testcse.ps1](https://abeltestcse.blob.core.windows.net/scripts/testcse.ps1) and the failed result is as below

![image](https://user-images.githubusercontent.com/6416187/80570106-ccf4a280-8a2c-11ea-8c04-148af55eab94.png)
