### ISSUE TITLE
Upgrade fails since v.0.50.0 if using availability sets

### ISSUE THREAD

**Issue by mtgerb** [Azure/aks-engine#3185]
Upgrade from 1.15.7 to version 1.16.9 fails if using availability sets since v.0.50.0

**Steps To Reproduce**

1. Create a cluster with availability sets, version 1.15.7 and aks-engine v0.48.0
2. Use the aks-engine v0.50.0 to upgrade the cluster to version 1.16.9

**Current behaviour**

Upon upgrading the new master the cse script fails with error code 13
(Hint on linux error code 13 EACCES = Permission denied)

**Expected behavior**

The cluster upgrade should succeed

**AKS Engine version**

v0.48.0 and v0.50.0

**Kubernetes version**

1.15.7 and 1.16.9

**Additional context**

Using availability sets and the basic loadbalancer

**Comment by mboersma** [comment]
I tried this scenario and had a successful upgrade. Both master and nodepool were availability sets, with basic loadbalancer. Any additional context that might help to isolate or reproduce this?

**Comment by mtgerb** [comment]
I just tried it again and this time it worked without any failures at all. As far as I can see, the failure yesterday occurred somewhere during pulling a docker image (after moby was installed). I guess it was some temporary failure of the docker registry or something like that.

**Comment by mtgerb** [comment]
But what I noticed in my second try is that the master was rebooted right away after the cse script finished. Maybe there is a race condition with the reboot?

**Comment by mtgerb** [comment]
Okay got it again on the third try:
That is the failing command:
`+ mount /var/lib/etcddisk
+ /bin/chown -R etcd:etcd /var/lib/etcddisk
/bin/chown: changing ownership of '/var/lib/etcddisk/DATALOSS_WARNING_README.txt': Operation not permitted
+ exit 13`

**Comment by mboersma** [comment]
Excellent, I think you pinpointed it. We think it may have been introduced by #3126.
