### ISSUE TITLE
consolidate addons specs in single files

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3188]
Right now we maintain Kubernetes-version-specific addons specs in a discrete, per-Kubernetes-specific directory under `parts/k8s/addons/`. That organization was established prior to processing the addon specs through a go template layer.

Now that we do have access to the Kubernetes version context via go template expressions, we can apply per-version specs in a single file for each addon under `parts/k8s/addons/`. This will make long-term maintenance of the addons much more trivial and easier to understand/document.

**Comment by mboersma** [comment]
Let's do this one addon at a time, to make reviewing easier.

**Comment by jackfrancis** [comment]
Yep, here's the first one: https://github.com/Azure/aks-engine/pull/3189
