### ISSUE TITLE
Regular Community Engagement

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#32]
Let's' discuss here a model for regularly engaging w/ the aks-engine user and dev community.

- public communication channels
- regular community meetings
- publishing roadmap

**Comment by tariq1890** [comment]
My two cents: As a first step, I think it would be great to hop onto the sig-azure community meetings and begin our engagement with the community there. I think this would help us reach out to the community and make our presence known gradually.

**Comment by tariq1890** [comment]
https://github.com/kubernetes/community/tree/master/sig-azure

**Comment by vijaygos** [comment]
Is there a slack channel that I can join?
