### ISSUE TITLE
nvidia plugin fails after node restart

### ISSUE THREAD

**Issue by sdruc** [Azure/aks-engine#3202]
I used aks-engine to create a Kubernetes 1.15.10 cluster with a gpu capable node pool using the following model
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.15",
      "orchestratorVersion": "1.15.10",  
      "kubernetesConfig": {
        "useManagedIdentity": true,
        "kubeletConfig": {"--max-pods": "110"},         
      }
    },    
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
        {
        "name": "cpupool",
        "count": 1,
        "vmSize": "Standard_A8_v2",
        "osDiskSizeGB": 50,
        "availabilityProfile": "VirtualMachineScaleSets",
        "scaleSetPriority": "Regular",
        "storageProfile": "ManagedDisks",
        "osType": "Linux",
        "distro": "aks-ubuntu-18.04"
        },
      {
        "name": "nc6pool",
        "count": 1,
        "vmSize": "Standard_NC6",
        "osDiskSizeGB": 500,
        "availabilityProfile": "VirtualMachineScaleSets",
        "scaleSetPriority": "Spot",
        "scaleSetEvictionPolicy": "Deallocate",
        "spotMaxPrice": -1,
        "storageProfile": "ManagedDisks",
        "osType": "Linux",
        "distro": "aks-ubuntu-18.04"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    }
  }
}

Upon creation the nvidia plugin works as expected. However after deallocating and re-starting the pool, the nvidia plugin fails for some/all nodes.

This is the error in the pod description: 

Warning  Failed     8m34s                kubelet, k8s-nc6pool-56779174-vmss000002  Error: failed to start container "nvidia-device-plugin-ctr": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --utility --pid=12435 /var/lib/docker/overlay2/001d155c61897586dda9044ce0b035116f193276095ec2e79a58fd7d6c5896b0/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown

**Comment by jackfrancis** [comment]
Hi @sdruc, can you explain what you mean by "deallocating and re-starting the pool"?

**Comment by sdruc** [comment]
Hi @jackfrancis,

I mean that I use the azure cli to run the following commands  

az vmss deallocate --name <vmss_name> --resource-group <cluster_resource_group>  --instance-ids "*" 

then after some time I run

az vmss start --name <vmss_name> --resource-group <cluster_resource_group>  --instance-ids "*" 

I don't know if it bears any relevance but my cluster is in north europe.

**Comment by jackfrancis** [comment]
I can reproduce (thanks for the clear steps @sdruc!):

```
$ k describe pod cuda-vector-add-8hdjn
Name:         cuda-vector-add-8hdjn
Namespace:    default
Priority:     0
Node:         k8s-agentpool1-37030907-vmss000000/10.240.0.34
Start Time:   Mon, 11 May 2020 10:28:39 -0700
Labels:       controller-uid=59fb84ce-7a55-4bd7-bfc2-d7b5e37acd0c
              job-name=cuda-vector-add
Annotations:  kubernetes.io/psp: privileged
Status:       Failed
IP:           10.240.0.44
IPs:
  IP:           10.240.0.44
Controlled By:  Job/cuda-vector-add
Containers:
  cuda-vector-add:
    Container ID:   docker://88aca640d23b60d1b618de23f4578790ff08ff3250d1d1c987e256ea2a12a7a5
    Image:          k8s.gcr.io/cuda-vector-add:v0.1
    Image ID:       docker-pullable://k8s.gcr.io/cuda-vector-add@sha256:0705cd690bc0abf54c0f0489d82bb846796586e9d087e9a93b5794576a456aea
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --compat32 --graphics --utility --video --display --require=cuda>=8.0 --pid=9426 /var/lib/docker/overlay2/d66399fa8280255479b9e77e6517767dabe859035ab25f0522a7a326a791ec3c/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown
      Exit Code:    128
      Started:      Mon, 11 May 2020 10:28:41 -0700
      Finished:     Mon, 11 May 2020 10:28:41 -0700
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tkbdk (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-tkbdk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tkbdk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  accelerator=nvidia
                 beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From                                         Message
  ----     ------            ----               ----                                         -------
  Warning  FailedScheduling  14m (x4 over 17m)  default-scheduler                            0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taint {node.kubernetes.io/unreachable: }, that the pod didn't tolerate.
  Warning  FailedScheduling  14m (x2 over 14m)  default-scheduler                            0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taint {node.cloudprovider.kubernetes.io/shutdown: }, that the pod didn't tolerate.
  Normal   Scheduled         14m                default-scheduler                            Successfully assigned default/cuda-vector-add-8hdjn to k8s-agentpool1-37030907-vmss000000
  Normal   Pulled            14m                kubelet, k8s-agentpool1-37030907-vmss000000  Container image "k8s.gcr.io/cuda-vector-add:v0.1" already present on machine
  Normal   Created           14m                kubelet, k8s-agentpool1-37030907-vmss000000  Created container cuda-vector-add
  Warning  Failed            14m                kubelet, k8s-agentpool1-37030907-vmss000000  Error: failed to start container "cuda-vector-add": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --compat32 --graphics --utility --video --display --require=cuda>=8.0 --pid=9426 /var/lib/docker/overlay2/d66399fa8280255479b9e77e6517767dabe859035ab25f0522a7a326a791ec3c/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown
```

In the meantime, I recommend you use VMSS scale instead of deallocate/start, as we know that works.

**Comment by jackfrancis** [comment]
I was able to confirm that scaling a node pool down to zero using the VMSS API, and then scaling back out to > 0, works. Is that an acceptable workflow, or does that present a functional gap as compared to deallocate/start?

**Comment by sdruc** [comment]
Actually that is better presumably since the vms won't incur storage charges. Would this not break anything on the k8s side though?

**Comment by jackfrancis** [comment]
Nodes are dynamic by design in k8s, this will work fine.

Go ahead and re-open if you struggle to implement scaling into your operational workflow!
