### ISSUE TITLE
clusterdefinitions.md says smb-flexvolume is enabled by default, but it not

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#322]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE 
---

**What version of aks-engine?**:
master
---

**What happened**:
in clusterdefinitions.md it says smb-flexvolume is enabled by default, but it is not actually,
we can find `DefaultSMBFlexVolumeAddonEnabled = false` in const.go.

https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md
https://github.com/Azure/aks-engine/blob/master/pkg/api/const.go

**Comment by CecileRobertMichon** [comment]
@andyzhangx any pointers on what the default should be?

**Comment by andyzhangx** [comment]
SMBFlexVolumeAddon should be disabled by default, I forgot to change the doc, let me change it later.

**Comment by CecileRobertMichon** [comment]
Thanks @andyzhangx. @zhiweiv if you'd like to open a PR to fix it, feel free to do so!
