### ISSUE TITLE
LoadBalancer pool cleared when installing a DSC extension on Windows VMSS

### ISSUE THREAD

**Issue by vavane-ms** [Azure/aks-engine#3229]
**Describe the bug**
We need to run a DSC extension on our Linux and Windows pool nodes, and that extension reboots VMs when the installation script runs. We only have LoadBalancer services deployed on Windows, so the bug report is for Windows. When the extension is run, the cluster's LoadBalancer pool is cleared by the cluster's service principal and not restored.

**Steps To Reproduce**
Install a VMSS extension as part of cluster ARM template. Reboot nodes one by one as part of the extension installation script.
We are using a basic LoadBalancer.

**Expected behavior**
Nodes are added back to the LoadBalancer backend pool.

**AKS Engine version**
aks-release-v0.47.0-1-aks

**Kubernetes version**
1.15.10

**Additional context**
This seems to be related to https://github.com/kubernetes/kubernetes/issues/80365, but since that issue is supposed to be fixed, maybe it's something else.

**Comment by vavane-ms** [comment]
@feiskyer, would you be the best person to contact for this issue? I can share subscription/cluster information and any other required information with you.

**Comment by feiskyer** [comment]
@vavane-ms is it dropped by ARM template? could you make an update to the service (or recreate the service) to mitigate the issue?

**Comment by vavane-ms** [comment]
No, simply redeploying the cluster using its ARM template doesn't affect the services. It's only if the DSC extension is run.

Yes, redeploying services fixes the issue, but given that cluster deployment and service deployment are uncoupled and that we redeploy clusters four times a day via our Azure Devops pipeline, this is not a feasible solution.

If you need me to collect information or try something else, please tell.

**Comment by vavane-ms** [comment]
Any news?

**Comment by feiskyer** [comment]
Another known issue is https://github.com/kubernetes/kubernetes/issues/89336, which has been fixed in v1.15.11. @vavane-ms Is it same with your issue?

**Comment by vavane-ms** [comment]
Thank you! Let me check if upgrade helps.

**Comment by vavane-ms** [comment]
Upgrade to 1.16 didn't help. Do you have other suggestions?

**Comment by feiskyer** [comment]
@vavane-ms could you describe your detailed reproduce steps? let's check what's wrong with repro.

**Comment by vavane-ms** [comment]
How detailed? We have a CI/CD pipeline for cluster deployment via ARM templates, it is run four times a day. It sets up the cluster, networking, and installs VMSS extensions on cluster pools (we have an additional Windows pool).

Independently, our partners deploy their LoadBalancer service to our cluster. They do it far less often. And we've noticed that after deployment (specifically, after restarting VMs which is part of VMSS extension installation) their LoadBalancer settings are not restored.

For which part do you need more details?

**Comment by jjindrich** [comment]
I can confirm that I have same issue. Running cluster 1.15.11. 
Steps to reproduce:
1. create new cluster and deploy nginx ingress (as internal loadbalancer) with some backend pod
2. check that internal loadbalancer is created with backend pool
3. enable monitoring extension on VMSS (e.g. from Security Center follow suggestion to enable monitoring on AKS VMSS)
4. check VMSS and start manual upgrade of instances
5. check internal loadbalancer - there will be no backend in backendpool

**Comment by vavane-ms** [comment]
@jjindrich, you may want to make sure that 1) you've specified Standard SKU for the load balancer in your ARM template or cluster creation script; 2) you've upgraded to 1.16.*. Unfortunately, due to our setup, I am not sure which of those helped us.
