### ISSUE TITLE
MAS is used as a default configuration for Azure CNI - in v0.50.0 - this leads allocation failures 

### ISSUE THREAD

**Issue by ninzavivek** [Azure/aks-engine#3245]
**Describe the bug**

MAS is used as a default configuration for Azure CNI - in v0.50.0 - this leads allocation failures , there PODs cannot be created

**Steps To Reproduce**
Create a cluster using v0.50.0 and trying creating PODSs using Azure CNI.

**Expected behavior**
It should not be the default configuration. 

**AKS Engine version**
 v0.50.0 

**Kubernetes version**

**Additional context**

**Comment by jackfrancis** [comment]
Fixed in https://github.com/Azure/aks-engine/pull/3228

**Comment by jackfrancis** [comment]
Will be released in v0.50.1
