### ISSUE TITLE
Do not use device name for etcd mount

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#3246]
**Describe the bug**

Originally reported by @Michael-Sinz. As described in https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/troubleshoot-device-names-problems, device names might change after you restart a Linux VM or reattach the data disks. 

> Normally, the mounts for the OS disk is /dev/sda1 - but this mount it done via a partition GUID and not a device name.
The "temp" disk shows up as /dev/sdb1 and is mounted on /mnt
The etcd disk is /dev/sdc1 and is mounted on /var/lib/etcddisk
However, on the failed boots, the OS disk is something other than /dev/sda1
In fact, the worst case is when the OS disk comes up as /dev/sdc1 - it is still the same disk (data wise) but the device name is not the same.
This lets the OS start but this breaks very quickly when we try to start kubernetes (well, actually, etcd - but that is part of kubernetes).
The reason is that the fstab for the etcd disk specifies mounting /dev/sdc1 to /var/lib/etcddisk (with auto and defaults,nofail)
Doing this ends up making an effective bind mount of the OS disk (/) into /var/lib/etcddisk
This causes etcd to fail as it does not have rights to write to /var/lib/etcddisk since that is the same as (/) and etcd does not have root rights.  
This prevents etcd from starting which then confuses kubelet and the master is out of commission.

We should change the [etcd mount script](https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/artifacts/mountetcd.sh) to use the UUID or filesystem labels to mount, not the device name `/dev/sda1` which is not guaranteed to stay the same.

See also: https://github.com/kubernetes-sigs/cluster-api/pull/3048/files#diff-f163e4a00e922ec2beac7fb211bba003R221

**Comment by CecileRobertMichon** [comment]
In addition, we should really consider doing this the right way in cloud init and finally addressing this TODO comment: https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/artifacts/mountetcd.sh#L3

**Comment by zhiweiv** [comment]
One of our AKS-E clusters runied recently, we couldn't access api server, kubectl shown error **ectd server timeout**, io of eted disk kept zero, I guess it was caused by this.

Can we fix it and release a new version asap.
