### ISSUE TITLE
Standard LB SKU configuration doesn't use explicit outbound rules

### ISSUE THREAD

**Issue by dmeytin** [Azure/aks-engine#3257]
**Describe the bug**
The LB with Standard SKU is created with flag "Create implicit outbound rules" set to true

As a result the LB doesn't use the explicit outbound rules  that are also configured but not used

It could be seen by checking outbound IPs on pods running on different nodes: some are going out using inbound IP and some using outbound IP, as opposite to rules definition

**Steps To Reproduce**

Deploy cluster with standard LB using aks-engine 0.49
**Expected behavior**
Create implicit outbound rules flag is set to false and explicit outbound rules been used
**AKS Engine version**
0.49
**Kubernetes version**
1.16.8
**Additional context**

**Comment by CecileRobertMichon** [comment]
@jackfrancis FYI this needs the same fix as https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/536/files#diff-b3b16dd828cf19adbdc5be2d4e28d2d5R120

**Comment by jackfrancis** [comment]
Do we want to match the value in `kubernetesConfig.cloudProviderDisableOutboundSNAT` ?
