### ISSUE TITLE
Trace aks-engine using OpenCensus

### ISSUE THREAD

**Issue by awesomenix** [Azure/aks-engine#326]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Request
---
Its hard to know exactly where is the time spent in aks engine, it would help upstream components to export traces to the exporter of their choice (example jaeger, zipkin etc)

https://opencensus.io/

**What version of aks-engine?**:
Any
---

**Kubernetes version**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by tariq1890** [comment]
Thanks @awesomenix for raising this :). So we already import opencensus transitively through go-autorest. Are you okay with us pinning to that version ?

**Comment by awesomenix** [comment]
Thanks @tariq1890 for diving into this. We are ok to pin to any specific version, if there is a requirement to downgrade upstream (libraries consuming aks engine, should be ok), worst case we can always ask go-autorest to upgrade as well :)
