### ISSUE TITLE
Enable nvidia for 18.04-LTS

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3274]
This solution has been prototyped as working for 18.04-LTS running on capz created cluster-api clusters:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/426#issuecomment-626966868

**Comment by jackfrancis** [comment]
cc @sozercan

**Comment by CecileRobertMichon** [comment]
@jackfrancis we could also look into leveraging https://github.com/NVIDIA/gpu-operator (it doesn't support containerd though https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/426#issuecomment-626953781)

**Comment by sozercan** [comment]
since aks relies on having drivers pre-installed on the nodes, aks gpu support will break unless docs can be updated and/or have gpu-operator installed as an aks add-on
