### ISSUE TITLE
Should not return "Connection to mcr.microsoft.com 443 port [tcp/https] succeeded!" when CSE failed to connect to API server

### ISSUE THREAD

**Issue by gtxistxgao** [Azure/aks-engine#3278]
**Describe the bug**

When CSE failed to connect to API server. But in the error message, we returned a **misleading message** (**Connection to mcr.microsoft.com 443 port [tcp/https] succeeded!"**). This only means we connect to mcr successfully. And it is not a stderr. 

> VM has reported a failure when processing extension 'vmssCSE'. Error message: "Enable failed: failed to execute command: command terminated with exit status=51
> [stdout]
> Sat Apr 25 11:14:50 UTC 2020,aks-nodepool1-xxxxx-vmss000000
> 
> [stderr]
> Connection to mcr.microsoft.com 443 port [tcp/https] succeeded!"
> 
> More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot 
> InternalDetail: [Details of predominant failure]
> VMExtensionProvisioningError: VM has reported a failure when processing extension 'vmssCSE'. Error message: "Enable failed: failed to execute command: command terminated with exit status=51
> [stdout]
> Sat Apr 25 11:14:50 UTC 2020,aks-nodepool1-xxxxxx-vmss000000
> 
> [stderr]Connection to mcr.microsoft.com 443 port [tcp/https] succeeded!"
> 
> More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot 

**Steps To Reproduce**

**Expected behavior**

We should return a correct error message. something like "**Failed to connect to API server**"

**AKS Engine version**

**Kubernetes version**

**Additional context**

https://github.com/Azure/aks-engine/blob/master/pkg/engine/cse.go
`"ERR_K8S_API_SERVER_CONN_FAIL": 51,`

https://github.com/Azure/aks-engine/blob/4163ea6be7d536b4b9b2606b2f30fc0fb6e79960/parts/k8s/cloud-init/artifacts/cse_main.sh#L277
```
VALIDATION_ERR=0

{{- if IsHostedMaster }}
RES=$(retrycmd 20 1 3 nslookup ${API_SERVER_NAME})
STS=$?
if [[ $STS != 0 ]]; then
    if [[ $RES == *"168.63.129.16"*  ]]; then
        VALIDATION_ERR={{GetCSEErrorCode "ERR_K8S_API_SERVER_AZURE_DNS_LOOKUP_FAIL"}}
    else
        VALIDATION_ERR={{GetCSEErrorCode "ERR_K8S_API_SERVER_DNS_LOOKUP_FAIL"}}
    fi
fi
retrycmd 50 1 3 nc -vz ${API_SERVER_NAME} 443 || VALIDATION_ERR={{GetCSEErrorCode "ERR_K8S_API_SERVER_CONN_FAIL"}}
{{end}}
```

**Comment by jackfrancis** [comment]
@xuto2 @bowang-666 @feiskyer do we want to make any changes to the CSE logic in response to this user feedback?

**Comment by xuto2** [comment]
this user is an AKS dev :)

The message is not printed out the cse_main.sh, but the nc tool when we use it to test connection to mcr.

Also in aks owned branch we update the message to be more accurate

echo "Custom script finished. API server connection check code:" $VALIDATION_ERR
echo $(date),$(hostname), endcustomscript>>/opt/m


https://github.com/Azure/aks-engine/blob/aks-release-v0.47.0-1/parts/k8s/cloud-init/artifacts/cse_main.sh#L266

I think we can close this issue.

**Comment by jackfrancis** [comment]
Thanks @xuto2!
