### ISSUE TITLE
CNI download URL is changed for Mooncake

### ISSUE THREAD

**Issue by AbelHu** [Azure/aks-engine#3279]
**Describe the bug**
This commit changed URL for Mooncake from `mirror.azk8s.cn` to `kubernetesartifacts.blob.core.chinacloudapi.cn`

https://github.com/Azure/aks-engine/commit/e93e0f32f9596e7deec0bae608078efa68828417#diff-f41c9478d3eabb30a6e28202cbfe7e18

Old URL works for v1.0.33
https://mirror.azk8s.cn/kubernetes/azure-container-networking/azure-vnet-cni-windows-amd64-v1.0.33.zip

Old URL works for v1.1.2
https://mirror.azk8s.cn/kubernetes/azure-container-networking/azure-vnet-cni-windows-amd64-v1.1.2.zip

New URL does not work for v1.0.33
https://kubernetesartifacts.blob.core.chinacloudapi.cn/azure-cni/v1.0.33/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.0.33.zip

New URL works for v1.1.2
https://kubernetesartifacts.blob.core.chinacloudapi.cn/azure-cni/v1.1.2/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.1.2.zip

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**
Should we change the URL from `mirror.azk8s.cn` to `kubernetesartifacts.blob.core.chinacloudapi.cn`?

**Comment by sozercan** [comment]
@AbelHu backfilled the older versions to `kubernetesartifacts.blob.core.chinacloudapi.cn`. for releases other than 1.1.1 and 1.1.2, there is no `singletenancy` in the name.

**Comment by AbelHu** [comment]
@sozercan Do we have decided to use `kubernetesartifacts.blob.core.chinacloudapi.cn` to replace `mirror.azk8s.cn`? `mirror.azk8s.cn` is the approved egress for china.

**Comment by mboersma** [comment]
cc: @jchauncey

**Comment by jchauncey** [comment]
I dont know who owns the mirror.azk8s.cn cdn endpoint nor do i know what storage account its pointing to. @AbelHu  if you know who I can get in contact with to figure out how to get artifacts into that SA I'd gladly use it.

**Comment by jackfrancis** [comment]
Is there any aks-engine work to do here?

**Comment by AbelHu** [comment]
@jackfrancis we need to keep to use `mirror.azk8s.cn` for Mooncake.

**Comment by jackfrancis** [comment]
Looks like that's already in place:

https://github.com/Azure/aks-engine/blob/master/pkg/api/azenvtypes.go#L284

So I don't think there's anything to do in aks-engine code, we just need to make sure the new CNI versions are being populated at the .cn mirror?

**Comment by AbelHu** [comment]
Outdated.
