### ISSUE TITLE
question about using sgx with k8s

### ISSUE THREAD

**Issue by justalittlenoob** [Azure/aks-engine#3282]
I am trying to deploy a sgx app with k8s. From there [https://github.com/Azure/aks-engine/blob/master/docs/topics/sgx.md#optional-using-oe-sgx-device-plugin-alpha](url), i know that the sgx driver is not installed in a container. I need to mount the driver into the container.   

My question is, do I need to install the sgx sdk and psw into the image/container? Or, the sdk/psw only need to be installed on the host machine (like the sgx driver) ? If so, how to mount the sdk/psw to into the container?  
  
Any advice would be appreciated.

**Comment by jackfrancis** [comment]
@salsal97 @vtikoo do we think that this question should be answered in the doc linked?

**Comment by vtikoo** [comment]
@justalittlenoob SGX SDK+ PSW dependencies are like any other library dependency for your app. There isn't any requirement to mount them, you can package them into your container.
 
@jackfrancis thats a good idea 👍

**Comment by justalittlenoob** [comment]
@vtikoo Thank your very much for your advice, i got your point. Just curious, why not install sgx sdk/psw only on the host, and mount it to the container when needed(like sgx driver)? I think it can reduce the size of the image/container. For example, a host has 10 containers, they all use the sgx sdk/psw on the host machine.   

Maybe my direction is wrong, please don't hesitate to correct me.

**Comment by vtikoo** [comment]
PSW is OS specific, and there are mutliple SDKs out there. And potentially different containers could be running different OSes and using different versions of the SDK. 
If you are creating your own images, you could try this. But for general aks-engine images, its hard to mandate a certain SDK + PSW setup due to issues mentioned above.

**Comment by justalittlenoob** [comment]
@vtikoo I really appreciate your detailed answer. Thank you:)
