### ISSUE TITLE
Documentation for Kubernetes on Cosmos (etcd) has a bad link

### ISSUE THREAD

**Issue by erick-thompson** [Azure/aks-engine#329]
The documentation/readme for Kubernetes on Cosmos (https://github.com/Azure/aks-engine/tree/master/examples/cosmos-etcd) contains a link for instructions (link is https://aka.ms/azurecosmosetcd). This takes me to the cosmos main page, as opposed to a page about Kubernetes/aks/etcd on Cosmos.

**Comment by CecileRobertMichon** [comment]
@khenidak do you have any guidance on what the link should be?
