### ISSUE TITLE
Allow GPU agent pools to be deployed without GPU software

### ISSUE THREAD

**Issue by JerryJoyce** [Azure/aks-engine#3307]
**Describe the request**
Currently when nodes with GPUs are provisioned, drivers and other GPU related components are installed.  This is a request to allow deployment without this provisioning.

**Explain why AKS Engine needs it**
Nvidia has a new GPU management operator.  One of the prerequisites for using it is that nodes must not be pre-configured with NVIDIA components.

[NVIDIA GPU operator](https://github.com/NVIDIA/gpu-operator)

**Describe the solution you'd like**

Some configuration option for the aks-engine cluster definition for agent pools that they are not to have GPU pre-provisioning.

**Comment by delulu** [comment]
It might be a better choice to install [NVIDIA GPU operator](https://github.com/NVIDIA/gpu-operator) as an addon in aks-engine, to replace the current nvidia-device-plugin addon and the gpu driver installation on N series VMs.
