### ISSUE TITLE
NodeAffinity pod scheduling errors

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3326]
Seeing these errors in E2E tests:

```
kube-system            pod/cluster-autoscaler-59464d8d66-8fv5w             1/1     Running        0          16m     10.239.255.239   k8s-master-40716864-0                  <none>           <none>
kube-system            pod/cluster-autoscaler-59464d8d66-b42w9             0/1     NodeAffinity   0          16m     <none>           k8s-master-40716864-2                  <none>           <none>
kube-system            pod/cluster-autoscaler-59464d8d66-l5j2h             0/1     NodeAffinity   0          16m     <none>           k8s-master-40716864-2                  <none>           <none>
kube-system            pod/cluster-autoscaler-59464d8d66-mr7xq             0/1     NodeAffinity   0          16m     <none>           k8s-master-40716864-2                  <none>           <none>
kube-system            pod/cluster-autoscaler-59464d8d66-p5k4b             0/1     NodeAffinity   0          16m     <none>           k8s-master-40716864-2                  <none>           <none>
kube-system            pod/cluster-autoscaler-59464d8d66-t45bh             0/1     NodeAffinity   0          16m     <none>           k8s-master-40716864-2                  <none>           <none>
kube-system            pod/cluster-autoscaler-59464d8d66-tgpm5             0/1     NodeAffinity   0          16m     <none>           k8s-master-40716864-2                  <none>           <none>
kube-system            pod/cluster-autoscaler-59464d8d66-wb8ll             0/1     NodeAffinity   0          16m     <none>           k8s-master-40716864-2                  <none>           <none>
kube-system            pod/cluster-autoscaler-59464d8d66-xgjjr             0/1     NodeAffinity   0          16m     <none>           k8s-master-40716864-2                  <none>           <none>
```

Why is a deployment with 1 replica rendering like the above?

Seeing this event in one of the pods:

```
Events:
  Type     Reason        Age        From                            Message
  ----     ------        ----       ----                            -------
  Normal   Scheduled     <unknown>  default-scheduler               Successfully assigned kube-system/cluster-autoscaler-59464d8d66-xgjjr to k8s-master-40716864-2
  Warning  NodeAffinity  51m        kubelet, k8s-master-40716864-2  Predicate NodeAffinity failed
```

Ref: https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=5085&view=logs&jobId=1814970b-a4b0-5ca5-aa6e-0747ee0a4d6f&j=1814970b-a4b0-5ca5-aa6e-0747ee0a4d6f&t=d135dd08-d552-5029-07fa-a5c3be6d0a06

**Comment by jackfrancis** [comment]
cc @aramase @feiskyer @ritazh 

I haven't observed this since we brought in 1.18.3 and 1.19.0-beta.0, so perhaps it's the result of a recent introduction upstream?

Couldn't find any k/k issues that seemed to match the above symptoms...

**Comment by jackfrancis** [comment]
Another one: https://msazure.visualstudio.com/One/_build/results?buildId=31458078&view=logs&j=1814970b-a4b0-5ca5-aa6e-0747ee0a4d6f&t=d135dd08-d552-5029-07fa-a5c3be6d0a06

**Comment by jackfrancis** [comment]
And another one: https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=5120&view=logs&jobId=71ef0db1-6916-5cda-25f3-19ec46a4388a&j=71ef0db1-6916-5cda-25f3-19ec46a4388a&t=b9bc4c27-e3cd-5a4e-f6a3-ffebd8a8e7b3

**Comment by jackfrancis** [comment]
@tamilmani1989 FYI: we suspect that these E2E errors are caused by a delay in assigning an IP address to the pod. These flakes come from Azure CNI-enabled clusters. Is there something in the 1.1.2 release of Azure CNI that would introduce inconsistencies in returning a pod IP address?

**Comment by tamilmani1989** [comment]
@jackfrancis We didnt change anything specific to IP address assignment in CNI for long. can you send me azure-vnet logs? let me check if there any delay in IP assignment.

**Comment by jackfrancis** [comment]
It looks like the kubelet tried to schedule a pod before the Azure CNI IPAM module was ready.

Here's the pod scheduling failure event:

```
May 27 19:47:13 k8s-master-38868224-0 kubelet[5978]: I0527 19:47:13.338969    5978 predicate.go:138] Predicate failed on Pod: cluster-autoscaler-86bd5997c7-bbpkl_kube-system(f26302e2-107d-4f6f-81f3-c8e518d59a5e), for reason: Predicate NodeAffinity failed
```

Here is the IPAM logs, suggesting that the IPAM runtime came online 4 seconds later:

```
$ sudo cat /var/log/azure-vnet-ipam.log
2020/05/27 19:47:17 [10045] [cni-ipam] Plugin azure-vnet-ipam version v1.1.2.
```

We've never observed these flakes before, is it possible the new release of Azure CNI takes longer to load?

**Comment by jackfrancis** [comment]
Kubelet says it loaded the CNI plugin over a minute before the IPAM logs show as starting:

```
May 27 19:46:11 k8s-master-38868224-0 kubelet[5978]: I0527 19:46:11.772871    5978 plugins.go:166] Loaded network plugin "cni"
```

**Comment by tamilmani1989** [comment]
That does't matter. Need to know when Kubelet invoked CNI with ADD call for that pod.

**Comment by jackfrancis** [comment]
What doesn't matter? The predicate.go log entry in kubelet above is roughly when that CNI ADD call would have been made. The IPAM module was not running yet.

**Comment by tamilmani1989** [comment]
If you have both kubelet and CNI logs that would be helpful. can find when CNI was invoked by kubelet and check if there any delay internally in CNI after its invoked. (azure-vnet) CNI is the one which invokes IPAM(azure-vnet-ipam).

When Kubelet invokes cni ADD, I have seen kubelet log saying something like this:

`kubelet.go:1901] SyncLoop (ADD, "api"): "container3-96cc4fb4c-l5658_default(007f0ec4-b5aa-4ff4-b8c8-53e239166516)"`
