### ISSUE TITLE
How to Rotate the KubectlClientServiceprincipal in cluster if expired

### ISSUE THREAD

**Issue by tejeshwari** [Azure/aks-engine#3346]
Hello

We have a KubectlClientServicePrincipal  that expires soon and it is being used in kubernetes cluster. Everything will be fine If we rebuild the cluster. But how do we rotate the Client ID on existing cluster without rebuilding. We are aware of  updating the API server ID in etc/kubernetes/Azure.json. But, could not see the KubectlClientServicePrincipal ID in Azure.json.

{
    "cloud":"ABCABCABC",
    "tenantId": "yyyyyyyyyyyyyyyyyy",
    "subscriptionId": "YYYYYYYYYYYYYYYYYY",
    "aadClientId": "YYYYYYYYYYYYYYYYYYYYYYYYYY",
    "aadClientSecret": "YYYYYYYYYYYYYYYYYYYYYYYYY",
    "resourceGroup": "YYYYYYYYYYYYYYYYYYYYYYYY",
    "location": "YYYYYYYYYYYYYY",
    "vmType": "standard",
    "subnetName": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "securityGroupName": "YYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "vnetName": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "vnetResourceGroup": "YYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "routeTableName": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "primaryAvailabilitySetName": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "primaryScaleSetName": "",
    "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffExponent": 1.5,
    "cloudProviderBackoffDuration": 5,
    "cloudProviderBackoffJitter": 1,
    "cloudProviderRatelimit": true,
    "cloudProviderRateLimitQPS": 10,
    "cloudProviderRateLimitBucket": 100,
    "useManagedIdentityExtension": false,
    "userAssignedIdentityID": "",
    "useInstanceMetadata": true,
    "loadBalancerSku": "Basic",
    "excludeMasterFromStandardLB": false,
    "providerVaultName": "",
    "maximumLoadBalancerRuleCount": 250,
    "providerKeyName": "YYY",
    "providerKeyVersion": ""
}

**Comment by m3ssana** [comment]
Hello. I am working with @tejeshwari on this project. What we are looking for is where we can replace what we have set in apimodel.json as "clientAppID" within an existing cluster. It is not appearing within the azure.json where we know we can replace the "serverAppID" value

**Comment by jackfrancis** [comment]
If you mint new service principals with the equivalent privileges in the sub + resource group where the existing cluster resides, you can simply replace the aadClientId and aadClientSecret values in `/etc/kubernetes/azure.json` with the id and password, respectively, of the new service principal.

However, future scale operations won't respect those manual changes. In order to do that, you'll have to update the values in the apimodel.json and scale or upgrade the cluster.

What's the shape of your cluster? masters? agent pools?

cc @deaborch
