### ISSUE TITLE
Managed Service Identity 429's from ARM

### ISSUE THREAD

**Issue by johnlento** [Azure/aks-engine#335]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
28.1
---

**Kubernetes version**:
1.13.1

**What happened**:
Using an MSI to communicate with an Azure load balancer results in many HTTP 429's to ARM and the MSI doesn't seem to backoff making at least a request a minute.

**What you expected to happen**:
The MSI to make a request to the load balancer and have it succeed.

**How to reproduce it** (as minimally and precisely as possible):
Use lots of VMSS with 400-1000 nodes each then deploy services requesting an IP address.

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@ritazh any ideas here?

@johnlento can you please share your cluster configuration for repro?

**Comment by johnlento** [comment]
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.13.1",
      "kubernetesConfig": {
        "loadBalancerSku": "Standard",
        "excludeMasterFromStandardLB": true,
        "networkPlugin": "azure",
        "useManagedIdentity": true,
        "enableEncryptionWithExternalKms": true,
        "enableDataEncryptionAtRest": true,
        "enableRbac": true,
        "addons": [
          {
            "name": "kubernetes-dashboard",
            "enabled": true
          },
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "config": {
              "minNodes": "1",
              "maxNodes": "1000"
            }
          }
        ]
      }
    },
    "masterProfile": {
      "count": 5,
      "dnsPrefix": "cluster",
      "vmSize": "Standard_D8s_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "toolpen",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "acceleratedNetworkingEnabled": true,
        "singlePlacementGroup": false,
        "customNodeLabels": {
          "app": "tool",
          "org": "pen",
          "use": "process",
          "priority": "dedicated"
        }
      },
      {
        "name": "toolpenlow",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "acceleratedNetworkingEnabled": true,
        "singlePlacementGroup": false,
        "scaleSetPriority": "Low",
        "customNodeLabels": {
          "app": "tool",
          "org": "pen",
          "use": "process",
          "priority": "low"
        }
      },
      {
        "name": "toolteam",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "acceleratedNetworkingEnabled": true,
        "singlePlacementGroup": false,
        "customNodeLabels": {
          "app": "tool",
          "org": "team",
          "use": "team_scan",
          "priority": "dedicated"
        }
      },
      {
        "name": "toolteamlow",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "acceleratedNetworkingEnabled": true,
        "singlePlacementGroup": false,
        "scaleSetPriority": "Low",
        "customNodeLabels": {
          "app": "tool",
          "org": "team",
          "use": "team_scan",
          "priority": "low"
        }
      },
      {
        "name": "toolnow",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "acceleratedNetworkingEnabled": true,
        "singlePlacementGroup": false,
        "customNodeLabels": {
          "app": "tool",
          "org": "team",
          "use": "ondemand",
          "priority": "dedicated"
        }
      },
      {
        "name": "toolnowlow",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "acceleratedNetworkingEnabled": true,
        "singlePlacementGroup": false,
        "scaleSetPriority": "Low",
        "customNodeLabels": {
          "app": "tool",
          "org": "team",
          "use": "ondemand",
          "priority": "low"
        }
      },
      {
        "name": "auto",
        "count": 1,
        "vmSize": "Standard_D8s_v3",
        "availabilityProfile": "VirtualMachineScaleSets",
        "acceleratedNetworkingEnabled": true,
        "customNodeLabels": {
          "app": "auto",
          "org": "team",
          "priority": "dedicated"
        }
      },
      {
        "name": "teamcon",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "acceleratedNetworkingEnabled": true,
        "customNodeLabels": {
          "app": "teamis",
          "org": "team",
          "priority": "dedicated"
        }
      }
    ],
    "linuxProfile": {
      "adminUsername": "georgewashington",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "aadProfile": {
      "clientAppID": "",
      "serverAppID": "",
      "adminGroupID": "",
      "tenantID": ""
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": "",
      "objectId": ""
    }
  }
}

**Comment by johnlento** [comment]
@CecileRobertMichon It didn't support JSON as a file type for upload so I put plain text in.
