### ISSUE TITLE
NIC in failed state

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#336]
Observed in our Azure CNI-enabled soak clusters on the following Kubernetes versions:

1.11.6
1.10.12

Relevant controller-manager log entry:

```
E0118 19:26:03.235370       1 azure_backoff.go:364] processHTTPRetryResponse: backoff failure, will retry, HTTP response=400, err=network.LoadBalancersClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="ReferencedResourceNotProvisioned" Message="Cannot proceed with operation because resource /subscriptions/05a2ff75-a688-47ed-ab90-6e84160d9dbd/resourceGroups/acse-test-soak-k8s-1dot11/providers/Microsoft.Network/networkInterfaces/k8s-agentmd-28066031-nic-1/ipConfigurations/ipconfig1 used by resource /subscriptions/05a2ff75-a688-47ed-ab90-6e84160d9dbd/resourceGroups/acse-test-soak-k8s-1dot11/providers/Microsoft.Network/loadBalancers/acse-test-soak-k8s-1dot11-internal is not in Succeeded state. Resource is in Failed state and the last operation that updated/is updating the resource is PutNicOperation." Details=[]
```

**Comment by jackfrancis** [comment]
@feiskyer @andyzhangx Are we tracking any current issues w/ either of the above k8s versions inducing NIC failures?

**Comment by feiskyer** [comment]
Partially, e.g. [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_standard.go#L645). There may be more resources in failure state, but I don't think we're tracking all.

**Comment by jackfrancis** [comment]
Thanks @feiskyer. I haven't been able to repro, so most likely this was an operational flake in the environment. What is the best remediation when a NIC goes into a failed state like this? Delete the NIC from the CLI or portal and then rely upon <something> (cloudprovider?) to recreate it? Or should we redeploy the ARM template in the resource group?

**Comment by feiskyer** [comment]
usually, run `az network nic update` could bring the NIC back.

**Comment by jackfrancis** [comment]
Closing for now, will use the `az network nic update` guidance to help folks in the future. Thanks @feiskyer!
