### ISSUE TITLE
Update pause to 1.3.1

### ISSUE THREAD

**Issue by ritazh** [Azure/aks-engine#3368]
**Describe the request**
Currently using `mcr.microsoft.com/k8s/core/pause:1.2.0`. We should move to a more secure `1.3.1` hosted at `mcr.microsoft.com/oss/kubernetes/pause:1.3.1`.

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ritazh** [comment]
cc @jchauncey

**Comment by jchauncey** [comment]
It was the first place pause landed and they switched because of windows support.

**Comment by ritazh** [comment]
Can we switch to `mcr.microsoft.com/oss/kubernetes/pause` for `1.3.1` now?

**Comment by jchauncey** [comment]
Yes we should

**Comment by jackfrancis** [comment]
FYI Windows is already using pause 1.3.1 from the oss/kubernetes origin

cc @marosset
