### ISSUE TITLE
Fail to enable custom extension after v0.48.0.

### ISSUE THREAD

**Issue by nilo19** [Azure/aks-engine#3383]
**Describe the bug**
If custom extension is enabled, the deployment would fail with the following error:
```
cli.azure.cli.core.util : Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template variable 'agentPublicIPAddressName' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'.
Additional Information:
        Type: TemplateViolation
        Info: {
            "lineNumber": 1,
            "linePosition": 47234,
            "path": "properties.template.resources[0].name"
        }
Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template variable 'agentPublicIPAddressName' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'.
Additional Information:
        Type: TemplateViolation
        Info: {
            "lineNumber": 1,
            "linePosition": 47234,
            "path": "properties.template.resources[0].name"
        }
```
It's good in v0.48.0 but would fail after v0.49.0.

**Steps To Reproduce**

Custom extension template: https://github.com/kubernetes-sigs/cloud-provider-azure/raw/master/tests/kubemark/extensions/config-kubemark-master/v1/template.json
API model: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/kubemark/templates/kubemark-cluster.json

**Expected behavior**
The deployment should succeed.

**AKS Engine version**
v0.49.0 or later.

**Kubernetes version**
1.18

**Additional context**

**Comment by jackfrancis** [comment]
Hi @nilo19: you don't have any agentPoolProfiles defined in your api models. Is that intentional?

**Comment by nilo19** [comment]
> Hi @nilo19: you don't have any agentPoolProfiles defined in your api models. Is that intentional?

Yes it is.

**Comment by jackfrancis** [comment]
I don't think masters only + custom extensions are a supported scenario.

**Comment by nilo19** [comment]
@jackfrancis I add a node in the api model 
```json
        "agentPoolProfiles": [
            {
                "name": "agentpool1",
                "count": 1,
                "vmSize": "Standard_F1s",
                "availabilityProfile": "VirtualMachineScaleSets",
                "storageProfile": "ManagedDisks"
            }
        ],
```
and the issue remains.
