### ISSUE TITLE
Metrics server fails to collect metrics for Windows pods/nodes

### ISSUE THREAD

**Issue by AlexEyler** [Azure/aks-engine#3388]
**Repro steps**:
1. Create cluster from AKS-Engine with some Windows nodes
   * Windows OS: WindowsServer_2019
   * Windows OS SKU: 2019-Datacenter-with-Containers
   * Windows Image Publisher: MicrosoftWindowsServer
   * Windows Image Offer: WindowsServer
2. Run `kubectl top node <node>`:
Expected: I'd expect to see some stats for the Windows agents
Actual: 
> Error from server (NotFound): nodemetrics.metrics.k8s.io "7813k8s004" not found

The root cause looks like this error message from the metrics-server (the same logs show up in kubelet.err.log on the node):
`hcsshim::OpenComputeSystem 1e6d3e48fed736289f9a87703e00910c785ed6ecc3c04af00c9e7eb6aef7d972: A virtual machine or container with the specified identifier does not exist.`

**Anything else we need to know?**:
Metrics for linux pods/nodes work fine

**Environment**:
- Kubernetes distribution (GKE, EKS, Kubeadm, the hard way, etc.): aks-engine v0.50.0
- Container Network Setup (flannel, calico, etc.): Azure CNI
- Kubernetes version (use `kubectl version`): 1.18.2 (both client/server)
- Metrics Server manifest:
```
Name:                 metrics-server-7f6c5b76b9-ghx5k
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 k8s-master-78132855-4/10.255.255.9
Start Time:           Mon, 11 May 2020 13:56:06 -0700
Labels:               k8s-app=metrics-server
                      pod-template-hash=7f6c5b76b9
Annotations:          kubernetes.io/psp: privileged
Status:               Running
IP:                   10.240.1.41
IPs:
  IP:           10.240.1.41
Controlled By:  ReplicaSet/metrics-server-7f6c5b76b9
Containers:
  metrics-server:
    Container ID:  docker://4fc7e8c86c8c781eab3d95d70561156c3d4a05915fe755075c25954a0c69306d
    Image:         mcr.microsoft.com/oss/kubernetes/metrics-server:v0.3.5
    Image ID:      docker-pullable://k8s.gcr.io/metrics-server-amd64@sha256:edab4c64c4e29f665adaf6c0e11fe00ac9d71bb1fdce61bfa3d9e2a664331f79
    Port:          <none>
    Host Port:     <none>
    Command:
      /metrics-server
      --kubelet-insecure-tls
    State:          Running
      Started:      Mon, 11 May 2020 13:56:10 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-pvjnb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  metrics-server-token-pvjnb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-pvjnb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```
- Kubelet config:
- Metrics Server logs:
`E0521 05:12:14.428027       1 manager.go:111] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:7813k8s004: unable to fetch metrics from Kubelet 7813k8s004 (7813k8s004): request failed - "500 Internal Server Error", response: "Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem adc0bbe1bc6fb9d6535a096bdab23b2cf796d45c62633432d09e9dfaad43f515: A virtual machine or container with the specified identifier does not exist.", unable to fully scrape metrics from source kubelet_summary:7813k8s003: unable to fetch metrics from Kubelet 7813k8s003 (7813k8s003): request failed - "500 Internal Server Error", response: "Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem ee1531ecad2e41a2c1f17299d622e6c81ddd6fdc7894c905c63a7567b377f897: A virtual machine or container with the specified identifier does not exist.", unable to fully scrape metrics from source kubelet_summary:7813k8s002: unable to fetch metrics from Kubelet 7813k8s002 (7813k8s002): request failed - "500 Internal Server Error", response: "Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 9ffc63a41104fa934d0706718f86f0d0b2329d988523b55136afe4dfb3406c7f: A virtual machine or container with the specified identifier does not exist.", unable to fully scrape metrics from source kubelet_summary:7813k8s001: unable to fetch metrics from Kubelet 7813k8s001 (7813k8s001): request failed - "500 Internal Server Error", response: "Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 1e6d3e48fed736289f9a87703e00910c785ed6ecc3c04af00c9e7eb6aef7d972: A virtual machine or container with the specified identifier does not exist."]`

Copied from metrics-server issue: https://github.com/kubernetes-sigs/metrics-server/issues/539

**Comment by AlexEyler** [comment]
Updated with repro steps. Not sure if this is an aks-engine issue, a k8s issue, a metrics-server issue, or a Windows issue :(

**Comment by jackfrancis** [comment]
@marosset @jsturtevant is this a known issue or is this a new one?

**Comment by marosset** [comment]
@AlexEyler can you check to see what status the pods/containers are in when you hit this?
I believe there was an upstream issue which has been recently fix in 1.19 and backported to 1.18 where if there where pods in an init state you should see this issue on Windows nodes until they start running.
I'll try and find the issue(s)

**Comment by AlexEyler** [comment]
All pods are in the "Running" status and I can still reproduce:
```
❯ kubectl get pod
NAME                                  READY   STATUS    RESTARTS   AGE
cu0-bot-authoring-d568fd6d9-ld28l     1/1     Running   231        6d
cu0-bot-authoring-d568fd6d9-v2p2b     1/1     Running   233        6d
cu0-bot-authoring-d568fd6d9-z7hxq     1/1     Running   233        6d
cu0-bot-engine-5867cfd78f-4lplb       1/1     Running   1925       14d
cu0-bot-engine-5867cfd78f-8v2hg       1/1     Running   1762       14d
cu0-bot-engine-5867cfd78f-pp9w6       1/1     Running   1932       14d
cu0-bot-engine-5867cfd78f-xnxjw       1/1     Running   1930       14d
cu0-bot-management-6b59f8f77f-cgpcz   1/1     Running   233        6d
cu0-bot-management-6b59f8f77f-npp8g   1/1     Running   233        6d
cu0-bot-management-6b59f8f77f-x4bk5   1/1     Running   231        6d
cu0-echo-9fd57f558-59mgl              1/1     Running   2          4d2h
cu0-echo-9fd57f558-kqzzs              1/1     Running   2          4d2h
cu0-gateway-594fb4b75c-2l2ln          1/1     Running   2          4d5h
cu0-gateway-594fb4b75c-6588w          1/1     Running   2          4d5h
cu0-gateway-594fb4b75c-cpfhd          1/1     Running   2          4d5h
scu0-metrics-7c9c4ff7f6-5r2gm         1/1     Running   1670       14d
scu0-metrics-7c9c4ff7f6-82n74         1/1     Running   1674       14d
scu0-metrics-7c9c4ff7f6-cv8fz         1/1     Running   1673       14d
scu0-metrics-7c9c4ff7f6-zchcv         1/1     Running   1675       14d

❯ kubectl top pod cu0-bot-authoring-d568fd6d9-ld28l
Error from server (NotFound): podmetrics.metrics.k8s.io "default/cu0-bot-authoring-d568fd6d9-ld28l" not found
```

**Comment by AlexEyler** [comment]
There's an error on the VM in the kubelet.err.log as well that looks related:
```
E0602 06:25:26.130158    7276 remote_runtime.go:495] ListContainerStats with filter &ContainerStatsFilter{Id:,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 3aef65ec92032a4d0b475b5720a20b8418d5d8a08e1ae55a994b785d5a0bd7cb: A virtual machine or container with the specified identifier does not exist.
```

**Comment by porrascarlos802018** [comment]
https://github.com/Azure/AKS/releases/tag/2020-06-15
