### ISSUE TITLE
`aks-engine orchestrators` shows DCOS/swarm orchestrators as available options

### ISSUE THREAD

**Issue by bacongobbler** [Azure/aks-engine#339]
If I enter `aks-engine orchestrators`, I get Kubernetes, DCOS and Swarm as available orchestrators.

Given that the only orchestrator AKS Engine intends to support in the future is Kubernetes, `aks-engine orchestrators` is probably due for a rewrite. Given that my assumption is this command was used to inform what versions of Kubernetes are supported (as well as whether they have Windows support), should it be re-written to `aks-engine available-versions` or something similar?

Additional side note: I haven't been able to find any information on `aks-engine orchestrators` in the docs (other than an excerpt from [one of the examples outside the docs](https://github.com/Azure/aks-engine/blob/7966f8f452c621444af90f69e6bd7f43a5c1682a/examples/k8s-upgrade/README.md)), so as a newcomer I'm not sure how I'm supposed to supply that information back to the API model to get the version I choose. I'd love to see a topic guide on using `aks-engine orchestrators` to select a particular Kubernetes version for my deployment... Perhaps as a new topic guide on how to use `aks-engine upgrade`?

**Comment by CecileRobertMichon** [comment]
I think the little docs with have on the topic are in the upgrade readme https://github.com/Azure/aks-engine/blob/master/examples/k8s-upgrade/README.md#L20 but totally agree these could be more comprehensive. Also agree that `orchestrators` isn't the right verb anymore. Slight preference for `get-versions` over `available-versions` since it's the same verb aks already uses.

**Comment by jackfrancis** [comment]
I vote for replacing `aks-engine orchestrators --orchestrator Kubernetes` with `aks-engine --k8s-versions`.

I also vote that we add an alias `aks-engine upgrade --k8s-versions` for folks who are upgrading and who do something like `aks-engine upgrade --help` as a discovery path towards finding out "how do I figure out which versions of Kubernetes I can upgrade to?"

**Comment by mboersma** [comment]
I like `aks-engine get-versions` because it's parallel to `az aks get-versions`.
