### ISSUE TITLE
Multiple nginx ingress containers add large, inconsistent amounts of latency

### ISSUE THREAD

**Issue by gaieges** [Azure/aks-engine#3392]
We bumped into an odd issue the other day with a few different versions of k8s (1.16 and 1.17), with a new aks-engine library (versions below).  This previously did not happen when we were using earlier versions of aks-engine (`v0.44.2`)

We use the helm version of the nginx controller via the below install method:

```
helm upgrade --install nginx-ingress stable/nginx-ingress \
    --version 1.33.5 \ # also broken in 1.39.0
    --set rbac.create=true \
    --set controller.replicaCount=3 \
    --namespace kube-system \
    --wait \
    --timeout 6000
```

When we enable this configuration, setting to 3 replicas as defined above causes very inconsistent amounts of latency to the most basic of ingress configurations (ie the default 404 fallback ingress).  Hitting the IP defined by the below command with a simple `GET /` request will take up to 10s sometimes, will sometimes take 1s, and often somewhere in between.  

The trick to solving this was to reduce the replica count to 1 rather than > 1. 

This however is a problem, as now we have a central point of failure and have no way to add redundancy to this if a node dies (and we use spot nodes which often get pre-empted and take down service for a few seconds)

### Getting IP of the ingress
`kubectl get service nginx-ingress-controller -n kube-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`

## Versions
- k8s: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-11-13T23:50:10Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T23:15:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- aks-engine: `v0.51.0`
- helm: `v2.16.1`

cc: @durch @posix4e

**Comment by posix4e** [comment]
It would also be nice to know what the load balancer configuration should look like

**Comment by jackfrancis** [comment]
Hi folks, what's the cluster configuration (api model) you're using to create your cluster(s)? (reminder to scrub any secrets)

**Comment by gaieges** [comment]
This is the generated `apimodel.json` 
[apimodel.json.zip](https://github.com/Azure/aks-engine/files/4726248/apimodel.json.zip)

**Comment by jackfrancis** [comment]
I can't repro yet, see my PR here for a programmatic attempt to do so:

https://github.com/Azure/aks-engine/pull/3402

**Comment by mtgerb** [comment]
I have the same issue with kubernetes 1.16.10 (aks-engine v0.51.0, ubuntu 18.04) and traefik (https://github.com/containous/traefik/) as an ingress controller and a basic loadbalancer. Decreasing the replica count to 1 solved the problem. With aks-engine v0.48.0,  ubuntu 16.04 and kubernetes 1.15.7 the problem does not occur.

**Comment by posix4e** [comment]
Sounds like a 1.16 bug.
