### ISSUE TITLE
Jumpbox support for non-private clusters

### ISSUE THREAD

**Issue by AlexEyler** [Azure/aks-engine#3414]
**Describe the request**
Today, support exists for private clusters by adding a jumpboxProfile within the private cluster profile. For [example](https://github.com/Azure/aks-engine/blob/813c78e87552bf3984515f361a1299723a1c7b8c/examples/kubernetes-config/kubernetes-private-cluster-single-master.json):
```json
"kubernetesConfig": {
    "privateCluster": {
        "enabled": true,
        "jumpboxProfile": {
            "name": "my-jb",
            "vmSize": "Standard_D2_v3",
            "osDiskSizeGB": 30,
            "username": "azureuser",
            "publicKey": ""
        }
    }
}
```

I'd like to request that this support is added to non-private clusters as well.

**Explain why AKS Engine needs it**
Right now, the only way to get to RDP into a Windows node is to manually create a jumpbox in the VNET ([official docs](https://docs.microsoft.com/en-us/azure/aks/rdp)). That's doable but we'd like to be able to have the machines pre-provisioned so we can easily jump onto a Windows node in the cluster for bug investigations/etc.

**Describe the solution you'd like**
Preferably, just move the `jumpboxProfile` outside of `privateCluster`:
```json
"kubernetesConfig": {
    "jumpboxProfile": {
        "name": "my-jb",
        "vmSize": "Standard_D2_v3",
        "osDiskSizeGB": 30,
        "username": "azureuser",
        "publicKey": ""
    }
}
```

**Describe alternatives you've considered**
After we provision the cluster, we can run a script to provision the jumpbox, which isn't difficult. But it would be nice if it were built-in to the product.

**Additional context**

**Comment by jackfrancis** [comment]
cc @rbitia
