### ISSUE TITLE
AKS-Engine won't respect: CustomHyperkubeImage key

### ISSUE THREAD

**Issue by adelina-t** [Azure/aks-engine#342]
Kind: Bug

Version: 0.29.1

Deployed cluster with a basic template containing: 
Properties.OrchestratorProfile.KubernetesConfig.CustomHyperkubeImage =e2eteam/hyperkube-amd64:win-e2e-1087703319876472832 

Expectation is that the kubelet should be extracted from the image.

However:

```
kubectl get nodes

NAME                    STATUS   ROLES    AGE     VERSION
k8s-master-31858204-0   Ready    master   3h22m   v1.13.2
```

Yet we can see that the other pods in kube-system use the right image:

```
kubectl get pods --output custom-columns=NAME:.spec.containers[*].name,IMAGE:.spec.containers[*].image -n kube-system

NAME                         IMAGE
azure-cnms                   containernetworking/networkmonitor:v0.0.4
azure-ip-masq-agent          k8s.gcr.io/ip-masq-agent-amd64:v2.0.0
blobfuse-flexvol-installer   mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume:1.0.7
coredns                      k8s.gcr.io/coredns:1.2.6
keyvault-flexvolume          mcr.microsoft.com/k8s/flexvolume/keyvault-flexvolume:v0.0.5
kube-addon-manager           k8s.gcr.io/kube-addon-manager-amd64:v8.9
kube-apiserver               e2eteam/hyperkube-amd64:win-e2e-1087703319876472832
kube-controller-manager      e2eteam/hyperkube-amd64:win-e2e-1087703319876472832
kube-proxy                   e2eteam/hyperkube-amd64:win-e2e-1087703319876472832
kube-scheduler               e2eteam/hyperkube-amd64:win-e2e-1087703319876472832
kubernetes-dashboard         k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
metrics-server               k8s.gcr.io/metrics-server-amd64:v0.2.1
tiller                       gcr.io/kubernetes-helm/tiller:v2.11.0
```

**Comment by adelina-t** [comment]
@PatrickLang

**Comment by jackfrancis** [comment]
Hi @adelina-t, you should be able to debug this in the provision script logs at `/var/log/azure/cluster-provision.log`.

Look for the `installKubeletAndKubectl` keyword in the logs. That's the function that is called to extract kubelet from the hyperkube image.

Here's the code:

https://github.com/Azure/aks-engine/blob/b35549b08a41495c194c7a47bde2205c61f1921a/parts/k8s/kubernetesinstalls.sh#L221

**Comment by ritazh** [comment]
Hey @adelina-t I'm using head from master 521478f to deploy a cluster with 2 windows nodes. I noticed it took some time for the windows nodes to join, but eventually the cluster came up as expected and using the right custom image I provided.

```
kubectl get no
NAME                    STATUS    ROLES     AGE       VERSION
2349k8s000              Ready     agent     33m       v1.11.6
2349k8s001              Ready     agent     33m       v1.11.6
k8s-master-23499679-0   Ready     master    40m       v1.11.6

kubectl get pods --output custom-columns=NAME:.spec.containers[*].name,IMAGE:.spec.containers[*].image -n kube-system
NAME                      IMAGE
kube-addon-manager        k8s.gcr.io/kube-addon-manager-amd64:v8.6
kube-apiserver            gcr.io/kubernetes-211319/hyperkube-amd64:win-e2e-4
kube-controller-manager   gcr.io/kubernetes-211319/hyperkube-amd64:win-e2e-4
kube-scheduler            gcr.io/kubernetes-211319/hyperkube-amd64:win-e2e-4
```

**Comment by adelina-t** [comment]
@jackfrancis So what's happening is that installKubeletAndKubectl() (https://github.com/Azure/aks-engine/blob/78832ef336886d763b2c5fe18f0142ed891df0b2/parts/k8s/kubernetesinstalls.sh#L251 ) checks if the kubelet is already present in /usr/local/bin/ for the kubernetes version specified and uses that. Since by default it is using the aks-ubuntu-1604 image, that would already have kubelet in there. And since we can't specify (?) any other version of k8s > 1.13.2  ( https://github.com/Azure/aks-engine/blob/cd8bdf2332c40f911a4333d91748b3e1e175f5d6/pkg/api/common/versions.go#L16 ) I guess we can't have custom kubelet with the aks default image.

Now, setting master and agent distro to "ubuntu" ( or anything else I suppose ) will work, as the image obviously doesn't contain kubelet already. I guess this should also be documented here:

https://github.com/Azure/aks-engine/blob/master/docs/topics/kubernetes-developers.md

**Comment by PatrickLang** [comment]
@jackfrancis what do you think? We could use the Ubuntu bare images. I'm not sure the VHD gains us much since we're pulling hyperkube and kubelet for these test passes.

**Comment by jackfrancis** [comment]
@adelina-t That makes sense. @CecileRobertMichon can also verify.

So yeah, I think the guidance given the current state of the code would be to use a `"distro": "ubuntu"` setting in the `masterProfile` configuration object, and in all members of the `agentPoolProfiles` configuration array.

Using the `ubuntu` distro delivers a vanilla 16.04 LTS OS image (@ latest), which will download/install all prereqs at provisioning time. Can you try that for now as a possible solution to unblock yourself in the near term?

**Comment by CecileRobertMichon** [comment]
Agreed. In order to bypass the pre-pulled hyperkube image you'll need to use the "ubuntu" distro in all agent/master profiles as @jackfrancis explained above.

**Comment by CecileRobertMichon** [comment]
We should add that distro guidance to https://github.com/Azure/aks-engine/blob/master/docs/topics/kubernetes-developers.md

**Comment by ritazh** [comment]
@adelina-t confirming this works now as part of kubetest https://github.com/ritazh/test-infra/commit/48326353dce93d5c1925f7fbb3810e63219062c5

on master and agent nodes, I now see consistent version as the kubelet in my hyperkube image
```
/usr/local/bin/kubelet --version
Kubernetes v1.12.0-alpha.1.5549+0c81d1a1b59ecc-dirty
```
