### ISSUE TITLE
[FEATURE] mTLS setup of oms-agent

### ISSUE THREAD

**Issue by MarianZoll** [Azure/aks-engine#3440]
**Describe the request**

We use AKS with Istio and enabled mTLS for all cluster-internal communication. Instead of running our own Prometheus (Istio addon which will be deprecated with v.1.8.0), we want to use the Azure native ALA integration with the `oms-agent`. 

Unfortunately, the Istio sidecar containers cannot spin up sidecars in the `kube-*` namespaces as this would intersect too much of the communication to the k8s control plane. 

Therefore, we suggest to isolate the logging into another k8s namespace - mainly changing the yamls on `oms-agent` site. 

**Explain why AKS Engine needs it**

Not sure if this is the right repo, but after searching for a hour I did not find a better one. The feature would allow better isolation of `kube-system` features and the logging and monitoring stack of Azure. It would further open the Azure logging and monitoring to other OSS tools and frameworks.

**Describe the solution you'd like**

Create a new namespace in managed AKS (e.g. `azure-ala-integration`) and deploy the `oms-agent` accordingly. In an ideal world, we might want the user to define the namespace.

**Describe alternatives you've considered**

1) Force sidecar to oms-agent: The deployment runs in kube-system and injection should not happen there - its not even possible with a mutating webhook we defined ourselves (which would work for non kube- namespaces.

2) Special port for metrics on the app side: Not supported by most of the app frameworks.

3) Standalone Prometheus and Metrics Exporter: Something that all users would need to install and operate themselves without having any advantage and further would need to use unofficial exporters from Prometheus.

4) In the `oms-agent` ConfigMap documentation on the docs, there is an annotation which indicate that you can configure TLS for the agent. But we did not find any documentation or implementation details in the repos we looked at (maybe we looked in the wrong place).

**Additional context**

- Running AKS 1.16.9 with Istio 1.5.0
- Applications are implemented as Quarkus v1.4

**Comment by ganga1980** [comment]
> cc @ganga1980 @rashmichandrashekar

>> ++ @vishiy, looks like ask is provide to ability to deploy monitoring addon pods into non kube-system namespace and also  questions around configuring TLS prometheus endpoints.

**Comment by ganga1980** [comment]
> > cc @ganga1980 @rashmichandrashekar
> 
> > > ++ @vishiy, looks like ask is provide to ability to deploy monitoring addon pods into non kube-system namespace  for AKS and also  questions around configuring TLS prometheus endpoints.

**Comment by vishiy** [comment]
@MarianZoll - 
We can make the namespace configurable, so that you can run outside kube-sys. For scraping we support http & https. Just annotate you pod using 'prometheus.io/scheme' and we will pick it up. We ignore TLS errors, as we most of the in-cluster metric endpoint certs are self-signed. We can make that (not to ignore TLS errors) configurable, if you want to and have a need for that.

**Comment by MarianZoll** [comment]
@vishiy 
That would be a nice feature add I think and would further demistify the integration of ALA and AKS which works like a charm for most of the cases. 

The issue with `prometheus.io/scheme: https` is that it will ignore TLS errors, but as the app pods require mTLS they will terminate the connection anyway. 
This is actually a very nice feature of Istio (mTLS setup) as it works by default and without configuring or changing anything on your app logic. Instead the network of the Pod is intersected by a sidecar which takes care of all the mTLS connection (including setup and certificate rotations).

With the solution of configuring it in a non `kube-` system we would annotate this namespace as `istio-injection: enabled` and this will automatically setup mTLS for the `oms-agent` within the cluster. So this will be a win-win as we will use the great Prometheus feature of Azure Monitor without lossing cluster-internal mTLS which is one of the must-haves for production workloads in our case.

Anything I can provide to you or assist?

**Comment by jackfrancis** [comment]
@MarianZoll it was tagged by the bot due to lack of activity.

@vishiy can you enumerate the list of work items that we can do to the AKS Engine-provided omsagent addon implementation to unblock folks?

**Comment by jackfrancis** [comment]
ping @vishiy, can you comment if this is not something you'll be able to take on? If so, we can probably close it so customers understand that it's not being prioritized.

Thanks!

**Comment by kdziurdz** [comment]
hey, anything new here? Do you plan to introduce customization in scraping Prometheus endpoints with mTLS?
