### ISSUE TITLE
Add E2E cluster config converage for etcd enableDataEncryptionAtRest feature

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3456]
This is described as an alpha feature in the docs. If E2E signal is positive, then let's add it to a permanent cluster config to continue testing it, and add an issue to the capz backlog to enable this functioanlity there.

**Comment by jackfrancis** [comment]
cc @rbitia

**Comment by bridgetkromhout** [comment]
Closing per @jackfrancis, given AKS Engine deprecation.
