### ISSUE TITLE
Add "1.13" coverage to TestGetK8sVersionComponents unit tests

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#346]
This coverage was never added when we first released 1.13.

See the "1.14" additions in this PR as a reference:

https://github.com/Azure/aks-engine/pull/330/files#diff-bb9b6cb6f08a63800be959ba49eaf714R16

**Comment by serbrech** [comment]
@francis #330 you reference wasn't merged, maybe it's best to push there to avoid unnecessary conflicts?

**Comment by CecileRobertMichon** [comment]
#330 is merged now
