### ISSUE TITLE
NetworkPlugin cni failed to set up pod

### ISSUE THREAD

**Issue by sd2302** [Azure/aks-engine#3465]
**Describe the bug**

Pods fails intermittently with following:

 Warning  FailedCreatePodSandBox  5m35s                kubelet, k8s-agentpoolque-95198166-vmss00000u  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "f9ca6f3e9b60c7ee2b69675f715272e1cd1df53816ec0f66ee7028b33ae3958f" network for pod "cloud-ingestionmobiledetailssvc-5b659ccbdb-c8szx": NetworkPlugin cni failed to set up pod "cloud-ingestionmobiledetailssvc-5b659ccbdb-c8szx_cloud" network: unexpected end of JSON input

**Steps To Reproduce**

NA
**Expected behavior**
Pods should be Running status
Pods should start
**AKS Engine version**

Version: v0.47.0

**Kubernetes version**

1.15.9
**Additional context**

**Comment by jackfrancis** [comment]
@tamilmani1989, v0.47.0 of AKS Engine shipped w/ Azure CNI v1.0.30. Do we expect the above failures are fixed w/ more recent versions of Azure CNI?

**Comment by tamilmani1989** [comment]
not sure why cni failed here. we made a fix related to surfacing cni errors to kubelet in v1.0.33 so that kubelet will show actual error why cni failed. I would recommend to use latest cni

**Comment by sd2302** [comment]
Should I upgrade my aks-engine cluster then ?

Is there a way to see cni version, kubelet version for a specific version of aks-engine ?

we continue to have these issues

**Comment by jackfrancis** [comment]
What does your cluster look like? Another way to smoke test if a newer version of Azure CNI fixes things is to add a node pool, schedule enough pods to those new nodes to observe if the failure symptoms have gone away.

Do something like this using v0.52.0 of aks-engine:

```
aks-engine addpool --subscription-id $SUB_ID --api-model <path to api model> --node-pool <path to JSON file with new nodepool specs> --location $LOCATION --resource-group <resource group> --auth-method client_secret --client-id $SP_ID --client-secret $SP_PW
```

The JSON file with new nodepool specs should look like this:

```json
{
	"name": "newpool",
	"count": 10,
	"vmSize": "Standard_D2_v3",
	"availabilityProfile": "VirtualMachineScaleSets",
	
	}
}
```

Basically, probably a copy of the pool you're seeing this symptom on in your original api model with a new name, and enough nodes to repro.

If that works, then you can schedule an upgrade.

Does that make sense?

(Of course an upgrade w/ v0.52.0 *will* deliver a newer version of Azure CNI, but it's a rather brute force way to do something you don't know will have the intended effect.)

**Comment by sd2302** [comment]
cool, i will test this out and update everyone, thanks

**Comment by tamilmani1989** [comment]
@sd2302 you may get error again but this time kubelet will say what the actual error is and we can debug from there...BTW is it linux or windows cluster?

**Comment by sd2302** [comment]
It is a Linux, Ubuntu 16.04

k8s-agentpoolque-95198166-vmss00000n   Ready    agent    107d   v1.15.9   10.245.16.67    <none>        Ubuntu 16.04.6 LTS   4.15.0-1089-azure   docker://3.0.10+azure

**Comment by jackfrancis** [comment]
Any updates here?

**Comment by jackfrancis** [comment]
Please re-open if this is still an issue!
