### ISSUE TITLE
Private Cluster fail on "Microsoft.Network/publicIPAddresses/write" due to DenyPolicy 

### ISSUE THREAD

**Issue by schmichri** [Azure/aks-engine#3470]
**Describe the issue**
Hi, 

in my clients corporate environment I have a global deny policy for `Microsoft.Network/publicIPAddresses` permissions, coming from the fact that all traffic / IPs have to be connected internally (via express route). This policy is untouchable. In my subscription I've tried to deploy aks-engine based private k8s clusters and assign them to the given subnet. 

When I try to deploy the generated template out of the definition shown below I run into the deny policy error. 

Error:
```
{'additionalProperties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment failed with error: 'Authorization failed for template resource 'k8s-agent-ip-outbound' of type 'Microsoft.Network/publicIPAddresses'. The client 'thisisme@myclientsemaildomain.com' with object id '' does not have permission to perform action 'Microsoft.Network/publicIPAddresses/write' at scope '/subscriptions/MYSUBSCRIPTION/resourceGroups/cshtest2/providers/Microsoft.Network/publicIPAddresses/k8s-agent-ip-outbound'.'.", 'target': None, 'details': None, 'additionalInfo': None}
```

aks-engine definition
```

{
  "apiVersion": "vlabs",
  "location": "westeurope",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
        "useManagedIdentity": true,
        "enableRbac": true,
        "useInstanceMetadata": true,
        "privateCluster": {
          "enabled": true
        }
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "cshtest2-dns",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "/subscriptions/MYSUBSCRIPTION/resourceGroups/cshtest2/providers/Microsoft.Network/virtualNetworks/vNet-ServiceTeam-IAT/subnets/Subnet-ServiceTeam-IAT",
      "distro": "aks-ubuntu-18.04",
      "firstConsecutiveStaticIP": "10.120.4.20",
      "vnetCIDR": "10.120.4.0/24"
    },
    "agentPoolProfiles": [
      {
        "name": "agents",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "vnetSubnetId": "/subscriptions/MYSUBSCRIPTION/resourceGroups/cshtest2/providers/Microsoft.Network/virtualNetworks/vNet-ServiceTeam-IAT/subnets/Subnet-ServiceTeam-IAT",
        "distro": "aks-ubuntu-18.04"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    }
  }
}

```

Does somebody has a hint how I can workaround this or does know a way how to achieve nonpublic / "real private" aks-engine based clusters? BTW the same rule avoids the usage of managed AKS Cluster.

Looking forward for some help. 

desperately regards
schmichri

**AKS Engine Version***

aks-engine version
Version: v0.52.0
GitCommit: aa2973a22
GitTreeState: clean

**Expected behavior**
Private cluster gets deployed with no need for public IPs

**Please don't remove the text below**
Notify @az-policy-kube

**Comment by jackfrancis** [comment]
Hi @schmichri, can you try creating a cluster w/ "Basic" Loadbalancer type? In your `kubernetesConfig` object in the api model:

```
"loadBalancerSku": "Basic",
```

"Standard" Loadbalancer (the default configured by AKS Engine) requires a public IP address in the resource group to route outbound traffic through (SNAT), whereas "Basic" doesn't have this requirement.

Note: if this does unblock you you'll only be able to use a single node pool in your cluster, which is a limitation of the "Basic" Loadbalancer type.

**Comment by schmichri** [comment]
@jackfrancis This unblocks my "public IP problem" but now I run in new restrictions regarding Roles. I guess it's network contributor which is denied by deny roles as well. Anyways, I will close this issue with big thank you for the great hint!

**Comment by jackfrancis** [comment]
Glad it was helpful!
