### ISSUE TITLE
kube-addon-manager complaining about coredns clusterIP

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3478]
We don't see any higher order symptoms of cluster DNS, but kube-addon-manager is complaining about the clusterIP value in the coredns spec:

```
Error from server (Invalid): error when creating "/etc/kubernetes/addons/coredns.yaml": Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.0.0.10": provided IP is already allocated
```

Perhaps this is the result of kube-addon-manager regularly reconciling after the svc has been created? In any event that log message is annoying.

**Comment by bridgetkromhout** [comment]
Consulted with @jackfrancis and due to the AKS Engine deprecation, we will not take action on this issue.
