### ISSUE TITLE
Expose created roleAssignment guid values in ARM output

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3494]
E.g.:

https://github.com/Azure/aks-engine/compare/master...dennis-benzinger-hybris:feat/3494

**Comment by jackfrancis** [comment]
https://github.com/Azure/aks-engine/compare/master...dennis-benzinger-hybris:feat/3494

**Comment by dennis-benzinger-hybris** [comment]
By now the Azure Java SDK exposes the `outputResources` on an ARM `deployment`:
Azure/azure-libraries-for-java#1209

So from our perspective this workaround can skipped.
