### ISSUE TITLE
hauns policy

### ISSUE THREAD

**Issue by mhaun0910** [Azure/aks-engine#3505]
**Describe the issue**
A clear and concise description of the issue

**AKS Engine Version***

**Kubernetes Version**

**Gatekeeper Version**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Please don't remove the text below**
Notify @az-policy-kube

**Comment by kenieva** [comment]
@mhaun0910 What is the issue that you are facing?
