### ISSUE TITLE
Kubelet service causes CPU 100% when docker service is not started in Windows nodes

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#351]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
master
---

**What happened**:
Due to timeout issue, docker service was not started after Windows started, I found these in event logs,
```
The Docker service failed to start due to the following error: %%1053
A timeout was reached (30000 milliseconds) while waiting for the Docker service to connect.
```
Kubelet service was causing CPU 100% in this situation.
aks-engine uses nssm to run kubelet service, kubeletstart.ps1 ran into exception because it faild to run c:\k\kubelet.exe because of stopped docker service, nssm will re-execute kubeletstart.ps1 indefinitely which causing CPU 100%.

**What you expected to happen**:
Kubelet service starts successfully.
Is it possible to ensure docker service before call c:\k\kubelet.exe in kubeletstart.ps1?

**How to reproduce it**:
remote into k8s Windows node, execute these cmdlets,
Stop-Service docker -Force
Stop-Service kubelet -Force
Start-Service kubelet

**Comment by zhiweiv** [comment]
I found a related issue https://github.com/Azure/acs-engine/issues/4001.

**Comment by PatrickLang** [comment]
This needs two fixes:

1. set kubelet service to be dependent on docker service. This will need to change later once we move to CRI-ContainerD
2. Add a 5 second sleep to the end of startkubelet.ps1 (after kubelet.exe exits), or adjust service restart parameters to wait 5-10 seconds between attempts.

I probably won't be able to look at these since I'm focused on testing the upstream Kubernetes project to get Windows stable for 1.14. I should have more time to look at aks-engine operational improvements after 1.14 is done.

**Comment by CecileRobertMichon** [comment]
remove stale label

This doesn't seem like it's fixed yet.

**Comment by sanderaernouts** [comment]
We have been running into this issue for the past few days now. At some seemingly random point in time our windows node disconnects from the cluster. When I inspect the node via Remote Desktop I see the docker service is not running and that `nssm` keeps trying to run `kubeletstart.ps1` causing the node to be around 100% CPU.

We deployed this cluster using:
- aksengine 0.35.1
- kubernetes 1.14.1

**Problem**
The real question off course is why does the docker service crash and fail to recover from that on it's own? But I guess that is an issue that does not belong in this repo. I would however help if the Kubelet start-up did not get stuck when this situation occurs.

**Workaround**
I can resolve the problem by manually starting the docker service on the node. The kubelet is then able to start and the node comes back online.

**Fix**
If the `kubeletstart.ps1` script would check if the docker service is running and start if it is not running then this problem would probably resolve itself. I guess the fix @PatrickLang proposed (making the kubelet service dependent on docker) would work as well.

Currently the kubelet service has no such dependency:
![image](https://user-images.githubusercontent.com/6184673/58306645-69b1c780-7dfc-11e9-9017-2b5df91bcced.png)
