### ISSUE TITLE
Add option to specify sleep time between vmss nodes upgrades

### ISSUE THREAD

**Issue by jprecuch** [Azure/aks-engine#3514]
Hi,
Would it be possible to add option where user can specify sleep time between every vmss is upgrades (deleted and new recreated)? 

Here is scenario that we faces in last upgrade cycle:
1. Components has 3 containers running to have stable HA cluster with volumes
2. One node goes down and first containers is drained away. 
3. New node is spun 
4. Second node is deleted before first container fully started (for containers with volumes it always takes time to fully start)..could be even 15min. 
5. Cluster is degraded as 2/3 containers are down and still stating. 

Option to specify sleep time between node is deleted and new one create would solve this issues easily.

Thanks

**Comment by jackfrancis** [comment]
Rather than adding an arbitrary sleep value, would the ability to run upgrade against a single node solve this problem? I.e., you could write a script that would manually progress through a list of node, running upgrade against each, and proceed only when your custom conditions are met.

**Comment by jprecuch** [comment]
@jackfrancis Wouldn't that complicate things more? I mean having "simple" sleep time between deletion of node and creation of new one for VMSS based on specified --flag would be enough. Because normally after new node is spun it drain containers. If we add sleep time before new node is spun then this will resolve everything.
