### ISSUE TITLE
Odd aks-engine upgrade behavior/logs with Windows nodes

### ISSUE THREAD

**Issue by marosset** [Azure/aks-engine#3520]
**Describe the bug**
When performing an aks-engine upgrade on a cluster with Windows nodes I saw the following output

```
INFO[1137] Copying custom annotations, labels, taints from old node 1199k8s01000000 to new node 1199k8s01000002...
WARN[1137] Error draining agent VM 1199k8s01000002. Proceeding with copying node properties. Error: nodes "1199k8s01000002" not found
ERRO[1437] Copying custom annotations, labels, taints from old node 1199k8s01000000 to new node 1199k8s01000002 can't complete within 5m0s
WARN[1437] Failed to copy custom annotations, labels, taints from old node 1199k8s01000000 to new node 1199k8s01000002: Copying custom annotations, labels, taints from old node 1199k8s01000000 to new node 1199k8s01000002 can't complete within 5m0s
INFO[1677] Successfully deleted VM 1199k8s01000000 in VMSS 1199k8s01
```

and I think there are a few, possibly related, issues here.

1. The error was not fatal and aks-engine continued upgrading the rest of the nodes in the cluster. I think this could result in an entire agent pool getting taken down by a bad upgrade. Maybe it would be better to fail if we can't find a node here?

1. I haven't verified this in code yet but I think aks-engine is just waiting for ARM operations to complete when creating new machines. For Windows node provisioning the CSE exits before the nodes have actually been joined to the cluster (the CSE triggers a restart and after that restart the Windows nodes are joined to the cluster). Aks-engine upgrade should check for node readiness instead of just waiting for ARM operations to complete in order to be safe.

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**
Tested with aks-engine v0.52.0 

**Kubernetes version**
n/a

**Additional context**

**Comment by surajrana93** [comment]
I am also seeing this issue.

time="2020-07-11T21:24:28+05:30" level=info msg="Draining node 1852k8s00000000"
time="2020-07-11T21:24:28+05:30" level=info msg="Node 1852k8s00000000 has been marked unschedulable."
time="2020-07-11T21:24:29+05:30" level=info msg="Node 1852k8s00000000 has no scheduled pods"
time="2020-07-11T21:24:29+05:30" level=info msg="Deleting VM 1852k8s00000000 in VMSS 1852k8s00"
time="2020-07-11T21:24:29+05:30" level=info msg="Copying custom annotations, labels, taints from old node 1852k8s00000000 to new node 1852k8s00000003..."
time="2020-07-11T21:24:30+05:30" level=warning msg="Error draining agent VM 1852k8s00000003. Proceeding with copying node properties. Error: nodes \"1852k8s00000003\" not found"
time="2020-07-11T21:29:30+05:30" level=error msg="Copying custom annotations, labels, taints from old node 1852k8s00000000 to new node 1852k8s00000003 can't complete within 5m0s"
time="2020-07-11T21:29:30+05:30" level=warning msg="Failed to copy custom annotations, labels, taints from old node 1852k8s00000000 to new node 1852k8s00000003: Copying custom annotations, labels, taints from old node 1852k8s00000000 to new node 1852k8s00000003 can't complete within 5m0s"
time="2020-07-11T21:30:31+05:30" level=info msg="Successfully deleted VM 1852k8s00000000 in VMSS 1852k8s00"


The weird things is that its trying to drain the new nodes (1852k8s00000003) that it just created. Also is there a way to increase this time to copy?
