### ISSUE TITLE
enableVMSSNodePublicIP: true is broken

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#3521]
**Describe the bug** Deploy a cluster with an agent pool defined as: 

```
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v3",
        "enableVMSSNodePublicIP": true,
        "availabilityProfile": "VirtualMachineScaleSets"
      },
```

The cluster fails to create with: 
```
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "NicWithPublicIpCannotReferencePoolWithOutboundRule",
                "message": "OutboundRules for VMs with public IpConfigurations (instance level publicIPs) /subscriptions/[...]/ipConfigurations/ipconfig1 are not supported"
            }
        ]
    }
}
```

This is due to outbound rules being defined for the node outbound Public Load Balancer. According to https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#scenarios, "When using Standard Load Balancer, outbound rules are not supported if a public IP is assigned to the Virtual Machine."

This is the same issue as https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/717.

Unfortunately, the issue is not as simple as removing those outbound rules since the SLB is shared by the whole cluster, whereas one agent pool might have node public IPs and not the other.

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by jackfrancis** [comment]
This was implemented when Basic LB was the default LB SKU:

https://github.com/Azure/aks-engine/pull/1087

We should do a quick test to see if this functionality still works in that configuration, and if so, add appropriate validation.

Alternatively, it may have never been fully implemented for AKS Engine, as it's an AKS-originating feature.
