### ISSUE TITLE
Windows nodes have old version after upgrade

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3522]
For example, when testing the `base` cluster config using the 1.18-1.19 flow, we see this symptom:

```
[91m[1m• Failure [0.364 seconds][0m
 Azure Container Cluster using the Kubernetes Orchestrator
 [90m/aks-engine/test/e2e/kubernetes/kubernetes_test.go:195[0m
   regardless of agent pool type
   [90m/aks-engine/test/e2e/kubernetes/kubernetes_test.go:196[0m
     [91m[1mshould have the expected k8s version [It][0m
     [90m/aks-engine/test/e2e/kubernetes/kubernetes_test.go:321[0m
 
     [91mExpected
         <string>: v1.19.0-beta.2
     to equal
         <string>: v1.18.4[0m
 
     /aks-engine/test/e2e/kubernetes/kubernetes_test.go:331
```

The test output shows the 1.18.4 node as being a Windows node.

**Comment by chewong** [comment]
+1

**Comment by chewong** [comment]
+1 in https://upstream.jenkins.azure-containers.io/blue/organizations/jenkins/k8s-create-cluster-matrix-1.16/detail/k8s-create-cluster-matrix-1.16/571/pipeline/281

**Comment by chewong** [comment]
According to https://upstream.jenkins.azure-containers.io/blue/organizations/jenkins/k8s-create-cluster-matrix-1.16/detail/k8s-create-cluster-matrix-1.16/571/pipeline/281, it looks like there is a random Windows VMSS nodepool that aren't registered with the API model (`2105k8s00`). After the upgrade, it's registered with the API model, causing the cluster to have an extra node with the olde version (`2105k8s00000001`).

**Comment by jackfrancis** [comment]
Right, I think in the scale/upgrade flow, the "do I have any VMS in node pool <pool name>?" foo is failing, and thus an entirely new one is being created. That flow is terribly convoluted, unfortunately, and the trickiest part is figuring out why this is inconsistent.
