### ISSUE TITLE
deploy to existing machines

### ISSUE THREAD

**Issue by MSFTChao** [Azure/aks-engine#3567]
Hi there,

Currently, all the tutorials I have read using aks-engine to deploy k8s cluster requires to create NEW VMs in azure. But if we already have a VNet with a bunch of running machines, can aks-engine directly deploys k8s services onto these existing running machines instead of creating new machines? Further more, if our existing machines are grouped in an on-premise VNet rather than azure VMs under azure VNet. Can aks-engine directly deploy k8s services onto these machines?

Thanks!

**Comment by jackfrancis** [comment]
Hi @msftchao, you are correct, AKS Engine is unable to use existing machines to install Kubernetes componentry. I would recommend investigating the kubeadm project for turning a linux VM into a Kubernetes node:

https://github.com/kubernetes/kubeadm

**Comment by MSFTChao** [comment]
Hi @jackfrancis , thanks very much for your replying! Per this [thread](https://github.com/Azure/aks-engine/issues/2018), aks-engin was not supporting kubeadm. Is it still the case? Or it's already supporting it officially?

**Comment by jackfrancis** [comment]
Hi @MSFTChao: AKS Engine doesn't support the kubeadm flow. You could investigate the Azure implementation of the cluster-api project:

https://github.com/kubernetes-sigs/cluster-api-provider-azure
