### ISSUE TITLE
flannel pod can't be scheduled

### ISSUE THREAD

**Issue by vossss** [Azure/aks-engine#3622]
If a taint like “app=none:NoExecute” be added to a node, flannel pod can't be scheduled to this node,
and  pods which running on this node is not working properly

Reason:
flannel daemonset  has no  configuration toleration ":NoSchedule".

**Comment by jackfrancis** [comment]
Hi @vossss, what version of Kubernetes built w/ AKS Engine are you running?

You can test your toleration theory out by manually editing the flannel spec in the `/etc/kubernetes/addons/` directory on each control plane VM.

**Comment by vossss** [comment]
k8s version: v1.15.11
akse version: v0.50.0

I have tested my toleration theory out by manually editing the flannel spec in the /etc/kubernetes/addons/ directory on each control plane VM, and the flannel was running correctly.

 Can you add these tolerations to the flannel addon in the next akse release?
