### ISSUE TITLE
 After the master restarts, it's not normal.

### ISSUE THREAD

**Issue by vossss** [Azure/aks-engine#3623]
If the master be rebooted，the etcd device name may be changed.
As shown below,  etcd device was /dev/sdc1 before restarting.
When rebooted, etcd device name was changed to /dev/sda1.
But as in /etc/fstab, /dev/sdc1 was stilled mounted as etcd disk,
Certainly, etcd data is incorrect.
I think the device id should be used instead of device name to mount etcd disk.

![图片](https://user-images.githubusercontent.com/16187999/88033899-823d7f00-cb72-11ea-9fc6-f0be7643f2ed.png)

**Comment by jackfrancis** [comment]
This is a bug we observed w/ 18.04-LTS, and fixed with a series of changes that is now present in the latest release.

What version of aks-engine was your cluster built with, and what version of Kubernetes are you running?

**Comment by vossss** [comment]
akse-engine version: v0.50.0
k8s version: v1.15.11
