### ISSUE TITLE
New documentation: upgrade limitations / issues

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#364]
Let's start a canonical doc that aims to help users through common upgrade problems. One we want to highlight especially is cluster-autoscaler.

**Comment by CecileRobertMichon** [comment]
Should we just add this in the troubleshooting doc with other "known issues"?

**Comment by CecileRobertMichon** [comment]
Done: https://github.com/Azure/aks-engine/blob/master/docs/topics/upgrade.md
