### ISSUE TITLE
We are currently unable to scale up or scale down any of our production VMSS using AKS Engine.

### ISSUE THREAD

**Issue by surendramannem** [Azure/aks-engine#3655]
**Describe the bug:**
Sometimes AKS engine deployed in Azure was unable to do VMSS scale up operations and throwing the below requestCount error

The server rejected the request because too many requests have been received for this subscription. 

(Code: OperationNotAllowed) {"operationgroup":"HighCostGetVMScaleSet30Min","starttime":"2020-07-30T20:03:03.8475154+00:00","endtime":"2020-07-30T20:18:03.8475154+00:00","allowedrequestcount":900,"measuredrequestcount":3554} (Code: TooManyRequests, Target: HighCostGetVMScaleSet30Min)

**Steps To Reproduce**
This is not happening always.

**Expected behavior**
Instances must be launched as specified in the configuration file.

Kubernetes version
N/A

**Comment by jackfrancis** [comment]
Hi @surendramannem, the above symptoms can occur when lots of requests are being sent to the VMSS API quickly over a short period of time. What version of Kubernetes are you using in the cluster seeing those symptoms?

**Comment by sharan-v** [comment]
Hi @jackfrancis, Its actually aks-engine on ubuntu 16.

**Comment by sharan-v** [comment]
This cluster is a aks-engine deployed cluster running autoscaler. We had to increase the amount of pods running on the cluster and did this by increasing the replica count on the deployment, this event triggered additional nodes to be brought online but failed. The reason why this failed is because we hit the API limit on the subscription, the way we fixed this was to remove any record of the SP from the masters and to leave it for about 30 mins then re-added. It seems as though the autoscaler and other Kubernetes services don't respect for 429 responses and it just keep hammering the API's

**Comment by jadarsie** [comment]
AFAIK, these issues should not happen with newer versions of Kubernetes / Azure Cloud Provider.

This [how-to](https://github.com/Azure/aks-engine/blob/master/docs/howto/kubernetes-large-clusters.md) explains how to tune cloud provider so it calls the ARM endpoints less frequently.

**Comment by jackfrancis** [comment]
@sharan-v in particular, starting with Kubernetes v1.18.0 (1.18 is now up to v1.18.9 as of today) these API limits are hit at much higher cluster node + disk counts. In other words, it's still possible to run a cluster that generates more traffic to the Azure APIs over a period of time that is permitted, but the headroom is much, much higher starting w/ 1.18.

How many VMSS and instances are you running? How many persistent volumes do you use on average? Without knowing those numbers, I can't say for sure that 1.18 will help you compared to 1.15, but for most cluster sizes (node counts under, say, 300) 1.18 makes Azure much happier compared to 1.15.

**Comment by sharan-v** [comment]
> @sharan-v in particular, starting with Kubernetes v1.18.0 (1.18 is now up to v1.18.9 as of today) these API limits are hit at much higher cluster node + disk counts. In other words, it's still possible to run a cluster that generates more traffic to the Azure APIs over a period of time that is permitted, but the headroom is much, much higher starting w/ 1.18.
> 
> How many VMSS and instances are you running? How many persistent volumes do you use on average? Without knowing those numbers, I can't say for sure that 1.18 will help you compared to 1.15, but for most cluster sizes (node counts under, say, 300) 1.18 makes Azure much happier compared to 1.15.

We are using 3*3 different sizes of VMSS with 70-150 instances. i'll update the information about persistent volumes. We are not able to get the exact reason on what basis it is failing as it is not happening continuously. Analyzing the requests parallely if we can get something which is causing this.
