### ISSUE TITLE
Upgrade from 1.14.8 to 1.15.11 fails due to missing pod-security-policy.yaml file

### ISSUE THREAD

**Issue by mtgerb** [Azure/aks-engine#3656]
**Describe the bug**

Upgrading a cluster from version 1.14.8 to version 1.15.11 fails, because `pod-security-policy.yaml` file is missing on the master node (should be located in /etc/kubernetes/addons/).

**Steps To Reproduce**

1. Create a cluster with kubernetes version 1.14.8 using aks-engine v.0.48.0 or older
2. Try to upgrade to version 1.15.11 using aks-engine v.0.54.0

**Expected behavior**

The cluster is successfully upgraded

**AKS Engine version**

v.0.54.0

**Kubernetes version**

1.14.8 and 1.15.11

**Comment by jprecuch** [comment]
Same scenario on our cluster. Jump from 1.14.7 to 1.15.12 using aks-engine v.0.54.0
`+ for i in '$(seq 1 $retries)'
+ grep -Fq '#EOF' /etc/kubernetes/addons/pod-security-policy.yaml
grep: /etc/kubernetes/addons/pod-security-policy.yaml: No such file or directory
+ '[' 116 -eq 1200 ']'
+ sleep 1
+ for i in '$(seq 1 $retries)'
+ grep -Fq '#EOF' /etc/kubernetes/addons/pod-security-policy.yaml
grep: /etc/kubernetes/addons/pod-security-policy.yaml: No such file or directory
+ '[' 117 -eq 1200 ']'
+ sleep 1
+ for i in '$(seq 1 $retries)'
`

**Comment by jackfrancis** [comment]
Hi @mtgerb and @jprecuch, can you try changing the `"pod-security-policy"` addon configuration to `"enabled": true` in your apimodel.json *before* you perform the upgrade?

Or do you explicitly want to disable the AKS Engine-provided PodSecurityPolicy configuration?
