### ISSUE TITLE
Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady Error  with Flannel CNI 

### ISSUE THREAD

**Issue by satishsudini** [Azure/aks-engine#3665]
**Describe the bug**
Kubelet failing with Container runtime network not ready error with k8-1.18.6

/etc/cni/net.d/10-flannel.conf

{
  "name": "cbr0",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true
    "cniVersion": "0.2.0",
  }
}

**AKS Engine version**
v0.54.0

**Kubernetes version**
1.18.6

{"cniVersion":"","name":"cbr0","plugins":[{"delegate":{"isDefaultGateway":true},"name":"cbr0","type":"flannel"}]}: [plugin flannel does not support config version ""]
Aug 04 19:25:43 k8s-master-40029895-0 kubelet[1470]: W0804 19:25:43.797204    1470 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
Aug 04 19:25:46 k8s-master-40029895-0 kubelet[1470]: E0804 19:25:46.941625    1470 kubelet.go:2188] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 04 19:25:48 k8s-master-40029895-0 kubelet[1470]: W0804 19:25:48.800001    1470 cni.go:202] Error validating CNI config list {"cniVersion":"","name":"cbr0","plugins":[{"delegate":{"isDefaultGateway":true},"name":"cbr0","type":"flannel"}]}: [plugin flannel does not support config version ""]
Aug 04 19:25:48 k8s-master-40029895-0 kubelet[1470]: W0804 19:25:48.800022    1470 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
Aug 04 19:25:50 k8s-master-40029895-0 kubelet[1470]: I0804 19:25:50.951577    1470 azure_backoff.go:81] GetVirtualMachineWithRetry(k8s-master-40029895-0): backoff success
Aug 04 19:25:51 k8s-master-40029895-0 kubelet[1470]: E0804 19:25:51.950968    1470 kubelet.go:2188] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 04 19:25:53 k8s-master-40029895-0 kubelet[1470]: W0804 19:25:53.803925    1470 cni.go:202] Error validating CNI config list {"cniVersion":"","name":"cbr0","plugins":[{"delegate":{"isDefaultGateway":true},"name":"cbr0","type":"flannel"}]}: [plugin flannel does not support config version ""]
Aug 04 19:25:53 k8s-master-40029895-0 kubelet[1470]: W0804 19:25:53.803948    1470 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
Aug 04 19:25:56 k8s-master-40029895-0 kubelet[1470]: E0804 19:25:56.961591    1470 kubelet.go:2188] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

**Comment by satishsudini** [comment]
@jackfrancis @CecileRobertMichon : can you please try out in your environment.Any workaround for a quick fix  or missing any parameter causing this issue

**Comment by craiglpeters** [comment]
@satishsudini is this still an issue for you?
