### ISSUE TITLE
Creating a new cluster leaves some masters in need of reboot (still)

### ISSUE THREAD

**Issue by Michael-Sinz** [Azure/aks-engine#3668]
**Describe the bug**
After creating a new cluster with 5 masters, 4 of the 5 masters are tagged with needing an OS reboot.

**Steps To Reproduce**
We create a v7.0.2 skyman cluster (aks-engine 0.54.0, kubernetes 1.18.6) with 5 masters and at least one VMSS node pool.

The input aks-engine looks like this:
```
 {
   "apiVersion": "vlabs",
   "location": "westus2",
   "properties": {
     "agentPoolProfiles": [
       {
         "OSDiskSizeGB": 128,
         "availabilityProfile": "VirtualMachineScaleSets",
         "count": 5,
         "ipAddressCount": 64,
         "kubernetesConfig": {
           "kubeletConfig": {
             "--image-pull-progress-deadline": "30m",
             "--max-pods": "63"
           }
         },
         "name": "agentpool1",
         "singlePlacementGroup": false,
         "storageProfile": "ManagedDisks",
         "vmSize": "Standard_DS13_v2"
       }
     ],
     "linuxProfile": {
       "adminUsername": "azureuser",
       "ssh": {
         "publicKeys": [
           {
             "keyData": "********"
           }
         ]
       }
     },
     "masterProfile": {
       "OSDiskSizeGB": 128,
       "count": 5,
       "dnsPrefix": "speech1-ppe7",
       "vmSize": "Standard_D8s_v3"
     },
     "orchestratorProfile": {
       "kubernetesConfig": {
         "ExcludeMasterFromStandardLB": true,
         "addons": [
           {
             "enabled": false,
             "name": "blobfuse-flexvolume"
           },
           {
             "enabled": false,
             "name": "scheduled-maintenance"
           },
           {
             "enabled": false,
             "name": "smb-flexvolume"
           },
           {
             "enabled": false,
             "name": "keyvault-flexvolume"
           },
           {
             "enabled": true,
             "name": "nvidia-device-plugin"
           },
           {
             "config": {
               "cores-per-replica": "320",
               "min-replicas": "2",
               "nodes-per-replica": "60"
             },
             "enabled": true,
             "name": "coredns"
           }
         ],
         "apiServerConfig": {
           "--feature-gates": "TTLAfterFinished=true,EphemeralContainers=true",
           "--profiling": "True",
           "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
         },
         "azureCNIVersion": "v1.1.2",
         "components": [
           {
             "data": "******",
             "enabled": true,
             "name": "cluster-init"
           }
         ],
         "controllerManagerConfig": {
           "--feature-gates": "TTLAfterFinished=true",
           "--terminated-pod-gc-threshold": "50"
         },
         "etcdDiskSizeGB": "2048",
         "kubeletConfig": {
           "--feature-gates": "EphemeralContainers=true",
           "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
         },
         "loadBalancerSku": "Standard",
         "networkPlugin": "azure"
       },
       "orchestratorType": "Kubernetes",
       "orchestratorVersion": "1.18.6"
     },
     "servicePrincipalProfile": {
       "clientId": "***",
       "secret": "********"
     }
   }
 }
```

**Expected behavior**
With the change in https://github.com/Azure/aks-engine/issues/3533 we thought it should have had all nodes rebooted before going live in the cluster.  Testing shows that the VMSS nodes and *1* master are correctly rebooted but not the remaining masters.

In my two test cases, it was always master-1 that was already rebooted (or not in need of reboot) while master-0, master-2, master-3, and master-4 were in need of a reboot.

**AKS Engine version**
0.54.0

**Kubernetes version**
1.18.6

**Additional context**
This shows that it was a reboot that was required by some package install/OS operation as aks-engine just makes the file exist if it did not exist and it would be empty.

```
$ cat /var/run/reboot-required
*** System restart required ***
```

**Comment by Michael-Sinz** [comment]
I am working on validating this some more.  There may be some other cause here.

**Comment by Michael-Sinz** [comment]
Ok, so I built another cluster with minimal setup and the master nodes were now 1 with reboot-required set and 2 without.
(Right after the cluster was up and I could run a job on it to check that host path)  (Within about 2 minutes of returning from the deployment of the arm template into the resource group)

This seems to indicate that there is some race going on since I have had 1 of 3, 3 of 3, and 4 of 5(twice) masters need to reboot right after cluster creation with basically the same aks-engine/kubernetes/etc configs (only difference was subscription, region, and master count)

**Comment by jackfrancis** [comment]
So, reviewing the code, CSE triggers an actual reboot (`/bin/bash -c "shutdown -r 1 &"`) only if `/var/run/reboot-required` exists. AKS Engine *does* touch this file, in the following conditions:

- if you're using the vanilla 18.04-LTS OS image (not the AKS Engine-curated VHD) for master VMs (this would be have a 100% consistent outcome across all master VMs btw)
- ditto for node pools, per-node pool
- if you're using the AKS Engine-provided `cilium` addon (this would be 100% consistent across all master VMs and node VMs

So, I suspect that apt (or cloud-init) is invoking the reboot condition. Perhaps there is a staged rollout happening for the kernel version of 18.04-LTS that ships w/ v0.54.0?

**Comment by Michael-Sinz** [comment]
I do know the change that was made in aks-engine to look for the trigger but something is amiss since it is unclear why some masters are clean and others are not.

I included our input to aks-engine and it is complete (module some redacted elements like secrets) - we use the aks-engine provided images for the VMs.  (We don't specifically call out something different)

My guess is that there is some background process that races with the cloud-init process and sometimes it has the updates already done and other times it does not and we get the node up and done right away.

I have not gone into trying to debug the cloud-init process.

**Comment by Michael-Sinz** [comment]
Interesting potential related issue:  This is a guess, but we have now seen three cluster creates fail with code 36, which is about addon manager.  This is with cluster configurations via aks-engine (api model) that is identical other than name and secrets.

Luckily, in one case we were able to log onto the master VM that failed (it was master-1) and it shows what looks like an apt-get update thing happening in the middle of the kube-addon-manager work.  It may be nothing but this seems to point at some potential internal races (or maybe just something of the race for this bug and not the failure to provision the cluster)

```
+ echo Executed '"systemctl' enable 'kubelet"' 1 times
Executed "systemctl enable kubelet" 1 times
+ [[ -n true ]]
+ time_metric EnsureAddons ensureAddons
+ shift
+ ensureAddons
+ retrycmd 120 5 30 /usr/local/bin/kubectl --kubeconfig=/home/azureuser/.kube/config get pods -l app=kube-addon-manager -n kube-system
+ retries=120
+ wait_sleep=5
+ timeout=30
+ shift
+ shift
+ shift
++ seq 1 120
+ for i in $(seq 1 $retries)
+ timeout 30 /usr/local/bin/kubectl --kubeconfig=/home/azureuser/.kube/config get pods -l app=kube-addon-manager -n kube-system
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
After this operation, 233 kB disk space will be freed.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 81418 files and directories currently installed.)
Removing mlocate (0.26-2ubuntu3.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 81405 files and directories currently installed.)
Purging configuration files for mlocate (0.26-2ubuntu3.1) ...
+ break
+ echo Executed apt-get purge -y '"mlocate"' 1 times
Executed apt-get purge -y "mlocate" 1 times
+ '[' 1 -eq 120 ']'
+ sleep 5
+ for i in $(seq 1 $retries)
+ timeout 30 /usr/local/bin/kubectl --kubeconfig=/home/azureuser/.kube/config get pods -l app=kube-addon-manager -n kube-system
+ '[' 2 -eq 120 ']'
+ sleep 5
```

**Comment by craiglpeters** [comment]
I think this is closed thanks to PR 3721
