### ISSUE TITLE
Kubernetes nodes going to NotReady State

### ISSUE THREAD

**Issue by azharudheen** [Azure/aks-engine#3672]
We are observing the Kubernetes nodes are going to NotReady state quite frequently.  When we do a kubectl get nodes we are seeing docker version to be unknown. "docker://uknown".

Attached is the kubelet logs taken while the issue was occuring

**Comment by azharudheen** [comment]
[](url)

**Comment by azharudheen** [comment]
[kubelet-node1.log](https://github.com/Azure/aks-engine/files/5038993/kubelet-node1.log)

**Comment by mboersma** [comment]
It does look like the docker daemon stops responding at some point. I wonder if the node is overloaded? What does `kubectl describe nodes` say? Or just running `top` in an SSH session to one of the failing nodes?

Is this something specific to AKS Engine? If so, can you provide a reproducible case with the version of `aks-engine`, the version of Kubernetes, and an example apimodel.json?

**Comment by azharudheen** [comment]
We are using 1.13 version of Kubernetes. The issue is neither reproducible nor we see a pattern. After stop and start of the docker daemon the issue seems to go away. Here is another issue raised for the same with more details : https://github.com/docker-library/docker/issues/250

**Comment by azharudheen** [comment]
We are using 1.13 version of Kubernetes. The issue is neither reproducible nor we see a pattern. After stop and start of the docker daemon the issue seems to go away. Here is another issue raised for the same with more details : https://github.com/docker-library/docker/issues/250

**Comment by azharudheen** [comment]
We are using 1.13 version of Kubernetes. The issue is neither reproducible nor we see a pattern. After stop and start of the docker daemon the issue seems to go away. Here is another issue raised for the same with more details : https://github.com/docker-library/docker/issues/250
