### ISSUE TITLE
Hyperv Containerd configuration

### ISSUE THREAD

**Issue by jsturtevant** [Azure/aks-engine#3687]
**Describe the request**
Be able to control the Containerd Runtime handlers

https://github.com/Azure/aks-engine/blob/c273c5163962e9ef42e01c4547de93b635361084/parts/k8s/windowscontainerdfunc.ps1#L127-L140  

**Explain why AKS Engine needs it**
When adding hyperv support we need to be able to specify the default handler for enabling [upstream tests ](https://testgrid.k8s.io/sig-windows-containerd#aks-engine-azure-windows-master-containerd-hyperv) with having to modify existing k8s tests to run them in hyperv mode, while the desired default is to run in process isolated.

In addition, given that hyperv only supports running versions less than the current Host OS (for example a host of 1909 can run 2019 containers in hyperv but cannot run 2004) having a configuration for 2004 is not needed.  In addition some customers will want to control which version of can be run.  

**Describe the solution you'd like**

Adding to the api model a section that enables you specify support:

```json
 "windowsProfile": {
        "adminUsername": "azureuser",
        "adminPassword": "replacepassword1234$",
        "enableAutomaticUpdates": false,
        "sshEnabled": true,
        "windowsPublisher": "MicrosoftWindowsServer",
        "windowsOffer": "WindowsServer",
        "windowsSku": "Datacenter-Core-2004-with-Containers-smalldisk",
        "imageVersion": "latest",
        "hyperv":{
          "default": "proccess or hyperv",
          "hypervisors":[
            "17763",
            "18362",
            "18363",
            "19041"
          ]
        }
```

**Describe alternatives you've considered**
Put the configuration on a storage blob and download the template. This requires customers to have deep knowledge of containerd configuration.

**Additional context**
Does linux eventually need something similar for runtime like kata containers? https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md#kata-containers-as-a-runtimeclass

**Comment by jsturtevant** [comment]
We landed on a basic model in #3688:

```json
"windowsProfile": {
...
      "windowsSku": "Datacenter-Core-2004-with-Containers-smalldisk",
      "imageVersion": "latest",
      "windowsRuntimes": {
        "default": "process",
        "hypervRuntimes": [
          {"buildNumber": "17763"},
          {"buildNumber": "19041"}
        ]
      }
    },
```

To do for this issue:  

- [ ] Is there need for adding other configuration options (cpu/memory) to various runtime handlers
- [ ] Should we move this under the kubernetesConfig instead of having this be in WindowsProfile ([comment](https://github.com/Azure/aks-engine/pull/3688#discussion_r470093432) from @marosset) 
  - The rest of the runtime settings (docker vs containerd, containerd URl etc) are all there so the settings would stay together
  - We might be moving these settings to a place where they can be different for each agent pool. I don't think we know how that will look yet.

**Comment by marosset** [comment]
We should add some validation too, probably in aks-engine's validate.go to make sure only valid build numbers are listed.
This could make it easier to root-cause incorrect configurations earlier.

**Comment by jsturtevant** [comment]
There is some validation there already but should revisit if we enable other features:

https://github.com/Azure/aks-engine/blob/e74871353eb5f5bfaa5d480b949ab988a5efb62d/pkg/api/vlabs/validate.go#L1261-L1269

**Comment by jackfrancis** [comment]
Is this issue still a priority?

**Comment by bridgetkromhout** [comment]
Per @jsturtevant this is largely implemented; we won't pursue iterative improvements, given the AKS Engine deprecation.
