### ISSUE TITLE
Cannot regen certificates.

### ISSUE THREAD

**Issue by CodeInnovator** [Azure/aks-engine#3724]
**Describe the bug**
Our certificates were expired about a couple of days ago so tried to regen certificate by running the command and was getting `Error: listing cluster nodes: failed to get cluster nodes: Get "https://xxxxx.cloudapp.azure.com/api/v1/nodes": x509: certificate has expired or is not yet valid: current time 2020-08-17T17:34:47-07:00 is after 2020-08-15T16:39:40Z`.
Is this supposed to be not able to regen the certificates after it is expired? Or this should regen the certs?
If not, what would be the best way of updating the certificates? Our cluster was deployed using acs-engine. Sorry if I'm raising the bug that isn't really a bug but I'm fairly new to aks-engine and Kubernetes and no answer could be found for the issue I'm having(the person who developed our infrastructure is not reachable).

**Steps To Reproduce**
I ran `aks-engine rotate-certs --api-model {path to apimodel.json} -- auth-method=device  --location canadacentral --apiserver {url to the main cluter url} -g {resource group name}  -o {_output/staging}`
and I was getting `Error: listing cluster nodes: failed to get cluster nodes: Get "https://xxxxx.cloudapp.azure.com/api/v1/nodes": x509: certificate has expired or is not yet valid: current time 2020-08-17T17:34:47-07:00 is after 2020-08-15T16:39:40Z`

**Expected behavior**
Regen the certificates.

**AKS Engine version**
v0.54.0

**Kubernetes version**
v1.1.0
**Additional context**

**Comment by jackfrancis** [comment]
Hi @CodeInnovator, there probably isn't an aks-engine-specific solution for this scenario. Your best bet to recover this cluster (existing container images should continue to run on the nodes until they exit) is to manually update the CA and certs on all master VMs and control plane VMs.

If that sounds too tedious, building a new cluster, installing workloads, and switching traffic would work, though that's obviously manual at a higher abstraction level.

**Comment by CecileRobertMichon** [comment]
+1 to what @jackfrancis said above, the rotate-certs command is not expected to work in scenarios where certs have already expired: https://github.com/Azure/aks-engine/blob/master/docs/topics/certificaterotation.md#known-limitations

**Comment by jackfrancis** [comment]
@CodeInnovator were you able to manually remediate?
