### ISSUE TITLE
Failed to resize OS disk

### ISSUE THREAD

**Issue by wumingcp** [Azure/aks-engine#3734]
**Describe the bug**
Currently, we use Standard_DS13_V2 as the size for our worker nodes, and we also set OS disk size to 288G in VMSS, but we find some nodes doesn't meet our expection, which means the OS disk size for some nodes is only 30G

![image](https://user-images.githubusercontent.com/11804619/90873936-7e02bc80-e3d1-11ea-9b4f-7f91a44ce84c.png)

In the Disk Management, there are unallocated 258G space
![image](https://user-images.githubusercontent.com/11804619/90874084-be623a80-e3d1-11ea-8df5-7913637aa484.png)
 
Check the log, this is caused by that the script [kuberneteswindowssetup.ps1](https://github.com/Azure/aks-engine/blob/master/parts/k8s/kuberneteswindowssetup.ps1#L246) fails to resize OS disk
![image](https://user-images.githubusercontent.com/11804619/90874154-e3ef4400-e3d1-11ea-855a-786423b1d9be.png)

**Steps To Reproduce**

This is a corner case, you may repro it by scaling up some nodes

**Expected behavior**
The OS size should always be 288G for all worker nodes

**AKS Engine version**
v0.40.0
https://github.com/Azure/aks-engine/releases/download/v0.40.0/aks-engine-v0.40.0-windows-amd64.zip

**Kubernetes version**
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by devigned** [comment]
@wumingcp thank you for the awesome issue write up!

**Comment by jackfrancis** [comment]
Hi @wumingcp, thanks for your patience. It sounds like you modified the OS disk configuration on the VMSS directly. @marosset does that sound like something that would confuse the powershell bootstrap scripts when VMSS scale events happen subsequently?

**Comment by marosset** [comment]
@wumingcp can you confirm if the 288Gb size is set manually through ARM api calls/azure portal or if it is getting set with [agentProfile](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#agentpoolprofiles).osDiskSizeGB

Also can you guess how often this is happening?
I have not encountered the errors you are describing before.

**Comment by wumingcp** [comment]
@marosset We don't set the "agentProfile.osDiskSizeGB", but we set "storageProfile.osDisk.diskSizeGB" to 288G

And this issue will happen for each week because we scale frequently

For now, we can workaround this issue to re-run the function `Resize-OSDrive` after restarting, and it will wrok fine for the second run
