### ISSUE TITLE
terminationGracePeriodSeconds default value is 45 second

### ISSUE THREAD

**Issue by ArenHarut** [Azure/aks-engine#3735]
We have noticed that after applying deployment kubernetes sets terminationGracePeriodSeconds default value to 45 seconds in one of the deployments, all deployments are applied without specifying terminationGracePeriodSeconds parameter and after roll out it should set default value to 30 seconds, but in only one it sets 45 seconds. Cluster is in Azure AKS version 1.15.11 enter image description here. Does any one experience or noticed such behavior. I have tried to search but couldn't find any article related to this.
![image](https://user-images.githubusercontent.com/60018498/90893219-a689b700-e3cf-11ea-8327-6a375dca52c8.png)

**Comment by ArenHarut** [comment]
@mboersma sure I will move this to the repo you mentioned. Thanks

**Comment by jackfrancis** [comment]
@ArenHarut feel free to reference an AKS issue if you open one in a comment here so any other AKS users curious about the same thing can find the canonical issue if they search the AKS Engine issue queue

**Comment by ArenHarut** [comment]
https://github.com/Azure/AKS/issues/1821
