### ISSUE TITLE
Upgrade has a Timeout of 3 hrs

### ISSUE THREAD

**Issue by surajrana93** [Azure/aks-engine#3746]
**Describe the bug**
Aks Engine upgrade comes to a sudden stop  on reaching 3 hrs mark.

**Steps To Reproduce**
Run Upgrade for around 3 hrs. For me it was a cluster with 3 Masters and 20 Nodes

**Expected behavior**
The timeout should be configurable or adjusted a bit higher, as because of another issue (https://github.com/Azure/aks-engine/issues/3520) we are hitting the 3 hr limit for 20 Nodes. 

**AKS Engine version**
v0.54.0

**Kubernetes version**
15
**Additional context**
If possible look into #3520 bug as that is whats contributing to the Timeout. Simply restarting Upgrade will not work for our usecase as we are doing Force Upgrades.

**Comment by devigned** [comment]
For most cases, 3 hrs would be much too long and would be better to fail earlier. I'd vote for making timeout configurable.

**Comment by jackfrancis** [comment]
Ref:

https://github.com/Azure/aks-engine/blob/master/pkg/operations/kubernetesupgrade/upgrader.go#L52

Consumed by the upgrade process here:

https://github.com/Azure/aks-engine/blob/master/pkg/operations/kubernetesupgrade/upgrader.go#L78

To be clear, the timeout is (as currently implemented) actually enforced twice:

- allow up to 3 hours to upgrade control plane nodes, plus:
- allow up to 3 hours to upgrade all nodes

Does that match your experience @surajrana93 ?

**Comment by surajrana93** [comment]
@jackfrancis 
Yeah. It failed around 3 hrs on the overall process.

**Comment by devigned** [comment]
@jackfrancis, thank you for the code references and explanation. Perhaps, that will make this issue more accessible for folks looking to contribute back the project.

@surajrana93, any interest in working on a patch? We are happy to help.
