### ISSUE TITLE
Migrate all container images to MCR

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3753]
AKS Engine currently refers to these dockerhub-hosted images in VHD CI:

- microsoft/virtual-kubelet
- registry

And currently delivers these dockerhub-hosted images via addons:

- calico/typha:v3.8.0
- calico/cni:v3.8.0
- calico/node:v3.8.0
- calico/pod2daemon-flexvol:v3.8.0
- docker.io/cilium/cilium:v1.4
- docker.io/cilium/cilium-init:2018-10-16
- docker.io/cilium/operator:v1.4
- docker.io/cilium/cilium-etcd-operator:v2.0.5
- antrea/antrea-ubuntu:v0.6.0
- microsoft/virtual-kubelet

**Comment by sozercan** [comment]
These should be available in MCR today:

```
calico/typha:v3.8.0
calico/cni:v3.8.0
calico/node:v3.8.0
calico/pod2daemon-flexvol:v3.8.0
microsoft/virtual-kubelet
```

**Comment by jackfrancis** [comment]
@jadarsie does Azure Stack still need the registry container image? As long as Azure Stack users always use the curated VHD they should be calling to dockerhub.

But if the need is still there, is there a plan to put it into MCR?

**Comment by jackfrancis** [comment]
Closing this for now, as all blessed configurations now have dependent container images hosted in MCR.

**Comment by jadarsie** [comment]
fyi @rjaini

**Comment by rjaini** [comment]
@jackfrancis : As of now we still need the registry image in the VHD for disconnected case. Let me check and discuss once again with Azure Stack PM and get back to you. After then we can decide if we need to move the image to MCR or not.
