### ISSUE TITLE
There is no way to produce AD token that is valid for the API

### ISSUE THREAD

**Issue by omerlh** [Azure/aks-engine#376]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature Request
 
---

**What version of acs-engine?**: v0.24.3

---

When working on authenticating users to the dashboard, I tried to leverage [Azure WebApp built-in authentication](https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-overview) feature. I create an AAD app and grant it permissions to Kubernetes's app. I was able to get a valid token, and tried to passed it to the dashboard - but this results in `Unauthorized`response from Kubernetes. When looking on api server logs, I find the following line:
```
expected audience "spn:<>" got ["<>"]
```
After reading ACS engine code, I find that Kubernetes is initialized with `--oidc-client-id` in the format `spn:<server app id>` (see this [line](https://github.com/Azure/acs-engine/blob/64322ffbc9b02dc2bdd8924d997cd6eda34aeafc/pkg/api/defaults-apiserver.go#L72)). This means that for a token to be valid, the `aud` must also be in the same format - e.g. `spn:<server app id>`. Why is the `spn` added? Not all clients can add it (see this issue for example AzureAD/azure-activedirectory-library-for-nodejs#128). For example, Azure WebApp AAD authentication creates a token without the SPN. I opened a support ticket about it (118110525001477), but I'm not sure this is something they can change - and it means we need to write authentication code ourselves, instead of using WebApp mechanism.
Can we remove the `spn` safely from the configuration?

**Comment by mpalumbo7** [comment]
I'm having this issue with kubeapps and the keycloak-gatekeeper on [#975](https://github.com/kubeapps/kubeapps/issues/975) API server wants `aud: spn:{clientId}` but tokens have `aud:{clientId}`.

**Comment by AMoghrabi** [comment]
Hey @mpalumbo7 -- Did you solve this by any chance? I'm also using keycloak and can't figure out a solution. I get the following error:

```
[invalid bearer token, oidc: verify token: oidc: expected audience "spn:eclient_id" got ["client_id"]]
```

**Comment by mpalumbo7** [comment]
Sorry, I did not continue working on this item for long after this post. One another project, I was bitten by Kubernetes/kubernetes#86410 mentioned above. 

Sorry, I can’t remember too much about it now.

**Comment by AMoghrabi** [comment]
Ah ok, not a problem. Thanks for taking the time out of your day to respond. I appreciate it.
