### ISSUE TITLE
roleAssignments step for user assigned identity is not dependent on creation of user assigned indentity.

### ISSUE THREAD

**Issue by jikuma** [Azure/aks-engine#3761]
I am using aks engine version 'Version: v0.53.0'. I am using user assigned identity instead of service principal. In the template generated role assignment is not dependent on identity creation. Making template flaky.  

**Steps To Reproduce**
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.18",
      "orchestratorVersion": "1.18.4",
      "kubernetesConfig": {
        "kubernetesImageBase": "mcr.microsoft.com/",
        "kubernetesImageBaseType": "mcr",
        "mcrKubernetesImageBase": "mcr.microsoft.com/",
        "clusterSubnet": "10.240.0.0/12",
        "dnsServiceIP": "10.0.0.10",
        "serviceCidr": "10.0.0.0/16",
        "networkPlugin": "azure",
        "containerRuntime": "docker",
        "dockerBridgeSubnet": "172.17.0.1/16",
        "useManagedIdentity": true,
        "userAssignedID": "kubernetesmanagedidentity",
        "mobyVersion": "3.0.13",
        "useInstanceMetadata": true,
        "enableRbac": true,
        "enableSecureKubelet": true,
        "enableAggregatedAPIs": true,
        "privateCluster": {
          "enabled": false
        },
        "gchighthreshold": 85,
        "gclowthreshold": 80,
        "etcdVersion": "3.3.22",
        "etcdDiskSizeGB": "512",
        "addons": [
          {
            "name": "tiller",
            "enabled": false
          },
          {
            "name": "aci-connector",
            "enabled": false
          },
          {
            "name": "cluster-autoscaler",
            "enabled": false
          },
          {
            "name": "blobfuse-flexvolume",
            "enabled": true,
            "containers": [
              {
                "name": "blobfuse-flexvolume",
                "image": "mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume:1.0.8",
                "cpuRequests": "50m",
                "memoryRequests": "100Mi",
                "cpuLimits": "50m",
                "memoryLimits": "100Mi"
              }
            ]
          },
          {
            "name": "smb-flexvolume",
            "enabled": false
          },
          {
            "name": "keyvault-flexvolume",
            "enabled": false
          },
          {
            "name": "kubernetes-dashboard",
            "enabled": false
          },
          {
            "name": "rescheduler",
            "enabled": false
          },
          {
            "name": "metrics-server",
            "enabled": true,
            "mode": "Reconcile",
            "containers": [
              {
                "name": "metrics-server",
                "image": "mcr.microsoft.com/oss/kubernetes/metrics-server:v0.3.6"
              }
            ]
          },
          {
            "name": "nvidia-device-plugin",
            "enabled": false
          },
          {
            "name": "container-monitoring",
            "enabled": false
          },
          {
            "name": "azure-cni-networkmonitor",
            "enabled": true,
            "containers": [
              {
                "name": "azure-cni-networkmonitor",
                "image": "mcr.microsoft.com/containernetworking/networkmonitor:v0.0.8",
                "cpuRequests": "30m",
                "memoryRequests": "25Mi",
                "cpuLimits": "200m",
                "memoryLimits": "256Mi"
              }
            ]
          },
          {
            "name": "azure-npm-daemonset",
            "enabled": false
          },
          {
            "name": "cloud-node-manager",
            "enabled": false
          },
          {
            "name": "ip-masq-agent",
            "enabled": true,
            "containers": [
              {
                "name": "ip-masq-agent",
                "image": "mcr.microsoft.com/oss/kubernetes/ip-masq-agent:v2.5.0",
                "cpuRequests": "50m",
                "memoryRequests": "50Mi",
                "cpuLimits": "50m",
                "memoryLimits": "250Mi"
              }
            ],
            "config": {
              "enable-ipv6": "false",
              "non-masq-cni-cidr": "168.63.129.16/32",
              "non-masquerade-cidr": "10.0.240.0/20",
              "secondary-non-masquerade-cidr": ""
            }
          },
          {
            "name": "calico-daemonset",
            "enabled": false
          },
          {
            "name": "cilium",
            "enabled": false
          },
          {
            "name": "aad-pod-identity",
            "enabled": false
          },
          {
            "name": "appgw-ingress",
            "enabled": false
          },
          {
            "name": "azuredisk-csi-driver",
            "enabled": false
          },
          {
            "name": "azurefile-csi-driver",
            "enabled": false
          },
          {
            "name": "azure-policy",
            "enabled": false
          },
          {
            "name": "node-problem-detector",
            "enabled": false
          },
          {
            "name": "kube-dns",
            "enabled": false
          },
          {
            "name": "coredns",
            "enabled": true,
            "containers": [
              {
                "name": "coredns",
                "image": "mcr.microsoft.com/oss/kubernetes/coredns:1.6.9"
              },
              {
                "name": "coredns-autoscaler",
                "image": "mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-proportional-autoscaler:1.7.1"
              }
            ],
            "config": {
              "clusterIP": "10.0.0.10",
              "cores-per-replica": "512",
              "domain": "cluster.local",
              "min-replicas": "1",
              "nodes-per-replica": "32"
            }
          },
          {
            "name": "kube-proxy",
            "enabled": true,
            "containers": [
              {
                "name": "kube-proxy",
                "image": "mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.18.4"
              }
            ],
            "config": {
              "cluster-cidr": "10.240.0.0/12",
              "featureGates": "{}",
              "proxy-mode": "iptables"
            }
          },
          {
            "name": "pod-security-policy",
            "enabled": true
          },
          {
            "name": "audit-policy",
            "enabled": true
          },
          {
            "name": "azure-cloud-provider",
            "enabled": true
          },
          {
            "name": "aad",
            "enabled": false
          },
          {
            "name": "antrea",
            "enabled": false
          },
          {
            "name": "flannel",
            "enabled": false
          },
          {
            "name": "scheduled-maintenance",
            "enabled": false
          },
          {
            "name": "csi-secrets-store",
            "enabled": true,
            "containers": [
              {
                "name": "livenessprobe",
                "image": "mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v1.1.0",
                "cpuRequests": "10m",
                "memoryRequests": "20Mi",
                "cpuLimits": "200m",
                "memoryLimits": "200Mi"
              },
              {
                "name": "csi-node-driver-registrar",
                "image": "mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v1.2.0",
                "cpuRequests": "10m",
                "memoryRequests": "20Mi",
                "cpuLimits": "200m",
                "memoryLimits": "200Mi"
              },
              {
                "name": "secrets-store",
                "image": "mcr.microsoft.com/k8s/csi/secrets-store/driver:v0.0.11",
                "cpuRequests": "50m",
                "memoryRequests": "100Mi",
                "cpuLimits": "200m",
                "memoryLimits": "200Mi"
              },
              {
                "name": "provider-azure-installer",
                "image": "mcr.microsoft.com/k8s/csi/secrets-store/provider-azure:0.0.6",
                "cpuRequests": "50m",
                "memoryRequests": "100Mi",
                "cpuLimits": "200m",
                "memoryLimits": "200Mi"
              }
            ]
          }
        ],
        "components": [
          {
            "name": "kube-scheduler",
            "enabled": true,
            "containers": [
              {
                "name": "kube-scheduler",
                "image": "mcr.microsoft.com/oss/kubernetes/kube-scheduler:v1.18.4"
              }
            ],
            "config": {
              "command": "\"kube-scheduler\""
            }
          },
          {
            "name": "kube-controller-manager",
            "enabled": true,
            "containers": [
              {
                "name": "kube-controller-manager",
                "image": "mcr.microsoft.com/oss/kubernetes/kube-controller-manager:v1.18.4"
              }
            ],
            "config": {
              "command": "\"kube-controller-manager\""
            }
          },
          {
            "name": "cloud-controller-manager",
            "enabled": false
          },
          {
            "name": "kube-apiserver",
            "enabled": true,
            "containers": [
              {
                "name": "kube-apiserver",
                "image": "mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.18.4"
              }
            ],
            "config": {
              "command": "\"kube-apiserver\""
            }
          },
          {
            "name": "kube-addon-manager",
            "enabled": true,
            "containers": [
              {
                "name": "kube-addon-manager",
                "image": "mcr.microsoft.com/oss/kubernetes/kube-addon-manager:v9.1.1"
              }
            ]
          }
        ],
        "kubeletConfig": {
          "--address": "0.0.0.0",
          "--anonymous-auth": "false",
          "--authentication-token-webhook": "true",
          "--authorization-mode": "Webhook",
          "--azure-container-registry-config": "/etc/kubernetes/azure.json",
          "--cgroups-per-qos": "true",
          "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--cluster-dns": "10.0.0.10",
          "--cluster-domain": "cluster.local",
          "--enforce-node-allocatable": "pods",
          "--event-qps": "0",
          "--eviction-hard": "memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%",
          "--feature-gates": "RotateKubeletServerCertificate=true",
          "--image-gc-high-threshold": "85",
          "--image-gc-low-threshold": "80",
          "--image-pull-progress-deadline": "30m",
          "--keep-terminated-pod-volumes": "false",
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--max-pods": "30",
          "--network-plugin": "cni",
          "--node-status-update-frequency": "10s",
          "--non-masquerade-cidr": "0.0.0.0/0",
          "--pod-infra-container-image": "mcr.microsoft.com/oss/kubernetes/pause:1.4.0",
          "--pod-manifest-path": "/etc/kubernetes/manifests",
          "--pod-max-pids": "-1",
          "--read-only-port": "0",
          "--rotate-certificates": "true",
          "--streaming-connection-idle-timeout": "4h",
          "--tls-cert-file": "/etc/kubernetes/certs/kubeletserver.crt",
          "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256",
          "--tls-private-key-file": "/etc/kubernetes/certs/kubeletserver.key",
          "--v": "2",
          "--volume-plugin-dir": "/etc/kubernetes/volumeplugins"
        },
        "controllerManagerConfig": {
          "--allocate-node-cidrs": "false",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--cluster-cidr": "10.240.0.0/12",
          "--cluster-name": "dnsPrefix",
          "--cluster-signing-cert-file": "/etc/kubernetes/certs/ca.crt",
          "--cluster-signing-key-file": "/etc/kubernetes/certs/ca.key",
          "--configure-cloud-routes": "false",
          "--controllers": "*,bootstrapsigner,tokencleaner",
          "--feature-gates": "LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true",
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--leader-elect": "true",
          "--node-monitor-grace-period": "40s",
          "--pod-eviction-timeout": "5m0s",
          "--profiling": "false",
          "--root-ca-file": "/etc/kubernetes/certs/ca.crt",
          "--route-reconciliation-period": "10s",
          "--service-account-private-key-file": "/etc/kubernetes/certs/apiserver.key",
          "--terminated-pod-gc-threshold": "5000",
          "--use-service-account-credentials": "true",
          "--v": "2"
        },
        "cloudControllerManagerConfig": {
          "--allocate-node-cidrs": "false",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--cluster-cidr": "10.240.0.0/12",
          "--cluster-name": "dnsPrefix",
          "--configure-cloud-routes": "false",
          "--controllers": "*,-cloud-node",
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--leader-elect": "true",
          "--route-reconciliation-period": "10s",
          "--v": "2"
        },
        "apiServerConfig": {
          "--advertise-address": "<advertiseAddr>",
          "--allow-privileged": "true",
          "--anonymous-auth": "false",
          "--audit-log-maxage": "30",
          "--audit-log-maxbackup": "10",
          "--audit-log-maxsize": "100",
          "--audit-log-path": "/var/log/kubeaudit/audit.log",
          "--audit-policy-file": "/etc/kubernetes/addons/audit-policy.yaml",
          "--authorization-mode": "Node,RBAC",
          "--bind-address": "0.0.0.0",
          "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration,PodSecurityPolicy",
          "--enable-bootstrap-token-auth": "true",
          "--etcd-cafile": "/etc/kubernetes/certs/ca.crt",
          "--etcd-certfile": "/etc/kubernetes/certs/etcdclient.crt",
          "--etcd-keyfile": "/etc/kubernetes/certs/etcdclient.key",
          "--etcd-servers": "https://127.0.0.1:2379",
          "--insecure-port": "0",
          "--kubelet-client-certificate": "/etc/kubernetes/certs/client.crt",
          "--kubelet-client-key": "/etc/kubernetes/certs/client.key",
          "--profiling": "false",
          "--proxy-client-cert-file": "/etc/kubernetes/certs/proxy.crt",
          "--proxy-client-key-file": "/etc/kubernetes/certs/proxy.key",
          "--requestheader-allowed-names": "",
          "--requestheader-client-ca-file": "/etc/kubernetes/certs/proxy-ca.crt",
          "--requestheader-extra-headers-prefix": "X-Remote-Extra-",
          "--requestheader-group-headers": "X-Remote-Group",
          "--requestheader-username-headers": "X-Remote-User",
          "--secure-port": "443",
          "--service-account-key-file": "/etc/kubernetes/certs/apiserver.key",
          "--service-account-lookup": "true",
          "--service-cluster-ip-range": "10.0.0.0/16",
          "--storage-backend": "etcd3",
          "--tls-cert-file": "/etc/kubernetes/certs/apiserver.crt",
          "--tls-cipher-suites": "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
          "--tls-private-key-file": "/etc/kubernetes/certs/apiserver.key",
          "--v": "4"
        },
        "schedulerConfig": {
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--leader-elect": "true",
          "--profiling": "false",
          "--v": "2"
        },
        "cloudProviderBackoffMode": "v2",
        "cloudProviderBackoff": true,
        "cloudProviderBackoffRetries": 6,
        "cloudProviderBackoffDuration": 5,
        "cloudProviderRateLimit": true,
        "cloudProviderRateLimitQPS": 20,
        "cloudProviderRateLimitQPSWrite": 20,
        "cloudProviderRateLimitBucket": 200,
        "cloudProviderRateLimitBucketWrite": 200,
        "cloudProviderDisableOutboundSNAT": false,
        "loadBalancerSku": "Standard",
        "excludeMasterFromStandardLB": true,
        "azureCNIVersion": "v1.1.3",
        "maximumLoadBalancerRuleCount": 250,
        "kubeProxyMode": "iptables",
        "outboundRuleIdleTimeoutInMinutes": 30
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "dnsPrefix",
      "subjectAltNames": null,
      "vmSize": "---mastervmsize---",
      "osDiskSizeGB": 256,
      "vnetSubnetID": "/subscriptions/vnetsubscriptionId/resourceGroups/vnetresourceGroups/providers/Microsoft.Network/virtualNetworks/vnetname/subnets/subnetname",
      "vnetCidr": "10.0.240.0/20",
      "firstConsecutiveStaticIP": "10.0.255.239",
      "storageProfile": "ManagedDisks",
      "oauthEnabled": false,
      "preProvisionExtension": null,
      "extensions": [],
      "distro": "aks-ubuntu-18.04",
      "kubernetesConfig": {
        "kubeletConfig": {
          "--address": "0.0.0.0",
          "--anonymous-auth": "false",
          "--authentication-token-webhook": "true",
          "--authorization-mode": "Webhook",
          "--azure-container-registry-config": "/etc/kubernetes/azure.json",
          "--cgroups-per-qos": "true",
          "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
          "--cloud-config": "/etc/kubernetes/azure.json",
          "--cloud-provider": "azure",
          "--cluster-dns": "10.0.0.10",
          "--cluster-domain": "cluster.local",
          "--enforce-node-allocatable": "pods",
          "--event-qps": "0",
          "--eviction-hard": "memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%",
          "--feature-gates": "RotateKubeletServerCertificate=true",
          "--image-gc-high-threshold": "85",
          "--image-gc-low-threshold": "80",
          "--image-pull-progress-deadline": "30m",
          "--keep-terminated-pod-volumes": "false",
          "--kubeconfig": "/var/lib/kubelet/kubeconfig",
          "--max-pods": "30",
          "--network-plugin": "cni",
          "--node-status-update-frequency": "10s",
          "--non-masquerade-cidr": "0.0.0.0/0",
          "--pod-infra-container-image": "mcr.microsoft.com/oss/kubernetes/pause:1.4.0",
          "--pod-manifest-path": "/etc/kubernetes/manifests",
          "--pod-max-pids": "-1",
          "--protect-kernel-defaults": "true",
          "--read-only-port": "0",
          "--register-with-taints": "node-role.kubernetes.io/master=true:NoSchedule",
          "--resolv-conf": "/run/systemd/resolve/resolv.conf",
          "--rotate-certificates": "true",
          "--streaming-connection-idle-timeout": "4h",
          "--tls-cert-file": "/etc/kubernetes/certs/kubeletserver.crt",
          "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256",
          "--tls-private-key-file": "/etc/kubernetes/certs/kubeletserver.key",
          "--v": "2",
          "--volume-plugin-dir": "/etc/kubernetes/volumeplugins"
        },
        "cloudProviderBackoffMode": ""
      },
      "availabilityProfile": "AvailabilitySet",
      "availabilityZones": [
        "---kubernetesAvabilityzone1---",
        "---kubernetesAvabilityzone2---",
        "---kubernetesAvabilityzone3---"
      ],
      "platformUpdateDomainCount": 3,
      "sysctldConfig": {
        "net.core.message_burst": "80",
        "net.core.message_cost": "40",
        "net.core.somaxconn": "16384",
        "net.ipv4.neigh.default.gc_thresh1": "4096",
        "net.ipv4.neigh.default.gc_thresh2": "8192",
        "net.ipv4.neigh.default.gc_thresh3": "16384",
        "net.ipv4.tcp_max_syn_backlog": "16384",
        "net.ipv4.tcp_retries2": "8"
      },
      "cosmosEtcd": false,
      "osDiskCachingType": "ReadWrite"
    },
    "agentPoolProfiles": [
      {
        "name": "registry",
        "count": 3,
        "vmSize": "---registryagentpoolvmsize---",
        "osType": "Linux",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "vnetSubnetID": "/subscriptions/vnetsubscriptionId/resourceGroups/vnetresourceGroups/providers/Microsoft.Network/virtualNetworks/vnetname/subnets/subnetname",
        "distro": "aks-ubuntu-18.04",
        "kubernetesConfig": {
          "kubeletConfig": {
            "--address": "0.0.0.0",
            "--anonymous-auth": "false",
            "--authentication-token-webhook": "true",
            "--authorization-mode": "Webhook",
            "--azure-container-registry-config": "/etc/kubernetes/azure.json",
            "--cgroups-per-qos": "true",
            "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
            "--cloud-config": "/etc/kubernetes/azure.json",
            "--cloud-provider": "azure",
            "--cluster-dns": "10.0.0.10",
            "--cluster-domain": "cluster.local",
            "--enforce-node-allocatable": "pods",
            "--event-qps": "0",
            "--eviction-hard": "memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%",
            "--feature-gates": "RotateKubeletServerCertificate=true",
            "--image-gc-high-threshold": "85",
            "--image-gc-low-threshold": "80",
            "--image-pull-progress-deadline": "30m",
            "--keep-terminated-pod-volumes": "false",
            "--kubeconfig": "/var/lib/kubelet/kubeconfig",
            "--max-pods": "30",
            "--network-plugin": "cni",
            "--node-status-update-frequency": "10s",
            "--non-masquerade-cidr": "0.0.0.0/0",
            "--pod-infra-container-image": "mcr.microsoft.com/oss/kubernetes/pause:1.4.0",
            "--pod-manifest-path": "/etc/kubernetes/manifests",
            "--pod-max-pids": "-1",
            "--protect-kernel-defaults": "true",
            "--read-only-port": "0",
            "--resolv-conf": "/run/systemd/resolve/resolv.conf",
            "--rotate-certificates": "true",
            "--streaming-connection-idle-timeout": "4h",
            "--tls-cert-file": "/etc/kubernetes/certs/kubeletserver.crt",
            "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256",
            "--tls-private-key-file": "/etc/kubernetes/certs/kubeletserver.key",
            "--v": "2",
            "--volume-plugin-dir": "/etc/kubernetes/volumeplugins"
          },
          "cloudProviderBackoffMode": ""
        },
        "acceleratedNetworkingEnabled": false,
        "acceleratedNetworkingEnabledWindows": false,
        "vmssOverProvisioningEnabled": false,
        "auditDEnabled": false,
        "fqdn": "",
        "customNodeLabels": {
          "acr.net/role": "registry"
        },
        "preProvisionExtension": null,
        "extensions": [],
        "singlePlacementGroup": false,
        "platformUpdateDomainCount": 3,
        "availabilityZones": [
          "---kubernetesAvabilityzone1---",
          "---kubernetesAvabilityzone2---",
          "---kubernetesAvabilityzone3---"
        ],
        "enableVMSSNodePublicIP": false,
        "sysctldConfig": {
          "net.core.message_burst": "80",
          "net.core.message_cost": "40",
          "net.core.somaxconn": "16384",
          "net.ipv4.neigh.default.gc_thresh1": "4096",
          "net.ipv4.neigh.default.gc_thresh2": "8192",
          "net.ipv4.neigh.default.gc_thresh3": "16384",
          "net.ipv4.tcp_max_syn_backlog": "16384",
          "net.ipv4.tcp_retries2": "8"
        },
        "osDiskCachingType": "ReadWrite",
        "dataDiskCachingType": "ReadOnly"
      },
      {
        "name": "redis",
        "count": 3,
        "vmSize": "---redisagentpoolvmsize---",
        "osType": "Linux",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "vnetSubnetID": "/subscriptions/vnetsubscriptionId/resourceGroups/vnetresourceGroups/providers/Microsoft.Network/virtualNetworks/vnetname/subnets/subnetname",
        "distro": "aks-ubuntu-18.04",
        "kubernetesConfig": {
          "kubeletConfig": {
            "--address": "0.0.0.0",
            "--anonymous-auth": "false",
            "--authentication-token-webhook": "true",
            "--authorization-mode": "Webhook",
            "--azure-container-registry-config": "/etc/kubernetes/azure.json",
            "--cgroups-per-qos": "true",
            "--client-ca-file": "/etc/kubernetes/certs/ca.crt",
            "--cloud-config": "/etc/kubernetes/azure.json",
            "--cloud-provider": "azure",
            "--cluster-dns": "10.0.0.10",
            "--cluster-domain": "cluster.local",
            "--enforce-node-allocatable": "pods",
            "--event-qps": "0",
            "--eviction-hard": "memory.available<750Mi,nodefs.available<10%,nodefs.inodesFree<5%",
            "--feature-gates": "RotateKubeletServerCertificate=true",
            "--image-gc-high-threshold": "85",
            "--image-gc-low-threshold": "80",
            "--image-pull-progress-deadline": "30m",
            "--keep-terminated-pod-volumes": "false",
            "--kubeconfig": "/var/lib/kubelet/kubeconfig",
            "--max-pods": "30",
            "--network-plugin": "cni",
            "--node-status-update-frequency": "10s",
            "--non-masquerade-cidr": "0.0.0.0/0",
            "--pod-infra-container-image": "mcr.microsoft.com/oss/kubernetes/pause:1.4.0",
            "--pod-manifest-path": "/etc/kubernetes/manifests",
            "--pod-max-pids": "-1",
            "--protect-kernel-defaults": "true",
            "--read-only-port": "0",
            "--resolv-conf": "/run/systemd/resolve/resolv.conf",
            "--rotate-certificates": "true",
            "--streaming-connection-idle-timeout": "4h",
            "--tls-cert-file": "/etc/kubernetes/certs/kubeletserver.crt",
            "--tls-cipher-suites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256",
            "--tls-private-key-file": "/etc/kubernetes/certs/kubeletserver.key",
            "--v": "2",
            "--volume-plugin-dir": "/etc/kubernetes/volumeplugins"
          },
          "cloudProviderBackoffMode": ""
        },
        "acceleratedNetworkingEnabled": false,
        "acceleratedNetworkingEnabledWindows": false,
        "vmssOverProvisioningEnabled": false,
        "auditDEnabled": false,
        "fqdn": "",
        "customNodeLabels": {
          "acr.net/role": "redis"
        },
        "preProvisionExtension": null,
        "extensions": [],
        "singlePlacementGroup": false,
        "platformUpdateDomainCount": 3,
        "availabilityZones": [
          "---kubernetesAvabilityzone1---",
          "---kubernetesAvabilityzone2---",
          "---kubernetesAvabilityzone3---"
        ],
        "enableVMSSNodePublicIP": false,
        "sysctldConfig": {
          "net.core.message_burst": "80",
          "net.core.message_cost": "40",
          "net.core.somaxconn": "16384",
          "net.ipv4.neigh.default.gc_thresh1": "4096",
          "net.ipv4.neigh.default.gc_thresh2": "8192",
          "net.ipv4.neigh.default.gc_thresh3": "16384",
          "net.ipv4.tcp_max_syn_backlog": "16384",
          "net.ipv4.tcp_retries2": "8"
        },
        "osDiskCachingType": "ReadWrite",
        "dataDiskCachingType": "ReadOnly"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "---publickey---"
          }
        ]
      }
    },
    "certificateProfile": {
      
      ]
    },
    "telemetryProfile": {}
  }
}

**Expected behavior**

The template should have below relation between resources 

        {
            "apiVersion": "[variables('apiVersionManagedIdentity')]",
            "location": "[variables('location')]",
            "name": "[variables('userAssignedID')]",
            "tags": null,
            "type": "Microsoft.ManagedIdentity/userAssignedIdentities"
        },
        {
            **"dependsOn": [
                "[variables('userAssignedIDReference')]"
            ],**
            "apiVersion": "[variables('apiVersionAuthorizationUser')]",
            "name": "[guid(concat(variables('userAssignedID'), 'roleAssignment', resourceGroup().id))]",
            "properties": {
                "principalId": "[reference(variables('userAssignedIDReference'), variables('apiVersionManagedIdentity')).principalId]",
                "principalType": "ServicePrincipal",
                "roleDefinitionId": "[variables('contributorRoleDefinitionId')]",
                "scope": "[resourceGroup().id]"
            },
            "type": "Microsoft.Authorization/roleAssignments"
        },

**AKS Engine version**
Version: v0.53.0
GitCommit: b1655d6cc
GitTreeState: clean

**Kubernetes version**
1.18
**Additional context**

**Comment by jackfrancis** [comment]
Hi @jikuma, are we sure we aren't running into the fact that aks-engine allows you to create a user assigned identity on the fly?
