### ISSUE TITLE
Availibility zone of virtualMachineScaleSets is specified directly in template file instead of reading from parameter file

### ISSUE THREAD

**Issue by jikuma** [Azure/aks-engine#3762]
**Describe the bug**

The value of the availability zone in the generated template file is directly specified and does not use parameters.

**Steps To Reproduce**

Create a Kubernetes cluster specifying the availability zone. 

e.g 

```json
"agentPoolProfiles": [
        {
          "name": "",
          "count": 3,
          "vmSize": "Standard_D2_v3",
          "vnetSubnetId": "",
          "availabilityZones": ["1","2", "3"],
        }
```

Generate template using 
```
aks-engine generate kubeconfig.json
```

Check the template resource section you and search for vmss. Check the availability zine value it will be fixed and not being read from the parameter.

```json
"zones": [
        "1",
        "2",
        "3"
      ]
```

**Expected behavior**

zones value should be read from parameter. 

```json
"zones": "[parameters('registryAvailabilityZones')]"
```

**AKS Engine version**

Version: v0.53.0
GitCommit: b1655d6cc
GitTreeState: clean

**Kubernetes version**

1.18

**Additional context**

**Comment by devigned** [comment]
Hi @jikuma, thank you for opening this issue and providing a great explanation of the enhancement. Since this is a relatively superficial change to aks-engine, I've added the `good first issue` and `help wanted` tags.

**Comment by manishram** [comment]
Hey @devigned , I'd love to be assigned for resolving this issue.

**Comment by manishram** [comment]
Hey @devigned , I'd love to be assigned for this issue. But since it will be my first contribution, assistance will be appreciated. Thanks

**Comment by devigned** [comment]
The aks-engine team would be delighted to help you contribute. Questions / discussions are easiest to chat about in https://slack.k8s.io #aks-engine-dev.

**Comment by jackfrancis** [comment]
@jikuma Hi there, just curious: what's the value of the output ARM template referring to the parameter instead of having the values directly? I agree that the current implementation is sloppy, but arguably the cleaner path forward is to just remove this unused parameter entirely. Is there any value keeping this value parameterized?

**Comment by jackfrancis** [comment]
For example, the three lines in this `if` statement can be removed:

https://github.com/Azure/aks-engine/blob/master/pkg/engine/params.go#L195

**Comment by jikuma** [comment]
@jackfrancis Yes there is lot of value in keeping the value in parameter. We generate a generic template and deploy the same template in every region using different parameters file. So you see if we fix the value in template file we will not be able to use same template in every region. 

@manishram thanks for your help in fixing this issue. Here is my private fix, if it helps https://github.com/Azure/aks-engine/commit/49d0d0e338dbe69aa9e303bacfb51bddc76269fd

**Comment by manishram** [comment]
@jikuma Thanks, sir. That was so welcoming.

**Comment by jackfrancis** [comment]
@jikuma that makes sense!

**Comment by manishram** [comment]
![r43r3](https://user-images.githubusercontent.com/22790904/91748882-4e785f00-ebde-11ea-89e5-58e2f6e976c8.PNG)

Is it the correct format for commit message?

**Comment by manishram** [comment]
![35t4](https://user-images.githubusercontent.com/22790904/91749065-913a3700-ebde-11ea-98d6-d182f97bd56c.PNG)

@jikuma  Is it the correct format for the commit message?
