### ISSUE TITLE
single stack IPv6 fails with 18.04 ubuntu image

### ISSUE THREAD

**Issue by aramase** [Azure/aks-engine#3776]
**Describe the bug**
With `18.04` ubuntu image, the `systemd-resolved` uses the port `:53` on the host and is being used by default for dns. This causes the coredns pods to crash for single stack IPv6 with `bind address already in use` as coredns pods are run on hostNetwork to leverage the host routes for dns resolution.

Steps for resolution -
- Update `/etc/systemd/resolv.conf` and set `DNSStubListener=no`
- `sudo mv /etc/resolv.conf /etc/resolv.conf.OLD && sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf`
- `systemctl restart systemd-resolved`

This frees up `:53` on the host and the coredns pods start running without errors.

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by jackfrancis** [comment]
Is there a definitive api model configuration that should engage the resolution steps provided?

**Comment by aramase** [comment]
I've added a sample api model as part of this PR - https://github.com/Azure/aks-engine/pull/3777/files. I've set the `distro: ubuntu` in the api model so users can try it out with `Ubuntu 16.04`. We can remove that after the fix is merged to aks-engine.
