### ISSUE TITLE
Add ability to set "storage-opts" : [ "size=XX" ] in windows daemon.json

### ISSUE THREAD

**Issue by rolnick** [Azure/aks-engine#3784]
Hi,

We are moving our compilation servers from bare metal to AKS clusters with windows machines.
We have big project, which for compilation needs at least 40 GB of space.
By default, docker for windows has "storage-opts" : [ "size=20" ]  = 20GB.
We do not need volumes, or i can say volumes are very slow on windows.

It would be nice to have this feature as some parameter.

Is there maybe other way to do it?

Regards,
rolnick

**Comment by chewong** [comment]
Hi @rolnick, as far as I know, I don't think there is an option in aks-engine to customize daemon.json. However, I think you could edit it by ssh-ing into your WIndows nodes and restart the docker service.

**Comment by rolnick** [comment]
Hi,
Will this change be applied to new node, which will be created with autoscaling?

**Comment by craiglpeters** [comment]
No it would not.

Can you confirm if this is an aks-engine cluster, or an AKS (the managed service) cluster?

**Comment by rolnick** [comment]
It's AKS unfortunately. Looks i need to search for help on AKS project.
