### ISSUE TITLE
Secrets store addon pulling from custom clouds 

### ISSUE THREAD

**Issue by jadarsie** [Azure/aks-engine#3786]
**Describe the request**

The `secrets-store-csi-driver` addon needs access to the custom cloud environment json in order to pull Key Vault secrets stored on custom clouds.

This file is currently unreachable to the addon as AKS Engine drops the json file in path `/etc/kubernetes/azurestackcloud.json` (see [current addon volumes](https://github.com/Azure/aks-engine/blob/v0.55.0/parts/k8s/addons/secrets-store-csi-driver.yaml#L395-L411))

So, I am thinking we could either (1, preferred IMO) mount `/etc/kubernetes` or (2) copy the environment json file to `/etc/kubernetes/secrets-store-csi-providers`.

@jackfrancis  / @aramase, what's your take?

**Additional context**

Related work: https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/220

**Comment by jackfrancis** [comment]
I prefer option 1: adding the additional mount

**Comment by aramase** [comment]
+1 for just mounting `/etc/kubernetes` in the driver instead of `/etc/kubernetes/secrets-store-csi-providers`
