### ISSUE TITLE
OutBoundNAT ExceptionList is only populated with the first entry from the list of Address Spaces of the VNET of the cluster

### ISSUE THREAD

**Issue by nboeckmann** [Azure/aks-engine#3789]
In situations where there are multiple address ranges defined for a VNET there's only the first CIDR taken into the OutBoundNAT exclusion list on Windows Nodes preventing the network communication with services that are in network ranges that are outside of the first CIDR exposed in pods running on the windows node pool.

*Workaround for two CIDR*
Have the CIDR that is not used as the node pool range as the first entry as the node pool range is always added as an exclusion

**Steps To Reproduce**
 - Create a VNET with at least two CIDRs
 - Provision the AKS into the first CIDR with a windows node pool
 - Deploy a pod hosting a website into the windows node pool
 - Provision an Application Gateway into the 2nd range
 - The Application Gateway is not able to reach services (i.e. a website) that is exposed from the windows pod

**Expected behavior**
- The Application Gateway is able to reach the service exposed by the windows pod.
- All CIDRs that are defined in the VNET that the AKS cluster is bound to are added to the ExceptionList of the OutBoundNAT on Windows nodes

**AKS Engine version**
v0.47.0-aks-gomod-a8-aks

**Kubernetes version**
1.18.6

**Additional context**
I believe that this assumption that is stated in the code is wrong and therefor it doesn't behave correct.

![problemInCode](https://user-images.githubusercontent.com/22768290/92198773-92d15c80-ee75-11ea-940a-68510e39c95b.png)

I can unfortunately not find that any longer (I detected the issue a while ago and still had the creation of the issue pending)

**Comment by CecileRobertMichon** [comment]
@nboeckmann are you using AKS or AKS Engine?

For AKS, please file an issue at https://github.com/Azure/AKS/issues

**Comment by CecileRobertMichon** [comment]
@AbelHu can you please take a look?

**Comment by nboeckmann** [comment]
> 
> 
> @nboeckmann are you using AKS or AKS Engine?
> 
> For AKS, please file an issue at https://github.com/Azure/AKS/issues

I'm on AKS. I'll log a bug there. Sorry!

**Comment by AbelHu** [comment]
@nboeckmann vnetCidr in aks-engine is not an array so only the first cidr is used. This should be changed to support multiple cidrs.
