### ISSUE TITLE
Azure Stack Hub - AKS Engine - AKS Base Ubuntu 16.04-LTS Image Distro, August 2020 - SKU Issue

### ISSUE THREAD

**Issue by dbrennand** [Azure/aks-engine#3791]
**Describe the bug**

With the new supported release of [AKS engine v0.55.0](https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#supported-aks-engine-versions). When attempting to deploy a Kubernetes cluster version 1.17.11 using AKS engine CLI version 0.55.0, the following error occurs:

```
ERRO[0025] error: failed to get virtual machine image, compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: '' error: EOF
ERRO[0025] Image Publisher: microsoft-aks, Offer: aks, SKU: aks-engine-ubuntu-1604-202007, Version: 2020.08.24
Error: validating OS base images required by ./kubernetes-azurestack.json: OS base image not available in target cloud: some VM images are missing on the target cloud
```

**Steps To Reproduce**

AKS engine deploy:
```bash
aks-engine deploy --azure-env AzureStackCloud --location {locationhere} --resource-group Kube-RG --api-model ./kubernetes-azurestack.json --output-directory cluster-config --client-id Redacted --client-secret Redacted  --subscription-id Redacted
```

API profile used attached. [kubernetes-azurestack.json.txt](https://github.com/Azure/aks-engine/files/5174792/kubernetes-azurestack.json.txt)

**Expected behavior**
AKS deploys the cluster with no errors.

**AKS Engine version**
0.55.0

**Kubernetes version**
1.17.11

**Additional context**

The base image the AKS engine CLI is searching for on the stamp is:

`ERRO[0025] Image Publisher: microsoft-aks, Offer: aks, SKU: aks-engine-ubuntu-1604-202007, Version: 2020.08.24`

However, it looks like there is an issue with the SKU. Upon inspection of the image the SKU for image version 2020.08.24 is:
```
DownloadName         : microsoft-aks.aksaks-ubuntu-1604-202007-2020.08.24
GalleryItemIdentity  : microsoft-aks.aksaks-ubuntu-1604-202007.1.0.8
DisplayName          : AKS Base Ubuntu 16.04-LTS Image Distro, August 2020
PublisherDisplayName : Azure Kubernetes Service
PublisherIdentifier  : microsoft-aks
Offer                : aks
OfferVersion         : 1.0.8
Sku                  : **aks-ubuntu-1604-201909**
SizeInMB             : 30721.05
SizeInGB             : 30
ProductVersionNumber : 2020.08.24
```

The actual image SKU for version ` 2020.08.24` is  `aks-ubuntu-1604-201909` and it doesn't look like it's `aks-engine-ubuntu-1604-202007` which the CLI is expecting.

**Comment by chewong** [comment]
@jadarsie could you help take a look?

**Comment by dbrennand** [comment]
Hey guys, the image 2020.08.24 (August 2020) is no longer available to add from Azure to the Azure Stack Hub marketplace.

**Comment by JesusAlvarezTorres** [comment]
@dbrennand I have a couple of follow up questions. 1. Which Azure region is your Azure Stack stamp connected to? and 2. When did you attempt to download the image? 

We had an issue in the publishing of the August 2020 image where it was published with the wrong sku (the aks-ubuntu-1604-201909 sku which you mentioned above); last week we took that wrong image down and republished with the correct sku. The image may temporarily disappear from the marketplace as the new one is being published. Please let us know the region so that we can check on our side if the image has propagated correctly to your region.

Once the correct image reappears on the marketplace please delete the old incorrect one before downloading the republished version.

**Comment by dbrennand** [comment]
> 
> 
> @dbrennand I have a couple of follow up questions. 1. Which Azure region is your Azure Stack stamp connected to? and 2. When did you attempt to download the image?
> 
> We had an issue in the publishing of the August 2020 image where it was published with the wrong sku (the aks-ubuntu-1604-201909 sku which you mentioned above); last week we took that wrong image down and republished with the correct sku. The image may temporarily disappear from the marketplace as the new one is being published. Please let us know the region so that we can check on our side if the image has propagated correctly to your region.
> 
> Once the correct image reappears on the marketplace please delete the old incorrect one before downloading the republished version.

Thanks for the response @JesusAlvarezTorres 

1. I assume you are referring to Azure, Azure Gov or Azure China clouds. If so, Azure is the region our stamp is connected to.
2. We downloaded the image on the 1st September.

**Comment by JesusAlvarezTorres** [comment]
Thanks @dbrennand, the image was undergoing validation, it was published earlier today. It should be available for download shortly; please give it a try and let us know if the image is still missing from the marketplace. Also, as mentioned earlier, please delete the image you downloaded on September 1st to avoid having conflicts.

**Comment by dbrennand** [comment]
Hi @JesusAlvarezTorres 

We have got the image and was able to depoy the cluster. However, are having a number of issues. Will be raising an issue soon.
