### ISSUE TITLE
Aksengine deploy command, generates same public  IP resource name on every deployment

### ISSUE THREAD

**Issue by valakhin** [Azure/aks-engine#3797]
On every run, aksengine generates same Azure public IP resource on a resource group.

**Steps To Reproduce**
I am trying to create second Kubernetes cluster with ASK engine on same resource group.  The aksengine deploy command  trying to create public IP for agent pool with same name as in the previous deployment.

"Resource /subscriptions/{subid}/resourceGroups/myRG/providers/Microsoft.Network/loadBalancers/myManagedinstanceApp3/frontendIPConfigurations/k8s-agent-outbound is referencing public IP address /subscriptions/{subid}/resourceGroups/myRG/providers/Microsoft.Network/publicIPAddresses/k8s-agent-ip-outbound that is already allocated to resource /subscriptions/{subid}/resourceGroups/myRG/providers/Microsoft.Network/loadBalancers/scomainternaks/frontendIPConfigurations/k8s-agent-outbound.\"

On further analyzing it, found that "agentPublicIPAddressName" parameter is generated with below params, which leads to generate same public IP address name on every aks deployment on resource group. 

"agentPublicIPAddressName": "[concat(parameters('orchestratorName'), '-agent-ip-outbound')]"

**Expected behavior**
On every Kubernetes deployment, The public IP address name should be different. 

**AKS Engine version**
0.55.10
**Kubernetes version**
1.18
**Additional context**

**Comment by MirzaSikander** [comment]
Running into the same issue.
