### ISSUE TITLE
Update to newer GPU driver version 

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#3814]
The current NVIDIA driver version is 418 with Ubuntu 18.04 and the latest version from NVIDIA is 450. 418 doesn't support a lot of current frameworks, like pytorch. Also needed to support CUDA.

**Comment by CecileRobertMichon** [comment]
This is where the GPU drivers are installed:
https://github.com/Azure/aks-engine/blob/87e89f67d2b261765e82ea5d68cc9988faa1b5fe/parts/k8s/cloud-init/artifacts/cse_install.sh#L69

And this is where the version is set:
https://github.com/Azure/aks-engine/blob/87e89f67d2b261765e82ea5d68cc9988faa1b5fe/parts/k8s/cloud-init/artifacts/cse_helpers.sh#L16

**Comment by Nishikoh** [comment]
@CecileRobertMichon  I'd like to tackle that.  Is the updated value 450.66?

**Comment by CecileRobertMichon** [comment]
@Nishikoh looking at https://docs.nvidia.com/datacenter/tesla/index.html, looks like 450.51.06 is the latest available for Linux. Where did you see 450.66?

**Comment by Nishikoh** [comment]
@CecileRobertMichon  I watched [here](https://www.nvidia.com/Download/driverResults.aspx/163238/en-us). 450.66 is not Data Center GPU Drivers. It's DISPLAY DRIVER.

**Comment by CecileRobertMichon** [comment]
Got it. I think we want `450.51.06` then.
