### ISSUE TITLE
variable provisionScriptParametersCommon in template file has hardcoded vnet reference and does not read from parameter.

### ISSUE THREAD

**Issue by jikuma** [Azure/aks-engine#3823]
**Describe the bug**

Create azure template and parameter file for kubernetes cluster inside vnet. The template file generated will have variable provisionScriptParametersCommon which does not read vnet value from paramter file

"provisionScriptParametersCommon": "[concat('ADMINUSER=azureuser APISERVER_PUBLIC_KEY=',parameters('apiServerCertificate'),' AUTHENTICATION_METHOD=client_secret CLOUDPROVIDER_BACKOFF=true CLOUDPROVIDER_BACKOFF_DURATION=5 CLOUDPROVIDER_BACKOFF_EXPONENT=0 CLOUDPROVIDER_BACKOFF_JITTER=0 CLOUDPROVIDER_BACKOFF_MODE=v2 CLOUDPROVIDER_BACKOFF_RETRIES=6 CLOUDPROVIDER_RATELIMIT=true CLOUDPROVIDER_RATELIMIT_BUCKET=200 CLOUDPROVIDER_RATELIMIT_BUCKET_WRITE=200 CLOUDPROVIDER_RATELIMIT_QPS=20 CLOUDPROVIDER_RATELIMIT_QPS_WRITE=20 CNI_PLUGINS_URL=https://kubernetesartifacts.azureedge.net/cni-plugins/v0.8.6/binaries/cni-plugins-linux-amd64-v0.8.6.tgz CONTAINERD_DOWNLOAD_URL_BASE=https://storage.googleapis.com/cri-containerd-release/ CONTAINERD_VERSION= CONTAINER_RUNTIME=docker CUSTOM_HYPERKUBE_IMAGE= ETCD_DOWNLOAD_URL=mcr.microsoft.com/oss/etcd-io/ ETCD_VERSION=3.3.22 EXCLUDE_MASTER_FROM_STANDARD_LB=true HYPERKUBE_URL=mcr.microsoft.com/ IDENTITY_SYSTEM=azure_ad IS_HOSTED_MASTER=false IS_IPV6_DUALSTACK_FEATURE_ENABLED=false IS_IPV6_ENABLED=false KMS_PROVIDER_VAULT_NAME=',variables('clusterKeyVaultName'),' KUBELET_PRIVATE_KEY=',parameters('clientPrivateKey'),' KUBERNETES_VERSION=1.18.8 KUBE_BINARY_URL= LOAD_BALANCER_DISABLE_OUTBOUND_SNAT=false LOAD_BALANCER_SKU=Standard LOCATION=',variables('location'),' MAXIMUM_LOADBALANCER_RULE_COUNT=250 MICROSOFT_APT_REPO=https://packages.microsoft.com MOBY_VERSION=19.03.12 NETWORK_API_VERSION=2018-08-01 NETWORK_MODE= NETWORK_PLUGIN=azure NETWORK_POLICY= NETWORK_SECURITY_GROUP=k8s-master-38808952-nsg PRIMARY_AVAILABILITY_SET= PRIMARY_SCALE_SET=k8s-registry-38808952-vmss RESOURCE_GROUP=',variables('resourceGroup'),' ROUTE_TABLE=k8s-master-38808952-routetable SERVICE_PRINCIPAL_CLIENT_ID=',variables('servicePrincipalClientId'),' SERVICE_PRINCIPAL_CLIENT_SECRET=',variables('singleQuote'),'',variables('servicePrincipalClientSecret'),'',variables('singleQuote'),' SUBNET=***subnetname*** SUBSCRIPTION_ID=',variables('subscriptionId'),' TENANT_ID=',variables('tenantID'),' USE_INSTANCE_METADATA=true USE_MANAGED_IDENTITY_EXTENSION=true VIRTUAL_NETWORK=***vnetname*** VIRTUAL_NETWORK_RESOURCE_GROUP=***vnetresourceGroups*** VM_TYPE=vmss VNET_CNI_PLUGINS_URL=https://kubernetesartifacts.azureedge.net/azure-cni/v1.1.6/binaries/azure-vnet-cni-linux-amd64-v1.1.6.tgz ')]",

**Steps To Reproduce**

use aks-engine generate command to generate template and parameter files. Create these file for kubernetes cluster inside a vnet

**Expected behavior**
VIRTUAL_NETWORK_RESOURCE_GROUP, VIRTUAL_NETWORK,  SUBNET should be read from variables or parameters.

**AKS Engine version**

Version: v0.55.2
GitCommit: 2c2af82e8
GitTreeState: clean

**Kubernetes version**

1.18.8
**Additional context**

**Comment by CecileRobertMichon** [comment]
@jikuma are you seeing a difference in value between the vnetName parameter and the vnetName provisioning script env variable? They should both be set from the same value, ie. `strings.Split(p.MasterProfile.VnetSubnetID, "/")[DefaultVnetNameResourceSegmentIndex]` for custom vnets, and `p.K8sOrchestratorName() + "-vnet-" + p.GetClusterID()` for non custom vnets:

https://github.com/Azure/aks-engine/blob/7b13847ad2a21cde934a5f3ad920b55cff85bc2e/pkg/api/types.go#L1120

https://github.com/Azure/aks-engine/blob/a1870f9a3ec6668515065df1bd41c6d37bff132b/pkg/engine/armvariables.go#L335

Agree that this code should be a bit more explicit though, perhaps a good improvement would be to reuse the `GetVirtualNetworkName` function to set the parameter, just we do with subnetName (https://github.com/Azure/aks-engine/blob/a1870f9a3ec6668515065df1bd41c6d37bff132b/pkg/engine/armvariables.go#L364).

**Comment by jikuma** [comment]
@CecileRobertMichon Thanks for your reply. Let me first explain you mu scenario. We use aks engine to generate azure template and parameters files. Our initial assumption was that if we can deploy multiple cluster using same template and changing parameters in a parameter file.  

But due to these random hardcode values present in between a value or custom data makes it making this scenario hard to achieve.

Right now as a workaround we do have a custom post processing script which runs on generated template file and parameters to fix these issue. 

Yes you are right a variable like subnetname will be really useful.

**Comment by CecileRobertMichon** [comment]
@jikuma understood. Unfortunately, AKS Engine generated templates are not designed to be reused for multiple clusters as all things that need to change are not parametrized. We expect users to generate an ARM template for each cluster deployment, or just use `aks-engine deploy` directly (basically the two ways described in https://github.com/Azure/aks-engine/blob/master/docs/tutorials/quickstart.md). You can, however, re-use the same apimodel.json to create multiple templates as long the DNS prefix is different. 

If this is the only change required to support your use case, we will gladly accept a PR to fix it but otherwise would recommend reconsidering the approach of re-using templates as that is untested by the project maintainers and might lead to unwanted side effects.

cc @jackfrancis
