### ISSUE TITLE
aad-pod-identity failed nmi pods

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3825]
Describing one of the pods:

```
Events:
  Type     Reason       Age                    From                                    Message
  ----     ------       ----                   ----                                    -------
  Warning  BackOff      4m6s (x6605 over 23h)  kubelet, k8s-pool1-18073537-vmss000001  Back-off restarting failed container
  Warning  FailedMount  2m29s                  kubelet, k8s-pool1-18073537-vmss000001  MountVolume.SetUp failed for volume "aad-pod-id-nmi-service-account-token-9gx77" : failed to sync secret cache: timed out waiting for the condition
  Normal   Pulled       2m12s (x2 over 2m28s)  kubelet, k8s-pool1-18073537-vmss000001  Container image "mcr.microsoft.com/k8s/aad-pod-identity/nmi:1.6.1" already present on machine
  Normal   Created      2m11s (x2 over 2m27s)  kubelet, k8s-pool1-18073537-vmss000001  Created container nmi
  Normal   Started      2m11s (x2 over 2m27s)  kubelet, k8s-pool1-18073537-vmss000001  Started container nmi
  Warning  BackOff      2m8s (x6 over 2m27s)   kubelet, k8s-pool1-18073537-vmss000001  Back-off restarting failed container
  Warning  FailedMount  113s                   kubelet, k8s-pool1-18073537-vmss000001  MountVolume.SetUp failed for volume "aad-pod-id-nmi-service-account-token-9gx77" : failed to sync secret cache: timed out waiting for the condition
  Normal   Pulled       15s (x4 over 112s)     kubelet, k8s-pool1-18073537-vmss000001  Container image "mcr.microsoft.com/k8s/aad-pod-identity/nmi:1.6.1" already present on machine
  Normal   Created      15s (x4 over 112s)     kubelet, k8s-pool1-18073537-vmss000001  Created container nmi
  Normal   Started      15s (x4 over 112s)     kubelet, k8s-pool1-18073537-vmss000001  Started container nmi
  Warning  BackOff      10s (x12 over 111s)    kubelet, k8s-pool1-18073537-vmss000001  Back-off restarting failed container
```

On a cluster using this api model:

{   "apiVersion": "vlabs",   "properties": {     "orchestratorProfile": {       "orchestratorType": "Kubernetes",       "kubernetesConfig": {         "clusterSubnet": "10.239.0.0/16",         "addons": [           {             "name": "aad-pod-identity",             "enabled": true                       }, { 							"name": "cluster-autoscaler", 							"enabled": true, 							"pools": [ 								{ 									"name": "pool1", 									"config": { 										"min-nodes": "1", 										"max-nodes": "5" 									} 								} 							], 							"config": { 								"scan-interval": "1m", 								"scale-down-delay-after-add": "1m0s", 								"scale-down-unneeded-time": "2m0s" 							} 						}, {             "name": "kubernetes-dashboard",             "enabled": true },           {             "name": "rescheduler",             "enabled": true           }, {             "name": "coredns",             "enabled": true,             "config": {               "min-replicas": "1"             }           }         ], "loadBalancerSku": "Standard", "excludeMasterFromStandardLB": true       }     },     "masterProfile": {       "count": 3,        "dnsPrefix": "",       "vmSize": "Standard_D2s_v3",       "OSDiskSizeGB": 200,       "vnetSubnetId": "/subscriptions/SUB_ID/resourceGroups/RG_NAME/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME",       "firstConsecutiveStaticIP": "10.239.255.239",       "vnetCidr": "10.239.0.0/16", "availabilityZones": ["1"]     },     "agentPoolProfiles": [       {         "name": "pool1",         "count": ${NODE_COUNT},         "vmSize": "Standard_D2s_v3",         "OSDiskSizeGB": 200,         "storageProfile": "ManagedDisks",         "diskSizesGB": [           128         ],         "availabilityProfile": "VirtualMachineScaleSets",         "vnetSubnetId": "/subscriptions/SUB_ID/resourceGroups/RG_NAME/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME", "availabilityZones": ["1", "2"], "scaleSetPriority": "Low"       }     ],     "linuxProfile": {       "adminUsername": "azureuser",       "ssh": {         "publicKeys": [           {             "keyData": ""           }         ]       }     },     "servicePrincipalProfile": {       "clientId": "",       "secret": ""     }   } }

**Comment by jackfrancis** [comment]
cc @aramase

**Comment by aramase** [comment]
It looks like kubelet failed to mount the service accounts in the volume for the pod -

```
  Warning  FailedMount  113s                   kubelet, k8s-pool1-18073537-vmss000001  MountVolume.SetUp failed for volume "aad-pod-id-nmi-service-account-token-9gx77" : failed to sync secret cache: timed out waiting for the condition
```
