### ISSUE TITLE
Change "loadBalancerOutboundIPs" config using aks-engine upgrade fails

### ISSUE THREAD

**Issue by DanielShor** [Azure/aks-engine#3883]
**Describe the bug**
We used [this example](https://raw.githubusercontent.com/Azure/aks-engine/master/test/e2e/test_cluster_configs/everything.json) to change the amount of outbound IPs from 1 to 2. 
When creating a new cluster (using `aks-engine deploy` command), everything is working properly. 
However, when upgrading an existing cluster (using `--force`, with or without `--control-plane-only` parameter), it's not working. What is actually happening is that a new IP (Azure resource) is created, but all other LoadBalancer needed modifications (adding second frontendIP configuration, add the frontendIP to the outbound rule) isn't happening. Basically, the upgrade is finished with a new IP deployed in the cluster's resource group, and no additional steps taken.

**Steps To Reproduce**
- Create a cluster (versions are specified below), using `aks-engine deploy` command, without specifying `loadBalancerOutboundIPs` config (meaning, using the default value 1)
- Upgrade the cluster by using aks-engine upgrade command (add to the apimodel `loadBalancerOutboundIPs` with value 2, using same K8s version of the original cluster in `--upgrade-version` parameter, use `--force`). 

**Expected behavior**
A new `Public IP address` Azure resource is created, but nothing is changed within the LoadBalancer.  

**AKS Engine version**
- The cluster was deployed using version `0.49.0`. 
- The upgrade was done with version `0.50.3` (the ability to use `loadBalancerOutboundIPs` was added in version `0.50.0`, and we can't use newer versions since it won't be compatible with the K8s version).  

**Kubernetes version**
`1.16.8`
**Additional context**

**Comment by jackfrancis** [comment]
Hi @DanielShor, I will add documentation to clarify that the `loadBalancerOutboundIPs` is not currently changeable via `aks-engine upgrade`. I'll add a help wanted tag and keep this issue open in case anyone wants to contribute a solution. I don't think it will be trivial to evolve `aks-engine upgrade` to do this configuration change, FYI.

**Comment by DanielShor** [comment]
Hi @jackfrancis , got it. 
Thanks for your quick response!
