### ISSUE TITLE
Create AKS Engine VHD documentation

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3898]
Let's write a detailed document that describes the following:

1) The functional surface area of the AKS Engine VHDs, what they provide, assume, etc
  - e.g., VHDs allow faster node bootstraps, as all required artifacts are present
2) Make it clear that VHD image versions are tightly coupled to particular versions of AKS Engine
3) Describe re-use possibilities, such as how to reliably build your own image derived from the AKS Engine VHD, and the "interface" that the AKS Engine-provided CSE expects to see on the underlying OS image (e.g., `/opt/azure/vhd-install.complete`).

**Comment by atiasadir** [comment]
Hi @jackfrancis,

What is the risk if we update the VHD manually and compile our own image ?
I go over the developer WIKI, and succeeded to compile aks-engine custom image easily.

I'll demonstrate our use case easily with fresh problem we are dealing with right now,
We have urgent vulnerability issue with VHD [2020.10.06](https://techness.co.uk/image/microsoft-aks/aks/aks-engine-ubuntu-1604-202007/2020.10.06) that tightly coupled with [aks-engine0.57](https://github.com/Azure/aks-engine/releases/tag/v0.57.0),
We need to update our VHD urgently to [2020.10.30](https://techness.co.uk/image/microsoft-aks/aks/aks-engine-ubuntu-1604-202007/2020.10.30)

Also, it's also good option to generate PR meanwhile to aks-engine, but this change is quite simple (similar PR [here)](https://github.com/Azure/aks-engine/pull/3906)

WDYT ? any suggestion ? 

Best regards,
Adir.

**Comment by bridgetkromhout** [comment]
Consulted with @jackfrancis and we're closing this due to the AKS Engine deprecation.
