### ISSUE TITLE
ARM template fails with CSE with status=15

### ISSUE THREAD

**Issue by elangocse** [Azure/aks-engine#3899]
**Describe the bug**

Hi All,

We have a requirement to create AKS engine in Azure stack environment. Therefore we followed below tutorial to create K8 cluster. and as part of running the command we got output folder with files along with ARM templates.

The input to the aks-engine command line tool is a cluster definition JSON file which contains Subscription, VNET, Subnet, Master count and Node count etc.

aks-engine will generate ARM templates, SSH keys, and a kubeconfig as Outputs and then persist those as local files under the _output/ directory:

https://github.com/Azure/aks-engine/blob/master/docs/tutorials/quickstart.md

So we thought of using this ARM templates as a template reference and using Terraform to automate the K8 cluster creation in other higher environments. However when we change some of the parameters like firstconsecutiveIP (CIDR or IP ranges for Master & worker IPs), VNET, Subnet etc and running the ARM template creates Public IP, VM, Disc, Avaiblity set etc without any issues but failing with Custom script extension only for Master VM. Not sure what excatly this exception but seems like a VM extension is failing with below exception:

_{ "id": "/subscriptions/xxxxx-42a4-4f90-xxxxxxxxxxxxxx/resourceGroups/aks-deployment-mdc-terraform-testing/providers/Microsoft.Resources/deployments/acctesttemplate-05/operations/C0BB1EA96DC78E2C", "operationId": "C0BB1EA96DC78E2C", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2020-09-24T15:29:00.4713997Z", "duration": "PT22M39.6171713S", "trackingId": "a713f23a-cbd5-490d-a9a3-d4baa0ea66d6", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: Enable failed: failed to execute command: command terminated with exit status=15\n[stdout]\nThu Sep 24 15:07:06 UTC 2020,k8s-master-43022074-0\n\n[stderr]\n" } ] } }, "targetResource": { "id": "/subscriptions/xxxxx-42a4-4f90-xxxxxxxxxxxxxx/resourceGroups/aks-deployment-mdc-terraform-testing/providers/Microsoft.Compute/virtualMachines/k8s-master-43022074-0/extensions/cse-master-0", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "k8s-master-43022074-0/cse-master-0" } }}_

**Steps To Reproduce**
Attached both ARM templates azuredeploy.json and azuredeploy.parameters.json for your review. Kindly have a look and help us in sorting it down.

I have mask Client Id, Client Secret, VNET and Subnet etc in azuredeploy.parameters.json file. Just change it if you would like simulate in your local.

**Expected behavior**
So we thought of using this ARM templates as a template reference. Changing some of the parameters and run same ARM templates for different environments.

**AKS Engine version**
v0.43.1
**Kubernetes version**
1.14
**Additional context**
[ARM.zip](https://github.com/Azure/aks-engine/files/5339755/ARM.zip)

**Comment by jackfrancis** [comment]
Hi @elangocse 

Is this a consistent error? The specifics of what caused that error would be in `/var/log/azure/cluster-provision.log` on the k8s-master-43022074-0 VM.

It's going to be something with the etcd configuration at bootstrapping.

Also, may I ask why you're continuing to use an older version of AKS Engine to build new clusters? Azure Stack supports newer versions.

@jadarsie @haofan-ms @JesusAlvarezTorres FYI

**Comment by elangocse** [comment]
Hi @jackfrancis 

Thank you so much for your response. Will look into the error in ` /var/log/azure/cluster-provision.log `and come back at the earliest.  Could you please help us find out the link/tutorial for list of AKS Engine versions supported latest ?

We need a AKS Engine version that should support kubernetes v1.17

**Comment by haofan-ms** [comment]
Hi @elangocse , the AKS Engine versions supported documentation is here https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#aks-engine-versions. For now we have deprecated the support for AKS Engine Version v0.43.1. Please use the AKS Engine Version v0.55.4 if you want to go with the Kubernetes v1.17.

**Comment by elangocse** [comment]
@jackfrancis / @haofan-ms ,

When I investigated the issue in `/var/log/azure/cluster-provision.log`, i am getting below exception. 
And this happens consistent. We are planning to have one ARM template which caters for all the environments just by changing the parameters accordingly.

The list of IP's you see below  :10.21.3.40 & 10.21.3.50 are the ones which we run  using **aks-engine deploy** and run successfully . Once we change the parameter json with variable "firstConsecutiveStaticIP" to 10.21.3.100 and run the ARM template directly we encountered with below error message.

_sudo: unable to resolve host k8s-master-43022074-0
client: etcd cluster is unavailable or misconfigured; error #0: x509: certificate is valid for 10.21.3.40, 127.0.0.1, 10.21.3.50, 10.0.0.1, not 10.21.3.100_

**Comment by elangocse** [comment]
> Hi @elangocse , the AKS Engine versions supported documentation is here https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#aks-engine-versions. For now we have deprecated the support for AKS Engine Version v0.43.1. Please use the AKS Engine Version v0.55.4 if you want to go with the Kubernetes v1.17.

Thanks for the tutorial. will use the new AKS Engine going forward.

**Comment by haofan-ms** [comment]
@elangocse ,

According to the behavior and error message you shared about, that is not a supported scenario. The IP of the etcd members are embedded on the certificates, and you cannot just change that "firstConsecutiveStaticIP" variable in the parameter json.

In order to achieve what you expect, you can try the `aks-engine deploy` command with the new IP, and take the "certificateProfile" portion to replace in the parameter json as well.

**Comment by elangocse** [comment]
> @elangocse ,
> 
> According to the behavior and error message you shared about, that is an expected error. The IP of the etcd members are embedded on the certificates, and you cannot just change that "firstConsecutiveStaticIP" variable in the parameter json.
> 
> In order to achieve what you expect, you can try the `aks-engine generate` command with the new IP, and take the "certificateProfile" portion to replace in the parameter json as well.

Thanks @haofan-ms , I will try the solution and check the behavior. 
Additionally where we can get the sample definition json file for provisioning v1.17 AKE . Could you please share the link.

**Comment by haofan-ms** [comment]
@elangocse , if you mean sample API model, they are available in the links in the `Notes` (https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#aks-engine-versions). Updating the `orchestratorRelease` and `orchestratorVersion` params in the template to the corresponding Kubernetes v1.17 should gives what you want.

**Comment by elangocse** [comment]
I have installed new aks-engine 0.55.4 and executed the command to deploy K8 cluster. But we are facing below issue:

INFO[0000] Writing cloud profile to: /tmp/azurestackcloud.json289031382
WARN[0000] apimodel: orchestratorProfile.kubernetesConfig.kubernetesImageBase forced to "mcr.microsoft.com/"
WARN[0000] apimodel: orchestratorProfile.kubernetesConfig.KubernetesImageBaseType forced to "mcr"
ERRO[0009] error: failed to get virtual machine image, compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
ERRO[0009] Image Publisher: microsoft-aks, Offer: aks, SKU: aks-engine-ubuntu-1604-202007, Version: 2020.09.14
Error: validating OS base images required by ./tiller-appgw-sit401.json: OS base image not available in target cloud: some VM images are missing on the target cloud

**Steps To Reproduce**
Run the following command
[tiller-appgw-sit401-1.json.log](https://github.com/Azure/aks-engine/files/5375666/tiller-appgw-sit401-1.json.log)

> ./aks-engine deploy --api-model ./tiller-appgw-sit401.json --azure-env AzureStackCloud --location abc1 --resource-group aks-deploy-mdc-ingress-test-new --auto-suffix --output-directory SIT401-1310-02 --client-id xxxxxxxxxxxxx --client-secret xxxxxxxxxxxxxxxxxx --subscription-id xxxxxxxxxxxxxxxxxxxxxxxxx

**Expected behavior**
When we run the above command it should create a k8 cluster with 1.17 version. but it produce following error.
error: failed to get virtual machine image, compute.VirtualMachineImagesClient

**AKS Engine version**
Version: v0.55.4

**Kubernetes version**
1.17 _[Planning to deploy]_
