### ISSUE TITLE
Azure DNS throttling issues

### ISSUE THREAD

**Issue by shaikatz** [Azure/aks-engine#390]
Lately, we upgraded our clusters to use the latest aks-engine version, and we started to see some performance issue with high-velocity applications running in our cluster.

It took us some time but we found that our kube-dns get throttled by azure dns limitations of 200qps.
The reason for that is probably this line:

https://github.com/Azure/aks-engine/blob/f6a406bff0e71cd8996781bd359b96e7612a5117/parts/k8s/addons/kubernetesmasteraddons-kube-dns-deployment.yaml#L166

In k8s as we all already know there is `ndots` configuration of 5. 
Meaning, most of our DNS queries will go to kube-dns 5 times.
For example, when asking for `localhost` from the container we can see those queries going to kube-dns:
`localhost.NAMESPACE.svc.cluster.local.`
`localhost.svc.cluster.local.`
`localhost.cluster.local`
`localhost.5ui1ximwqasdasdlulaoxuab01yg.bx.internal.cloudapp.net.`
`localhost`

The first 3 queries will be resolved internally by kube-dns, because of the `server` args, but the request to `bx.internal.cloudpp.net` will get to azure-dns, will receive NXDOMAIN, and will not get cached in kube-dns.

With those conditions, in default aks-engine setup, we getting very fast to the azure dns queries limits.

4 solutions that I see are:
 - Add `server` arg to kube-dns to resolve `bx.internal.cloudapp.net` to `127.0.0.1#10053`, but it might be breaking change if someone uses that.
 - Remove the `--no-negcache` argument and increase the cache size (the no neg cache was introduced to prevent filling the cache with NXDOMAIN responses, so increasing the cache size might give the same effect)
 - Set default kube-dns pods default to a higher number, to get some queries quota.
 - Change the ndots configuration in kubelet to lower number, it'll we increase the overall cluster performance [interesting benchmark](https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html), it'll not help to localhost queries, but it'll help to must of our dns queries and significantly reduce the overall queries count.

**Comment by jackfrancis** [comment]
Thanks for reporting @shaikatz and including such great detail.

I like the idea of enabling the first two options as configuration at cluster creation time. Which of those two is the most appropriate for reducing the queries in your environment?

**Comment by shaikatz** [comment]
@jackfrancis 

I'm not sure about the first option pitfalls, maybe some system pods use it? 
The second options sound more pitfall free for me, and I think I would love to go with it.
Do you want me to open PR for that?

**Comment by jackfrancis** [comment]
@shaikatz we'd welcome that, for sure! I think as long as we make it user-configurable, and not enable by default, it should be O.K. to add. If we find it doesn't work for most users but helps some then we need to make sure we clearly document when something should/should not be used.

**Comment by shaikatz** [comment]
I've decided to not implement that, and try to enhance my efforts to migrate to CoreDNS.
Hope that this issue will at least give some info to people seeing the same performance regression.

Thanks
