### ISSUE TITLE
Unable to deploy AKS engine with self signed certificate stored in keyvault

### ISSUE THREAD

**Issue by amankohli** [Azure/aks-engine#3912]
Below are the steps:

i) Create self signed certificates using the below open ssl command:
 sudo openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout apiserver.key -out apiserver.crt
note: The command is used to create all ceritificates

ii) Add the certificate to keyvault

iii) Use the below  command to deploy the aks engine cluster:
aks-engine deploy --subscription-id <subid?--location eastasia --api-model <filename>  -g -auth-method cli --debug -f

Below is the error:
  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=15\\n[stdout]\\nFri Oct 9 04:58:49 UTC 2020,k8s-master-36562843-0\\n\\n[stderr]\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentExists\",\r\n    \"message\": \"The role assignment already exists.\"\r\n  }\r\n}"}]
Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=15\\n[stdout]\\nFri Oct 9 04:58:49 UTC 2020,k8s-master-36562843-0\\n

Aks engine version:v0.56.0

Kubernetes version:1.15

**Comment by jackfrancis** [comment]
Hi @amankohli, are you including the certs, including CA certs, into the api model JSON?

**Comment by amankohli** [comment]
@jackfrancis 
Yes, we are including the certificates into api model json. Below is the apimodel.json:
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.15",
        "kubernetesConfig": {
        "useManagedIdentity": true,
        "userAssignedID": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/testingaks",
        "networkPlugin": "kubenet",
        "privateCluster": {
            "enabled": true
            }
        }
        },
        "certificateProfile": {
            "caCertificate": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksenginecacrt",
            "caPrivateKey": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksenginecakey",
            "apiServerCertificate": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineapiservercrt",
            "apiServerPrivateKey": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineapiserverkey",
            "clientCertificate": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineclientcrt",
            "clientPrivateKey": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineclientkey",
            "kubeConfigCertificate": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksenginekubectlClientcrt",
            "kubeConfigPrivateKey": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksenginekubectlClientkey",
            "etcdServerCertificate": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineetcdservercrt",
            "etcdServerPrivateKey": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineetcdserverkey",
            "etcdClientCertificate": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineetcdclientcrt",
            "etcdClientPrivateKey": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineetcdclientkey",
            "etcdPeerCertificates": [
                "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineetcdpeer0crt"

            ],
            "etcdPeerPrivateKeys": [
                "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.KeyVault/vaults/inf-eastasia1/secrets/aksengineetcdpeer0key"
            ]
        },

        "masterProfile": {
            "count": 1,
            "dnsPrefix": "k8seastasia-2dc",
            "vmSize": "Standard_D2s_v3",
            "OSDiskSizeGB": 100,
            "vnetSubnetId": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.Network/virtualNetworks/anf.dc.mgmt.eastasia.vnet/subnets/anf.dc.mgmt.eastasia.subnet",
            "firstConsecutiveStaticIP": "10.14.0.50"
            },
        "agentPoolProfiles": [
        {
            "name": "node",
            "count": 3,
            "vmSize": "Standard_D8s_v3",
            "OSDiskSizeGB": 100,
            "vnetSubnetId": "/subscriptions//resourceGroups/anf.dc.mgmt.eastasia.rg/providers/Microsoft.Network/virtualNetworks/anf.dc.mgmt.eastasia.vnet/subnets/anf.dc.mgmt.eastasia.subnet"
        }
        ],
        "linuxProfile": {
            "adminUsername": "ubuntu",
            "ssh": {
                "publicKeys": [
                {
                    "keyData": ""
                }
                ]
            }
        }
    }
}

 
When I add the certificates which are generated by aks engine on deployment to keyvault and retry the same deployment. the deployment is successful. Please guide me to the right command to create the certificate. The certificate generated by below command doesn't work with AKS engine:
sudo openssl req -x509 -nodes -days 365 -newkey rsa:4095 -keyout apiserver.key -out apiserver.crt

**Comment by jackfrancis** [comment]
Did you follow the documentation here?

https://github.com/Azure/aks-engine/blob/master/docs/topics/keyvault-secrets.md

Especially, you want to base64-encode the secret data in a single line as the value of the Key Vault data.

**Comment by amankohli** [comment]
@jackfrancis  yes , I followed the documentation above and base64 encoded the self signed certificates with the below commnad;
 az keyvault secret set --vault-name inf-eastasia1 --name aksengineapiservercrt --value "$(cat /root/kubecrt/apiserver.crt    | base64 --wrap=0)"


Does AKS engine support AKV managed certificates for the above request or they is roadmap to enable the support for AKV managed ceritificates?

**Comment by jackfrancis** [comment]
Did you include the `keyvaultSecretRef` object in the `servicePrincipalProfile` as described in the doc?

**Comment by jackfrancis** [comment]
Also, did you do this step against your key vault? (also referenced in the doc):

`az keyvault update -g $RG_NAME -n $KV_NAME --enabled-for-template-deployment`

**Comment by amankohli** [comment]
@jackfrancis  yes I have done the above steps. I was able to deploy the cluster by following steps:
i) Deploy aks engine without keyvault
ii) Upload all the certificate generated by aks engine to keyvault.
iii) Delete the cluster and create a new one by referencing the secrets on keyvault.
iv) The cluster deployment succeeds.

**The aks engine deployment fails only when I am using openssl to create certificates and upload to keyvault**

Please guide me on how aks engine generates the self signed ceritificates and I can try replicating it.

**Comment by jackfrancis** [comment]
Hi @amankohli, any progress, or should we close this issue?

**Comment by amankohli** [comment]
@jackfrancis  Yes, though this is not the best way to do to it I was able to resolve the issue with aks-egnine generate. Below are the steps we are following now:
i) Create certificates using aks-engine generate.

ii) Upload the certificates to the keyvault.

iii) Deploy kubernetes with the aks engine and uploaded certificates.
