### ISSUE TITLE
Openshift deployed on Azure has latency on DNS resolve on pods

### ISSUE THREAD

**Issue by serdarkalayci** [Azure/aks-engine#3913]
**Disclaimer**
We have an Openshift cluster installed on Azure VMs which has this problem, I'll provide details below.
I know this place is for AKS but some fellow from Microsoft encouraged me to open an issue here, because this community here knows best how to run an Kubernetes cluster on Azure. So if you find this interesting, you're more than welcome to lend a hand, if not, no harsh feelings.

**Describe the bug**
When I make any requests from a pod to anywhere (some address from service network ending with svc.cluster.local, or some address from internet like quay.io) the name resolution of the first request takes 2.5+ seconds while following requests take only 0.03 second. After a while when no requests have been made, it goes up to 2.5+ seconds again. So there must be a caching of the names for like 15 seconds TTL. The interesting part is this 2.5 seconds seems a fixed value, it's added to a normal name resolution time like the first request takes 2.53 seconds and the second request takes 0.03 second.
We tried the same command from the worker node (the node which runs my pod that I tried the command) resolves the name within 0.03 second also.

**Steps To Reproduce**
Running this command from the pod resolves name in 2.5+ seconds, and when the same command is ran immediately after the first one, resolution time is significantly smaller.
```
/ # curl -w '\nLookup time:t%{time_namelookup}\nConnect time:t%{time_connect}\nPreXfer time:t%{time_pretransfer}\nStartXfer time:t%{time_starttransfer}\n\nTotal time:t%{time_total}\n' -o /dev/null -s https://quay.io

Lookup time:t2.539307
Connect time:t2.889484
PreXfer time:t3.601053
StartXfer time:t3.959966
Total time:t5.275491

/ # curl -w '\nLookup time:t%{time_namelookup}\nConnect time:t%{time_connect}\nPreXfer time:t%{time_pretransfer}\nStartXfer time:t%{time_starttransfer}\n\nTotal time:t%{time_total}\n' -o /dev/null -s https://quay.io

Lookup time:t0.022437
Connect time:t0.274098
PreXfer time:t0.791364
StartXfer time:t1.059044
Total time:t2.158799
```

**Expected behavior**
All namespace resolution must be done somewhere around 0.03 second.

**AKS Engine version**
Openshift Container Platform 4.4.19
**Kubernetes version**
v1.17.1+6af3663
**Additional context**

**Comment by jackfrancis** [comment]
Hi @serdarkalayci, what CNI is your Openshift + k8s cluster using?

**Comment by serdarkalayci** [comment]
Hi @jackfrancis , Openshift uses its own solution named Openshift SDN as a CNI plugin. It has an option to use OVN-Kubernetes but its still in tech preview state, so we are using the default one.
https://docs.openshift.com/container-platform/4.4/networking/openshift_sdn/about-openshift-sdn.html

**Comment by jackfrancis** [comment]
So, one thing we've observed is that certain bridge mode configurations combined w/ distributed kube-dns svc (e.g., > 1 coredns pod) result in DNAT conntrack race conditions which produce this.

Is the Openshift SDN using a bridge interface on the host VM?

**Comment by serdarkalayci** [comment]
Hi @jackfrancis 
I'm not sure about your question, bu Red Hat approved that this is a bug within the OpenShift kernel, and told us that it'll be fixed in the next release.
