### ISSUE TITLE
AKS-Engine 0.57.0 Windows - The system cannot execute the specified program.

### ISSUE THREAD

**Issue by oronboni** [Azure/aks-engine#3919]
**The exe file cannot be used**

**Steps To Reproduce**

**Expected behavior**
Aks-Engine options

**AKS Engine version**
0.57.0

**Kubernetes version**
N/A
**Additional context**

**Comment by jackfrancis** [comment]
Hi @oronboni, there's not enough info in this issue to understand what's going on.
