### ISSUE TITLE
kubernetes-calico deployment error

### ISSUE THREAD

**Issue by shayshahak** [Azure/aks-engine#392]
**Is this a request for help?**:
---
yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Issue

**What version of aks-engine?**:

---
Version: v0.29.1

**Kubernetes version**:
untouched. as defined in the template.

**What happened**:
I'm using the following template:
https://github.com/Azure/aks-engine/blob/master/examples/networkpolicy/kubernetes-calico-azure.json
just added keys and a DNS name. didn't change anything else.
deployment is working but the cluster is not responding. and when SSHing to the Master you get the unix prompt but then it is also gets un responsive.

**What you expected to happen**:
to get a responsive cluster

**How to reproduce it** (as minimally and precisely as possible):
just deploy using the template:
https://github.com/Azure/aks-engine/blob/master/examples/networkpolicy/kubernetes-calico-azure.json

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
Repro'd

**Comment by shayshahak** [comment]
i think it might be related to this:
https://stackoverflow.com/questions/54492598/azure-unable-to-connect-to-cluster-aks-engine-using-kubectl

haven't got the change to deeply inspect.
