### ISSUE TITLE
aks-engine deploy reports failed to get virtual machine image

### ISSUE THREAD

**Issue by elangocse** [Azure/aks-engine#3926]
**Describe the bug**
We have a requirement to execute aks-engine deploy to install K8 cluster. But we are facing below issue:

_INFO[0000] Writing cloud profile to: /tmp/azurestackcloud.json289031382
WARN[0000] apimodel: orchestratorProfile.kubernetesConfig.kubernetesImageBase forced to "mcr.microsoft.com/"
WARN[0000] apimodel: orchestratorProfile.kubernetesConfig.KubernetesImageBaseType forced to "mcr"
ERRO[0009] error: failed to get virtual machine image, compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
ERRO[0009] Image Publisher: microsoft-aks, Offer: aks, SKU: aks-engine-ubuntu-1604-202007, Version: 2020.09.14
Error: validating OS base images required by ./tiller-appgw-sit401.json: OS base image not available in target cloud: some VM images are missing on the target cloud_

**Steps To Reproduce**
Run the following command
[tiller-appgw-sit401-1.json.log](https://github.com/Azure/aks-engine/files/5373043/tiller-appgw-sit401-1.json.log)

> ./aks-engine deploy --api-model ./tiller-appgw-sit401.json --azure-env AzureStackCloud --location abc1 --resource-group aks-deploy-mdc-ingress-test-new --auto-suffix --output-directory SIT401-1310-02 --client-id xxxxxxxxxxxxx --client-secret xxxxxxxxxxxxxxxxxx  --subscription-id xxxxxxxxxxxxxxxxxxxxxxxxx

**Attaching definition json file for your review. Not sure whether we have to edit something in the file to make it work.**

**Expected behavior**
When we run the above command it should create a k8 cluster with 1.17 version. but it produce following error.
**`error: failed to get virtual machine image, compute.VirtualMachineImagesClient`**

**AKS Engine version**
Version: v0.55.4

**Kubernetes version**
1.17 [Planning to deploy]

**Additional context**

**Comment by CecileRobertMichon** [comment]
cc @jadarsie

**Comment by elangocse** [comment]
> cc @jadarsie

Hello, any update please ? 
We are waiting for a response. Not able to proceed further.

**Comment by jadarsie** [comment]
The attached apimodel shows that you are trying to use the `aks-ubuntu-16.04` distro. The error message `OS base image not available in target cloud` is telling you that the required base image was not downloaded to your ASH cloud.

See [how to download](https://docs.microsoft.com/azure-stack/operator/azure-stack-download-azure-marketplace-item)  base images and [which specific base image version](https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#disconnected-azure-stack-hub-instances) to download for v0.55.4.
