### ISSUE TITLE
Image missing that addresses Microsoft Windows Servicing Stack Security Update September 2020

### ISSUE THREAD

**Issue by manojsubramani** [Azure/aks-engine#3927]
We use this wiki to upgrade K8 windows VMSS image to address vulnerability. https://review.docs.microsoft.com/en-us/engineering/compliance/upgrade-windows-os-version-for-vmss?branch=master
The latest image version is 17763.1397.2008070242 for the OS we use (2019-Datacenter-with-Containers-smalldisk). 
This does not resolve the vulnerability. I’m reaching out to you 

**Steps To Reproduce**
1. Deploy the latest image 17763.1397.2008070242
2. Check if following vulnerabilities are resolved
      Microsoft Windows Servicing Stack Security Update September 2020
      Microsoft Internet Explorer Security Update for September 2020

**Expected behavior**
A new image version with the vulnerabilities addressed is present in the OS list.

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by jackfrancis** [comment]
@marosset @jsturtevant

**Comment by jackfrancis** [comment]
Sorry, I didn't actually leave a comment :/

The question is: is there an AKS Engine story here?

**Comment by manojsubramani** [comment]
I was told that a new VHD (with sept and oct cumulative rollup packages) will be released on 20-Oct-2020. You may close this ticket.

**Comment by jackfrancis** [comment]
thx for checking back in!
