### ISSUE TITLE
Allow for definition of registry mirrors

### ISSUE THREAD

**Issue by arbielsk** [Azure/aks-engine#3941]
**Describe the request**
In an enterprise use-case it is a common scenario to not allow cluster worker nodes to access the internet. In order to solve the issue of pulling public container images, often an image registry mirror is provided. We'd like to be able to configure a registry mirror when configuring node-pools. This could be solved similarly to how the container runtime can be configured through [--aks-custom-headers](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#use-containerd-on-new-clusters-preview).

**Explain why AKS Engine needs it**

Currently ['hackish' solutions to this problem exist](https://github.com/juan-lee/knode) but we believe that it is a relevant, common use-case for enterprise users and thus it would be worth it make this available more easily and possible during provisioning.

**Describe the solution you'd like**

While it is not optimal as it involves some manual work, in most cases this issue can be easily solved on deployment side by adjusting image identifiers - e.g. **alpine:latest** becomes **internal-repository-url/alpine:latest**. 

However there are other automated tools that refer public images, e.g. **Bridge To Kubernetes** which references **envoyproxy/envoy**. In these cases, defining the 'base-registry', becomes a repetitive, tedious, manual task.

Luckily, both moby (/etc/docker/daemon.json) and containerd (/etc/containerd/config.toml) offer ways to configure repository-mirrors to pull public images from a mirror instead of docker.io.

This could be solved similarly to how the container runtime can be configured through [--aks-custom-headers](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#use-containerd-on-new-clusters-preview).

**Describe alternatives you've considered**

- Configuring this manually on the nodes -> gets lost on scaling, restarts
- Running a daemon set to setup the nodes -> daemon set needs privileged access, delay after provisioning before updated configuration is available
- Giving nodes internet access -> not possible due to enterprise security rules

**Additional context**
It looks like [this PR](https://github.com/Azure/aks-engine/pull/3072) has laid a lot of the necessary ground work.

Thank you very much for considering our request!

**Comment by jackfrancis** [comment]
Is this desired change able to be fulfilled entirely in the CRI configs? (e.g., /etc/docker/daemon.json or /etc/containerd/config.toml)

**Comment by arbielsk** [comment]
Thank you for your reply, @jackfrancis! 

I believe that this is really the only configuration necessary.

I have verified this with the docker runtime already in two different ways:
1. SSH-ing into the nodes and setting it up manually.
2. Using the above mentioned [knode](https://github.com/juan-lee/knode) which uses a daemon set to change the daemon.json file.

This is an example daemon.json file that results in the envisioned behavior (e.g. **nginx** is pulled as **my-favorite-enterprise.mirror.net:18086/nginx**):
```
    {
      "live-restore": true,
      "log-driver": "json-file",
      "log-opts":  {
        "max-size": "50m",
        "max-file": "5"
      },
      "registry-mirrors": ["https://my-favorite-enterprise.mirror.net:18086"]
    }
```

According to the [containerd documentation](https://github.com/containerd/cri/blob/master/docs/registry.md) it should be possible there as well by simply configuring the /etc/containerd/config.toml . I don't have the time to validate this today, but if you'd like me to I can probably get around to testing it with containerd on Monday.

**Comment by uncycler** [comment]
For containerd, we should be able to add this configuration:
```toml
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."*"]
    endpoint = ["https://my-favorite-enterprise.mirror.net:18086"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."my-favorite-enterprise.mirror.net:18086".auth]
    auth = "XXXXXXXXX"
```

**Comment by jackfrancis** [comment]
If you guys are manually managing the `/etc/containerd/config.toml` on worker nodes, this project might help if you're using AKS Engine-created clusters with VMSS node pools:

https://github.com/jackfrancis/kamino

Essentially what that project aims to do with a simple helm gesture is to take a OS image snapshot of a known-working VMSS instance (one of the VMs in the VMSS) and update the VMSS model with it. Primarily to make scaling faster (no need to download stuff for each node), but also to make manual node maintenance more tractable: apply manual node configs (per VMSS) on one node, then every new node you scale out on that pool will get that config automatically. (Obviously we're talking about config that is static and duplicated across all nodes in the pool.)
