### ISSUE TITLE
AKS Engine 0.55.4 not provisioning the kube cluster and fails with CSE exit status=36

### ISSUE THREAD

**Issue by elangocse** [Azure/aks-engine#3946]
Hi Team,

We have recently installed aks-engine 0.55.4 and want to deploy K8 cluster with v1.17 in azure stack. Whenever we run below command then the expected result is to provision kubernetes cluster in the Azure stack platform. However we are getting error which is also highlighted down.  **All resources are created like VM, Availability Set, Disk, Public IP etc. except Master node cse which fails after one hour of running.** 

`aks-engine deploy --api-model ./tiller-appgw-sit401.json --azure-env AzureStackCloud --location abc --resource-group aks-deploy-mdc-sit401-ing-test --auto-suffix --output-directory AKS-SIT401-1910-01 --client-id xxxxxx --client-secret xxxxxxxxxxx --subscription-id xxxxxxxxxxxxx`

ERROR:

> { "id": "/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/SAT-AzS-MDC-LM-APP-NFT401-DFV-RG/providers/Microsoft.Resources/deployments/SAT-AzS-MDC-LM-APP-NFT401-DFV-RG-1990650946/operations/730C993609997E4A", "operationId": "730C993609997E4A", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2020-10-19T16:16:26.2534585Z", "duration": "PT1H12M25.0934094S", "trackingId": "07eea180-c0d4-48e4-bd71-757304977dc5", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'cse-master-2'. Error message: Enable failed: failed to execute command: command terminated with exit status=36\n[stdout]\nMon Oct 19 15:05:09 UTC 2020,k8s-master-93995456-2\n\n[stderr]\n" } ] } }, "targetResource": { "id": "/subscriptions/xxxxxxxx/resourceGroups/SAT-AzS-MDC-LM-APP-NFT401-DFV-RG/providers/Microsoft.Compute/virtualMachines/k8s-master-93995456-2/extensions/cse-master-2", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "k8s-master-93995456-2/cse-master-2" } }}

Could you kindly help us to investigate what went wrong and why we aren't able to install Kubernetes cluster. Attached both api definition json and cluster-provisioning.log files. If I closely monitor cluster-provision.log file, it retries for 120 times to run below kubectl command and encountered with above mentioned exception.

**_kubectl --kubeconfig=/home/lmcp/.kube/config get pods -l app=kube-addon-manager -n kube-system_**

Moreover If I try to run  kubectl get nodes in the master node, its unresponsive. Also all resources are created except master node cse not provisioning and finally fails to come up. 

[cluster-provision.log](https://github.com/Azure/aks-engine/files/5403429/cluster-provision.log)
[tiller-nft-addons.yml.log](https://github.com/Azure/aks-engine/files/5403437/tiller-nft-addons.yml.log)
![Capture](https://user-images.githubusercontent.com/7022387/96489142-aa657880-125c-11eb-90bc-afb4824292ee.JPG)

**Comment by jadarsie** [comment]
Hello @elangocse, could you please try with Kubernetes v1.17.11?

See available K8s versions [here](https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#aks-engine-versions)

**Comment by elangocse** [comment]
Hello @jadarsie ,

As you recommended i have updated apimodel json from V1.17.9 to 1.17.11 and tried deploying 3 master and 3 worker node machine.

All the resources are provisioned without any issues, unfortunately two of the VMs (1 master and 1 worker node) failed with below exceptions. **_Attached the screen below from portal for clear reference._** 

Also I tried with one master and two worker nodes which is working fine.  What could be the reason for this with 3 master and 3 worker nodes ? isn't supported yet ?

**Worker Node:**

> { "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxx/resourceGroups/SAT-AzS-MDC-LM-APP-AKS-NFT401-RG/providers/Microsoft.Resources/deployments/SAT-AzS-MDC-LM-APP-AKS-NFT401-RG-1224013367/operations/99A8563BFCAB9480", "operationId": "99A8563BFCAB9480", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2020-10-20T09:12:24.1394516Z", "duration": "PT41M12.0735303S", "trackingId": "43e6e0fc-5e03-4d35-920f-18f43ca08136", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "FabricVmCreationError", "message": "Failed to create VM 'k8s-lmcpwrknft-13083861-0' " } ] } }, "targetResource": { "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxx/resourceGroups/SAT-AzS-MDC-LM-APP-AKS-NFT401-RG/providers/Microsoft.Compute/virtualMachines/k8s-lmcpwrknft-13083861-0", "resourceType": "Microsoft.Compute/virtualMachines", "resourceName": "k8s-lmcpwrknft-13083861-0" } }}

**Master Node:**

> { "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxx/resourceGroups/SAT-AzS-MDC-LM-APP-AKS-NFT401-RG/providers/Microsoft.Resources/deployments/SAT-AzS-MDC-LM-APP-AKS-NFT401-RG-1224013367/operations/1B7DD51A2B957DBC", "operationId": "1B7DD51A2B957DBC", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2020-10-20T09:17:08.4498771Z", "duration": "PT45M50.8228606S", "trackingId": "eed8cfe6-7aff-4ab4-b160-b3a4395fcad0", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "InternalExecutionError", "message": "Failed to create VM 'k8s-master-13083861-2' " } ] } }, "targetResource": { "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxx/resourceGroups/SAT-AzS-MDC-LM-APP-AKS-NFT401-RG/providers/Microsoft.Compute/virtualMachines/k8s-master-13083861-2", "resourceType": "Microsoft.Compute/virtualMachines", "resourceName": "k8s-master-13083861-2" } }}

![MicrosoftTeams-image](https://user-images.githubusercontent.com/7022387/96609577-4902df80-1318-11eb-94fe-6fb39bf094a1.png)

**Comment by jadarsie** [comment]
Thx for retrying. A FabricVmCreationError is beyond AKS Engine's scope. Could you please contact support? They should be able to tell you if this is a transient issue or what to do next.

**Comment by elangocse** [comment]
> Thx for retrying. A FabricVmCreationError is beyond AKS Engine's scope. Could you please contact support? They should be able to tell you if this is a transient issue or what to do next.

I can now provision AKS cluster without any issues , so closing the issue.
Thanks jadarsie for your technical support.
