### ISSUE TITLE
Accessing clusterIP services from a pod on the same node fails in ipvs proxy mode

### ISSUE THREAD

**Issue by aramase** [Azure/aks-engine#3949]
**Describe the bug**

**Steps To Reproduce**

For this particular issue when a test pod lands on the same node as the coredns pod, then the pod fails to connect to the dns pod through the `kube-dns` service ClusterIP. 

This is with ipvs + kubenet. DNAT seems to happen after the route lookup and the packet hits the ebtables output chain which results in the packet being dropped.

**Expected behavior**

**AKS Engine version**
v0.55.4 (but should be the same in all versions of aks-engine)

**Kubernetes version**
v1.18.8

**Additional context**

kubelet default `hairpin-mode` is `promiscuous-bridge`. As part of the resolution we should set `hairpin-mode` to `hairpin-veth` in kubelet config for ipvs + kubenet. 

Ref issue - https://github.com/kubernetes/kubernetes/issues/65358

**Comment by bridgetkromhout** [comment]
Verified with @aramase that although this bug still exists in AKS Engine, this issue can be closed now that AKS Engine is deprecated. He has not yet validated this scenario in CAPZ/
