### ISSUE TITLE
Auto Scale nodepool to 0

### ISSUE THREAD

**Issue by sdruc** [Azure/aks-engine#3952]
Deployed a cluster with autoscale enabled and min-nodes set to 0 but the nodepool does not scale to 0 

kubectl get nodes with no workloads deployed returned:

NAME                              STATUS   ROLES    AGE   VERSION
k8s-master-56779174-0             Ready    master   46m   v1.15.11
k8s-nc6pool-56779174-vmss000000   Ready    agent    46m   v1.15.11

**Steps To Reproduce**
Deploy the following manifest 

{"apiVersion": "vlabs", "properties": {"orchestratorProfile": {"orchestratorType": "Kubernetes", "orchestratorRelease": "1.15", "orchestratorVersion": "1.15.11", "kubernetesConfig": {"useManagedIdentity": true, "kubeletConfig": {"--max-pods": "110"}, "addons": [{"name": "blobfuse-flexvolume", "enabled": false}, {"name": "cluster-autoscaler", "enabled": true, "pools": [{"name": "nc6pool", "config": {"min-nodes": "0", "max-nodes": "10"}}], "config": {"scan-interval": "1m", "ignore-daemonsets-utilization": "true", "ignore-mirror-pods-utilization": "true", "skip-nodes-with-system-pods": "false"}}]}}, "masterProfile": {"count": 1, "dnsPrefix": "", "vmSize": "Standard_D2_v3"}, "agentPoolProfiles": [{"name": "nc6pool", "count": 2, "vmSize": "Standard_NC6", "osDiskSizeGB": 500, "availabilityProfile": "VirtualMachineScaleSets", "scaleSetPriority": "Spot", "scaleSetEvictionPolicy": "Delete", "spotMaxPrice": -1, "storageProfile": "ManagedDisks", "osType": "Linux", "distro": "aks-ubuntu-18.04"}], "linuxProfile": {"adminUsername": "azureuser", "ssh": {"publicKeys": [{"keyData": ""}]}}}}

using:

aks-engine deploy --subscription-id {subscription_id} \
    --dns-prefix {dns_prefix} \
    --resource-group {aks_name} \
    --location {location} \
    --api-model ./cluster-tmplt.json \
    --client-id {appId} \
    --client-secret {password} \
    --set servicePrincipalProfile.clientId="{appId}" \
    --set servicePrincipalProfile.secret="{password}" \
    --force-overwrite 

**Expected behavior**
kubectl get nodes should return :

NAME                              STATUS   ROLES    AGE   VERSION
k8s-master-56779174-0             Ready    master   46m   v1.15.11

**Comment by CecileRobertMichon** [comment]
Hi @sdruc, are you seeing the resulting cluster-autoscaler addon misconfigured on your cluster? Could you share the output of`kubectl describe deployment cluster-autoscaler -n kube-system`?

If the cluster-autoscaler does indeed have a min count of 0, this might be a cluster-autoscaler bug, I recommend filing an issue there. See also https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#scaling-a-vmss-node-group-to-and-from-0

**Comment by sdruc** [comment]
Hi  @CecileRobertMichon thanks for replying 

Here is the output for the CA deployment

`Name:                   cluster-autoscaler
Namespace:              kube-system
CreationTimestamp:      Thu, 22 Oct 2020 04:34:51 +0000
Labels:                 addonmanager.kubernetes.io/mode=EnsureExists
                        app=cluster-autoscaler
                        kubernetes.io/cluster-service=true
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=cluster-autoscaler
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=cluster-autoscaler
  Service Account:  cluster-autoscaler
  Containers:
   cluster-autoscaler:
    Image:      mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.18.2
    Port:       <none>
    Host Port:  <none>
    Command:
      ./cluster-autoscaler
      --logtostderr=true
      --cloud-provider=azure
      --skip-nodes-with-local-storage=false
      --scan-interval=1m
      --expendable-pods-priority-cutoff=-10
      --ignore-daemonsets-utilization=true
      --ignore-mirror-pods-utilization=true
      --max-autoprovisioned-node-group-count=15
      --max-empty-bulk-delete=10
      --max-failing-time=15m0s
      --max-graceful-termination-sec=600
      --max-inactivity=10m0s
      --max-node-provision-time=15m0s
      --max-nodes-total=0
      --max-total-unready-percentage=45
      --memory-total=0:6400000
      --min-replica-count=0
      --namespace=kube-system
      --new-pod-scale-up-delay=0s
      --node-autoprovisioning-enabled=false
      --ok-total-unready-count=3
      --scale-down-candidates-pool-min-count=50
      --scale-down-candidates-pool-ratio=0.1
      --scale-down-delay-after-add=10m0s
      --scale-down-delay-after-delete=1m
      --scale-down-delay-after-failure=3m0s
      --scale-down-enabled=true
      --scale-down-non-empty-candidates-count=30
      --scale-down-unneeded-time=10m0s
      --scale-down-unready-time=20m0s
      --scale-down-utilization-threshold=0.5
      --skip-nodes-with-local-storage=false
      --skip-nodes-with-system-pods=false
      --stderrthreshold=2
      --unremovable-node-recheck-timeout=5m0s
      --v=3
      --write-status-configmap=true
      --balance-similar-node-groups=true
      --nodes=0:10:k8s-nc6pool-56779174-vmss
    Limits:
      cpu:     100m
      memory:  300Mi
    Requests:
      cpu:     100m
      memory:  300Mi
    Environment:
      ARM_CLOUD:                           AzurePublicCloud
      ARM_SUBSCRIPTION_ID:                 <set to the key 'SubscriptionID' in secret 'cluster-autoscaler-azure'>  Optional: false
      ARM_RESOURCE_GROUP:                  <set to the key 'ResourceGroup' in secret 'cluster-autoscaler-azure'>   Optional: false
      ARM_TENANT_ID:                       <set to the key 'TenantID' in secret 'cluster-autoscaler-azure'>        Optional: false
      ARM_CLIENT_ID:                       <set to the key 'ClientID' in secret 'cluster-autoscaler-azure'>        Optional: false
      ARM_CLIENT_SECRET:                   <set to the key 'ClientSecret' in secret 'cluster-autoscaler-azure'>    Optional: false
      ARM_VM_TYPE:                         <set to the key 'VMType' in secret 'cluster-autoscaler-azure'>          Optional: false
      ARM_USE_MANAGED_IDENTITY_EXTENSION:  true
    Mounts:
      /etc/ssl/certs/ca-certificates.crt from ssl-certs (ro)
      /var/lib/waagent/ from waagent (ro)
  Volumes:
   ssl-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs/ca-certificates.crt
    HostPathType:  
   waagent:
    Type:               HostPath (bare host directory volume)
    Path:               /var/lib/waagent/
    HostPathType:       
  Priority Class Name:  system-node-critical
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   cluster-autoscaler-6d57f98f7f (1/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  3m17s  deployment-controller  Scaled up replica set cluster-autoscaler-6d57f98f7f to 1`

The min node looks to be set to 0.

Thanks for the reference but I don't really understand why I need to apply taints to my nodepools

Incidentally my service principal is assigned as Owner - could that make a difference

**Comment by CecileRobertMichon** [comment]
I see `Replicas: 1 desired | 1 updated | 1 total | 1 available | 0 unavailable` which indicates the cluster-autoscaler is expecting 1 node and not trying to scale down. Is there anything else running on the cluster (perhaps addons) that might require that 1 worker node? The next thing I would check is the autoscaler logs. This issue doesn't seem AKS Engine related.

**Comment by sdruc** [comment]
I thought that was referring to the master node. 

> Is there anything else running on the cluster (perhaps addons) that might require that 1 worker node?

I have nothing running that isn't shipped with the manifest in my original post

> This issue doesn't seem AKS Engine related.

I would agree if not for the fact that for the past month various previously working components have been failing. From CA to blobfuse, to kubeflow not wanting to deploy for Kuberenetes api >1.15

I have torn down my clusters and redeployed them in various configurations to try and get it to work. I was hoping you could confirm these aren't isolated issues

**Comment by CecileRobertMichon** [comment]
@sdruc not saying this is related to the issues you're having, but k8s 1.15 is out of support in the latest AKS Engine versions so it would be best to test this with a newer version. Do you have a reference to the kubeflow issue you mentioned?

> I have torn down my clusters and redeployed them in various configurations to try and get it to work. I was hoping you could confirm these aren't isolated issues

Was this autoscaler configuration successfully scaling down to 0 for you before? or is this the first time you're trying to get it working? what version of AKS Engine did you try this with? 

As a side note, I'm surprised your autoscaler deployment is using v1.18.2, the default in AKS Engine us v1.15.7 for k8s 1.15. Did you override the image default?

**Comment by bridgetkromhout** [comment]
@sdruc As we have not heard back in some time, we'll close this issue. If you continue to have issues, please be aware that AKS Engine is being deprecated; we recommend a move to AKS or CAPZ. See https://github.com/Azure/aks-engine#project-status - thanks!
