### ISSUE TITLE
Blobfuse PVC doesn't see files

### ISSUE THREAD

**Issue by sdruc** [Azure/aks-engine#3960]
**Describe the bug**
If I deploy a pod with volume mounts using a pvc provided by blobfuse the pod can not access the files in cloud storage

**Steps To Reproduce**

requirements: azure storage account container with files in it

deploy a cluster in NorthEurope using the following manifest

{"apiVersion": "vlabs", "properties": {"orchestratorProfile": {"orchestratorType": "Kubernetes", "orchestratorRelease": "1.18", "orchestratorVersion": "1.18.8", "kubernetesConfig": {"useManagedIdentity": true, "kubeletConfig": {"--max-pods": "110"}, "addons": [{"name": "cluster-autoscaler", "enabled": true, "pools": [{"name": "nc6pool", "config": {"min-nodes": "0", "max-nodes": "10"}}], "config": {"scan-interval": "1m", "ignore-daemonsets-utilization": "true", "ignore-mirror-pods-utilization": "true", "skip-nodes-with-system-pods": "false"}}]}}, "masterProfile": {"count": 1, "dnsPrefix": "", "vmSize": "Standard_D2_v3"}, "agentPoolProfiles": [{"name": "nc6pool", "count": 2, "vmSize": "Standard_NC6", "osDiskSizeGB": 500, "availabilityProfile": "VirtualMachineScaleSets", "scaleSetPriority": "Spot", "scaleSetEvictionPolicy": "Delete", "spotMaxPrice": -1, "storageProfile": "ManagedDisks", "osType": "Linux", "distro": "aks-ubuntu-18.04"}], "linuxProfile": {"adminUsername": "azureuser", "ssh": {"publicKeys": [{"keyData": ""}]}}}}

with the following command:

aks-engine deploy --subscription-id {subscription_id} \
    --dns-prefix {dns_prefix} \
    --resource-group {aks_name} \
    --location {location} \
    --api-model ./cluster-tmplt.json \
    --client-id {appId} \
    --client-secret {password} \
    --set servicePrincipalProfile.clientId="{appId}" \
    --set servicePrincipalProfile.secret="{password}" \
    --force-overwrite

once deployed create secret for the azure blob storage account

kubectl create secret generic {secret name} --from-literal accountname={storage_account} --from-literal accountkey={storage_account_key} --type="azure/blobfuse"

create a flexvolume PV for the storage account container and referencing the secret

create a PVC referencing the PV 

deploy a busy box pod with the PVC mounted

execute:

kubectl exec -it {busyboxpod} -- ls {pvc_mount_point}

(in my case it returns nothing) 

**Expected behavior**

kubectl exec -it {busyboxpod} -- ls {pvc_mount_point} should return a list of files in blob storage

**AKS Engine version**

0.57

**Kubernetes version**
1.18.8

**Additional context**
Service Principal has Owner privileges
location is North Europe
tried a similar deployment using az aks and it worked 

Thanks for your help

**Comment by CecileRobertMichon** [comment]
Hi @sdruc, I'm not sure how this behavior could be different on AKS vs. AKS Engine. Did you specify any different configurations on the AKS cluster?

**Comment by sdruc** [comment]
Hi @CecileRobertMichon 

The only thing I can think of is that the default aks api version is 1.17.11 and you have to manually install blobfuse which I did v 1.0.13 vs the 1.0.8 that is default for aks engine. 

I tried updating blobfuse for the aks-engine cluster but it gave the same result

**Comment by andyzhangx** [comment]
pls follow this guide to provide more detailed info, thanks
https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse#troubleshooting

**Comment by bridgetkromhout** [comment]
As we have not heard back in some time, we'll close this issue. If you continue to have issues, please be aware that AKS Engine is being deprecated; we recommend a move to AKS or CAPZ. See https://github.com/Azure/aks-engine#project-status - thanks!

**Comment by andyzhangx** [comment]
blobfuse flexvol is already deprecated, pls try https://github.com/kubernetes-sigs/blob-csi-driver instead.
