### ISSUE TITLE
Ingress Nginx works only for 1 Master and 1 Worker Node

### ISSUE THREAD

**Issue by elangocse** [Azure/aks-engine#3968]
Hi Team,

We have provisioned K8 cluster (1 Master and 1 Worker node ) using aks-engine v0.55.4 and kube server 1.17 version. Later we followed below MS doc for creating Ingress in Azure.

https://docs.microsoft.com/en-us/azure/aks/ingress-basic

Once after setting up the applications and Nginx Ingress , we could run the demo application in browser using Ingress LoadBalancer IP address. But when we try to scale up one more Worker node in the cluster and subsequently deployed sample apps into K8. It get deployed into Worker node 2 and after set up ingress for the new app, this time Ingress not able to route it to app and its throwing **504 time out error**.

We investigated further and identified , the Ingress POD and Application POD if it runs in the same Worker Node then its running fine. But if incase App is deployed in a diff Worker node then its throwing 504 time out error.

However Ingress Nginx should able to determine the apps regardless of the Worker machine where it runs and it should route the HTTP traffic right ? Could you kindly help us identify the issue and how to sort it out ?

Also whenever we run Ingress manifest yaml file , we encounter below issue.

> Error from server (InternalError): error when creating "helloworld-ingres.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://nginx-ingress-ingress-nginx-controller-admission.ingress-basic.svc:443/networking/v1beta1/ingresses?timeout=10s: dial tcp 10.0.158.27:443: connect: connection refused

so every time we have to run below command to fix this issue. Please guide us on this issue too,
`kubectl delete ValidatingWebhookConfiguration nginx-ingress-ingress-nginx-admission`

**Comment by elangocse** [comment]
Hi Team,

Can you respond on the above query please ?
Thanks

**Comment by jadarsie** [comment]
Hello @elangocse. Please provide your apimodel so we can reduce the scope of the problem. Azure or Azure Stack? 

This behavior can happen if you are deploying to a custom VNET + kubenet and forgot to attach the route table to the subnet: https://github.com/Azure/aks-engine/blob/master/docs/tutorials/custom-vnet.md#post-deployment-attach-cluster-route-table-to-vnet

**Comment by bridgetkromhout** [comment]
Hi, @elangocse - hopefully the reply above from @jadarsie led you to a solution. As we have not heard back in some time, we'll close this issue. If you continue to have issues, please be aware that AKS Engine is being deprecated; we recommend a move to AKS or CAPZ. See https://github.com/Azure/aks-engine#project-status - thanks!
