### ISSUE TITLE
Add support for orchestratorRelease: custom 

### ISSUE THREAD

**Issue by ritazh** [Azure/aks-engine#397]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

FEATURE REQUEST
---

**What version of aks-engine?**:

---

When using aks-engine to create test clusters on Azure for e2e prow jobs for k8s/k8s PRs, it would be great to add support for `orchestratorRelease: custom` such that instead of using a pre-existing supported version, we use a custom hyperkube image instead. This allows us to use the latest from k8s master.

Today, we have to provide a version for`orchestratorRelease`, but the cluster created is using a custom hyperkube image that looks like `v1.14.0-alpha.2.20+819dcaaa17a04c`, which does not match any version in our supported versions list. This can create confusion for testgrid or anyone looking at the jobs. 

**Kubernetes version**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

cc @PatrickLang @jchauncey @adelina-t

**Comment by jackfrancis** [comment]
Just to make sure we're doing this in the right place... Is it not possible to have the CI runner infer the major.minor (or even major.minor.patch) release that is associated with the build? In the above example that would be "1.14".

It would require some potentially undesirable refactoring to overload `orchestratorRelease` with this additional semantic representation (currently it is defined as a SEMVER string with two significant digits).

What is the downside to not changing aks-engine, but instead re-using the existing `orchestratorRelease` configuration vector like this?

**Comment by ritazh** [comment]
The issue is `orchestratorRelease` is required to run aks-engine and v1.14 is not a supported version (yet). but this is more of the case since we are testing the latest from k8s upstream. so it will be very common to not have the version supported yet.

**Comment by jackfrancis** [comment]
1.14 is supported in master. Do we need it to be a releasable aks-engine version?

Also, we can reduce the latency between (1) k8s upstream reving its HEAD to the next pre-release version and (2) that new major.minor version being "supported" via aks-engine.

If we can do the above it would be, in my opinion, more elegant and idiomatic within pre-existing aks-engine constructs. Is that feasible?

**Comment by ritazh** [comment]
> 1.14 is supported in master. Do we need it to be a releasable aks-engine version?

yea, we are using a released version of aks-engine v0.29.1, which did not have 1.14. so I think this will continue to happen.

**Comment by jackfrancis** [comment]
Understood, but aks-engine will need some rationalized semantic version representation of the desired cluster, as its template generation workflow is version-context-dependent. I.e.,is vmss supported, Standard LB, etc etc. So whatever we come up with we need to solve that as well.

**Comment by ritazh** [comment]
yea totally understand this is not an easy ask. lets brainstorm on some possible, less intrusive options?

**Comment by jackfrancis** [comment]
I think if we (1) required an "orchestratorRelease" value but (2) if we also got a custom hyperkube image we (3) short circuit the version "validation" foo, but (4) we now establish a cluster version context so we do the right things for that particular k8s version

@CecileRobertMichon does the above make sense?

**Comment by adelina-t** [comment]
We have the same issue in k8s windows upstream tests. Now we can just use builds from master ( which is what we do ), but for the community it would be clearer if they can see exactly what tools we use and have the process as transparent as possible. 

Can we accept any orchestratorRelease version if we also pass another key that specifies this is a dev environment? ("dev": "True" or something similar ). Or just make a validation based on weather customHyperkube is passed or not?

**Comment by CecileRobertMichon** [comment]
`(3) short circuit the version "validation" foo` will get very messy IMO but it doable (we'll have to fill in the orchestratorVersion value as well, which won't be easy if the release isn't a support minor version in aks-engine). Doing `we now establish a cluster version context so we do the right things for that particular k8s version` for a version that hasn't been explicitly added in aks-engine might get tricky though (for eg. the k8s component map won't have a 1.15 entry until we add a 1.15 entry).

I think in general, using aks-engine tool to deploy k8s versions that it doesn't support is not straight forward because nothing was designed with this requirement in mind...
