### ISSUE TITLE
Windows + containerd request/limits edge cases for Kubernetes < 1.18

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3978]
In versions of Kubernetes prior to 1.18, we observe pods unable to be scheduled when CPU/memory requests/limits are applied. For example:

```
Warning  Failed     34m (x5 over 35m)    kubelet, 7408k8s01000001  Error: failed to create containerd task: invalid spec - Windows Process Container CPU Count: '0', Limit: '1000', and Weight: '5000' are mutually exclusive: unknown
```

For this reason, we recommend folks don't use containerd w/ Windows-enabled clusters on versions prior to 1.18

**Comment by jackfrancis** [comment]
cc @marosset @jsturtevant

**Comment by ganga1980** [comment]
Hi, @marosset , @jsturtevant,  is this issue fixed already? if not, when this issue will be fixed?

**Comment by jsturtevant** [comment]
This isn't an issue in 1.18+. 1.18 was dropped from [upstream k8s support this month ](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history)so there a no plans to make this work prior to 1.18
