### ISSUE TITLE
Cluster created using AKS-Engine. Ingress controller/LB svc pending. Error AADSTS7000215 Invalid client secret. & Can't connect VM with ssh

### ISSUE THREAD

**Issue by valerymo** [Azure/aks-engine#3984]
**Describe the bug**
[log1.txt](https://github.com/Azure/aks-engine/files/5456503/log1.txt)

I created AKS Cluster using AKS-Engine,
and deployed my microservcies and Ingress Controller.
All Pods are running ok.
But issue with Ingress controller LoadBalancer/service is in pending state.
Error: AADSTS7000215 Invalid client secret
I tried to connect VM using ssh, but can't do it.
Could you please see details in log attached.

Notes. Same helm deployment of Ingress controller is working ok in my local environment (WSL/Ubuntu 20)
Just in Azure - service of Ingress controller - pending, and error.

**Steps To Reproduce**

I used my app to create the cluster and apps.
https://github.com/valerymo/azure-try

**Expected behavior**
 Ingress controller service should work

**AKS Engine version**
$ aks-engine version
Version: v0.57.0
GitCommit: e80c40dba
GitTreeState: clean

**Kubernetes version**
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T23:07:23Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
[log1.txt](https://github.com/Azure/aks-engine/files/5456536/log1.txt)

**Comment by valerymo** [comment]
sorry, maybe it's not bug. It's actually question, wanted to consult. I'm not completely sure ... maybe it's my issue.
Thank you. Please you can change it from Bug to another group.

**Comment by jackfrancis** [comment]
Hi @valerymo, are you wanting to create an AKS cluster? To do so, get the Azure CLI (`az`) and use the `az aks` command.

**Comment by bridgetkromhout** [comment]
Hi, @valerymo - we're resolving this issue; if you still need assistance with AKS, please check out https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough. As the AKS Engine tool in this GitHub repo is deprecated, we do not recommend using it at this time. Thanks.
