### ISSUE TITLE
Add required apiserver tokenRequest flags

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3988]
**Describe the request**

1.20 (or thereabouts) will make tokenRequest flags a required flag, see this PR:

https://github.com/kubernetes/kubernetes/pull/95896

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

This has been determined to be a known-working config to assign by default:

```
          "--service-account-issuer": "kubernetes.default.svc",
          "--service-account-signing-key-file": "/etc/kubernetes/certs/apiserver.key"
```

**Describe alternatives you've considered**

**Additional context**

**Comment by mboersma** [comment]
Closed by #3989.
