### ISSUE TITLE
Deployment of prometheus-grafana-k8s extension fails on Windows Pools

### ISSUE THREAD

**Issue by JoaquimFreitas** [Azure/aks-engine#399]
**Is this a request for help?**:
**NO**
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
**ISSUE**
---

**What version of aks-engine?**:
**0.29.1**
---

**Kubernetes version**:
**1.13**

**What happened**:
Added the extension `prometheus-grafana-k8s`:  
https://github.com/Azure/aks-engine/tree/master/extensions/prometheus-grafana-k8s  
to an hybrid cluster deployment, and the extension failed to install on ALL Windows nodes with the following error:

```
{
  "error": {
    "code": "PropertyChangeNotAllowed",
    "message": "Changing property 'publisher' is not allowed.",
    "target": "publisher"
  }
}
```

**What you expected to happen**:
The extension `prometheus-grafana-k8s` to be installed on ALL nodes in the hybrid cluster.

**How to reproduce it** (as minimally and precisely as possible):
Just use an simple hybrid deployment:

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_DS2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "extensions": [
          {
            "name": "prometheus-grafana-k8s"
          }
      },
      {
        "name": "windowspool",
        "osType": "Windows",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "extensions": [
          {
            "name": "prometheus-grafana-k8s"
          }
        ]
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": "",
    },
    "extensionProfiles": [
      {
        "name": "prometheus-grafana-k8s",
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/aks-engine/master/"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

**Anything else we need to know**:

**Comment by zhiweiv** [comment]
I think it only supports Linux, it run prometheus-grafana-k8s.sh on agent nodes which definitely does not work on Windows. See https://github.com/Azure/aks-engine/tree/master/extensions/prometheus-grafana-k8s.

**Comment by JoaquimFreitas** [comment]
Some poor guy reporting the same problem: #245

The documentation is not very clear:
https://github.com/Azure/aks-engine/tree/master/extensions/prometheus-grafana-k8s

BUT, it seems not to be working even on Linux nodes in a hybrid cluster... I've tested and only a short number of pods deployed by the extension are in fact started, most of them just fail...
