### ISSUE TITLE
Azure CNI from Feb. 2019 or earlier being retired

### ISSUE THREAD

**Issue by pjohnst5** [Azure/aks-engine#3992]
**Describe the bug**
Azure CNI versions from Feb. 2019 or earlier (<=v1.0.18) are being retired due to an underlying service change.

**Additional context**
Used to track the announcement for affected customers
@craiglpeters

**Comment by bridgetkromhout** [comment]
Thanks, @pjohnst5! I'm resolving this now, as those versions of Kubernetes are already out of support.
