### ISSUE TITLE
CSE error: exit code 30

### ISSUE THREAD

**Issue by jhzhu89** [Azure/aks-engine#3998]
**Describe the bug**
I am deploying a k8s cluster using aks-engine via linux terminal. The deployment got stuck. I checked azure portal, found below error when deploying a VM extension:

k8s-master-33543450-0/cse-master-0:

Status: Conflict

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=30\n[stdout]\nTue Nov 3 03:23:06 UTC 2020,k8s-master-33543450-0\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
}

**Steps To Reproduce**

**Expected behavior**
The deployment should succeed without any error.

**AKS Engine version**
Version: v0.57.0
GitCommit: e80c40dba
GitTreeState: clean

**Kubernetes version**
Default.

**Additional context**

**Comment by jackfrancis** [comment]
Hi @jhzhu89,

That indicates the kubelet systemd service (which launches all the Kubernetes application daemons) did not come online successfully. journald may give you some hints of what's. going on:

`sudo journalctl -u kubelet`

on the `k8s-master-33543450-0` VM that reported the CSE error.

Do you see any pattern of failure in the log output?

**Comment by vavenk-ms** [comment]
I faced the same issue, turns out I was passing arguments in the format `tls_min_version` instead of `--tls-min-version` and k8s v.1.19.x isn't happy with that. Updating that resolved the issue.

This comment helped me debug the issue further - https://github.com/kubernetes/kubeadm/issues/1082#issuecomment-417230673

**Comment by craiglpeters** [comment]
This appears to have been resolved so I am closing. Please reopen if it is not resolved.
