### ISSUE TITLE
Enabling EncryptionWithExternalKms causes cluster creation to fail

### ISSUE THREAD

**Issue by oluwadeyi** [Azure/aks-engine#4005]
**Describe the bug**
I had an existing cluster which I had to delete and then recreate with the existing api model.

Using the same api model I had used to create the cluster in the first place, the cluster creation was failing with the following error message:

` "code": "Conflict",
                             "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n
                             \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n  
                             {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'k8s-master-18526365-vmssCSE'.
                             Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=36\\n[stdout]\\nThu Oct 22 00:25:21 UTC 2020,k8s-master-18526365-vmss000000\\n\\n[stderr]\\n\\\"\\r\\n\\r\\n
                             More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"`

I had `"enableEncryptionWithExternalKms": true` and when I removed that config, the cluster creation was successful.

**Steps To Reproduce**

My api model looks like this:

`{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.17.0",
      "kubernetesConfig": {
        "kubeletConfig": {
            "--tls-cipher-suites": <REDACTED>
        },
        "apiServerConfig": {
            "--tls-cipher-suites": <REDACTED>
        },
        "enableEncryptionWithExternalKms": true,
        "etcdDiskSizeGB": "30",
        "azureCNIURLWindows": "https://acs-mirror.azureedge.net/cni/azure-vnet-cni-windows-amd64-v1.0.30.zip",
        "addons": [
          {
            "name": "tiller",
            "enabled": true
          }
        ]
      }
    },
    "masterProfile": {
      "availabilityProfile": "VirtualMachineScaleSets",
      "count": 1,
      "dnsPrefix": <REDACTED>,
      "vmSize": "Standard_D2_v2",
      "osDiskSizeGB": 30
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool",
        "count": 1,
        "vmSize": "Standard_D2_v2",
        "osType": "Windows",
        "osDiskSizeGB": 128
      }
    ],
    "windowsProfile": {
      "adminUsername": <REDACTED>,
      "adminPassword": <REDACTED>,
      "windowsPublisher": "MicrosoftWindowsServer",
      "windowsOffer": "WindowsServerSemiAnnual",
      "windowsSku": "Datacenter-Core-1809-with-Containers-smalldisk",
      "imageVersion": "1809.0.20190613",
      "windowsDockerVersion": "19.03.5"
    },
    "linuxProfile": {
      "adminUsername": <REDACTED>,
      "ssh": {
        "publicKeys": [
          {
            "keyData": <REDACTED>
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": <REDACTED>
      "keyvaultSecretRef": {
        "vaultId": <REDACTED>,
        "secretName": <REDACTED>
      },
      "objectId": <REDACTED>
    },
    "certificateProfile": {
      "caCertificate": <REDACTED>,
      "caPrivateKey": <REDACTED>,
      "apiServerCertificate": <REDACTED>,
      "apiServerPrivateKey": <REDACTED>
      "clientCertificate": <REDACTED>
      "clientPrivateKey": <REDACTED>,
      "kubeConfigCertificate": <REDACTED>
      "kubeConfigPrivateKey": <REDACTED>
      "etcdServerCertificate": <REDACTED>,
      "etcdServerPrivateKey": <REDACTED>
      "etcdClientCertificate": <REDACTED>,
      "etcdClientPrivateKey": <REDACTED>
      "etcdPeerCertificates": [
        <REDACTED>
      ],
      "etcdPeerPrivateKeys": [
        <REDACTED>
      ]
    }
  }
}
`

**Expected behavior**
Successful cluster creation.

**AKS Engine version**
0.45
**Kubernetes version**
1.17.0
**Additional context**

**Comment by bridgetkromhout** [comment]
Hi, @oluwadeyi - Thanks for reaching out with this bug report. The AKS Engine project is being deprecated, and will receive minimal updates at this point. Please see https://github.com/Azure/aks-engine#project-status for details and for our recommendations for moving forward on AKS or CAPZ.
