### ISSUE TITLE
Deployment fails when Role Assignment already exists 

### ISSUE THREAD

**Issue by amankohli** [Azure/aks-engine#4014]
Using MSI to deploy the AKS engine cluster. The cluster deploys fine but the arm template throws the below error:
Deployment fails when Role Assignment already exists
ge\\\":\\\"{\\\\r
\\\\\\\"error\\\\\\\": {\\\\r
\\\\\\\"code\\\\\\\": \\\\\\\"RoleAssignmentExists\\\\\\\",\\\\r
\\\\\\\"message\\\\\\\": \\\\\\\"The role assignment already exists.\\\\\\\"\\\\r
}\\\\r
}\\\"}]
**Steps To Reproduce**
Below is the API Model:
{
             "apiVersion": "vlabs",
             "properties": {
                "orchestratorProfile": {
                "orchestratorType": "Kubernetes",
                "orchestratorRelease": "'$version'",
                "kubernetesConfig": {
                "useManagedIdentity": true,
                "userAssignedID": "/subscriptions/'$subscription'/resourceGroups/'$resourceGroup'/providers/Microsoft.ManagedIdentity/userAssignedIdentities/'$msiName'",
                "networkPlugin": "kubenet",
                "privateCluster": {
                    "enabled": true
                    }
                }
                },
                "masterProfile": {
                    "count": 3,
                    "dnsPrefix": "k8s'$environment'2dc",
                    "vmSize": "Standard_D2s_v3",
                    "OSDiskSizeGB": 100,
                    "vnetSubnetId": "/subscriptions/'$subscription'/resourceGroups/'$resourceGroup'/providers/Microsoft.Network/virtualNetworks/'$vnetName'/subnets/'$subnetName'",
                    "firstConsecutiveStaticIP": "'$ipRange'"
                    },
                "agentPoolProfiles": [
                {
                    "name": "node",
                    "count": 9,
                    "vmSize": "Standard_D8s_v3",
                    "OSDiskSizeGB": 100,
                    "vnetSubnetId": "/subscriptions/'$subscription'/resourceGroups/'$resourceGroup'/providers/Microsoft.Network/virtualNetworks/'$vnetName'/subnets/'$subnetName'"
                }
                ],
                "linuxProfile": {
                    "adminUsername": "ubuntu",
                    "ssh": {
                        "publicKeys": [
                        {
                            "keyData": "'$sshkey'"
                        }
                        ]
                    }
                }
            }
            }

**Expected behavior**
The template shouldn't error out

**AKS Engine version**

v0.57.0
**Kubernetes version**
1.15

**Additional context**
Found a similar bug on AKS:
https://github.com/Azure/AKS/issues/548

**Comment by bridgetkromhout** [comment]
Hi, @amankohli - Thanks for reaching out with your input. The AKS Engine project is being deprecated, and will receive minimal updates at this point. Please see https://github.com/Azure/aks-engine#project-status for details and for our recommendations for moving forward.
