### ISSUE TITLE
Only create `volumeplugins` when it does not exist

### ISSUE THREAD

**Issue by AbelHu** [Azure/aks-engine#4018]
**Describe the issue**
A clear and concise description of the issue
Only create `volumeplugins` when it does not exist so reduce error logs as below.
```
mkdir : An item with the specified name C:\k\volumeplugins already exists.
At C:\k\kubeletstart.ps1:36 char:1
+ mkdir $global:VolumePluginDir
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\k\volumeplugins:String) [New-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand
```

https://github.com/Azure/aks-engine/blob/d0c09712cd5a1024c34843eb6ebf7fa02380fa81/staging/provisioning/windows/kubeletstart.ps1#L33

```
# Calculate some local paths
$global:VolumePluginDir = [Io.path]::Combine($global:KubeDir, "volumeplugins")
mkdir $global:VolumePluginDir
```

**AKS Engine Version***
v0.57.0

**Kubernetes Version**
v1.16.13

**Gatekeeper Version**

**To Reproduce**

**Expected behavior**
Do not call mkdir to create volumeplugins when it exists.

**Screenshots**

**Additional context**

**Please don't remove the text below**
Notify @az-policy-kube

**Comment by bridgetkromhout** [comment]
Hi, @AbelHu. Thanks for reaching out with your input. The AKS Engine project is being deprecated, and will receive minimal updates at this point. Please see https://github.com/Azure/aks-engine#project-status for details and for our recommendations for moving forward.
