### ISSUE TITLE
Disable windows auto update

### ISSUE THREAD

**Issue by khenidak** [Azure/aks-engine#402]
ref: https://kubernetes.slack.com/archives/C0SJ4AFB7/p1548872012173700

Windows VMs are currently set to auto update. Come patch Tuesday an entire FD/UD/Zone can go down as machines updates themselves. Windows autoupdates should be turned off (or use external tools to manage windows servers).

@PatrickLang @craiglpeters

**Comment by draiche** [comment]
We would also be very interested in this being added. Ideally we would just be able to set the "enableAutomaticUpdates" flag of "osProfile/windowsConfiguration".
