### ISSUE TITLE
The Addpool and Scale operations should support ManagedIdentiy based Authentication also

### ISSUE THREAD

**Issue by surajrana93** [Azure/aks-engine#4027]
**Describe the request**
Allow Upgrade, Addpool and Scale operations to get their AuthenticationContext from the Managed Identity of the host its running on directly.

**Explain why AKS Engine needs it**

The authentication method used for the above operations client_secret, cli, client_certificate, and device. However our preferred Authentication mechanism is Managed Service Identity (MSI) and this model is quite common for services running in Azure. 

**Describe the solution you'd like**
The Aks Engine library should be able to pick the Manged Identity of the resource and use it for authentication to Azure.

**Describe alternatives you've considered**
We have considered triggering Az login and then using then using 'cli' flag. However this is not always feasible as not every runtime would have the Az Cli present or be in our control in that way. We are also trying to use these operation programmatically and we dont want the added complication of having the program run a script or create a shell process(or something equivalent) where we have to set the AuthenticationContext and then use AksEngine.

**Additional context**
We have done some initial investigation and it seems enabling this feature should be relatively simple , as the authentication library Aks Engine is using can support this. We can also take up this work if the feature request gets complicated.

**Comment by vavenk-ms** [comment]
The adal library [provides functions to get the tokens using MSI](https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L687-L697). It could be used to create an azure client similar to how it's [created using client secret](https://github.com/Azure/aks-engine/blob/79de20bd76fe7c7277805a982b36aa417df71766/pkg/armhelpers/azureclient.go#L188-L208).

**Comment by bridgetkromhout** [comment]
Hi, @surajrana93 - I see that you received one idea of how to proceed. Thanks for reaching out. We will resolve this issue now; if you have ongoing questions about AKS Engine, please be aware that it is being deprecated, so we are not adding features at this time. Please see https://github.com/Azure/aks-engine#project-status for details; we recommend using AKS or in some cases CAPZ instead.
