### ISSUE TITLE
Container monitoring - able to specify log analytics agent to log analytics gateway

### ISSUE THREAD

**Issue by gangyi89** [Azure/aks-engine#4046]
We are currently hosting 2 kubernetes clusters, 1 in azure cloud (aks) and the other azure stack (aks-engine).
We would like to have a centralized containerized monitoring view in our azure cloud.

Are we able to specify aks-engine log analytics agent to send logs to a log analytics gateway (which will eventually be forwarded to azure cloud)

Based on below reference documentation, to include the proxy address, port, username and password.

---

manual setup of log analytics agent documentation: 
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/agent-linux
```
sudo sh ./omsagent-*.universal.x64.sh --upgrade -p https://<proxy user>:<proxy password>@<proxy address>:<proxy port> -w <workspace id> -s <shared key>
```

**Comment by bridgetkromhout** [comment]
Hi, @gangyi89 -  thanks for reaching out. If the features you want are not available in AKS Engine, please be aware that it is being deprecated. Please see https://github.com/Azure/aks-engine#project-status for details; we recommend using AKS or in some cases CAPZ instead.
