### ISSUE TITLE
Switch to "control-plane" labels and taints for v1.20 or afterward

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#4050]
**Describe the bug**

[Kubernetes v1.20.0-beta.2](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#no-really-you-must-read-this-before-you-upgrade) is where the transition to more inclusive language for control plane elements has begun, by deprecating labels and taints. A future release will remove support for the deprecated items. AKS Engine should adjust its templates and label-nodes.sh script to match.

See the [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#no-really-you-must-read-this-before-you-upgrade) for details.

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by mboersma** [comment]
As best I can tell, "stage 2" of implementing this change lands with Kubernetes 1.24. This seems to imply we will see things break unless we implement this change:

> During the second stage the "master" label will be removed from new Nodes. User infrastructure must only manage the "control-plane" label at that point. New nodes will also have the "node-role.kubernetes.io/control-plane:NoSchedule" taint.

See https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md

So I think we still need to address this at least for Kubernetes 1.24 in AKS Engine.

**Comment by bridgetkromhout** [comment]
> So I don't think there are any action items here since 1.24 works and it's the last dance for aks-engine.

Thanks, @mboersma - resolving this issue.
