### ISSUE TITLE
State of microsoft-oms-agent-k8s extension in aks-engine deployments

### ISSUE THREAD

**Issue by JoaquimFreitas** [Azure/aks-engine#406]
**Is this a request for help?**:
**YES**
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
**FEATURE REQUEST**
---

**What version of aks-engine?**:
**0.28.1** **0.29.1**
---

**Kubernetes version**:
**1.13**

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

https://github.com/Azure/aks-engine/tree/master/extensions/microsoft-oms-agent-k8s  
Hi, what is the current state of the `microsoft-oms-agent-k8s` extension in aks-engine deployments?  
Mainly for hybrid cluster deployments?

Can we make this additional deployment or not?

Thanks.

**Comment by CecileRobertMichon** [comment]
@JackQuincy who added the README with the "Currently doesn't work" statement last year to see if he remembers what context was. 

Also @rashmichandrashekar who added https://github.com/Azure/aks-engine/blob/master/docs/topics/monitoring.md and mostly owned the Container-monitoring add-on implementation in aks-engine.

I suspect that the extension doc is outdated and the monitoring addon is what you're looking for.

**Comment by rashmichandrashekar** [comment]
@JoaquimFreitas : This is the right link as Cecile mentioned: https://github.com/Azure/aks-engine/blob/master/docs/topics/monitoring.md
Right now we do not support monitoring for windows vms.

Please let me know if you have any questions about onboarding to a cluster with Linux VMs.
