### ISSUE TITLE
Null pointer error when running akg-engine deploy

### ISSUE THREAD

**Issue by georgeteo** [Azure/aks-engine#4066]
**Describe the bug**

When running `aks-engine deploy`, there is a null pointer exception:
```
aks-engine deploy --dns-prefix contoso-apple \
    --resource-group contoso-apple \
    --location westus2 \
    --api-model examples/kubernetes.json \
    --auto-suffix

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x154b42e]

goroutine 1 [running]:
github.com/Azure/aks-engine/pkg/api.(*OrchestratorProfile).IsKubernetes(...)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/types.go:1917
github.com/Azure/aks-engine/pkg/api.convertVLabsProperties(0xc0008210e0, 0xc000715e10, 0xc0000b7a00, 0x0, 0x11)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/convertertoapi.go:69 +0x12e
github.com/Azure/aks-engine/pkg/api.ConvertVLabsContainerService(0xc00080ea80, 0x400, 0x60b, 0xc0000b7b38, 0x2)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/convertertoapi.go:38 +0x249
github.com/Azure/aks-engine/pkg/api.(*Apiloader).LoadContainerService(0xc0000b7d48, 0xc0003ba700, 0x40b, 0x60b, 0xc000802d18, 0x5, 0x0, 0x0, 0xc0003ba700, 0x40b, ...)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:122 +0x35b
github.com/Azure/aks-engine/pkg/api.(*Apiloader).DeserializeContainerService(0xc0000b7d48, 0xc0003ba700, 0x40b, 0x60b, 0x0, 0x0, 0x0, 0x7, 0x255cd98, 0x1, ...)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:83 +0x24f
github.com/Azure/aks-engine/pkg/api.(*Apiloader).LoadContainerServiceFromFile(0xc0000b7d48, 0x7ffeefbff151, 0xf, 0x12f0000, 0x0, 0x7, 0x7ffeefbff13d, 0x7, 0x0, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:43 +0x20a
github.com/Azure/aks-engine/cmd.(*deployCmd).loadAPIModel(0xc0000d2000, 0x0, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/cmd/deploy.go:191 +0xa1
github.com/Azure/aks-engine/cmd.newDeployCmd.func1(0xc000833900, 0xc0000d6960, 0x0, 0xa, 0x0, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/cmd/deploy.go:81 +0x9d
github.com/spf13/cobra.(*Command).execute(0xc000833900, 0xc0000d6820, 0xa, 0xa, 0xc000833900, 0xc0000d6820)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:762 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000833180, 0x27ea3c0, 0xc000120008, 0xc00010c058)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/Users/jackfrancis/work/src/github.com/Azure/aks-engine/main.go:17 +0x8e
```

I am 
- running on macOS Cataline version 10.15.7 
- installed `aks-engine` via https://github.com/Azure/aks-engine/releases. 

**Steps To Reproduce**

On macOs Catalina, 
- `wget https://github.com/Azure/aks-engine/releases/download/v0.57.0/aks-engine-v0.57.0-darwin-amd64.tar.gz`
` tar -zxf aks-engine-v0.57.0-darwin-amd64.tar.gz`
- Copy https://github.com/Azure/aks-engine/blob/master/examples/kubernetes.json to local file. Specifically, the api model is:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v3"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    }
  }
}
```
- Run 
```
aks-engine deploy --dns-prefix contoso-apple \
    --resource-group contoso-apple \
    --location westus2 \
    --api-model examples/kubernetes.json \
    --auto-suffix
```

**Expected behavior**

It should work per https://github.com/Azure/aks-engine/blob/master/docs/tutorials/quickstart.md

**AKS Engine version**

0.57.0

**Kubernetes version**

Not sure

**Additional context**

This works if I `git clone git@github.com:Azure/aks-engine.git` and `go build` and run from source.

**Comment by helshabini** [comment]
##Same issue replicated on:
ProductName:    macOS
ProductVersion: 11.0.1
BuildVersion:   20B29

##Installation:
`brew install Azure/aks-engine/aks-engine`

##Command:
`aks-engine deploy --dns-prefix $rgName \
>     --resource-group $rgName \
>     --location $location \
>     --subscription-id $subscriptionId \
>     --api-model aks-engine.json \
>     --auto-suffix`

##Result:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x154b19e]

goroutine 1 [running]:
github.com/Azure/aks-engine/pkg/api.(*OrchestratorProfile).IsKubernetes(...)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/types.go:1916
github.com/Azure/aks-engine/pkg/api.convertVLabsProperties(0xc000441170, 0xc00003ac30, 0xc00051ba00, 0x0, 0x11)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/convertertoapi.go:69 +0x12e
github.com/Azure/aks-engine/pkg/api.ConvertVLabsContainerService(0xc000688660, 0x400, 0x6ba, 0xc00051bb38, 0x2)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/convertertoapi.go:38 +0x249
github.com/Azure/aks-engine/pkg/api.(*Apiloader).LoadContainerService(0xc00051bd48, 0xc000346700, 0x4ba, 0x6ba, 0xc000480288, 0x5, 0x0, 0x0, 0xc000346700, 0x4ba, ...)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:122 +0x35b
github.com/Azure/aks-engine/pkg/api.(*Apiloader).DeserializeContainerService(0xc00051bd48, 0xc000346700, 0x4ba, 0x6ba, 0x0, 0x0, 0x0, 0xa, 0x255a738, 0x1, ...)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:83 +0x24f
github.com/Azure/aks-engine/pkg/api.(*Apiloader).LoadContainerServiceFromFile(0xc00051bd48, 0x7ffeefbffa05, 0xf, 0x12f0000, 0x0, 0xa, 0x7ffeefbff9b7, 0xa, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:43 +0x20a
github.com/Azure/aks-engine/cmd.(*deployCmd).loadAPIModel(0xc000010000, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/cmd/deploy.go:191 +0xa1
github.com/Azure/aks-engine/cmd.newDeployCmd.func1(0xc00047ea00, 0xc0001c68f0, 0x0, 0xb, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/cmd/deploy.go:81 +0x9d
github.com/spf13/cobra.(*Command).execute(0xc00047ea00, 0xc0001c6840, 0xb, 0xb, 0xc00047ea00, 0xc0001c6840)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:762 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00047e280, 0x27e7400, 0xc0000b8008, 0xc0000a4058)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /Users/jackfrancis/work/src/github.com/Azure/aks-engine/main.go:17 +0x8e`

**Comment by jackfrancis** [comment]
Hi folks, what you're observing is that a recent documentation refresh happened before a code release. Stand by soon for a v0.58.0 release that includes working code of these recently documented UX conveniences.

(For the record, the reason for the nil exception is that in v0.57.0 your API model input *must* include an `orchestratorProfile` config object, and the `orchestratorType` *must* be equal to `"Kubernetes"`. The example file at HEAD in the codebase now omits that configuration, which works because of recent changes. These changes streamline the set of required configuration that a user needs to build a simple Kubernetes cluster.)

Sorry for the inconvenience :/
