### ISSUE TITLE
Enable DSR support in Windows nodes.

### ISSUE THREAD

**Issue by AbelHu** [Azure/aks-engine#4079]
**Describe the request**
kubeproxy since 1.19  with Windows 10C supports DSR now. To support Calico Windows, we need to allow users to enable DSR.

**Explain why AKS Engine needs it**
Support Calico Windows.

**Describe the solution you'd like**
1. Add `EnableWindowsDSR` in WindowsProfile with default value `false`. We can consider to change the default value to `true` later.

2. In the file `parts/k8s/kuberneteswindowssetup.ps1`

```
# DSR
$global:EnableDSR = [System.Convert]::ToBoolean("{{WrapAsVariable "enableWindowsDSR" }}");
```

3. In method `Write-KubeClusterConfig` in the file `parts/k8s/kuberneteswindowsfunctions.ps1`
```

    $Global:ClusterConfiguration | Add-Member -MemberType NoteProperty -Name Kubernetes -Value @{
        ...
        Network      = @{
            ServiceCidr = $global:KubeServiceCIDR;
            ClusterCidr = $global:KubeClusterCIDR;
            DnsIp       = $KubeDnsServiceIp;
            EnableDSR   = $global:EnableDSR
        };
        ...
    }
```

4. In the file `staging/provisioning/windows/kubeproxystart.ps1`
```
$features = @()

# add dualstack feature gate if dualstack enabled
$isDualStackEnabled = ("IPv6DualStack=true" | ? { $Global:ClusterConfiguration.Kubernetes.Kubelet.ConfigArgs -match $_ }) -ne $null
if ($isDualStackEnabled) {
   $features += @("'IPv6DualStack=true'")
}

# add dsr feature gate if dsr enabled
if ($Global:ClusterConfiguration.Kubernetes.Network.EnableDSR) {
    $features += @("'WinOverlay=false'")
    $features += @("'WinDSR=true'")
    $global:KubeproxyArgList += @("--enable-dsr=true")
}

if ($features.Count -gt 0) {
    $global:KubeproxyArgList += @("--feature-gates=" + ($features -join ","))
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by AbelHu** [comment]
We may need to do same things as kubeletstartup.ps1 to read additional configs directly from $Global:ClusterConfiguration

**Comment by jsturtevant** [comment]
looks good. If it is on and the CNI doesn't support it what happens? 

> We may need to do same things as kubeletstartup.ps1 to read additional configs directly from $Global:ClusterConfiguration

Not sure I follow, Are there settings in kubelet that are required?

**Comment by AbelHu** [comment]
@jsturtevant From what I know, this feature is related to Windows OS. DSR needs 2019 11C and k8s 1.20. I think that it does not rely on cni. 

No. It only needs to set this in kubeproxy.
