### ISSUE TITLE
Add option to dynamically set CPU reserves for Windows nodes based on CPU count

### ISSUE THREAD

**Issue by marosset** [Azure/aks-engine#4083]
We recently discovered that due to some changes in behavior in how container limits are enforced in Windows nodes (starting with v1.18.0) Windows node should set CPU reserves to help processes running on the node do not get starved.

Investigations have shown that these reserves should be set dynamically based on the number of cores on the node.

**Proposal**
 Add a new `windowsProfile.dynamicallySetCPUReserves` config to the (WindowsProfile)[https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#windowsProfile] cluster definition config section.

If set to `true` logic inside kubeletstart.ps1 would query the node to determine the core count, compute an appropriate reserves value, and add that value to arguments used to launch the kubelet.

Proposed values are
| Reserves  | Core Count  |
|---|---|
| 500m | less than 4 cores |
| 1 | between 8  and 16 cores |
| 2 | more than 16 cores |

By computing the value in kubeletstart.ps1 on the node ew avoid the need to map SKUs to core counts in aks-engine/AKS code which will increase maintainability.

If set to `false` CPU reserves will not be set dynamically.
**note**: users can specify static reserves by updating the (kubelet config)[https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#kubeletconfig] section in the cluster definition file.

**Comment by marosset** [comment]
@jsturtevant @keikhara @AbelHu  PTAL.
I want to make sure any changes we make here will work for AKS as well.

**Comment by AbelHu** [comment]
@marosset , could aks-engine compute the value outside of the kubeletstart.ps1 and let kubeletstart.ps1 read the value from `kubeclusterconfig.json`?

**Comment by jsturtevant** [comment]
@AbelHu I think that should still work as long as this new flag is set to false. 

There are two different flags that will give similar effects in [Windows (in Linux there is a difference but for windows it is semantic)](https://github.com/Azure/aks-engine/pull/3975#discussion_r513949980): `--system-reserved` and `--kube-reserved` for memory reserves we use `--system-reserved`. 

https://github.com/Azure/aks-engine/blob/6d292f1ae1598be81a7250e39d6dd87a81fd5843/pkg/api/defaults-kubelet.go#L75

We should make sure we are using the same reserve setting in at least in aks-engine.

**Comment by AbelHu** [comment]
@jsturtevant, AKS is using kube-reserved for both cpu and memory.

**Comment by AbelHu** [comment]
Here is the Resource reservations in AKS: https://docs.microsoft.com/en-us/azure/aks/concepts-clusters-workloads#resource-reservations

**Comment by bridgetkromhout** [comment]
Consulting with @marosset & @justindavies, I'm told that this is a "nice to have", not a requirement. Given the deprecation of AKS Engine, I'm closing this issue now.
