### ISSUE TITLE
KUBE_VERSION  1.19.x gives 'Cannot connect to the Docker daemon' error when doing Docker in Docker (dind) build in jenkins

### ISSUE THREAD

**Issue by hectoralicea** [Azure/aks-engine#4091]
**Describe the bug**
KUBE_VERSION  1.19.3, actually also 1.19.1, gives 'Cannot connect to the Docker daemon' error when doing Docker in Docker (dind) build in jenkins

**Steps To Reproduce**
Build an AKS using 1.19.3 kube version, install helm chart  jenkinsci/jenkins --version 3.0.2, and create a docker in docker pipeline which creates a docker image inside a jenkins slave.  Helm chart can be found here:  https://github.com/jenkinsci/helm-charts

**Expected behavior**
KUBE_VERSION 1.18.10  works just fine.  but when the only thing I change in the build is building an AKS cluster using 1.19.3 I get these errors:  I have obfuscated for security purposes.

```
+ docker rmi hazrp*********.azurecr.io/***.***/ria/ria-jsonify-svc:0.0.1
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
+ true
[Pipeline] isUnix
[Pipeline] sh
+ docker build -t hazrp*********.azurecr.io/***.***/ria/ria-jsonify-svc:0.0.1.1 -t hazrp*********.azurecr.io/***.***/ria/ria-jsonify-svc:0.0.1 -t hazrp*********.azurecr.io/***.***/ria/ria-jsonify-svc:latest --build-arg 'ENV=dev' --build-arg 'DOCKER_REGISTRY=hazrp*********.azurecr.io' --build-arg 'REGISTRY_REPOSITORY=***.***' --build-arg 'SERVICE_NAME=ria-jsonify-svc' --build-arg 'SERVICE_GROUP=ria' --build-arg 'SERVICE_BUILD=0.0.1.1' --build-arg 'SERVICE_VERSION=0.0.1' -f ./docker/Dockerfile .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```

**AKS Engine version**
1.19.3 

**Kubernetes version**
1.19.3 

**Additional context**
Was some security hardening added in 1.19.3 which caused this issue?  Is there a work around?

**Comment by hectoralicea** [comment]
anybody have an update on this?

**Comment by anhdle14** [comment]
From 1.19 containerd became the standard for AKS.

So there are some tradeoffs that being made from AKS. https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#containerd-limitationsdifferences. 

Basically DinD has been disable because of security

**Comment by moimart1** [comment]
I have the same issue. Does a workaround exist?

**Comment by hectoralicea** [comment]
> I have the same issue. Does a workaround exist?

When you build your AKS cluster make sure you use a Kubernetes version 1.18.x version such as 1.18.10.
Otherwise, if you want to use kubernetes version 1.19.1 or later you will need to use "podman in docker" rather than "docker in docker".  The podman docker image I use in jenkins is: registry.redhat.io/rhel8/podman

**Comment by bridgetkromhout** [comment]
Looks like workarounds have been offered; also, looks like this issue may have been about AKS, not AKS Engine. Resolving.
