### ISSUE TITLE
Update adal package version

### ISSUE THREAD

**Issue by vavenk-ms** [Azure/aks-engine#4092]
**Describe the request**

Update the verison of the adal package (github.com/Azure/go-autorest/autorest/adal) aks-engine uses to v0.9.6 

**Explain why AKS Engine needs it**

The latest version of the adal package has a fix for an issue with acquiring token using MSI from an Azure App Service environment. https://github.com/Azure/go-autorest/issues/574

This would be helpful to implement MSI auth method as requested by #4027 

**Describe the solution you'd like**

Upgrade the adal package version aks-engine consumes to v0.9.6

**Describe alternatives you've considered**

**Additional context**

**Comment by bridgetkromhout** [comment]
Resolved in https://github.com/Azure/aks-engine/pull/4093. Thanks!
