### ISSUE TITLE
[Question] Master nodes with VirtualMachineScaleSets

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#4095]
Per https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#masterprofile

availabilityProfile | no | Supported values are AvailabilitySet (default) and VirtualMachineScaleSets (still under development: upgrade not supported; requires Kubernetes clusters version 1.10+ and agent pool availabilityProfile must also be VirtualMachineScaleSets).
-- | -- | --

Just to confirm is VMSS recommended for master nodes? The doc says it is still under development.

**Comment by jackfrancis** [comment]
No, not recommended, I would still classify this as experimental. Because control plane VMs are more or less statically defined in AKS Engine (you can't scale them), the stablest choice is the default AvailabilitySet.

**Comment by zhiweiv** [comment]
ok, thanks.
