### ISSUE TITLE
[Question] Container runtime choice

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#4096]
Due to some limitations we are switching workloads from AKS to AKS-Engine, AKS has set it's default runtime to ContainerD since 1.19. 
1. Will AKS-Engine follow this?
2. Is ContainerD recommended in AKS-Engine 1.19? We want to keep same configuration with AKS.
3. We have both Linux Pool and Windows Pool, is possible to use ContainerD for Linux Pool and docker for Windows Pool?

**Comment by jackfrancis** [comment]
1. We are waiting to validate containerd against all Windows scenarios before making containerd the default
  - cc @marosset and @jsturtevant to add any color here
2. We recommend containerd for 1.19 for Linux node pools
3. That's not possible, unfortunately we only support a single CRI across all pools (including control plane as well)

containerd *does* work with Windows node pools, but there are more edge cases. Can you provide a description of your containerd + Windows use case and we can chime in if there are concerns?

**Comment by zhiweiv** [comment]
We run asp.net web/.net fx application in Windows pool, no specific case for containerd + Windows, just want to keep consistent infra with AKS.

Seems k8s 1.20 released with Containerd GA for Windows, I will try Containerd on both Linux/Windows in AKS-Engine later.

**Comment by zhiweiv** [comment]
Just FYI, @jackfrancis 

We got follwing limitations in AKS
1 We want to turn off Window Defender by default due to https://github.com/Azure/AKS/issues/1944
2 We want to pre cache Windows base image for faster node scale, see https://github.com/Azure/AKS/issues/1532
3 The most important part,  AKS doesn't support basic load balancer for Windows pool, see https://github.com/Azure/AKS/issues/1888

**Comment by marosset** [comment]
I'd recommend using v1.20 in you want to use contianerD with Windows nodes in your cluster.

If you want pre-cache Windows base images you can build your own VHDs with these images caches and use these for your aks-engine deployments.
Here is some documentation on how to use managed images or images from a Shared Image Gallery for our Windows nodes: https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#windows-images

We also have the [packer](www.packer.io) files and scripts used by the aks-engine team to produce our Windows VHDs checked in here:
- https://github.com/Azure/aks-engine/blob/master/vhd/packer/windows-vhd-builder.json
- https://github.com/Azure/aks-engine/blob/master/vhd/packer/configure-windows-vhd.ps1

You can start with the images published by aks-engine team found under and 
- offer: microsoft-aks
- publisher: aks-windows

and add any additional customizations.
