### ISSUE TITLE
[Question] Ephemeral OS support

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#4097]
Ephemeral OS has reach GA in AKS, what is the status in AKS-Engine? It says **Experimental** in https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#ephemeral-os-disks.

This feature is useful for faster node scale.

**Comment by jackfrancis** [comment]
Hi @zhiweiv, if you understand the risks of using Ephemeral disk, there's nothing from an AKS Engine perspective that would prevent you from using it, and suitable Kubernetes scenarios (no stateless data) match well with it. Agree it can unlock faster node scale.

Also look at this pre-alpha project that aims to improve node scaling by taking a snapshot of a VMSS instance OS image and updating the VMSS model to use it:

https://github.com/jackfrancis/kamino

**Comment by zhiweiv** [comment]
Thanks for the information, I will evaluate them both.
