### ISSUE TITLE
confusing errors in metrics-server pod logs 'unable to fetch pod metrics'

### ISSUE THREAD

**Issue by Zeka13** [Azure/aks-engine#4107]
```
kubectl get hpa -n production
NAME              REFERENCE        TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
api-autoscaling   Deployment/api   <unknown>/50%   2         30        2          3h
```

meanwhile Logs from metrics-server for all pods printing this error
```
E1210 15:33:26.398909       1 reststorage.go:160] unable to fetch pod metrics for pod production/api-5b97fcc46f-phkxm: no metrics known for pod
E1210 15:33:26.398931       1 reststorage.go:160] unable to fetch pod metrics for pod production/api-5b97fcc46f-gh5m2: no metrics known for pod
```

**AKS Engine version**
0.57

**Kubernetes version**
1.19.2

Please help, thx in advance

**Comment by jackfrancis** [comment]
@Zeka13 is this error intermittent? Does it clear up if you manually kill the metrics-server pod(s) running in kube-system and let the addon-manager recreate new ones?

**Comment by Zeka13** [comment]
@jackfrancis this errors allways like this, even if I delete Deployment completly and addon-manager recreate a new metrics-server pods errors still here ... I found some solutions online, like add --version=2 to metrics-server command, but I have no idea how to apply changes to Deployment, addon-manager always erase my changes

**Comment by Zeka13** [comment]
So, first of all, my pad, I was getting unknown because I did not setup resources for container correctly

Theese errors were just confusing me. I succesefully fixed them after upgrading metrics-server to 0.4.1 by manually edit yml inside masters addon-manager directory

**Comment by jackfrancis** [comment]
@Zeka13 thanks for the update

Sounds like updating the current aks-engine-provided metrics-server version would be a good idea.

What version of Kubernetes are you successfully using 0.4.1 with?

cc @CecileRobertMichon @mboersma @xuto2

**Comment by jackfrancis** [comment]
I have a PR here that will be able to do a quick (~90 min) functional test of metrics-server v0.4.1 running on 1.19 and 1.20:

https://github.com/Azure/aks-engine/pull/4127

**Comment by rogaha** [comment]
@Zeka13 I'm having the same issue. `--v2` seems to fix the issue, but something erases my changes after a few seconds. Can you please share the way you successfully updated the `metrics-server` image version/config?

**Comment by Zeka13** [comment]
@rogaha  it is possible by ssh to each master and change yaml on each of them in /etc/kubernetes/addon .. something :)
