### ISSUE TITLE
Enable and document SCTP support

### ISSUE THREAD

**Issue by aramase** [Azure/aks-engine#4108]
**Describe the request**
SCTP support for Services, Pod, Endpoint, and NetworkPolicy is finally GA as of Kubernetes 1.20 (https://github.com/kubernetes/enhancements/pull/2107) after being introduced in 1.12. 

- [ ] Test SCTP support with clusters in Azure. Make necessary changes to enable the support. 
- [ ] Add e2e tests for SCTP in aks-engine.
- [ ] Document how to use and any limitations.
- [ ] Enable testing in prow with aks-engine clusters.

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by firefly2000** [comment]
Wonder if this is supported with 1.21 release and how do I enable this? Thank you!

**Comment by thomsonjames** [comment]
It still looks like they block it during security hardening anyway. You can't bind an SCTP port from a workload.  https://docs.microsoft.com/en-us/azure/aks/security-hardened-vm-host-image#what-is-configured
