### ISSUE TITLE
Add AKSEngineVersion tag in agent VMSS templates

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#411]
VMSS agent VMs are missing the `"aksEngineVersion" : "[parameters('aksEngineVersion')]",` tag that VMAS VMs have (https://github.com/Azure/aks-engine/blob/master/parts/k8s/kubernetesmasterresourcesvmss.t#L415-L416).

Let's add it in these two places for VMSS:
https://github.com/Azure/aks-engine/blob/master/parts/k8s/kubernetesagentresourcesvmss.t#L24
https://github.com/Azure/aks-engine/blob/master/parts/k8s/kuberneteswinagentresourcesvmss.t#L24

**Comment by mathieu-benoit** [comment]
Hi @CecileRobertMichon, thanks for the pointers to implement this, I just submitted this PR #413. Let me know if you have any feedback. Thanks1

**Comment by marcoboffi** [comment]
When I upgrade k8s version of an AKS nodepool, does upgrade procedure modify value of this tag?
