### ISSUE TITLE
aks-engine applies default feature gates instead of honoring user-defined feature gates

### ISSUE THREAD

**Issue by chewong** [Azure/aks-engine#4112]
**Describe the bug**

I explictly set `ExecProbeTimeout=true` in kubelet feature gates and run `aks-engine generate` but the generated API model does not reflect that:

```json 

        "kubeletConfig": {
          ...
          "--feature-gates": "ExecProbeTimeout=true,KubeletPodResources=false"
          ...
```

The generated API model has the following feature gates:

```json
        "kubeletConfig": {
          ...
          "--feature-gates": "ExecProbeTimeout=false,KubeletPodResources=false,RotateKubeletServerCertificate=true",
          ...
```

**Expected behavior**

```json
        "kubeletConfig": {
          ...
          "--feature-gates": "ExecProbeTimeout=true,KubeletPodResources=false,RotateKubeletServerCertificate=true",
          ...
```

**AKS Engine version**

v0.58.0

**Kubernetes version**

v1.20

**Additional context**

**Comment by jackfrancis** [comment]
which feature gates? kubelet? apiserver?

**Comment by jackfrancis** [comment]
nm `ExecProbeTimeout` is a kubelet-only feature gate

**Comment by jackfrancis** [comment]
This UT suggests that the `setKubeletConfig` foo is doing what we expect, so I think the defaults kubelet enforcement flow is sane:

https://github.com/Azure/aks-engine/blob/master/pkg/api/defaults-kubelet_test.go#L969

I'll repro and see what's going on

**Comment by jackfrancis** [comment]
nevermind again, looks like we didn't have the correct UT!

https://github.com/Azure/aks-engine/pull/4114
