### ISSUE TITLE
Use the kubelet priority flag for Windows kubelet process

### ISSUE THREAD

**Issue by jsturtevant** [Azure/aks-engine#4130]
**Describe the request**
We should use the new flag `windows-priorityclass` for kubelet for version of kubernetes that it is available for: https://github.com/kubernetes/kubernetes/pull/96051

**Explain why AKS Engine needs it**
help resolve Windows cpu related issues: https://github.com/kubernetes/kubernetes/issues/95735

**Describe the solution you'd like**

**Describe alternatives you've considered**
We have introduced workaround for all processes not just kubelet: https://github.com/Azure/aks-engine/pull/4073

**Additional context**

**Comment by bridgetkromhout** [comment]
Per @jsturtevant this was resolved a different way (instead of using the kubelet priority flag) via https://github.com/Azure/aks-engine/pull/4073.
