### ISSUE TITLE
AzureBackupWindowsWorkload has exited with Exit code: 52

### ISSUE THREAD

**Issue by shashitech** [Azure/aks-engine#4146]
I am trying to discover DB through start discovery in recovery services vault and i see that Wlenable.cmd command fails for AzureBackupWindowsWorkload with exit code : 52 within the VM.

Has any one seen this before ?

**Comment by bridgetkromhout** [comment]
Hi, @shashitech - Uncertain if this problem report was related to AKS Engine. If so, please be advised that AKS Engine is deprecated; please use AKS or CAPZ, per https://github.com/Azure/aks-engine#project-status - thanks!
