### ISSUE TITLE
Allow creation of dual stack Windows clusters

### ISSUE THREAD

**Issue by vavenk-ms** [Azure/aks-engine#4171]
**Describe the request**

Allow creation of dual stack Windows Kubernetes clusters. This was restricted as Windows did not support dual stack. From Windows version 2004 (10.0.19041.610) and Kubernetes version 1.19+, dual stack is supported. https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#ipv4-ipv6-dual-stack

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

Remove the check which restricts creation of  dual stack Windows clusters - https://github.com/Azure/aks-engine/blob/master/pkg/api/vlabs/validate.go#L472-L474.

**Describe alternatives you've considered**

**Additional context**

**Comment by bridgetkromhout** [comment]
Fixed by https://github.com/Azure/aks-engine/pull/4176; thanks!
