### ISSUE TITLE
[Question] How to use NetworkPolicy after installing cluster without specify networkPolicy on initial deploy?

### ISSUE THREAD

**Issue by Zeka13** [Azure/aks-engine#4177]
**Describe the issue**
A clear and concise description of the issue

**AKS Engine Version***
0.58.0

**Kubernetes Version**
1.19.4

Hello, my config for deploy looks like this
`{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.19",
      "orchestratorVersion": "1.19.4",
      "kubernetesConfig": {
        "networkPlugin": "azure",
...`

without any defenition for networkPolicy.

**Did I understand correctly that this is mean I can't use NetworkPolicy manifests for restricting network access from one pod to another?**

Is there any method to add calico with aks-engine to existed k8s cluster or the only option to create a new one?

Thanks in advance

**Please don't remove the text below**
Notify @az-policy-kube

**Comment by kenieva** [comment]
Hi @Zeka13 , what built-in AKS policy are you using?

**Comment by Zeka13** [comment]
@kenieva it is not AKS, it is aks-engine.

NVM, I created a new cluster
