### ISSUE TITLE
change data disk cache to ReadOnly

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#418]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.29.1
---

**Kubernetes version**:
1.13.2

**What happened**:
k8s changed azure disk host cache to ReadOnly in 1.13.2, see https://github.com/kubernetes/kubernetes/issues/72228.
The cache mode of attached data disk by aks-engine is still None. 

**What you expected to happen**:
change data disk cache to ReadOnly

**How to reproduce it** (as minimally and precisely as possible):
Build a cluster with data disks on Windows nodes, check cache mode of data disk in Azure Portal.

**Comment by zhiweiv** [comment]
@andyzhangx

**Comment by zhiweiv** [comment]
btw, cache mode of etcd disk is None also, I don't have much experience on it, should it be updated to a proper cache mode too?

**Comment by andyzhangx** [comment]
@zhiweiv thanks for the remindar, I think all caching mode should be `ReadOnly` by default, I will send out a PR next week.
