### ISSUE TITLE
[Question] How to manage Backend pool members in Azure Load Balancer?

### ISSUE THREAD

**Issue by Zeka13** [Azure/aks-engine#4181]
**Describe the issue**
A clear and concise description of the issue

**AKS Engine Version***
v0.59.0

**Kubernetes Version**
1.19.6

**To Reproduce**

After new cluster deployed I can see all my instances are members of only one "Backend pool" of Azure Load balancer

I don't need all of them here, is there a way to specify only some VMSS or instances to be a part of Backend pool?

Maybe there is a way to have more than one Azure Load Balancer for incoming traffic?

Notify @az-policy-kube

![Screenshot from 2021-01-20 17-53-46](https://user-images.githubusercontent.com/13749031/105200738-d2f55b00-5b48-11eb-9052-2717606226a6.png)

**Comment by CecileRobertMichon** [comment]
This doc might help https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/

**Comment by Zeka13** [comment]
@CecileRobertMichon thanks, I will try this one

**Comment by Zeka13** [comment]
@CecileRobertMichon Hello again, I can see "Exclude nodes from the load balancer (v1.20.0)" section in the doc you sent me, so I 

- tried to put label **node.kubernetes.io/exclude-from-external-load-balancers** on my nodes 
```
kubectl get nodes --show-labels
LABELS
agentpool=consolidated...,node.kubernetes.io/exclude-from-external-load-balancers=true...
```
- check that feature gate ServiceNodeExclusion should is on
```
ps aux | grep apiserver | grep feature-gates
... kube-controller-manager  ... ServiceNodeExclusion=true ... 
```
- And I also  created/changed LB typed services to initiate LB reconcile loop

Unfortunately nothing changed in Backend pool 

Could be because of members are not Nodes, but Virtual machine scale sets ?

**Comment by az-policy-kube** [comment]
Notify @az-policy-kube

**Comment by bridgetkromhout** [comment]
Hi, @Zeka13 - We have deprecated the AKS Engine project, and we encourage you to (ideally) use AKS for managed clusters or (if necessary) switch to CAPZ for self-managed clusters. See https://github.com/Azure/aks-engine/#project-status for details; please let us know if we can answer any questions. Thanks.
