### ISSUE TITLE
Public IP address name is exactly same every time.

### ISSUE THREAD

**Issue by MirzaSikander** [Azure/aks-engine#4196]
As described here: 

https://github.com/Azure/aks-engine/issues/3797

This prevents deploying multiple clusters within the same resource group.

**Comment by bridgetkromhout** [comment]
Hi, @MirzaSikander - thanks for this report. I am resolving this issue as the AKS Engine project is deprecated, and we encourage users to move to AKS or CAPZ, as explained in the project status: https://github.com/Azure/aks-engine#project-status
