### ISSUE TITLE
Master Down: docker daemon fails to start due to corrupted data

### ISSUE THREAD

**Issue by delulu** [Azure/aks-engine#4208]
**Describe the bug**

The master node was stuck in **NotReady** status, and it showed "Kubelet stopped posting node status" with kubectl describe.

From the node it's found that it failed to start kubelet service, and with a further check on syslog it showed the docker daemon also failed to start and lots of errors indicating corrupted disk partition.

![image](https://user-images.githubusercontent.com/8267625/106223742-f725fb80-621c-11eb-84c7-d65632d77359.png)

So I guess disk failure -> docker failed to start -> kubelet failed to start, so I reset docker data location with `mv /var/lib/docker /var/lib/docker.old` and restart the docker/kubelet service, then the docker and kubelet are up and running successfully.

And the master node is back to **Ready** status.

**Steps To Reproduce**

A sudden crash of the vm node might bring a filesystem corruption and it might fail to start services like docker and etcd. 

**Expected behavior**

Make it more robust to start those daemon services and do some mitigation steps automatically to fix the failure, for example resetting the data location or require filesystem with fsck.

**AKS Engine version**

0.54.0

**Kubernetes version**

1.18.6

**Comment by jackfrancis** [comment]
Thanks for reporting this @delulu 

I am a little hesitant to generalize recovery (insert a bunch of automated stuff), as so many weird things can go wrong as a result of a sudden Azure platform error. Do you have any suggestions on how we might add some `OnFailure=`-type solutions to the kubelet and docker systemd service definitions?

kubelet is here:
- https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/artifacts/kubelet.service
docker/containerd systemd service definition is delivered via the apt package, so we'd have to extend it like we're doing here for docker:
- https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/masternodecustomdata.yml#L222

**Comment by delulu** [comment]
Yeah, there're different errors such as networking issue, and dns issue. While from the cluster master issues we met so far almost all other issues can be mitigated with "redeploy" the master node except the disk errors.

So it might worth a try to simply check the disk error for now.

@Michael-Sinz do you have any other suggestion?

**Comment by Michael-Sinz** [comment]
@delulu - When you say redeploy, do you mean re-image?  For the really nasty disk corruption cases, we actually reimage the machine back to initial state (or some snapshot if we have one).  Any data on the disk is lost.  This should be fine as long as only one of the masters is impacted as it will reconcile cluster state from the other masters.

We have been lucky that this has not happened often.  In fact, even with all of our clusters, it has happened on one master in one cluster where the OS disk got corrupted and needed manual intervention.  We have not yet fully automated this part but I suppose it could be done at some point.

**Comment by delulu** [comment]
@Michael-Sinz I mean stop the vm and restart it from azure portal, so the vm can be assigned to a different node. 

Sometime we might keep trying to stop the vm then restart it several times until it's located in a healthy physical node.

It will bring the master node back from most failures except disk errors.

**Comment by Michael-Sinz** [comment]
@delulu - Yes, that is another remediation we also do for certain failures where the hosting machine runs into problems.  However, if the filesystem gets corrupted, you really need to "reimage" the VM.  You can do that by redeploying that part of the arm template after deleting the VM and its disk or you can recover from snapshot if you took one for the VMs.

This makes me think that we should, on some regular basis, take a fresh snapshot of the master VM OS disk for recovery purposes.  The etcd disk, if corrupted, can be cleared and rebuilt and data recovered from the other masters during reconciliation but the OS disk is special.  That would make a much better recovery process at the cost of a snapshot for each master VM.

Thank you for making me think some more about how to automate this solution to the image corruption problem :-)

**Comment by delulu** [comment]
@Michael-Sinz thank you for this sharing, interesting to know.

I agree that it's better with vm snapshot for recovery.

**Comment by bridgetkromhout** [comment]
Hi, @delulu - thanks for opening this issue. Update from discussion with @Michael-Sinz - after getting some fixes into containerd (such as fixing caches that were incorrect/corrupt/incomplete), this is smoother with containerd than it was with docker, so we recommend using containerd instead of docker. Snapshots can speed up recovery, and work happening with VMSS prototype use can also self-optimize a cluster.

Closing this issue as due to AKS Engine deprecation, there are no AKS Engine changes that will be made for this issue: https://github.com/Azure/aks-engine#project-status
