### ISSUE TITLE
Support AKS Engine on Azure Stack HCI

### ISSUE THREAD

**Issue by msftkenneth** [Azure/aks-engine#4209]
**Describe the request**
As AKS is still under preview on Azure Stack HCI, we would like to leverage AKS Engine to provision Kubernetes cluster on Azure Stack HCI.

**Explain why AKS Engine needs it**
It would be preferred as the current AKS deployment does not provide multiple master nodes which to achieve a higher level of resiliency.

**Describe alternatives you've considered**
No other alternatives

**Comment by mkostersitz** [comment]
@msftkenneth please add an enhancement to the AKS-HCI repo here https://aks.ms/aks-hci/issues.
Also note that resiliency of the control plane nodes is achieved by making the VM that host the node highly available within the HCI cluster. So if the physical node goes down the node will come back on another node.

**Comment by craiglpeters** [comment]
As @mkostersitz says this belongs on the AKS on HCI roadmap. Unless a community member contributes it, there aren't plans to add support for Azure Stack HCI to aks-engine. Please reopen if you do plan to do the work
