### ISSUE TITLE
Support extensions on agent VMSS

### ISSUE THREAD

**Issue by davidmatson** [Azure/aks-engine#422]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of aks-engine?**:
0.29.1
---

**Anything else we need to know**:
The documentation for extensions:
https://github.com/Azure/aks-engine/blob/ee49afb90c42fb2cf13f2179f8bbc5447bab87ef/docs/topics/extensions.md

Doesn't note any requirement to use VMAS, but when trying to use an extension with the (now default) VMSS, the following error occurs:
```
FATA[0005] Failed to validate the apimodel after populating values: Extensions are currently not supported with VirtualMachineScaleSets. Please specify "availabilityProfile": "AvailabilitySet"
```

It looks like the underlying VMSS environment does support extensions:
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-extension-sequencing

Having aks-engine support them as well would be great. In particular, we wanted to use them to get a patch installed to resolve #414.

**Comment by CecileRobertMichon** [comment]
cc @marosset

**Comment by rbitia** [comment]
This kind of feature is out of scope for AKS-Engine. Closing for now. :)
