### ISSUE TITLE
Support T4 GPU VM flavors for Linux agent nodes

### ISSUE THREAD

**Issue by penggu** [Azure/aks-engine#4220]
**Describe the request**
Add the following VM types (with NVidia T4 GPUs) to the ask-engine support matrix

**Explain why AKS Engine needs it**
Azure added support for NVidia T4 GPU VMs. We want to enable those GPUs in AKS clusters.

**Describe the solution you'd like**
Add corresponding GPU specs in to our skus matrix.

**Describe alternatives you've considered**
N/A

**Additional context**
We already support NVidia V100 GPU in our AKS clusters. We want to support T4 GPUs in addition to V100 GPUs.

**Comment by penggu** [comment]
This issue is partially addressed by #4224 . 
However, the GPU_NODE still needs to be set to true for T4 flavors, so that nvidia-device-plugin not to be cleaned up on AzureStackHub after installation.

**Comment by bridgetkromhout** [comment]
As explained in https://github.com/Azure/aks-engine/pull/4243#issuecomment-775458347, the VM SKU list is auto-generated.
