### ISSUE TITLE
Installation through Chocolatey is marked as Trojan Horse

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/aks-engine#4227]
**Describe the bug**
Installation through Chocolatey is marked as Trojan Horse and quarantined by Windows Defender:
![image](https://user-images.githubusercontent.com/4345663/106899916-390be180-66f6-11eb-9f98-f065ada586bd.png)

**Steps To Reproduce**
choco install aks-engine -f -y

**Expected behavior**
CLI is able to be used

**Comment by bridgetkromhout** [comment]
Hi, @tomkerkhove - thanks for this report. It looks like it may have been cleared up in the intervening months, as https://community.chocolatey.org/packages/aks-engine seems to be okay. Meanwhile, we'll want to make sure that you are moving away from AKS Engine, which is now deprecated. Please let us know if you have questions: https://github.com/Azure/aks-engine#project-status
