### ISSUE TITLE
Service Principal in servicePrincipalProfile not recognized during template generation.

### ISSUE THREAD

**Issue by aiurxxw** [Azure/aks-engine#4240]
**Describe the bug**
In AKS Engine document it says the recommended way is to "use service principals generated from the VM identity itself". AKS-Engine creation by default assigns "Contributor" Role to "Virtual Machine" type resource "k8s-master-xxxxxxxx-x", then cluster always calls cloud provider to perform LoadBalancer/PublicIP related operations with the master "Virtual Machine" identity instead of the user provided Service Principal. 
However even if we specify the servicePrincipalProfile in the kubernetes.json, it's not recognized, and the cluster still uses the VM identity. This makes the user provided Service Principal in the original "kubernetes.json" superfluous, as the AKS-Engine tool itself or the created Cluster never uses the provided Service Principal.

**Steps To Reproduce**

1. Create Service Principal with:
az ad sp create-for-rbac --role="Contributor"

2. Create kubernetes.json template with servicePrincipalProfile:
    "servicePrincipalProfile": {
      "clientId": "xxxxxxxxxxxxxx",
      "secret": "xxxxxxxxxxxxxx"
    },

3. Create Template:
aks-engine generate kubernetes.json

4. Deploy Cluster with the files in _output.

5. Use kubectl to create a Load Balancer type Service. In Activity Log, the "Event initiated by" column says the operation is by "k8s-master-xxxxxxxx-x"

**Expected behavior**
1. AKS-Engine cluster uses the user provided Service Principal in kubernetes.json to control Cloud Provider activity like the Managed AKS Cluster. 

**AKS Engine version**
Version: v0.59.0
GitCommit: 3eafba286
GitTreeState: clean

**Kubernetes version**
v1.18.14

**Additional context**

kubernetes.json:

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "kubernetesConfig": {
        "networkPlugin": "azure"
      }
    },
    "servicePrincipalProfile": {
      "clientId": "xxxxxxxxxxxxxx",
      "secret": "xxxxxxxxxxxxxx"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "rg0203e",
      "vmSize": "Standard_B2s",
      "vnetSubnetId": "/subscriptions/xxxxxxxxxxxxxx/resourceGroups/rg0203e/providers/Microsoft.Network/virtualNetworks/vnet0203e/subnets/subnet0203e",
      "firstConsecutiveStaticIP": "192.168.0.5"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_B2s",
        "vnetSubnetId": "/subscriptions/xxxxxxxxxxxxxx/resourceGroups/rg0203e/providers/Microsoft.Network/virtualNetworks/vnet0203e/subnets/subnet0203e2"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa AAAAB3NzaxxxxxxxxxxdVStz"
          }
        ]
      }
    }
  }
}

**Comment by bridgetkromhout** [comment]
Hi, @aiurxxw - Thank you for the report; at this time, AKS Engine is deprecated, so we are not continuing to develop it. Please see the project status (https://github.com/Azure/aks-engine#project-status) and use either AKS or CAPZ as your needs require.
