### ISSUE TITLE
Nvidia T4 GPU flavors should be recognized on Azure Stack Hub 

### ISSUE THREAD

**Issue by penggu** [Azure/aks-engine#4242]
**Describe the bug**
For agent nodes with Nvidia T4 GPUs, aks-engine deploys k8s cluster without adding nvidia-device-plugin on Azure stack hub, makeing GPU pods unschedulable.

**Steps To Reproduce**

In the apimodel, specify

 "addons": [
                    {
                        "name": "nvidia-device-plugin",
                        "enabled": true
                    }
                ]

and

        "agentPoolProfiles": [
            {
                "name": "linuxpool",
                "count": 1,
                "vmSize": "Standard_NC4as_T4_v3",
                "distro": "aks-ubuntu-16.04",
                "availabilityProfile": "AvailabilitySet",
                "AcceleratedNetworkingEnabled": false
            }
        ],

**Expected behavior**
 $ kubectl describe node k8s-linuxpool-24766904-0 | grep gpu
  nvidia.com/gpu: 1

**AKS Engine version**
0.55.4

**Kubernetes version**
1.17.11

**Additional context**

**Comment by jpc** [comment]
Hi,

I was wondering if this problem may be affecting standard Azure AKS deployments as well? I encountered similar problem in the West Europe region – a pool of `Standard_NC4as_T4_v3` instances is not recognized as having an `nvidia.com/gpu` resource while the same setup works perfectly with NC6 or NC6s_v3. Unfortunately we need to deploy in Germany West Central which only supports `Standard_NC4as_T4_v3`.

**Comment by penggu** [comment]
> 

Hi Jakub, this issue has been fixed in #4259. Can you update your aks-engine to include the fix in #4259?

**Comment by jpc** [comment]
Hi, thanks for the reply. I am using a managed AKS cluster on Azure so I guess this is a completely wrong place to ask this question?

**Comment by jackfrancis** [comment]
Hi @jpc yeah, this codebased doesn't drive the AKS managed service. You can search through this issue queue and see if others are dealing with your issue:

https://github.com/Azure/AKS/issues

(Or open up a new one.)

Alternatively your AKS service includes Azure support so you man open up an Azure support issue.

**Comment by jpc** [comment]
Thanks and sorry for the noise.
