### ISSUE TITLE
AKSE can support Azure load balancer as service load balance mode ?

### ISSUE THREAD

**Issue by tianputao** [Azure/aks-engine#4246]
**Describe the request**

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bridgetkromhout** [comment]
Hi, @tianputao - Thanks for your suggestion. I'm writing to let you know that AKS Engine is being deprecated, so we will not be adding features; please look into AKS or CAPZ for your ongoing needs: https://github.com/Azure/aks-engine#project-status
