### ISSUE TITLE
When updating from 0.47 to anything above, get a cse-master error code of 30

### ISSUE THREAD

**Issue by RonPrior** [Azure/aks-engine#4247]
When running our deployment scripts, the master fails to run the aks-engine provisioned extension scripts.

The below error appears in the logs, and the kubelets are denied access to the api server as a result.

Backing off to version 0.47 works fine.

Created symlink /etc/systemd/system/multi-user.target.wants/docker-monitor.service → /etc/systemd/system/docker-monitor.service.
+ break
+ echo Executed '"systemctl' enable 'docker-monitor"' 1 times
Executed "systemctl enable docker-monitor" 1 times
+ time_metric ConfigureK8s configureK8s
+ shift
+ configureK8s
+ local client_key=/etc/kubernetes/certs/client.key apiserver_crt=/etc/kubernetes/certs/apiserver.crt azure_json=/etc/kubernetes/azure.json
+ touch /etc/kubernetes/certs/client.key
+ chmod 0600 /etc/kubernetes/certs/client.key
+ chown root:root /etc/kubernetes/certs/client.key
+ [[ -n true ]]
+ touch /etc/kubernetes/certs/apiserver.crt
+ chmod 0644 /etc/kubernetes/certs/apiserver.crt
+ chown root:root /etc/kubernetes/certs/apiserver.crt
+ set +x
Generating RSA private key, 2048 bit long modulus (2 primes)
....+++++
......+++++
e is 65537 (0x010001)
Can't load ./.rnd into RNG
140143289201088:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=./.rnd
Generating RSA private key, 2048 bit long modulus (2 primes)
..................................................................................+++++
..................................................................................................................................................................(Reading database ... 
...(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
.(Reading database ... 60%
.(Reading database ... 65%
.(Reading database ... 70%
.(Reading database ... 75%
......(Reading database ... 80%
.(Reading database ... 85%
..(Reading database ... 90%

aks-engine version - 0.48 - 0.60

kubernetes version - 1.16+

Please ask me for any other information you may need

**Comment by bridgetkromhout** [comment]
Hi, @RonPrior - AKS Engine is deprecated. Please see the project status (https://github.com/Azure/aks-engine#project-status) and use either AKS or CAPZ as your needs require. We're happy to answer questions to help you choose the right path forward.
