### ISSUE TITLE
Automate PR to add VHD "release notes" when DRY_RUN is False in VHD Build

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#427]
When we run the VHD creation CI, we should output a human-readable set of release notes so that a user can easily correlate a VHD build version with a functional description of what is on that VHD.

- OS version
- kernel version
- version of all pre-installed components

**Comment by CecileRobertMichon** [comment]
where should be put this in the repo? As part of release notes? In a new directory? somewhere else?

**Comment by jackfrancis** [comment]
This should be in the repo itself, ideally created programmatically by the VHD CI build process.

**Comment by CecileRobertMichon** [comment]
The release notes artifact was added in #450.

What still needs to be done:
- Remove parallel logging which causes some log lines to appear in the release note output
- Format notes in markdown (?)
- Add a step to the pipeline to create a PR adding the file to the repo when DRY_RUN is false

**Comment by jackfrancis** [comment]
I think this is the only open item that has value-add worthy of investment:

- Add a step to the pipeline to create a PR adding the file to the repo when DRY_RUN is false

**Comment by bridgetkromhout** [comment]
Per @jackfrancis, closing this due to the AKS engine deprecation; we're not making incremental improvements of this sort now.
