### ISSUE TITLE
Azure-vnet.json is missing, Azure CNI failed in provisioning

### ISSUE THREAD

**Issue by tarrantro** [Azure/aks-engine#4289]
I deployed 1.12 AKS engine cluster and Azure CNI got problem to assign IP in pods. In azure CNI log, below is the error.

![image](https://user-images.githubusercontent.com/19900542/108615459-3f60c400-743f-11eb-9745-30956538c2f1.png)

**Comment by zhiweiv** [comment]
Azure CNI 1.2.2 seems help, you can have a try.
https://github.com/Azure/azure-container-networking/issues/763.

**Comment by jackfrancis** [comment]
Hi @tarrantro, could you provide the api model you used to create your cluster (remember to remove any secret data)?

Thanks!

**Comment by bridgetkromhout** [comment]
Hi, @tarrantro - we're closing this issue due to lack to response. If you are still trying to use AKS Engine, please be aware that it is deprecated; we recommend using AKS instead. Please see https://github.com/Azure/aks-engine#project-status for details; thanks!
