### ISSUE TITLE
Proposal: standardize to AKS Engine | aks-engine

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#429]
I propose we standardize the naming thusly:

- When referring to the project: AKS Engine
- When referring to the binary/tool: `aks-engine`

**Comment by CecileRobertMichon** [comment]
Sounds good to me. Is this issue a placeholder for doing a search and replace in all the docs and fixing the naming inconsistencies?

**Comment by jackfrancis** [comment]
Yes, if we come to a consensus that this is a good idea.
