### ISSUE TITLE
AKS-Engine cluster Pod cannot get client Source IP when externalTrafficPolicy is set to Local

### ISSUE THREAD

**Issue by aiurxxw** [Azure/aks-engine#4291]
**Describe the bug**
We are using AKS-Engine to build the cluster and access application Pod exposed by Service, one of the business requirement is that the Pod can see the Source IP of the client who visits the application through the exposed Service. 

When using azure-vote.yaml sample in https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough, we have changed the ExternalTrafficPolicy to Local, but still the Pod cannot see the Public Source IP of the client.

root@uvm:~# kubectl describe svc azure-vote-front
Name:                     azure-vote-front
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=azure-vote-front
Type:                     LoadBalancer
IP:                       10.0.111.107
LoadBalancer Ingress:     52.186.33.36
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31915/TCP
Endpoints:                192.168.96.10:80
Session Affinity:         None
External Traffic Policy:  Local  <<<<<<
HealthCheck NodePort:     32593

**Steps To Reproduce**

1. Create AKS-Engine cluster (Azure CNI). 
2. Deploy Services/Pods through azure-vote.yaml sample in https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough.
3. Change azure-vote-front Service's ExternalTrafficPolicy from "Cluster" to "Local" with "kubectl edit svc azure-vote-front".
4. Restart azure-vote-front-xxxx Pod
5. Start tcpdump in azure-vote-front-xxxx Pod, and access the Service Public IP through an Internet client machine.
6. The request in tcpdump is from the Node VM(VMSS Instance) internal IP to the Pod internal IP. But we expect to see the client's original Source Public IP.

**Expected behavior**
The tcpdump in the Pod can see the Source Public IP of the client who visits the exposed Load Balancer Service.

**AKS Engine version**
Version: v0.59.0
GitCommit: 3eafba286
GitTreeState: clean

**Kubernetes version**
1.18.14

**Additional context**
After changing the ExternalTrafficPolicy to Local, Pod has been restarted manually, but it still doesn't work.
The same configuration works perfectly in AKS Cluster, but not in the AKS-Engine cluster.
It seems https://github.com/Azure/aks-engine/issues/1269 and https://github.com/Azure/aks-engine/issues/1634 are discussing the similar issue for AKS-Engine however cannot find a solution.

**Comment by jackfrancis** [comment]
Hi @aiurxxw, there are no plans to add the equivalent AKS source IP functionality to the AKS Engine-generated ARM templates at this time. Can you describe your preference for using AKS Engine over AKS?

Thanks!

cc @craiglpeters @devigned

**Comment by aiurxxw** [comment]
@jackfrancis thanks for the update. We have some requirement to use self managed cluster so the managed AKS is not an option. Thanks for confirming this function is not included in AKS Engine cluster, will try to achieve it manually with ip-masq-agent.

**Comment by jackfrancis** [comment]
Make sense. FYI more resources are being directed toward cluster-api + Azure these days, have you checked out capz to drive your self-managed Kubernetes needs?

https://github.com/kubernetes-sigs/cluster-api-provider-azure

**Comment by Zeka13** [comment]
```kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'```

did work for me
