### ISSUE TITLE
Upgrading control plane causes api server to be unavailable 

### ISSUE THREAD

**Issue by arsnyder16** [Azure/aks-engine#4301]
**Describe the bug**
I have a web service that is running within AKS.
I recently upgraded a cluster from 1.17-1.18 using 
`az aks upgrade --kubernetes-version 1.18.14 --control-plane-only --yes --name {}`

During the upgrade to the api server become unavaialbe for ~5 minutes. My cluster is configured to have uptime sla. 

During this down time my ingress(nginx) and some custom controllers within the cluster are unable to operate properly causing some downtime since they cannot List/Watch resources. 

`E0226 15:22:43.880879 6 reflector.go:123] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:157: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout`
`E0226 15:22:40.609921 7 reflector.go:123] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:156: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout`

**Steps To Reproduce**
Setup an nginx ingress and upgrade a cluster it will be unable to route to the backends once the api server is down for a period of time

**Expected behavior**
The api server remains available during an upgrade.

**AKS Engine version**
**Kubernetes version**
upgrade from 1.17 - 1.18.14

**Additional context**
It would be nice to have more information on how the api server is deployed on the aks-engine control plane side. Is it a single replica deployment? Based on the behavior that is what it seems. 

This cluster has 2 nodes in the system pool

**Comment by bridgetkromhout** [comment]
Hi, @arsnyder16 - it appears that you are using AKS, based on the command line containing `az aks upgrade`. AKS Engine is a different project (now deprecated) and is not the basis for the managed AKS service. 

If you continue to have questions about AKS, please refer to https://github.com/Azure/AKS#overview for the right way to receive support; thanks.
