### ISSUE TITLE
Scale down command does not accept IP address for "--apiserver" parameter (only FQDN is accepted)

### ISSUE THREAD

**Issue by penggu** [Azure/aks-engine#4302]
**Describe the bug**
On Azure Stack Hub, while using "aks-engine scale" command to scale down a k8s cluster, while supplying IP address for the "--apiserver"
 parameter, the scale down will not succeed.

**Steps To Reproduce**

Try to scale down a Kubernetes cluster using "ask-engine scale" command, and use IP address for "--apiserver" parameter. Neither public IP nor private IP will work. Only FQDN for apiserver will work.

For example, the following command will not work.
aks-engine.exe scale `
    --azure-env AzureStackCloud `
    --resource-group rg-demoA `
    --location redmond `
    --api-model .\apimodel.json `
    --client-id REDACTED `
    --client-secret "REDACTED" `
    --apiserver 10.240.255.5 `
    --new-node-count 1

Output:
_[33mWARN_[0m[0574] Found no VMs in resource group rg-demoA that match pool name linuxpool 
aks-engine.exe : Error: None of the VMs in the provided resource group contain any nodes

However, the following command will work by replacing the IP address with FQDN.
aks-engine.exe scale `
    --azure-env AzureStackCloud `
    --resource-group rg-demoA `
    --location redmond `
    --api-model .\apimodel.json `
    --client-id REDACTED `
    --client-secret "REDACTED" `
    --apiserver demoA.readmond.cloudapp.microsoft.com `
    --new-node-count 1

**Expected behavior**
Kubernetes cluster successful scale down to 1 node (from 3 nodes).

**AKS Engine version**
0.55.4

**Kubernetes version**
1.17.11

**Additional context**

**Comment by jadarsie** [comment]
Private IP won't work. Regarding Public IP, my guess is that this is NOT an AKS Engine issue, I do not think AKS Engine's behavior changes based on whether `--apiserver` is an IP or a host name. BTW, your example is not showing `--node-pool`,

**Comment by bridgetkromhout** [comment]
Hi, @penggu - As a number of months have passed, and @jadarsie replied, I'll close this issue now, with one note: AKS Engine is being deprecated, and Azure Stack Hub customers are encouraged to try AKS for Azure Stack Hub. See https://github.com/Azure/aks-engine#project-status for details; thanks!
