### ISSUE TITLE
parsing ssh private key content: ssh: this private key is passphrase protected

### ISSUE THREAD

**Issue by basawaqe** [Azure/aks-engine#4304]
INFO[0000] Writing cloud profile to: /tmp/azurestackcloud.json101899068 
Error: loading API model: creating linux SSH config: parsing ssh private key content: ssh: this private key is passphrase protected
Usage:
  aks-engine get-logs [flags]

Flags:
  -m, --api-model string               path to the generated apimodel.json file (required)
      --control-plane-only             get logs from control plane VMs only
  -h, --help                           help for get-logs
      --linux-script string            path to the log collection script to execute on the cluster's Linux nodes (required)
      --linux-ssh-private-key string   path to a valid private SSH key to access the cluster's Linux nodes (required)
  -l, --location string                Azure location where the cluster is deployed (required)
  -o, --output-directory string        collected logs destination directory, derived from --api-model if missing
      --ssh-host string                FQDN, or IP address, of an SSH listener that can reach all nodes in the cluster (required)

Global Flags:
      --debug   enable verbose debug logs

**Steps To Reproduce**

**Expected behavior**
ask for passphrase
**AKS Engine version**
0.55.4
**Kubernetes version**
1.15.2
**Additional context**

**Comment by devigned** [comment]
Can you not just add the key to the SSH agent before you start the aks-engine operation?

**Comment by basawaqe** [comment]
Error: required flag(s) "linux-ssh-private-key" not set

**Comment by devigned** [comment]
Ah... I see the issue. Perhaps, if the `linux-ssh-private-key` is not specified, we should use the default identity for the SSH agent, or prompt for password as you suggest.

Happy to review a PR for either solution.

**Comment by bridgetkromhout** [comment]
Hi, @basawaqe - thanks for your input. We're not adding features to AKS Engine at this point, so I'll close this issue now. See https://github.com/Azure/aks-engine#project-status for details; thanks!
