### ISSUE TITLE
aks-engine get-logs Error: unknown flag: --upload-sas-url

### ISSUE THREAD

**Issue by basawaqe** [Azure/aks-engine#4305]
Error: unknown flag: --upload-sas-url
Usage:
  aks-engine get-logs [flags]

Flags:
  -m, --api-model string               path to the generated apimodel.json file (required)
      --control-plane-only             get logs from control plane VMs only
  -h, --help                           help for get-logs
      --linux-script string            path to the log collection script to execute on the cluster's Linux nodes (required)
      --linux-ssh-private-key string   path to a valid private SSH key to access the cluster's Linux nodes (required)
  -l, --location string                Azure location where the cluster is deployed (required)
  -o, --output-directory string        collected logs destination directory, derived from --api-model if missing
      --ssh-host string                FQDN, or IP address, of an SSH listener that can reach all nodes in the cluster (required)

**Steps To Reproduce**
aks-engine get-logs

**Expected behavior**
enable the upload to sasuri
**AKS Engine version**
0.55.4
**Kubernetes version**
1.15.2
**Additional context**

**Comment by devigned** [comment]
Looks like `--upload-sas-url` was added in v0.58.0. See: https://github.com/Azure/aks-engine/pull/3990

**Comment by devigned** [comment]
I believe this feature landed in [v0.58.0](https://github.com/Azure/aks-engine/releases/tag/v0.58.0). Please update your AKS-Engine bin and give it a try.

**Comment by bridgetkromhout** [comment]
Hi, @basawaqe  - As a number of months have passed, it seems likely you were able to resolve this issue with a new version. I'll close this issue now, with one note: AKS Engine is being deprecated. See https://github.com/Azure/aks-engine#project-status for details; thanks!
