### ISSUE TITLE
Error: loading API model: parsing --client-id: invalid UUID length: 0

### ISSUE THREAD

**Issue by samf-cy** [Azure/aks-engine#4311]
****Describe the bug****

I have prepared prerequisites for my Aks deployment  (created resource groupe, vnet, app registritration to retrieve the client Id and secret, and a linux VM i call it "VM-deployment" in which i have installed AKS engine and tried to deploy my apimodel.json. I've been struggling there for hours and i always get the  "Error: loading API model: parsing --client-id: invalid UUID length: 0" error.

**Steps To Reproduce**

here is my apimodel.json :

```

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.18"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "aks-master",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v3"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAaO6y2PJUmqghfcMRXDbKJjjSsbiyBqE+/cwqCONOPjkwI7sl4ZTMpQpjODblQ9JCXrblmUlu93PuPNT$          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "xxxxxxx",
      "secret": "xxxxxxxxxx"
    }
  }
}
```

Then i ran : 

```
aks-engine deploy --dns-prefix contoso-apple \
    --resource-group aks-master \
    --location northeurope \
    --api-model apimodel.json \
    --auto-suffix
```
and I got:

`Error: loading API model: parsing --client-id: invalid UUID length: 0
`

**Expected behavior**

I expected that my cluster starts deploying but i kept getting these errors.

**AKS Engine version**
Version: v0.56.1

**Kubernetes version**
1.18

**Additional context**

Any suggestions will be appreciated!

**Comment by samf-cy** [comment]
any suggestion?

**Comment by devigned** [comment]
I think you are being prompted for the client-id to use to deploy the template generated by aks-engine when running `aks-engine deploy`. 

My guess is that you don't have Azure CLI installed on the VM where you are running aks-engine. If Azure CLI is not installed and you've logged in, `aks-engine` can't use the Azure CLI identity and needs you to specify an identity to use to deploy the cluster Azure Resource Manager template. You didn't provide `--client-id` as a cmd line argument to `aks-engine deploy`. That is why you are receiving the error. 

See: https://github.com/Azure/aks-engine/blob/master/docs/tutorials/cli-overview.md#aks-engine-deploy.

**Comment by samf-cy** [comment]
@devigned thank you for your comment. I actually installed azure CLI and have logged in before trying to deploy my aks-engine. I think this could be something related to the part below: 
```
"servicePrincipalProfile": {
      "clientId": "xxxxxxx",
      "secret": "xxxxxxxxxx"
    }
```

**Comment by samf-cy** [comment]
@devigned do you mean that i have to provide the client-id in both json file( as "clientId") and cmd (as an --client-id argument) ?

**Comment by devigned** [comment]
Yes. The identities have different roles. 
- `aks-engine deploy --client-id` is the identity used to deploy the ARM template. 
- `clientId` in the API model is the identity the cluster will run as

You can also build the cluster so you don't specify a `clientId`, but rather use an Azure Managed Identity ([example](https://github.com/Azure/aks-engine/blob/b4b4dc0e7e747fb5c95b3a6f0986927330653d9c/examples/managed-identity/kubernetes-msi.json#L6), [MI docs](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview))

I hope that helps a bit. Azure IAM is a deep topic and we are just scratching the surface.

**Comment by devigned** [comment]
We have recently written some [identity / role documentation in Cluster API Provider Azure](https://capz.sigs.k8s.io/topics/identities-use-cases.html) that doesn't translate 1 to 1 to AKS-Engine, but it's relatively close and can provide some differentiation of the multiple roles and identities when running / building a K8s cluster on Azure.

**Comment by samf-cy** [comment]
Thank you i figured out this issue !
