### ISSUE TITLE
Unable to connect to the server: dial tcp 13.66.162.75:443: i/o timeout

### ISSUE THREAD

**Issue by Masquerade0097** [Azure/aks-engine#432]
I deployed a Kubernetes cluster using aks-engine but I'm getting this error `Unable to connect to the server: dial tcp 13.66.162.75:443: i/o timeout` when I try to use kubectl. I'm able to access the master node with the serial console but not through ssh (same error comes in this case).

```
$ KUBECONFIG=_output/kubeconfig/kubeconfig.westus2.json kubectl get node
Unable to connect to the server: dial tcp 13.66.162.75:443: i/o timeout
```

```
$ KUBECONFIG=_output/kubeconfig/kubeconfig.westus2.json kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Aks-Engine version  - `v0.28.1-linux-amd64`
Kubernetes version - `1.10.12`

Here is the kubeconfig.westus2.json file - 
```
    {
        "apiVersion": "v1",
        "clusters": [
            {
                "cluster": {
                    "certificate-authority-data": "*****"
                    "server": "https://masquerade-az.westus2.cloudapp.azure.com"
                },
                "name": "masquerade-az"
            }
        ],
        "contexts": [
            {
                "context": {
                    "cluster": "masquerade-az",
                    "user": "masquerade-az-admin"
                },
                "name": "masquerade-az"
            }
        ],
        "current-context": "masquerade-az",
        "kind": "Config",
        "users": [
            {
                "name": "masquerade-az-admin",
                "user": {"client-certificate-data":"****","client-key-data":"*****"}
            }
        ]
    }
```

This is the screenshots for inbound ports - 
![inbound](https://user-images.githubusercontent.com/23634977/52162658-54097c80-26fd-11e9-9ad2-8ef678eed81c.png)

This is the screenshot for outbound ports - 
![outbound](https://user-images.githubusercontent.com/23634977/52162665-697ea680-26fd-11e9-8190-dff7f03c667f.png)

**Comment by andyzhangx** [comment]
your master node is down, could you check by `docker ps` and get kubelet logs `sudo journalctl -u kubelet -l > kubelet.log `

**Comment by Masquerade0097** [comment]
Thanks, the master node was down because of some breaking changes in `kube-apiserver` but I managed to fix it. Closing this.
