### ISSUE TITLE
Implement a safe method to shut down cluster nodes without losing control over the cluster the next time we connect to

### ISSUE THREAD

**Issue by samf-cy** [Azure/aks-engine#4323]
**Describe the request**

Using aks-engine for deploying kubernetes cluster on azure stack, we had to keep our node VMs running all the time in order to keep the cluster running. Once we shut down the VMs (intentionally) , we lost complete control over the cluster.
**Explain why AKS Engine needs it**

We cannot keep the VMs up and running all the time, so we need to be able to shut down the cluster in a recommended and safe way in order to be able to reconnect into it whenever needed. 

**Additional context**

We can't support such failure in production environment. So this is highly urgent

**Comment by jadarsie** [comment]
@samf-cy, are you shutting down control plane or agent nodes? what do you mean exactly with "control is lost"? what's the symptom? workloads do not work anymore or control plane does not behave as expected?

**Comment by bridgetkromhout** [comment]
Hi, @samf-cy - As a number of months have passed, it seems likely you sought support via Azure Stack Hub. I'll close this issue now, with one note: AKS Engine is being deprecated, and Azure Stack Hub customers are encouraged to try AKS for Azure Stack Hub. See https://github.com/Azure/aks-engine#project-status for details; thanks!
