### ISSUE TITLE
Pause image live building is supported by only docker container runtime

### ISSUE THREAD

**Issue by mainred** [Azure/aks-engine#4330]
**Describe the bug**

If the pause image version is not in the default supported list, windows cse will try to build the pause image when launching the windows node, but this happens only when the container runtime is docker, and will raise error when it comes to containerd.

https://github.com/Azure/aks-engine/blob/23240cae3c7905fdc8f95bb468a8ae913c1a0a8e/parts/k8s/windowskubeletfunc.ps1#L203

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by jackfrancis** [comment]
@marosset @jsturtevant is this still an issue? if so, will we ever address it in aks-engine?

cc @bridgetkromhout

**Comment by jsturtevant** [comment]
this isn't something we won't fix as it only for some development flows
