### ISSUE TITLE
Unable to access my load balncer Azure AKS

### ISSUE THREAD

**Issue by rakeshkmbj** [Azure/aks-engine#4343]
**Describe the issue**
I am not able to run my ASP net core 5 MVC applciation via port http://<aks external ip>/:8080
This is the yaml that i am using

apiVersion: v1
kind: Service
metadata:
  name: sampleapi
  labels:
    app: sampleapi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: sampleapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapi
  template:
    metadata:
      labels:
        app: sampleapi
    spec:
      containers:
      - name: sampleapi
        image: pocrkacr.azurecr.io/sampleaspcoreapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

**AKS Engine Version***
1.18.14
**Kubernetes Version**
1.18.14
**Expected behavior**
"Site should load on browser as it is loading via local docker"

![image](https://user-images.githubusercontent.com/52172275/112349237-ef278c80-8c9e-11eb-84a6-90b936037884.png)

Actual behavior
"This site can’t be reached"
![image](https://user-images.githubusercontent.com/52172275/112349392-10887880-8c9f-11eb-8b63-ead4d12cfa18.png)
 
Please help !!!

**Comment by bridgetkromhout** [comment]
Hi, @rakeshkmbj - it appears your question is not about AKS Engine; please check https://docs.microsoft.com/en-us/azure/ for your use case. Thanks.
