### ISSUE TITLE
No “Deployment” and "View live data" feature for AKS-Engine > Monitor Insights view

### ISSUE THREAD

**Issue by Riiiiika** [Azure/aks-engine#4349]
In pure AKS cluster monitor insights, we could get "Deployment" and "View Live Data" as the capture shows, but there're no such buttons in AKS-Engine. May I know if this is by-design? If yes, any workaround now to get these two metrics for AKS-Engine?
![image](https://user-images.githubusercontent.com/73595930/113108527-a724de80-9237-11eb-8f81-c249c4287fa7.png)

**Comment by bridgetkromhout** [comment]
Hi, @Riiiiika - AKS Engine is deprecated and we recommend using AKS instead; we will not be adding features to AKS Engine. Please see https://github.com/Azure/aks-engine#project-status for details; thanks.
