### ISSUE TITLE
test mtu 3900

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#4350]
**Describe the request**

Test the viability of 3900 byte MTU size on node eth0 interfaces.

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bridgetkromhout** [comment]
Closing per https://github.com/Azure/aks-engine/pull/4352 and due to AKS Engine deprecation.
