### ISSUE TITLE
Intermittent DNS Failures with external hostnames

### ISSUE THREAD

**Issue by mesutcelik** [Azure/aks-engine#4356]
We see intermittent dns failures in some of the pods while cloning a repo from bitbucket...
**ssh: Could not resolve hostname bitbucket.org: Temporary failure in name resolution**

**AKS Engine version**
Version: v0.50.0

**Kubernetes version**
1.15.11

**Additional context**
We have increased min. coredns pods to 2 but still no luck. We also do not see any error in core-dns logs.
Btw,we do not have any issues with internal dns resolution. The problem is only happening with external hostname (i.e. bitbucket.org)
Our latest configuration to coredns is to add a specific block to bitbucket.org but we still see the error occasionally.
```
    bitbucket.org:53 {
        errors
        log
        cache 30
        forward . 8.8.8.8
    }
```

Do you have any idea how to fix this issue?

**Comment by bridgetkromhout** [comment]
Hi, @mesutcelik - AKS Engine is deprecated and we recommend using AKS instead. Please see https://github.com/Azure/aks-engine#project-status for details; thanks.
