### ISSUE TITLE
GPU drivers don't work with containerd

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#4357]
**Describe the bug**

This is a tracking issue to clarify that the aks-engine-provided GPU drivers don't work when using containerd CRI. See the code comment here:

https://github.com/Azure/aks-engine/blob/47c439d1e8891a1cc63ced39332418f1506e6a41/parts/k8s/cloud-init/artifacts/cse_config.sh#L584

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by Michael-Sinz** [comment]
Note that this is blocking containerd for Skyman work as we use GPU nodes in a number of scenarios.

**Comment by Michael-Sinz** [comment]
PS - maybe it is time to switch to the GPU Operator design?  They have a new update that has containerd support.
https://developer.nvidia.com/blog/announcing-containerd-support-for-the-nvidia-gpu-operator/

**Comment by jackfrancis** [comment]
This is no longer an issue.
