### ISSUE TITLE
Release notes for Windows + containerd VHDs do not include container info

### ISSUE THREAD

**Issue by marosset** [Azure/aks-engine#4369]
https://github.com/Azure/aks-engine/blame/master/vhd/packer/write-release-notes-windows.ps1 should be updated to use ctr.exe to list images and their tags similar to 

https://github.com/Azure/aks-engine/blob/60828c79dc943877618eca1d1bda3563ca52dd05/vhd/packer/write-release-notes-windows.ps1#L92-L98

**Comment by bridgetkromhout** [comment]
Closing given the AKS Engine deprecation.
