### ISSUE TITLE
Configurable log levels for addons

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/aks-engine#4397]
**Describe the request**

To date, the addon pods produce large amounts of logs, even of non-relevant information (for example: level [INFO](https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/calico.yaml#L22) or [DEBUG](https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/container-monitoring.yaml#L78)).

It would be desirable, during the cluster deployment phase, to be able to configure, through configMap or another way, the output level of the logs in order to reduce the impact. 

Addons that are more relevant (at least for my usage scenario):
* [Calico](https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/calico.yaml)
* [CoreDNS](https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/coredns.yaml)
* [Kube Proxy](https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/kube-proxy.yaml)
* [OMS Agent](https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/container-monitoring.yaml)

**Explain why AKS Engine needs it**

Configured in this way, each AKS cluster produces tens of thousands of useless log lines every day. This information becomes relevant only in case of problems but otherwise, it creates only background noise and costs. 

**Describe the solution you'd like**

Define via [Kubernetes config](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#kubernetesconfig) in deploy phase and after with a ConfigMap the desired level of logs for AKS addons.

**Describe alternatives you've considered**

No alternatives.

**Comment by bridgetkromhout** [comment]
Hi, @pierluigilenoci - Thanks for the suggestion! We are not adding new features to AKS Engine, as this project is no longer being actively developed. From the [README - Project status](https://github.com/Azure/aks-engine#project-status), you can see your options, which include using AKS for managed Kubernetes (which is recommended for many use cases). Please let us know about any questions we can answer.

**Comment by pierluigilenoci** [comment]
@bridgetkromhout we already use AKS for our clusters.
I believed the engine was also used internally by AKS.
So mine was a feature request to have this option on AKS. 😉 
If this is not the correct way... is there a way to do FR for AKS?

**Comment by devigned** [comment]
Hi @pierluigilenoci, AKS did use some bits from AKS-Engine in the past, but has broken away from using AKS-Engine for quite some time. Please consider using [AKS User Voice](https://feedback.azure.com/d365community/forum/aabe212a-f724-ec11-b6e6-000d3a4f0da0) to request the feature.

**Comment by pierluigilenoci** [comment]
Ref: https://feedback.azure.com/d365community/idea/ed0a2ef8-b689-ec11-a81b-0022484bfd94
