### ISSUE TITLE
Generation 2 VM SKUs do not work with default AKS Engine Linux VHDs

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#4398]
The AKS Engine default VHDs, which are identified by the `"distro": "aks-ubuntu-18.04"` or `"distro": "aks-ubuntu-16.04"` api model configurations are built from Generation 1 Azure VMs, and thus only work with VM SKUs that are compatible with Generation 1 Azure VM hardware.

The practical effect of this is that Generation 2-required Azure VMs require a user-managed OS image in order to be used as the VM type for a node pool. The current AKS Engine-supported way to do this is to build your own Ubuntu 18.04-LTS OS image and host as a Shared Image Gallery image. See more information here:

https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#use-a-shared-image-gallery-image

**Comment by bridgetkromhout** [comment]
Closing per @jackfrancis as AKS Engine is deprecated.
