### ISSUE TITLE
devenv.sh script is missing

### ISSUE THREAD

**Issue by UncleTawnos** [Azure/aks-engine#440]
**Is this a request for help?**: No

---

**TYPE: ISSUE**
---

According to the documentation, there should be a `scripts/devenv.sh` script for building aks-engine binaries. It definitely was in acs-engine before
https://github.com/Azure/aks-engine/blob/master/docs/tutorials/quickstart.md

**What version of aks-engine?**:
---
0.29.1 / master

Either documentation should be updated (like we just support PS, install ps on linux and go away), or missing script should be added and maintained.

**Comment by CecileRobertMichon** [comment]
The documentation will be fixed by https://github.com/Azure/aks-engine/pull/301

Please use `make dev` in the meantime.
