### ISSUE TITLE
Is it possible to add service-meash (istio) to existed cluster?

### ISSUE THREAD

**Issue by Zeka13** [Azure/aks-engine#4400]
Hello, I know there is an instruction how to configure aks-engine with istio support for a new cluster
https://github.com/Azure/aks-engine/tree/master/examples/service-mesh

But if I already created a cluster without this options and I want to install Istio, is it possible? What can you suggest?

Currently I get this error
```
MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled
```

Thx in advance 

**AKS Engine version**
latest

**Kubernetes version**
1.19

**Comment by jadarsie** [comment]
hello @Zeka13 , you can either update `/etc/kubernetes/manifests/kube-apiserver.yaml` on each control plane OR update the `apimodel.json` and execute `aks-engine upgrade` (`--force` if upgrading to the current version).

Please pre-validate in a non-production environment.

**Comment by Zeka13** [comment]
@jadarsie thx a lot! For feature googlers, I added this line
```"--service-account-signing-key-file=/etc/kubernetes/certs/apiserver.key" ,"--service-account-issuer=kubernetes.default.svc" ,"--service-account-api-audiences=api,istio-ca",```

to 
```
containers:
    - name: kube-apiserver
      args: ...
```
