### ISSUE TITLE
Security issue - Container Escape in azure-cni-networkmonitor

### ISSUE THREAD

**Issue by nadav-robas** [Azure/aks-engine#4405]
Hello,
The StatefulSet of azure-cni-networkmonitor is configured with the following:

      - name: ebtables-rule-repo
        hostPath:
          path: /var/run/
          type: Directory

Mounting the whole /var/run directory exposes /var/run/docker.sock socket as well, which can lead to container escaping,
especially since this specific container runs as root by default.

I would like to ask two questions:
1. Is it required for the CNI to properly function?
2. If so, what is the suggested to mitigate this security vulnerability?

Thanks in advance

**Comment by bridgetkromhout** [comment]
Hi, @nadav-robas - thanks for reaching out, and apologies for the slow reply. We missed this because this is not an AKS Engine issue; please instead [open an AKS issue](https://github.com/Azure/AKS/issues) if you're still encountering this problem.
