### ISSUE TITLE
Remove support for 16.04

### ISSUE THREAD

**Issue by Michael-Sinz** [Azure/aks-engine#4409]
**Describe the bug**
Ubuntu 16.04 is now fully end-of-life and will no longer get updates/security fixes.

In Microsoft, it is now a security violation to be running anything based on 16.04.  Minimum bar now is 18.04.

This can help reduce the support and test matrix by dropping 16.04 support which will help simplify things.

**Comment by jackfrancis** [comment]
cc @craiglpeters @jadarsie @devigned @haofan-ms 

Javier/Hao Fan, can we remove 16.04 before the next release? Or will it take more time for Azure Stack Hub to let customers know they aren't able to use 16.04-LTS anymore?

**Comment by haofan-ms** [comment]
We are actually planning to drop the support for 16.04 on Azure Stack Hub from aks-engine v0.63.0 release as well, and we have also validated that the upgrade from 16.04 VM to 18.04. I think maybe there are some docs we need to update. @jadarsie can you help confirm that?

**Comment by khouloudbo** [comment]
Hello,
I have done an upgrade of the AKS engine to 0.60.1 and kubernetes version to 1.18.15.
Now I'am trying to perform an upgrade of AKS Cluster OS to 18.04, the base image is available in the marketplace, but whenever i Try to perform an upgrade, it gives me this error:
Error: loading existing cluster: failed to get client: Request failed: subscriptions.Client#Get: Failure sending request: StatusCode=0 -- Original Error: Get "https://management.region.fqdn/subscriptions/xxxxxxx-xxxx-xxxxxx-xxxxx-xxxx?api-version=2016-06-01": dial tcp: lookup management.region.fqdn on 127.0.0.53:53: read udp 127.0.0.1:52301->127.0.0.53:53: i/o timeout

Do you have any idea regarding this ?

Thank you :)

**Comment by jadarsie** [comment]
Hard to tell given the provided information. 

The error message indicates problems creating an HTTP client to reach to the resource manager.
Make sure all required parameters are set and the correct apimodel.json is passed as input.
Port 53 is the DNS port, check that's working as well.

**Comment by khouloudbo** [comment]
There there were a problem with DNS resolution in the jumpbox VM , i just restarted it and the upgrade went with success

**Comment by bridgetkromhout** [comment]
Support for 16.04 was removed in https://github.com/Azure/aks-engine/pull/4418 and this change was released in https://github.com/Azure/aks-engine/releases/tag/v0.63.0.
