### ISSUE TITLE
Multiple clusters can easily have the same VMSS/Node hostnames if DNSPrefix is not uniquely managed by the end user

### ISSUE THREAD

**Issue by KamalAman** [Azure/aks-engine#4414]
**Describe the request**

VMSS Nodes with the same hostname can easily be created across different cluster if the DNSPrefix name is the same in the clusters.  For some reason, the function GetClusterID, which is used to automatically generate VMSS name for AKS Clusters , automatically uses the DNSPrefix name to try to create a "Random" ID for the VMSS.  If two clusters DNSPrefix names are the same, the VMSS name will be the same causing many issues. 

This is implemented in `aks-engine/pkg/api/types.go`

```
func (p *Properties) GetClusterID() string {
	if p.ClusterID == "" {
		uniqueNameSuffixSize := 8
		// the name suffix uniquely identifies the cluster and is generated off a hash
		// from the master dns name
		h := fnv.New64a()
		if p.MasterProfile != nil {
			_, _ = h.Write([]byte(p.MasterProfile.DNSPrefix))
		} else if len(p.AgentPoolProfiles) > 0 {
			_, _ = h.Write([]byte(p.AgentPoolProfiles[0].Name))
		}
		r := rand.New(rand.NewSource(int64(h.Sum64())))
		p.ClusterID = fmt.Sprintf("%08d", r.Uint32())[:uniqueNameSuffixSize]
	}
	return p.ClusterID
}
```

**Explain why AKS Engine needs it**
This code results many clusters with the same DNSPrefix name results in the clusters to have nodes with the same hostname names. This can messup any monitoring solution that monitors clusters, Nodes in different clusters should have unique names.

**Describe the solution you'd like**

Use something more unique like, like the actual ID of the cluster that includes the subscription information. 

**Describe alternatives you've considered**
Manually enforcing a unique DNSPrefix name to be used each and every cluster is created so that this hash would actually be unique

**Additional context**
Hostnames in AKS are automatically given a name with the following format aks-[nodePoolName]-[ClusterId]-vmss, but in reality ClusterId is not really the clusters id, it is a hash of the DNSPrefix.

**Comment by bridgetkromhout** [comment]
Hi, @KamalAman - Thanks for this report. AKS Engine is deprecated and we recommend using AKS instead; we will not be continuing development on AKS Engine. Please see https://github.com/Azure/aks-engine#project-status for details; thanks.
