### ISSUE TITLE
Adding proxy servers didn't work

### ISSUE THREAD

**Issue by zjinjian-cn** [Azure/aks-engine#4415]
**Describe the bug**
https://github.com/Azure/aks-engine/blob/master/docs/topics/proxy-servers.md
Adding proxy servers didn't work

**Steps To Reproduce**

After adding the proxy setting into both /etc/profile and /etc/environment, I still failed to pull the image. 

**Expected behavior**
I added the following to /etc/systemd/system/docker.service.d/proxy.conf
[Service]
Environment="HTTP_PROXY=http://proxy:8080/"
Environment="HTTPS_PROXY=http://proxy:8080/"
Environment="NO_PROXY=localhost,127.0.0.1,.example.com"

Then restarted the docker daemon.
sudo systemctl daemon-reload
sudo systemctl restart docker

docker pull works after that.

**AKS Engine version**
~$ aks-engine version
Version: v0.60.1
GitCommit: 91d42f2ba
GitTreeState: clean

**Kubernetes version**
~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"34a0735619ce4b9630f2dd2be3fd4327bed9719f", GitTreeState:"clean", BuildDate:"2021-01-20T21:05:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

~$ docker version
Client:
 Version:           19.03.14+azure
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        fd3371eb7df1adeceff5935cf3ade0576a0f48d5
 Built:             Sat Oct 24 07:44:17 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.14+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       7d75c1d40d88ddef08653dbd611f41df42bdf087
  Built:            Mon Mar 12 00:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9+azure
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:

**Additional context**

**Comment by bridgetkromhout** [comment]
Hi, @zjinjian-cn - AKS Engine is deprecated. Please see the project status (https://github.com/Azure/aks-engine#project-status) and use either AKS or CAPZ as your needs require.
