### ISSUE TITLE
Unable to configure csi-secrets-store-provider-azure after cluster deployment

### ISSUE THREAD

**Issue by jcobb48** [Azure/aks-engine#4416]
**Describe the bug**
After deploying a cluster, the csi secret store driver and azure key vault provider is automatically deployed.

kubectl get ds -n kube-system
NAME                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
azure-ip-masq-agent                4         4         4       4            4           kubernetes.io/os=linux   38d
csi-secrets-store                  1         1         1       1            1           kubernetes.io/os=linux   38d
csi-secrets-store-provider-azure   1         1         1       1            1           kubernetes.io/os=linux   38d
kube-proxy                         4         4         4       4            4           kubernetes.io/os=linux   38d

I am trying to configure AKV provider to point to a Ket Vault in Azure Stack as per this documentation:
https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/custom-environments/

If try to delete akv provider and redeploy using helm, I am unable to do so, because default akv provider resources get recreated (daemon set, service accounts, etc).

Could not find any documentation about customizing akv provider deployment when using aks-engine, or on how to update the provider

**Steps To Reproduce**
Deploy a K8s cluster with aks-engine and try to remove csi-secrets-store-provider-azure, it will get recreated with default configuration

**Expected behavior**
To be able to customize akv csi secret provider, using aks-engine or at least be able to delete the provider an recreate with custom configuration.

**AKS Engine version**
Version: v0.55.4
GitCommit: 0b2df8a7a
GitTreeState: clean

**Kubernetes version**
v1.17.11

**Additional context**
akv secret provider works as expected with Azure Public Cloud.

**Comment by pengjz89** [comment]
Hi,

I am also facing the same issue for aks-engine add-on csi-secret-store driver when trying to connect azure stack hub keyvault.

We are able to successfully authenticated with the AAD to get bearer token (Step1&2) however it failed when trying to keyVaut.BaseClient#GetSecret (Step3)
https://safe.menlosecurity.com/https://docs.microsoft.com/en-us/azure/key-vault/general/authentication

We suspect that the CSI-Secret-Store-Driver failed as the KeyVault Endpoint is using my project certificate.
Please advise on how we can load the project certificate into the CSI-Secret-Store-Driver? Thanks

**Comment by bridgetkromhout** [comment]
Hi, @jcobb48 & @pengjz89 - AKS Engine is deprecated. Please see the project status (https://github.com/Azure/aks-engine#project-status) and use either AKS or CAPZ as your needs require.
