### ISSUE TITLE
Can't connect IPv6 cluster to Azure-arc

### ISSUE THREAD

**Issue by Schreder-Hyperion** [Azure/aks-engine#4426]
Hi all!
First of all, I apologize if the ticket is malformed in any way.

I used your example of an IPv6 cluster JSON to create an IPv6 Cluster in Azure.

When trying to connect the cluster to azure-arc I get an error:
`Unable to install helm release: W0519 14:00:51.245973, further down stating that it Timed out waiting for a condition.`

After digging around I noticed the following error under the azure-arc namespace for the container **clusteridentityoperator:manager**:

`ERROR   controller      Reconciler error        {"reconcilerGroup": "clusterconfig.azure.com", "reconcilerKind": "AzureClusterIdentityRequest", "controller": "azureclusteridentityrequest", "name": "connectproxy-agent-identity-request", "namespace": "azure-arc", "error": "Failed to get regional uri with error: {Get https://gbl.his.hybridcompute.azure-automation.net/discovery?location=westeurope&api-version=1.0-preview: dial tcp 20.50.1.196:443: connect: network is unreachable}"}`

I attempted to telnet to 20.50.1.196 443  from different pods (kube-system and azure-arc) and noticed that whenever the IP is an IPv4 the error "network is unreachable" is thrown.

Does anyone have any idea on how to work around this? (I did not enable the azure-arc addon from the JSON)

Thank you for the attention.

**Comment by bridgetkromhout** [comment]
Hi, @Schreder-Hyperion - I'm not sure from this issue if you're using AKS Engine at all, but I can point you in the direction of how to use dual-stack networking in AKS, which is now in preview: https://docs.microsoft.com/en-us/azure/aks/configure-kubenet-dual-stack?tabs=azure-cli%2Ckubectl

If you are trying to use AKS Engine, please be aware that it is deprecated and so you will want to use AKS or CAPZ: https://github.com/Azure/aks-engine/#project-status - happy to answer questions about this.
