### ISSUE TITLE
Proposal: 5000 Nodes Clusters

### ISSUE THREAD

**Issue by khenidak** [Azure/aks-engine#443]
Here is the proposed process to create ultra large clusters (500+ nodes)

1. Create a script that stands up an etcd cluster (User will need two, one for events and one for everything else). User may need to install additional etcd for `cilium` or similar. Each cluster runs on a separate availability set. each node is configured with ultra-ssd. The script will also create the certificates needed by etcd.
2. Add `api-model` knop that allows the user to enter etcd details manually (this knop will have to be mutually exclusive with cosmos and any other etcd specific configuration).
3. Turning on this knop will 
   1. Stop installing etcd locally on api-server
   2. Connect api server to etcd as specified by user
4. Deploy cluster as expected.
5. Scaling the cluster to 5000 nodes. Current approach does not allow us to create more than 5 (iirc) agent pools before reaching ARM template limits. That leaves us with two choices:
  1. Create VMSS that allow 1000 VM (right now our limits are 100) - I think this is better option.
  2. Manually modify the generated template by updating VMSS names and redeploy them.

@jackfrancis  @CecileRobertMichon; questions? Can we bless the above in order to start executing?

**Comment by CecileRobertMichon** [comment]
Sounds good to me. One concern: the naming of aks-engine VMs might not be designed to accommodate such a large number of VMs (I think we reserve 2 chars for index 0-99) so that might be something that needs to be slightly altered to avoid node name collisions. Maybe it will work out of the box though, just something to look into!

**Comment by sozercan** [comment]
> * Create VMSS that allow 1000 VM (right now our limits are 100) - I think this is better option.

You can set `singlePlacementGroup` to `false` which allows for 1000 nodes per pool: https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#agentpoolprofiles

**Comment by jackfrancis** [comment]
keep open

**Comment by jackfrancis** [comment]
ditto

**Comment by jackfrancis** [comment]
keep open

**Comment by sozercan** [comment]
keep open
