### ISSUE TITLE
Flannel + Containerd + Multus (flannel": error in getting result from AddNetwork: failed to allocate for range 0: no IP addresses available in range set: 10.244.1.1-10.244.1.254)

### ISSUE THREAD

**Issue by abhishek-jnpr** [Azure/aks-engine#4435]
**Describe the bug**

I have a pod with multiple interfaces topology looks like below.

                          eth0
                            |
-----eth1------csrx-cm (pod)-----eth2------

I'm using flannel + containerd with Multus CNI to provide additional interfaces to container. Upon deployment of "csrx-cm" I;m facing below error.

Logs of csrx-cm (pod) -> application pod
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               5m8s                  default-scheduler  Successfully assigned default/csrx-cm to k8s-agentpool1-49763098-2
  Warning  FailedCreatePodSandBox  5m7s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8ebb5874a03adc791b320de5f5b68e4bd685acabf929862fc99dcf235f45b1c4": failed to find network info for sandbox "8ebb5874a03adc791b320de5f5b68e4bd685acabf929862fc99dcf235f45b1c4"
  Warning  FailedCreatePodSandBox  5m6s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "68056f10792d765b5d13bd07f722841139c3639b19b0a16293612ef3dfc26da3": failed to find network info for sandbox "68056f10792d765b5d13bd07f722841139c3639b19b0a16293612ef3dfc26da3"
  Warning  FailedCreatePodSandBox  5m5s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ca6753724d5f06589722ac6e6fd3141f2a1d3fd93fec5b26660c63af4a293864": failed to find network info for sandbox "ca6753724d5f06589722ac6e6fd3141f2a1d3fd93fec5b26660c63af4a293864"
  Warning  FailedCreatePodSandBox  5m4s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "edd8df68ede4fa055d415e385afafe061e71f40366736a028a53fc782bad6ab7": failed to find network info for sandbox "edd8df68ede4fa055d415e385afafe061e71f40366736a028a53fc782bad6ab7"
  Warning  FailedCreatePodSandBox  5m3s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "11e09644036a2bcfb798b4a4a8828330843a20e2327d63595300a9e6d3999fff": failed to find network info for sandbox "11e09644036a2bcfb798b4a4a8828330843a20e2327d63595300a9e6d3999fff"
  Warning  FailedCreatePodSandBox  5m2s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ed5021ffa10e9012c596d2f5004dab3db4d4a1ad269a9bda4fd3247a5f55a893": failed to find network info for sandbox "ed5021ffa10e9012c596d2f5004dab3db4d4a1ad269a9bda4fd3247a5f55a893"
  Warning  FailedCreatePodSandBox  5m1s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5faeead493949d8ecde4fdedcf12f7f963b4a6ea8850d05cecef222f58f0bffa": failed to find network info for sandbox "5faeead493949d8ecde4fdedcf12f7f963b4a6ea8850d05cecef222f58f0bffa"
  Warning  FailedCreatePodSandBox  5m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "68d654671ae92f16b1582d0e178a8ea000008da349af95f1c34bce66f5d1ab01": failed to find network info for sandbox "68d654671ae92f16b1582d0e178a8ea000008da349af95f1c34bce66f5d1ab01"
  Warning  FailedCreatePodSandBox  4m59s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "41d21a0bfb143ee1c86567cd07377d16d647ceb0cde610a5f278035773a3a4fd": failed to find network info for sandbox "41d21a0bfb143ee1c86567cd07377d16d647ceb0cde610a5f278035773a3a4fd"
  Warning  FailedCreatePodSandBox  0s (x188 over 4m58s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2d21953a2b1e3d50d51c747896f7c1b17ddfa63c619f76dbcf79197638aac89b": Multus: [default/csrx-cm]: error adding container to network "cbr0": delegateAdd: error invoking DelegateAdd - "flannel": error in getting result from AddNetwork: failed to allocate for range 0: no IP addresses available in range set: 10.244.1.1-10.244.1.254
Error from server (NotFound): pods "logs" not found

All pods deployed on cluster.
abhishekr-mbp:aks-dep-dir abhishekr$ KUBECONFIG=_output/csrx-60adc15b/kubeconfig/kubeconfig.westus2.json kubectl get pods -A
NAMESPACE     NAME                                            READY   STATUS              RESTARTS   AGE
default       csrx-cm                                         0/1     ContainerCreating   0          11m
kube-system   azure-ip-masq-agent-d4njj                       1/1     Running             0          38m
kube-system   azure-ip-masq-agent-hxpl5                       1/1     Running             0          38m
kube-system   azure-ip-masq-agent-k8rb5                       1/1     Running             0          38m
kube-system   azure-ip-masq-agent-nx46v                       1/1     Running             0          38m
kube-system   blobfuse-flexvol-installer-2c7z9                1/1     Running             0          37m
kube-system   blobfuse-flexvol-installer-cn2f5                1/1     Running             0          37m
kube-system   blobfuse-flexvol-installer-qztbd                1/1     Running             0          37m
kube-system   coredns-6bbfb77cb5-srxj4                        1/1     Running             0          38m
kube-system   coredns-autoscaler-87b67c5fd-fjds4              1/1     Running             0          38m
kube-system   csi-secrets-store-glv76                         3/3     Running             0          37m
kube-system   csi-secrets-store-gq9rz                         3/3     Running             0          37m
kube-system   csi-secrets-store-provider-azure-74cxq          1/1     Running             0          37m
kube-system   csi-secrets-store-provider-azure-7l8sb          1/1     Running             0          37m
kube-system   csi-secrets-store-provider-azure-8c96r          1/1     Running             0          37m
kube-system   csi-secrets-store-vsq7d                         3/3     Running             0          37m
kube-system   kube-addon-manager-k8s-master-49763098-0        1/1     Running             0          38m
kube-system   kube-apiserver-k8s-master-49763098-0            1/1     Running             0          37m
kube-system   kube-controller-manager-k8s-master-49763098-0   1/1     Running             0          37m
kube-system   kube-flannel-ds-bfnrx                           2/2     Running             0          38m
kube-system   kube-flannel-ds-gmcb7                           2/2     Running             0          38m
kube-system   kube-flannel-ds-gwjdx                           2/2     Running             0          37m
kube-system   kube-flannel-ds-t6drm                           2/2     Running             1          38m
kube-system   kube-multus-ds-amd64-bjjjw                      1/1     Running             0          34m
kube-system   kube-multus-ds-amd64-h9xg4                      1/1     Running             0          34m
kube-system   kube-multus-ds-amd64-kfsvm                      1/1     Running             0          34m
kube-system   kube-multus-ds-amd64-w2dts                      1/1     Running             0          34m
kube-system   kube-proxy-7r2qv                                1/1     Running             0          38m
kube-system   kube-proxy-gtdh2                                1/1     Running             0          38m
kube-system   kube-proxy-lbbbf                                1/1     Running             0          38m
kube-system   kube-proxy-mzfzk                                1/1     Running             0          38m
kube-system   kube-scheduler-k8s-master-49763098-0            1/1     Running             0          37m
kube-system   metrics-server-6c8cc7585b-fcff2                 1/1     Running             0          38m
abhishekr-mbp:aks-dep-dir abhishekr$

**Steps To Reproduce**

Bring up cluster with flannel and containerd, install multus cni on the cluster.
Deploy a Ubuntu container with multiple interfaces to it.

**Expected behavior**
In our baremetal server we are able to get the k8s cluster with application pod working with flannel+docker+multus.

**AKS Engine version**
aks-engine version
Version: v0.58.0
GitCommit: 11651366c
GitTreeState: clean

**Kubernetes version**
k8s version: 1.19

**Additional context**

**Comment by bridgetkromhout** [comment]
Hi, @abhishek-jnpr - AKS Engine is deprecated. Please see the project status (https://github.com/Azure/aks-engine#project-status) and use either AKS or CAPZ as your needs require. Thanks!
