### ISSUE TITLE
Switch default Linux distro to Ubuntu 20.04-LTS 

### ISSUE THREAD

**Issue by amankohli** [Azure/aks-engine#4441]
Please add default linux distro to Ubuntu 20.04-LTS , do we have ETA to switch to Ubuntu 20.04-LTS ?

**Comment by bridgetkromhout** [comment]
Thanks for reaching out! AKS Engine is deprecated, so we do not plan to make this change. If you're creating new clusters, please use either AKS (for managed clusters) or CAPZ (for self-managed clusters). See https://github.com/Azure/aks-engine#project-status for additional details and links.
