### ISSUE TITLE
Add more AAD options to aadProfile

### ISSUE THREAD

**Issue by Isaac-Lee-msft** [Azure/aks-engine#4445]
**Describe the request**
Requesting adding optional cluster-role assignments to the aadProfile specifically for cluster edit/view permissions.

**Explain why AKS Engine needs it**
Offering the adminGroupID spec is too broad in scope, especially for production environments - enabling different role levels from deployment will empower developers using aks-engine to make better decisions regarding cluster security. 

**Describe the solution you'd like**
Add optional editGroupID / viewGroupID to the aadProfile settings which bind directly to the edit and view cluster role bindings - similar to how adminGroupID functions.

**Describe alternatives you've considered**
In order to add the cluster role permissions for edit/view on deployment, the option that I found most feasible is to specify a custom script extension with `kubectl create clusterrolebinding --clusterrolebinding=edit --group=xxxx`. The other option is to SSH to the cluster after deployment, but this is not scalable.

**Additional context**
My team cannot allow any user on our team to have cluster-admin permissions since we are deploying to a production environment. We also cannot simply SSH to each k8s cluster to manually create the clusterrolebinding since we have to deploy at scale.

**Comment by bridgetkromhout** [comment]
Hi, @Isaac-Lee-msft - We are not adding new features to AKS Engine, as this project is no longer being actively developed. From the [README - Project status](https://github.com/Azure/aks-engine#project-status), you can see your options, which include using AKS for managed Kubernetes (which is recommended for many use cases). Please let us know about any questions we can answer.
