### ISSUE TITLE
Update metrics-server to v0.5.0

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/aks-engine#4455]
**Describe the request**

New metrics-server version 0.5.0 has been released and promises interesting performances: 

> This release comes with big improvements in both autoscaling quality and reliability. A 2X improvement to the CPU based scale up time makes horizontal pod autoscaler much more responsive to large load spikes. A default resource requirements that should guarantee reliable support up to 100 node clusters (70 pods per node) out of the box. This is achieved thanks to multiple performance improvements, that allowed an increase of metric collection frequency while keeping the resource requests low.

Ref: https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.5.0

**Explain why AKS Engine needs it**

Improve the overall performances

**Describe the solution you'd like**

Update the metrics-server version

**Describe alternatives you've considered**

None

**Additional context**

Not relevant

**Comment by jackfrancis** [comment]
@pierluigilenoci this change has already merged and will be released soon! (ETA: EOD today)

**Comment by pierluigilenoci** [comment]
Thanks
