### ISSUE TITLE
master node not starting without audit-policy and/or pod-security-policy

### ISSUE THREAD

**Issue by mweibel** [Azure/aks-engine#4461]
**Describe the bug**
In order to be able to deploy due to #4460 we disabled (for tryout reasons) pod security policy and audit policy (among other things). The master nodes then didn't start because the kube API server exited (`docker ps -a` helps here), stating the error that the audit policy doesn't exist. After adding that one, the pod security policy didn't exist either.

In my opinion, the CLI should not give the possibliity to disable those two addons if they are required. 

**Steps To Reproduce**
See config in #4460 

**Expected behavior**

**AKS Engine version**
#4459 custom build

**Kubernetes version**
1.20.7

**Comment by bridgetkromhout** [comment]
hi, @mweibel - as mentioned in https://github.com/Azure/aks-engine/issues/4460#issuecomment-1035659426 this project is being deprecated. Please let us know if we can assist with your move to AKS or CAPZ.

**Comment by mweibel** [comment]
I replied in #4460, thanks again for reaching out :)

**Comment by bridgetkromhout** [comment]
Thanks, @mweibel. I am closing this issue as AKS Engine is deprecated and so we will not be making these changes.
