### ISSUE TITLE
Problem running AKS-Engine on MAC: 32639 killed 

### ISSUE THREAD

**Issue by 0hlov3** [Azure/aks-engine#4513]
**Describe the bug**

I have the aks-engine-v0.63.0 as zip and tar.gz fall down, after I unpacked it, I confirmed on the Mac that the run is OK, however, I then always get the following message.

❯ /usr/local/bin/aks-engine-v0.63.0
[1] 32639 killed /usr/local/bin/aks-engine-v0.63.0

I couldn't get it running, so I downloaded the "source-code.zip" and built it with "make build", after that the built was finisched, i can execute the new build aks-engine.
However, of course there are no tags or similar in there.

aks-engine-0.63.0/bin/aks-engine version
Version: canary
GitCommit:
GitTreeState: clean
Is there a way to get the build running?
Or did i make something wrong?

**Steps To Reproduce**
Installing AKS-Engine version v0.63.0 on macOS Big Sur 11.4.

**Expected behavior**
aks-engine version
Version: v0.60.1
GitCommit: 91d42f2ba
GitTreeState: clean
**AKS Engine version**
AKS-Engine version v0.63.0 
**Kubernetes version**
n/a
**Additional context**

**Comment by jackfrancis** [comment]
Hi @0hlov3, can you reproduce this with v0.65.0 macos binaries?

**Comment by 0hlov3** [comment]
> Hi @0hlov3, can you reproduce this with v0.65.0 macos binaries?

Yes, after Downloading and allowing aks-engine-v0.65.0 on the Mac, I see the same behavior.

~/Downloads/aks-engine-v0.65.0-darwin-amd64
❯ ./aks-engine --help
[1]    3448 killed     ./aks-engine --help

**Comment by 0hlov3** [comment]
Hi,

Thats what I did, to get things working:


```
❯ cd ~/Downloads/aks-engine-0.63.0
❯ ls -la
total 256
drwxrwxr-x@ 43 ohlove  staff   1376 27 May 21:03 .
drwx------@ 63 ohlove  staff   2016  6 Jul 17:06 ..
drwxrwxr-x@  4 ohlove  staff    128 27 May 21:03 .chglog
drwxrwxr-x@  3 ohlove  staff     96 27 May 21:03 .codecov
-rw-rw-r--@  1 ohlove  staff    382 27 May 21:03 .devcontainer.json
-rw-rw-r--@  1 ohlove  staff     90 27 May 21:03 .gitattributes
drwxrwxr-x@  7 ohlove  staff    224 27 May 21:03 .github
-rw-rw-r--@  1 ohlove  staff    780 27 May 21:03 .gitignore
-rw-rw-r--@  1 ohlove  staff      7 27 May 21:03 .go-version
-rw-rw-r--@  1 ohlove  staff    391 27 May 21:03 .golangci.yml
drwxrwxr-x@ 13 ohlove  staff    416 27 May 21:03 .pipelines
drwxrwxr-x@ 11 ohlove  staff    352 27 May 21:03 .prowci
-rw-rw-r--@  1 ohlove  staff    444 27 May 21:03 CODE_OF_CONDUCT.md
-rw-rw-r--@  1 ohlove  staff   3647 27 May 21:03 CONTRIBUTING.md
-rw-rw-r--@  1 ohlove  staff   1045 27 May 21:03 Dockerfile
-rw-rw-r--@  1 ohlove  staff   5914 27 May 21:03 Jenkinsfile
-rw-rw-r--@  1 ohlove  staff   1072 27 May 21:03 LICENSE
-rw-rw-r--@  1 ohlove  staff   5520 27 May 21:03 Makefile
-rw-rw-r--@  1 ohlove  staff    124 27 May 21:03 OWNERS
-rw-rw-r--@  1 ohlove  staff   4597 27 May 21:03 README.md
-rw-rw-r--@  1 ohlove  staff   3187 27 May 21:03 SUPPORT.md
drwxrwxr-x@ 33 ohlove  staff   1056 27 May 21:03 cmd
drwxrwxr-x@ 10 ohlove  staff    320 27 May 21:03 docs
drwxrwxr-x@ 47 ohlove  staff   1504 27 May 21:03 examples
drwxrwxr-x@  9 ohlove  staff    288 27 May 21:03 extensions
-rw-rw-r--@  1 ohlove  staff   2173 27 May 21:03 go.mod
-rw-rw-r--@  1 ohlove  staff  35787 27 May 21:03 go.sum
drwxrwxr-x@  3 ohlove  staff     96 27 May 21:03 hack
drwxrwxr-x@  3 ohlove  staff     96 27 May 21:03 jenkins
-rw-rw-r--@  1 ohlove  staff    430 27 May 21:03 main.go
-rw-rw-r--@  1 ohlove  staff    472 27 May 21:03 makedev.ps1
-rw-rw-r--@  1 ohlove  staff   1558 27 May 21:03 packer.mk
drwxrwxr-x@  9 ohlove  staff    288 27 May 21:03 parts
drwxrwxr-x@ 12 ohlove  staff    384 27 May 21:03 pkg
drwxrwxr-x@  4 ohlove  staff    128 27 May 21:03 releases
drwxrwxr-x@ 23 ohlove  staff    736 27 May 21:03 scripts
drwxrwxr-x@  3 ohlove  staff     96 27 May 21:03 staging
drwxrwxr-x@  3 ohlove  staff     96 27 May 21:03 test
-rw-rw-r--@  1 ohlove  staff    876 27 May 21:03 test.mk
drwxrwxr-x@ 20 ohlove  staff    640 27 May 21:03 translations
drwxrwxr-x@  9 ohlove  staff    288 27 May 21:03 vendor
-rw-rw-r--@  1 ohlove  staff    760 27 May 21:03 versioning.mk
drwxrwxr-x@  6 ohlove  staff    192 27 May 21:03 vhd
```

```
❯ make build
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
make -C hack/tools/
GOBIN=/Users/ohlove/Downloads/aks-engine-0.63.0/hack/tools/bin go get github.com/go-bindata/go-bindata/...@v3.1.2
GOBIN=/Users/ohlove/Downloads/aks-engine-0.63.0/hack/tools/bin go get github.com/mitchellh/gox/...@v1.0.1
GOBIN=/Users/ohlove/Downloads/aks-engine-0.63.0/hack/tools/bin go get github.com/onsi/ginkgo/ginkgo/...@v1.15.0
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /Users/ohlove/Downloads/aks-engine-0.63.0/hack/tools/bin v1.39.0
golangci/golangci-lint info checking GitHub for tag 'v1.39.0'
golangci/golangci-lint info found version: 1.39.0 for v1.39.0/darwin/amd64
golangci/golangci-lint info installed /Users/ohlove/Downloads/aks-engine-0.63.0/hack/tools/bin/golangci-lint
GOBIN=/Users/ohlove/Downloads/aks-engine-0.63.0/hack/tools/bin go get github.com/devigned/pub/...@v0.2.6
GOBIN=/Users/ohlove/Downloads/aks-engine-0.63.0/hack/tools/bin go get github.com/mattn/goveralls
go get: upgraded github.com/mattn/goveralls v0.0.8 => v0.0.9
GOBIN=/Users/ohlove/Downloads/aks-engine-0.63.0/hack/tools/bin go get github.com/golang/mock/mockgen@v1.2.0
go-bindata 3.1.2 (Go runtime go1.16.4).
Copyright (c) 2010-2013, Jim Teeuwen.
go generate -mod=vendor -v ./... > /dev/null 2>&1
go build -mod=vendor -ldflags '-s -X main.version= -X github.com/Azure/aks-engine/pkg/telemetry.AKSEngineAppInsightsKey=c92d8284-b550-4b06-b7ba-e80fd7178faa -X github.com/Azure/aks-engine/cmd.BuildSHA= -X github.com/Azure/aks-engine/cmd.GitTreeState=clean -X github.com/Azure/aks-engine/cmd.BuildTag=canary' -o /Users/ohlove/Downloads/aks-engine-0.63.0/bin/aks-engine 
```

```
❯ /Users/ohlove/Downloads/aks-engine-0.63.0/bin/aks-engine --help
AKS Engine deploys and manages Kubernetes clusters in Azure

Usage:
  aks-engine [flags]
  aks-engine [command]

Available Commands:
  addpool       Add a node pool to an existing AKS Engine-created Kubernetes cluster
  completion    Generates bash completion scripts
  deploy        Deploy an Azure Resource Manager template
  generate      Generate an Azure Resource Manager template
  get-logs      Collect logs and current cluster nodes configuration.
  get-versions  Display info about supported Kubernetes versions
  help          Help about any command
  rotate-certs  Rotate certificates on an existing AKS Engine-created Kubernetes cluster
  scale         Scale an existing AKS Engine-created Kubernetes cluster
  update        Update an existing AKS Engine-created VMSS node pool
  upgrade       Upgrade an existing AKS Engine-created Kubernetes cluster
  version       Print the version of aks-engine

Flags:
      --debug                enable verbose debug logs
  -h, --help                 help for aks-engine
      --show-default-model   Dump the default API model to stdout

Use "aks-engine [command] --help" for more information about a command.
```

```
❯ /Users/ohlove/Downloads/aks-engine-0.63.0/bin/aks-engine get-versions
Version        Upgrades
1.22.0-alpha.1 
1.21.1         1.22.0-alpha.1
1.20.7         1.21.1
1.19.11        1.20.7
1.18.19        1.19.11
1.17.17        1.18.19
```

Old Version Works without Problems:
```
❯ aks-engine-v0.60.1 get-versions
Version        Upgrades
1.21.0-alpha.1 
1.20.2         1.21.0-alpha.1
1.20.1         1.20.2, 1.21.0-alpha.1
1.19.7         1.20.1, 1.20.2
1.19.6         1.19.7, 1.20.1, 1.20.2
1.18.15        1.19.6, 1.19.7
1.18.14        1.18.15, 1.19.6, 1.19.7
1.17.17        1.18.14, 1.18.15
1.17.16        1.17.17, 1.18.14, 1.18.15
1.16.15        1.17.16, 1.17.17
1.16.14        1.16.15, 1.17.16, 1.17.17
1.6.9          1.16.14, 1.16.15
```

**Comment by 0hlov3** [comment]
@jackfrancis If there's anything else I can support or test, feel free to let me know. Then I will run the tests at my place. 

A colleague can see the same behavior, so I would rule out that it is me.

**Comment by maksim-paskal** [comment]
problem in https://github.com/Azure/aks-engine/blob/v0.65.0/.github/workflows/release.yaml#L122-L125 - this docker image `mcr.microsoft.com/oss/azcu/go-dev:v1.32.1` create not executable darwin binnary - I think it will be fixed in new release - release `v0.65.0` has broken binnary

**Comment by maksim-paskal** [comment]
```bash
> brew install maksim-paskal/tap/aks-engine

> aks-engine version
Version: v0.65.0
GitCommit: a94702030
GitTreeState: clean
```

**Comment by jackfrancis** [comment]
@maksim-paskal Thanks for the detective work. What exactly are you seeing?

**Comment by maksim-paskal** [comment]
I see that after compression with upx version 3.94 macOS binary became broken, I try to use upx version 3.96 - and it create normal binary that was compressed and this binary works on my macOS 11.4 - I think that problem in this version of upx that was used on release stage

**Comment by 0hlov3** [comment]
Wow that's nice, thank you, so I've to rebuild aks-engine v0.63.0 this way, for azure stack hub support.

https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2102#aks-engine-and-corresponding-image-mapping

**Comment by jackfrancis** [comment]
I think it makes the most sense to remove upx from the build flow going forward. Thoughts?

cc @devigned @mboersma

**Comment by mboersma** [comment]
It's just a delivery optimization, so we could remove `upx` from the build process without harm.

**Comment by devigned** [comment]
The bins are pretty small even without `upx`. I would vote to remove `upx`.

**Comment by jackfrancis** [comment]
Can you try this release?

https://github.com/Azure/aks-engine/releases/tag/v0.65.1

**Comment by 0hlov3** [comment]
> Can you try this release?
> 
> https://github.com/Azure/aks-engine/releases/tag/v0.65.1

Everything Works as aspected, after enabling AKS-Engine in the Security & Privacy Settings.
```
❯ ./aks-engine
Usage:
  aks-engine [flags]
  aks-engine [command]

Available Commands:
  addpool       Add a node pool to an existing AKS Engine-created Kubernetes cluster
  completion    Generates bash completion scripts
  deploy        Deploy an Azure Resource Manager template
  generate      Generate an Azure Resource Manager template
  get-logs      Collect logs and current cluster nodes configuration.
  get-versions  Display info about supported Kubernetes versions
  help          Help about any command
  rotate-certs  Rotate certificates on an existing AKS Engine-created Kubernetes cluster
  scale         Scale an existing AKS Engine-created Kubernetes cluster
  update        Update an existing AKS Engine-created VMSS node pool
  upgrade       Upgrade an existing AKS Engine-created Kubernetes cluster
  version       Print the version of aks-engine

Flags:
      --debug                enable verbose debug logs
  -h, --help                 help for aks-engine
      --show-default-model   Dump the default API model to stdout

Use "aks-engine [command] --help" for more information about a command.
❯ ./aks-engine get-versions
Version        Upgrades
1.22.0-alpha.1
1.21.2         1.22.0-alpha.1
1.20.8         1.21.2
1.19.12        1.20.8
1.18.20        1.19.12
1.17.17        1.18.20
```

Thank you! =)

**Comment by jackfrancis** [comment]
Sorry for the annoyance. :(

Definitely let us know if you see this again.

**Comment by 0hlov3** [comment]
> > Can you try this release?
> > https://github.com/Azure/aks-engine/releases/tag/v0.65.1
> 
> Everything Works as aspected, after enabling AKS-Engine in the Security & Privacy Settings.
> 
> ```
> ❯ ./aks-engine
> Usage:
>   aks-engine [flags]
>   aks-engine [command]
> 
> Available Commands:
>   addpool       Add a node pool to an existing AKS Engine-created Kubernetes cluster
>   completion    Generates bash completion scripts
>   deploy        Deploy an Azure Resource Manager template
>   generate      Generate an Azure Resource Manager template
>   get-logs      Collect logs and current cluster nodes configuration.
>   get-versions  Display info about supported Kubernetes versions
>   help          Help about any command
>   rotate-certs  Rotate certificates on an existing AKS Engine-created Kubernetes cluster
>   scale         Scale an existing AKS Engine-created Kubernetes cluster
>   update        Update an existing AKS Engine-created VMSS node pool
>   upgrade       Upgrade an existing AKS Engine-created Kubernetes cluster
>   version       Print the version of aks-engine
> 
> Flags:
>       --debug                enable verbose debug logs
>   -h, --help                 help for aks-engine
>       --show-default-model   Dump the default API model to stdout
> 
> Use "aks-engine [command] --help" for more information about a command.
> ❯ ./aks-engine get-versions
> Version        Upgrades
> 1.22.0-alpha.1
> 1.21.2         1.22.0-alpha.1
> 1.20.8         1.21.2
> 1.19.12        1.20.8
> 1.18.20        1.19.12
> 1.17.17        1.18.20
> ```
> 
> Thank you! =)

❯ /usr/local/bin/aks-engine-v0.65.1 version
Version: v0.65.1
GitCommit: 156eb2e
GitTreeState: dirty
