### ISSUE TITLE
Deprecate azure-policy addon for 1.22+

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#4549]
The current `azure-policy` addon doesn't work starting with 1.22. Because this addon is not actively maintained, let's deprecate the addon starting with that version and recommend that folks use the official helm chart.

**Comment by jackfrancis** [comment]
@sozercan what's the best link to provide for folks to use who want to install azure-policy via helm?

cc @ritazh

**Comment by sozercan** [comment]
https://github.com/Azure/azure-policy-kubernetes/tree/prod/charts

Charts will be located here once they are updated

**Comment by bridgetkromhout** [comment]
Given the AKS Engine deprecation, @jackfrancis believes we can close this issue without making AKS Engine changes.
