### ISSUE TITLE
CSE exit 4 on N series nodes due to rpcbind failure

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#455]
Customers are observing intermittent CSE 4 errors during N series node provisioning due to rpcbind errors:

```
Job for rpcbind.service failed because the control process exited with error code. See "systemctl status rpcbind.service" and "journalctl -xe" for details.
+ '[' 1 -eq 0 ']'
+ '[' 100 -eq 100 ']'
+ return 1
+ RESTART_STATUS=1
+ systemctl status rpcbind --no-pager -l
+ '[' 1 -ne 0 ']'
+ echo 'rpcbind could not be started'
rpcbind could not be started
+ return 1
+ exit 4
```

**Comment by Shuanglu** [comment]
@jackfrancis @mboersma @tariq1890 Hey team, just would like to know if we have any update regarding this issue?

**Comment by mboersma** [comment]
@Shuanglu I'm trying to reproduce it so we can narrow down what happens. If you have a quick way to reproduce this, let me know.

**Comment by Shuanglu** [comment]
> @Shuanglu I'm trying to reproduce it so we can narrow down what happens. If you have a quick way to reproduce this, let me know.
> 
> I've been repeatedly creating and scaling up N-series clusters but haven't seen this failure yet.

@mboersma the issue happened twice in cx's cluster. we don't hv a quick way to reproduce this unfortunately. is that possible due to the something inside the OS stalled and blocked the rpcbind to start or something like a performance issue? When we logged to the VM to check, the rpc service  was started

**Comment by Sewci0** [comment]
I am experiencing the same problem, it happens consistently while creating a cluster with multiple node pools. All 9 of my NC6 VMs end up in a failed state.

**Comment by jackfrancis** [comment]
@Sewci0 What version of aks-engine? Could you paste the api model JSON you use as input to aks-engine, with private creds removed?

**Comment by archmangler** [comment]
What was the solution here?

**Comment by jackfrancis** [comment]
We were never able to reproduce a GPU cluster provisioning failure due to `systemctl start rpcbind.service` failing.

If you have a repro you could use journalctl to get logs on rpcbind.service
