### ISSUE TITLE
Can I add local node to AKS?

### ISSUE THREAD

**Issue by chuangxinyuan** [Azure/aks-engine#4551]
**Describe the request**
Can I add local node to AKS?
**Explain why AKS Engine needs it**
 we have a small local datacenter, and we want to reuse those local machines. The method in my mind is: we can connect the local machines to the AKS network through Azure S2S VPN, then, add those nodes to Kubernetes cluster. dont know if this idea is supported by aks engine or not 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bridgetkromhout** [comment]
Hi, @chuangxinyuan - while what you're describing isn't specifically an AKS Engine feature, you may find [Virtual Node](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes) or [Virtual Kubelet](https://github.com/virtual-kubelet/virtual-kubelet) relevant to your interests.
