### ISSUE TITLE
Windows pause is using a local image

### ISSUE THREAD

**Issue by sozercan** [Azure/aks-engine#4597]
**Describe the bug**
Looks like Windows pause image is pulled and retagged as `kubletwin/pause`
https://github.com/Azure/aks-engine/blob/47c439d1e8891a1cc63ced39332418f1506e6a41/parts/k8s/windowskubeletfunc.ps1#L210
and used in kubelet config https://github.com/Azure/aks-engine/blob/master/pkg/api/defaults-kubelet.go#L70

This should reference MCR pause image directly as image might get deleted from local node

It is also doesn't contain tag/digest information so it's not possible to tell what version of pause it is using

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by marosset** [comment]
The behavior to use a local image (kubelet/win) dates back to before there was support for Windows worker nodes in K8s / before there was a pause image for Windows that could have gotten published to MCR.

This behavior also assisted in testing pre-release Windows Server SAC releases where aks-engine would need to build a local pause image from nanoserver-insider images (https://github.com/Azure/aks-engine/blob/47c439d1e8891a1cc63ced39332418f1506e6a41/parts/k8s/windowskubeletfunc.ps1#L219)

If we wanted to start using tagged MCR images we'd need to make a couple of updates in aks-engine.
- Set the MCR pause image in the kubelet config args generated here https://github.com/Azure/aks-engine/blob/47c439d1e8891a1cc63ced39332418f1506e6a41/parts/k8s/kuberneteswindowsfunctions.ps1#L231-L237
- Don't hardcode the kubelet config arg here https://github.com/Azure/aks-engine/blob/cfea4ac1e366d421d5aaa069e9a663874acb5620/pkg/api/defaults-kubelet.go#L70
- Update this script to use value in kubelet config json file (set in first bullet point)
- Test everything

**Comment by sozercan** [comment]
Since aks-engine is deprecated, closing this as a non-security related issue.

Matching AgentBaker issue: https://github.com/Azure/AgentBaker/issues/967
