### ISSUE TITLE
How to add a node label when the vmss scale out

### ISSUE THREAD

**Issue by hmi12** [Azure/aks-engine#4608]
**Describe the request**
We're using nodeSelector,   when the VMSS scale out, the new node will not be labeled automatically. 

**Explain why AKS Engine needs it**

**Describe the solution you'd like**
if the VMSS scale out,   we'd like it can be automatically added with some labels,  so we can use the nodeSelector.

**Describe alternatives you've considered**

**Additional context**

**Comment by bridgetkromhout** [comment]
Hi, @hmi12 - AKS Engine is deprecated. Please see the project status (https://github.com/Azure/aks-engine#project-status) and use either AKS or CAPZ as your needs require.
