### ISSUE TITLE
What should the certificateProfile format be like?

### ISSUE THREAD

**Issue by pretystar** [Azure/aks-engine#4611]
**Describe the issue**
I try to use aks-engine to scale k8s cluster in Azure Stack, but aks-engine\pkg\helpers\pki.go line 342 return nil, my question is What should the certificateProfile format be like?
![image](https://user-images.githubusercontent.com/26919284/128692866-371c591d-93a8-411d-91e4-826dbaa9626f.png)

**AKS Engine Version***

**Kubernetes Version**

**Gatekeeper Version**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26919284/128692249-affe5810-c6f2-4638-8b26-3467a52919f1.png)

**Additional context**

**Please don't remove the text below**
Notify @az-policy-kube

**Comment by jadarsie** [comment]
`apimodel.json` should already contain a valid `certificateProfile`, the recommendation would be to use the json outputed by `aks-engine deploy`. Regardless, try this:

```zsh
cat ${path} | awk '{printf "%s\\n", $0}'
```
