### ISSUE TITLE
GPU nodes fail with CSE error 86

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#4631]
**Describe the bug**

GPU nodes fail to provision with `"Enable failed: failed to execute command: command terminated with exit status=86"`

**Steps To Reproduce**

``` $ aks-engine deploy -m examples/kubernetes-gpu/kubernetes.json -l westus2 -p mydnsprefix```

**Expected behavior**

Nodes provision without error and expose their GPU resources.

**AKS Engine version**

v0.66.0 and `HEAD` of master branch. This did not seem to be a problem in v0.65.0.

**Kubernetes version**

**Additional context**

Is it possible that https://github.com/Azure/aks-engine/blob/4edaf4d68c28cbcb4c1cd8ad35cddc5d64ff5284/parts/k8s/cloud-init/artifacts/cse_install.sh#L82 failed during image building, or that the package moved?

cc: @Michael-Sinz

**Comment by birdemily** [comment]
We met this issue when we use 0.65.0 on July 28th. Then we update the aks-engine to v0.66.0. Before Aug 27th, V0.66.0 works well. So we believe v0.65.0 also have this issue.

**Comment by mboersma** [comment]
From the CSE log on a failed GPU node:

```shell
$ cat /var/log/azure/cluster-provision.log
+ '[' -f /opt/azure/containers/provision.complete ']'
++ date
++ hostname
+ echo Mon Aug 30 19:56:21 UTC 2021,k8s-poolgpu-26399701-vmss000000, startcustomscript
++ seq 1 3600
+ for i in $(seq 1 3600)
+ '[' -s /opt/azure/containers/provision_source.sh ']'
+ grep -Fq '#HELPERSEOF' /opt/azure/containers/provision_source.sh
+ break
+ sed -i /#HELPERSEOF/d /opt/azure/containers/provision_source.sh
...
rmmod: ERROR: Module nouveau is not currently loaded
+ echo blacklist nouveau
+ retrycmd_no_stats 120 5 25 update-initramfs -u
+ retries=120
+ wait_sleep=5
+ timeout=25
+ shift
+ shift
+ shift
++ seq 1 120
+ for i in $(seq 1 $retries)
+ timeout 25 update-initramfs -u
update-initramfs: Generating /boot/initrd.img-5.4.0-1055-azure
+ break
+ echo Executed apt-get purge -y '"mlocate"' 1 times
Executed apt-get purge -y "mlocate" 1 times
+ break
+ wait_for_apt_locks
+ fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock
++ ls '/var/cache/apt/archives/libnvidia-container1*'
ls: cannot access '/var/cache/apt/archives/libnvidia-container1*': No such file or directory
+ dpkg -i
dpkg: error: --install needs at least one package archive file argument

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
+ exit 86
```

**Comment by mboersma** [comment]
There are no *.deb files in `/var/cache/apt/archives`, but clearly the CSE script expects them to be there. I don't see earlier errors relating to this, and the `nvidia-modprobe.service` exists, so this was detected as a GPU node.

**Comment by mboersma** [comment]
So my assumption is that something did `apt-get clean`, and once 30 days had passed, the nvidia .deb files under /var/cache/apt/archive were considered stale and automatically cleaned up.

```shell
$ apt-config dump | grep MaxAge
APT::Archives::MaxAge "30";
```

We do have some code that should have disabled the nightly cleanup here:
https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/masternodecustomdata.yml#L191

But when I log in to a freshly created cluster, I don't see `99periodic` where I expected to:

```shell
$ ls /etc/apt/apt.conf.d/
01-vendor-ubuntu      15update-stamp       20snapd.conf           99update-notifier
01autoremove          20apt-esm-hook.conf  50command-not-found
01autoremove-kernels  20archive            50unattended-upgrades
10periodic            20auto-upgrades      70debconf
$ apt-config dump | grep lean
APT::Periodic::AutocleanInterval "0";
```

Nonetheless, it is set to "0" (disabled), so there *shouldn't* be a periodic job running `apt-get clean`.
