### ISSUE TITLE
Can you upload these artifacts to the Acs mirror?

### ISSUE THREAD

**Issue by pjohnst5** [Azure/aks-engine#4660]
**Describe the request**
AKS will be using ARM64 GOARCH soon, and requested that Container Networking upload the bits to the acs-mirror where AKS consumes them. We typically do this through Aks-engine folk, hoping you could help out, or maybe show me how

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pjohnst5** [comment]
@sozercan can you upload these artifacts to the acs mirror please?

https://github.com/Azure/azure-container-networking/releases/download/v1.4.12/azure-vnet-cni-linux-arm64-v1.4.12.tgz
https://github.com/Azure/azure-container-networking/releases/download/v1.4.12/azure-vnet-cni-swift-linux-arm64-v1.4.12.tgz

**Comment by sozercan** [comment]
this is uploaded by @matmerr's team now

**Comment by matmerr** [comment]
yep @pjohnst5, these files already exist, ex:
https://acs-mirror.azureedge.net/azure-cni/v1.4.12/binaries/azure-vnet-cni-linux-amd64-v1.4.12.tgz

**Comment by pjohnst5** [comment]
My bad, thanks guys
