### ISSUE TITLE
No response to "%self%.svc.cluster.local" from within the container

### ISSUE THREAD

**Issue by adoprog** [Azure/aks-engine#4687]
**Describe the bug**
After the recent upgrades applying latest images to the clusters, some of them have stopped responding to its own internal name within the containers. This applies to approximately 10 out of 20 clusters, they're all on the same version - 1.21.2

**Steps To Reproduce**
On affected cluster, I can't run 
`
curl "http://SERVICENAME.NAMESPACE.svc.cluster.local/" -usebasicparsing
`
from within "SERVICENAME", but it works from other pods in the same namespace.

The error is:
curl : Unable to connect to the remote server

Meanwhile,

`
curl "http://localhost/" -usebasicparsing
`

works

**Expected behavior**
It should be possible to request the service from itself via internal name

**AKS Engine version**

**Kubernetes version**
1.21.2

**Additional context**

**Comment by scbap** [comment]
Hi @adoprog 

Can you provide the previous AKS version?

Bart

**Comment by bridgetkromhout** [comment]
Hi, @adoprog - as we did not hear back, we aren't sure if you're even using AKS Engine; at this time, AKS Engine is deprecated. Please see the project status (https://github.com/Azure/aks-engine#project-status) and use either AKS or CAPZ as your needs require. If this issue exists in AKS, please open a support request there. Thanks!
