### ISSUE TITLE
aks-engine does not allow 2 masters when using Etcd CosmosDb

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/aks-engine#469]
**Is this a request for help?**:
no
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.30.0
---

**Kubernetes version**:
N/A

**What happened**:
aks-engine does not allow 2 masters when using Etcd in CosmosDb (only 1,3,5 allowed).

**What you expected to happen**:
Don't complain about 2 masters when using Etcd in CosmosDb. 2 masters make perfect sense as no quorum is required in that case.

**How to reproduce it** (as minimally and precisely as possible):
Use example for EtcdCosmosDb and change master count to 2, then try to deploy.

**Anything else we need to know**:
https://github.com/Azure/aks-engine/blob/b1ffc7545cfedb759763d0a0c2bb44507cab8ff9/pkg/api/vlabs/types.go#L377 - here is the problem

**Comment by UncleTawnos** [comment]
any update / ETA on that?
