### ISSUE TITLE
Cannot update Metrics-Server deployment. It reverts after saving the deployment change. 

### ISSUE THREAD

**Issue by jkengland** [Azure/aks-engine#4692]
**Describe the bug**
When editing the deployment yml for metrics-server it reverts to the original state. We need to add the following command 

--kubelet-preferred-address-types Internal IP,Hostname,Internal DNS,External DNS,External IP

 A new pod gets spun up, then destroyed then re created with the original settings. When I check the deployment after making the changes, the original settings are there. 

**Steps To Reproduce**
tested in non-prod as well as prod cluster and both are unable re-deploy with new changes.

**Expected behavior**
deployment saves and new pods get deployed with changes. 
**AKS Engine version**
0.57.0
**Kubernetes version**
1.18.8
**Additional context**

**Comment by jadarsie** [comment]
The addons specified in your API Model (check `properties.orchestratorProfile.kubernetesConfig.addons`) are ensured by [addon manager](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager).

The default mode is `Reconcile` (check apimodel). That means that addon manager will always try to converge to the addon spec (stored in the control plane VMs file system under /etc/kubernetes/addons).

If you change mode to `EnsureExists`, then addon manager won't undo your changes unless you delete the deployment. Remember to  keep the apimodel and the addon yaml in sync.

**Comment by jadarsie** [comment]
There is no way to specify the value of this flag at this point. You can though submit a PR with the proposed change including a well crafted justification of why the new flag value is beneficial to every one using aks-engine.

https://github.com/Azure/aks-engine/blob/master/parts/k8s/addons/metrics-server.yaml#L142

https://github.com/Azure/aks-engine/blob/master/docs/community/developer-guide.md
