### ISSUE TITLE
Update nvidia driver to 410.79+ to allow cuda-10 and ubuntu-18.04 inside containers

### ISSUE THREAD

**Issue by overplumbum** [Azure/aks-engine#471]
**Is this a request for help?**:
no
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of aks-engine?**:
v0.30.0
---

As seen in https://github.com/Azure/aks-engine/blob/v0.30.0/parts/k8s/kubernetesprovisionsource.sh#L55

```
GPU_DV=396.26
```

aks-engine still use 396 nvidia driver, which is not supported by cuda v10.0, — minimal cuda version supporting ubuntu-18.04 **inside containers**.

It's quite a problem that Ubuntu-18.04 can't be used **inside containers** for Cuda workloads because of this old driver version.

It will be really great have something like `GPU_DV=410.79` in aks-engine.

**Comment by brendandburns** [comment]
PR for this is here:

https://github.com/Azure/aks-engine/pull/634
