### ISSUE TITLE
Publish releases for darwin-arm64 "Apple silicon"

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#4715]
**Describe the request**

It would be great if future releases could be published for `darwin-arm64` to run natively on M1 CPUs. 

**Explain why AKS Engine needs it**

While the `darwin-amd64` binary works fine on new Macs, scripts like `get-akse.sh` fail since the detected architecture isn't supported.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bridgetkromhout** [comment]
After conferring with @mboersma I am closing this enhancement issue, based on the [AKS Engine deprecation statement](https://github.com/Azure/aks-engine#project-status).
