### ISSUE TITLE
CIS Benchmark Improvements

### ISSUE THREAD

**Issue by dtzar** [Azure/aks-engine#4735]
**Describe the request**
Ran the default CIS Benchmark tests via the Calico demo and these failed using these [default azure cli commands to install from the workshop](https://github.com/tigera-solutions/calicocloud-aks-workshop/blob/main/modules/creating-aks-cluster.md).  I deployed a 1.22.2 cluster.

2.1.12 - Ensure that the --rotate-certificates argument is not set to false (Scored)
2.2.3 - Ensure that the kubelet service file permissions are set to 644 or more restrictive (Scored)
2.2.5 - Ensure that the proxy kubeconfig file permissions are set to 644 or more restrictive (Scored)
2.1.6 - Ensure that the --protect-kernel-defaults argument is set to true (Scored)
2.1.10 - Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Scored)

**Explain why AKS Engine needs it**
To have more secure baseline clusters by default.

**Describe the solution you'd like**
Pass these results.

**Describe alternatives you've considered**
I'd have to dig up which version of CIS benchmark they're using.. but this is [baked into their product](https://github.com/tigera-solutions/calicocloud-aks-workshop/blob/main/demo/40-compliance-reports/daily-cis-results.yaml) and results seem reasonable to correct.  Some might not apply by design.

**Comment by dtzar** [comment]
Related issue https://github.com/Azure/AKS/issues/2179

**Comment by bridgetkromhout** [comment]
Hi there, @dtzar! 👋 I'm checking up on old issues in this AKS Engine repo, and I'm trying to understand if we are talking about AKS Engine in this case? I looked at the lab you linked, and that looked like it was directing people to create AKS clusters. Please let us know if you see something specific to AKS Engine we should be looking at (while keeping in mind that AKS Engine is [no longer under active development](https://github.com/Azure/aks-engine#project-status)).

**Comment by dtzar** [comment]
This was for AKS and I can see is replaced by more current https://github.com/Azure/AKS/issues/2776
