### ISSUE TITLE
creating new  cluster with  network plugin: kubenet creating  route  new route table automatically

### ISSUE THREAD

**Issue by cramakan** [Azure/aks-engine#4738]
creating new  cluster with  network plugin: kubenet creating  route  new route table automatically ,I do  not  want this should  create automatically, i have another  route table that one i want to use, but can not see any  parameter to override this

**AKS Engine Version**  : 0.67.0

**Kubernetes Version** :1.21.5

**Comment by jadarsie** [comment]
Found this https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#kubenet-networking-custom-vnet
