### ISSUE TITLE
Wrong release?

### ISSUE THREAD

**Issue by jcobb48** [Azure/aks-engine#4741]
Seems that there is something wrong with the last release:

When about to deploy a new cluster, I saw that aks-engine version was dirty:
```
~$ aks-engine version        
Version: v0.67.0
GitCommit: 1da9b5e
GitTreeState: dirty
```
So I run the get-aks.sh script and got this:
```
~$ ./get-akse.sh
AKS-Engine v0.60.2 is available. Changing from version v0.67.0.
Downloading https://github.com/Azure/aks-engine/releases/download/v0.60.2/aks-engine-v0.60.2-linux-amd64.tar.gz
Preparing to install aks-engine into /usr/local/bin
aks-engine installed into /usr/local/bin/aks-engine
Run 'aks-engine version' to test.
~$ aks-engine version                            
Version: v0.60.2
GitCommit: 1482217
GitTreeState: clean
```

At that point I saw the releases in github and found:
![image](https://user-images.githubusercontent.com/61519958/141387663-d5ed07f1-c673-4ced-8d29-1bb23f80bc56.png)

**Comment by mboersma** [comment]
See also #4734.

**Comment by bridgetkromhout** [comment]
Hi, @jcobb48 - yes, the script will download the [latest release](https://github.com/Azure/aks-engine/releases), and in rare circumstances, that may be a patched version of an older release. As AKS Engine is being deprecated, this will not be a frequent problem going forward. 

From the [README - Project status](https://github.com/Azure/aks-engine#project-status), you can see your options, which include using AKS for managed Kubernetes (which is recommended for many use cases). Please let us know about any questions we can answer.
