### ISSUE TITLE
Outdated Documentation (Tutorials "customer-vnet.md")

### ISSUE THREAD

**Issue by dipito31** [Azure/aks-engine#475]
**Is this a request for help?**: 
NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
latest
---

**Kubernetes version**:
Latest

**What happened**:
Outdated documentation within docs-> tutorials -> custom-vnet.md
These are all related to ACS engine.

**What you expected to happen**:
These should be updated for EKS engine

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by serbrech** [comment]
Hi, @dipito31  Thanks for reporting this issue.
Could you be more specific as to which part you mean is outdated?

I can see that the document uses `swarm` orchestrator as an example and `Azure Container Services`. That should be fixed.

Note that the process is still valid.
We'll add it to our backlog, meanwhile, you're welcome to send us a PR if you get to it before us.

**Comment by marlonsingleton** [comment]
Hello @dipito31, are you referring to Amazon EKS? If so, you'll have to reference their documentation for a tutorial.

Sorry, I was hoping to perform a pull request to see if I could assist but I don't think there's anything that can be done.

**Comment by dipito31** [comment]
@serbrech I was referring to both the documentation and the CLI commands that refer to ACS or have outdated commands in there. Such as:

`az group create -n acs-custom-vnet -l "westeurope"`

`az group deployment create -g acs-custom-vnet --name "CustomVNet" --template-file azuredeploy.swarm.vnet.json`

> Note: This article describes the procedure with Docker Swarm but it will work in the exact same way with the all the orchestrators available with AKS Engine: Docker Swarm, Kubernetes and DC/OS.

The above isn't possible with AKS engine ... so the documentation for Swarm and DC/OS inaccurate.
