### ISSUE TITLE
aks-engine upgraded only 1 master of 3 total in cluster

### ISSUE THREAD

**Issue by Zeka13** [Azure/aks-engine#4751]
**Describe the bug**

Hello, I am trying to upgrade my master instance from Standard_D2s_v4 to Standard_D4s_v4 type

For this I am doing 
`aks-engine upgrade --debug --control-plane-only \
  --subscription-id XX-XX-XX-XX-XX \
  --api-model /home/somepath/_output/my-prod/apimodel.json \
  --location eastus \
  --resource-group my-prod \
  --upgrade-version 1.19.6 --force`

I can see one of the masters replaced, but other two not and I am getting this error after long time of waiting (one hour)
Seems like after replacing one vm aks-engine just doing nothing

**Error**: upgrading cluster: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded

What can you suggest please? Thanks in advance

Here is full log

```
WARN[0000] Ephemeral disks are enabled for Agent Pool gateway4. This feature in AKS-Engine is experimental, and data could be lost in some cases. 
WARN[0000] Ephemeral disks are enabled for Agent Pool gateway5. This feature in AKS-Engine is experimental, and data could be lost in some cases. 
DEBU[0000] Resolving tenantID for subscriptionID: 27ef9916-c320-4c25-90a7-bcef8b0f9769 
DEBU[0004] Already registered for "Microsoft.Compute"   
DEBU[0004] Already registered for "Microsoft.Storage"   
DEBU[0004] Already registered for "Microsoft.Network"   
INFO[0006] Upgrading cluster with name suffix: 24510007 
INFO[0006] Master VM name: k8s-master-24510007-0, orchestrator: 1.19.6 (MasterVMs) 
INFO[0006] Master VM name: k8s-master-24510007-1, orchestrator: 1.19.6 (MasterVMs) 
INFO[0006] Master VM name: k8s-master-24510007-2, orchestrator: 1.19.6 (MasterVMs) 
INFO[0006] Upgrading control plane nodes to Kubernetes version 1.19.6 
INFO[0006] Master nodes StorageProfile: ManagedDisks    
INFO[0006] Prepping master nodes for upgrade...         
INFO[0006] Resource count before running NormalizeResourcesForK8sMasterUpgrade: 40 
INFO[0006] Removing Microsoft.Compute/availabilitySets dependency from [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))] 
INFO[0006] Resource count after running NormalizeResourcesForK8sMasterUpgrade: 5 
INFO[0006] Total expected master count: 3               
INFO[0006] Master nodes that need to be upgraded: 3     
INFO[0006] Master nodes that have been upgraded: 0      
INFO[0006] Starting upgrade of master nodes...          
INFO[0006] masterNodesInCluster: 3                      
INFO[0006] Expected master count: 3, Creating 0 more master VMs 
INFO[0006] Upgrading Master VM: k8s-master-24510007-0   
INFO[0007] deleting VM k8s-master-24510007-0 in resource group anzu-prod ... 
INFO[0158] deleting NIC k8s-master-24510007-nic-0 in resource group anzu-prod ... 
INFO[0169] deleting managed disk k8s-master-24510007-0_OsDisk_1_960ea7fdc21a4c6bba2637d32dada3b0 in resource group anzu-prod ... 
INFO[0231] deleting role assignment /subscriptions/27ef9916-c320-4c25-90a7-bcef8b0f9769/resourcegroups/anzu-prod/providers/Microsoft.Authorization/roleAssignments/1e664b3a-c5be-54a7-8811-962471b5058a ... 
INFO[0232] Master offset: 0                             
INFO[0232] Master pool set count to: 1 temporarily during upgrade... 
INFO[0232] Starting ARM Deployment k8s-upgrade-master-0-21-11-22T18.46.27-1085956954 in resource group anzu-prod. This will take some time... 



INFO[3606] Finished ARM Deployment (k8s-upgrade-master-0-21-11-22T18.46.27-1085956954). Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded 
INFO[3606] Error creating upgraded master VM: k8s-master-24510007-0 
Error: upgrading cluster: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
```

**AKS Engine version**
v0.59.0

**Kubernetes version**
1.19.6

**Comment by jadarsie** [comment]
If the cluster is healthy, you can retry.

Otherwise, check the resource groups deployments (https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal), hopefully that will tell you what went wrong.

If the ARM deployment is OK, then fetch the provisioning logs to understand where the bootstrapping process broke (https://github.com/Azure/aks-engine/blob/master/docs/topics/get-logs.md)

**Comment by Zeka13** [comment]
@jadarsie thanks for pointing me to Deployment log

This is the error I get 
`{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=30\n[stdout]\nMon Nov 22 16:49:25 UTC 2021,k8s-master-24510007-0\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
}`

**Comment by Zeka13** [comment]
fix I replaced the instances with bigger type manually from Azure portal
