### ISSUE TITLE
ImageGCFailed in master nodes in aks-engine cluster

### ISSUE THREAD

**Issue by sikasam** [Azure/aks-engine#4754]
We neither made any new changes nor added more containers. Kubelet is facing only the Disk pressure.
Due to this, most of the pods running on master nodes are getting evicted.
How to debug this further and fix? Any known issue?

Checked the "docker images" and containers but they are not consuming lot of disk too.

**Warning ImageGCFailed 2m52s (x3935 over 24d) kubelet, k8s-master-xxxxxxx-1 (combined from similar events): failed to garbage collect required amount of images. Wanted to free 1972314931 bytes, but freed 0 bytes**

In the below result, only sdc1 has been consumed 90% while sda1 and sdb1 are rarely used. If the above issue can be due to this, how to modify the disk usage to point to sda1/sdb1?

xxxx@k8s-master-xxxxxxx-0:/dev$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             56G     0   56G   0% /dev
tmpfs            12G  2.6M   12G   1% /run
**/dev/sdc1        29G   26G  3.1G  90% /**
tmpfs            56G  8.0K   56G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            56G     0   56G   0% /sys/fs/cgroup
/dev/sdc15      105M  8.9M   96M   9% /boot/efi
**/dev/sda1       787G   73M  747G   1% /mnt**
**/dev/sdb1      1007G  473M  956G   1% /var/lib/etcddisk**
tmpfs            12G     0   12G   0% /run/user/1000

**Comment by bridgetkromhout** [comment]
Hi, @sikasam - it's not clear that this is an AKS Engine issue, but a good page to read is https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images - that should assist with garbage collection.
