### ISSUE TITLE
would it cause problems if we change system nodel labels

### ISSUE THREAD

**Issue by brenguy** [Azure/aks-engine#4770]
I would like to change the label 
from: 
"AGENT_LABELS="kubernetes.azure.com/role=agent kubernetes.io/role=agent node-role.kubernetes.io/agent=" 

to:
"AGENT_LABELS="kubernetes.azure.com/role=worker kubernetes.io/role=agent node-role.kubernetes.io/worker=" 

would that cause any issues with AKS? Does AKS expect these values to be set to agent?

**Comment by jadarsie** [comment]
Do you mean AKS or AKS Engine? if AKS, go here https://github.com/Azure/aks

To your question, the code base says `they need to be present for backward compatibility`.

Will it work for you if you add more labels instead of replacing?

**Comment by bridgetkromhout** [comment]
Hi, @brenguy - as @jadarsie points out, AKS is different from AKS Engine. If you are in fact using AKS Engine, please be aware that the AKS Engine project is no longer being actively developed. From the [README - Project status](https://github.com/Azure/aks-engine#project-status), you can see your options, which include using AKS for managed Kubernetes (which is recommended for many use cases). Please let us know about any questions we can answer.
