### ISSUE TITLE
Issues with scaling VMSS

### ISSUE THREAD

**Issue by Ramu432** [Azure/aks-engine#4776]
We are having issues with adding additional capacity to our production VMSS groups.

We are receiving the following error message when trying to add additional capacity to VMSS:

VM has reported a failure when processing extension 'vmssCSE'. Error message: "Enable failed: failed to execute command: command terminated with exit status=166 [stdout] Fri Nov 26 14:26:04 UTC 2021,k8s-f64sv2az2-25250458-vmss0008Y9 [stderr] " More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot

We have done some more investigation around this issue and this looks to be related to AKS. It is failing on running the following command:

curl -fsSL https://repo.iovisor.org/GPG-KEY

Which looks to be related to a failed SSL certificate. Can someone help us out on this issue?

**Comment by bridgetkromhout** [comment]
Hi, @Ramu432 - when you say that the problem seems to be AKS, do you mean AKS itself? Or AKS Engine? Thanks.

**Comment by bridgetkromhout** [comment]
To follow up on my previous message, AKS Engine is deprecated. Please see the project status (https://github.com/Azure/aks-engine#project-status) and use either AKS or CAPZ as your needs require. And if the issue is AKS, please open a support ticket - thanks!
