### ISSUE TITLE
AKS-E+VMSS upgrade causes reboot

### ISSUE THREAD

**Issue by palma21** [Azure/aks-engine#478]
Problem: Azure cloudprovider calls UpdateInstances() as a workaround to update the LB backendpools for VMSS (since an API for this for this does not exist yet). Regrettably, UpdateInstances() is the same/only API call to manually upgrade VMSS models if there is a model upgrade pending (this can be any model change on the VMSS, like image change), that will restart instances if upgraded.

So, if the cluster has an LB service associated, and there is a VMSS model upgrade pending: even if there is only an update/scale on the non-primary scale set, cloudprovider will call manual update (updateInstances()) for the primary scale set resulting in all primary scale set VMs restarting at once.

Fix: 
1) Switch to using standard load balancer;

2) Remove primaryScaleSet in azure.json

3) Add a new scaleset for upgrade, cordon and drain old scaleset and then delete old scaleset (this prevents all instances being restarted at once).

**Comment by jackfrancis** [comment]
@feiskyer Is there another canonical issue for this known behavior?

**Comment by feiskyer** [comment]
yep, this is knowns issues. We are waiting for new network profile update APIs from VMSS team.

**Comment by palma21** [comment]
Needs requirements meeting before progressing.
Booked

**Comment by sylr** [comment]
Related to this I think: https://github.com/kubernetes/kubernetes/issues/71594

**Comment by alexeldeib** [comment]
Does this issue imply VMSS **scale** operation with a single agent pool results in reboot of all nodes (== downtime blips)?

**Comment by craiglpeters** [comment]
From @palma21 

> 1.14: https://github.com/kubernetes/kubernetes/pull/76992 (merged)
> 1.13: https://github.com/kubernetes/kubernetes/pull/76993 (on the merge queue)
> 1.12: https://github.com/kubernetes/kubernetes/pull/76994 (merged)
> 1.11: https://github.com/kubernetes/kubernetes/pull/77069 (merged, and included in v1.11.10)

**Comment by alexeldeib** [comment]
Is there anything actually needed for this to be marked fixed other than testing? This should "just work" with the upstream work I think?

**Comment by jackfrancis** [comment]
@alexeldeib Correct, we should do some due diligence manual validation and then close this

**Comment by alexeldeib** [comment]
n.b. for anyone revisiting this https://github.com/kubernetes/kubernetes/issues/80365

**Comment by mboersma** [comment]
I've tested this scenario described initially with Kubernetes 1.16.0 and 1.15.4 and don't see misbehavior. VMSS nodes are not rebooted all at once (in fact, changing the VM size or scaling via the portal leaves existing nodes intact and upgrading to the latest model appears to be a manual task). Everything stays attached to the LB throughout. Looks like the errant call to `updateInstances()` is gone. :+1:
