### ISSUE TITLE
Error: loading API model: error parsing the api model: networkPolicy 'calico' is not supporting windows agents

### ISSUE THREAD

**Issue by bjo004** [Azure/aks-engine#4819]
Using aks-engine to install kubernetes and straight away getting the error. 

Error: loading API model: error parsing the api model: networkPolicy 'calico' is not supporting windows agents

`{
    "apiVersion": "vlabs",
    "location": "<LOCATION>",
    "properties": {
        "orchestratorProfile": {
            "orchestratorRelease": "1.20",
            "orchestratorVersion": "1.20.11",
            "kubernetesConfig": {
                "cloudProviderBackoff": true,
                "cloudProviderBackoffRetries": 1,
                "cloudProviderBackoffDuration": 30,
                "cloudProviderRateLimit": true,
                "cloudProviderRateLimitQPS": 100,
                "cloudProviderRateLimitBucket": 150,
                "cloudProviderRateLimitQPSWrite": 25,
                "cloudProviderRateLimitBucketWrite": 30,
                "useInstanceMetadata": false,
                "networkPlugin": "azure",
                "networkPolicy": "calico",
                "clusterSubnet": "10.30.40.0/21",
                "kubeletConfig": {
                    "--node-status-update-frequency": "1m",
                    "--max-pods": "110"
                },
                "controllerManagerConfig": {
                    "--node-monitor-grace-period": "5m",
                    "--pod-eviction-timeout": "5m",
                    "--route-reconciliation-period": "1m"
                }
            }
        },
        "customCloudProfile": {
            "portalURL": "<PORTAL_URL>",
            "identitySystem": ""
        },
        "featureFlags": {
            "enableTelemetry": true
        },
        "masterProfile": {
            "dnsPrefix": "prdsabb",
            "vnetSubnetId": "<VNET_SUBNET_ID>",
            "firstConsecutiveStaticIP": "10.30.47.224",
            "distro": "aks-ubuntu-18.04",
            "count": 3,
            "vmSize": "Standard_D1_v2"
        },
        "agentPoolProfiles": [
            {
                "name": "linuxpool",
                "count": 3,
                "vnetSubnetId": "<VNET_SUBNET_ID>",
                "vmSize": "Standard_D1_v2",
                "distro": "aks-ubuntu-18.04",
                "availabilityProfile": "AvailabilitySet",
                "AcceleratedNetworkingEnabled": false
            },
            {
                "name": "windowspool",
                "count": 1,
                "vnetSubnetId": "<VNET_SUBNET_ID>",
                "vmSize": "Standard_D1_v2",
                "osType": "Windows",
                "availabilityProfile": "AvailabilitySet",
                "AcceleratedNetworkingEnabled": false
            }
        ],
        "linuxProfile": {
            "adminUsername": "<ADMIN_USERNAME>",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": "<SSH_PUBLIC_KEY>"
                    }
                ]
            }
        },
        "windowsProfile": {
            "adminUsername": "<USERNAME>",
            "adminPassword": "<PASSWORD>",
            "windowsPublisher": "MicrosoftWindowsServer",
            "windowsOffer": "WindowsServer",
			"windowsSku": "2019-Datacenter"
        },
        "servicePrincipalProfile": {
            "clientId": "<CLIENT_ID>",
            "secret": "<CLIENT_SECRET>"
        }
    }
}`
Kind regards,

Bankole.

**Comment by bridgetkromhout** [comment]
Hi, @bjo004 - If you are just starting a new cluster, we recommend you do not start it with AKS Engine. We are not adding new features to AKS Engine, as this project is no longer being actively developed. From the [README - Project status](https://github.com/Azure/aks-engine#project-status), you can see your options, which include using AKS for managed Kubernetes (which is recommended for many use cases). Please let us know about any questions we can answer.
