### ISSUE TITLE
Please mark coredns with soft anti-pod-affinity in AKS-Engine

### ISSUE THREAD

**Issue by DanielHajduk2-TomTom** [Azure/aks-engine#4831]
**Describe the request**

Please allow configuring coredns deployment without having to patch it explicitly. (at least the affinity)

**Explain why AKS Engine needs it**

In case a single node goes down and all coredns pods are running on that one node -> DNS resolution in the whole cluster will be down for brief amount of time.

**Describe the solution you'd like**

Being able to specify that coredns should have a soft affinity to be scheduled on a different nodes if possible..

**Describe alternatives you've considered**

Patching coredns which is managed by AKS-Engine

**Additional context**

Patching is not a good solution for CI - hacks

**Comment by bridgetkromhout** [comment]
Hi, @DanielHajduk2-TomTom - Please use [AKS User Voice](https://feedback.azure.com/d365community/forum/aabe212a-f724-ec11-b6e6-000d3a4f0da0) to request features for AKS. Thanks!
