### ISSUE TITLE
Documentation how to easily migrate from aks-engine to AKS

### ISSUE THREAD

**Issue by jprecuch** [Azure/aks-engine#4836]
**Describe the request**
Is there some recommended way how we can easily migrate from aks-engine to AKS? 
If yes, can it be added to the aks-engine repository?

I found only https://docs.microsoft.com/en-us/azure/aks/aks-migration but that is mostly general migration. Would be much better to have one which is closely written to aks-engine.

**Explain why AKS Engine needs it**
The aks-engine is slowly being deprecated. This would point all customers using aks-engine to properly migrate their clusters to AKS with limited/no downtime?

**Describe the solution you'd like**
Documentation written  for aks-engine migration to AKS

**Comment by bridgetkromhout** [comment]
Hi, @jprecuch - while there isn't a one-size-fits-all method, we can definitely add some migration steps to the AKS Engine docs to help AKS Engine users move onto AKS. Thanks!

**Comment by bridgetkromhout** [comment]
Note: this is the AKS docs page on migration: https://docs.microsoft.com/en-us/azure/aks/aks-migration

**Comment by jprecuch** [comment]
Thanks @bridgetkromhout . Would it be the official page from aks-engine team we should use or do you plan to release some more detailed one? Just to be sure

**Comment by bridgetkromhout** [comment]
Hi, @jprecuch - as you've probably seen, AKS migration can have specifics that are best covered by the AKS team's documentation in  https://docs.microsoft.com/en-us/azure/aks/aks-migration. If you have questions that aren't answered there, using the Feedback box at the bottom of that page is the way to ensure they get those docs updated correctly. The AKS Engine project encourages the use of the official AKS migration docs on that page. Thanks!
