### ISSUE TITLE
Scaling up and down masters

### ISSUE THREAD

**Issue by chmielas** [Azure/aks-engine#484]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of aks-engine?**:
0.30.1
---

**Kubernetes version**:
1.10.12

**What happened**:
I want to scale up and down masters in cluster ? It is possible with aks-engine ? I could not find such a description in the documentation  (there is the only description for scaling workers).

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by serbrech** [comment]
@ritazh if you want to weigh in on this

**Comment by ritazh** [comment]
AFAIK I dont think we support scaling of master nodes, scale only works for agent nodes.
> The aks-engine scale command can increase or decrease the number of nodes in an existing agent pool in an aks-engine Kubernetes cluster. Nodes will always be added or removed from the end of the agent pool. Nodes will be cordoned and drained before deletion.

https://github.com/Azure/aks-engine/blob/master/docs/topics/scale.md
