### ISSUE TITLE
SSL Certificate - Signature Verification Failed

### ISSUE THREAD

**Issue by bajyow** [Azure/aks-engine#4853]
**Describe the bug**
Qualys is detecting vulnerability SSL Certificate - Signature Verification Failed Vulnerability Certificate #0 CN=Kubernetes_Ingress_Controller_Fake_Certificate,O=Acme_Co self signed certificate but cert is not found on the system
**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**
v0.47.0-aks-gomod-b9-aks
**Kubernetes version**

**Additional context**

**Comment by jadarsie** [comment]
aks-engine does not deploy ingress controllers, this looks like an user configuration, check you `Let's encrypt` certs

**Comment by jadarsie** [comment]
I am not sure the portal offers that feature for aks-engine clusters, maybe this link gives you some pointers: https://getbetterdevops.io/k8s-ingress-with-letsencrypt/
