### ISSUE TITLE
Update busybox image used in vhd

### ISSUE THREAD

**Issue by ritazh** [Azure/aks-engine#4864]
**Describe the request**
Update the busybox image used in the vhd to mcr.microsoft.com/oss/busybox/busybox:1.33.1

**Explain why AKS Engine needs it**
To reduce dockerhub throttling and overall security, all images referenced in the vhd and deployments should pull from mcr. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackfrancis** [comment]
We use busybox for some E2E test scenarios, and put it into the VHD to remove any potential runtime image pull issues from those flows.
