### ISSUE TITLE
busybox image is currently installed from docker hub, it is also available in mcr. We can use mcr busybox instead.

### ISSUE THREAD

**Issue by jikuma** [Azure/aks-engine#4870]
busybox image is pre pulled on VHD, for security concerns it's better if we pull this image from mcr. Most of the images are pulled from mcr except busybox. 
https://github.com/Azure/aks-engine/blob/master/vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2021.12.15.txt

**Comment by bridgetkromhout** [comment]
Hi, @jikuma - are you looking for a different change other than what's in https://github.com/Azure/aks-engine/pull/4869 - that should be in the next release. Thanks.

**Comment by jikuma** [comment]
That's what we need. Thanks @bridgetkromhout
