### ISSUE TITLE
Request Assistance for Testing WS2022 E2E

### ISSUE THREAD

**Issue by jaer-tsun** [Azure/aks-engine#4874]
**Describe the bug**
E2E tests (for ws2022) seem to hang in below test case

Summarizing 1 Failure:

[Fail] Azure Container Cluster using the Kubernetes Orchestrator regardless of agent pool type [It] should have the correct service account issuer when consuming a projected service account token

/__w/_temp/go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:1585

Ran 39 of 65 Specs in 5817.547 seconds

FAIL! -- 38 Passed | 1 Failed | 0 Pending | 26 Skipped

--- FAIL: TestKubernetes (5817.56s)

FAIL
**Steps To Reproduce**
run make test-kubernetes on [private branch](https://github.com/jaer-tsun/aks-engine/tree/hackForWs2022)

**Expected behavior**
expected to pass

**AKS Engine version**
[private build/branch](https://github.com/jaer-tsun/aks-engine/tree/hackForWs2022)

**Kubernetes version**

**Additional context**
Azure Container Cluster using the Kubernetes Orchestrator regardless of agent pool type 
should have the correct service account issuer when consuming a projected service account token 
/__w/_temp/go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:1575 
STEP: Launching a pod with a projected service account token 

$ k apply -f workloads/pod-projected-svc-token.yaml 

• Failure [1204.004 seconds] 
Azure Container Cluster using the Kubernetes Orchestrator 
/__w/_temp/go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:227 
regardless of agent pool type 
/__w/_temp/go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:228 
should have the correct service account issuer when consuming a projected service account token [It] 
/__w/_temp/go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:1575 

Unexpected error: 
<*errors.fundamental | 0xc000366618>: { 
msg: "WaitOnReady timed out: %!s(<nil>)\n", 
stack: [0x10cc5ec, 0x110eab2, 0x110ea7e, 0x82b37a, 0x82ad45, 0x82a43b, 0x82dc69, 0x82d647, 0x83a545, 0x83a265, 0x839aa5, 0x83bd52, 0x846745, 0x846559, 0x10f6fca, 0x50a622, 0x46ac41], 
} 
WaitOnReady timed out: %!s(<nil>) 

occurred 

/__w/_temp/go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:1585

This cmd always hangs for some reason

k apply -f workloads/pod-projected-svc-token.yaml

**Comment by bridgetkromhout** [comment]
@jaer-tsun Thanks for pointing this out. We are in the process of moving all tests away from using AKS Engine, because AKS Engine is deprecated as explained in the [AKS Engine project status](https://github.com/Azure/aks-engine#project-status).

**Comment by lzhecheng** [comment]
@jaer-tsun Hello! We are replacing aks-engine with CAPZ and AKS. Are you facing some issues with aks-engine Windows? Then could you try CAPZ?

**Comment by bridgetkromhout** [comment]
Hi, @jaer-tsun - closing this now because we are moving all tests away from using AKS Engine.
Please see https://cloud-provider-azure.sigs.k8s.io/development/e2e/e2e-tests/ for running e2e tests using CAPZ instead - thanks.
