### ISSUE TITLE
[Aks-Engine][Dev Tool] Support Dev Tool for M1 Chips

### ISSUE THREAD

**Issue by Czhang0727** [Azure/aks-engine#4880]
**Describe the request**
I am using my cool fashion M1 chip machine to bootstrap aks-engine repo.
However after I have my docker ran, all tools installed ( go, dep etc...), After I run make dev, I got:

``` console
docker run -it --rm -v /pkg/mod:/go/pkg/mod -v /Users/chenyizhang/source/aks-engine:/aks-engine -w /aks-engine  mcr.microsoft.com/oss/azcu/go-dev:v1.32.3 bash
Unable to find image 'mcr.microsoft.com/oss/azcu/go-dev:v1.32.3' locally
v1.32.3: Pulling from oss/azcu/go-dev
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
 ```

**Explain why AKS Engine needs it**
Since ARM chip is raising now and we should be able to support ARM CPU in dev environment. 

**Describe the solution you'd like**
I think update a newer version which supports M1 Chips will fix the problem. 
Will dig deeper into the registry.

**Describe alternatives you've considered**
Consider that M1 Chips are brand new, and Mac OS supports virtualization to x86 environment, I guess it should work if we use a x86 version of image, need to test this out.

However per my understanding, this wont fix this issue for other linux system. ( my lovely Raspberry Pi 4B with 8GB memo 🥲 )

**Additional context**
Let me know if any people already make it running, so we could simply ignore this report

**Comment by Czhang0727** [comment]
Per discuss, we will need to make a new container with arm64/v8 for Mac M1 Chips.

[docker-go-dev/Dockerfile at main · deis/docker-go-dev (github.com)](https://github.com/deis/docker-go-dev/blob/main/rootfs/Dockerfile)

**Comment by bridgetkromhout** [comment]
Hi, @Czhang0727 - This project is no longer under active development as explained in the [AKS Engine project status](https://github.com/Azure/aks-engine#project-status); additionally, Kubernetes 1.24 will be the last version of Kubernetes supported. 

We will not be adding M1 support or any other new features to AKS Engine. You should instead be using AKS for managed clusters or CAPZ for self-managed clusters. I'll close this issue now and reach out internally to ask some more detailed questions; thanks.
