### ISSUE TITLE
Azure metadata service not reachable due to ip-masq-agent since 0.23

### ISSUE THREAD

**Issue by palmerabollo** [Azure/aks-engine#495]
**Is this a request for help?**:

Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

---

**What version of aks-engine?**:

v0.30.1

---

acs-engine 0.23.0 added ip-masq-agent as an addon (see https://github.com/Azure/acs-engine/pull/3916). Since then, our clusters that need access to the Azure metadata API (i.e. http://169.254.169.254/metadata/) no longer work.

We haven't found a workaround (other than disabling the ip-masq addon). 

**Kubernetes version**:

1.10

**What happened**:

Azure metadata service not reachable.

**What you expected to happen**:

A configuration property to make Azure metadata service reachable again.

**How to reproduce it** (as minimally and precisely as possible):

- Deploy a cluster
- Run an alpine pod
- curl http://169.254.169.254/metadata/instance

**Anything else we need to know**:

https://github.com/Azure/aks-engine/issues/306 could be related

**Comment by qike-ms** [comment]
Go to master nodes and change manifest of ip-masq-agent to set: "masqLinkLocal: true" at: /etc/kubernetes/addons/ip-masq-agent.yaml. 

The root cause is when it's false, the pod ip addresses are not masqueraded in iptables (https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/). However, the host only accepts access to this address from vm ip. So for pods to access metadata service on the host, it has to use the vm ip and hence it has to mask pod ip.

**Comment by palmerabollo** [comment]
@qike-ms thanks for the tip.

According to https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/#create-an-ip-masq-agent:
> By default, the link local range (169.254.0.0/16) is also handled by the ip-masq agent, which sets up the appropriate iptables rules. To have the ip-masq-agent ignore link local, you can set masqLinkLocal to true in the config map.

Changing the manifest on the master nodes makes it difficult to automate the task (and master nodes could die) so I wonder if configuring this somewhere in the aks addons definition would do the trick as well:

```
nonMasqueradeCIDRs:
 - a.b.c.d/x
masqLinkLocal: true
```

**Comment by qike-ms** [comment]
Correct. This is being put in the TODO list of this project. If you can't wait for the fix, my recommendation is disable this add-on and install it yourself with this desired manifest. That should be easy and fast.

**Comment by palmerabollo** [comment]
not stale
