### ISSUE TITLE
Kube API high latency caused by etcd with custom image

### ISSUE THREAD

**Issue by luanadotcom** [Azure/aks-engine#496]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
0.28.0
---

**Kubernetes version**:
1.13.1

**What happened**:
We're seeing many etcd errors/warnings on our 3 master cluster with aks-engine: `server is likely overloaded`, `timed out waiting for read index response`, `took too long`, `failed to revoke x ("etcdserver: request timed out")`,...  which are causing kube API requests take too long/timeout.

Running the standard prometheus operator ruleset is resulting in lots of high latency alerts being fired for the kube api, that's what led me to the etcd errors and warnings.

**What you expected to happen**:
etcd can take the I/O and kube API requests go through seamlessly.

**How to reproduce it** (as minimally and precisely as possible):
3 master cluster, running standard Prometheus operator ruleset resulting in many high latency alerts fired for kube api.

**Anything else we need to know**:

**Comment by serbrech** [comment]
Hi @luanadotcom thanks for filing an issue.
Is this happening without any other load on the cluster?

**Comment by danmassie** [comment]
@serbrech Yes. We also see relatively high iowait on the masters when the kube api is reporting high latency which sounds like similar symptoms to https://github.com/Azure/acs-engine/issues/2510. 

https://github.com/Azure/aks-engine/blob/b5851ff48b1540215e8040020937b3b463121cc6/parts/k8s/kubernetesmasterresources.t#L911 looks as though the use of a custom image (we use a CIS hardened ubuntu image) for a VMAS master means the etcd disk size is ignored and it will instead use the OS disk which is defaulted to a 30GB HDD. I don't know why there isn't a managed disk created for etcd when both the manageddisk flag and the etcd disk size is specified. 

I've also created https://github.com/Azure/aks-engine/issues/532 for using SSD for the masters OS disk when a suitable VM is used.
