### ISSUE TITLE
We need a short term bridge of support for ubuntu 20.04 while working on Cluster API migration

### ISSUE THREAD

**Issue by Michael-Sinz** [Azure/aks-engine#4960]
**Describe the request**
We need to build clusters with Ubuntu 20.04 as 18.04 is hitting end of support on 4/2023

**Explain why AKS Engine needs it**
Just needs it long enough such that we can keep our services compliant until we finish the move to Cluster API

**Describe the solution you'd like**
Full support for 20.04 - it could be done as a replacement for 18.04 if needed

**Describe alternatives you've considered**
Cluster API is in the works but there are a lot of things yet to be covered and we need something we can roll out to remain compliant until that is ready to handle our technologies.

**Additional context**

**Comment by bridgetkromhout** [comment]
As we discussed today, https://github.com/Azure/aks-engine/releases/tag/v0.75.0 includes Ubuntu 20.04 support. Please re-open if anything additional is needed on this issue; as I understand it, the VHDs we're providing make Ubuntu 20.04 an option.
