### ISSUE TITLE
Disabling Unattended Upgrades Ignored

### ISSUE THREAD

**Issue by JamesR-120** [Azure/aks-engine#4984]
**Describe the bug**

Specifying the option 'linuxProfile.enableUnattendedUpgrades' to 'false' in the API Model doesn't appear to take effect. Even when set the following message is displayed during deployment 'WARN[0001] linuxProfile.enableUnattendedUpgrades configuration was not declared, your cluster nodes will be configured to run unattended-upgrade by default'

**Steps To Reproduce**
Set 'linuxProfile.enableUnattendedUpgrades' to 'false' in API Model.

    "linuxProfile": {
      "runUnattendedUpgradesOnBootstrap": false,
      "enableUnattendedUpgrades": false,
      "adminUsername": "admin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa "
          }
        ]
      }
    },

Run aksengine deploy.

INFO[0000] Writing cloud profile to: C:\Users\user\AppData\Local\Temp\azurestackcloud.json520222299
DEBU[0000] Already registered for "Microsoft.Compute"
DEBU[0000] Already registered for "Microsoft.Storage"
DEBU[0000] Already registered for "Microsoft.Network"
WARN[0000] linuxProfile.enableUnattendedUpgrades configuration was not declared, your cluster nodes will be configured to run unattended-upgrade by default
WARN[0000] NetworkPlugin 'azure' is a private preview feature on Azure Stack clouds
WARN[0001] apimodel: orchestratorProfile.kubernetesConfig.kubernetesImageBase forced to "mcr.microsoft.com/"
WARN[0001] apimodel: orchestratorProfile.kubernetesConfig.kubernetesImageBaseType forced to "mcr"

The output API Model does not include the 'enableUnattendedUpgrades ' setting and the unattended upgrade schedule remains in place.

    "linuxProfile": {
      "adminUsername": "admin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa "
          }
        ]
      },
      "runUnattendedUpgradesOnBootstrap": false,
      "eth0MTU": 1500
    },

**Expected behavior**

Setting 'enableUnattendedUpgrades' to 'false' disables the unattended-upgrade schedule.

**AKS Engine version**
0.70.0

**Kubernetes version**
1.22.7

**Additional context**
Platform is Disconnected ASH 2108.

**Comment by bridgetkromhout** [comment]
Hi, @JamesR-120 - Opening issues in this deprecated AKS Engine repo unfortunately will not get you any answers about Azure Stack Hub. Please open an issue in the Azure Stack Docs repo https://github.com/MicrosoftDocs/azure-stack-docs/issues so that team can guide you in the right direction - thanks!
