### ISSUE TITLE
aks-engine upgrade fails (1.9.2 to 1.10.9)

### ISSUE THREAD

**Issue by mchendil82** [Azure/aks-engine#499]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Yes

**What version of aks-engine?**:

aks-engine-v0.30.0-linux-amd64

**Kubernetes version**:
1.9.2

**What happened**:
aks-engine upgrades fails after upgrading first 1st master

**What you expected to happen**:
Acs-engine has to continue upgrading remaining master and agents to desired version 

**How to reproduce it** (as minimally and precisely as possible):
Try to upgrade 3 nodes, 3 agents clusters and it will fail after upgrading first master. I believe, its fails while validating the upgraded master. Errors as below:

INFO[0099] Starting ARM Deployment (master-xxxxxxxxx). This will take some time...
INFO[1274] Finished ARM Deployment (master-xxxxxx). Succeeded
INFO[1274] Error validating upgraded master VM: k8s-XXXXX-XXXX
FATA[1274] Error upgrading cluster: No Auth Provider found for name "azure"

**Anything else we need to know**:
After upgrades quits, kubectl get nodes shows that the only one master has been upgraded:
kubectl get nodes#
NAME                      STATUS    ROLES     AGE       VERSION
k8s-agentstd-xxxxxxxxxx   Ready     agent     19h       v1.9.2
k8s-agentstd-xxxxxxxxxx  Ready     agent     19h       v1.9.2
k8s-agentstd-xxxxxxxxx   Ready     agent     19h       v1.9.2
k8s-master-xxxxxxxxxx    Ready     master    14h       v1.10.9
k8s-master-xxxxxxxxxx    Ready     master    19h       v1.9.2
k8s-master-xxxxxxxxxx    Ready     master    19h       v1.9.2

**Comment by jackfrancis** [comment]
Hi @mchendil82,

That's odd to see such an auth error after one master vm was successfully upgraded. Can you retry the exact same upgrade command against the cluster and report back results?

**Comment by mchendil82** [comment]
Yes, we have given a retry. The sad part is that the acs-engine is not allowing to proceed the upgrade even if one of the node is already upgraded to the targeted newer version. In my case, one of the master is already upgraded from 1.9.2 to 1.10.9 and so it quits as per below logs:

DEBU[0000] Resolving tenantID for subscriptionID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0003] Already registered for "Microsoft.Compute"
DEBU[0003] Already registered for "Microsoft.Storage"
DEBU[0003] Already registered for "Microsoft.Network"
INFO[0005] Upgrading cluster with name suffix: xxxxxxxxxxxxxxxxxxx
WARN[0005] Failed to get a Kubernetes client: No Auth Provider found for name "azure"
INFO[0005] Evaluating VM: k8s-agentstd-xxxxxxxxxx in pool: agentstd...
INFO[0005] Adding Agent VM: k8s-agentstd-xxxxxxxxxx, orchestrator: Kubernetes:1.9.2 to pool: agentstd (AgentVMs)
INFO[0005] Evaluating VM: k8s-agentstd-xxxxxxxxxx  in pool: agentstd...
INFO[0005] Adding Agent VM: k8s-agentstd-xxxxxxxxxx , orchestrator: Kubernetes:1.9.2 to pool: agentstd (AgentVMs)
INFO[0005] Evaluating VM: k8s-agentstd-xxxxxxxxxx  in pool: agentstd...
INFO[0005] Adding Agent VM: k8s-agentstd-xxxxxxxxxx, orchestrator: Kubernetes:1.9.2 to pool: agentstd (AgentVMs)
FATA[0005] Error upgrading cluster: Error while querying ARM for resources: 1.10.9 cannot be upgraded to 1.10.9
github.com/Azure/aks-engine/pkg/operations/kubernetesupgrade.(*UpgradeCluster).upgradable
        /go/src/github.com/Azure/aks-engine/pkg/operations/kubernetesupgrade/upgradecluster.go:259
github.com/Azure/aks-engine/pkg/operations/kubernetesupgrade.(*UpgradeCluster).getClusterNodeStatus
        /go/src/github.com/Azure/aks-engine/pkg/operations/kubernetesupgrade/upgradecluster.go:182
github.com/Azure/aks-engine/pkg/operations/kubernetesupgrade.(*UpgradeCluster).UpgradeCluster
        /go/src/github.com/Azure/aks-engine/pkg/operations/kubernetesupgrade/upgradecluster.go:83
github.com/Azure/aks-engine/cmd.(*upgradeCmd).run
        /go/src/github.com/Azure/aks-engine/cmd/upgrade.go:260
github.com/Azure/aks-engine/cmd.newUpgradeCmd.func1
        /go/src/github.com/Azure/aks-engine/cmd/upgrade.go:62
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).execute
        /go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:762
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:852
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).Execute
        /go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:800
main.main
        /go/src/github.com/Azure/aks-engine/main.go:15
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333

**Comment by navicore** [comment]
I believe I had this effect upgrading using v0.26.1 but restarting the command after each master got past it. 

Today I'm trying to upgrade with v0.30.1 and it failed after first master but as above, the retry says:

```
Error upgrading cluster: Error while querying ARM for resources: 1.11.7 cannot be upgraded to 1.11.7
```

Is there a correct way to force a restart?

**Comment by jackfrancis** [comment]
We will investigate how to unblock these clusters. In the meantime, can folks kindly review this documentation and comment on (1) if any of the stated gotcha scenarios match your operational reality, and (2) how we can make the docs more clear? Basically, we'd like to know if there's a bug in upgrade (or if the clusters subject to these "fails after one master" symptoms have been modified out of band), and how we can better document/communicate the current `aks-engine upgrade` limitations to users.

**Comment by navicore** [comment]
Thanks @jackfrancis,

more info: I now see the cluster that is failing has violated the "no out of band change" rule in that it has had its public IP and LB deleted out of band - the cluster is older than the `privateCluster` flag and prior to that flag we had to delete the pip/lb as a post install step.

**Comment by jackfrancis** [comment]
You could try re-deploying the original ARM template to see if it reconciles the 1.11 master back to a 1.10 master.

```
az group deployment create \
    --name "<DEPLOYMENT NAME>" \
    --resource-group "<RESOURCE_GROUP_NAME>" \
    --template-file "./_output/<PATH_TO>/azuredeploy.json" \
    --parameters "./_output/<PATH_TO>/azuredeploy.parameters.json"
```

**Comment by navicore** [comment]
re-deploying the orig ARM gives:
```
  "error": {
    "code": "PublicIPAddressInUseCannotUpdateToDynamic",
```
I'm guessing this means we'll indeed have to apply the fix manually to this cluster and one other that have had their public IPs removed out of band.
