### ISSUE TITLE
Load Balancer directing traffic to one Backend pool(VM) :  aks-engine 0.67.0 & AKS 1.20.11

### ISSUE THREAD

**Issue by zohebs341** [Azure/aks-engine#4992]
Hi Team,

I've deployed the AKS cluster using aks-engine on Azure Stack Hub and it's up and running.

However the LoadBalancer is directing traffic to one Backend pool(one VM). In general, it should route traffic to all worker nodes.

When I'm trying to add a backend pool to already existing LoadBalancer, it's failing.

Is there a way to add a backend pool, as it's mandatory.

AKS version: 1.20.11

**Comment by jadarsie** [comment]
> However the LoadBalancer is directing traffic to one Backend pool(one VM).
> When I'm trying to add a backend pool to already existing LoadBalancer, it's failing.

The `basic` load balancer SKU only supports one backend pool.

> In general, it should route traffic to all worker nodes.

`kube-proxy` will redirect traffic to the corresponding node, even if the pod landed in VM that does not belong to the backend pool.

**Comment by zohebs341** [comment]
@jadarsie Hi Javier, thanks for your response.

Actually my use case is, in my cluster I'm having multiple nodepool like nodepool-1 to nodepool-5.

If LoadBalancer is routing traffic to only one Backendpool, in my case it's pointing to a nodepool which is having only one node(VM). 

How about other nodepools? If traffic is comming to these nodes, it will get rejected? As I'm not able to add these nodepools as a backendpool to that LoadBalancer. You got my point right?

**Comment by zohebs341** [comment]
In Azure Stack Hub (2102) which we are using, it's doesn't have an option to select Standard LoadBalancer. Only option for me is "Basic LoadBalancer"

**Comment by jadarsie** [comment]
Hi @zohebs341, see answers below please:

> If traffic is coming to these nodes, it will get rejected?

The kube-proxy daemonset applies the same iptables rules to every node, it won't be "rejected". Traffic will be eventually routed to the destination service no matter which node gets the initial request.

You can validate by specifying a `nodeSelector` that forces pods to land in a nodepool other than the one specified as the LB backend pool.

```yaml
nodeSelector:
  agentpool: <not-backend-pool>
```

> Only option for me is "Basic LoadBalancer"

Only Basic is supported.

**Comment by zohebs341** [comment]
@jadarsie I will test and update you tomorrow.

Thanks for your response and inputs.

**Comment by bridgetkromhout** [comment]
Hi, @zohebs341 - it seems your question has been answered; please let us know if you have additional questions. Thanks.
