### ISSUE TITLE
aks-engine quick start tutorial is failing, due to error: SkuNotAvailable

### ISSUE THREAD

**Issue by ronpel88** [Azure/aks-engine#5021]
**Description**
When running the quickstart tutorial with the basic `kubernetes.json` file, the `aks-engine deploy` command return the following error:
```bash
Error: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplateDeployment" Message="The template deployment 'contoso-apple-2124399508' is not valid according to the validation procedure. The tracking id is '18dfa592-cfa4-4b0b-aeee-1ba964ec452c'. See inner errors for details." Details=[{"code":"SkuNotAvailable","message":"The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_D2_v3, Standard_D2_v3' is currently not available in location 'westus2'. Please try another size or deploy to a different location or different zone. See https://aka.ms/azureskunotavailable for details."}]
```

**Steps To Reproduce**
Go over the quickstart guide step by step with the default configuration

**Expected behavior**
We want the resources to be created at Azure cloud, but instead of success, we are ending with failure. A new resource group is created but without any resources.

**Additional information**
Azure subscription is the most basic one

**Possible solutions**
- Change to region that supports the requested vm size
- Change the vm size to one that is available in the requested region
- run automated script to ensure that vm size is available in the requested region (`az vm list-skus --location <region> --size <vm_size_group> --all --output table`)

**Comment by bridgetkromhout** [comment]
Hi, @ronpel88 - the AKS Engine project is deprecated for Azure public cloud customers. Please consider using [Azure Kubernetes Service (AKS)](https://azure.microsoft.com/en-us/services/kubernetes-service/#overview) for managed Kubernetes or [Cluster API Provider Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure) for self-managed Kubernetes.

**Comment by bridgetkromhout** [comment]
Hi, @ronpel88 - I am resolving this issue since it is not recommended to start using AKS Engine. Please look at AKS for your Kubernetes needs instead; thanks!
