### ISSUE TITLE
SGX driver installation fails

### ISSUE THREAD

**Issue by lili8808** [Azure/aks-engine#5035]
I am trying to install SGX DCAP using link on vm with os ubuntu 20.04 https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html When I run command sudo ./sgx_linux_x64_driver_1.36.2.bin
```
Unpacking Intel SGX Driver ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX Driver ...
/tmp/sgx-driver-TPgGiQ /home/sama
install -d /opt/intel/sgxdriver/package
install -d /opt/intel/sgxdriver/scripts
cp -r package/* /opt/intel/sgxdriver/package
install scripts/* /opt/intel/sgxdriver/scripts
/home/sama

Creating symlink /var/lib/dkms/sgx/1.36.2/source ->
                 /usr/src/sgx-1.36.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' KDIR=/lib/modules/5.15.0-1023-azure/build....(bad exit status: 2)
ERROR (dkms apport): binary package for sgx: 1.36.2 not found
Error! Bad return status for module build on kernel: 5.15.0-1023-azure (x86_64)
Consult /var/lib/dkms/sgx/1.36.2/build/make.log for more information.
```

**Comment by bridgetkromhout** [comment]
Hi, @lili8808 - the AKS Engine Kubernetes cluster launching tool is deprecated, so you should not be starting to use it. If you need SGX-specific help you may find that in https://github.com/intel/linux-sgx but this AKS Engine repo will not have any SGX maintainers checking it to answer your question, so I'll resolve this issue now. Thanks.
