### ISSUE TITLE
[Question] ADFS integration with k8 RBAC

### ISSUE THREAD

**Issue by soocode** [Azure/aks-engine#5072]
Hi Team, 

I'm planning to deploy a cluster using aks-engine in Azure Stack Hub and using ADFS as an identity provider.
I want to use the same identity to access the aks-engine cluster by pointing the API model to ADFS and integrate it with k8 RBAC so that I don't have to separately manage another account.

My question:
It seems AAD can be integrated with AKS Engine-created cluster to use K8 RBAC. 
https://github.com/Azure/aks-engine/blob/master/docs/topics/aad.md
Can the accounts defined in ADFS be used to associate with K8 RBAC? 

I would appreciate if you could share any relevant documentation.

**Comment by soocode** [comment]
Tagging @jackfrancis for awareness. It would be greatly appreciate if we can have answers.

**Comment by bridgetkromhout** [comment]
Hi, @soocode - Jack is away for a bit. Perhaps @jadarsie can answer; this repo is also not a good source of Azure Stack Hub support and will be archived later this year (see https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-overview?view=azs-2206 instead). Thanks.

**Comment by soocode** [comment]
Hi, @bridgetkromhout thank you for letting me know. It seems the documentation has no answers for my question. I'll wait for @jadarsie's feedback.

**Comment by jadarsie** [comment]
@soocode, the doc page says ADFS is not supported (https://github.com/Azure/aks-engine/blob/master/docs/topics/aad.md#prerequisites)

Please log an issue here (https://github.com/Azure/aks-engine-azurestack/issues/new), I will try to understand what was the limitation on ADFS and based on that maybe find a solution.
