### ISSUE TITLE
Need to document or punt on committing generated files

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#509]
#449 made it easier to vendor in and `go get` aks-engine, but raised the bar for contributors, who are now expected to run `make generate` if any of the `*.po` or `parts/*` files are touched and include that as part of the commit.

Should we fix this situation with clearer documentation in CONTRIBUTING.md, or should we revert to not committing the generated files?

cc: @cchildress @Azure/aks-engine

**Comment by tariq1890** [comment]
I vote for "fixing this situation with clearer documentation in CONTRIBUTING.md"
