### ISSUE TITLE
How to download apimodel.json of existing cluster

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/aks-engine#5096]
Hello,

Is there any way to download the apimodel.json for existing cluster.

**Comment by jackfrancis** [comment]
@smartaquarius10 No, the apimodel.json is persisted locally from where the `aks-engine` binary is run.

You can download the ARM template in either the portal or CLI that represents the ARM deployment that initially ran your cluster, but you won't be able to use it w/ `aks-engine` (you can manually modify the JSON if you know what you're doing, but the whole reason for `aks-engine` was to prevent folks from having to do that 😎).

**Comment by bridgetkromhout** [comment]
Thanks, @jackfrancis! @smartaquarius10, I'm going to resolve this now - please be aware that AKS Engine is deprecated and won't support any versions of Kubernetes after 1.24. We recommend moving to AKS if possible, or CAPZ if you need a self-managed cluster solution.

**Comment by smartaquarius10** [comment]
@bridgetkromhout Oh thanks for sharing this update. 

I have asked this question to know if its possible to update maximum pods per node on existing AKS cluster.
