### ISSUE TITLE
Creating AKS-engine Cluster - VM Extension CSE Exit Code 30

### ISSUE THREAD

**Issue by JohonsonChan** [Azure/aks-engine#5102]
**Describe the request**
We are provisioning AKS-engine cluster in Poland Central region for AOAI, but failed in deploy VM Extension CSE for master node and the exit code is 30,

Poland Central is a new region which wasn't supported by AKS-enigne, could you help to add the region? If you have any concern please send e-mail to me yanchenzhang@microsfot.com.

Similar PR is required: [#4895 ]

**Error logs**
E0727 16:41:50.106540    5158 memcache.go:238] couldn't get current server API group list: Get "https://ameplcl1.polandcentral.cloudapp.azure.com/api?timeout=32s": x509: certificate is valid for ameplcl1.australiacentral.cloudapp.azure.com, ameplcl1.australiacentral2.cloudapp.azure.com, ameplcl1.australiaeast.cloudapp.azure.com, ameplcl1.australiasoutheast.cloudapp.azure.com, ameplcl1.brazilsouth.cloudapp.azure.com, ameplcl1.brazilsoutheast.cloudapp.azure.com, ameplcl1.canadacentral.cloudapp.azure.com, ameplcl1.canadaeast.cloudapp.azure.com, ameplcl1.centralindia.cloudapp.azure.com, ameplcl1.centralus.cloudapp.azure.com, ameplcl1.centraluseuap.cloudapp.azure.com, ameplcl1.chinaeast.cloudapp.chinacloudapi.cn, ameplcl1.chinaeast2.cloudapp.chinacloudapi.cn, ameplcl1.chinaeast3.cloudapp.chinacloudapi.cn, ameplcl1.chinanorth.cloudapp.chinacloudapi.cn, ameplcl1.chinanorth2.cloudapp.chinacloudapi.cn, ameplcl1.chinanorth3.cloudapp.chinacloudapi.cn, ameplcl1.eastasia.cloudapp.azure.com, ameplcl1.eastus.cloudapp.azure.com, ameplcl1.eastus2.cloudapp.azure.com, ameplcl1.eastus2euap.cloudapp.azure.com, ameplcl1.francecentral.cloudapp.azure.com, ameplcl1.francesouth.cloudapp.azure.com, ameplcl1.germanycentral.cloudapp.microsoftazure.de, ameplcl1.germanynorth.cloudapp.azure.com, ameplcl1.germanynortheast.cloudapp.microsoftazure.de, ameplcl1.germanywestcentral.cloudapp.azure.com, ameplcl1.japaneast.cloudapp.azure.com, ameplcl1.japanwest.cloudapp.azure.com, ameplcl1.jioindiacentral.cloudapp.azure.com, ameplcl1.jioindiawest.cloudapp.azure.com, ameplcl1.koreacentral.cloudapp.azure.com, ameplcl1.koreasouth.cloudapp.azure.com, ameplcl1.northcentralus.cloudapp.azure.com, ameplcl1.northeurope.cloudapp.azure.com, ameplcl1.norwayeast.cloudapp.azure.com, ameplcl1.norwaywest.cloudapp.azure.com, ameplcl1.qatarcentral.cloudapp.azure.com, ameplcl1.southafricanorth.cloudapp.azure.com, ameplcl1.southafricawest.cloudapp.azure.com, ameplcl1.southcentralus.cloudapp.azure.com, ameplcl1.southeastasia.cloudapp.azure.com, ameplcl1.southindia.cloudapp.azure.com, ameplcl1.swedencentral.cloudapp.azure.com, ameplcl1.switzerlandnorth.cloudapp.azure.com, ameplcl1.switzerlandwest.cloudapp.azure.com, ameplcl1.uaecentral.cloudapp.azure.com, ameplcl1.uaenorth.cloudapp.azure.com, ameplcl1.uksouth.cloudapp.azure.com, ameplcl1.ukwest.cloudapp.azure.com, ameplcl1.usdodcentral.cloudapp.usgovcloudapi.net, ameplcl1.usdodeast.cloudapp.usgovcloudapi.net, ameplcl1.usgovarizona.cloudapp.usgovcloudapi.net, ameplcl1.usgoviowa.cloudapp.usgovcloudapi.net, ameplcl1.usgovtexas.cloudapp.usgovcloudapi.net, ameplcl1.usgovvirginia.cloudapp.usgovcloudapi.net, ameplcl1.westcentralus.cloudapp.azure.com, ameplcl1.westeurope.cloudapp.azure.com, ameplcl1.westindia.cloudapp.azure.com, ameplcl1.westus.cloudapp.azure.com, ameplcl1.westus2.cloudapp.azure.com, ameplcl1.westus3.cloudapp.azure.com, localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, kubernetes.kube-system, kubernetes.kube-system.svc, kubernetes.kube-system.svc.cluster.local, not ameplcl1.polandcentral.cloudapp.azure.com

**Comment by bridgetkromhout** [comment]
Hi, @JohonsonChan - AKS Engine is deprecated and is not getting frequent releases. We do anticipate one final release at EOL for Kubernetes 1.24 in the coming weeks, and the build process for the VHDs will pick up any active regions at that time. Thanks for reaching out.

For anyone looking at this issue later, AKS Engine will support new regions up until its last release, at which point no more VHDs will be created. It's recommended to move to AKS for all managed-cluster needs and to CAPZ for self-managed needs. Thanks!
