### ISSUE TITLE
AKS Engine is unable to find the node

### ISSUE THREAD

**Issue by kaman05010** [Azure/aks-engine#5121]
**Describe the bug**
AKS Engine is unable to find the node with below error:

Below is the error on aks engine:

  Warning  FailedToCreateRoute  3m27s (x2858 over 8h)  route_controller  (combined from similar events): Could not create route 33211c55-5446-4b0c-b43f-f3cca5f9546d 10.244.8.0/24 for node k8s-node-xxx-vmssxxxxx after 364.619109ms: instance not found
**Expected behavior**

We are able to list the instances from azure cli and powershell:

Get-AzVmssVM -ResourceGroupName xxVMScaleSetName k8s-node-xx-vmss -InstanceId xx
ResourceGroupName                         : xx
InstanceId                                : 233
Sku                                       :
  Name                                    : Standard_D8s_v3
  Tier                                    : Standard
LatestModelApplied                        : True
VmId                                      : d9e5e2bc-b4ca-4ae9-b269-02aa1e2ec819
HardwareProfile                           :
  VmSize                                  : Standard_D8s_v3
StorageProfile                            :
  ImageReference                          :
    Publisher                             : microsoft-aks
    Offer                                 : aks
    Sku                                   : aks-engine-ubuntu-2004-202301
    Version                               : 2023.03.06
    ExactVersion                          : 2023.03.06

  LinuxConfiguration                      :
    DisablePasswordAuthentication         : True
    Ssh                                   :
      
    ProvisionVMAgent                      : True
  AllowExtensionOperations                : True
  RequireGuestProvisionSignal             : True
NetworkProfile                            :
  NetworkInterfaces[0]                    :
    Id                                    : /subscriptions/xx/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Compute/virtu
alMachineScaleSets/k8s-node-xx-vmss/virtualMachines/233/networkInterfaces/k8s-node-xx
NetworkProfileConfiguration               :
  NetworkInterfaceConfigurations[0]       :
    Name                                  : k8s-node-11577350-vmss
    Primary                               : True
    EnableAcceleratedNetworking           : True
    DisableTcpStateTracking               : False
    NetworkSecurityGroup                  :
      Id                                  :
/subscriptions/xx/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Network/networkSecurityGroups/xx
    DnsSettings                           :
    IpConfigurations[0]                   :
      Name                                : ipconfig1
      Subnet                              :
        Id                                : /subscriptions/xx/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Network/virtu
alNetworks/axx/subnets/xxx
      Primary                             : True
      PrivateIPAddressVersion             : IPv4
      LoadBalancerBackendAddressPools[0]  :
        Id                                : /subscriptions/2f495c46-73b1-463c-ae90-dae28e3880ef/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Network/loadB
alancers/k8seastus2euapdc/backendAddressPools/k8seastus2euapdc
      LoadBalancerBackendAddressPools[1]  :
        Id                                : /subscriptions/xx/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Network/loadB
alancers/xx/backendAddressPools/xx
    EnableIPForwarding                    : True
DiagnosticsProfile                        :
  BootDiagnostics                         :
    Enabled                               : True
    StorageUri                            : https://kvlsaeastus2euap.blob.core.windows.net/
ProvisioningState                         : Succeeded
ModelDefinitionApplied                    : VirtualMachineScaleSet
Resources[0]                              :
  Location                                : eastus2euap
  Id                                      : /subscriptions/2f495c46-73b1-463c-ae90-dae28e3880ef/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Compute/virtu
alMachines/k8s-node-xx-vmss_xx/extensions/vmssCSE
  Name                                    : vmssCSE
  Type                                    : Microsoft.Compute/virtualMachines/extensions
  Publisher                               : Microsoft.Azure.Extensions
  VirtualMachineExtensionType             : CustomScript
  TypeHandlerVersion                      : 2.0
  AutoUpgradeMinorVersion                 : True
  Settings                                : {}
  ProvisioningState                       : Succeeded
Resources[1]                              :
  Location                                : eastus2euap
  Id                                      : /subscriptions/xx/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Compute/virtu
alMachines/k8s-node-xx-vmss_xx/extensions/k8s-node-1xx-vmss-computeAksLinuxBilling
  Name                                    : k8s-node-xx-vmss-computeAksLinuxBilling
  Type                                    : Microsoft.Compute/virtualMachines/extensions
  Publisher                               : Microsoft.AKS
  VirtualMachineExtensionType             : Compute.AKS-Engine.Linux.Billing
  TypeHandlerVersion                      : 1.0
  AutoUpgradeMinorVersion                 : True
  Settings                                : {}
  ProvisioningState                       : Succeeded
Id                                        : /subscriptions/xx/resourceGroups/anf.dc.mgmt.eastus2euap.rg/providers/Microsoft.Compute/virtu
alMachineScaleSets/k8s-node-xx-vmss/virtualMachines/xx
Name                                      : k8s-node--vmss_xx
Type                                      : Microsoft.Compute/virtualMachineScaleSets/virtualMachines
Location                                  : eastus2euap
Tags                                      : {"aksEngineVersion":"v0.77.0","creationSource":"aksengine-k8s-node-xx-vmss","orchestrator":"Kubernetes:1.22.17","poolName
":"node","resourceNameSuffix":"11577350","platformsettings.host_environment.service.platform_optedin_for_rootcerts":"true","SkipASMAzSecPack":"True"}

**AKS Engine version**
0.77
**Kubernetes version**
1.22.17
**Additional context**
We need to know if this is an issue with aks engine or VMSS nodes

**Comment by bridgetkromhout** [comment]
Hi, @kaman05010 - AKS Engine is EOL and has no support available. I'll follow up in email.
