### ISSUE TITLE
How to change the kubernetesConfig in an existing cluster

### ISSUE THREAD

**Issue by palmerabollo** [Azure/aks-engine#528]
**Is this a request for help?**:
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

**What version of aks-engine?**:
v0.30.1
 
**Kubernetes version**:
1.10

**What happened**:
Upgrading an existing cluster with aks-engine does not update the kubernetes configuration (e.g. kubelet config, apiserver config, `enableRbac` or `networkPolicy`). Is there any way to do it without destroying and recreating the cluster?

**What you expected to happen**:
I expected the cluster configuration to be updated.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a cluster. Change the `kubernetesConfig` in the cluster description, adding, for example:

```
      "kubernetesConfig": {
        "kubeletConfig": {
          "--eviction-hard": "memory.available<500Mi"
        },
        "controllerManagerConfig": {
          "--feature-gates": "TaintBasedEvictions=true,ExpandPersistentVolumes=true"
        }
      }
```

and redeploy the cluster. Changes won't be applied.

**Comment by jackfrancis** [comment]
Hi @palmerabollo, here are some steps that *may* work:

1. Deploy a cluster and retain the `apimodel.json` in the relevant `_output/` directory
2. Modify the `apimodel.json` file to reflect new configuration
3. Run `aks-engine upgrade` against the cluster and refer to the updated `apimodel.json`.

The way upgrade works is it re-generates ARM templates from the `apimodel.json` input specification. The reason this may or may not work is that it depends on what configuration vector in `apimodel.json` is changed. If the change results in an ARM template that is not reconcilable as a follow-up deployment on top of the pre-existing ARM template deployment (what happened in step 1 above), then you will get a deployment failure (for example, ARM won't let you change the "accelerated networking enabled/disabled" configuration of a VM, it's something that is only configurable at creation time).

Hope that makes sense. Let me know if this guidance gets you anywhere closer to a usable workflow.

**Comment by palmerabollo** [comment]
Thanks, @jackfrancis. That's what we do to modify some cluster settings (e.g. create new agent pools, change node types). However, we find it too limited because most changes result in a new `customData` in the ARM template that is one of those parameters you can't change.

Some additional use cases we have:
- Replace an agentPool with a new one that is vmss-based.
- Change the network plugin to be able to use K8S network policies.

_I'll try to update the list on Monday._

**Comment by jackfrancis** [comment]
Thanks for the feedback. Both of the above are out-of-scope for the current `aks-engine upgrade` implementation, as you've observed; the current `upgrade` implementation is basically brute-force, re-pave everything.

We are working in the background to integrate more sustainable cluster lifecycle tooling (e.g., `cluster-api`) as a 1st class bit of functionality on aks-engine-created clusters. Nothing concrete to share, other than "we are aware that AKS Engine does not provide resilient Day 2 cluster lifecycle functionality right now". Thanks for your help in clarifying what the real world looks like, keep the pressure on us. :)

**Comment by arodriguezdlc** [comment]
This `automation` have considered as Done an issue that should stay in To do...

**Comment by palmerabollo** [comment]
Yes, agree, I'd reopen the issue.

**Comment by popsikle** [comment]
yes.... please re-open this.

**Comment by LennartOlsen** [comment]
Is there anything new on this? A timeline maybe?

**Comment by jackfrancis** [comment]
I believe there are current ways to evolve a `kubernetesConfig` in a pre-existing cluster, using either scale or upgrade. We should document that.
