### ISSUE TITLE
AgentPoolProfile count needs to be in the range [1,100]

### ISSUE THREAD

**Issue by palmerabollo** [Azure/aks-engine#530]
**Is this a request for help?**:
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Request

**What version of aks-engine?**:
v0.31.1

**Kubernetes version**:
1.10

**What happened**:
Creating node pools with more than 100 nodes raises the error:

`AgentPoolProfile count needs to be in the range [1,100]`

**What you expected to happen**:
aks-engine should be able to create bigger node pools, only restricted by the limitations of the underlying network (for example, number of IP addresses in the VPC or things like that). 

**How to reproduce it** (as minimally and precisely as possible):

Deploy a cluster with the following agentPoolProfile:
```
    {
        "name": "test",
        "count": 0,
        "vmSize": "Standard_D4s_v3",
        "availabilityProfile": "VirtualMachineScaleSets"
    },
```

**Comment by palmerabollo** [comment]
Setting `singlePlacementGroup` to `false` allows for 1000 nodes per pool.
However, It's still [1,1000] instead of [**0**,1000]

**Comment by allantargino** [comment]
I guess this is already fixed: https://github.com/Azure/aks-engine/search?q=MinAgentCount&unscoped_q=MinAgentCount
At least in every ocurrence in every api version this seems to be equals 1 (instead of 0)

**Comment by palmerabollo** [comment]
Hi @allantargino. I think that's the issue. `MinAgentCount` should be allowed to be zero.

**Comment by palmerabollo** [comment]
not stale
