### ISSUE TITLE
Enable nvidia drivers w/ moby

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#534]
nvidia drivers currently have a hard dependency on docker-engine. Let's get this removed so they can run on moby-backed nodes.

**Comment by andyzhangx** [comment]
Thanks for raising this up, as I know, we could not NC serials node by AKS due to this bug on Azure China.
Global Azure use a built-in image which already has the nvidia-driver-container, while that image could not be used on Azure China now.
