### ISSUE TITLE
Enable cluster configuration with no master public IP and no master LB

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#537]
```
az network lb delete -g $GNAME -n k8s-master-lb-${CID}
 
az network public-ip delete -g ${GNAME} -n k8s-master-ip-${GNAME}-${CID}
```

@navicore FYI

**Comment by jackfrancis** [comment]
@navicore it does seem that the current "private cluster" cluster configuration scenario is most of the way there in terms of your requirements. Will you be able to build a small one and report back any Azure IaaS configuration that doesn't meet your req's?

Here are brief docs:

https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#feat-private-cluster

I think there's a decent chance we can adapt this feature to match what you need, in which case it'd be a win for everyone as a single configuration entry point is most likely easier for most users.

Thanks!

**Comment by navicore** [comment]
@jackfrancis I will run through a test and report back.  thx!

**Comment by navicore** [comment]
I've created a "private cluster" and my bastion/vnet setup works with the internal lb - all kubectl commands seem to work.

However, this test deployment has broken DNS in that images are downloaded from registries fine but the pods themselves can't resolved any DNS names.   I will test further to see if this is related to the private network property or something related to the jump to the current aks-engine or my crossing hands... more info shortly.

**Comment by jackfrancis** [comment]
@navicore Just wanted to check in to see if you're still blocked
