### ISSUE TITLE
Node labels and taints are reset after node upgrade

### ISSUE THREAD

**Issue by jluk** [Azure/aks-engine#549]
**Kubernetes version**:
1.10.3

**What happened**:
User reports labels are reset after a node upgrade occurred on AKS. Active email discussion between Jorge, Jack, Justin, and Anders on this.

**What you expected to happen**:
Nodes retain labels through a node upgrade so pods can be handled appropriately before/after.

**How to reproduce it** (as minimally and precisely as possible):
1. Assign label to node
2. Upgrade node
3. Verify labels on upgraded node

**Anything else we need to know**:
Core AKS issue reported here: https://github.com/Azure/AKS/issues/468

**Comment by jluk** [comment]
@palma21 FYI per teams chat

**Comment by CecileRobertMichon** [comment]
fixed in #570
