### ISSUE TITLE
Enable user-configurable vm names

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#56]
Details // TODO

Some customers wish to be able to influence the names of their node vms. Scale/upgrade would have to be taken into account in order to deliver this.

**Comment by sylr** [comment]
I've already proposed a patch for this: https://github.com/Azure/acs-engine/pull/2485

The lastest version of the patch on top of patch-release-v0.25.3 : https://github.com/sylr/acs-engine/commit/c304bdefbbf648cedd30bf26b66b2829c8d45209
