### ISSUE TITLE
docs: Missing notes about "clusterSubnet" in custom-vnet.md

### ISSUE THREAD

**Issue by song-jiang** [Azure/aks-engine#561]
**Is this a request for help?**:
 no
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
 issue
---

**What version of aks-engine?**:
 latest
---

**Kubernetes version**:
1.12.5

**What happened**:
Following tutorial custom-vnet.md to install kubernetes cluster, subnet ip ranges (10.100.0.0/24, 10.200.0.0/24). kube-proxy and kube-controller-manager still use default clusterCIDR 10.124.0.0/12. 
```
kube-controller-manager
    - --cluster-cidr=10.240.0.0/12

kube-proxy
    --cluster-cidr=10.240.0.0/12
```
This causes packet from pod to service ip get masqueraded and break network policy. 
Adding `clusterSubnet` to kubernetesConfig fixed the issue.

**What you expected to happen**:
A note in tutorial about setting up clusterCIDR. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by ams0** [comment]
I looked into this as efforts to reduce the number of bugs. What I found:

- for Azure CNI, `--cluster-cidr` is ignored and pods get IP's from the agent subnet; they are able to talk to the outside word, be reachable *from* the service Loadbalancer IPs and access ClusterIP's Service IPs.

- for Kubenet,  `--cluster-cidr` is respected and pods get IP's from that range. I think this can be closed, as I just filed #1282 .
