### ISSUE TITLE
package on gofish is not up to date

### ISSUE THREAD

**Issue by superyyrrzz** [Azure/aks-engine#576]
v0.31.1 on [GitHub](https://github.com/Azure/aks-engine/releases/tag/v0.31.1)
v0.29.1 on GoFish:
```
PS D:\K8S> gofish upgrade aks-engine
==> Rigs updated!
NAME
github.com\fishworks\fish-food

🐠  rigs updated in 6.0111485s
🐠  Everything up to date!
PS D:\K8S> aks-engine version
Version: v0.29.1
GitCommit: b35549b
GitTreeState: clean
```

**Comment by superyyrrzz** [comment]
Today I find 0.33.5 on GitHub and 0.33.4 on gofish. Maybe it need to automate the process to update gofish.

**Comment by mboersma** [comment]
Nice catch @superyyrrzz—looks like we failed to make our package manager PRs with the last release. I'll go backfill those now.

We do have a work item to automate all this: see #653. I'll try to address that as soon as time permits.

**Comment by mboersma** [comment]
Better late than never:
https://github.com/fishworks/fish-food/pull/156
https://github.com/Azure/homebrew-aks-engine/pull/10
