### ISSUE TITLE
Document release procedure

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#577]
**Is this a request for help?**:
NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

---

We need a simple, tested doc on how to release a new version of aks-engine. It's not that complicated but there are several steps that are easy to forget, including:

- make sure to `git clean -fdx` before `make dist` or the `aks-engine version` command shows the binaries as "dirty"
- update the `gofish` index with a PR to fishworks/fish-food
- update the `brew` index with a PR to Azure/homebrew-aks-engine

**Comment by CecileRobertMichon** [comment]
+ dockerhub if we want to maintain that (used to be https://hub.docker.com/r/microsoft/acs-engine/)

**Comment by palma21** [comment]
Added to the milestoned @mboersma would you take a first stab at it?

(Agree on MCR)
