### ISSUE TITLE
containers failing to resolve public dns

### ISSUE THREAD

**Issue by idanysela** [Azure/aks-engine#593]
**Is this a request for help?**:
Yes
---
ISSUE

---

 aks-engine version: v0.31.1

---

**Kubernetes version**: 1.13.3.

**What happened**: We are running a single container image on a cluster with low priority agents and trying to scale up, when we do we are getting a lot of failed containers – they are failing to resolve a public dns address
we did notice that it seems to be related to the networking containers(kube-proxy, azure-ip-masq-agent) which fail to load (or they might be affected as well, we can see other infra containers taking a very long time to load such as blobfuse and keyvault-flexvolume) before the actual workloads plus the dns service which is deployed by default with only one replica.
When we scaled the cluster manually and waited for the networking components to load before scaling the containers and of course raise the replica count for the dns service we did see them all run.
However that would still mean that autoscaling is not usable (and is not practical in relaunching low priority vms) 

**What you expected to happen**: after the cluster autoscaler scales up the nodes the pods are all scheduled and running without issues

**How to reproduce it** (as minimally and precisely as possible):

- use aks-engine to generate a cluster with agent pool on low  priority vms with the autoscaler addon
- add a deployment for an image that will test a public url repeatedly and fail when the url is not available
- scale the deployment to 1000 replicas
- watch the pods status

**Comment by brendandburns** [comment]
@idanysela have you scaled up your core-dns Pod? My first guess is that the core-dns container is overloaded. Try your experiment and then observe CPU usage for the core-dns pod.

Thanks!

**Comment by idanysela** [comment]
@brendandburns as i stated before when we scaled the nodes and allowed for time for networking components to load we also scaled the core-dns (i referred to it as the "dns service") and that did work but only when we allowed the time for the networking to start responding on the new nodes, the issue seems to be with the long init time for containers network access on new nodes even basic system services are affected just appearing as "pending" not failed (might be built with better requirement specifications)

**Comment by brendandburns** [comment]
You may also need to scale up the apiserver and controller manager. I would look at the monitoring for the system components when you scale up the number of Pods.

--brendan

**Comment by nleib** [comment]
@brendalee @idanysela when using aks-engine the apiserver and controller manager are not deployed as pods in the system, here are all the deployemnts in the cluster:
```bash
cluster-autoscaler
coredns
kubernetes-dashboard
metrics-server
tiller-deploy
```

what is the correct way to scale up apiserver and controller manager in this case?

**Comment by brendandburns** [comment]
as far as I know (and it's been a while since I poked at an AKS-Engine cluster) they're deployed as static pods via YAML files.

SSH onto the master node and look at `/etc/kubernetes/manifests/*`

**Comment by idanysela** [comment]
according to the documentation they are running on all master nodes in aks-engine:
["the kube-apiserver daemon running on all master nodes"](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#apiserverconfig)
["the cloud-controller-manager daemon running on all master nodes"](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#cloudcontrollermanagerconfig)

and the tests we conducted were with 3 master nodes
