### ISSUE TITLE
Make aks-engine scale command NOT depend on azuredeploy.json in _output folder

### ISSUE THREAD

**Issue by sukhong** [Azure/aks-engine#595]
**Is this a request for help?**:

--- No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

--- FEATURE REQUEST

**What version of aks-engine?**:

--- v0.31.1

**Kubernetes version**: 1.13

**What happened**: aks-engine scale command apparently has a dependency on azuredeploy.json.

**What you expected to happen**: I'd like to see aks-engine scale command NOT depend on the existence of azuredeploy.json file in _output folder any more. I looked at the code briefly, and it seems like the scale command only needs "nameSuffix" value from azuredeploy.json. Can't we compute this value from apimodel.json instead?

**How to reproduce it** (as minimally and precisely as possible): N/A

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Related top https://github.com/Azure/aks-engine/issues/361

You're correct, this should be possible. We have plans to do it for upgrade. It should equivalent for scale. If you're interested in contributing and working on a PR to do this let me know and I can help/provide guidance/review your PR!
