### ISSUE TITLE
What is the difference between aks-engine scale vs. manually increasing vmss instance counts?

### ISSUE THREAD

**Issue by sukhong** [Azure/aks-engine#596]
**Is this a request for help?**:

--- No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

--- FEATURE REQUEST

**What version of aks-engine?**:

--- v0.31.1

**Kubernetes version**: v1.13.0

**What happened**: Instead of using aks-engine scale command to scale up nodes count, I tried to manually increase vmss instance counts in the portal. It seems like to have an exact same effect (i.e. kubectl get nodes correctly show increased nodes as READY). Is there any difference between these two approaches?

**Comment by CecileRobertMichon** [comment]
Using `aks-engine scale` will ensure that your apimodel is up-to-date with your cluster resources state which will allow future `aks-engine` operations to be successful. Other than that, no functional differences AFAIK.
