### ISSUE TITLE
Incorrect output directory while using aks-engine deploy with --dns-prefix specified

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#597]
**Is this a request for help?**:
NO
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.31.1
---

**Kubernetes version**:
1.13.x

**What happened**:
While using aks-engine deploy with --dns-prefix specified, files are generated to _output instead of  _output/DNSPrefix

**What you expected to happen**:
Files are generated to  _output/DNSPrefix while using aks-engine deploy with --dns-prefix specified

**How to reproduce it** (as minimally and precisely as possible):
 Deploy cluster with command aks-engine deploy --dns-prefix xxx, check the generated output folder.

**Anything else we need to know**:
I checked the code in deploy.go, dc.outputDirectory is set before  dc.containerService.Properties.MasterProfile.DNSPrefix gets correct value.
Line 192
`dc.outputDirectory = path.Join("_output", dc.containerService.Properties.MasterProfile.DNSPrefix)`
Line 261
`dc.containerService.Properties.MasterProfile.DNSPrefix = dc.dnsPrefix`

**Comment by alexeldeib** [comment]
@CecileRobertMichon I attempted a fix to this in https://github.com/Azure/aks-engine/pull/880. I am still looking at how the tests work to update them to catch this case.

**Comment by CecileRobertMichon** [comment]
thanks @alexeldeib!
