### ISSUE TITLE
Installing flannel on mixed (Win + Lin) cluster

### ISSUE THREAD

**Issue by brusMX** [Azure/aks-engine#598]
**Is this a request for help?**:

NO

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of aks-engine?**:

Version: canary
GitCommit: 124379b0
GitTreeState: clean

**Kubernetes version**:
1.13.3

**What happened**:
- Deployed Windows - Linux cluster
- Deployed [flannel](https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml)
- Pods starts and then I get the following error log :

```
Error registering network: failed to acquire lease: node "k8s-master-19932461-0" pod cidr not assigned
```

**What you expected to happen**:

Deploy flannel.

**How to reproduce it** (as minimally and precisely as possible):
Follow steps above.

**Anything else we need to know**:
This is a different way to enable cross OS pods communication.

**Comment by brusMX** [comment]
Found the problem.

This [link](https://github.com/coreos/flannel/blob/fd8c28917f338a30b27534512292cd5037696634/Documentation/troubleshooting.md#kubernetes-specific) helps to solve it.
Flannel is usually configured on clusters that are deployed with kubeadm with a flag `pod-network-cidr`: 

```bash
kubeadm init --pod-network-cidr=10.244.0.0/12
```

Now, we were able to fix the problem by patching all the nodes:

```
kubectl patch node <NODE_NAME> -p '{"spec":{"podCIDR":"<SUBNET>"}}'
```
What would be the aks-engine equivalent to set this flag?

**Comment by serbrech** [comment]
Thanks @brusMX, it might be a good practice for us to match the kubeadm behaviour and flag nods with the podCIDR.

**Comment by DavidHache** [comment]
AKS allows for the modification of the podCidr and serviceCidr.
I was thinking of adding something like this to match what AKS does.


    "masterProfile": {
      "count": 3,
      "dnsPrefix": "",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": "",
      "vnetCidr": "",
      "podCidr": "",
      "serviceCidr": "",
      "dnsServiceIP": "",
      "dockerBridgeCidr": "172.17.0.1/32",
      "availabilityProfile": "AvailabilitySet"
    },
