### ISSUE TITLE
Intermittent exit 4 failures on N series

### ISSUE THREAD

**Issue by AndKram** [Azure/aks-engine#608]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
aks.v0.29.1-windoes-amd64
---

**Kubernetes version**:

On Azure with api-model below

**What happened**:

Fails with provisioning error (in Azure portal under Resource Group):

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'cse-agent-4'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=4\\n[stdout]\\n\\n[stderr]\\nConnection to k8s.gcr.io 443 port [tcp/https] succeeded!\\nConnection to gcr.io 443 port [tcp/https] succeeded!\\nConnection to docker.io 443 port [tcp/https] succeeded!\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

Re-running usually resolves the problem so it appears to be some temporary issue.

**What you expected to happen**:

K8 cluster to be created each time.

**How to reproduce it** (as minimally and precisely as possible):
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "kubernetesConfig": {
          "gcHighThreshold" : 60,
          "gcLowThreshold" : 40
        }
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "k8s-cluster",
        "vmSize": "Standard_D2_v2"
      },
      "agentPoolProfiles": [
        {
          "name": "linuxpool1",
          "count": 1,
          "vmSize": "Standard_NC6",
          "availabilityProfile": "AvailabilitySet",
          "OSDiskSizeGB": 100
        },
        {
          "name": "linuxpool2",
          "count": 4,
          "vmSize": "Standard_D8s_v3",
          "availabilityProfile": "AvailabilitySet",
          "storageProfile": "ManagedDisks",
          "OSDiskSizeGB": 100
        }
      ],
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "ssh-rsa " [DELETED]
            }
          ]
        }
      }
    }
}

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
@AndKram does the VMExtensionError always happen on VMs in 
linuxpool2? You can see the detail of which VM extensions failed in the deployment tab of the portal. See https://github.com/Azure/aks-engine/blob/master/docs/howto/troubleshooting.md#vmextensionprovisioningerror-or-vmextensionprovisioningtimeout for general troubleshooting help with this type of error. I suspect this might be due to the VM size you're using (`
Standard_D8s_v3`). FWIW we are not observing similar intermittent failures in our tests.

**Comment by AndKram** [comment]
I'll check the next time it happens but I suspect it's the NC6 instances.

**Comment by CecileRobertMichon** [comment]
@AndKram looks like your issue is related to https://github.com/Azure/aks-engine/issues/455
