### ISSUE TITLE
AKS engine autoscaler crashloopbackoff

### ISSUE THREAD

**Issue by henrikrox** [Azure/aks-engine#609]
**Is this a request for help?**:

yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

issue

**What version of aks-engine?**:
v0.31.1

E0228 12:01:48.083147       1 azure_scale_set.go:199] VirtualMachineScaleSetVMsClient.List failed for k8s-windowspool2-16790049-vmss: compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'k8s-windowspool2-16790049-vmss' not found."
F0228 12:01:48.123291       1 azure_cloud_provider.go:139] Failed to create Azure Manager: compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'k8s-windowspool2-16790049-vmss' not found."
E0228 12:01:48.146252       1 azure_scale_set.go:199] VirtualMachineScaleSetVMsClient.List failed for k8s-windowspool2-16790049-vmss: compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'k8s-windowspool2-16790049-vmss' not found."

I tried exporting the deployment and changing the  name to 1679k8s00 and deleted the deployment and createda  new one, after a restarts it shows as running then goes into error, then crashloopbackoff.

**Kubernetes version**:
1.13.1

**What happened**:
Did a new aks engine deploy, says crashloopbackoff

**What you expected to happen**:
cluster-autsocaler working as it has in the past.

**How to reproduce it** (as minimally and precisely as possible):
use aks engine 0,31.1 set config with addon cluster autoscaler

**Anything nanelse we need to know**:

**Comment by CecileRobertMichon** [comment]
@henrikrox can you please share your apimodel (after removing secrets) to allow us to try and repro?
