### ISSUE TITLE
Error dialing backend when attemtping to run kubectl exec -it -- /bin/bash

### ISSUE THREAD

**Issue by joclemen** [Azure/aks-engine#616]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of aks-engine?**: acs-engine v0.23.6

---

**Kubernetes version**: 1.11.5

**What happened**: Attempting to run "kubectl exec -it -n "namespace" "pod name" -- /bin/bash"
Receiving this error: “Error from server: error dialing backend: dial tcp: lookup <node name> on <private ip>:53: server misbehaving”

**What you expected to happen**: A bash shell on the specified pod.

**How to reproduce it** (as minimally and precisely as possible): N/a

**Anything else we need to know**:
We have verified resolv.conf is configured to correctly resolv dns requests.

**Comment by jackfrancis** [comment]
@joclemen is this intermittent or persistent?

Anything interesting in `kube-dns` logs?

**Comment by joclemen** [comment]
Hi @jackfrancis ,

It is a persistent issue that happens across all the pods on the clusters.

When trying to retrieve the logs for kubedns, dnsmasq, and sidecar I get this error,

Error from server: Get https://<agent name and port>/containerLogs/kube-system/kube-dns-8446b8bd4c-6pwdm/kubedns: dial tcp: look
up <agent name> on <IP address>: server misbehaving

**Comment by jackfrancis** [comment]
What do you get doing a comprable debugging exercise against your kube-dns pod?

```
$ kubectl exec -it -n kube-system kube-dns-554b6f9d86-v8j9q -c kubedns -- /bin/sh
Defaulting container name to kubedns.
Use 'kubectl describe pod/kube-dns-554b6f9d86-v8j9q -n kube-system' to see all of the containers in this pod.
/ # cat /etc/resolv.conf
nameserver 168.63.129.16
search zvtulz2l1znupfe1tz3t1km1ee.bx.internal.cloudapp.net
/ # nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      google.com
Address 1: 172.217.7.174 iad30s09-in-f174.1e100.net
Address 2: 2607:f8b0:4004:800::200e iad30s09-in-x0e.1e100.net
/ # echo $?
0
/ # nslookup bing.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      bing.com
Address 1: 204.79.197.200 a-0001.a-msedge.net
Address 2: 13.107.21.200
/ # echo $?
0
/ #
```

(`kube-dns-554b6f9d86-v8j9q` is the name of the pod on my sample cluster)

**Comment by joclemen** [comment]
Hi @jackfrancis ,

When attempting the commands on the kube-dns pod I receive the following similar error.

Error from server: error dialing backend: dial tcp: lookup <agentname> on <IP address>:53: server misbehaving

Thanks for the suggestion. Any additional troubleshooting ideas are greatly appreciated.
