### ISSUE TITLE
Import of certificate fails in AKS Cluster for nanoserver

### ISSUE THREAD

**Issue by bospoort** [Azure/aks-engine#617]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**What version of aks-engine?**:

---

**Kubernetes version**:
1.13

**What happened**:
Fail to import certificate in ASP.NET Core nanoserver 1809. When the container is running stand-alone, the import of the certificate succeeds. 

**What you expected to happen**:
Import of certificate succeeds

**How to reproduce it** (as minimally and precisely as possible):
Please ping me. I have a repro I can share. 

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
@jsturtevant FYI

**Comment by jsturtevant** [comment]
Could you share a GitHub repository that has the certificate import and a dockerfile?  

Have you followed the instructions for https on the [dotnetcore docker repo](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md)?
