### ISSUE TITLE
Multiple SSH ports 22,2201,2202 open  for Master VMs.

### ISSUE THREAD

**Issue by ashishkulk** [Azure/aks-engine#618]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue/Question
---

**What version of aks-engine?**:
acs-engine 0.18.9
---

**Kubernetes version**:
1.10.5
---

**What happened**:
Our team came to know that there are multiple ssh ports namely 22, 2201,2202. Is there any particular reason for it?

**What you expected to happen**:
Only one SSH port should be open.

**How to reproduce it** (as minimally and precisely as possible):
Try ssh on port 22  2201 2202
ssh -i <ssh-key-file> username@production-server-name/ip -p <port-number-22,2201,2202>

**Comment by jackfrancis** [comment]
I can't repro:



```
$ ssh -A -i _output/kubernetes-eastus-88389-ssh -p 2201 azureuser@kubernetes-eastus-88389.eastus.cloudapp.azure.com
ssh: connect to host kubernetes-eastus-88389.eastus.cloudapp.azure.com port 2201: Operation timed out
$ ssh -A -i _output/kubernetes-eastus-88389-ssh -p 2202 azureuser@kubernetes-eastus-88389.eastus.cloudapp.azure.com
ssh: connect to host kubernetes-eastus-88389.eastus.cloudapp.azure.com port 2202: Operation timed out
```

(this is against a cluster built from master)

@palma21 have you ever heard of this?

@ashishkulk where are you connecting from? And are you connecting from to the public IP via ELB?

**Comment by CecileRobertMichon** [comment]
@tariq1890 added https://github.com/Azure/aks-engine/pull/324/files#diff-66f514bfef9af8cacaea5f53f6cc5094R17 in his refactor PR which makes me think it's intentional...

**Comment by thatInfrastructureGuy** [comment]
@jackfrancis I am connecting via public ELB. Just a FYI; we were using acs-engine 0.18.9 when clusters were built.
