### ISSUE TITLE
pod-security-policy.yaml is being parsed as a pod

### ISSUE THREAD

**Issue by danmassie** [Azure/aks-engine#633]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.31.1
---

**Kubernetes version**:
1.13.3

**What happened**:
I created a cluster with rbac and pod security policies enabled then inspected the kubelet journal logs.

kubelet logs the following repeatedly:

```
Feb 28 22:05:20 master-27738982-0 kubelet[18862]: E0228 22:05:20.288964   18862 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/pod-security-policy.yaml": /etc/kubernetes/manifests/pod-security-policy.yaml: couldn't parse as pod(invalid pod: &policy.PodSecurityPolicy{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"privileged", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"seccomp.security.alpha.kubernetes.io/allowedProfileNames":"*"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:policy.PodSecurityPolicySpec{Privileged:true, DefaultAddCapabilities:[]core.Capability(nil), RequiredDropCapabilities:[]core.Capability(nil), AllowedCapabilities:[]core.Capability{"*"}, Volumes:[]policy.FSType{"*"}, HostNetwork:true, HostPorts:[]policy.HostPortRange{policy.HostPortRange{Min:0, Max:65535}}, HostPID:true, HostIPC:true, SELinux:policy.SELinuxStrategyOptions{Rule:"RunAsAny", SELinuxOptions:(*core.SELinuxOptions)(nil)}, RunAsUser:policy.RunAsUserStrategyOptions{Rule:"RunAsAny", Ranges:[]policy.IDRange(nil)}, RunAsGroup:(*policy.RunAsGroupStrategyOptions)(nil), SupplementalGroups:policy.SupplementalGroupsStrategyOptions{Rule:"RunAsAny", Ranges:[]policy.IDRange(nil)}, FSGroup:policy.FSGroupStrategyOptions{Rule:"RunAsAny", Ranges:[]policy.IDRange(nil)}, ReadOnlyRootFilesystem:false, DefaultAllowPrivilegeEscalation:(*bool)(nil), AllowPrivilegeEscalation:true, AllowedHostPaths:[]policy.AllowedHostPath(nil), AllowedFlexVolumes:[]policy.AllowedFlexVolume(nil), AllowedUnsafeSysctls:[]string(nil), ForbiddenSysctls:[]string(nil), AllowedProcMountTypes:[]core.ProcMountType(nil)}}), please check config file.
```

**What you expected to happen**:
pod security policies provided by aks-engine are parsed and processed without errors

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster with pod security policies and rbac enabled.

**Anything else we need to know**:
This is logged every 20 seconds.

**Comment by allantargino** [comment]
I am investigating this behavior, thanks.

**Comment by ams0** [comment]
I dug a bit a found out that that directory (`/etc/kubernetes/manifests`) is only [for static pod definitions](https://kubernetes.io/docs/tasks/administer-cluster/static-pod/) and nothing else. The file `pod-security-policy.yaml` contains PodSecurityPolicy, ClusterRoles and ClusterRoleBindings objects thus invalid.

**Comment by allantargino** [comment]
Detailed reproduce steps:
1. Create a cluster with both RBAC and PodSecurityPolicy enabled, with the following definition:
```json
[...]
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.13.4",
      "kubernetesConfig":{
        "enablePodSecurityPolicy": true,
        "enableRbac": true
      }
    }
[...]
```
2. SSH into the master node
3. Use the following to get the logs:
```shell
sudo journalctl -u kubelet | tail -n 100 | grep /etc/kubernetes/manifests/pod-security-policy.yaml
```

**Comment by allantargino** [comment]
Reason: @ams0 spot on.
From https://github.com/Azure/acs-engine/pull/2048 we are creating the PSP definition inside `/etc/kubernetes/manifests/`.
This is the exactly path configured for static pod files using the kubelet flag `--pod-manifest-path`.
Also, this is logged every 20s due to the kubelet flag `--file-check-frequency` (by default its value is `20s`)

Even with the kubelet not creating them, the PSP rules are created due this bash function: https://github.com/Azure/acs-engine/pull/2048/files#diff-f2f5404d19a8ead71fce9bc62331f682R614
