### ISSUE TITLE
Expose etcd metrics

### ISSUE THREAD

**Issue by danmassie** [Azure/aks-engine#637]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature request
---

**What version of aks-engine?**:
0.31.1
---

**Kubernetes version**:
1.13.3

**What happened**:
Metrics are not exposed for etcd on the masters on port 2379 at /metrics.

**What you expected to happen**:
etcd metrics to be enabled by default (https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/monitoring.md#metrics-endpoint) and exposed in the cluster for prometheus to scrape.

**How to reproduce it** (as minimally and precisely as possible):

1. Create a cluster
2. ssh in to a master
3. curl -v http://localhost:2379/metrics

**Anything else we need to know**:

**Comment by vharsh** [comment]
I'd like to help with this one. I currently tired hitting the etcd metrics API and I got a binary response.

**Comment by AtebMT** [comment]
Did you confirm this as a certificate issue? I'm having the same problem.

**Comment by omerlh** [comment]
Any update about this issue? I was able to collect only etcd metrics that are exposed via the API server
