### ISSUE TITLE
Build new VHDs w/ kernel 4.15.0-1039-azure

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#648]
Expectation is that kernel https://packages.ubuntu.com/xenial/kernel/linux-image-4.15.0-1039-azure is provided on 16.04-LTS:latest

**Comment by CecileRobertMichon** [comment]
I built a cluster yesterday with ubuntu latest, it was using `4.15.0-1040-azure`

**Comment by jackfrancis** [comment]
Great, that qualifies. Next VHD build and code update to reference it closes this issue. :)
