### ISSUE TITLE
Chocolatey install

### ISSUE THREAD

**Issue by kyschouv** [Azure/aks-engine#652]
We used to be able to install `acs-engine` using [Chocolatey](https://chocolatey.org/). This was very convenient, as everything we required for setup could be installed with Chocolatey (azure cli, helm, etc.). It appears that `aks-engine` isn't available via Chocolatey though - is there any plan to make it available again?

**Comment by mboersma** [comment]
Thanks for the nudge! I tried to get this started here: synax/chocolatey-packages#2.

**Comment by mboersma** [comment]
@kyschouv you should be able to do `choco install aks-engine` as soon as it is approved here: https://chocolatey.org/packages/aks-engine/

Thanks again for pointing this out.
