### ISSUE TITLE
Add customized config: use /mnt (the ephemeral/temp drive) for pod volumes

### ISSUE THREAD

**Issue by andyzhangx** [Azure/aks-engine#665]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:
we’re processing large assets (video files of 10GB+ size) in Kubernetes. Running on agent nodes (Azure H8 instances), we have vast amounts of space under /mnt (on the ephemeral / local SSD). Unfortunately, it seems ACS/AKS agents always have their docker directories on the OS disk… 

Is there a way to specify that writable filesystem of a k8s pod should be on the fast, large, ephemeral disk (/dev/sdb1) instead of the OS disk? 

forensic@k8s-agent-EDD077D5-0:~$ df -H
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        32G  4.1G   28G  13% /
/dev/sdb1       1.1T   75M  1.1T   1% /mnt

There is a manual way:
https://github.com/andyzhangx/Demo/tree/master/acs-engine#change-varlibdocker-to-mnt-which-has-100gb-disk-space

@JiangtianLi @jackfrancis , we may add this as a customized config into acs-engine?
I could see there are lots of customers asking for this feature, see:
https://github.com/Azure/acs-engine/issues/1307
https://github.com/Azure/acs-engine/issues/543

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
Hi @theobolo, as you may have noticed, the acs-engine project has moved and is now located at https://github.com/Azure/aks-engine. I've transferred your issue to the new issue queue.

**Comment by theobolo** [comment]
@CecileRobertMichon Thanks Cecile, i wasn't sure ;) since none of thoses related issues seem to have been moved on AKS issue thread, that's a great start ! 

Looking forward for this, cheers.

**Comment by CecileRobertMichon** [comment]
@theobolo just FYI, AKS Engine is different from AKS see https://github.com/Azure/aks-engine/blob/master/docs/faq.md

**Comment by theobolo** [comment]
@CecileRobertMichon Thanks, i'm using AKS btw, and i used ACS, but i tought that ACS was used by AKS underlyingly.

There is a lot of issues on the ACS issue thread that are still relevant for AKS today, i just try to big some of them :P

**Comment by CecileRobertMichon** [comment]
@theobolo by ACS do you mean acs-engine (the open source project)? acs-engine (now aks-engine) is open source, while ACS (deprecated) and AKS are services, not open source. See the FAQ I sent above for more details. 

You should file AKS specific issues (not aks-engine) at https://github.com/Azure/AKS/issues.

**Comment by theobolo** [comment]
@CecileRobertMichon Yes, to be clear is used ACS-Engine before AKS-engine, now i use AKS-engine but still thoses issues are relevant. I know that ACS-engine is deprecated but the underlying running processes are the same on the new AKS-engine. I think thoses issues are more proposals for additionnal features more than just issues, so i think that the correct git repo to transfer them is AKS-engine repo and not the AKS issue repo.

I'm sorry i was misleading you with my messages but i wasn't aware of all the AKS git repos ... :/

**Comment by adinunzio84** [comment]
Also looking for ephemeral drive support (related: https://github.com/Azure/AKS/issues/105), but we're using AKS, not AKS-engine. I assume the feature would be added somewhere in AKS-engine though
