### ISSUE TITLE
Get FD count based on region

### ISSUE THREAD

**Issue by palma21** [Azure/aks-engine#671]
Use and assign the fault domain count based on region support as per:

https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/managed-disks-common-fault-domain-region-list.md

**Comment by CecileRobertMichon** [comment]
For the record, we tried doing this before but it broke upgrade/scale and had to be reverted:
https://github.com/Azure/acs-engine/pull/3617
https://github.com/Azure/acs-engine/pull/3661

@mboersma might have more context.

**Comment by palma21** [comment]
@mboersma did you reopen the old PR or are you making a new one?

**Comment by mboersma** [comment]
@palma21 I have a new branch I'm working on.
