### ISSUE TITLE
Agent stuck in NotReady state.

### ISSUE THREAD

**Issue by nickmcmahan** [Azure/aks-engine#673]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of aks-engine?**: acs-engine v0.21.1

---

**Kubernetes version**: 1.11.2

**What happened**: There is a node in our cluster that is stuck in NotReady state. We have attempted to gracefully cordon, drain, reboot (through the Azure Portal), and then uncordon (in that order) - yet the issue persists. There is no error output in the console when this happens.

**What you expected to happen**: Expected the node to return to Ready status.

**How to reproduce it** (as minimally and precisely as possible): See above, we are following the typical node drain workflow as documented in the Kubernetes documentation (https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/).

**Anything else we need to know**: For this particular node, when we run kubectl get nodes -o=wide - the **CONTAINER-RUNTIME** field displays as **docker://Unknown**. All of the rest of the nodes in this cluster are reporting the correct Docker version.

**Comment by CecileRobertMichon** [comment]
@nickmcmahan did you try checking docker logs on that node? `sudo journalctl -u docker`.
Also checking if docker is running on the node `systemctl status docker` and then restarting docker might help `sudo systemctl restart docker`.

Which version of docker is your cluster on?
