### ISSUE TITLE
Document "component upgrade" scenarios

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#683]
Leaning upon the "force upgrade" functionality, let's document real-world scenarios that describe how it can help with component upgrades:

- update moby
- change kubelet/controller-manager/apiserver configuration
- new nvidia driver

etc

**Comment by CecileRobertMichon** [comment]
and test these scenarios :) 

also maybe reuse the existing docs/tutorials/day2-operations.md doc since this new functionality is relevant.
