### ISSUE TITLE
Make aks-engine generate command automatically generate SSH key pairs when publicKeys is empty

### ISSUE THREAD

**Issue by sukhong** [Azure/aks-engine#689]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**What version of aks-engine?**: v0.31.1

---

**Kubernetes version**: N/A

**What happened**: aks-engine generate command currently requires publicKeys's keyData field to be non-empty.

**What you expected to happen**: aks-engine generate command should automatically generate SSH key pairs and populate it.

**How to reproduce it** (as minimally and precisely as possible): Just run aks-engine generate with a cluster definition with empty publicKeys keyData.

**Anything else we need to know**: This would be really helpful as it doesn't require user to manually generate SSH key pair.

**Comment by CecileRobertMichon** [comment]
We already do this for deploy so this shouldn't be too hard to implement. Thanks @sukhong for the suggestion!

If anyone wants to pick this up, let us know - will label this as good first issue.
