### ISSUE TITLE
Validate AKS against template generation refactor

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#695]
This PR will represent the up-to-date "cutover" of the template generation implementation:

https://github.com/Azure/aks-engine/pull/682

Let's get some mileage testing AKS E2E scenarios against this to identify regressions early.

**Comment by mboersma** [comment]
@jackfrancis is there anything left to do here, or can we close this?

**Comment by jackfrancis** [comment]
Thanks for tracking!
