### ISSUE TITLE
Trying to build 1.12.6 cluster and getting "failed to load apimodel: --client-id and --client-secret must be specified when --auth-method="client_secret""

### ISSUE THREAD

**Issue by vannovv** [Azure/aks-engine#697]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
Version: v0.32.0
---

**Kubernetes version**:
1.12.6

**What happened**:
Have been using acs-engine to build out 1.8.6 clusters.  Wanting to build new 1.12.6 clusters and was encouraged to switch over to the latest version of AKS-Engine to do this.  Have updated my kubernetes.json file reflect the new version and when I issue the the AKS-Engine deploy command I get the error:

 FATA[0000] failed to load apimodel: --client-id and --client-secret must be specified when --auth-method="client_secret"

**What you expected to happen**:
A new cluster to be built

**How to reproduce it** (as minimally and precisely as possible):
Use AKS-Engine 1.12.6
Issue AKS-Engine deploy command:

aks-engine deploy --force-overwrite true --api-model apimodel.json --resource-group $RESOURCEGROUP --location ${LOCATION} --subscription-id ${SUBSCRIPTIONID} --output-directory ./$TIER/${region} --debug

**Anything else we need to know**:

I see an issue out there with the same error and it seemed like the "ClientID" field had been renamed to "service_principal" but then later on down in the thread it looked like it got reverted.
[https://github.com/Azure/aks-engine/pull/231 ]

Here is my kubernetes.json file:
`{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.12.6",
      "kubernetesConfig": {
        "networkPolicy": "calico",
        "networkPlugin": "kubenet",
        "gcHighThreshold": 75,
        "gcLowThreshold": 70,
        "controllerManagerConfig": {
          "--terminated-pod-gc-threshold": "100"
        }
      }
    },
    "aadProfile": {
      "serverAppID": "xxxxxxxxx",
      "clientAppID": "xxxxxxxxxx",
      "tenantID": "xxxxxxxxx"
  },
    "masterProfile": {
      "count": $MASTERNODECOUNT$,
      "dnsPrefix": "$TIER$$REGION$$APP$k8s$VERSION$",
      "vnetSubnetId": "/subscriptions/$SUBSCRIPTIONID$/resourceGroups/$TIER$$REGION$$APP$net$VERSION$rg/providers/Microsoft.Network/virtualNetworks/$TIER$$REGION$$APP$k8svn$VERSION$/subnets/$TIER$$REGION$$APP$mst$VERSION$sn",
      "vmSize": "Standard_D2_v2",
      "OSDiskSizeGB": 100,
      "storageProfile" : "ManagedDisks",
      "availabilityProfile": "AvailabilitySet",
      "vnetCidr" : "$CIDRBLOCK$",
      "firstConsecutiveStaticIP": "10.$SECONDOCTET$$THIRDOCTET$.150"
    },
    "agentPoolProfiles": [
      {
        "name": "fe",
        "count": $FRONTENDNODECOUNT$,
        "vmSize": "Standard_A4m_v2",
        "OSDiskSizeGB": 100,
        "storageProfile" : "ManagedDisks",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/$SUBSCRIPTIONID$/resourceGroups/$TIER$$REGION$$APP$net$VERSION$rg/providers/Microsoft.Network/virtualNetworks/$TIER$$REGION$$APP$k8svn$VERSION$/subnets/$TIER$$REGION$$APP$fea$VERSION$sn",
        "availabilityProfile": "AvailabilitySet"
      },
      {
        "name": "be",
        "count": $BACKENDNODECOUNT$,
        "vmSize": "Standard_A4m_v2",
        "OSDiskSizeGB": 100,
        "storageProfile" : "ManagedDisks",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/$SUBSCRIPTIONID$/resourceGroups/$TIER$$REGION$$APP$net$VERSION$rg/providers/Microsoft.Network/virtualNetworks/$TIER$$REGION$$APP$k8svn$VERSION$/subnets/$TIER$$REGION$$APP$bea$VERSION$sn",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "$ID_RSA_PUB$"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "ClientID": "$SP_CLIENTID$",
      "Secret": "$SP_SECRET$"}
  }
}`

**Comment by CecileRobertMichon** [comment]
Hi @vannovv, this is by design, as implemented by PR #231 as you pointed out. See https://github.com/Azure/aks-engine/issues/451 for more details.

**Comment by vannovv** [comment]
@CecileRobertMichon Thanks for answering.  I was able to pull the the client and secret out of the Kubernetes.json file and add it directly to the aks-engine deploy command and the cluster built.  However it appears these credentials are used when Kubernetes creates and assigns IP to my internal azure load balancer when I deploy a service that needs to be exposed outside of the cluster.  So I guess I am confused.  Should I be leaving the secret and client info in my Kubernetes.json file?  Is there a different way to get K8S to be able to manage the azure load balancer now?

**Comment by tariq1890** [comment]
@vannovv The details `kubernetes.json` is used by Azure's cloud controller manager in upstream Kubernetes. To my knowledge, there is no alternative to Kubernetes.json as of now.
