### ISSUE TITLE
Powershell Support?

### ISSUE THREAD

**Issue by perezjasonr** [Azure/aks-engine#711]
**Is this a request for help?**:

No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature Request

**What version of aks-engine?**:

Version: v0.32.0
GitCommit: c2b614849

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

The request is very simple, I was really hoping since this target users are people who will be using Azure, that this would be Powershell supported. I installed aks engine and it can be called from powershell but it failed with: "Invoking Azure CLI failed with the following error: 'az' is not recognized as an internal or external command..."

So its trying to use the Azure CLI and I dont see anything indicating we can get it to use powershell.

Please consider it. I set up all the pre-requisites (resource Group, service principal, etc). It would have been cool to just be able to call aks-engine successfully right there in the powershell prompt.

**Comment by serbrech** [comment]
Hi @perezjasonr. `az` is a cross platform cli tool that also works on all platform, you can install it on windows, and it will work from within powershell. see https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest
You should be able to call aks-engine just fine from Powershell once az is installed and in your path.

**Comment by perezjasonr** [comment]
Thank you, that is what I ended up doing of course. But my point was that
no matter what it requires the azure CLI its not interchangeable with the
azure powershell module. and the requirements say you must have aks engine
installed and azure cli, as opposed to aks engine and azure cli OR azure
powershell module.

Even though I can call aks engine with powershell it doesn't use powershell
after that it tries to use the az cli. I cannot use the other functionality
like aks-engine scale, it all relies on the azure cli in the end.

I just think it would be a cool thing to support since many azure users use
powershell modules. Pretty much anything that can be done in az cli can be
mirrored in azure powershell so I just thought it would be cool to support
eventually. My original request might have been misleading, I was actually
saying it would be nice to have a feature/support for the azure powershell
module instead of the az cli.

Thank you for your consideration.
