### ISSUE TITLE
Please update clusterdefinitions.md for #402 "Disable windows auto update"

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aks-engine#713]
Please update clusterdefinitions.md for #402, about how to disable Windows auto update, what is the default value.

**Comment by brunhil** [comment]
Hi @zhiweiv , as part of that feature I added documentation at the following location for [Windows and Kubernetes](https://github.com/Azure/aks-engine/blob/master/docs/topics/windows-and-kubernetes.md#disabling-automatic-updates).

Let me know if this needs more documentation.

**Comment by zhiweiv** [comment]
It looks great, I will have a try later.
Many thanks.
