### ISSUE TITLE
VMSS masters can't be upgraded

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#719]
VMSS master support is currently for experimentation only. We need to be able to upgrade them to call this a 1st class feature.

**Comment by senordeveloper** [comment]
We would like to see this feature soon because we are currently building private clusters in Azure and to be fail safe we need to set up three masters which have to use the VMSS currently.

**Comment by jackfrancis** [comment]
@senordeveloper why aren't you able to build 3 master clusters with availability set master VMs?

**Comment by senordeveloper** [comment]
The latest AKS-Engine does not allow to build a private 3 master cluster with availability set VMs.
Maybe we misconfigured something? 
Did anyone try this configuration? Thanks.

**Comment by jackfrancis** [comment]
@CecileRobertMichon Does that limitation ring true to you?

**Comment by CecileRobertMichon** [comment]
It doesn't. @senordeveloper can you please share the apimodel you're using in a new issue? It sounds like what you're describing isn't related to this particular issue since you're using private cluster + availability set, not VMSS masters.

**Comment by CecileRobertMichon** [comment]
I just deployed a cluster based on this configuration successfully with the latest aks-engine: https://github.com/Azure/aks-engine/blob/master/examples/kubernetes-config/kubernetes-private-cluster.json

**Comment by senordeveloper** [comment]
Does this work also with VMSS Agents and Availability Set Masters? Sorry, I can’t test it actually.

**Comment by jackfrancis** [comment]
@senordeveloper, upgrade does work against VMSS node pools. We don't plan to address this in the near term. I.e., VMSS master nodes support is for ephemeral clusters only (no upgrade support).
