### ISSUE TITLE
Add Custom NSG rules to template 

### ISSUE THREAD

**Issue by csubj** [Azure/aks-engine#720]
**Is this a request for help?**:
No 
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): 
FEATURE 

---

**What version of acs-engine?**:
ALL 
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
ALL

**What you expected to happen**:
When the template is used for generating the resource/deployment files a master NSG is created with some default securitygroup rules; as it is there is no current way to override or add custom rules in the template - they need to be added manually after generation. This would be a very nice feature to add for people trying to lock down vnet/subnets for security + compliance when running ACS clusters for production.

**Comment by ams0** [comment]
I would like to work on this one to learn more about the inner workings of aks-engine and as part of our CSE bug bash.

**Comment by CecileRobertMichon** [comment]
keep open
