### ISSUE TITLE
Make creating a service principal and granting contributor rights a better experience

### ISSUE THREAD

**Issue by davidmatson** [Azure/aks-engine#737]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
```
Version: v0.22.1
GitCommit: 0908e5151
GitTreeState: clean
```
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.11.2

**What happened**:
kubectl create secret failed

**What you expected to happen**:
kubectl create secret should succeed

**How to reproduce it** (as minimally and precisely as possible):
tl;dr
The service principal needs to be provisioned with Owner permissions via IAM on both the key vault and storage account resources.

Details:
1. In apimodel.json, set `"enableEncryptionWithExternalKms": true` on a new resource group.
2. Run `kubectl create secret generic secret1 -n default --from-literal=mykey=mydata`.

Error message:
```
Error from server (InternalError): Internal error occurred: rpc error: code = Unknown desc = failed to get vault, error: failed to get vault, error: keyvault.VaultsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<clientId>' with object id '<objectId>' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.KeyVault/vaults/<keyVaultName>'."
```

3. Work around that error by running `az role assignment create --subscription $SubscriptionId --role Owner --assignee-object-id $servicePrincipalObjectId --scope keyVaultResourceId`.
4. Again run `kubectl create secret generic secret1 -n default --from-literal=mykey=mydata`.

Second error message:
```
Error from server (InternalError): Internal error occurred: rpc error: code = Unknown desc = failed to create key, error: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<clientId>' with object id <objectId>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Storage/storageAccounts/<keyVaultName>'."
```

5. Work around the second error by running `az role assignment create --subscription $SubscriptionId --role Owner --assignee-object-id $servicePrincipalObjectId --scope $storageAccountResourceId`.

The kubectl create secret command will now work.

**Comment by munishm** [comment]
I have few questions related to it:

1.   Is it not a sound practice to have a contributor role SP?
2.  We don't need this enhancement if SP has contributor role, Will there be any  case where one doesn't have permission to create this kind of role?

**Comment by davidmatson** [comment]
@munishm - To answer your questions -
1. I think it's fine for the SP to be granted Contributor rights on this resource group.
2. If the SP is already in the Contributor role, then you're correct, nothing else is needed. However, for a newly-created SP, it may not already have been grated the Contributor role on this resource group, which is what this issue is about. If the identity aks-engine is running under doesn't have rights to add the SP to the Contributor role, then yes, it won't be able to fix the problem, but it could at least attempt to do so and fail saying it couldn't if that happens.

**Comment by jackfrancis** [comment]
@davidmatson I notice you removed the stale label recently. Are there remaining issues in this issue?

**Comment by davidmatson** [comment]
Can aks-engine automatically grant Contributor rights to the SP? (That's the remaining part.)

**Comment by jackfrancis** [comment]
Hi @davidmatson, we don't plan to integrate automatic role assignment of sps into aks-engine.
