### ISSUE TITLE
Update cluster-autoscaler versions to fix case sensivity in resource groups

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#741]
Upstream PR here:

https://github.com/kubernetes/kubernetes/pull/74882

Let's make sure we have the latest, stable cluster-autoscaler implementation for each version of k8s. E.g., 1.14 is here:

https://github.com/Azure/aks-engine/blob/master/pkg/api/k8s_versions.go#L33

Let's get the right versions configured for:

- 1.10
- 1.11
- 1.12
- 1.13
- 1.14

**Comment by feiskyer** [comment]
Kubernetes Version | CA Version
-- | --
1.13.X | 1.13.2
1.12.X | 1.12.3
1.11.X | 1.3.8
1.10.X | 1.2.5

**Comment by CecileRobertMichon** [comment]
PR was reverted because it broke unit tests in master
