### ISSUE TITLE
addons/cluster-autoscaler - error parsing the api model: invalid character '}' 

### ISSUE THREAD

**Issue by ben-omji** [Azure/aks-engine#746]
**Is this a request for help?**: No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of aks-engine?**: v0.32.0

---

For enable adds-on 'cluster-autoscaler', I wrote the yaml file like this. (based on [example](https://github.com/Azure/aks-engine/blob/master/examples/addons/cluster-autoscaler/README.md))

( '***' is some value)
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
	  "orchestratorRelease": "1.10",
      "kubernetesConfig": {
        "useManagedIdentity": true,
        "addons": [
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "config": {
              "min-nodes": "1",
              "max-nodes": "5",
              "scan-interval": "10s",
            }
          }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "tw-tedworks",
      "vmSize": "Standard_B2ms"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool1",
        "count": 1,
        "vmSize": "Standard_B2ms",
		"availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azure-user",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa ***"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "***",
      "secret": "***"
    }
  }
}
```

But, I got ERROR like:
> FATA[0000] error loading API model in generateCmd: error parsing the api model: invalid character '}' looking for beginning of object key string

### After some tries, I found the ',' after "scan-interval": "10s"

If you guys got error like me, please remove the comma.

Cheers,
Ben

**Kubernetes version**: 1.10

**What happened**: Got Error with the file base on example

**What you expected to happen**: Work fine with no error

**How to reproduce it** (as minimally and precisely as possible): Use [this example](https://github.com/Azure/aks-engine/blob/master/examples/addons/cluster-autoscaler/README.md)

**Anything else we need to know**: Someone who change the example..

**Comment by ams0** [comment]
There's an extra comma on the line:

```bash
              "scan-interval": "10s",
```
