### ISSUE TITLE
Hardcoded master VMSS ILB IP address not within custom VNET CIDR

### ISSUE THREAD

**Issue by mpalumbo7** [Azure/aks-engine#750]
**Is this a request for help?**: `Yes`

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): `Issue`

---

**What version of aks-engine?**: `v0.31.3`

---

**Kubernetes version**: 

**What happened**:

Azure ARM API error due to hardcoded IP address not falling in custom VNET CIDR:

```json
{ 
    "statusCode": "BadRequest",
    "statusMessage": { "error": { 
         "code": "PrivateIPAddressNotInSubnet", 
        "message": "Private static IP address 172.16.255.10 does not belong to the range of subnet prefix 172.16.8.0/24.", 
        "details": [] 
    } },
    "resourceName": "k8s-master-internal-lb-XXXXXXXXX" } }
}
```

The custom VNET has the following configuration:

**Address Space**: `172.16.8.0/22`
**Master Subnet**: `172.16.8.0/24`
**Agent Subnet**: `172.16.9.0/24`

And the generated ARM template with Master VMSS ILB is trying to create the `172.16.55.10` which is not in the master subnet.

It's this line that is causing the issue:

```go
if isMasterVMSS {
    masterVars["kubernetesAPIServerIP"] = "[concat(variables('masterFirstAddrOctets')[0],'.',variables('masterFirstAddrOctets')[1],'.255.', variables('masterInternalLbIPOffset'))]"
} else {
    masterVars["kubernetesAPIServerIP"] = "[concat(variables('masterFirstAddrPrefix'), add(variables('masterInternalLbIPOffset'), int(variables('masterFirstAddrOctet4'))))]"
}
```

This was introduced in #324 in [pkg/engine/armvariables.go#L361](https://github.com/Azure/aks-engine/blob/ccb29355a17d0b40b70014e09ee374b71a4048fb/pkg/engine/armvariables.go#L361).

**What you expected to happen**:

The AKS-Engine generates an IP address within the master node subnet.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by zjfroot** [comment]
We have the same issue when using a custom vnet. Please fix the bug.

**Comment by smahalingam** [comment]
@jackfrancis Any reason for hardcoded third octet (`255`) https://github.com/Azure/aks-engine/blob/21329821055e7c39ea3a040a2ca03d9d7566c1fd/pkg/engine/armvariables.go#L369 
rather `firstMasterIP[2]` ?

**Comment by ritazh** [comment]
Agreed that this should be derived. Background on this: Since Azure VMSS does not allow us to set static private IPs of the specific instances, the private IPs have to be derived from `masterFirstAddrOctets` and `IPAddressCount` (number of IP address per master node). These IPs are used to join master nodes to the etcd cluster as well as creating the cert and key pairs for etcd.  To prevent collision, `255` was used for the third octet for the `kubernetesAPIServerIP`.

**Comment by bengrisafi** [comment]
We have run into this issue as well, if you expose the ability to set a custom vnet they allow us to set the vnet cidr and not just a portion.

**Comment by awr** [comment]
I've run into this as well ... had to rewrite the azuredeploy.json file after it was generated to work around it, which is a bit of a pain
