### ISSUE TITLE
ubuntu-18.04 distro + AzureCNI results in OS Provisioning Timeouts (OSPTO)

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#761]
As discovered in #223, cloud-init 18.04 changed the default for ` apply_network_config` default to true.
https://git.launchpad.net/cloud-init/tree/cloudinit/sources/DataSourceAzure.py#n213

This results in no network path from VM ( potentially due to race with older IP address set within the VM from from Metadata Service). Because AzureCNI uses more IPs than kubenet, it is much more likely to reproduce this behavior, which causes most 18.04 + AzureCNI deployments to result in OSPTO.

There is a separate bug in cloud-init where the userdata supplied when a VM is provisioned cannot override the configuration of the Azure datasource in custom data. 

Workaround (not tested):
In the VM used to build the VHD, create a file in /etc/cloud/cloud.cfg.d called 80_azure_net_config.cfg with this content:
 
```
datasource:
    Azure:
        apply_network_config: false
```

**Comment by CecileRobertMichon** [comment]
Reopening as this still applies for the ubuntu-18.04 (not aks-18.04) distro.

**Comment by jackfrancis** [comment]
Fixed in #2908

**Comment by AlexEyler** [comment]
@jackfrancis is the default distro for master nodes still 16.04 LTS? [These docs](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#masterprofile) point to this issue as the reason why the default distro is 16.04 LTS.

**Comment by jackfrancis** [comment]
Thanks for reporting @AlexEyler!

That's a mistake, corrected here: https://github.com/Azure/aks-engine/pull/3317

The default was recently changed to 18.04-LTS.
