### ISSUE TITLE
Migrate from heapster to metrics-server. Metrics-server is paused.

### ISSUE THREAD

**Issue by arianitu** [Azure/aks-engine#765]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
v1.11.5

---

**Kubernetes version**:
v1.11.5

**What happened**:

metrics-server is paused somehow, the yaml looks like so:

```
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 0
```

because metrics-server is paused, I cannot do backups with Velero because of this issue: https://github.com/heptio/velero/issues/1283

I notice that Heapster is running instead of metrics-server. I think this is probably because Azure has an option to use the Kubernetes dashboard and that's not supported yet:

https://github.com/kubernetes/dashboard/issues/2986

So I have a few questions:

1. How do I move to metrics-server from heapster. If I move, I assume `az aks browse ` will stop working and we can no longer use the Kubernetes dashboard.
2. Can I have both metrics-server and heapster running at the same time. Did AKS disable metrics-server for me, or how did that happen?

I also notice I can't use `kubectl top` since that requires metrics-server.

**Comment by CecileRobertMichon** [comment]
Hi @arianitu, is this an issue for https://github.com/Azure/AKS?

**Comment by arianitu** [comment]
Yes. apologies.
