### ISSUE TITLE
Can not deploy a windowscluster with aks-engine 32.1 

### ISSUE THREAD

**Issue by fberlin** [Azure/aks-engine#775]
**Is this a request for help?**:
Yes.

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

**What version of aks-engine?**:
32.1

**Kubernetes version**:
1.14.0-beta.1

**What happened**:
When I try to deploy a cluster using Kubernetes Windows Walkthrough (https://github.com/Azure/aks-engine/blob/master/docs/topics/windows.md) it fails in the 'az group deployment create' step.

Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template resource '3129k8s000winrm' at line '1' and column '139628' is invalid. 'ApiVersion' property is invalid. The supported versions are '2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'. Please see https://aka.ms/arm-template/#resources for usage details.'.

I've done this many times before without any problems using a previous version of aks-engine.

**What you expected to happen**:
To get a working kubenetescluster in Azure

**How to reproduce it** (as minimally and precisely as possible):
Deploy with this kubernetes-windows-complete.json:
{
    "apiVersion":  "vlabs",
    "properties":  {
                       "orchestratorProfile":  {
                                                   "orchestratorType":  "Kubernetes",
                                                   "orchestratorRelease":  "1.14",
                                                   "orchestratorVersion": "1.14.0-beta.1"
                                               },
                       "masterProfile":  {
                                             "count":  1,
                                             "dnsPrefix":  "paletteonline14",
                                             "vmSize":  "Standard_D2_v3"
                                         },
                       "agentPoolProfiles":  [
                                                 {
                                                     "name":  "windowspool2",
                                                     "count":  2,
                                                     "vmSize":  "Standard_D2_v3",
                                                     "availabilityProfile":  "AvailabilitySet",
                                                     "osType":  "Windows",
                                                     "osDiskSizeGB":  128,
                                                     "extensions":  [
                                                                        {
                                                                            "name":  "winrm"
                                                                        }
                                                                    ]
                                                 }
                                             ],
                       "windowsProfile":  {
                                              "adminUsername":  "username",
                                              "adminPassword":  "password",
                                              "sshEnabled":  true
                                          },
                       "linuxProfile":  {
                                            "adminUsername":  "azureuser",
                                            "ssh":  {
                                                        "publicKeys":  [
                                                                           {
                                                                               "keyData":  *****************************
                                                                           }
                                                                       ]
                                                    }
                                        },
                       "servicePrincipalProfile":  {
                                                       "clientId":  ***********************************,
                                                       "secret":  **********************************
                                                   },
                       "extensionProfiles":  [
                                                 {
                                                     "name":  "winrm",
                                                     "version":  "v1"
                                                 }
                                             ]
                   }
}

**Comment by CecileRobertMichon** [comment]
@fberlin my guess is that the error is coming from the extension. Are you able to get a successful deployment if you remove the extension?

**Comment by jchauncey** [comment]
I mentioned this the other day in teams. Ive been having this problem for like 2 weeks now.

**Comment by jchauncey** [comment]
At the time it was mentioned that maybe it was related to this pr - https://github.com/Azure/aks-engine/pull/578

**Comment by fberlin** [comment]
@CecileRobertMichon I think you are correct about the extension. 

When I remove it the deployment succedes. Never thought about the extension as it's set automatically in the walkthrough.

**Comment by andrewboyce** [comment]
I ran into this today, when attempting to deploy a Windows cluster with the winrm extension present. If one examines the template produced by `aks-engine generate` for such a cluster, one will find something similar to the following:

```jsonc
{
  "apiVersion": "[variables('apiVersionCompute')]",
  "copy": {
    "count": "[sub(variables('windowspool1Count'), variables('windowspool1Offset'))]",
    "name": "winrmExtensionLoop"
  },
  "dependsOn": [
    "[concat('Microsoft.Compute/virtualMachines/', variables('windowspool1VMNamePrefix'), copyIndex(variables('windowspool1Offset')), '/extensions/cse', '-agent-', copyIndex(variables('windowspool1Offset')))]"
  ],
  "name": "[concat(variables('windowspool1VMNamePrefix'), copyIndex(variables('windowspool1Offset')), 'winrm')]",
  "properties": {
    "parameters": {
      "apiVersionCompute": {
        "value": "[variables('apiVersionCompute')]"
      },
      // ...parameters elided...
    },
    "mode": "Incremental",
    "templateLink": {
      "contentVersion": "1.0.0.0",
      "uri": "https://raw.githubusercontent.com/Azure/aks-engine/master/extensions/winrm/v1/template.json"
    }
  },
  "type": "Microsoft.Resources/deployments"
}
```

The critical part seems to be the `apiVersion` at the top of the block above:
```jsonc
  "apiVersion": "[variables('apiVersionCompute')]"
```

When I changed that line in the ARM template file to
```jsonc
  "apiVersion": "2018-11-01"
```
and then tried to deploy the template, the deployment succeeded.

**Instead of using the `apiVersionCompute` variable, should that `apiVersion` line instead be referencing a template variable (added to [kubernetesmastervars.t](https://github.com/Azure/aks-engine/blob/master/parts/k8s/kubernetesmastervars.t)?) containing an API version appropriate for the `Microsoft.Resources/deployments` resource type?**

Running the following Azure CLI command to list API versions for the `Microsoft.Resources/deployments` resource type
```
az provider show --namespace Microsoft.Resources --query "resourceTypes[?resourceType=='deployments'].apiVersions | [0]" --out table
```
returns a list containing some of the supported versions listed in the original error message (and none that _aren't_ in the list from the original error message).

**Comment by CecileRobertMichon** [comment]
@andrewboyce you are correct, that is exactly what to issue/fix is.

If you or anyone else in this thread would like to contribute to help us get this fixed faster, please do open a PR and someone from the team can help review & get it merged.
