### ISSUE TITLE
Metrics Server still broken

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/aks-engine#776]
**Is this a request for help?**: Help

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of aks-engine?**: 0.32.0

---

**Kubernetes version**: 1.13.4

**What happened**: Metrics-server still in a Crashback Loop

**What you expected to happen**: Metrics-server to run correctly

**How to reproduce it** (as minimally and precisely as possible): Deploy a 1.13.4 cluster and check the status of metrics-server

**Anything else we need to know**:
From the logs:

I0315 20:23:17.644542       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:''
I0315 20:23:17.644606       1 heapster.go:72] Metrics Server version v0.2.1
I0315 20:23:17.644783       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version 
I0315 20:23:17.644806       1 configs.go:62] Using kubelet port 10255
I0315 20:23:17.645739       1 heapster.go:128] Starting with Metric Sink
I0315 20:23:18.064897       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0315 20:23:18.354382       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file

**Comment by CecileRobertMichon** [comment]
@dcieslak19973 can you please share your apimodel? we're not seeing this in our tests.

**Comment by dcieslak19973** [comment]
The start of our configuration file that we pass into aks-engine is:

`{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.13",
      "kubernetesConfig": {
        "networkPolicy": "azure",
        "enableRbac": false,
        "useManagedIdentity": false,
        "addons": [
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "config": {
              "maxNodes": "16",
              "minNodes": "3"
            }
          }
        ],
        "privateCluster": {
          "enabled": true
        }
      }
    },
`

**Comment by jackfrancis** [comment]
I've filed this to help us debug this (and other) private cluster scenarios:

https://github.com/Azure/aks-engine/issues/823

@palma21 for prioritization
