### ISSUE TITLE
aks-engine deploy hangs and fails to deploy Microsoft.Compute/virtualMachines/extensions after 1~2 hours

### ISSUE THREAD

**Issue by sukhong** [Azure/aks-engine#783]
**Is this a request for help?**: 
Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): 
ISSUE

---

**What version of aks-engine?**:
Version: v0.31.1
GitCommit: 13c427824

---

**Kubernetes version**:
1.13

**What happened**:
aks-engine deploy hangs and fails to deploy Microsoft.Compute/virtualMachines/extensions after 1~2 hours:

![image](https://user-images.githubusercontent.com/3857851/54503047-b784ed80-48ea-11e9-89bd-709349d6f28c.png)

This used to work, but it starts to happen recently. Deployment sometimes succeeds. Number of master nodes failures seem to be random (sometimes I see 2 failures, sometimes I see 1 failure).

**What you expected to happen**:

aks-engine deployment should succeed in 5~10 minutes (it used to work perfectly).

**How to reproduce it** (as minimally and precisely as possible):

I run this command: 
`aks-engine deploy --subscription-id 18cec2bf-838a-4b37-87df-33582732a378 --auth-method cli --resource-group IAMKubernetesPPEWUS2 --location westus2 --api-model wus2.iamcluster-ppe.json`

I have attached wus2.iamcluster-ppe.json file as well as generated ARM template.

**Anything else we need to know**:
I also created an ICM ticket here: https://icm.ad.msft.net/imp/v3/incidents/details/110100252/home

**Comment by sukhong** [comment]
Attaching original template + generated ARM templates

[PPE.zip](https://github.com/Azure/aks-engine/files/2976152/PPE.zip)

**Comment by andyzhangx** [comment]
would you attach `/var/log/azure/cluster-provision.log`?

**Comment by PacoGuy** [comment]
I opened a ticket for a similar or the same [issue](https://github.com/Azure/aks-engine/issues/768) last week. The change which fixed my issue was made and is present in the latest release v0.32.3

Hope that helps!

**Comment by sukhong** [comment]
@PacoGuy Thank you so much! Using the latest aks-engine version resolved this issue.

**Comment by PacoGuy** [comment]
Thanks goes to @jackfrancis and team!
