### ISSUE TITLE
Cannot create Kubernetes LoadBalancer

### ISSUE THREAD

**Issue by bclau** [Azure/aks-engine#784]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of aks-engine?**: v0.31.3

---

**Kubernetes version**: v1.14.0-alpha.1

**What happened**:

Cannot create Kubernetes LoadBalancer, it remains in the ``Pending`` state, and looking at its event list, the following can be seen:

    Warning  ListLoadBalancers           27s                azure-cloud-provider  
    azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to 
    https://management.azure.com/subscriptions/subscription_id/resourceGroups/group_name/providers/Microsoft.Network/loadBalancers?api-version=2017-09-01: 
    StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. 
    Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client 
    secret is provided.\r\nTrace ID: trace_id\r\nCorrelation ID: correlation_id\r\nTimestamp: 
    2019-03-18 10:33:25Z","error_codes":[7000215],"timestamp":"2019-03-18 
    10:33:25Z","trace_id":"trace_id","correlation_id":"correlation_id"}

**What you expected to happen**:

Should be able to create LoadBalancer.

**How to reproduce it** (as minimally and precisely as possible):

Create the following replication controller and service: [1]
Run the following:

    kubectl create -f lb.yaml  # [1]
    kubectl describe -n test-lb svc/service

[1] https://paste.ubuntu.com/p/k98Kg7kMdm/

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
Hi @bclau, this may have been due to a new release of walinuxagent in the wild, and a bug in the way that our provisioning script handles that. It was addressed in #771 and #778 and those fixes were included in the v0.32.3 release:

https://github.com/Azure/aks-engine/releases/tag/v0.32.3

This bug only affected newly built clusters, so the fix is to re-build those cluster using v0.32.3

Is it possible for you to re-build the cluster and report back?

**Comment by seanw122** [comment]
I found my error; the service principal being used was not the same one that created the cluster. I updated my Az Cli and ran command to replace the service principal. I'm good now.  https://docs.microsoft.com/en-us/azure/aks/update-credentials

**Comment by jackfrancis** [comment]
Thanks @seanw122 for following up. Will close this issue for now.
