### ISSUE TITLE
Dashboard permission errors from `kubectl proxy` on K8s 1.10.3 cluster deployed from acs-engine master 

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#805]
**Is this an ISSUE or FEATURE REQUEST?**

Issue

---

**What version of acs-engine?**

Version: canary
GitCommit: a1fe789
GitTreeState: dirty

(I had one change to the Makefile so that `make dev` works on my system with a strange net config)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:

The dashboard at http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default doesn't seem to have any permissions for the service account it's running as.

```
warning
configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list configmaps in the namespace "default" 
close 
warning
persistentvolumeclaims is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list persistentvolumeclaims in the namespace "default" 
close 
warning
secrets is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list secrets in the namespace "default" 
close 
warning
services is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list services in the namespace "default" 
close 
warning
ingresses.extensions is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list ingresses.extensions in the namespace "default" 
close 
warning
daemonsets.apps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list daemonsets.apps in the namespace "default" 
close 
warning
pods is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list pods in the namespace "default" 
close 
warning
events is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list events in the namespace "default" 
close 
warning
deployments.apps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list deployments.apps in the namespace "default" 
close 
warning
replicasets.apps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list replicasets.apps in the namespace "default" 
close 
warning
jobs.batch is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list jobs.batch in the namespace "default" 
close 
warning
cronjobs.batch is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list cronjobs.batch in the namespace "default" 
close 
warning
replicationcontrollers is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list replicationcontrollers in the namespace "default" 
close 
warning
statefulsets.apps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list statefulsets.apps in the namespace "default" 
```

**What you expected to happen**:

Dashboard should work, be able to show nodes, pods, and so on

**How to reproduce it** (as minimally and precisely as possible):

1. Create a JSON file with 

```
"orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.10.3"
    },
```
2. `acs-engine generate`, deploy it
3. Copy .kube/config from master node

4. `kubectl proxy`

5. browse to http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default

**Comment by jackfrancis** [comment]
This looks fixed

**Comment by joshuataylor** [comment]
It's only fixed after running the above command though.

**Comment by sujyot** [comment]
> Run kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
> Everything worked for me.


Fantastic. It worked for me too... Thanks :)

**Comment by jackfrancis** [comment]
@joshuataylor thank you for adding that important bit of information :) so that folks coming to this thread from older clusters have a clear path

**Comment by ricadelic** [comment]
This is documented in https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges

**Comment by glglak** [comment]
> Run kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
> Everything worked for me.

that worked for me

**Comment by KyleSanderson** [comment]
lol pretty disgraceful this is broken over a year later.

**Comment by alkadevops** [comment]
nothing is working for me after trying all abiove

**Comment by Berndinox** [comment]
@alkadevops 
Installed the Dashboard with Ingress just a few seconds ago, worked perfectly.
May delete you serviceaccount and try again: https://medium.com/@kanrangsan/creating-admin-user-to-access-kubernetes-dashboard-723d6c9764e4

BR Bernd

**Comment by gynet** [comment]
If this is an issue closed with some fix, why this doc does not tell the customers about it and let it happen again and again?  https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes

**Comment by paulohenriquesi** [comment]
> Run kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
> Everything worked for me.

This! Solved my problem. Thank you!

**Comment by TheAzureGuy007** [comment]
> Run kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
> Everything worked for me.

Assigning "cluster-admin" role is not solution for every case, especially if you are building kubernetes multitenancy model
#theazureguy007

**Comment by stampeder** [comment]
Run kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard

Nope. I ran this and I still can't get the permissions of an admin no matter what. Definitely not solved.
Thanks.

**Comment by fsantos2019** [comment]
Sorry for posting on closed issue, but **IMHO** you should never link a service account to a `Cluster-admin` role. 
The Privilege is just way to big, it's like God on your cluster and if anyone uses it, that person can potentially destroy all ressources within your cluster. 

You should use something like this instead: 
```
--- 
kind: ClusterRole 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  name: k8s-dashboard-clusterrole 
  namespace: kube-system
rules: 
  - apiGroups: 
      - "*" 
    resources: 
      - "*" 
    verbs: 
      - "list"
      - "get" 
      - "watch" 
 
--- 
kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  name: k8s-dashboard-clusterrole 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: k8s-dashboard-clusterrole 
subjects: 
- kind: ServiceAccount 
  name: kubernetes-dashboard
  namespace: kube-system
```

This provides the service account **kubernetes-dashboard** the ability to **List, get and watch** all ressources on all API but can't modify anything.  Hope it helps

**Comment by AMoghrabi** [comment]
Really appreciate the example yaml @fsantos2019! Worked like a charm.
