### ISSUE TITLE
Scale does not drain nodes when scaling down VMSS

### ISSUE THREAD

**Issue by amrmahdi** [Azure/aks-engine#806]
**Is this a request for help?**:

No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

0.25.1

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.10.8

**What happened**:

Using acs-engine scale to scale down a VMSS agent pool, the nodes are not drained before scaling down the VMSS. To verify the issue, I tried not supplying ```--master-FQDN``` when scaling down, and acs-engine did not complain that it is not missing.

**What you expected to happen**:

Acs-engine would drain the nodes first before taking the nodes down.

**How to reproduce it** (as minimally and precisely as possible):

Use acs-engine to scale down an agent pool without supplying ```--master-FQDN``` and monitor the nodes while this is happening. 

1. Nodes transition to NotReady from Ready directly.
2. No acs -engine logs to indicate nodes drainage

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
@palma21 for prioritization

**Comment by chreichert** [comment]
Not stale.
Nodes are deleted but not correctly drained when scaling down VMSS.

**Comment by palma21** [comment]
That should not be the case.

CC @craiglpeters
