### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#808]
Currently coverage is 38%. We should add unit tests as much as possible and get closer to 100%. Good places to start: 
- https://github.com/Azure/acs-engine/tree/master/pkg/acsengine, for example https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/engine_test.go 
- https://github.com/Azure/acs-engine/tree/master/pkg/operations/
- https://github.com/Azure/acs-engine/tree/master/cmd

**Comment by mboersma** [comment]
Coverage is now 68%.

**Comment by tariq1890** [comment]
There is no such thing as "too many unit tests".
