### ISSUE TITLE
Expose service, the public IP doesn't hit the pod

### ISSUE THREAD

**Issue by wuhanyumsft** [Azure/aks-engine#817]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
aks-engine-v0.31.1-windows-amd64.zip
---

**Kubernetes version**:
v1.13.3

**What happened**:
I can't access an exposed service via public external IP.

**What you expected to happen**:
I can access the webapp via external IP

**How to reproduce it** (as minimally and precisely as possible):
I deploy Web App with containerPort 80 open. 
Then I expose the deployment using `kubectl expose deployment XXX --type=LoadBalancer"
I wait a while and see the external IP exposed.
I try to access the external IP but the connection is timeout.

**Anything else we need to know**:
The master node is linux OS.
The agent nodes are VMSS on windows OS,

**Comment by jackfrancis** [comment]
@craiglpeters @jsturtevant FYI this is the same symptom we've seen when we've run VMSS Windows tests.

**Comment by jackfrancis** [comment]
@wuhanyumsft I'm going to close this in favor of #809
