### ISSUE TITLE
Is it possible to set the default value of max-pods to 110 by using the azure network plugin on the AKS-Engine?

### ISSUE THREAD

**Issue by toyota790** [Azure/aks-engine#820]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE 
---

**What version of aks-engine?**:
v0.32.3
---

**Kubernetes version**:
1.13.4

**What happened**:
I want to confirm that is it possible to set the default value of `max-pods` to 110 by using the azure network plugin on the AKS-Engine? 

**What you expected to happen**:
The default value of `max-pods` should be set to 110 by using the azure network plugin.

**How to reproduce it** (as minimally and precisely as possible):

1. Generate the template file by AKS-Engine
1. Deploy the cluster to Azure

**Anything else we need to know**:
No

**Comment by jackfrancis** [comment]
@tamilmani1989 can you confirm that there is no definite limitation on `--max-pods` to `30` for Azure CNI?

@toyota790 the documentation you reference only shows the default values, not any static limitation

**Comment by toyota790** [comment]
@jackfrancis So there is no limitation of the `--max-pods` size for any network plugin? Thank you!

**Comment by tamilmani1989** [comment]
@jackfrancis @toyota790 I will submit a PR today for increasing the limit to 110

**Comment by toyota790** [comment]
@tamilmani1989 OK! Thank you so much!

**Comment by toyota790** [comment]
@jackfrancis Sorry, I just realized it means the **default value** rather than the maximum value. So I have revised the issue to align the PR. Sorry for any inconvenience may cause. And thank you so much for your explanation and confirmation.
