### ISSUE TITLE
Private Cluster E2E scenarios

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#823]
We don't currently have reliable E2E test coverage for private cluster scenarios. This makes it more likely that regressions will be introduced, and reduced the effectiveness of rapid testing/validation for folks struggling with private cluster scenarios.

**Comment by dcieslak19973** [comment]
So here's my scenario for this - Ark requires Metrics Server. We use (or plan to use) Ark to migrate data from PVCs when we upgrade a K8s cluster. Without this functionality, I don't have an upgrade path nor a DR path for anything that uses PVCs.
