### ISSUE TITLE
AKS default OS disk size is now 100 GB

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#827]
Let's update our surface area and VHD configurations as appropriate.

**Comment by jackfrancis** [comment]
@CecileRobertMichon FYI

**Comment by CecileRobertMichon** [comment]
Is the minimum disk size still 100 GB as well (if it is configurable)?

**Comment by weinong** [comment]
@CecileRobertMichon , nope, the change is about "defaulting to 100G" is not specified. We are not bumping the minimum requirement to 100G.

**Comment by CecileRobertMichon** [comment]
In that case we can't assume that every deployment will use have 100 GB minimum so we need to maintain a solution for clusters with OS disks between 30 and 100 GB.

**Comment by jackfrancis** [comment]
I think we should continue to pin our E2E tests against the minimum (30 GB), so I think there's nothing to do here.
