### ISSUE TITLE
Is there any size limitation for the agent pool profiles on the aks-engine?

### ISSUE THREAD

**Issue by toyota790** [Azure/aks-engine#834]
**Is this a request for help?**:
YES
---
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
v0.32.3
---

**Kubernetes version**:
1.13.4

**What happened**:

Is there any size limitation for the agent pool profiles on the aks-engine? The cluster definition [document](https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#agentpoolprofiles) state that 

> A cluster can have 0 to 12 agent pool profiles. 

But I can generate the ARM files with 14 agent pool profiles by aks-engine. It can also deploy the cluster to the Azure. The aks-engine seems not to check the size for the agent pool profiles. Does anyone know whether it is possible to have more than 12 agent pools in a cluster? If it is possible, is there any other details I should note? Thank you.

**What you expected to happen**:

If the aks-engine can only have 0 to 12 agent pool profiles, it should check the template file and won't be able to deploy the cluster on Azure. 

**How to reproduce it** (as minimally and precisely as possible):

1. Generate the template file by AKS-Engine
1. Edit the template file and add 13 or more `agentPoolProfiles`
1. Deploy the cluster on Azure

**Anything else we need to know**:
No

**Comment by toyota790** [comment]
@jackfrancis Could you please help me on this? Thank you so much! :blush:

**Comment by CecileRobertMichon** [comment]
There is no enforced limit on the number of agent pools a cluster can have. Historically, this limit was artificially enforced by the max size of the ARM parameters template. We should review the documentation if it doesn't reflect reality anymore and update it. Thanks for raising this @toyota790

**Comment by toyota790** [comment]
@CecileRobertMichon Got it. Thank you for your kind assistance! :)
