### ISSUE TITLE
TLS certificate rotation

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#84]
Implement TLS certificate rotation to provide a tool for clusters created 2+ years ago that are reaching the default cert expiration.

**Comment by palma21** [comment]
Let's start this by phases

## Phase1:

- Use part of the AKS-Engine deploy code to generate the certificates we need
- From master rotate etcd CA and certificates in all masters
- From master rotate CA and certs in the nodes 
- Update kubeconfig and rotate the kubelet certs 

*Important:* For this phase the user is required to:
- (Optional but preferred) Backup etcd
- (Required) Reboot all nodes after rotation

**Comment by palma21** [comment]
### **Phase 2:**

- look into enabling the kubelet certificate rotation feature `--feature-gates=RotateKubeletClientCertificate=true` for newer clusters 
https://kubernetes.io/docs/tasks/tls/certificate-rotation/
https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

- look into creating a general script for validation
`aks-engine validate --kubeconfig=<path-to-kube-config> --api-model=<path-to-api-model>`
