### ISSUE TITLE
Random Windows node stops working with "NetworkPlugin cni failed to set up pod ..." error

### ISSUE THREAD

**Issue by ai2admin** [Azure/aks-engine#856]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**:  v0.25.3

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes, Windows nodes 1709

**What happened**:

Nodes randomly start failing in a few days of use. New pods stop being created on a particular node, with the error being Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "my-pod-648b47bcc-hj8tm_t-1ea5c65c-0824-4d63-8f5f-f8e820322e28" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input

Same deployment succeeds on other nodes.

kubectl get nodes returns node status as "Ready".

Restarting the node doesn't help. Recreating the cluster fixes the issue for a few days, then a random node goes bad again

**What you expected to happen**:

Nodes should be stable

**How to reproduce it** (as minimally and precisely as possible):

Create a cluster with a few Windows nodes, use it with a few pods. One of the nodes will stop creating new pods in a few days.

**Anything else we need to know**:

The node shows no resource stress.

**Comment by wesleyae** [comment]
Still having this issue with v1.0.18 of the azure-vnet-cni plugin with Windows Server 2019. Has there been any movement on this?

**Comment by wesleyae** [comment]
Actually, I think this is the real issue: https://github.com/Azure/azure-container-networking/issues/339
