### ISSUE TITLE
Any best practices for rebooting master node ?

### ISSUE THREAD

**Issue by sampath2121** [Azure/aks-engine#866]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Advisory
---

**What version of aks-engine?**:
---
acs-engine v1.11.5   

**Kubernetes version**:

**What happened**:
Looking to reboot the master node as there are some DNS issues and checking if there are any best practices to reboot it. We understand acs-engine was deprecated and we are in the process of moving to aks-engine. But before that, we want to get our cluster healthy state. 

**What you expected to happen**:
Master node should be restarted without any issues.

**How to reproduce it** (as minimally and precisely as possible):
Restart master node.

**Anything else we need to know**:

**Comment by andyzhangx** [comment]
just reboot the master node VM? any concern?

**Comment by bzuelke** [comment]
In the testing I've been doing lately I needed to edit a config on the master and was able to reboot it and it came back ok. As long as you're not terminating the instance there shouldn't be an issue with it.

**Comment by invidian** [comment]
I also experience issues with rebooting master node. Currently on CoreOS, kubelet does not bring up pods after a reboot. When you restart `kubelet` after booting, pods are showing up, but kube-apiserver fails to start, complaining that `/etc/kubernetes/certs/proxy-ca.crt` file is empty.
