### ISSUE TITLE
AKS-engine generated an invalid arm template

### ISSUE THREAD

**Issue by DavidParks8** [Azure/aks-engine#868]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Issue

**What version of aks-engine?**:
---
0.33.0

**Kubernetes version**:
1.13

**What happened**:
I generated an arm template using aks-engine, then tried to deploy it using the azure cli and received the following error: 

```
* null_resource.deploy-cluster: Error running command 'az group deployment create --name david-westus --resource-group david-westus --template-file ./_output/david-k8s-westus/azuredeploy.json --parameters ./_output/david-k8s-westus/azuredeploy.parameters.json': exit status 1. Output: ERROR: Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template resource 'bcb77dc7-4265-57e9-ae28-2a61a5a610eb' at line '1' and column '58973' is not valid: Unable to parse language expression 'reference(concat('Microsoft.Compute/virtualMachineScaleSets/', variables('linuxpool1VMNamePrefix'), '2017-03-30', 'Full').identity.principalId': expected token 'RightParenthesis' and actual 'EndOfData'.. Please see https://aka.ms/arm-template-expressions for usage details.'.
```

**What you expected to happen**:
I expect the template pass az syntax validation, and deploy.

**How to reproduce it** (as minimally and precisely as possible):
@jackfrancis, please contact me directly and I will give you the repo which is generating the issue.

**Comment by jackfrancis** [comment]
@DavidParks8 Could you build from this PR and validate that this fixes things?

https://github.com/Azure/aks-engine/pull/871

**Comment by jackfrancis** [comment]
Confirmed not yet fixed
