### ISSUE TITLE
Revisit --max-pods default of 30 for Azure CNI

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#87]
Lots of folks running into the 30 upper bound w/ Azure CNI clusters. @rocketraman and @sylus in particular.

Work with @sharmasushant and @tamilmani1989 to identify valid reasons to keep this value low by default.

**Comment by rocketraman** [comment]
I'm still interested in a solution, or at least an explanation.

**Comment by jackfrancis** [comment]
Re-opening for @rocketraman (and others)

**Comment by tamilmani1989** [comment]
My apologies for not noticing this request before. @rocketraman Can you please state your requirements clearly? Why can't you configure number of pods in cluster config while deploying kubernetes cluster?

**Comment by rocketraman** [comment]
@tamilmani1989 The requirement is simple: run more than 30 pods on one node on a cluster using aks-engine. I am already setting the max pods value manually in my cluster config as a kubelet config setting. The question here, though, is why the *default value* is 30 instead of a higher value?

**Comment by sharmasushant** [comment]
There is no reason to keep this value as 30 by default for azure cni. We will submit a PR to get this value changed in aks-engine and on par with non-vnet. @jackfrancis @rocketraman @tamilmani1989

**Comment by jackfrancis** [comment]
Thank you @sharmasushant !
