### ISSUE TITLE
Azure Oss Db Tools Pgbouncer Sidecar

### ISSUE THREAD

**Issue by phroiland** [Azure/aks-engine#889]
**Kubernetes version**:
```

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
**Helm version**:
```

Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

```
**What happened**:
Up until the last few days I had been able to run jobs and deployments just fine with pgbouncer-sidecar and my django application. 

In that time Microsoft Azure has:
1) Dropped acs-engine
2) Moved it to here.
3) Continuous updates on [pgbouncer-sidecar image](https://hub.docker.com/_/microsoft-azure-oss-db-tools-pgbouncer-sidecar)

**What you expected to happen**:
The containers should run and perform django migrations, but it's acting as if the user/db isn't there, or it's pointing to the wrong db.
 ```

2019-03-26 22:18:00.959 1 LOG file descriptor limit: 1048576 (H:1048576), max_client_conn: 100, max fds possible: 110
2019-03-26 22:18:00.959 1 LOG listening on 0.0.0.0:5432
2019-03-26 22:18:00.959 1 LOG listening on ::/5432
2019-03-26 22:18:00.959 1 LOG process up: pgbouncer 1.9.0, libevent 2.1.8-stable (epoll), adns: c-ares 1.14.0, tls: LibreSSL 2.7.4
2019-03-26 22:18:05.824 1 LOG C-0x560a626dbe30: (nodb)/(nouser)@127.0.0.1:50674 registered new auto-database: db=****
2019-03-26 22:18:50.132 1 LOG C-0x560a626dbe30: (nodb)/(nouser)@10.1.0.1:35094 closing because: client unexpected eof (age=0)
2019-03-26 22:19:00.918 1 LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait time 0 us

```

django output:
```
django.db.utils.OperationalError: ERROR:  no such user: ****admin@c****-db
```
...but they are.

`$ psql --host=****-db.postgres.database.azure.com --port=5432 --username=****admin@****-db --dbname=****`
```
Password for user ****admin@****-db:
psql (11.2, server 9.6.10)
SSL connection (protocol: TLSv1.2, cipher: POOPY-RSA-ASS256-GUM-SHAT84, bits: 256, compression: off)
Type "help" for help.
****=> \du
                                              List of roles
    Role name    |                         Attributes                         |         Member of
-----------------+------------------------------------------------------------+---------------------------
 azure_pg_admin  | Cannot login                                               | {}
 azure_superuser | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 ****admin       | Create role, Create DB                                     | {azure_pg_admin}
 ****            | Create role, Create DB                                    +| {azure_pg_admin,****admin}
                 | Password valid until infinity                              |

```
**How to reproduce it** (as minimally and precisely as possible):
Create a deployment with a django-app container and secret/env Azure credentials along with pgbouncer-sidecar container as per https://hub.docker.com/_/microsoft-azure-oss-db-tools-pgbouncer-sidecar.

**Comment by phroiland** [comment]
![Screen Shot 2019-03-28 at 6 39 56 PM](https://user-images.githubusercontent.com/10401786/55197445-fcc9da80-5188-11e9-9176-28d2d962f12e.png)

**Comment by CecileRobertMichon** [comment]
@phroiland sorry to hear you're having a bad experience. The pgbouncer-sidecar image isn't supported by the AKS Engine team but I've reached out to the Azure OSS Database service team to see if they can provide assistance.

If you have any questions about the acs-engine -> aks-engine move after reading https://github.com/Azure/aks-engine/blob/master/docs/faq.md, please let us know.
