### ISSUE TITLE
aks-engine generate an InvalidTemplate

### ISSUE THREAD

**Issue by andyzhangx** [Azure/aks-engine#891]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
master
---

**Kubernetes version**:

**What happened**:
I used following kubernetes.json template, and then run
 - `./aks-engine generate ~/acs/kubernetes-zone-1.13.4.json`
 - after template generation, and then run following command and get the `InvalidTemplate` error
```
$ az group deployment create \
    --name="$CLUSTER_NAME" \
    --resource-group=$RESOURCE_GROUP_NAME \
    --template-file="./_output/$CLUSTER_NAME/azuredeploy.json" \
    --parameters "@./_output/$CLUSTER_NAME/azuredeploy.parameters.json"
Azure Error: InvalidTemplate
Message: Deployment template parse failed: 'Error reading string. Unexpected token: StartArray. Path '[0]'.'.
```

 - The template I used:
```
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.13.4"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "andy-zone1134",
      "vmSize": "Standard_D2s_v3",
      "availabilityZones": [
                "1"
      ]
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool",
        "count": 2,
        "vmSize": "Standard_D2s_v3",
        "storageProfile" : "ManagedDisks",
        "availabilityProfile": "VirtualMachineScaleSets",
        "availabilityZones": [
                "1"
        ]
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa ..."
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "ClientID": "...",
      "Secret": "..."
    }
  }
}

```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
While if I switch to use aks-engine `v0.30.1`, it works well, so I guess it's a regression, current master branch would generate an ARM template that azure ARM could not recognize.

**Comment by CecileRobertMichon** [comment]
@jackfrancis @tariq1890 possibly another template V2 regression?

**Comment by tariq1890** [comment]
Yes. This has been fixed by @jackfrancis

**Comment by CecileRobertMichon** [comment]
@andyzhangx can you please try again with current master or 0.33.1 and confirm that this is fixed?

**Comment by tariq1890** [comment]
In #882
