### ISSUE TITLE
Remove packer user at provisioning with AKS distro

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/aks-engine#899]
packer user is created as part of VHD Packer build process. We delete `/home/packer` during deployments but we don't remove the packer user. We should remove it for consistency.

On a VM built with AKS distro:

`packer:x:1000:1000:Ubuntu:/home/packer:/bin/bash`

**Comment by alexeldeib** [comment]
Is this as simple as changing (making an addition after) [this line](https://github.com/Azure/aks-engine/blob/b45eb042282ba093900af7642491b81aca2e4f72/packer/vhd-image-builder.json#L72) to  `sudo deluser --remove-home packer`? I noticed this on our machines and wanted to clean it up, I'm happy to fix here. Is there automation to validate the vhd builds/how does it work?

**Comment by CecileRobertMichon** [comment]
@alexeldeib correct that should be the only needed change. The `--remove-home` option should take care of removing `/home/packer` so we should even be able to replace that line. The VHD build pipeline runs on every PR that changes that file automatically so it will be easy to validate.
