### ISSUE TITLE
VMAS Availability Zones broken in template refactor V2

### ISSUE THREAD

**Issue by tariq1890** [Azure/aks-engine#902]
This is due to fact that the ARM template generation has moved to a more go-native and strongly-typed method. Relying solely on ARM methods will be more challenging. 

In this case, availability zones are set by using the following ARM method :

"zones": `"[split(string(parameters('availabilityZones')[mod(copyIndex(variables('masterOffset')), length(parameters('availabilityZones')))]), ',')]`

In the current template implementation (which is strongly typed), `"zones"` is of the slice type and can only accept a slice. The current code will not work.

`virtualMachine.Zones = &[]string{
			"split(string(parameters('availabilityZones')[mod(copyIndex(variables('masterOffset')), length(parameters('availabilityZones')))]), ',')",
		}`

**Comment by tariq1890** [comment]
^ Lol

**Comment by CecileRobertMichon** [comment]
@jackfrancis @palma21 we should prioritize fixing this regression.

**Comment by jackfrancis** [comment]
Hmmm, see the current validation code here:

https://github.com/Azure/aks-engine/blob/master/pkg/api/vlabs/validate.go#L458

In fact, availability zones support has never existed for VMAS agent pools. This PR enabled availability zones for VMAS *master* scenarios:

https://github.com/Azure/acs-engine/pull/4286/files

But at no point was it possible to build an AZ-enabled cluster using VMAS agent pools.

@ritazh does the above description match with your view of reality?

**Comment by CecileRobertMichon** [comment]
I think the bug that Tariq is describing above is for VMAS master scenarios, not agent pools.
