### ISSUE TITLE
Only set control plane defaults if masterProfile != nil

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#91]
See:

https://github.com/Azure/aks-engine/blob/master/pkg/api/defaults.go#L232
https://github.com/Azure/aks-engine/blob/master/pkg/api/defaults.go#L236
https://github.com/Azure/aks-engine/blob/master/pkg/api/defaults.go#L240

**Comment by craiglpeters** [comment]
AKS is doing this on their own
