### ISSUE TITLE
Upgrade Fails due to node drain timeout

### ISSUE THREAD

**Issue by mo-saeed** [Azure/aks-engine#930]
Is this a request for help?: NO

Is this an ISSUE or FEATURE REQUEST? (choose one): ISSUE

What version of aks-engine?: v0.33.2

Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm) Kubernetes (upgrade from 1.13.3 to 1.13.5)

What happened: When doing an upgrade, there is now a drain process due to . However, the timeout for the drain is only 1 minute, and this is nowhere near long enough with persistent Azure disks, which take several minutes to drain from a node because they are dang slow to reschedule on other nodes.

The upgrade fails every time due to this timeout 

What you expected to happen:

Drain should not timeout or set an option to increase it.

How to reproduce it (as minimally and precisely as possible):

Create a cluster with a bunch of PVs. Upgrade it.

Anything else we need to know:

**Comment by CecileRobertMichon** [comment]
@jackfrancis here's a repro case for https://github.com/Azure/aks-engine/pull/298

**Comment by mo-saeed** [comment]
The error occurred again today on different cluster with PVC:
`ERRO[0839] Error draining VM in VMSS: Drain did not complete within 1m0s
Error: upgrading cluster: Drain did not complete within 1m0s`
