### ISSUE TITLE
Upgrade fails due to drain node error for VMSS instance with hostnames ending with letters

### ISSUE THREAD

**Issue by mo-saeed** [Azure/aks-engine#935]
**Is this a request for help?**: NO

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

**What version of aks-engine?**: v0.33.2

**Kubernetes version**:
1.13.4

**What happened**:

I got an error trying to upgrade kubernetes version from 1.13.4 to 1.13.5:

`INFO[0971] Draining node k8s-minion-42312186-vmss00000B
ERRO[0971] Error draining VM in VMSS: nodes "k8s-minion-42312186-vmss00000B" not found
Error: upgrading cluster: nodes "k8s-minion-42312186-vmss00000B" not found`

```kubectl get node
NAME                             STATUS   ROLES    AGE  
k8s-master-42312186-0            Ready    master   11h  
k8s-minion-42312186-vmss00000b   Ready    agent    33m  
k8s-minion-42312186-vmss00000c   Ready    agent    29m 
```
It seems that there's an issue with the azure instance names when it ends with Letters "e.g. a or b". in the scalet-set, instance names are ending with UPPERCASE Letters but kubernetes nodes names end with LOWERCASE letters which makes draining nodes not possible.

**What you expected to happen**:
Drain node should be successful regardless instance names in VMSS

**How to reproduce it** (as minimally and precisely as possible):
Upgrade kubernetes cluster with VMSS including instances with names ending with letters not numbers

**Comment by CecileRobertMichon** [comment]
This is an interesting edge case. We usually don't have uppercase letters in VM names (the prefix is always lowercase and the suffix is numbers only). Just curious, did you scale up and down a lot to get to letter indices for your vmss instances?

I think we should be able to fix this easily by adding a `strings.ToLower()` on the VM name before proceeding with the drain and any other kube client operations in the upgrade flow.

**Comment by mo-saeed** [comment]
@CecileRobertMichon Yes due to the load change on this cluster, we had to scale down/up many times and that led to having nodes ending with letters. After index "10" node names will always end with letter.

I hope that will be fixed soon.

Thanks a lot !

**Comment by mo-saeed** [comment]
FYI, this is how computer name is defined in azure scale set:
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-ids#scale-set-vm-computer-name

**Comment by mo-saeed** [comment]
@CecileRobertMichon I would really appreciate if you give an estimation when this issue can be fixed, it's blocker for us now to proceed with upgrade.

Thanks a lot !

**Comment by CecileRobertMichon** [comment]
I've opened #951 to fix it.

**Comment by mo-saeed** [comment]
@CecileRobertMichon Thanks a lot !
