### ISSUE TITLE
Validate k8s PR #71736

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#94]
https://github.com/kubernetes/kubernetes/pull/71736 was merged recently to address metrics-server breakage in 1.10.10, 1.10.11, 1.12.3, and 1.13.0 w/ Azure CNI. Please build a cluster from this PR and validate that metrics-server + Azure CNI functionality is restored.

**Comment by CecileRobertMichon** [comment]
@tariq1890 can this be closed now?

**Comment by tariq1890** [comment]
Yes
