### ISSUE TITLE
GPU-backed agent pools require outbound internet access

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#940]
The current nvidia driver installation/configuration implementation assumes outbound internet access during cluster provisioning. With a little investment we should be able to move all external download dependencies to VHD CI, and have them in the VHD at cluster creation time.

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/aks-engine/pull/897/files#r271078941 for context

**Comment by CecileRobertMichon** [comment]
@jadarsie FYI

**Comment by posix4e** [comment]
That pull request is closed, are we good to close this?

**Comment by CecileRobertMichon** [comment]
@posix4e this issue is still relevant, the PR I linked to was only for context of when this was introduced, it didn't fix the issue.

**Comment by CecileRobertMichon** [comment]
keep open

**Comment by jackfrancis** [comment]
I will test to see if this is still an issue.

**Comment by jackfrancis** [comment]
Still an issue

**Comment by mboersma** [comment]
I'm closing this along with #4684.
