### ISSUE TITLE
How to use kured

### ISSUE THREAD

**Issue by shaikatz** [Azure/aks-engine#956]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
Not-Relevant
---

**Kubernetes version**:
Not-Relevant

**What happened**:
I've tried to use https://github.com/weaveworks/kured as AKS official documentation recommend to use it.
Having VMSS and Cluster-Autoscaler, when kured restart node for security updates 2 things happens:
1. The autoscaler automatically start a new agent to replace the one who is currently on restart.
2. The new node that comes up is outdated from security-updates perspective.

**What you expected to happen**:
Reach a state where my nodes will be security up to date with VMSS and autoscaler.

**Comment by przemolb** [comment]
I am also interested in this topic - does anybody know if VMSS is "compatbile" with kured (or vice versa) ?

**Comment by przemolb** [comment]
Refresh ...

**Comment by sukhong** [comment]
Refreshing.

Does it mean that all new nodes created by cluster-autoscaler will have to restart at least once to reach a stable state?

**Comment by palma21** [comment]
@sukhong @przemolb @shaikatz 

I believe that is the correct behavior.

eg.
2 nodes - patched nightly. Kured will reboot them.
When it does so CA will scale a 3rd node to keep the needed resources in the cluster. the 3rd node will have the same image used to create the cluster, or from the last AKS upgrade operation.
that 3rd node will be patched nightly too and rebooted by kured.


Let me know if you feel it should be different but likely is an aks to be made the kured/ca level.

From AKS-Engine you may also run an aks-engine upgrade that will give all the latest bits to all nodes.

**Comment by kthompson23** [comment]
I don't think Kured can be used reliably with the autoscaler.

This is the current state of our cluster. aks-user1-38485947-vmss00005i was created 29 hours ago and has had patches applied. It is ready for reboot. It is still on an old kernel version; 4.15.0-1083-azure

```
NAME                              STATUS   ROLES   AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-default-38485947-vmss000000   Ready    agent   51d    v1.16.9   10.240.0.4    <none>        Ubuntu 16.04.6 LTS   4.15.0-1091-azure   docker://3.0.10+azure
aks-default-38485947-vmss000001   Ready    agent   51d    v1.16.9   10.240.0.5    <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00004b     Ready    agent   7d7h   v1.16.9   10.240.0.10   <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00004l     Ready    agent   6d8h   v1.16.9   10.240.0.13   <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00005g     Ready    agent   29h    v1.16.9   10.240.0.7    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00005i     Ready    agent   28h    v1.16.9   10.240.0.6    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00006l     Ready    agent   6h9m   v1.16.9   10.240.0.8    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
```

I cordoned, drained, rebooted, and uncordoned aks-user1-38485947-vmss00005i manually.

The autoscaler created two additional nodes (perhaps because users were on the system and there is some additional load).
aks-user1-38485947-vmss00005i is now on the latest kernel 4.15.0-1092-azure

```
NAME                              STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-default-38485947-vmss000000   Ready    agent   51d     v1.16.9   10.240.0.4    <none>        Ubuntu 16.04.6 LTS   4.15.0-1091-azure   docker://3.0.10+azure
aks-default-38485947-vmss000001   Ready    agent   51d     v1.16.9   10.240.0.5    <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00004b     Ready    agent   7d8h    v1.16.9   10.240.0.10   <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00004l     Ready    agent   6d9h    v1.16.9   10.240.0.13   <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00005g     Ready    agent   31h     v1.16.9   10.240.0.7    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00005i     Ready    agent   29h     v1.16.9   10.240.0.6    <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00006l     Ready    agent   7h16m   v1.16.9   10.240.0.8    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00006m     Ready    agent   11m     v1.16.9   10.240.0.9    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00006n     Ready    agent   4m24s   v1.16.9   10.240.0.11   <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
```

After a few minutes the autoscaler destroyed aks-user1-38485947-vmss00005i:

```
NAME                              STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-default-38485947-vmss000000   Ready    agent   51d     v1.16.9   10.240.0.4    <none>        Ubuntu 16.04.6 LTS   4.15.0-1091-azure   docker://3.0.10+azure
aks-default-38485947-vmss000001   Ready    agent   51d     v1.16.9   10.240.0.5    <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00004b     Ready    agent   7d8h    v1.16.9   10.240.0.10   <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00004l     Ready    agent   6d9h    v1.16.9   10.240.0.13   <none>        Ubuntu 16.04.6 LTS   4.15.0-1092-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00005g     Ready    agent   31h     v1.16.9   10.240.0.7    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00006l     Ready    agent   7h23m   v1.16.9   10.240.0.8    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00006m     Ready    agent   17m     v1.16.9   10.240.0.9    <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
aks-user1-38485947-vmss00006n     Ready    agent   10m     v1.16.9   10.240.0.11   <none>        Ubuntu 16.04.6 LTS   4.15.0-1083-azure   docker://3.0.10+azure
```

My updated node is now gone and I have two new nodes running on an old kernel with no patches applied.

**Comment by ericsuhong** [comment]
You may be facing an issue where kured is holding a lock on a destroyed node: https://github.com/weaveworks/kured/issues/137

I am still waiting for kured to fix a bug regarding --annotation-ttl (https://github.com/weaveworks/kured/issues/143)

**Comment by kthompson23** [comment]
@ericsuhong We did run into the issue that annotation-ttl flag is supposed to fix and deployed the latest version of Kured and set the ttl. Thanks for linking issue #143 though, I didn't know there were still problems with it.

In my example above I did everything manually using kubectl but I followed the same flow as Kured; cordon/drain, reboot, and uncordon.
