### ISSUE TITLE
"gofish install aks-engine" fails

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#98]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**What version of aks-engine?**:

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by bacongobbler** [comment]
fixed via https://github.com/fishworks/fish-food/pull/87
