### ISSUE TITLE
CIS 1.5.1 Ensure core dumps are restricted

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#980]
in file `/etc/security/limits.d/CIS.conf`:

```
# CIS Ubuntu Linux 16.04LTS Benchmark v1.0.0
# https://benchmarks.cisecurity.org/tools2/linux/CIS_Ubuntu_Linux_16.04_LTS_Benchmark_v1.0.0.pdf

# 1.5.1 Ensure core dumps are restricted (Scored)

* hard core 0
```

**Comment by jackfrancis** [comment]
@cchildress @jakepearson @weinong @yangl900 Thoughts on whether or not this will impede AKS troubleshooting? Do we regularly take advantage of core dumps to diagnose issues?

Here is a page that describes why the above change is a best-practice security fundamental:

https://secscan.acron.pl/centos7/1/5/1

**Comment by weinong** [comment]
i don't believe so.
